### ISSUE TITLE
Availability of JDK8 for macOS aarch64

### ISSUE THREAD

**Issue by pietrobraione** [adoptium/adoptium-support#1000]
## Question
Will it be available the JDK8 for macOS aarch64? In the negative case, how can I build it from source?

## Context

I have just purchased an Apple M3 pro with Sonoma 14.2.1. I have an important project that is bound to Java 8 and cannot migrate (it is the implementation of a metacircular Java 8 virtual machine), therefore I need a Java 8 setup on my new machine. However I cannot find the macOS aarch64 architecture in the Temurin distributions. Will this architecture be supported? In the positive case, when it will likely be available? In the negative case, can I (and how do I) package by myself a JDK8 for this architecture?

**Comment by karianna** [comment]
The Apple Silicon port has not been back ported to OpenJDK 8 and so we don't built it.  You might want to try Bellsoft or Azul
