### ISSUE TITLE
How do I disable Automatic Updates

### ISSUE THREAD

**Issue by CoopJeff** [adoptium/adoptium-support#1001]
Eclipse Termurin 8.392.8 (Win x64)

Because the JDK automatically updates, and changes it's folder name. It crashes our application each time b/c the folder path no longer exists. 

I would prefer to manually control the updates, rather have them automatically updated. Alternatively, is there a way to have this installed but stored in a generic named folder?

How do i disable automatic updates in the current version of the JDK?

Thanks,

Jeff

**Comment by karianna** [comment]
https://adoptium.net/en-GB/installation/windows/ has our installation instructions and a further link to the MSI installer options.  You need to manually run the4 MSI, not not sure how 'auto-update' is owrking unless you have an IT policy doing so?

**Comment by CoopJeff** [comment]
Hi Martijn,


Thank you for the response. Just to clarify, the adoptium version I'm using does NOT auto update itself? It is updated.manually only?


Thank you,






Get 
Outlook for Android
Jeff Cooper
Director of Information Technology
O: 314-851-6263
M: 720-840-3832
stlouisbank.com


 
 
 
NOTICE: Please be advised that emails to or from Saint Louis Bank and its directors, officers, and employees are not loan commitments and cannot form an agreement to loan money, extend credit, renew loans, or extend
 loans. No discussions, e-mails and other communication between you and Saint Louis Bank shall be considered an agreement to loan money, extend credit, renew loans, or extend loans to you until the terms for credit, renewal or extension are memorialized in
 written loan documents that are approved by bank management and signed by all parties.

STATEMENT OF CONFIDENTIALITY: The information contained in this message may be privileged and confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee
 or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify
 us immediately by replying to the sender. Thank you.

**Comment by karianna** [comment]
My understanding is that we do not autoupdate, you need to manually run the MSI.
