### ISSUE TITLE
Error: An unexpected error occurred while trying to open file /app/app.jar

### ISSUE THREAD

**Issue by homiak** [adoptium/adoptium-support#1005]
### Please provide a brief summary of the bug

We use maven:3-eclipse-temurin-21 image in bitbutcket pipeline to build and package our application image, 
here is the Docker file for our application which is using `eclipse-temurin:21-alpine` image as a base.  

FROM eclipse-temurin:21-alpine
WORKDIR /app
# copy the jar file to /app
ENTRYPOINT ["java"]

CMD [ "-jar", "/app/app.jar"]

Image build in such a way is defunct and fails with  `Error: An unexpected error occurred while trying to open file /app/app.jar` 

It seems like the issue is with the ENTRYPOINT["java"] 
because if I override it like so 

`docker run -ti --entrypoint java app:latest -jar /app/app.jar`

The app works. 

Also setting ENTRYPOINT to full path to java executable also solves the issue 

`ENTRYPOINT["/opt/java/openjdk/bin/java"]`
  
### Did you test with the latest update version?

```Shell
Yes
```

### Please provide steps to reproduce where possible

Run maven:3-eclipse-temurin-21 image and package any executable java application (jar) file using the Dockerfile below: 

FROM eclipse-temurin:21-alpine
WORKDIR /app
# copy the jar file to /app
ENTRYPOINT ["java"]

CMD [ "-jar", "/app/app.jar"]

from inside this image, save the docker image somewhere accessible outside the container. Try to run the resulting image with docker run 

### Expected Results

Packaged Java application would start normally

### Actual Results

docker run app:latest
Error: Unable to access jarfile /app/app.jar

### What Java Version are you using?

whatever is provided in maven:3-eclipse-temurin-21 

### What is your operating system and platform?

maven:3-eclipse-temurin-21 on linux

### How did you install Java?

Java is part of maven:3-eclipse-temurin-21

### Did it work before?

```Shell
Yes, this worked for before, but stopped after eclipse-temurin:21-alpine update yesterday (25 Jan 2024)
```

### Did you test with other Java versions?

```Shell
It works with previous version of eclipse-temurin@sha256:075f8207cbfecf7e509e2d93e2ffc36c097b52a8109a9bfd40326fa12bd5c438 

We suspect that the version of Java in maven:3-eclipse-temurin-21 is also important because I can build the working image just fine locally outside the docker container in Ubuntu with java 21.0.2-tem
```

### Relevant log output

```Shell
Error: Unable to access jarfile /app/app.jar
```

**Comment by homiak** [comment]
The issue was caused by security enforcer not officially supporting alpine based images

**Comment by goodic50** [comment]
> The issue was caused by security enforcer not officially supporting alpine based images

What does it mean?

**Comment by mdevale** [comment]
> The issue was caused by security enforcer not officially supporting alpine based image

I am also facing same issue with latest image. However it's working fine with older image created by few days back with same branch, no any single line of code change

**Comment by goodic50** [comment]
In our k8s cluster, we have Aqua (https://www.aquasec.com/products/container-vulnerability-scanning/). There was an issue with it, but a patch was released a month ago that fixed the problem.
