### ISSUE TITLE
temurin-11-jre and temurin-17-jdk Debian package aren't served properly on JFrog

### ISSUE THREAD

**Issue by hdurand-work** [adoptium/adoptium-support#1006]
Hello,

Same as #1002  (but it was closed)

Since yesterday packages.adoptium.net stopped serving some of the temurin's Debian package.

debmirror's log:

```
Errors:
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 Download of pool/main/t/temurin-11/temurin-11-jre_11.0.22.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
Failed to download files (3 errors)
```

Our firewall doesn't seem to see any problem:

![image](https://github.com/adoptium/temurin/assets/116072998/618e70ac-c6ab-4fe8-a768-4b5d5fbfd21c)

After digging into it, we discovered that the packages aren't visible on JFrog's web UI even though it seems to "know" that they exist

![image](https://github.com/adoptium/temurin/assets/116072998/76b9de97-eb0b-42ac-aa39-a83a89078fee)

![image](https://github.com/adoptium/temurin/assets/116072998/de87a729-4fdf-4f72-92e6-0ff5d47f3b47)

Alpine in comparison:

![image](https://github.com/adoptium/temurin/assets/116072998/15a6b698-7054-4c09-ae50-a466163215c0)

Debian 11 JRE in comparison: 
![image](https://github.com/adoptium/temurin/assets/116072998/dab3c929-4f33-4804-a677-3de136958ce3)

**Comment by karianna** [comment]
https://github.com/adoptium/installer/pull/810 to resolve this

**Comment by steelhead31** [comment]
I also believe these packages should now be being served properly.

**Comment by karianna** [comment]
@hdurand-artic Can you try again and let us know?

**Comment by sxa** [comment]
This is odd. I just performed a quick new test on Debian 12 (bookworm) on x64 and 11-jre installed ok but 17-jdk didn't.
```
Err:1 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-17-jdk amd64 17.0.10.0.0+7
  Error reading from server. Remote end closed connection [IP: 151.101.131.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.131.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@f76153b94ba7:/# wget https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb
--2024-01-26 23:28:26--  https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb
Resolving packages.adoptium.net (packages.adoptium.net)... 151.101.67.42, 151.101.195.42, 151.101.3.42, ...
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.67.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
I tried the install several times with the same results, then paused for a minute or so before trying the `wget` on the URL, which worked, and then after that the `apt install` worked. It does feel somehow cache/proxy related.

**Comment by hdurand-artic** [comment]
@karianna Some errors are still here, including on new packages:

```
Errors:
 Download of pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-11/temurin-11-jre_11.0.22.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-17/temurin-17-jre_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb failed: 500 read timeout
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 Download of pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-8/temurin-8-jre_8.0.402.0.0+6_amd64.deb failed: 500 read timeout
Failed to download files (8 errors)!
```

Some of them are indeed broken in JFrog (but, weirdly enough, not all of them) - for example:

![image](https://github.com/adoptium/adoptium-support/assets/116072998/eb6d869a-9b3e-4403-bede-a5bb89082478)


![image](https://github.com/adoptium/adoptium-support/assets/116072998/8966b9ef-f9f5-4d57-a709-00bafde7bd9d)

**Comment by steelhead31** [comment]
I've checked all of these artifacts ( and re-uploaded them, and checked again! ), and it appears all are present and correct, there may be an issue with the jfrog web UI, when clicking on the location page. but for me at least, it then redirects to the correct artifact when browsing, e.g...  [https://packages.adoptium.net/ui/repos/tree/General/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0+12_amd64.deb](https://packages.adoptium.net/ui/repos/tree/General/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0+12_amd64.deb)   .. Im going to log the issue with the webui with jfrog.. but I've also tested that apt install works for JDKs & JREs for all version and installs the current/latest versions..

**Comment by hdurand-artic** [comment]
I am not sure it's working... it doesn't seem to error out on download, but it does say that there were timeouts... which is weird:

```
Files to download: 568 MiB
[  0%] Getting: pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb... [  0%] Getting: pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb... [  0%] Getting: pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb... [  0%] Getting: pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb... Downloaded 25 kiB in 25s at 1.03 kiB/s.
Everything OK. Moving meta files ...
Cleanup mirror.
All done.
Errors:
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
Failed to download files (4 errors)!
```

**Comment by steelhead31** [comment]
@hdurand-artic  Are you using a mirror repo/proxy or anything of that nature?, also would you mind sharing your repository configurations, and specifically what/how you are downloading the jdks ? .. the read errors appear to be related to debmirror..

**Comment by hdurand-artic** [comment]
@steelhead31 So, we're using debmirror to mirror every adoptium debian packages (amd64 / bullseyes-buster) - and serve them back ourselves internally.

I don't think there's a proxy between our server and your server.

(I'm personally not super familiar with debmirror)

Everything worked before the original issue happened so I really don't think it's on our end.

**Comment by steelhead31** [comment]
I think the cache on the debmirror may need updating, as we had to re-upload some packages following an initial error...

**Comment by hdurand-artic** [comment]
>is it possible for you to try with the debmirror disabled?

It really isn't no, our machines don't have external access if they don't have to

**Comment by steelhead31** [comment]
Yes, it appears there may be an issue on our hosted jfrog server, I've raised an issue with them to investigate, but it looks related to metadata/indexes on the artifactory server itself.  The packages are visible ( and installable via other methods ) . But I think I've exhausted everything I can do.. I'll update this issue when I get an update

**Comment by hdurand-artic** [comment]
@steelhead31 Alright, thank you!

**Comment by steelhead31** [comment]
@pandeyv-del thanks for that information, thats useful to know...

@hdurand-artic Apologies Im still waiting on an update from Jfrog for this issue, I've chased them again this morning.  Can you have a look at the comment above and see if something similar is appropriate for your mirror scripting / environment?

**Comment by hdurand-artic** [comment]
@steelhead31 Hello, do you have any news ?

By the way, here's the debmirror output with debug/verbose enabled (I had to dug a bit recently to understand how debmirror works - after an unrelated issue - so I was able to enable that)

```
Get Translation files ...
Get DEP-11 metadata files ...
Get command-not-found metadata files ...
Files to download: 568 MiB
https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb => [  0%] Getting: pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb...     #** GET https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb ==> 200 OK (4s)
200 OK
read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb => [  0%] Getting: pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb...     #** GET https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb ==> 500 read timeout (3s)
500 read timeout
Download of pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb => [  0%] Getting: pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb...     #** GET https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb ==> 500 read timeout (3s)
500 read timeout
Download of pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb failed: 500 read timeout
https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb => [  0%] Getting: pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb...         #** GET https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb ==> 500 read timeout (3s)
500 read timeout
Download of pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb failed: 500 read timeout
Downloaded 38 kiB in 20s at 1.93 kiB/s.
Everything OK. Moving meta files ...
Moving dists/bullseye/InRelease
Moving dists/bullseye/Release
Moving dists/bullseye/main/binary-all/Packages.gz
Moving dists/bullseye/main/binary-amd64/Packages.gz
Moving dists/bullseye/Release.gpg
Moving dists/buster/InRelease
Moving dists/buster/Release
Moving dists/buster/main/binary-all/Packages.gz
Moving dists/buster/main/binary-amd64/Packages.gz
Moving dists/buster/Release.gpg
Moving dists/bookworm/InRelease
Moving dists/bookworm/Release
Moving dists/bookworm/main/binary-all/Packages.gz
Moving dists/bookworm/main/binary-amd64/Packages.gz
Moving dists/bookworm/Release.gpg
Cleanup mirror.
deleting pool/main/t/temurin-11/temurin-11-jdk_11.0.22.0.0+7_amd64.deb-4017329
All done.
Errors:
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 Download of pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-21/temurin-21-jdk_21.0.2.0.0+13_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb failed: 500 read timeout
Failed to download files (4 errors)!
`````

**Comment by hdurand-artic** [comment]
So it seems to work now.

I also just noticed that  URLs had double "/" "https://packages.adoptium.net/artifactory/deb//pool/main/t/temurin-8/temurin-8-jdk_8.0.402.0.0+6_amd64.deb" , after solving this, it seems to be working consistently... so problem solved? Maybe?

**Comment by steelhead31** [comment]
Thanks for the update, Im still awaiting a response from jfrog... ,so Im guessing the caching issue with broken URLs is now working properly... as far as the packages, Im pretty much stuck until jfrog take a look.. as they manage the repository, and the only option left to me, is to rebuild the repository from scratch.. which I'd like to avoid unless its absolutely necessary.

**Comment by steelhead31** [comment]
I think these issues have now been resolved. Certainly the most recent release packages work correctly.
