### ISSUE TITLE
There is variable name in Packages (temurin-${VERSION})

### ISSUE THREAD

**Issue by andy778** [adoptium/adoptium-support#1007]
### Please provide a brief summary of the bug

In the file https://packages.adoptium.net/artifactory/deb/dists/bookworm/main/binary-amd64/Packages
There is now several entries with ${VERSION} that causes apt upgrade error 

### Expected Results

Update to latest of the 16 branch 

### Actual Results

Failed to download file 

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)

### What is your operating system and platform?

Linux unifi 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux

### How did you install Java?

deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/adoptium.gpg] https://packages.adoptium.net/artifactory/deb bookworm main

### Did it work before?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
Err:1 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-17-jre amd64 17.0.10.0.0+7
  400  Bad Request [IP: 151.101.247.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
```

**Comment by Kai-Hei** [comment]
In file https://packages.adoptium.net/artifactory/deb/dists/bullseye/main/binary-arm64/Packages is

`Filename: pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.2.0.0+13_arm64.deb`

**Comment by andy778** [comment]
Files seems to have been fixed now

**Comment by karianna** [comment]
Yeah we manually replaced the bad packages.  Permanent fix early next week.
