### ISSUE TITLE
MacOS 14.3 M2: Temurin 17.0.10 has problem with starting an Eclipse RCP application

### ISSUE THREAD

**Issue by ivy-lli** [adoptium/adoptium-support#1008]
### Please provide a brief summary of the bug

Since the update to Temurin 17.0.10 (from Temurin 17.0.9), my started Eclipse RCP application shows only an empty screen.

Temurin 17.0.10:
![Screenshot 2024-01-26 at 14 12 02](https://github.com/adoptium/adoptium-support/assets/42733123/0886d040-5dec-4f6e-8f53-301f224f5484)

Temurin 17.0.9:
![Screenshot 2024-01-26 at 14 12 39](https://github.com/adoptium/adoptium-support/assets/42733123/2c9b71ae-e0f9-482f-91d9-8df9be20ea8b)

### Did you test with the latest update version?

```Shell
Yes, I tested it with the latest Temurin 17.0.10 release (installed via homebrew).
```

### Please provide steps to reproduce where possible

1. Install Eclipse RCP 2023-12 (4.30.0) https://www.eclipse.org/downloads/packages/release/2023-12/r/eclipse-ide-rcp-and-rap-developers
2. Create a new RCP application, done as described here: https://www.vogella.com/tutorials/EclipseRCP/article.html#generatetemplatewithcontent
3. Add Temurin 17.0.10 to Eclipse
  - Open Preferences
  - Java > Installed JREs
  - Add...
  - Select it
  - Apply
4. Start the Eclipse application as described in the tutorial (Step 2) 
  -> Empty application
5. Close the Eclipse application
6. Add Temurin 17.0.9 to Eclipse
  - Same as step 3
7. Make sure the Eclipse application uses Temurin 17.0.9
  - Run
  - Run configurations...
  - Choose our Eclipse Application
  - Java Runtime Environment 
  - Runtime JRE: select Temurin 17.0.9
  - Apply
8. Start the Eclipse application 
  -> Application with sample content

I can also provide the workspace via a GitHub repo, but it is really not more than the wizard for new RCP Applications created.

### Expected Results

The Eclipse Application should show the same content as with Temurin 17.0.9.

### Actual Results

The Eclipse Application showed an empty screen with Temurin 17.0.10.

### What Java Version are you using?

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7) OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)

### What is your operating system and platform?

OS: MacOS Sonoma 14.3
Platform: MacBook Pro M2, 2023

### How did you install Java?

Homebrew

### Did it work before?

```Shell
Yes it worked with Temurin 17.0.9.
I made an update via Homebrew.

Java itself seems to work with Temurin 17.0.10 only the Eclipse RCP application has problem or maybe it has something to do with SWT?
```

### Did you test with other Java versions?

```Shell
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
```

**Comment by karianna** [comment]
@ivy-lli - This might be a Eclipse RCP bug (they call out to SWT/native code).  Have you reported this to them?  Are there any other messages in the Eclipse IDE log files?

**Comment by ivy-lli** [comment]
Yes of course that is possible too. I thought as this appears when I change the temurin version it is more likely a bug here, but I'm not sure.
Sadly I didn't see any errors in the system output or a log file.
Should I open an issue on the [eclipse swt platform](https://github.com/eclipse-platform/eclipse.platform.swt/issues) too?

**Comment by karianna** [comment]
> Yes of course that is possible too. I thought as this appears when I change the temurin version it is more likely a bug here, but I'm not sure. Sadly I didn't see any errors in the system output or a log file. Should I open an issue on the [eclipse swt platform](https://github.com/eclipse-platform/eclipse.platform.swt/issues) too?

Yes please and they'll come back to us if it's a Temurin crasher.

**Comment by Phillipus** [comment]
I am getting the exact same problem. https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012

**Comment by Phillipus** [comment]
I think the difference is that the `java` binary in latest Temurin is built using macOS SDK 14, previous versions were built using SDK 11 (`vtool -show bin/java` will show this).

**Comment by karianna** [comment]
Could well be that its expecting a new API path/call?  I'm not familair with Mac OS X changes in this space. https://bugs.openjdk.org/issues/?jql=text%20~%20macos14%20ORDER%20BY%20updated%20DESC might also be worth scanning (recent issues against macosx14)

**Comment by Phillipus** [comment]
This has got nothing to do with the JDK, only that Eclipse SWT is not handling using a later macOS SDK (14) on the `java` binary. The same is true if Eclipse is launched with its own launcher binary when that is compiled with macOS SDK 14. See my comments [here](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012#issuecomment-1915168980).

**Comment by karianna** [comment]
@Phillipus Thanks, I'll close this for now.
