### ISSUE TITLE
Downgrading MacOS Arm doesn't work from jdk-17.0.10+7 to jdk-17.0.9+9

### ISSUE THREAD

**Issue by FlorianKirmaier** [adoptium/adoptium-support#1009]
**What are you trying to do?**
Trying to downgrade from jdk-17.0.10+7 to jdk-17.0.9+9
(On Mac Arm, installing JDK arm.)
Verified on two different Laptops

**Expected behavior:**
Afterward installing 17.0.9, the following should inform me, that 17.0.9 is installed:
```
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -version
```

**Observed behavior:**
The version 17.0.10 is still installed.

**Any other comments:**
Probably every case of downgrading doesn't work - but I haven't done more detailed tests.

**Comment by FlorianKirmaier** [comment]
I tried out some more.
Downgrading from 17.0.9 to 17.0.8 and 21.0.2 to 21.0.1 has the same issue.

**How am I downgrading?**
I download an installer of the desired version and basically click through the installer with "next" all the time until the installer is finished.

**Comment by karianna** [comment]
Ah thansk, that helps.  As a workaround I ca only suggest you remove the folder or use our tar.gz installers and place in a different folder.  Suspect this will take some time to unravel.

**Comment by karianna** [comment]
Going to close this as won't fix.  Brew and default Mac OS X packaging expects you to remove the N before installing N-1
