### ISSUE TITLE
[libjvm.dylib+0x3f4dbc]  G1MergeHeapRootsTask::work(unsigned int)+0x548 - jvm crash

### ISSUE THREAD

**Issue by zdenek-jonas** [adoptium/adoptium-support#1015]
### Please provide a brief summary of the bug

We are developers of Eclipse Store framework. From JDK version 21.0.2 we have problem with jvm crash. 

In hs_err file, which is in this case sporadically created is: 

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000102084dbc, pid=87449, tid=33027
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.2+13 (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (21.0.2+13-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x3f4dbc]  G1MergeHeapRootsTask::work(unsigned int)+0x548
```

[hs_err_pid87449.log](https://github.com/adoptium/adoptium-support/files/14124959/hs_err_pid87449.log)

Unfortunately i do not have more information for you now. I can see some changes in GC jdk files between version 21.0.1 and 21.0.2
The same procedure with ZGC works fine.

I would like to please you to check this error file even if i do not have another reusable code for you. I can build a simple project with our framework, but i am not sure if somebody will want it. 

### Did you test with the latest update version?

```Shell
Yes, i use Temurin 21.0.2

We are tested this framework continuously from version 11.
```

### Expected Results

Just works, no jvm crash

### Actual Results

Jvm crash

### What Java Version are you using?

openjdk version "21.0.2" 2024-01-16 LTS

### What is your operating system and platform?

MacOS

### Did it work before?

```Shell
Yes, first problem from java 8
```

### Relevant log output

```Shell
Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8325173

**Comment by jerboaa** [comment]
This was caused by: https://github.com/eclipse-serializer/serializer/issues/102
