### ISSUE TITLE
Javac Error with Collectors.toMap() : reference to method is ambiguous, both Map and List match

### ISSUE THREAD

**Issue by meldorq** [adoptium/adoptium-support#1020]
### Please provide a brief summary of the bug

The included class (see below) doesn't compile.

The error message is:
`javac ListVsMap.java 
ListVsMap.java:11: error: reference to set is ambiguous
        set(List.of("foo", "bar", "baz")
        ^
  both method set(Map<String,String>) in ListVsMap and method set(List<String>) in ListVsMap match
1 error`

The internal compiler of Eclipse, however, doesn't seem to mind, and compiles and runs the code.

I don't know if this is a bug in either Adoptium or Eclipse, or if the compilers are free to decide whether this code is compilable.

I believe the code should be compilable, because the return type of collect() here is HashMap, which doesn't extend List.

```
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ListVsMap {

    public static void main(String[] args) {

        // does not compile
        set(List.of("foo", "bar", "baz")
                .stream()
                .collect(Collectors.toMap(
                        l -> l,
                        l -> l,
                        (x, y) -> y,
                        HashMap::new)));

        // compiles
        set(List.of("foo", "bar", "baz")
                .stream()
                .collect(Collectors.toMap(
                        l -> l,
                        l -> l,
                        (x, y) -> y,
                        () -> new HashMap<>())));

        // compiles
        set(List.of("foo", "bar", "baz")
                .stream()
                .collect(Collectors.toMap(
                        l -> l,
                        l -> l,
                        (x, y) -> y)));

        // compiles
        var temp = List.of("foo", "bar", "baz")
                      .stream()
                      .collect(Collectors.toMap(
                              l -> l,
                              l -> l,
                              (x, y) -> y,
                              HashMap::new));

        set(temp);

    }

    public static void set(Map<String, String> valueMap) {
        // empty
    }

    public static void set(List<String> values) {
        // empty
    }
}

```

### Did you test with the latest update version?

```Shell
Tested with the latest javac (21.0.2+13 and 17.0.10+7).
```

### Please provide steps to reproduce where possible

javac ListVsMap.java

### Expected Results

Code compiles without error.

### Actual Results

Compiler terminates with error message:

`ListVsMap.java:11: error: reference to set is ambiguous
        set(List.of("foo", "bar", "baz")
        ^
  both method set(Map<String,String>) in ListVsMap and method set(List<String>) in ListVsMap match
1 error`

### What Java Version are you using?

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04.3 LTS on x86-64

### Did you test with other Java versions?

```Shell
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```

**Comment by karianna** [comment]
This is a question for the compiler-dev mailing list over at openjdk.org
