### ISSUE TITLE
DBeaver Crashes When Clicking Outside Window on Multi-Screen Setup

### ISSUE THREAD

**Issue by Aristevao** [adoptium/adoptium-support#1021]
### Please provide a brief summary of the bug

I have encountered a recurring issue while working with DBeaver on a dual-screen setup, comprising a notebook and a second screen. The problem arises when I am actively working within the DBeaver window and subsequently click anywhere on the second screen or vice versa. Invariably, this action triggers a crash of the DBeaver application.

Notably, the issue persists even during the app's startup phase, exacerbating the inconvenience. This behavior has been consistent across multiple versions, including the latest release, as well as several preceding versions that I've tested.

### Did you test with the latest update version?

```Shell
Yes.
```

### Please provide steps to reproduce where possible

Launch DBeaver on a dual-screen setup.
Click within the DBeaver window.
Click anywhere on the second screen or vice versa.

### Expected Results

Normal functioning without any crashes or disruptions when interacting with different screens while the DBeaver application is active.

### Actual Results

DBeaver crashes every time there is an interaction between the DBeaver window and the second screen, leading to a disruption in workflow.

### What Java Version are you using?

java 11.0.17 2022-10-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)

### What is your operating system and platform?

Windows 10

### How did you install Java?

zip

### Did it work before?

```Shell
It worked several months ago.
```

**Comment by karianna** [comment]
Please use 11.0.22 and send us a crash log if it happens again.

**Comment by Aristevao** [comment]
> Please use 11.0.22 and send us a crash log if it happens again.

@karianna, I couldn't find the version 11.0.22 in DBeaver [Archive Files](https://dbeaver.io/files/).

**Comment by Aristevao** [comment]
Thanks, @karianna . I updated to `java 17.0.6 2023-01-17 LTS` and the problem ceased, at least for now.

**Comment by karianna** [comment]
Please do move to the latest Java 17 to stay on top of other security and stability bugs, but great to hear!

**Comment by Aristevao** [comment]
I updated to the latest available version of Java `17.0.11 2024-04-16 LTS` and the problem continues. Are there other approaches to solving this?

**Comment by karianna** [comment]
@Aristevao Have you contacted the DBeaver folks?  Are there any crash logs you can share?

**Comment by karianna** [comment]
You need to submit a bug at: https://github.com/dbeaver/dbeaver
