### ISSUE TITLE
Runelite crashing

### ISSUE THREAD

**Issue by JoeeP1** [adoptium/adoptium-support#1023]
### Please provide a brief summary of the bug

Idk how relevant this is but in my crash logs I was provided with this forum and I'm really stuck on how to solve it as the few things I tried haven't helped at all.

My client will randomly crash with no error message or indication that it is about to crash.
I think I have a relatively decent PC so I don't think that should be the issue but would be good to know if so in order to get it fixed. 

I have attached my crash log if that is any help but I have no idea how to read it:

**https://pastebin.com/vfyqP4iF**

### Expected Results

The client should run without crashing normally 

### Actual Results

The client crashes.
Last year I had 4 crash reports.
This week I have had 7 without any changes that I can tell. 

### What Java Version are you using?

OpenJDK 64-Bit Server VM Temurin-11.0.22+7

### What is your operating system and platform?

Windows 10

**Comment by karianna** [comment]
It looks a bit like a memory corruption.  Have you reported this to Runescape?  I assume you're on the latest version, graphics drivers and patched windows OS?

**Comment by JoeeP1** [comment]
Thank you for the response! 

Yeah the first thing I did was update OS and drivers, the client updates weekly so I assume that is also the latest update.
Runescape support is beyond useless so I wouldn't even know who to report it to if I'm honest.. 

I will try to google solutions for memory corruption and see if it can be fixed

**Comment by karianna** [comment]
OK, one thing to try is to download and install the previous version of Java you had, if less crashes that helps us narrow it down

**Comment by JoeeP1** [comment]
I'm not sure if I'm being an idiot or not.. Is it possible I don't have java installed at all? 
https://i.imgur.com/hkk3E0S.png

**Comment by eddyscanlan** [comment]
> It looks a bit like a memory corruption. Have you reported this to Runescape? I assume you're on the latest version, graphics drivers and patched windows OS?

Runelite is separate from Runescape. Runelite is an approved client to run Oldschool Runescape.

**Comment by JoeeP1** [comment]
I joined the Runelite discord and they told me to turn off Core Performance Boost in my BIOS and it has been 24 hours without a crash after previously crashing everyday. 
I would suggest giving that a try if you are having the issue but I lost 50-100 FPS on games like CS2 and Valorant so there is a trade off.

**Comment by karianna** [comment]
Thanks, unfortunately this is a native crash that just happens to propagate back through Java (which is why you see a Java 'crash').
