### ISSUE TITLE
Fatal: Read Error: Could not read or parse the JNLP file at....

### ISSUE THREAD

**Issue by leandrobotelholins** [adoptium/adoptium-support#1024]
### Please provide a brief summary of the bug

Waiting for exception dialog to be closed
Exiting Boot.mainWithReturnCode() with 1
failed to launch
netx: Read Error: Could not read or parse the JNLP file at 'file:/C:/Users/leandro.botelho/Downloads/des.jnlp'. (Only one application-desc element allowed per JNLP file.)
HandleLaunchError Sbow BasicExceptionDialog Fatal: Read Error: Could not read or parse the JNLP file at 'file:/C:/Users/leandro.botelho/Downloads/des.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
good - your JRE - 1.8.0_392 - match requested JRE - 1.6.0_21+
Acceptable vendor tag found, contains: Prefeitura Municipal de Belo Horizonte
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
Using MalformedXMLParser
Download done. Shutting down executor
Resource is not cacheable: des.jnlp
Create resource for 'file:/C:/Users/leandro.botelho/Downloads/des.jnlp'
JNLP file location: C:\Users\leandro.botelho\Downloads\des.jnlp
Proceeding with jnlp
End JNLPRuntime.initialize()
Finished Proxy Selector
Proxy disabled ( registry value 'ProxyEnable'). Will use direct proxy.
Windows based proxy created
Selected ProxyProvider : OPERATION_SYSTEM
Start Proxy Selector
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts, found successful pass = true
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts exists.
unlockKeyStore: Operating Keystore Unknown
unlockKeyStore: For file Unknown, found successful pass = false
Loading Keystore Unknown
Keystore file c:\program files\openwebstart\jre\lib\security\trusted.clientcerts does not exists.
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.cacerts
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.cacerts
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.cacerts, found successful pass = false
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.cacerts
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.cacerts exists.
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecacerts
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecacerts
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecacerts, found successful pass = false
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecacerts
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecacerts exists.
unlockKeyStore: Store successful pass for file C:\Program Files\OpenWebStart\jre\lib\security\cacerts
unlockKeyStore: Operating Keystore C:\Program Files\OpenWebStart\jre\lib\security\cacerts
unlockKeyStore: For file C:\Program Files\OpenWebStart\jre\lib\security\cacerts, found successful pass = false
Loading Keystore c:\program files\openwebstart\jre\lib\security\cacerts
Keystore file c:\program files\openwebstart\jre\lib\security\cacerts exists.
unlockKeyStore: Operating Keystore Unknown
unlockKeyStore: For file Unknown, found successful pass = false
Loading Keystore Unknown
Keystore file c:\program files\openwebstart\jre\lib\security\jssecacerts does not exists.
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.certs
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.certs
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.certs, found successful pass = false
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.certs
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.certs exists.
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecerts
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecerts
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecerts, found successful pass = false
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecerts
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.jssecerts exists.
unlockKeyStore: Operating Keystore Unknown
unlockKeyStore: For file Unknown, found successful pass = false
Loading Keystore Unknown
Keystore file c:\program files\openwebstart\jre\lib\security\trusted.certs does not exists.
unlockKeyStore: Operating Keystore Unknown
unlockKeyStore: For file Unknown, found successful pass = false
Loading Keystore Unknown
Keystore file c:\program files\openwebstart\jre\lib\security\trusted.jssecerts does not exists.
unlockKeyStore: Operating Keystore Unknown
unlockKeyStore: For file Unknown, found successful pass = false
unlockKeyStore: Store successful pass for file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
unlockKeyStore: Operating Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
unlockKeyStore: For file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts, found successful pass = false
Loading Keystore C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts
Keystore file C:\Users\leandro.botelho\.config\icedtea-web\security\trusted.clientcerts exists.
Starting security dialog thread
Started Security Thread
Finished get JavaPolicy
End getPolicyFromUrl()
End Policy.getInstance(file://C:/Users/leandro.botelho/.config/icedtea-web/security/java.policy)
Start Policy.getInstance(file://C:/Users/leandro.botelho/.config/icedtea-web/security/java.policy)
Begin getPolicyFromUrl(file://C:\Users\leandro.botelho\.config\icedtea-web\security\java.policy)
End getPolicyFromUrl()
Begin getPolicyFromUrl(null)
Start get JavaPolicy
Begin JNLPRuntime.initialize()
using com.openwebstart.extensionpoint.OwsExtensionPoint extension point
Java Runtime Temurin-1.8.0_392
OS: Windows 10
OpenWebStartLauncher called with args: [C:\Users\leandro.botelho\Downloads\des.jnlp].
Calling ITW Boot with args [C:\Users\leandro.botelho\Downloads\des.jnlp].
Error in possible update process
Checking for update on server https://download-openwebstart.com/updates/updates.xml
RelevantJavawsArgs: '[C:\Users\leandro.botelho\Downloads\des.jnlp]'
Checking if installation time (1707331342705) is after last initial config time (1707331351183)
Setting download indicator to com.openwebstart.download.ApplicationDownloadIndicator@566776ad
Trying to set download indicator
End DeploymentConfiguration.load()
Loading USER level properties from: file:/C:/Users/leandro.botelho/.config/icedtea-web/deployment.properties
End DeploymentConfiguration.load()
Loading USER level properties from: file:/C:/Users/leandro.botelho/.config/icedtea-web/deployment.properties
Start DeploymentConfiguration.load()
Ico provider registered correctly.
Start DeploymentConfiguration.load()
Ico provider registered correctly.
Starting OpenWebStart 1.9.1
OWS main args [C:\Users\leandro.botelho\Downloads\des.jnlp].
init logger factory to net.sourceforge.jnlp.util.logging.OutputControllerLoggerFactory@deb6432

### Did you test with the latest update version?

```Shell
OpenJDK8U-jre_x64_windows_hotspot_8u402b06.msi
icedtea-web-1.8.8.msi
```

### Please provide steps to reproduce where possible

To open software: des.jnlp
http://www.pbh.gov.br/bhissdigital/portal/print.php?content=des/instalacao.php

### Expected Results

Open software Web Start.

### Actual Results

Error.

### What Java Version are you using?

OpenWebStart_windows-x64_1_9_1.exe

### What is your operating system and platform?

Windows 10 Pro 64x.

### How did you install Java?

.exe / .msi

**Comment by karianna** [comment]
@hendrikebbers - This looks like an OpenWebStart issue?

**Comment by leandrobotelholins** [comment]
Yes.

Em sex., 16 de fev. de 2024 às 21:01, Martijn Verburg <
***@***.***> escreveu:

**Comment by karianna** [comment]
@leandrobotelholins Does the latest 1.8.0_412 + ITW 1.8.9 work for you?
