### ISSUE TITLE
Compact record constructor is missing generic type info on parameters

### ISSUE THREAD

**Issue by prdoyle** [adoptium/adoptium-support#1025]
### Please provide a brief summary of the bug

If a compact constructor is added to a record, that record's reflective `Constructor` object loses the generic type info on its `Parameter` objects.

### Did you test with the latest update version?

```Shell
Tested with 21.0.2.
```

### Please provide steps to reproduce where possible

```
import java.lang.reflect.Type;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RecordParameterTest {
	public static List<String> fieldWithExpectedType;
	public static Type expected;

	@BeforeAll
	static void determineExpectedType() throws NoSuchFieldException {
		expected = RecordParameterTest.class.getField("fieldWithExpectedType").getGenericType();
	}

	record ImplicitConstructor(List<String> arg){}

	record CompactConstructor(List<String> arg) {
		CompactConstructor { }
	}

	record CanonicalConstructor(List<String> arg) {
		CanonicalConstructor(List<String> arg) {
			this.arg = arg;
		}
	}

	@Test
	void implicit() {
		assertEquals(expected, firstConstructorParameterType(ImplicitConstructor.class));
	}

	@Test
	void compact() {
		assertEquals(expected, firstConstructorParameterType(CompactConstructor.class));
	}

	@Test
	void canonical() {
		assertEquals(expected, firstConstructorParameterType(CanonicalConstructor.class));
	}

	static Type firstConstructorParameterType(Class<?> c) {
		return c.getDeclaredConstructors()[0].getParameters()[0].getParameterizedType();
	}
}
```

### Expected Results

All tests pass

### Actual Results

`compact` fails. The other tests pass.

### What Java Version are you using?

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### What is your operating system and platform?

Windows 11 on x86-64

**Comment by karianna** [comment]
This is something to raise at the OpenJDK project itself.  I recommend posting to https://mail.openjdk.org/mailman/listinfo/amber-dev

**Comment by prdoyle** [comment]
@karianna I didn't get any replies on the Project Amber mailing list. (Message [here](https://mail.openjdk.org/pipermail/amber-dev/2024-February/008608.html).) Is there perhaps a better place to report bugs?

**Comment by karianna** [comment]
I'd recommend nudging that thread and asking where they'd like a bug report.

**Comment by prdoyle** [comment]
Submitted a bug report to bugs.java.com. The internal review ID is 9076928.

**Comment by karianna** [comment]
I've reopened it, you can track at https://bugs.openjdk.org/browse/JDK-8331026

**Comment by prdoyle** [comment]
Turns out there's another bug here: https://bugs.openjdk.org/browse/JDK-8320575

And a fix on the way here: https://github.com/openjdk/jdk/pull/17070
