### ISSUE TITLE
Fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by anwarim** [adoptium/adoptium-support#1027]
## Question

**is this issue already known?** 

 --
A fatal error has been detected by the Java Runtime Environment:
 
   SIGSEGV (0xb) at pc=0x00007f8e1fffb67c, pid=7, tid=12
 
  JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
  Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, shenandoah gc, linux-amd64)
  Problematic frame:
  V  [libjvm.so+0xd3a67c]  ShenandoahMark::count_liveness(unsigned short*, oopDesc*) [clone .isra.0]+0x28c
 
  Core dump will be written. Default location: /usr/local/epa/core.7
  
  An error report file with more information is saved as:
  /usr/local/epa/hs_err_pid7.log
 
  If you would like to submit a bug report, please visit:
    https://github.com/adoptium/adoptium-support/issues
 
Aborted (core dumped)

**Comment by viken29** [comment]
Hi,

I have a similar error. See please the log below :

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff3e5937c78, pid=4140, tid=4141
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0xcc78]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/ps3/core.4140)

---------------  T H R E A D  ---------------

Current thread (0x00007ff3dc028eb0):  JavaThread "main" [_thread_in_native, id=4141, stack(0x00007ff3e5a19000,0x00007ff3e5b1a000)]

Stack: [0x00007ff3e5a19000,0x00007ff3e5b1a000],  sp=0x00007ff3e5b15560,  free space=1009k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ld-linux-x86-64.so.2+0xcc78]
C  [ld-linux-x86-64.so.2+0x1525d]

**Comment by karianna** [comment]
You both need to upgrade to the latest Java 17.0.11 from adoptium.net

**Comment by viken29** [comment]
Hi thank you for your response.

I'm searching on your site adoptium.net but i didn't find the latest Java 17.0.11. The latest find is [17.0.10+7].

Could you please give me the direct link.

Thanks in adavance

**Comment by anwarim** [comment]
@karianna there are just some beta versions! is there any release for 17.0.11 ?!

https://github.com/adoptium/temurin17-binaries/releases?q=17.0.11&expanded=true

**Comment by karianna** [comment]
Sorry I meant 17.0.10
