### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by neodymius** [adoptium/adoptium-support#1029]
### Please provide a brief summary of the bug

![Screenshot 2024-02-20 182423](https://github.com/adoptium/adoptium-support/assets/67477530/f39f46ca-586a-4be3-8cab-f7dd1fe002dc)

I'm not sure what the error is, im using the latests version. 

### Expected Results

just for the game to work, was abit worried as the command page was open and just running in the background but i assume that's normal right?

### Actual Results

i ran the mikorouge.bak file then played for a while then it crashed

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-23+7-202401260130 (23.0+7) (build 23-beta+7-ea)

### What is your operating system and platform?

Windows 11

### How did you install Java?

as instructed

**Comment by karianna** [comment]
23 is a beta build that is not supported until it goes GA.   Recommend you use latest 21.0.2 LTS
