### ISSUE TITLE
Getting fatal error while deploying the app

### ISSUE THREAD

**Issue by seenuusa455** [adoptium/adoptium-support#1032]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:       
		 
SIGSEGV (0xb) at pc=0x00007fd31e91b0e4, pid=1, tid=23                 
		 
JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)             
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)         
Problematic frame:                       
V  [libjvm.so+0xb8a0e4]  markWord::displaced_mark_helper() const+0x14                                
		 
Core dump will be written. Default location: //core.1                  
		 
An error report file with more information is saved as:                
/tmp/hs_err_pid1.log                     
		 
If you would like to submit a bug report, please visit:                
https://github.com/adoptium/adoptium-support/issues                  

### Did you test with the latest update version?

```Shell
no
```

### Expected Results

Started seeing errors while deploying a Springboot app with alpine base docker image

### Actual Results

App is not able to deploy and going into crash loop with above mentioned JVM error

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7) 

### What is your operating system and platform?

linux-amd64

### How did you install Java?

its a docker image trying to deploy on AWS EKS

### Did it work before?

```Shell
yes, it was working fine since few days
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
A fatal error has been detected by the Java Runtime Environment:       
		 
SIGSEGV (0xb) at pc=0x00007fd31e91b0e4, pid=1, tid=23                 
		 
JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)             
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)         
Problematic frame:                       
V  [libjvm.so+0xb8a0e4]  markWord::displaced_mark_helper() const+0x14                                
		 
Core dump will be written. Default location: //core.1                  
		 
An error report file with more information is saved as:                
/tmp/hs_err_pid1.log                     
		 
If you would like to submit a bug report, please visit:                
https://github.com/adoptium/adoptium-support/issues
```

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8313658 could be related

**Comment by karianna** [comment]
@seenuusa455 can you try with 17.0.12 and see if the issue has been resolved?

**Comment by marlramirez-clgx** [comment]
Hello, I'm facing the same issue with `17.0.12+10`


`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007b84c294dd1b, pid=1, tid=89
#
# JRE version: OpenJDK Runtime Environment (17.0.12+10) (build 17.0.12+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM (17.0.12+10-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xb8dd1b]  markWord::displaced_mark_helper() const+0xb
#
# Core dump will be written. Default location: /core.%e.1.%t
#
# An error report file with more information is saved as:
# /home/vcap/app/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bell-sw.com/support
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007b84c3410a10]`

**Comment by seenuusa455** [comment]
Hi @marlramirez-clgx,
I added below command to my Dockerfile to fix the issue
`RUN apk add --no-cache gcompat`

This  installs the gcompat package in the Alpine image. gcompat is a compatibility layer that provides some of the glibc functionalities in musl-based systems like Alpine. Without this, certain functions that the JVM relies on (like the one in the error trace) can cause a segmentation fault.

**Comment by karianna** [comment]
Ah OK, were you using the Alpine JDK builds?  https://adoptium.net/en-GB/temurin/releases/?os=alpine-linux&version=17
