### ISSUE TITLE
Wrong timezone offset for Asia/Almaty

### ISSUE THREAD

**Issue by marko-asplund** [adoptium/adoptium-support#1037]
### Please provide a brief summary of the bug

Kazakhstan Almaty timezone was changed on 2024-03-01 to +05:00.
For more info see https://www.timeanddate.com/time/zone/kazakstan/almaty

See also OpenJDK bug report [JDK-8325150](https://bugs.openjdk.org/browse/JDK-8325150)

### Did you test with the latest update version?

```Shell
yes
```

### Please provide steps to reproduce where possible

java.util.TimeZone.getTimeZone("Asia/Almaty").getRawOffset()/(1000*60*60)

### Expected Results

jshell> java.util.TimeZone.getTimeZone("Asia/Almaty").getRawOffset()/(1000*60*60)
$1 ==> 5

### Actual Results

jshell> java.util.TimeZone.getTimeZone("Asia/Almaty").getRawOffset()/(1000*60*60)
$1 ==> 6

### What Java Version are you using?

openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7) OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)

### What is your operating system and platform?

macOS on M1

### How did you install Java?

sdkman

### Did it work before?

```Shell
no
```

**Comment by jerboaa** [comment]
This will be fixed with the `17.0.11` release in April.
