### ISSUE TITLE
Temurin 21.0.2 crashed when connecting to Firestore using "com.google.firebase:firebase-admin:9.2.0"

### ISSUE THREAD

**Issue by at9pm** [adoptium/adoptium-support#1038]
### Please provide a brief summary of the bug

When using eclipse-temurin:21-jdk-alpine (21.0.2), connection to FIreStore will fail with "com.google.firebase:firebase-admin:9.2.0". It is not the dependency issue as I tested openjdk:21-slim (21.0.2) is working.

### Expected Results

After creating a FireStore bean with "com.google.firebase:firebase-admin:9.2.0", it should not crash, just like it works when using OpenJDK.

### Actual Results

I was using OpenJDK 21.0.2 locally with below code to get a FirestoreClient,  which work fine.
```
import com.google.cloud.firestore.Firestore;
import com.google.firebase.cloud.FirestoreClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;

@Configuration
@DependsOn("firebaseInitializer")
public class FirestoreConfig {

    @Bean
    public Firestore getDatabase() {
        return FirestoreClient.getFirestore();
    }
}

```
However, when I deploy it to GKE with base image eclipse-temurin:21-jdk-alpine, it fails after app startup with below error. I tried to obtain the dump but couldn't find in the specified location /opt/app/hs_err_pid1.log. I am sorry that there is no any application error log, and this is the only thing I have got.

```
# A fatal error has been detected by the Java Runtime Environment:
#  SIGSEGV (0xb) at pc=0x00000000000207d6, pid=1, tid=7
# JRE version: OpenJDK Runtime Environment Temurin-21.0.2+13 (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libio_grpc_netty_shaded_netty_tcnative_linux_x86_645642903622730458719.so+0x29193]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0x7b3
# Core dump will be written. Default location: /core.%e.1.%t
# An error report file with more information is saved as:
# /opt/app/hs_err_pid1.log
[102.492s][warning][os] Loading hsdis library failed
# The crash happened outside the Java Virtual Machine in native code.

```
However, I can confirm that it is due to Temurin 21.0.2 issue as it works after I deploy my app with base image openjdk:21-slim. I can also confirm that it is due to the use of Firestore in com.google.firebase:firebase-admin:9.2.0, as I tried to comment out the code and then it works. What my guess is some gRPC connection between Firestore making this error.

### What Java Version are you using?

21.0.2

### What is your operating system and platform?

Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)

**Comment by karianna** [comment]
You'll need to contact the netty authors (their native code operates differently on Alpine is my guess).

Note the error message:

_# C  [libio_grpc_netty_shaded_netty_tcnative_linux_x86_645642903622730458719.so+0x29193]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0x7b3
# Core dump will be written. Default location: /core.%e.1.%t
# An error report file with more information is saved as:
# /opt/app/hs_err_pid1.log_
