### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by carvermon** [adoptium/adoptium-support#1042]
Hi. A program I have indicated that I needed Java to run it, and presented your site address to download it. I did so, but the program would still not run, so I downloaded Java from the Java page and now it works. My question is - where is your program on my computer (iMac/OS 10.13.6) and how can I uninstall it? I can find nothing in a search for Adoptium, Temurin, or the version apparently installed (JDK-21.0.2-13) on my drive.

Thank you for any info.

**Comment by karianna** [comment]
@carvermon You should find the installation at: `/Library/Java/JavaVirtualMachines/temurin-21.jdk/`

**Comment by carvermon** [comment]
Thank you.
