### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by mohammad-mursalin** [adoptium/adoptium-support#1046]
### Please provide a brief summary of the bug

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4a0c58cb28, pid=25, tid=26
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.1.so.0+0xd8cb28]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/mursalin/core.25)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava -Dosgi.requiredJavaVersion=17 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true -Declipse.e4.inject.javax.warning=false -Xms256m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -Djava.security.manager=allow -Dosgi.configuration.area=@user.home/.var/app/org.eclipse.Java/eclipse/configuration --patch-module=java.base=/app/eclipse/flatpak-dev-shim.jar -Dsun.boot.library.path=/app/lib /app/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar -os linux -ws gtk -arch x86_64 -showsplash /app/eclipse//plugins/org.eclipse.epp.package.common_4.31.0.20240307-1200/splash.bmp -launcher /app/eclipse/eclipse -name Eclipse --launcher.library /app/eclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.900.v20240129-1338/eclipse_11900.so -startup /app/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar --launcher.appendVmargs -exitdata 20005 -product org.eclipse.epp.package.java.product -vm /app/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.10.v20240120-1143/jre/bin/java -vmargs -Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava -Dosgi.requiredJavaVersion=17 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true -Declipse.e4.inject.javax.warning=false -Dsun.java.command=Eclipse -Xms256m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -Djava.security.manager=allow -Dosgi.configuration.area=@user.home/.var/app/org.eclipse.Java/eclipse/configuration --patch-module=java.base=/app/eclipse/flatpak-dev-shim.jar -Dsun.boot.library.path=/app/lib -jar /app/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar

Host: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz, 4 cores, 3G, GNOME 45 (Flatpak runtime)
Time: Tue Mar 26 07:14:11 2024 +06 elapsed time: 53.462801 seconds (0d 0h 0m 53s)
```

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

while working on java servlets suddenly it stopped responding. When I reopen it the result is same

### Actual Results

while working on java servlets suddenly it stopped responding. When I reopen it the result is same

### What Java Version are you using?

openjdk 17.0.9 2023-10-17 OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9) OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9, mixed mode, sharing)

**Comment by karianna** [comment]
@mohammad-mursalin Please make sure your GTK libs and Eclipse IDE are at the latest patch levels and report back here if it still crashes.  It's a native lib bug that is propagating back to Java.

**Comment by azizBouhouch** [comment]
I have the same problem, but with libwebkit2gtk-4.0.so.37+0xdb6260.

**Comment by azizBouhouch** [comment]
I have the same problem, but with libwebkit2gtk-4.0.so.37+0xdb6260.

**Comment by azbo1** [comment]
> I have the same problem, but with libwebkit2gtk-4.0.so.37+0xdb6260.

No error if I run eclipse with sudo ./eclipse

**Comment by sehaartuc** [comment]
I realized that I didn't installed Java before. After installation, problem is most probably solved. I am saying most probably because I faced another error. Maybe these are related with each other

**Comment by sehaartuc** [comment]
Currently I am facing with following problem;

WARNING: abs already refers to: #'clojure.core/abs in namespace: garden.color, being replaced by: #'garden.color/abs
2024-03-27 12:39:13,606 [main rqc:- - -] INFO  rems.main - REMS {:version v2.36-0-gbcb97adc4, :revision bcb97adc4d9bfd8a60287aefe642a44a363d837d}
Exception in thread "main" java.lang.RuntimeException: could not start [#'rems.config/env] due to
	at mount.core$up$fn__21670.invoke(core.cljc:80)
	at mount.core$up.invokeStatic(core.cljc:80)
	at mount.core$up.invoke(core.cljc:78)
	at mount.core$bring.invokeStatic(core.cljc:247)
	at mount.core$bring.invoke(core.cljc:239)
	at mount.core$start.invokeStatic(core.cljc:289)
	at mount.core$start.doInvoke(core.cljc:281)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at rems.main$_main.invokeStatic(main.clj:167)
	at rems.main$_main.doInvoke(main.clj:114)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at rems.main.main(Unknown Source)
Caused by: java.util.MissingResourceException: can't find a configuration file path: "config/config.edn". besides providing it via "(load-config :file <path>)", it could also be set via "conf" system property (i.e. -Dconf=<path>)
	at cprop.source$from_file.invokeStatic(source.cljc:242)
	at cprop.source$from_file.invoke(source.cljc:228)
	at cprop.source$ignore_missing_default.invokeStatic(source.cljc:285)
	at cprop.source$ignore_missing_default.invoke(source.cljc:281)
	at cprop.core$load_config.invokeStatic(core.cljc:19)
	at cprop.core$load_config.doInvoke(core.cljc:15)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at rems.config$fn__21919.invokeStatic(config.clj:112)
	at rems.config$fn__21919.invoke(config.clj:112)
	at mount.core$record_BANG_.invokeStatic(core.cljc:74)
	at mount.core$record_BANG_.invoke(core.cljc:73)
	at mount.core$up$fn__21670.invoke(core.cljc:81)
	... 11 more

**Comment by fensefernando** [comment]
I have same problem, I use openjdk 21, fedora 39, eclipse 2024-03 (4.31.0).  

It began to present errors in the last update of the operating system.

I have tried with a virtual machine in virtualbox with fedora 39. But the error does not appear there.

**Comment by jerboaa** [comment]
Some of the issues seen here seem to be https://github.com/eclipse-platform/eclipse.platform.swt/issues/1146

**Comment by mmatteo31** [comment]
i have the same problem on ubuntu 22.04. Has anyone found a solution? Thk
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007427c63b61f8, pid=85613, tid=85614
#
# JRE version: OpenJDK Runtime Environment Temurin-22+36 (22.0+36) (build 22+36)
# Java VM: OpenJDK 64-Bit Server VM Temurin-22+36 (22+36, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/matteo/opt/sts-4.21.0.RELEASE/core.85613)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by karianna** [comment]
Please see #1060
