### ISSUE TITLE
a fatal error has been detected by the java runtime environment

### ISSUE THREAD

**Issue by Joseph90827** [adoptium/adoptium-support#1047]
### Please provide a brief summary of the bug

Hi everyone,
I was using siemens star ccm+ program and while I was using it, the program suddenly stopped. After closing, a text file appeared with the error.
[hs_err_pid5944.log](https://github.com/adoptium/adoptium-support/files/14780273/hs_err_pid5944.log)
[hs_err_pid4484.log](https://github.com/adoptium/adoptium-support/files/14780276/hs_err_pid4484.log)
Can someone help me to fix it?

### Did you test with the latest update version?

- [X] Yes

### Expected Results

idk

### Actual Results

idk

### What Java Version are you using?

8.401

**Comment by karianna** [comment]
@Joseph90827 Please try with the latest update version 11.0.22.
