### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by AlphaHans** [adoptium/adoptium-support#1051]
### Please provide a brief summary of the bug

[hs_err_pid95227.log](https://github.com/adoptium/adoptium-support/files/14849219/hs_err_pid95227.log)
[replay_pid95227.log](https://github.com/adoptium/adoptium-support/files/14849220/replay_pid95227.log)
[117/37444] ACTION //services/network/public/mojom:mojom_proxy_config_java__compile_java(//build/toolchain/android:android_clang_arm64)
FAILED: obj/services/network/public/mojom/mojom_proxy_config_java.javac.jar obj/services/network/public/mojom/mojom_proxy_config_java.javac.jar.info
python3 ../../build/android/gyp/compile_java.py --depfile=gen/services/network/public/mojom/mojom_proxy_config_java__compile_java.d --generated-dir=gen/services/network/public/mojom/mojom_proxy_config_java/generated_java --jar-path=obj/services/network/public/mojom/mojom_proxy_config_java.javac.jar --java-srcjars=\[\"gen/services/network/public/mojom/mojom_proxy_config_java_sources.srcjar\",\ \"gen/services/network/public/mojom/mojom_proxy_config_java.generated.srcjar\"\] --target-name //services/network/public/mojom:mojom_proxy_config_java__compile_java --classpath=@FileArg\(gen/services/network/public/mojom/mojom_proxy_config_java.build_config.json:android:sdk_interface_jars\) --header-jar obj/services/network/public/mojom/mojom_proxy_config_java.turbine.jar --classpath=\[\"obj/services/network/public/mojom/mojom_proxy_config_java.turbine.jar\"\] --classpath=@FileArg\(gen/services/network/public/mojom/mojom_proxy_config_java.build_config.json:deps_info:javac_full_interface_classpath\) --jar-info-exclude-globs=\[\"\*/R.class\",\ \"\*/R\\\$\*.class\",\ \"\*/Manifest.class\",\ \"\*/Manifest\\\$\*.class\",\ \"\*/\*GEN_JNI.class\"\]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcfbe4b4378, pid=95227, tid=95249
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x69c378]  PhaseIdealLoop::Dominators()+0x6c8
#
# Core dump will be written. Default location: /mnt/wslg/dumps/core.%e
#
# An error report file with more information is saved as:
# /home/hans/code/xweb116/src/out/Pinus_arm64/hs_err_pid95227.log
#
# Compiler replay data is saved as:
# /home/hans/code/xweb116/src/out/Pinus_arm64/replay_pid95227.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
[130/37444] ACTION //gpu/ipc/common:surface_handle_java__dex(//build/toolchain/android:android_clang_arm64)
```
### Did you test with the latest update version?

- [ ] Yes

### Expected Results

build success

### Actual Results

build failed

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)

### What is your operating system and platform?

Windwos WSL: Ubuntu 20.04.6 LTS

**Comment by karianna** [comment]
update to 17.0.10 and report back please.

**Comment by esraaelmligy** [comment]
Hello, i am also facing the same issue even after updating to OpenJDK 21.0.02

A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007ff3fa90fe17, pid=58512, tid=58513

 JRE version: OpenJDK Runtime Environment (21.0.2+13) (build 21.0.2+13-Ubuntu-120.04.1)
 Java VM: OpenJDK 64-Bit Server VM (21.0.2+13-Ubuntu-120.04.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [sqlite-3.40.0.0-c0fa26ba-7228-4bed-ac22-ac902a2d1bcc-libsqlitejdbc.so+0x11e17]

 Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/esraa/core.58512)

 If you would like to submit a bug report, please visit:
   Unknown
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by karianna** [comment]
@esraaelmligy moving your issue to https://github.com/adoptium/adoptium-support/issues/1053
