### ISSUE TITLE
Eclipse is Crashing

### ISSUE THREAD

**Issue by dshunter107** [adoptium/adoptium-support#1060]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb05bbb61f8, pid=8004, tid=8005
#
# JRE version: OpenJDK Runtime Environment (21.0.2+13) (build 21.0.2+13-Ubuntu-122.04.1)
# Java VM: OpenJDK 64-Bit Server VM (21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/dshunter/eclipse/java-2024-03/eclipse/core.8004)
#
# If you would like to submit a bug report, please visit:
#   Unknown
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

[hs_err_pid8004.log](https://github.com/adoptium/adoptium-support/files/15000631/hs_err_pid8004.log)

### Expected Results

Eclipse should be able to be opened for more than a minute. 

### Actual Results

It shuts down very quickly and gives the error logs. 

### What Java Version are you using?

openjdk 21.0.2 2024-01-16 OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing)

### What is your operating system and platform?

Linux dshunter-VivoBook-ASUSLaptop-E510MAB-L510MA 6.8.6+ #2 SMP PREEMPT_DYNAMIC Mon Apr 15 23:12:08 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### How did you install Java?

Through the commandline 

### Did it work before?

```Shell
Yes.
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by davidmoten** [comment]
getting exactly the same. I assume a libwebkit upgrade on my ubuntu 22.04 has broken eclipse. Can't find workaround, have switched to IntelliJ Idea. Serious business for Eclipse, they could suddenly lose a lot of users.

**Comment by aricomputacao** [comment]
I'm going through the same problem.

**Comment by phamdat** [comment]
got the same issue after update a package on ubuntu 22

**Comment by phamdat** [comment]
WEBKIT_DISABLE_DMABUF_RENDERER=1 solves the problem for me 

https://github.com/eclipse-platform/eclipse.platform.swt/issues/1108#issuecomment-2016591736

**Comment by Abdul1809** [comment]
@phamdat can you please provide the steps to where i need to add WEBKIT_DISABLE_DMABUF_RENDERER=1 for ubuntu 22.04 eclipse

**Comment by phamdat** [comment]
> @phamdat can you please provide the steps to where i need to add WEBKIT_DISABLE_DMABUF_RENDERER=1 for ubuntu 22.04 eclipse

export in bash file or create eclipse.desktop. Can follow to create desktop file in comment https://github.com/eclipse-platform/eclipse.platform.swt/issues/1108#issuecomment-2023171644

**Comment by Danicespedes** [comment]
Anyone coming from Ubuntu 22.04? It seems that workaround is effective on Fedora but I did not add that comment on my application file and did not solve the issue after restart.

**Comment by jerboaa** [comment]
Please update to the latest swt build. This is https://github.com/eclipse-platform/eclipse.platform.swt/issues/1146

**Comment by davidmoten** [comment]
> Anyone coming from Ubuntu 22.04? It seems that workaround is effective on Fedora but I did add that comment on my application file and did not solve the issue after restart.

Yep all fixed, thanks to @phamdat. 

My `eclipse.desktop` looks like this now:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_AU]=eclipse
Name[en_AU]=Eclipse
Exec=env WEBKIT_DISABLE_DMABUF_RENDERER=1 eclipse
Comment[en_AU]=Eclipse
Name=Eclipse
Comment=Eclipse
Icon=/opt/eclipse/current/icon.xpm
```

**Comment by seeker-mm-1499** [comment]
> getting exactly the same. I assume a libwebkit upgrade on my ubuntu 22.04 has broken eclipse. Can't find workaround, completely unusable, have switched to IntelliJ Idea. Serious business for Eclipse, they could suddenly lose a lot of users.

**Comment by seeker-mm-1499** [comment]
> getting exactly the same. I assume a libwebkit upgrade on my ubuntu 22.04 has broken eclipse. Can't find workaround, completely unusable, have switched to IntelliJ Idea. Serious business for Eclipse, they could suddenly lose a lot of users.

I also have the same error  .I'm just a beginner learning java so I don't know what to do .Have you already fixed that error or fixed by using IntelliJ Idea. Should I use to intelli J until that error is occurred?
Please can you reply

**Comment by Danicespedes** [comment]
> > Anyone coming from Ubuntu 22.04? It seems that workaround is effective on Fedora but I did add that comment on my application file and did not solve the issue after restart.
> 
> Yep all fixed, thanks to @phamdat.
> 
> My `eclipse.desktop` looks like this now:
> 
> ```
> #!/usr/bin/env xdg-open
> [Desktop Entry]
> Version=1.0
> Type=Application
> Terminal=false
> Icon[en_AU]=eclipse
> Name[en_AU]=Eclipse
> Exec=env WEBKIT_DISABLE_DMABUF_RENDERER=1 eclipse
> Comment[en_AU]=Eclipse
> Name=Eclipse
> Comment=Eclipse
> Icon=/opt/eclipse/current/icon.xpm
> ```

I have just commented the file as you did, the issue persists... but will check later again

**Comment by seeker-mm-1499** [comment]
> > Anyone coming from Ubuntu 22.04? It seems that workaround is effective on Fedora but I did add that comment on my application file and did not solve the issue after restart.
> 
> Yep all fixed, thanks to @phamdat.
> 
> My `eclipse.desktop` looks like this now:
> 
> ```
> #!/usr/bin/env xdg-open
> [Desktop Entry]
> Version=1.0
> Type=Application
> Terminal=false
> Icon[en_AU]=eclipse
> Name[en_AU]=Eclipse
> Exec=env WEBKIT_DISABLE_DMABUF_RENDERER=1 eclipse
> Comment[en_AU]=Eclipse
> Name=Eclipse
> Comment=Eclipse
> Icon=/opt/eclipse/current/icon.xpm
> ```

Thanks this fixed my error

**Comment by suriDeveloper** [comment]
Hi folks ,
Any one please let me know this issue fixed or not . I am trying with above file but its not working for me.

**Comment by suriDeveloper** [comment]
I am using ubuntu **22.0.4 LTS** and STS version : **spring-tool-suite-4-4.22.0.RELEASE-e4.31.0-linux.gtk.aarch64**. I have checked with my IT team sts perfectly woking in ubuntu 20.0.4 LTS but after package upadte in ubuntu 22.0.4 its getting crashed.

**Comment by Danicespedes** [comment]
> Hi guys , issue fixed . For Ubuntu 22.04.4 LTS,
> 
> sudo nano /etc/gdm3/custom.conf WaylandEnable=false
> 
> After 2 days of R&D finally fixed the isse. Thanks, Happy coding.

Hello

Could you please confirm if your file looks differnt than this?? 


# Uncomment the line below to force the login screen to use Xorg
#WaylandEnable=false

# Enabling automatic login
#  AutomaticLoginEnable = true
#  AutomaticLogin = user1

# Enabling timed login
#  TimedLoginEnable = true
#  TimedLogin = user1
#  TimedLoginDelay = 10

In my case the false in wayland was already comment but Eclipse still collapses. 

thanks!

**Comment by Danicespedes** [comment]
> Hi guys , issue fixed . For Ubuntu 22.04.4 LTS,
> 
> sudo nano /etc/gdm3/custom.conf WaylandEnable=false
> 
> After 2 days of R&D finally fixed the isse. Thanks, Happy coding.

Hello!

In my case the file had the false already commented, If possible  let me know if your file looks different 

![Screenshot from 2024-04-25 16-28-04](https://github.com/adoptium/adoptium-support/assets/155178421/63638788-79d0-41ab-ad17-6a6626ed1706)

Thanks

**Comment by prashant401** [comment]
> Hi guys , issue fixed . For Ubuntu 22.04.4 LTS,
> 
> sudo nano /etc/gdm3/custom.conf WaylandEnable=false
> 
> After 2 days of R&D finally fixed the isse. Thanks, Happy coding.

i followed the same steps but still crashing

**Comment by lokeshmgm05** [comment]
I had the same issue. Ubuntu 22.04.4 LTS. Windowing system - Wayland
Have switched from WayLand to X11 - Solved my eclipse crash
Refer this [link](https://symless.com/synergy/help/synergy-on-ubuntu-21-04) for switching Wayland to X11

**Comment by sxa** [comment]
See also upstream issue https://github.com/eclipse-platform/eclipse.platform.swt/issues/381

**Comment by Danicespedes** [comment]
OK after a month I finally found a simple workaround that worked for me (Ubuntu 22.04)

On eclipse configuration file: 

[Desktop Entry]
Version=1.0
Name=Eclipse
Comment=Java IDE
Type=Application
Categories=Development;IDE;
Exec= env GDK_BACKEND=x11 /home/?? ?/eclipse/eclipse
Terminal=false
StartupNotify=true
Icon=/home/???/eclipse/icon.xpm
Name[en_US]=Eclipse

On the terminal: 

1- Go to the directory where eclipse is installed 
2- export GDK_BACKEND=x11
3- ./eclipse

 Hope it helps, if not i have heard a new version is on its way around 15 June

**Comment by devepulido-mf** [comment]
None of these suggested "fixes" seems to much to solve the issue on openSuSE Leap 15.5.  Everything seems to work OK on Leap 15.4 with the 2022-12 version of Eclipse.  Apparently if it works on Ubuntu these issues get 'closed' right away. Time to move on from Eclipse.
