### ISSUE TITLE
Spring Tool Suite crashing

### ISSUE THREAD

**Issue by sysmasa** [adoptium/adoptium-support#1061]
### Please provide a brief summary of the bug

Spring Tool Suite crashes after few seconds.  It was working fine couple of hours ago.  

OS: Ubuntu 22.04.3 LTS
STS version: 4.19
Java version: 17.0.10

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007cfdca7b61f8, pid=3632, tid=3633
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/mas/bmas/spring/sts-4.19.0.RELEASE/core.3632)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[hs_err_pid3632.log](https://github.com/adoptium/adoptium-support/files/15002334/hs_err_pid3632.log)

### Expected Results

STS on ubuntu machine should work fine as it was working earlier.

### Actual Results

No idea.  STS was working fine a couple of hours ago, now crashing.

### What Java Version are you using?

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

### What is your operating system and platform?

OS: Ubuntu 22.04.3 LTS

### Did it work before?

```Shell
Yes, it was working fine.
```

### Did you test with other Java versions?

```Shell
No.
```

**Comment by gabimaqueda** [comment]
Hi there! I have the same problem ... the only difference is that I use the Ubuntu 22.04.4 LTS and Spring Tool Suite 4.22.0.RELEASE ... 
Attached log file 
Thanks in advance
[hs_err_pid50671.log](https://github.com/adoptium/adoptium-support/files/15006948/hs_err_pid50671.log)
!

**Comment by karianna** [comment]
@sysmasa you log file says 17.0.7 but your but report says 17.0.10 - please make sure you're using the 17.0.10 version (the error log should report that).  Also please upgrade to latest Eclipse / STS and UI packages.

#1060  could also be related

**Comment by igornem1** [comment]
Hello, seemce same problem here but with run of latest Eclipse 2024-03
OS: Ubuntu 22.04.3 LTS
Java version tried: 
1. openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

2. openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

3. openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-122.04.1, mixed mode, sharing)

Eclipse version:
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

[hs_err_pid27050.log](https://github.com/adoptium/adoptium-support/files/15048153/hs_err_pid27050.log)

**Comment by ZeLonewolf** [comment]
Same issue, Java version:
```
java version &quot;17.0.6&quot; 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
```

**Comment by karianna** [comment]
See #1060 for workarounds

**Comment by Mary4D** [comment]
Same issue
 Ubuntu 22.04.4 LTS and Spring Tool Suite 4.22.0.
Java version: 
java 17.0.6 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
 log file :
hs_err_pid2793.log

**Comment by karianna** [comment]
Closing this in favour of #1060
