### ISSUE TITLE
 A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by seeker-mm-1499** [adoptium/adoptium-support#1062]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007a2e3d9b61f8, pid=6254, tid=6255
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/eclipse/core.6254)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

### Did you test with the latest update version?

- [X] Yes

### Expected Results

I want to solve this issue

### Actual Results

eclipse crashed after opening 

### What Java Version are you using?

openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 2022.04 AMD 64

### How did you install Java?

tar.gz

### Did it work before?

```Shell
Yes, the latest version worked but before a few days ago, that error starts to happen.
```

### Did you test with other Java versions?

```Shell
yes, I test with 2023-03 version too.
```

**Comment by seeker-mm-1499** [comment]
[hs_err_pid6254.log](https://github.com/adoptium/adoptium-support/files/15015558/hs_err_pid6254.log)
This is log file from my error

**Comment by karianna** [comment]
Please see #1060
