### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by ashok-dhulipalla** [adoptium/adoptium-support#1065]
### Please provide a brief summary of the bug

[hs_err_pid86419.log](https://github.com/adoptium/adoptium-support/files/15053190/hs_err_pid86419.log)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

Eclipse should not crash

### Actual Results

Eclipse crashing

### What Java Version are you using?

openjdk version "11.0.22" 2024-01-16 OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1) OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

**Comment by karianna** [comment]
See #1060
