### ISSUE TITLE
My Eclipse is constantly crashing

### ISSUE THREAD

**Issue by dmondia679** [adoptium/adoptium-support#1068]
### Please provide a brief summary of the bug

My Eclipse is crashing after a few minutes for no reason and i don't know what's wrong here is one of the logs i got:

[hs_err_pid35888.log](https://github.com/adoptium/adoptium-support/files/15081851/hs_err_pid35888.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

Just open the workspace and after a few minutes it's gonna close without no messages

### Expected Results

Not to crash

### Actual Results

Crashed without doing anything

### What Java Version are you using?

openjdk 11.0.22 2024-01-16

### What is your operating system and platform?

Ubuntu 22.04.3 LTS

### How did you install Java?

Linux via package install

### Did it work before?

```Shell
Yea of course.
```

**Comment by karianna** [comment]
Please see #1060
