### ISSUE TITLE
crash eclipse application.

### ISSUE THREAD

**Issue by robertmakrytski** [adoptium/adoptium-support#1070]
### Please provide a brief summary of the bug

> #
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # A fatal error has been detected by the Java Runtime Environment:
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: #
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: #  SIGSEGV (0xb) at pc=0x00007691f71b61f8, pid=10613, tid=10614
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: #
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # JRE version: OpenJDK Runtime Environment Temurin-22.0.1+8 (22.0.1+8) (build 22.0.1+8)
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # Java VM: OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (22.0.1+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # Problematic frame:
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: #
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/robert/core.10613)
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: #
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # An error report file with more information is saved as:
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: # /home/robert/hs_err_pid10613.log
апр 24 12:02:50 roblap epp.package.jee.desktop[10613]: [28,003s][warning][os] Loading hsdis library failed
апр 24 12:02:51 roblap systemd[2447]: app-gnome-epp.package.jee-10108.scope: Consumed 2min 52.329s CPU time.
апр 24 12:02:51 roblap epp.package.jee.desktop[10613]: #
апр 24 12:02:51 roblap epp.package.jee.desktop[10613]: # If you would like to submit a bug report, please visit:
апр 24 12:02:51 roblap epp.package.jee.desktop[10613]: #   https://github.com/adoptium/adoptium-support/issues
апр 24 12:02:51 roblap epp.package.jee.desktop[10613]: # The crash happened outside the Java Virtual Machine in native code.
апр 24 12:02:51 roblap epp.package.jee.desktop[10613]: # See problematic frame for where to report the bug.

[hs_err_pid10613.log](https://github.com/adoptium/adoptium-support/files/15091585/hs_err_pid10613.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

When i run eclipse and open some java class.

### Expected Results

eclipse not crash

### Actual Results

eclipse crash

### What Java Version are you using?

openjdk 22.0.1 2024-04-16 OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8) OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)

**Comment by karianna** [comment]
See #1060
