### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by clansdown** [adoptium/adoptium-support#1071]
### Please provide a brief summary of the bug

It keeps randomly crashing, sometimes only a few seconds after starting. Here's the latest.
[hs_err_pid2976142.log](https://github.com/adoptium/adoptium-support/files/15096334/hs_err_pid2976142.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

Some trivial navigation did it, it happens without me even touching the keyboard sometimes.

### Expected Results

Not crash

### Actual Results

Crashed

### What Java Version are you using?

openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-123.10.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-123.10.1, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 23.10, Ryzen 7950X

### How did you install Java?

package manager 

### Did it work before?

```Shell
No, eclipse updated to eclipse 2024-03 and now it crashes all the time
```

**Comment by clansdown** [comment]
I didn't notice this line until just now:
(Eclipse:2983995): Gdk-CRITICAL **: 12:40:16.778: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed

The problem is with java and popups. IIRC, if the window manager is too fast, Java GUIs crash because of that assertion, as there's a race condition in the GUI code that, on slower systems, the non-crashing condition always wins.

**Comment by pocolocosv** [comment]
I see this too. Whenever a popups appears, Eclipse just crashes. I get:

(Eclipse:69120): Gdk-CRITICAL **: 15:09:14.526: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed

Using it on a Ubuntu 22.04.4:

JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)

**Comment by karianna** [comment]
Please see #1060
