### ISSUE TITLE
h

### ISSUE THREAD

**Issue by kishordhangarsv** [adoptium/adoptium-support#1072]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007157251b61f8, pid=379816, tid=379817
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (17.0.8.1+1) (build 17.0.8.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (17.0.8.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE/core.379816)
#
# If you would like to submit a bug report, please visit:
#    
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Xms256m -Xmx2048m --illegal-access=permit /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE/SpringToolSuite4 -name SpringToolSuite4 --launcher.library /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024/eclipse_11801.so -startup /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar --launcher.overrideVmargs -exitdata 15 -product org.springframework.boot.ide.branding.sts4 -vm /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.8.v20230831-1047/jre/bin/java -vmargs --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Dsun.java.command=SpringToolSuite4 -Xms256m -Xmx2048m --illegal-access=permit -jar /home/kd/IDE's/spring-tool-suite-4-4.20.0.RELEASE-e4.29.0-linux.gtk.x86_64/sts-4.20.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar

Host: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 8 cores, 7G, Ubuntu 22.04.4 LTS
Time: Thu Apr 25 15:01:56 2024 IST elapsed time: 187.522067 seconds (0d 0h 3m 7s)

---------------  T H R E A D  ---------------

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

sts shuting down automatically..

### Actual Results

sts shuting down automatically..

### What Java Version are you using?

kd@kd-Latitude-5490:~$ java --version openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing) kd@kd-Latitude-5490:~$ 

### What is your operating system and platform?

ubuntu

### How did you install Java?

using cli

### Did it work before?

```Shell
yes
```

**Comment by karianna** [comment]
Please see #1060
