### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment: 

### ISSUE THREAD

**Issue by UchumakiTestDev** [adoptium/adoptium-support#1073]
### Please provide a brief summary of the bug

I have this bug in Ubuntu when i use Eclipse.

(Eclipse:55993): Gdk-CRITICAL **: 10:06:31.849: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000782ec81b61f8, pid=55993, tid=55994
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/ezequiel/core.55993)
#
# An error report file with more information is saved as:
# /home/ezequiel/hs_err_pid55993.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

i can use eclipse.

### Actual Results

eclipse close 

### What Java Version are you using?

openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

**Comment by karianna** [comment]
See #1060
