### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:  pid=18320

### ISSUE THREAD

**Issue by PEIDONGLU** [adoptium/adoptium-support#1074]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000019d99c61115, pid=18320, tid=26160
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, parallel gc, windows-amd64)
# Problematic frame:
# v  ~StubRoutines::atomic_add_long
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
[hs_err_pid18320.log](https://github.com/adoptium/adoptium-support/files/15138043/hs_err_pid18320.log)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

RUN Successfully

### Actual Results

 A fatal error has been detected by the Java Runtime Environment

### What Java Version are you using?

java_jdk\11.0.16.1\

**Comment by karianna** [comment]
@PEIDONGLU Please try 11.0.23 and post the crash log here if it still persists
