### ISSUE TITLE
Spring Tool Suite crash

### ISSUE THREAD

**Issue by LongQuayTay** [adoptium/adoptium-support#1075]
### Please provide a brief summary of the bug

[hs_err_pid3361.log](https://github.com/adoptium/adoptium-support/files/15138399/hs_err_pid3361.log)

### Did you test with the latest update version?

- [X] Yes

### Expected Results

STS can work similar.  

### Actual Results

STS crash

### What Java Version are you using?

21

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

**Comment by karianna** [comment]
See #1060
