### ISSUE TITLE
Eclipse keep crashing while modifying code

### ISSUE THREAD

**Issue by wildwood44** [adoptium/adoptium-support#1076]
### Error message
[hs_err_pid8107.log](https://github.com/adoptium/adoptium-support/files/15139842/hs_err_pid8107.log)

### Java Version
17.0.0

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

I should be able to code without issue in eclipse.

### Actual Results

Interaction with code will cause eclipse to crash with out warning after a short time.

### What Java Version are you using?

Java 17.0.10

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

### Did it work before?

```Shell
Until recently I have been able to program without issue. I am unaware of any changes to cause this.
```

### Did you test with other Java versions?

```Shell
I have updated from openjdk version "11.0.22" to openjdk version "17.0.10" but this has not resolved the issue
```

**Comment by EmmahOwens** [comment]
Of recent I've started having the same issue. I may also need help on this.

**Comment by pablompamplona** [comment]
I'm started having the same problem

**Comment by karianna** [comment]
See #1060
