### ISSUE TITLE
Uncontrolled closing of Eclipse IDE on Zorin OS

### ISSUE THREAD

**Issue by EmmahOwens** [adoptium/adoptium-support#1077]
### Please provide a brief summary of the bug

[Uploading hs_err_pid25891.log…]()

### Did you test with the latest update version?

- [x] Yes

### Expected Results

I was expecting it to run normally without crashing.

### Actual Results

It crashed everytime I try to code using the IDE.

### What Java Version are you using?

22

### What is your operating system and platform?

Zorin OS 17.1 on 64 bit machine

### How did you install Java?

Using the debian file

### Did it work before?

```Shell
Yes, it did.
```

### Did you test with other Java versions?

```Shell
Yes, I did.
```

**Comment by karianna** [comment]
See #1060

**Comment by EmmahOwens** [comment]
Please provide me with a step by step guide on how to solve this

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
