### ISSUE TITLE
STS autoclose

### ISSUE THREAD

**Issue by vikasbhosalecybage** [adoptium/adoptium-support#1078]
### Please provide a brief summary of the bug

Host: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz, 4 cores, 15G, Ubuntu 22.04.4 LTS
Time: Tue Apr 30 10:31:21 2024 IST elapsed time: 56833.844555 seconds (0d 15h 47m 13s)

---------------  T H R E A D  ---------------

Current thread (0x000071b5fc027330):  JavaThread "main" [_thread_in_native, id=14465, stack(0x000071b602100000,0x000071b602200000)]

Stack: [0x000071b602100000,0x000071b602200000],  sp=0x000071b6021fcf48,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 5397  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(J)V (0 bytes) @ 0x000071b5f1562061 [0x000071b5f1562020+0x0000000000000041]
J 24050 c2 org.eclipse.swt.widgets.Display.eventProc(JJ)J (212 bytes) @ 0x000071b5f20cc8ac [0x000071b5f20cc800+0x00000000000000ac]
v  ~StubRoutines::call_stub
J 5403  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Z)Z (0 bytes) @ 0x000071b5f1562de1 [0x000071b5f1562da0+0x0000000000000041]
J 42194 c2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (88 bytes) @ 0x000071b5f33ca200 [0x000071b5f33ca120+0x00000000000000e0]
J 26081% c2 org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run()V (690 bytes) @ 0x000071b5f22c8e70 [0x000071b5f22c8cc0+0x00000000000001b0]
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(Lorg/eclipse/e4/ui/model/application/MApplicationElement;Lorg/eclipse/e4/core/contexts/IEclipseContext;)Ljava/lang/Object;+57
j  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(Lorg/eclipse/e4/ui/model/application/MApplicationElement;)V+20
j  org.eclipse.ui.internal.Workbench.lambda$3(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;[I)V+392
j  org.eclipse.ui.internal.Workbench$$Lambda$371+0x00000001003577c8.run()V+12
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+16
j  org.eclipse.ui.PlatformUI.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+2
j  org.eclipse.ui.internal.ide.application.IDEApplication.start(Lorg/eclipse/equinox/app/IApplicationContext;)Ljava/lang/Object;+113
j  org.eclipse.equinox.internal.app.EclipseAppHandle.run(Ljava/lang/Object;)Ljava/lang/Object;+138
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ljava/lang/Object;)Ljava/lang/Object;+85
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Ljava/lang/Object;)Ljava/lang/Object;+79
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run(Ljava/lang/Object;)Ljava/lang/Object;+99
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run([Ljava/lang/String;Ljava/lang/Runnable;)Ljava/lang/Object;+132
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.10
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.10
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.10
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.10
j  org.eclipse.equinox.launcher.Main.invokeFramework([Ljava/lang/String;[Ljava/net/URL;)V+202
j  org.eclipse.equinox.launcher.Main.basicRun([Ljava/lang/String;)V+159
j  org.eclipse.equinox.launcher.Main.run([Ljava/lang/String;)I+4
j  org.eclipse.equinox.launcher.Main.main([Ljava/lang/String;)V+10
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

Registers:
RAX=0x000071b5ff973600, RBX=0x0000000000000000, RCX=0x0000000000000001, RDX=0x0000000000000002
RSP=0x000071b6021fcf48, RBP=0x000071b5fc4d00e0, RSI=0x000071b5fc4ce710, RDI=0x0000000000000000
R8 =0x0000000000000000, R9 =0x0000000000000800, R10=0x0000000000000000, R11=0xa204b377c6ca5517
R12=0x000071b5ff600f70, R13=0x000071b5ff2ad7c0, R14=0x000071b5fcb72930, R15=0x0000000000000000
RIP=0x000071b5e41e23c4, EFLAGS=0x0000000000010202, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Register to memory mapping:

RAX=0x000071b5ff973600 points into unknown readable memory: 0x000071b5ff219950 | 50 99 21 ff b5 71 00 00
RBX=0x0 is NULL
RCX=0x0000000000000001 is an unknown value
RDX=0x0000000000000002 is an unknown value
RSP=0x000071b6021fcf48 is pointing into the stack for thread: 0x000071b5fc027330
RBP=0x000071b5fc4d00e0 points into unknown readable memory: 0x000071b5fc4ced90 | 90 ed 4c fc b5 71 00 00
RSI=0x000071b5fc4ce710 points into unknown readable memory: 0x0000000000000520 | 20 05 00 00 00 00 00 00
RDI=0x0 is NULL
R8 =0x0 is NULL
R9 =0x0000000000000800 is an unknown value
R10=0x0 is NULL
R11=0xa204b377c6ca5517 is an unknown value
R12=0x000071b5ff600f70 points into unknown readable memory: 0x000071b5ff2ad7c0 | c0 d7 2a ff b5 71 00 00
R13=0x000071b5ff2ad7c0 points into unknown readable memory: 0x000071b5ff2ad6a0 | a0 d6 2a ff b5 71 00 00
R14=0x000071b5fcb72930 points into unknown readable memory: 0x000071b5fc4d5420 | 20 54 4d fc b5 71 00 00
R15=0x0 is NULL

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

NA

### Actual Results

NA

### What Java Version are you using?

openjdk 11.0.22 2024-01-16

**Comment by karianna** [comment]
See #1060
