### ISSUE TITLE
eclipse crashes due to libwebkit2gtk 

### ISSUE THREAD

**Issue by benjamin-murauer-esd** [adoptium/adoptium-support#1079]
### Please provide a brief summary of the bug

The Spring Tool Suite (a branded Eclipse version) crashes under wayland.

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

on Arch linux, installed the latest `spring-tool-suite` and ran it under wayland (Hyprland). Ater a few seconds, the UI freezes, and the core is dumped.
The error happens both on the system's latest adoptium version 17.0.11+9 (see the log above), as well as in two different versions 17.0.10 and 21.0.2.
The same application runs fine under X.

### Expected Results

I expected the app to run.

### Actual Results

The app crashed.

### What Java Version are you using?

openjdk 17.0.11 2024-04-16 OpenJDK Runtime Environment (build 17.0.11+9) OpenJDK 64-Bit Server VM (build 17.0.11+9, mixed mode, sharing)

### What is your operating system and platform?

Arch Linux with all updates installed, on x86.

### How did you install Java?

Arch package manager

### Did it work before?

```Shell
I only recently tried switching to wayland.
```

### Did you test with other Java versions?

```Shell
17.0.10 (not working)
21.0.2  (not working)
```

### Relevant log output

```Shell
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007aba1cec283b, pid=656056, tid=656057
#
# JRE version: OpenJDK Runtime Environment (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0x10c283b]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /opt/sts-4.22.0.RELEASE/core.656056)
#
# An error report file with more information is saved as:
# /opt/sts-4.22.0.RELEASE/hs_err_pid656056.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by karianna** [comment]
See #1060
