### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by haptm** [adoptium/adoptium-support#1080]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ed68c1b61f8, pid=7285, tid=7286
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/manhha/core.7285)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.slf4j.simpleLogger.defaultLogLevel=off -Dp2.trustedAuthorities=https://download.eclipse.org,https://archive.eclipse.org,https://cdn.spring.io -Xms256m -Xmx2048m --illegal-access=permit --add-modules=ALL-SYSTEM -javaagent:/home/manhha/sts/sts-4.22.1.RELEASE/lombok.jar /home/manhha/sts/sts-4.22.1.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /home/manhha/sts/sts-4.22.1.RELEASE/SpringToolSuite4 -name SpringToolSuite4 --launcher.library /home/manhha/sts/sts-4.22.1.RELEASE//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.900.v20240129-1338/eclipse_11900.so -startup /home/manhha/sts/sts-4.22.1.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar --launcher.overrideVmargs -exitdata 3b -product org.springframework.boot.ide.branding.sts4 -vm /home/manhha/sts/sts-4.22.1.RELEASE//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.11.v20240426-1830/jre/bin/java -vmargs --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.slf4j.simpleLogger.defaultLogLevel=off -Dsun.java.command=SpringToolSuite4 -Dp2.trustedAuthorities=https://download.eclipse.org,https://archive.eclipse.org,https://cdn.spring.io -Xms256m -Xmx2048m --illegal-access=permit --add-modules=ALL-SYSTEM -javaagent:/home/manhha/sts/sts-4.22.1.RELEASE/lombok.jar -jar /home/manhha/sts/sts-4.22.1.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

run successfully

### Actual Results

A fatal error has been detected by the Java Runtime Environment

### What Java Version are you using?

openjdk 19.0.2 2023-01-17 OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04) OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)

### What is your operating system and platform?

ubuntu 22.04

**Comment by karianna** [comment]
See #1060
