### ISSUE TITLE
Eclipse closes automatically while using it.

### ISSUE THREAD

**Issue by Swati-Gadekar** [adoptium/adoptium-support#1082]
### Please provide a brief summary of the bug

While writing some code in the Eclipse, it closes abruptly.
Error log is there, attaching the file. 
PFA

[hs_err_pid175147.log](https://github.com/adoptium/adoptium-support/files/15213027/hs_err_pid175147.log)

### Did you test with the latest update version?

- [x] Yes

### Expected Results

Eclipse should not close automatically.

### Actual Results

While writing some code in the Eclipse, it closes abruptly.

### What Java Version are you using?

openjdk version "11.0.22" 2024-01-16

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

### Did it work before?

```Shell
Yes, it was working before.
```

**Comment by sureshkrishnan-v** [comment]
same thing happning to me 
[hs_err_pid15123.log](https://github.com/adoptium/adoptium-support/files/15213649/hs_err_pid15123.log)
here is the log attached please resolve my error I cannot use eclipse or java in my ubuntu system

**Comment by karianna** [comment]
See #1060
