### ISSUE TITLE
In container with Jenkins 2.452.1 LTS - Temurin-17.0.11+9 - #  SIGSEGV (0xb) at pc=0x00007ffffe1b4700, pid=7, tid=33

### ISSUE THREAD

**Issue by bodhi-one** [adoptium/adoptium-support#1088]
### Please provide a brief summary of the bug

Attempting to run with Jenkins version 2.242.1 LTS built into a docker container using Temurin-17.0.11+9

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffe1b4700, pid=7, tid=33
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x73d700]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x35b0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/dev/hs_err_pid7.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

This is interesting, if the container is allowed to startup as normal using ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"] , the container will fail with this error

However, if container is started using entrypoint bash then issued command /bin/tini /usr/local/bin/jenkins.sh manually, the container comes up fine.

Possibly pointing to a runtime bootstrap issue in the java layer that Jenkins is running into.

### Expected Results

run without issue as has in the past with previous versions of Jenkins.war

### Actual Results

failure as noted above

### What Java Version are you using?

```
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
```

### What is your operating system and platform?

Mac OS aarm M1, but this is failing in the docker container running Rocky Linux 8.9

### How did you install Java?

FROM rockylinux/rockylinux:8.9

# Install Java
unzipping  OpenJDK17U-jre_x64_linux_hotspot_17.0.11_9.tar.gz

# Copy in jenkins LTS
jenkins-2.452.1.war

ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]

### Did it work before?

```Shell
Worked with Jenkins up through 2.241.3 LTS
```

### Did you test with other Java versions?

```Shell
Similar failure with Temurin 17.0.10
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffe1b4700, pid=7, tid=33
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x73d700]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x35b0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/dev/hs_err_pid7.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by bodhi-one** [comment]
In the container: 
[dev@79ff5a32b513 ~]$ docker --version
Docker version 20.10.8, build 3967b7d

**Comment by bodhi-one** [comment]
Within the container which would start successfully with manual commands, upon updating Jenkins plugins and jenkins restarted, with the same container still up, I re-issued the /bin/tini /usr/local/bin/jenkins.sh command again and it fails:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffe1b4700, pid=2646, tid=2684
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x73d700]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x35b0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/dev/hs_err_pid2646.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

I have the hs_err_pid2646.log file but it's 6231 lines long.  Trying to attach. 
[hs_err_pid2646.log](https://github.com/adoptium/adoptium-support/files/15324721/hs_err_pid2646.log)

**Comment by cjbeatty** [comment]
@bodhi-one Which version of macOS are you using?

**Comment by bodhi-one** [comment]
> @bodhi-one Which version of macOS are you using?

Sonoma 14.5 (23F79) as of yesterday.  Docker Desktop 4.29.0 (145265) with Docker Engine 26.0.0 built into that.

**Comment by aberman** [comment]
I am also experiencing crashes after having upgraded to MacOS 14.5 running a java process on Linux within Docker.  I wonder if the previous Java issue on MacOS 14.4 has resurfaced.

**Comment by bodhi-one** [comment]
> I am also experiencing crashes after having upgraded to MacOS 14.5 running a java process on Linux within Docker. I wonder if the previous Java issue on MacOS 14.4 has resurfaced.

You mean like this ?  https://www.reddit.com/r/Clojure/comments/1bgap6a/watch_out_latest_mac_os_update_144_breaks_java/

**Comment by karianna** [comment]
@bodhi-one are you able to try with Docker desktop 4.30.0?

**Comment by bodhi-one** [comment]
> @bodhi-one are you able to try with Docker desktop 4.30.0?

I installed docker desktop 4.30.0 this morning.  Same/similar issue occurs (SEGSEGV).

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fffe946bf87, pid=7, tid=68
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# J 11563 c2 net.sf.json.JSONObject.hashCode()I (88 bytes) @ 0x00007fffe946bf87 [0x00007fffe946b920+0x0000000000000667]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/dev/hs_err_pid7.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

**Comment by aberman** [comment]
> > I am also experiencing crashes after having upgraded to MacOS 14.5 running a java process on Linux within Docker. I wonder if the previous Java issue on MacOS 14.4 has resurfaced.
> 
> You mean like this ? https://blogs.oracle.com/java/post/java-on-macos-14-4#:~:text=With%20macOS%2014.4%2C%20programs%20that,1. https://www.reddit.com/r/Clojure/comments/1bgap6a/watch_out_latest_mac_os_update_144_breaks_java/

Yep, that's the one.  I am also using Docker Desktop 4.30.0 and I tried going down a version as well, same issue.  

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffed2525a, pid=1, tid=0x00007ffffc512700
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9d825a][thread 140737427617536 also had an error]
[thread 140737428670208 also had an error]
  oopDesc* PSPromotionManager::copy_to_survivor_space<false>(oopDesc*)+0x2ea
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
[thread 140737425512192 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
```

**Comment by jritst** [comment]
Same issue after upgrading to Sonoma 14.5

**Comment by bbombachini** [comment]
I think we're facing the same issue. Docker setup for logstash is failing with this exact same error although we're using Temurin-17.0.4+8.
I'm on OS Sonoma 14.5 and M3 machine.

```
=> ERROR [logstash 6/6] RUN logstash-plugin install logstash-filter-jso  16.0s
------
 > [logstash 6/6] RUN logstash-plugin install logstash-filter-json:
0.156 Using bundled JDK: /usr/share/logstash/jdk
13.07 Validating logstash-filter-json
15.96 #
15.96 # A fatal error has been detected by the Java Runtime Environment:
15.96 #
15.96 #  SIGSEGV (0xb) at pc=0x00007ffffe975c90, pid=7, tid=63
15.96 #
15.96 # JRE version: OpenJDK Runtime Environment Temurin-17.0.4+8 (17.0.4+8) (build 17.0.4+8)
15.96 # Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (17.0.4+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
15.96 # Problematic frame:
15.96 # V  [libjvm.so+0x733c90]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x35b0
15.97 #
15.97 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
15.97 #
15.97 # An error report file with more information is saved as:
15.97 # /usr/share/logstash/hs_err_pid7.log
15.98 #
15.98 # If you would like to submit a bug report, please visit:
15.98 #   https://github.com/adoptium/adoptium-support/issues
15.98 #
15.99 Aborted
------
failed to solve: process "/bin/sh -c logstash-plugin install logstash-filter-json" did not complete successfully: exit code: 134
```

**Comment by jjexpat00** [comment]
Same issue here on lts-jdk21 Temurin-21.0.3+9 (21.0.3+9) (build 21.0.3+9-LTS). Sonoma 14.5 M1 machine.

**Comment by mikich** [comment]
Same here, what's going on?!?
Running Docker on M3 Pro, happened after the update to Sonoma 14.5 from 14.4.x :(

`# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffec1b3dd, pid=1, tid=45
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.23+9 (11.0.23+9) (build 11.0.23+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (11.0.23+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7ce3dd]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x3ad
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -XX:+IgnoreUnrecognizedVMOptions -Dfile.encoding=UTF-8 -Dlogfile.path=target/log -XX:+CrashOnOutOfMemoryError /app/metabase.jar

Host: x86_64, 11 cores, 21G, Alpine Linux v3.19
Time: Wed May 29 22:43:47 2024 UTC elapsed time: 7.843398 seconds (0d 0h 0m 7s)`

**Comment by bodhi-one** [comment]
Resolution provided by docker desktop updates.
