### ISSUE TITLE
 A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by amuthanvenkatesan** [adoptium/adoptium-support#1090]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000754755db61f8, pid=2207, tid=2208
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/rajkumar/core.2207)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

### Did you test with the latest update version?

- [X] Yes

### Expected Results

Progam is able to execute.

### Actual Results

Noted as above

### What Java Version are you using?

12

### What is your operating system and platform?

Ubuntu 18.04

### Did it work before?

```Shell
Yes
```

**Comment by karianna** [comment]
See #1060
