### ISSUE TITLE
Eclipse IDE for C++ 2024-03 coredumps when accessing the marketplace on openSuSE Leap 15.5

### ISSUE THREAD

**Issue by devepulido-mf** [adoptium/adoptium-support#1098]
### Please provide a brief summary of the bug

While attempting to bring up the marketplace panel to look for extensions, the Eclipse IDE for CPP coredumps consistently. I tried switching JVMs from 17 to 21 but it made no difference. 

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

1. Install the required JDK for your project, in my case Java 17 or 21 Temurin release
2. Launch the new version of Eclipse for C++ (v2024-03)
3. Select the workspace you use, if asked
4. From the Help pull-down menu select 'Eclipse Marketplace'
5. The 'Eclipse Marketplace' panel will pop up for about 2 seconds and then the entire IDE crashes
[hs_err_pid32738.log](https://github.com/adoptium/adoptium-support/files/15446790/hs_err_pid32738.log)

### Expected Results

I expect the 'Eclipse Marketplace' panel to stay open to search for the plugins/extensions that I need for the editor and the C++ language I need to use.

### Actual Results

The entire IDE crashes and I am not able to use it.

### What Java Version are you using?

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

### What is your operating system and platform?

openSuSE Leap 15.5, up to date

### How did you install Java?

I used SDKMAN:
script: 5.18.2
native: 0.4.6

But I also downloaded and reproduced the problem with the version you suggested at  https://adoptium.net/temurin/releases/

### Did it work before?

```Shell
The previous version of Eclipse that I had installed was 2021-12 for Java Development and it was running with Java 11.0.22+7 and it also has the same problem.

I have installed now the Eclipse for C++ and I still have the same issue.
```

### Did you test with other Java versions?

```Shell
I have test this issue with java 11, 17, and 21, and the version of Temurin that you have suggested above. I have encountered the same problem with all of them.

So far, that seems to be the only panel that it seems to crash the entire IDE. It only seems to crash when I try the 'Open Marketplace Favorites' or the 'Eclipse Marketplace' menu options.
```

### Relevant log output

```Shell
$WARNING: Using incubator modules: jdk.incubator.vector
May 26, 2024 2:11:48 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(Eclipse:32738): Gdk-CRITICAL **: 02:12:12.066: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3907e922e0, pid=32738, tid=32739
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.3+9 (21.0.3+9) (build 21.0.3+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.1.so.0+0xe2d2e0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/bin/false" (or dumping to /home/epulido/eclipse/cpp-2024-03/eclipse/core.32738)
#
# An error report file with more information is saved as:
# /home/epulido/eclipse/cpp-2024-03/eclipse/hs_err_pid32738.log
[25.643s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by karianna** [comment]
Likely #1060
