### ISSUE TITLE
just downloaded latest eclipse version for Eclipse IDE for Enterprise Java and Web Developers and its crashing when opening marketplace

### ISSUE THREAD

**Issue by xlogan777** [adoptium/adoptium-support#1100]
### Please provide a brief summary of the bug

[hs_err_pid15379.log](https://github.com/adoptium/adoptium-support/files/15467427/hs_err_pid15379.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

i just opened the eclipse market place

### Expected Results

to see the eclipse market place

### Actual Results

ide just crashed

### What Java Version are you using?

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

### What is your operating system and platform?

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

### How did you install Java?

sudo apt install openjdk-17-jdk

### Did it work before?

```Shell
used to before this version of eclipse.
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by karianna** [comment]
See #1060
