### ISSUE TITLE
Eclipse getting crashed 

### ISSUE THREAD

**Issue by sree24111** [adoptium/adoptium-support#1102]
### Please provide a brief summary of the bug

While opening eclipse market place it getting crashed

### Did you test with the latest update version?

- [x] Yes

### Please provide steps to reproduce where possible

Eclipse-->Help-->Eclipse marketplace

### Expected Results

It should be in Market place and allow me to search for plugin

### Actual Results

But it getting crashed instead of allowing me to search

### What Java Version are you using?

jdk 17

### What is your operating system and platform?

Linux Ubuntu 24.04 LTS

### How did you install Java?

From Terminal by using this command "sudo snap install --classic eclipse"

### Did it work before?

```Shell
Yes, Its working before
```

### Did you test with other Java versions?

```Shell
Yes, with other versions also its not working
```

### Relevant log output

```Shell
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007940883819d0, pid=22484, tid=22485
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.1.so.0+0xd819d0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/srikanth/snap/core.22484)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code
```

**Comment by karianna** [comment]
See #1060
