### ISSUE TITLE
Introduce JEP356 to all suitable Adoptium releases

### ISSUE THREAD

**Issue by Frontear** [adoptium/adoptium-support#1104]
## Question
Hey there, long time Adoptium (formerly AdoptOpenJDK) user here, absolutely love your releases and have been a long-time supporter as well. I was running some Java applications that make use of code that was introduced and accepted by upstream OpenJDK in [JEP 356: Enhanced Pseudo-Random Number Generators](https://openjdk.org/jeps/356). I was a bit surprised to see my app crash and tell me that the class necessary for this feature "java.util.random.RandomGeneratorFactory" was missing. When I went back to test I noticed that while the proposal has been accepted for over a year, it seems to be missing from the latest Adoptium builds (both 17 and 21, 22 not tested).

I was wondering why this was the case. Was there any particular reasons for why this JEP has not yet made it into Adoptium? If it is a simple matter of missing its integration, would it be possible to introduce it? It's a great JEP that opens the possibility of creating and using more performant/effective Random generators that can still comply with Java's Random interface, allowing for a lot of flexibility in its use for both old and new projects.

## Context

Java version: 17.0.11+9 and 21.0.3+9

```console
$ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```
```console
$ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

Your operating system and platform:

Windows 11 23H2 on x86-64

**Comment by karianna** [comment]
@Frontear Can you give the full error message / stack trace?  I can only gues that your JAVA_HOME or PATH is including a Pre Java 17 Java and that's actually what's being called first...

**Comment by jerboaa** [comment]
What makes you believe [JEP 356:](https://openjdk.org/jeps/356) isn't in Eclipse Temurin 17+ builds?

```
bin/jshell -J-showversion
openjdk version "17.0.11-beta" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+4-202402212033 (build 17.0.11-beta+4-ea)
OpenJDK 64-Bit Server VM Temurin-17.0.11+4-202402212033 (build 17.0.11-beta+4-ea, mixed mode, sharing)
|  Welcome to JShell -- Version 17.0.11-beta
|  For an introduction type: /help intro

jshell> java.util.random.RandomGenerator.getDefault()
$1 ==> jdk.random.L32X64MixRandom@7c3df479

jshell> 
```

**Comment by Frontear** [comment]
Apologies, it turns out I was very much in User Error. I have no idea HOW I messed it up, it mightve been a headless build or an invalid version, but you're correct, doing testing again revealed that it does indeed exist. Sorry about that!
