### ISSUE TITLE
[vscode devcontainer]A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by zanqi** [adoptium/adoptium-support#1108]
### Please provide a brief summary of the bug

I use vscode devcontainer on a java project. Got the following error for the past month and couldn't get IntelliSense for java. Log file attached. 
[hs_err_pid939.log](https://github.com/user-attachments/files/15749886/hs_err_pid939.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

0. install docker desktop
1. clone the repo: https://github.com/zanqi/compiler
2. open it in vscode
3. vscode should popup a prompt on bottom right to open It in devcontainer. Click blue button to do so
4. after things settled (no more in progress UI on the screen), open a java file
5. "java: initialize workspace" in the bottom bar appears, but never finished. Click on it will see the error I am reporting.

### Expected Results

no error

### Actual Results

as reported

### What Java Version are you using?

openjdk 21.0.3 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 24.04 LTS on amd64

### How did you install Java?

vscode devcontainer, select java in select container features
<img width="724" alt="image" src="https://github.com/adoptium/adoptium-support/assets/2538192/eb32d58d-4e88-49f3-a219-d9b5882411d1">

### Did it work before?

```Shell
Yes, used to work a month ago
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffeec3a2d, pid=939, tid=991
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc87a2d]  void OopOopIterateDispatch<PCIterateMarkAndPushClosure>::Table::oop_oop_iterate<InstanceKlass, narrowOop>(PCIterateMarkAndPushClosure*, oopDesc*, Klass*)+0xdd
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /workspaces/compiler/hs_err_pid939.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
[Error - 11:32:36 PM] Client Language Support for Java (Syntax Server): connection to server is erroring. Shutting down server.
[Error - 11:32:36 PM] Client Language Support for Java (Syntax Server): connection to server is erroring. Shutting down server.
[Error - 11:32:36 PM] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099
```

**Comment by karianna** [comment]
Might be related to #1094 as well.

**Comment by karianna** [comment]
@zanqi It looks like that you have both Java 21.0.3 installed and 17.0.11.  Is it the case that VS Code starts with 21 but you are targeting 17 for that project?

**Comment by zanqi** [comment]
@karianna I don't have jdk 17 installed, but the redhat java language server for vscode seems to expect it.

**Comment by akaroml** [comment]
@testforstephen could you help take a look?

**Comment by akaroml** [comment]
> @karianna I don't have jdk 17 installed, but the redhat java extension for vscode comes with an embedded JDK 17.

Just to clarify that the embedded JDK is for the language service internal use only. User still needs to install the JDK corresponding to their project needs.

**Comment by testforstephen** [comment]
Hey @zanqi, I followed your reproducing steps and Java extension is started well using the embedded JRE 17. See the screenshot below.

![image](https://github.com/adoptium/adoptium-support/assets/14052197/583f8a62-3118-456f-aa83-c6d6480c5636)

The embedded JRE of Java extension is from [JustJ](https://eclipse.dev/justj/) (which is based on Temurin), I'm not familiar with the specific JDK errors. Can you try to change the user setting `"java.jdt.ls.java.home": "/usr/local/sdkman/candidates/java/21.0.3-tem"`? This will force the Java extension to use your specified JDK to start the Java tooling.

**Comment by zanqi** [comment]
Hi, @testforstephen, the setting key `"java.jdt.ls.java.home"` is not recognized by vscode.

<img width="994" alt="image" src="https://github.com/adoptium/adoptium-support/assets/2538192/c2e76bbd-1985-4ec0-b4ff-0605ea47bede">

One difference between our setup is I am using vscode on a mac.

**Comment by testforstephen** [comment]
**F1 -> Preferences: Open User Settings**

![image](https://github.com/adoptium/adoptium-support/assets/14052197/11de5a73-b556-40fd-8785-de24e7afea99)

Yes, I run docker on Windows 11. Can you share specific info for your macOS machine?

**Comment by zanqi** [comment]
Thanks for the instruction. I changed the Remote settings accordingly. Unfortunately, the problem still appears. Only this time, the error is reported by JDK 21

My mac info:
Chip: Apple M3 Pro
OS: macOS Sonama Version 14.5

The error:
```
[thread 8687 also had an error]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffed93690, pid=8670, tid=8672
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.3+9 (21.0.3+9) (build 21.0.3+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xd7c690]  oopDesc* PSPromotionManager::copy_unmarked_to_survivor_space<false>(oopDesc*, markWord)+0x40
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /workspaces/compiler/hs_err_pid8670.log
[thread 8688 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by testforstephen** [comment]
I noticed that your image is for AMD64 (x64), but your machine uses Apple Silicon. Was this intentional? Have you tried using the ARM64 image?

**Comment by zanqi** [comment]
Yes, some of the packages I need are compiled for i386. It only works on AMD64 but not ARM64.

I tried switching the image to ARM64. The Java language server indeed works.

**Comment by testforstephen** [comment]
So this is a platform compatibility issue. let's narrow it down a bit. Can you manually run Java command on the devcontainer? for example, `javac Hello.java` and `java Hello`. I want to confirm if the problem is with the JDK itself or with the Java extension.

**Comment by zanqi** [comment]
`javac` and `java` commands work fine. Only the Java extension is having trouble.

**Comment by zanqi** [comment]
I don't know the last working version.

**Comment by karianna** [comment]
@zanqi Can you try again with the latest VS Code and Arm based JDK?
