### ISSUE TITLE
Winget EclipseAdoptium.Temurin.8.JRE

### ISSUE THREAD

**Issue by cstett** [adoptium/adoptium-support#1110]
My organization wants to auto update EclipseAdoptium.Temurin.8.JRE through winget but version 8.0.412.8 has not been published to winget yet. Does the Winget versions typically lag far behind? Are there better ways to manage updates?

Thank you kindly,

**Comment by karianna** [comment]
Can confirm this is a bug, _402 is the latest available via Winget.  You can manually install the package via a .zip or .msi from Adoptium.net

**Comment by cstett** [comment]
Big thank you for confirming this! Do you think this will be fixed in later releases?

**Comment by karianna** [comment]
I'm chasing it down (but please do bug me in a week or so if I don't come back :-))

**Comment by cstett** [comment]
Hello! I wanted to check in to see what you have found. Thank you :)

**Comment by karianna** [comment]
Chasing thread...

**Comment by gdams** [comment]
The config files are here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/EclipseAdoptium/Temurin/8

Looks like someone upgraded the JDK but not the JRE (I'll handle it now)

**Comment by gdams** [comment]
Noting that it's the same for all versions, I'll get this sorted. We should perhaps consider some automation to the winget repo to ensure these stay up-to-date.

**Comment by gdams** [comment]
I've raised https://github.com/microsoft/winget-pkgs/pull/160047

Noting that I used the following command:

```bash
komac update EclipseAdoptium.Temurin.8.JRE --version 8.0.412.8 --urls https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u412-b08/OpenJDK8U-jre_x64_windows_hotspot_8u412b08.msi https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u412-b08/OpenJDK8U-jre_x32_windows_hotspot_8u412b08.msi --submit
```

**Comment by karianna** [comment]
> Noting that it's the same for all versions, I'll get this sorted. We should perhaps consider some automation to the winget repo to ensure these stay up-to-date.

Have we just manually submitted in hte past or did a Winget enthusiast pull from us?

**Comment by gdams** [comment]
> > Noting that it's the same for all versions, I'll get this sorted. We should perhaps consider some automation to the winget repo to ensure these stay up-to-date.
> 
> Have we just manually submitted in the past or did a Winget enthusiast pull from us?

AFAIK we (Adoptium) have never been responsible for the updates, the community have kindly done it for us

**Comment by karianna** [comment]
Ah OK, I do wonder if we need to take it off our docs / website in that case

**Comment by sxa** [comment]
> Ah OK, I do wonder if we need to take it off our docs / website in that case

+1 ... Or as a minimum make it absolutely clear on there that it's not an Adoptium-maintained distribution mechanism.
