### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by ineedhelp-real** [adoptium/adoptium-support#1113]
### Please provide a brief summary of the bug

I was trying to boot up my mc server and everything was going on fine but it crashed(i think) after starting. I have no idea about what may have caused this but I suspect that it might be because im playing modded. The "hs_err_pid1.log" is attached
[hs_err_pid1.log](https://github.com/user-attachments/files/15841616/hs_err_pid1.log)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

I dont know, I have no knowledge about these things

### Actual Results

I dont know, I have no knowledge about these things

### What Java Version are you using?

I do not know how to check

**Comment by karianna** [comment]
@ineedhelp-real This is a bug in the game / valkerie mod that is causing Java to crash, please report this issue to their forums.
