### ISSUE TITLE
i tried to open the SQL Console of DBeaver Extension on Eclipse whit Ctrl + Alt + Enter

### ISSUE THREAD

**Issue by guisantos-dev** [adoptium/adoptium-support#1114]
### Please provide a brief summary of the bug

[hs_err_pid9732.log](https://github.com/user-attachments/files/15859066/hs_err_pid9732.log)

### Did you test with the latest update version?

- [X] Yes

### Expected Results

I was expecting to open the SQL console of Dbeaver plugin whit Ctrl + Alt + Enter

### Actual Results

the eclipse IDE crashed, but the Spring project and H2 database continued running. When I reopened it, there was no option to stop them

### What Java Version are you using?

openjdk 17.0.11 2024-04-16 OpenJDK Runtime Environment (build 17.0.11+9) OpenJDK 64-Bit Server VM (build 17.0.11+9, mixed mode, sharing)

**Comment by karianna** [comment]
The log file indicates you're actually using 21.0.3.  Regardless, you may be experiencing #1060 

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007a4a03da9f81, pid=9732, tid=9733
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.3+9 (21.0.3+9) (build 21.0.3+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (21.0.3+9-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libgobject-2.0.so.0+0x39f81]  g_type_check_instance_is_fundamentally_a+0x11
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/sant/core.9732)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
