### ISSUE TITLE
I got errors while trying to run Java  using mac terminal, I tried to install it from Oracle but the Java version (permission denied) , may some one guide please?

### ISSUE THREAD

**Issue by AymanMkhalifa** [adoptium/adoptium-support#1118]
A fatal error has been detected by the Java Runtime Environment +  SIGSEGV (0xb) at pc=0x000000018407cdc4, pid=33891, tid=8707 JRE version:  (11.0.9.1+1) (build ) # Java VM: OpenJDK 64-Bit Server VM (11.0.9.1+1-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64) # Problematic frame: # C  [libsystem_platform.dylib+0xdc4]  _platform_strlen+0x4 # # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again # # An error report file with more information is saved as: # \/Users/aymankhalifa/hs_err_pid33891.log

**Comment by karianna** [comment]
We distribute the Eclipse Temurin builds from the Adoptium project.  Please try the Oracle forums for your question.
