### ISSUE TITLE
CRASH on start  with SIGSEGV

### ISSUE THREAD

**Issue by ekitru** [adoptium/adoptium-support#1122]
### Please provide a brief summary of the bug

(Studio 3T:1221916): Gtk-WARNING **: 09:45:26.809: Negative content width -7 (allocation 6, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
EGLDisplay Initialization failed: EGL_BAD_ACCESS
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007be1321ae072, pid=1221916, tid=1221992
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.1.so.0+0x2bae072]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E"

[hs_err_pid1221916.log](https://github.com/user-attachments/files/16025450/hs_err_pid1221916.log)

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

start Studio-3t on  ubuntu 22.04

### Expected Results

working app

### Actual Results

crashing app

### What Java Version are you using?

openjdk 21.0.3 2024-04-16

### What is your operating system and platform?

ubuntu 22.04

### How did you install Java?

standard  ubuntu openjdk pack

### Did it work before?

```Shell
yes
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
#
#  SIGSEGV (0xb) at pc=0x00007be1321ae072, pid=1221916, tid=1221992
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.1.so.0+0x2bae072]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/kitru/studio3t/core.1221916)
#
# An error report file with more information is saved as:
# /home/kitru/studio3t/hs_err_pid1221916.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[1]    1221916 IOT instruction (core dumped)  /home/kitru/studio3t/Studio-3T
```

**Comment by karianna** [comment]
See #1060 - suspect you'll find help there.
