### ISSUE TITLE
Compatibility issue with adoption jdk due to T12KeyAgreement (TLS v1.2) implementation

### ISSUE THREAD

**Issue by pradeep1794** [adoptium/adoptium-support#1126]
### Please provide a brief summary of the bug

Compatibility issue with adoption jdk due to T12KeyAgreement (TLS v1.2) implementation

OpenJDK 1.8:
ECDHE("ecdhe", ECDHKeyExchange.poGenerator, ECDHKeyExchange.ecdheKAGenerator)

Adomptium JDK 11:
ECDHE("ecdhe", ECDHKeyExchange.poGenerator, ECDHKeyExchange.ecdheXdhKAGenerator)

The use of a different SSL key agreement generator might be the cause for JDK 11 calling Luna for key derivation while JDK 1.8 does not. 

Due to this our application is failing.

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

NA

### Actual Results

NA

### What Java Version are you using?

jdk11.0.23+9 for linux 64

### What is your operating system and platform?

RHEL 7.9

**Comment by karianna** [comment]
@pradeep1794 What is the exact error your seeing?

**Comment by pradeep1794** [comment]
Hi @karianna, below is what we are getting in our PingFederate server:

> 
![image](https://github.com/user-attachments/assets/2a39ba8d-9487-4c28-98f0-37478b3eb1fa)

JFI, we are moving from Oracle java8 to open jdk 11 in our Pingfederate servers. There, PingFed's certs/keys (private) are stored in 3rd party HSM tool : safenet Luna. Now when we are trying to use the open jdk 11 , our PF servers is unable to drive the keys from HSM (The key used for server SSL cert , the key used to communicate to user data store(Microsoft AD), and all other private keys store in HSM. 

This has been checked by our Ping Vendor and also from HSM provider(Safenet luna), they indicated that its something in the open jdk's java security which is creating the issue.

**Comment by pradeep1794** [comment]
The error which we are getting is with Open jdk 11. 
We have not used Oracle Jdk 11, we were having Oracle JDK 8, which was working fine without any error.

**Comment by karianna** [comment]
> The error which we are getting is with Open jdk 11. We have not used Oracle Jdk 11, we were having Oracle JDK 8, which was working fine without any error.

OK, can you try OracleJDK 11 and see what happens, I'm trying to determine if this is a diff between the two.

**Comment by psvats1794** [comment]
Hi Karianna,
this has been fixed. The issue was not from Adoptium jdk11. It was with the product Pingfederate, which is fixed with the help of vendor. Thanks for looking into this issue 👍 :)
