### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by kencorbin** [adoptium/adoptium-support#1131]
### Please provide a brief summary of the bug

Eclipse has been crashing within minutes of being started up.  Today I tried to resolve things by wiping out my Eclipse installation and reinstalling it, only to find that the Eclipse installer also crashes immediately.

[hs_err_pid1141382.log](https://github.com/user-attachments/files/16229257/hs_err_pid1141382.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

Download latest version of Eclipse installer for Linux64 and run it.

### Expected Results

Something other than an immediate crash

### Actual Results

Immediate crash - fatal error in Java Runtime Environment

### What Java Version are you using?

openjdk 17.0.7 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314) OpenJDK 64-Bit Server VM (build 17.0.7+0-17.0.7b1000.6-10550314, mixed mode)

### What is your operating system and platform?

Ubuntu 22.04.4 LTS

### How did you install Java?

I have JAVA_HOME set to the version of Java distributed with Android Studio.  But I am pretty sure the Ecliipse installer is running it's own version of the JRE.

### Did it work before?

```Shell
Eclipse has been working find for many years.  I think this started when I installed latest set of Eclipse updates, but it might have been something completely different.
```

### Did you test with other Java versions?

```Shell
I would like to, but I don't know how to tell the installer to use a different JRE.
```

### Relevant log output

```Shell
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
EGLDisplay Initialization failed: EGL_BAD_ACCESS
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007a16ba054abf, pid=1141382, tid=1141383
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0x2c54abf]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/ken/eclipse-installer/core.1141382)
#
# An error report file with more information is saved as:
# /home/ken/eclipse-installer/hs_err_pid1141382.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by karianna** [comment]
See #1060
