### ISSUE TITLE
Fragpipe issues

### ISSUE THREAD

**Issue by Lynda-Narh** [adoptium/adoptium-support#1133]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8d5c63b51, pid=9992, tid=9028
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x563b51]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Linda\Desktop\GEN\hs_err_pid9992.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues

Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 132 remaining tasks

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

_No response_

### Expected Results

Run my data successfully without cancelling remaining tasks

### Actual Results

Not sure what's happening

### What Java Version are you using?

latest version

### What is your operating system and platform?

_No response_

### How did you install Java?

_No response_

### Did it work before?

_No response_

### Did you test with other Java versions?

_No response_

### Relevant log output

_No response_

**Comment by karianna** [comment]
@Lynda-Narh Can you try with our 17.0.11 and post back here?

**Comment by Lynda-Narh** [comment]
Hi Karianna, do you mean MsFragger v17.0.11?

**Comment by karianna** [comment]
No, the Java 17 build.  You can actually get 17.0.12 from adoptium.net now.
