### ISSUE TITLE
Wheres AdoptOpenJDK JRE with Hotspot 11.0.9.11 (x64)?

### ISSUE THREAD

**Issue by notharold** [adoptium/adoptium-support#1135]
Hello, Seems like i cant find the version on the title, i am on Windows 10.

**Comment by karianna** [comment]
go to adoptium.net for all of our downloads.

**Comment by notharold** [comment]
i cannot find it. can you send me a link

**Comment by karianna** [comment]
Ah sorry, see: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.9.1%2B1
