### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by lakechain** [adoptium/adoptium-support#1137]
### Please provide a brief summary of the bug

I got an error when running a java program, all the system information and errors are in the log file
[hs_err_pid181507.log](https://github.com/user-attachments/files/16341315/hs_err_pid181507.log)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

Program completed

### Actual Results

The program encountered an error and crashed.

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-11.0.23+9 (11.0.23+9) (build 11.0.23+9)

### What is your operating system and platform?

Intel(R) Core(TM) i5-14500, 20 cores, 62G, Ubuntu 20.04.6 LTS

**Comment by karianna** [comment]
Can you try with the recently released 11.0.24 and drop the crash log here?

**Comment by lakechain** [comment]
okie @lakechain , let me try

**Comment by lakechain** [comment]
@karianna this log here: 
[hs_err_pid18063.log](https://github.com/user-attachments/files/16343202/hs_err_pid18063.log)

**Comment by karianna** [comment]
OK, looks like the org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner is triggering this in both cases.  What version of Hadoop are you using?

**Comment by lakechain** [comment]
I'm using Hadoop version 3.3.4

**Comment by karianna** [comment]
Do you have the ability to move to 3.3.6?  There's a bunch of fixes with the transitive dependencies (especially for the ASM lib which is also caught up in this crash.)

**Comment by lakechain** [comment]
Thank @karianna, Let me try

**Comment by lakechain** [comment]
@karianna I have switched to Hadoop 3.3.6, but the problem still occurs, although it is not as frequent as before.
[hs_err_pid1345206.log](https://github.com/user-attachments/files/16355721/hs_err_pid1345206.log)

**Comment by karianna** [comment]
Do you know if the Core dump gets generated?  The log says it would be at:

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/hadoop/projects/chainslake/core/run/ethereum/core.1345206)
