### ISSUE TITLE
OpenJDK8U-jdk_x64_mac_hotspot_8u422b05.pkg is not signed

### ISSUE THREAD

**Issue by l2dy** [adoptium/adoptium-support#1139]
### Please provide a brief summary of the bug

Could not install JDK 8 from Adoptium.

### Did you test with the latest update version?

- [X] Yes

### Expected Results

.pkg installer opens successfully.

### Actual Results

<img width="371" alt="Screenshot 2024-0" src="https://github.com/user-attachments/assets/c074092c-058d-44fa-ad36-710daa26e548">

### What Java Version are you using?

8u422b05

### What is your operating system and platform?

macOS 14.5 on x86-64

### Relevant log output

```Shell
Package "OpenJDK8U-jdk_x64_mac_hotspot_8u422b05.pkg":
   Status: no signature
```

**Comment by karianna** [comment]
@gdams for initial triage

**Comment by gdams** [comment]
I can confirm that I also get this issue

**Comment by gdams** [comment]
Looking at https://ci.adoptium.net/job/build-scripts/job/release/job/sign_verification/1482/console is seems to suggest that the PKG was signed correctly when built

```output
Signed correctly: ./OpenJDK8U-jdk_x64_mac_hotspot_8u422b05.pkg
Notarized correctly: ./OpenJDK8U-jdk_x64_mac_hotspot_8u422b05.pkg
Package "OpenJDK8U-jre_x64_mac_hotspot_8u422b05.pkg":
   Status: signed by a developer certificate issued by Apple for distribution
   Notarization: trusted by the Apple notary service
   Signed with a trusted timestamp on: 2024-07-24 22:06:20 +0000
   Certificate Chain:
    1. Developer ID Installer: Eclipse Foundation, Inc. (JCDTMS22B4)
       Expires: 2024-08-26 17:22:33 +0000
       SHA256 Fingerprint:
           FD A7 11 E1 1F 78 34 D1 98 51 CC 38 35 6A 03 9F A1 35 3A 60 63 3F 
           F9 0F 1C 27 E2 29 E1 0A 26 7B
       ------------------------------------------------------------------------
    2. Developer ID Certification Authority
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
           F2 9C 88 CF B0 B1 BA 63 58 7F
       ------------------------------------------------------------------------
    3. Apple Root CA
       Expires: 2035-02-09 21:40:36 +0000
       SHA256 Fingerprint:
           B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
           68 C5 BE 91 B5 A1 10 01 F0 24
```

**Comment by gdams** [comment]
Looks like https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/job/jdk8u-release-mac-x64-temurin/28/console had a failed installer sign job though, I suspect the wrong artefact was published

**Comment by karianna** [comment]
This has since been resolved and a new pkg released
