### ISSUE TITLE
Keytool not prompting password

### ISSUE THREAD

**Issue by ding-ma** [adoptium/adoptium-support#1145]
### Please provide a brief summary of the bug

When listing cacerts, the keytool is not prompting for password. I have noticed this problem in both Java 17 and 21.
`keytool -list -cacerts`, the content prints out instead of asking for the password `changeit`. When trying to add a certificate, the keytool does not ask for a password either

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

1. pull docker image or download binaries
2. keytool -list -cacerts

### Expected Results

The password should be prompted

### Actual Results

The content is printed out, and I can also add ca-certs without password.

### What Java Version are you using?

root@7dc840bb1f74:/# java --version openjdk 21.0.4 2024-07-16 LTS OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

### What is your operating system and platform?

docker.

 podman run -it eclipse-temurin:21.0.4_7-jre bash

### How did you install Java?

inside docker image.

### Relevant log output

```Shell
root@00a872596f2c:/opt/java/openjdk/bin# keytool -list -keystore -cacerts
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 148 entries

c_de,o_atos,cn_atos_trustedroot_2011 [jdk], Aug 5, 2024, trustedCertEntry,
Certificate fingerprint (SHA-256): F3:56:BE:A2:44:B7:A9:1E:B3:5D:53:CA:9A:D7:86:4A:CE:01:8E:2D:35:D5:F8:F9:6D:DF:68:A6:F4:1A:A4:74
```

**Comment by karianna** [comment]
@ding-ma Do you have this same issue with a build from another vendor?

**Comment by karianna** [comment]
Also from GPT-4o:

------

The behavior you're experiencing with `keytool` not prompting for a password when listing or adding certificates to the `cacerts` keystore can be due to several reasons. Let's go through some potential causes and solutions:

1. **Default Keystore Password**:
    - The `cacerts` keystore usually has a default password of `changeit`. If the keystore password has not been changed from this default, `keytool` might not prompt for it explicitly.

2. **Permissions and User Privileges**:
    - Ensure that the user running the `keytool` command has the necessary permissions to access and modify the keystore file. If the keystore file has read and write permissions set for the user, it might not prompt for a password.

3. **Environment Configuration**:
    - Check if there are any environment variables or configuration files setting a default password for the `keytool`. Sometimes, the password can be provided through scripts or configuration settings.

4. **Keytool Version and Java Configuration**:
    - There might be differences in how different versions of `keytool` and Java handle password prompts. Make sure you are using the correct version of `keytool` corresponding to your Java installation.

5. **Corrupted Keystore**:
    - If the keystore is corrupted or in an inconsistent state, it might not prompt for a password correctly. You can try creating a new keystore and see if the issue persists.

### Steps to Diagnose and Resolve:

1. **Check Default Password**:
    ```sh
    keytool -list -cacerts -storepass changeit
    ```
    If this works without prompting for a password, the keystore is using the default password.

2. **Change Keystore Password**:
    ```sh
    keytool -storepasswd -keystore <path_to_cacerts>
    ```
    Follow the prompts to change the password.

3. **Verify Permissions**:
    - Check the permissions of the `cacerts` file:
      ```sh
      ls -l $(dirname $(readlink -f $(which java)))/../lib/security/cacerts
      ```
    - Ensure the user has the necessary read and write permissions.

4. **Check for Environment Variables**:
    - Look for any environment variables related to `keytool` or `JAVA_OPTS` that might be setting the password.

5. **Try with Different Java Version**:
    - If possible, switch to a different version of Java and see if the behavior changes.

6. **Create a New Keystore**:
    ```sh
    keytool -genkeypair -alias test -keystore newkeystore.jks
    ```
    Follow the prompts to create a new keystore and see if it asks for a password.

By following these steps, you should be able to diagnose why `keytool` is not prompting for a password and take appropriate action to resolve the issue.

**Comment by ding-ma** [comment]
I did some digging, it's very inconsistent amongst the java releases.

In the google distroless project, java 17 is based off of the debian release. It does prompt for the password if you do not give the flag `storepass`


```
podman run -it --entrypoint /busybox/sh  gcr.io/distroless/java17-debian12:debug
/ # .//usr/lib/jvm/java-17-openjdk-arm64/bin/keytool -list -cacerts
Enter keystore password:
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 139 entries

1.2.840.113549.1.9.1=#1610696e666f40652d737a69676e6f2e6875,cn=microsec e-szigno root ca 2009,o=microsec ltd.,l=budapest,c=hu, Jun 16, 2009, trustedCertEntry,
Certificate fingerprint (SHA-256): 3C:5F:81:FE:A5:FA:B8:2C:64:BF:A2:EA:EC:AF:CD:E8:E0:77:FC:86:20:A7:CA:E5:37:16:3D:F3:6E:DB:F3:78
c=de,o=atos,cn=atos trustedroot 2011, Jul 7, 2011, trustedCertEntry,
```

The amazon release (corretto) does not prompt for the password

```
podman run -it amazoncorretto:21 bash
bash-4.2# ./usr/lib/jvm/java/bin/keytool -list -cacerts
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 159 entries

accvraiz1, Aug 5, 2024, trustedCertEntry,
Certificate fingerprint (SHA-256): 9A:6E:C0:12:E1:A7:DA:9D:BE:34:19:4D:47:8A:D7:C0:DB:18:22:FB:07:1D:F1:29:81:49:6E:D1:04:38:41:13
acraizfnmt-rcm, Aug 5, 2024, trustedCertEntry,
```

IBM release does prompt for password
```
podman run -it ibm-semeru-runtimes:open-17-jdk-jammy
root@2bb33b6fe51b:/# /opt/java/openjdk/bin/keytool -list -cacerts
Enter keystore password:
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 147 entries

c_de,o_atos,cn_atos_trustedroot_2011 [jdk], Jul 7, 2011, trustedCertEntry,
```

**Comment by ding-ma** [comment]
On the releases that does not require a password, even if you change the password with `keytool -storepasswd -cacerts` to something else, and try to list the cacerts, it does not. 

```
bash-4.2# ./usr/lib/jvm/java/bin/keytool -storepasswd -cacerts -new 123456 -storepass changeit
bash-4.2# ./usr/lib/jvm/java/bin/keytool -list -cacerts
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 159 entries

bash-4.2# ./keytool -list -cacerts -storepass wrongpass
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 159 entries
```

On the correct release, IBM/Google, the password is prompted

```
root@f471499dcd3d:/#  keytool  -storepasswd -cacerts -new 123456 -storepass changeit
root@f471499dcd3d:/# keytool  -list -cacerts -storepass 123456
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 147 entries

root@f471499dcd3d:/# keytool  -list -cacerts -storepass wrongpwd
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
```

**Comment by karianna** [comment]
Hmm, this does seem inconsistent across vendors etc.  I'm not an expert in this space, so I think we'll need to have one of the team reproduce this and try to understand why.

**Comment by karianna** [comment]
One quick Q.  Does the problem exist if you download a binary and run it manually on a VM/Host without using Docker/Podman?

**Comment by ding-ma** [comment]
yes, the problem is there. I downloaded JRE 17 amd64.

```
~/jdk-21.0.4+7-jre/bin$ ./keytool  -list -cacerts
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 148 entries

~/jdk-21.0.4+7-jre/bin$ ./keytool -storepasswd -cacerts -new 123456 -storepass changeit
~/jdk-21.0.4+7-jre/bin$ ./keytool -list -cacerts
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 148 entries

~/jdk-21.0.4+7-jre/bin$ ./keytool -list -cacerts -storepass wrongpwd
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 148 entries
```

The password should be asked. A wrong password should not allow the user to access the keystore.

**Comment by karianna** [comment]
Sorry to keep asking for more testing.  I notice you grabbed the JRE, what happens if you download and run a jdk?

**Comment by ding-ma** [comment]
same problem, i tried on https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz

**Comment by jiekang** [comment]
For the listing of contents is this bug relevant?
https://bugs.openjdk.org/browse/JDK-8141612

It still seems to apply in the newer documents [1] as the text is still there:
```
When retrieving information from the keystore, the password is optional. If a password is not specified, then the integrity of the retrieved information can't be verified and a warning is displayed.
```

[1]
https://docs.oracle.com/en/java/javase/21/docs/specs/man/keytool.html

**Comment by ding-ma** [comment]
Also, no warning is displayed if no password is entered, which does not match oracle's doc. In the IBM java release, it does show a warning

```
root@169e1793ef61:/# /opt/java/openjdk/bin/keytool -list -cacerts -storepass 123456
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
root@169e1793ef61:/# /opt/java/openjdk/bin/keytool -list -cacerts
Enter keystore password:

*****************  WARNING WARNING WARNING  *****************
* The integrity of the information stored in your keystore  *
* has NOT been verified!  In order to verify its integrity, *
* you must provide your keystore password.                  *
*****************  WARNING WARNING WARNING  *****************

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 147 entries
```

**Comment by jiekang** [comment]
I think Temurin uses a non-default cacerts file from Mozilla and we may need to adjust it to have a default password to behave more in line with upstream OpenJDK expectations.

This is from some manual tests I've done comparing a Fedora OpenJDK to a downloaded Temurin 21 JDK using the keytool binaries from both and trying to manipulate each other's cacerts files.

The Temurin cacerts keystore has no password (explaining the lack of warning and other behavior) and I am not able to set a password for it via either `keytool` binary, unlike the upstream cacerts file in Fedora OpenJDK, which I could manipulate properly (successfully change the password) with both `keytool` binaries.

Following: https://stackoverflow.com/questions/15093440/change-keystore-password-from-no-password-to-a-non-blank-password

I was able to import the cacerts to a new cacerts2 and then manipulate that okay, though the certs are no longer visible when supplying no password (which is probably a nice thing?)
```
/keytool -importkeystore -srckeystore ~/Downloads/jdk-21.0.4+7/lib/security/cacerts -destkeystore cacerts2 -deststorepass 123456
```

This `cacerts2` behaved better when manipulated by `keytool`

**Comment by jiekang** [comment]
@andrew-m-leonard ^ Thoughts?

**Comment by ding-ma** [comment]
as a workaround, we can do the following
```
~/jdk-21.0.4+7/bin$ ./keytool -importkeystore -srckeystore ../lib/security/cacerts -destkeystore ../lib/security/cacerts2 -deststorepass changeit
Importing keystore ../lib/security/cacerts to ../lib/security/cacers2...
[ommitted...]
~/jdk-21.0.4+7/bin$ rm ../lib/security/cacerts
~/jdk-21.0.4+7/bin$ mv ../lib/security/cacerts2 ../lib/security/cacerts

~/jdk-21.0.4+7/bin$ ./keytool -list -cacerts -storepass 123456
keytool error: java.io.IOException: keystore password was incorrect

~/jdk-21.0.4+7/bin$ ./keytool -list -cacerts
Enter keystore password:

*****************  WARNING WARNING WARNING  *****************
* The integrity of the information stored in your keystore  *
* has NOT been verified!  In order to verify its integrity, *
* you must provide your keystore password.                  *
*****************  WARNING WARNING WARNING  *****************

Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 0 entries



~/jdk-21.0.4+7/bin$ ./keytool -list -cacerts -storepass changeit
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 149 entries
```

What is interesting of this approach is that it reports are the keystore having 0 entries when no password is entered. It's still a different behavior as the IBM Java.

**Comment by jiekang** [comment]
SO comment in [1] mentions:

"[...] I also noticed that different store types treats the password in different ways. While providing no password for JKS type just results in unavailability to check the store integrity, providing no password for PKCS12 keystore results in empty list (when use keytool -list) so that there is no chance to use the store if you do not know the password."

[1] https://stackoverflow.com/questions/2343691/do-you-not-need-a-password-to-access-a-truststore-made-with-the-java-keytool

**Comment by andrew-m-leonard** [comment]
Hi @ding-ma , thank you for reporting this issue. I have done some investigations, and this is working as designed, the lib/security/cacerts is now a "password-less" PKCS12 rather than the old JKS format that had a "changeit" password.
The bug documenting this change is here: https://bugs.openjdk.org/browse/JDK-8275253?jql=text%20~%20%22password-less%22
The current "docs" are not correct, there is an existing bug to update them with the password-less PKCS12 description here: https://bugs.openjdk.org/browse/JDK-8275306 which is still Open.
Here is the suggested new text from that bug:
```
The cacerts keystore file is released as a password-less PKCS12 file. System administrators should change the default access permission of that file upon installing the SDK. 
```

The reason some providers are different is because of the way some providers build the JDK default cacerts file. IBM Semeru and Google will no doubt be using a different set of cacerts, if they build their own cacerts file using keytool using a "changeit" password as historically was the case, then it will still have it.

**Comment by ding-ma** [comment]
Thank you for clarifying and going to the bottom of this!

**Comment by ding-ma** [comment]
Marking as closed.
