### ISSUE TITLE
Support for jdk-17.0.13

### ISSUE THREAD

**Issue by thameenas** [adoptium/adoptium-support#1149]
## Question

When will the image for jdk-17.0.13 be released?
https://github.com/openjdk/jdk17u/releases/tag/jdk-17.0.13%2B2

## Context

Java version: 17
There was a recent amendment in the Currency package that was published as a part of jdk-17.0.13:
https://bugs.openjdk.org/browse/JDK-8334653

Since this is a currency change which we needed to support in our application as soon as possible, is it possible that this image version will be released any time soon for eclipse-temurin? I can see that the last version published is of 17.0.12_7: 
https://hub.docker.com/_/eclipse-temurin/tags?page=&page_size=&ordering=&name=17

**Comment by karianna** [comment]
17.0.3 will be release ~Oct 20th in line with hte quarterly update cycle of OpenJDK update projects.
