### ISSUE TITLE
Eclipse C/C++ with ESP-IDF CRASH

### ISSUE THREAD

**Issue by Mekon3** [adoptium/adoptium-support#1150]
### Please provide a brief summary of the bug

Not much to go on except I suggest it's a size problem. Just my code is over 5000 lines and either the project I'm working on (window) will disappear, or the whole PC will freeze and do a kernel dump. (Not nice!) Even though I'm using my non-privileged user.
I started with a clean install of Ubuntu, (16GB of RAM), with the express desire to get Eclipse and/or Espressif-IDE  + ESP-IDF running with their respective latest versions.

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

Steps? Load up a LARGE project and start working .... I imagine the process will bomb out sooner or later. 
There are many "errors" in the code, migration related mostly, and "Mouse-over" an error in the code, for example can bring on the failure.

### Expected Results

I expect "nothing" to happen, I expect to keep working as I did with "last years" versions.

### Actual Results

[hs_err_pid18822.log](https://github.com/user-attachments/files/16548256/hs_err_pid18822.log)

### What Java Version are you using?

java 21.0.4 2024-07-16 LTS

### What is your operating system and platform?

Ubuntu 24.04 LTS on x86_64

### How did you install Java?

I used the package manager to install "jdk-21_linux-x64_bin.deb"

### Did it work before?

```Shell
its a clean install
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by karianna** [comment]
See #1060
