### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by abdullahil-kafi** [adoptium/adoptium-support#1152]
### Please provide a brief summary of the bug

Eclipse IDE 2023.12R crashes with open JDK 17 on ubuntu 22.04. For dependency purpose, I need this specific version of Eclipse IDE.
[hs_err_pid20641.log](https://github.com/user-attachments/files/16609637/hs_err_pid20641.log)

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

On a fresh Ubuntu 22.04, install `openjdk-17-jdk` and `openjdk-17-jre`. Download and install Eclipse for Committers from [here](https://www.eclipse.org/downloads/packages/release/2023-12/r/eclipse-ide-eclipse-committers). Open a java project and hover over any keyword.

### Expected Results

Upon hovering over a keyword with mouse, the result for the hover is expected.

### Actual Results

The IDE crashes.

### What Java Version are you using?

openjdk 17.0.12 2024-07-16 OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04) OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04 on AMD Ryzen 7 7730U with Radeon Graphics.

### How did you install Java?

`sudo apt install openjdk-17-jdk openjdk-17-jre`

### Did it work before?

```Shell
This is the first time I am using the Eclipse IDE. I cannot confirm it.
```

### Did you test with other Java versions?

```Shell
No.
```

**Comment by karianna** [comment]
See #1060
