### ISSUE TITLE
Solaris jdk8u402-b06 A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by ravindrar** [adoptium/adoptium-support#1153]
### Please provide a brief summary of the bug

Hello , 

We are process of migrating to open jdk and are using jdk8u402-b06 with apache-tomcat-9.0.87. 
We have tomcats in cluster. After  JSP was deployed  , we could see both the tomcats crashing with in 10 min. 

Attached is the error log. 

We tried redeploying for recreating the issue , however we could not . 

Please look in to the error logs and suggest best resolution.
[hs_err_pid16379-.log](https://github.com/user-attachments/files/16620978/hs_err_pid16379-.log)

Best Regards,
Ravindra 

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

Our application works with normally with out tomcat / jre crash

### Actual Results

Jre crash has caused tomcat to shutdown bringing  down our web application. 

### What Java Version are you using?

8.0_402-b06

### What is your operating system and platform?

SunOS 5.11 11.4.70.170.1

### How did you install Java?

We use binary archive

### Did it work before?

```Shell
We have open jdk for some time and it works most of the time. After the server restart , we have not seen the issue in past 24 hours .
```

### Did you test with other Java versions?

```Shell
we keep upgrading jre once in 3 months . 
The latest we are using is 8.0_402-b06 and will soon update to 8.0.422+5
https://adoptium.net/temurin/releases/?os=solaris&arch=sparcv9&package=jre&version=8
```

### Relevant log output

```Shell
Please see the attachment in the main ticket.
```

**Comment by karianna** [comment]
This can happen if the zip file is being overridden whilst being processed.  Try adding -Dsun.zip.disableMemoryMapping=true to teh Java command line next time you run

**Comment by ravindrar** [comment]
Hello , We added -Dsun.zip.disableMemoryMapping=true and the issue has not appeared again so far. 

Thank you .
