### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by foodisready** [adoptium/adoptium-support#1154]
### Please provide a brief summary of the bug

```#
#  SIGSEGV (0xb) at pc=0x000000010e707000, pid=77078, tid=16131
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.11+9 (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (17.0.11+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libnative-platform-file-events.dylib+0x0]  __dso_handle+0x0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again```
[hs_err_pid2468.log](https://github.com/user-attachments/files/16646523/hs_err_pid2468.log)


### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

Using latest BubbleWrap to package a PWA
```
Building the Android App...

cli ERROR Command failed: ./gradlew assembleRelease --stacktrace
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=d20dedab-8327-4d30-ace0-e5b53828e0d7, currentDir=/project1/sandbox/sff-pwa}
Attempting to read last messages from the daemon log...
Daemon pid: 21552
  log file: /project1/.gradle/daemon/8.8/daemon-21552.out.log
----- Last  20 lines from daemon log file - daemon-21552.out.log -----
For more information refer to the compatibility table:
https://d.android.com/r/tools/api-level-support

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=35
to this project's gradle.properties.
Checking the license for package Android SDK Platform 35 in /project1/.bubblewrap/android_sdk/licenses
License for package Android SDK Platform 35 accepted.
Preparing "Install Android SDK Platform 35 (revision 1)".
"Install Android SDK Platform 35 (revision 1)" ready.
Installing Android SDK Platform 35 in /project1/.bubblewrap/android_sdk/platforms/android-35
"Install Android SDK Platform 35 (revision 1)" complete.
"Install Android SDK Platform 35 (revision 1)" finished.
Checking the license for package Android SDK Platform-Tools in /project1/.bubblewrap/android_sdk/licenses
License for package Android SDK Platform-Tools accepted.
Preparing "Install Android SDK Platform-Tools v.35.0.2".
"Install Android SDK Platform-Tools v.35.0.2" ready.
Installing Android SDK Platform-Tools in /project1/.bubblewrap/android_sdk/platform-tools
"Install Android SDK Platform-Tools v.35.0.2" complete.
"Install Android SDK Platform-Tools v.35.0.2" finished.
----- End of the daemon log -----

JVM crash log found: file:///project1/sandbox/sff-pwa/hs_err_pid21552.log
```

### Expected Results

Expect to build successfully

### Actual Results

Build failed with exception
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

### What Java Version are you using?

17.0.11

### What is your operating system and platform?

MacOS Big Sur 11.7.10

### How did you install Java?

BubbleWrap install it.

### Did it work before?

```Shell
First time trying it out
```

**Comment by karianna** [comment]
Please try 17.0.12 but note that you are using an EOL Mac OS X version.

**Comment by foodisready** [comment]
Hi @karianna, thanks, but am still getting the same error with 17.0.12 :-(.  Does that mean I need to get a new Mac?

**Comment by karianna** [comment]
Mac OS X 11 is EOL (September 26, 2023) - we do in theory still support it (https://adoptium.net/en-GB/supported-platforms/) but I suspect that will be dropped shortly.
