### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by tmmlsBE** [adoptium/adoptium-support#1158]
### Please provide a brief summary of the bug

'#  A fatal error has been detected by the Java Runtime Environment:

'#  SIGSEGV (0xb) at pc=0x00000003295ae1bc, pid=9742, tid=259
'#
'# JRE version: OpenJDK Runtime Environment Temurin-21.0.4+7 (21.0.4+7) (build 21.0.4+7-LTS)
'# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (21.0.4+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
'# Problematic frame:
'# C  [libjfxwebkit.dylib+0xc421bc]  WebCoreTestSupport::allowsAnySSLCertificate()+0x8e21f4
'#
'# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
'#
'# An error report file with more information is saved as:
'# [REMOVED]
[21.090s][warning][os] Loading hsdis library failed
'#
'# If you would like to submit a bug report, please visit:
'#   https://github.com/adoptium/adoptium-support/issues
'# The crash happened outside the Java Virtual Machine in native code.
'# See problematic frame for where to report the bug.
'#
Disconnected from the target VM, address: '127.0.0.1:51346', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

// The crash appears when reloading the webengine url ... 

webEngine.locationProperty().addListener(
                new ChangeListener<String>() {
                    @Override public void changed(ObservableValue ov, String oldState, String newState) {
                        if(oldState != null){
                            if (!oldState.equals(newState)) {

                            }
                        }
                    }

### Expected Results

url should be reloaded

### Actual Results

Crash 

### What Java Version are you using?

 21.0.4

### What is your operating system and platform?

Os X 14.5, Java 21.0.4, JavaFX 21.0.4

### Did you test with other Java versions?

```Shell
Java 17 (latest) + JavaFX (latest)
```

**Comment by karianna** [comment]
@tmmlsBE This ia. crash in OpenJFX, you'll need to report this over to them.  SEe https://github.com/openjdk/jfx for the steps
