### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by ajith-nataraj** [adoptium/adoptium-support#1161]
### Please provide a brief summary of the bug
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007f78b67fdb3c, pid=16857, tid=17046

 JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
 Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 V  [libjvm.so+0xc01b3c]  compute_tree_cost(SwitchRange*, SwitchRange*, float)+0x21c

No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
If you would like to submit a bug report, please visit:
https://github.com/AdoptOpenJDK/openjdk-support/issues

[hs_err_pid16857.log](https://github.com/user-attachments/files/16860019/hs_err_pid16857.log)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

No crash 

### Actual Results

Crashed once yesterday after running for a long time(3years).
we are running this is Elastic search 7x 

### What Java Version are you using?

openjdk 11.0.9.1 2020-11-04 OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2) OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 18.04 on amd64
4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

### Did it work before?

```Shell
yes
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f78b67fdb3c, pid=16857, tid=17046
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc01b3c]  compute_tree_cost(SwitchRange*, SwitchRange*, float)+0x21c
#
root@Es-7x-06:/var/log/elasticsearch# head -n 20 hs_err_pid16857.log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f78b67fdb3c, pid=16857, tid=17046
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc01b3c]  compute_tree_cost(SwitchRange*, SwitchRange*, float)+0x21c
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms8022m -Xmx8022m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/elasticsearch-7380624113833672016 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${heap.dump.path} -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m -XX:MaxGCPauseMillis=500 -XX:G1HeapRegionSize=4m -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:MaxDirectMemorySize=4206886912 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=default -Des.distribution.type=deb -Des.bundled_jdk=true org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet
```

**Comment by karianna** [comment]
@ajith-nataraj Java 14 is not supported, please move to Java 17 LTS release.

**Comment by ajith-nataraj** [comment]
@karianna can I please know what could have happened here.
