### ISSUE TITLE
AdoptOpenJDK.IcedTea-Web pre-req in Winget is AdoptOpenJDK.OpenJDK.8

### ISSUE THREAD

**Issue by cstett** [adoptium/adoptium-support#1162]
When installing AdoptOpenJDK.IcedTea-Web through Winget it looks like there is a pre-req of AdoptOpenJDK.OpenJDK.8. My question is, are there plans to update the pre-req to the EclipseAdoptium JDK 8?

**Comment by karianna** [comment]
That's not something that the Adoptium project looks after anymore - @hendrikebbers is that something you can look into?
