### ISSUE TITLE
SIGSEGV (0xb) at pc=0x00000000000011e0, pid=1455, tid=1552

### ISSUE THREAD

**Issue by iv-the-red** [adoptium/adoptium-support#1164]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000011e0, pid=1455, tid=1552
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.4+7 (21.0.4+7) (build 21.0.4+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (21.0.4+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# C  [native-1075383487882941609.so+0x1ae4]  sort_symbols+0x54
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /homeassistant/mc-purpur/core.1455)
#
# An error report file with more information is saved as:
# /homeassistant/mc-purpur/hs_err_pid1455.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[1]    1453 abort      sudo java -Xmx3324M -Xms3324M --add-modules=jdk.incubator.vector -jar  nogui

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

Sorry not possible.

### Expected Results

When a client connects to a java server, it should not crash. (tested on other mashines)

### Actual Results

Java crashes

### What Java Version are you using?

openjdk 21.0.4 2024-07-16 LTS OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

### What is your operating system and platform?

Linux mint

### How did you install Java?

1. wget -O /etc/apk/keys/adoptium.rsa.pub https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk
2. echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >> /etc/apk/repositories
3. apk add temurin-21-jdk

### Did it work before?

```Shell
It worked on the same java version on another mashine with the same linux distro
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
Null
```

**Comment by karianna** [comment]
@Ivthered-123ivopp  Can you upload /homeassistant/mc-purpur/hs_err_pid1455.log ?

**Comment by Ivthered-123ivopp** [comment]
[hs_err_pid1817.log](https://github.com/user-attachments/files/16926206/hs_err_pid1817.log)
@karianna Here, i attached it to this message.

**Comment by karianna** [comment]
@Ivthered-123ivopp You're running JFR and async profiler at the same time, both of which can interfere with native code and cause crashes.  Are you able to run this without attaching both of those?

**Comment by Ivthered-123ivopp** [comment]
No, i don't think so sadly.
