### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by adambaranec** [adoptium/adoptium-support#1169]
### Please provide a brief summary of the bug

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa405dd1cc, pid=25176, tid=12996

JRE version: OpenJDK Runtime Environment Temurin-17.0.8+7 (17.0.8+7) (build 17.0.8+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (17.0.8+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  [igxelpicd64.dll+0x30d1cc]

No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

I expected it to work

### Actual Results

It crashed

### What Java Version are you using?

Java 17.0.8

### What is your operating system and platform?

Windows 11 64-bit x64

**Comment by karianna** [comment]
@adambaranec Please try with 17.0.12 and post back here.

**Comment by gabepikamole** [comment]
hey, having sort of a similar issue, but the post got closed immediately. i'm using the last version and all that, but have no idea why it happens. doesn't seem to cause any issue besides just crashing, as i was able to boot and play like as if nothing happened after

**Comment by karianna** [comment]
@gabepikamole what is the application you are running?
