### ISSUE TITLE
Feather client downloading issue

### ISSUE THREAD

**Issue by zequ0** [adoptium/adoptium-support#1179]
Guys can you help me when i am trying to download for example 1.17.1 fabric version in feather client it says it will take me 2 hour when I on speed test have over 150 mbs but in feather only 0.03 mbs. W
windows 10 
![Screenshot_2](https://github.com/user-attachments/assets/4f7e63f0-60ae-4af7-b3d1-e99f75abe2af)

**Comment by jowuast95** [comment]
same here you found a solution?

**Comment by karianna** [comment]
Please contact the folks behind the Feather installer for this one
