### ISSUE TITLE
Eclipse Temurin JDK/JRE 17.0.13+11 aarch64 (macOS ARM) version is not notarised and not signed

### ISSUE THREAD

**Issue by inglenny** [adoptium/adoptium-support#1181]
**Eclipse Temurin 17.0.13+11 aarch64 (macOS ARM) version is not notarised and not signed.**

The recent update of Eclipse Temurin 17 seems to have an issue during build process.

JDK/JRE 17.0.13+11 macOS ARM version (aarch64) is not signed and not notarised. 
JDK/JRE 17.0.13+11 macOS Intel version (x64) is signed and notarised.

Could you trigger the build process for  aarch64 again? 

macOS aarch64
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/db3f9f3b-5c91-469c-bb63-686f06f66e80">

macOS x64
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/9365da6c-1faf-4ace-9ad2-a6247bb312b6">

Thanks

### Did you test with the latest update version?

- [x] Yes

### Please provide steps to reproduce where possible

Download latest aarch64 version from website(https://adoptium.net/temurin/releases/?os=mac&arch=aarch64&version=17) or github (https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.13%2B11)

### Expected Results

JDK/JRE 17.0.13+11 aarch64 pkg to be signed (and notarised).

### Actual Results

JDK/JRE 17.0.13+11 aarch64 pkg is not signed and not notarised (notarisation is only possible when pkg is signed)

### What Java Version are you using?

17.0.13+11

### What is your operating system and platform?

macOS ARM (aarch64)

### How did you install Java?

automatic installation with pkg installer

### Did it work before?

```Shell
Last version(jdk/jre 17.0.12+7) of pkg is signed.
```

### Did you test with other Java versions?

```Shell
Last version(jdk/jre 17.0.12+7) of pkg is signed.
```

**Comment by andrew-m-leonard** [comment]
@inglenny thank you for highlighting, there was a problem uploading, we have just re-freshed the binaries, and all should be good now.

**Comment by inglenny** [comment]
@andrew-m-leonard Thank you! I just tried again and can confirm it is now signed and notarised.
