### ISSUE TITLE
PDB files for Adoptium build

### ISSUE THREAD

**Issue by GazziFX** [adoptium/adoptium-support#1182]
## Question

I need PDB files for debugging

## Context

Java version:

OpenJDK 9+181

Your operating system and platform:

Windows 10 22H2 19045.5011 x86_64

**Comment by karianna** [comment]
For which versions out of interest?

**Comment by GazziFX** [comment]
> For which versions out of interest?

JDK 9+181

**Comment by karianna** [comment]
That version is no longer supported I'm afraid.  Is there an LTS version (11, 17, 21) that you require this work?

**Comment by sxa** [comment]
Noting that for currently supported versions versions there are PDB downloads available in a "debugimage" tarball.
