### ISSUE TITLE
The repository 'https://packages.adoptium.net/artifactory/deb focal InRelease' is no longer signed

### ISSUE THREAD

**Issue by asreich** [adoptium/adoptium-support#1199]
### Please provide a brief summary of the bug

`apt update` fails for an unknown reason after 3:40 PM Central

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

Attempt to apt-update on Ubuntu 20.0 after having the following in your source.list:

`deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb focal main`

### Expected Results

`apt update` command should succeed

### Actual Results

`apt update` fails with "The repository 'https://packages.adoptium.net/artifactory/deb focal InRelease' is no longer signed" and "Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)"

### What Java Version are you using?

11

### What is your operating system and platform?

Ubuntu 20.04, amd64

### How did you install Java?

`apt install temurin-11-jre`

### Did it work before?

```Shell
Yes, it worked prior to 3:40 PM Central Time 12/2/24
```

### Did you test with other Java versions?

No

### Relevant log output

```Shell
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:4 https://apt.puppet.com focal InRelease
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Hit:2 https://artifactory.adtechlabs.com/artifactory/debian focal InRelease
Get:6 https://packages.adoptium.net/artifactory/deb focal InRelease
Err:6 https://packages.adoptium.net/artifactory/deb focal InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:7 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]
Get:8 http://nova.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease [128 kB]
Reading package lists... Done
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/dists/focal/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.adoptium.net/artifactory/deb focal InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Other Troubleshooting

Based on the availability check we have, latency increased around 3:40PM Central Time.

![image](https://github.com/user-attachments/assets/9f1ea26a-e7f4-420b-81dd-b9353abf6fd8)

I've diffed the current and available keys (.asc) and there is no difference in the public GPG key which I had thought maybe expired and we had a chicken/egg scenario but they are still identical. Happens outside of our datacenters as well. I've found a way to proxy this through our JFrog SaaS instead but I understand this is also backed by JFrog Artifactory so I'm confused why packages.adoptium.net -> our JFrog SaaS -> user works but not packages.adoptium.net -> user?

**Comment by labkey-stuartm** [comment]
Similar issue with Java 17 on Ubuntu 20.04 and 24.04.1

**Comment by bpiper** [comment]
For some bizarre reason, Artifactory is redirecting the request to `/ui/native/deb/dists/jammy/InRelease` when the `User-Agent` header starts with `Debian`.  See the below output from running `apt-get -o Debug::Acquire::https=true update`.  This seems like a proxy misconfiguration or something like that (I'm not aware that Artifactory itself redirects based on User-Agent).

```
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                   
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                 
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                               
0% [Connected to packages.adoptium.net (104.18.21.66)]GET /artifactory/deb/dists/jammy/InRelease HTTP/1.1                      
Host: packages.adoptium.net
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (2.4.13) non-interactive


Answer for: https://packages.adoptium.net/artifactory/deb/dists/jammy/InRelease
HTTP/1.1 302 Found
Date: Tue, 03 Dec 2024 05:00:39 GMT
Content-Length: 0
Connection: keep-alive
retry-after: 0
location: /ui/native/deb/dists/jammy/InRelease
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-iad-kiad7000176-IAD
x-cache: HIT
x-cache-hits: 0
x-timer: S1733202039.461023,VS0,VE0
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 8ec0fe8a7c74575e-IAD
alt-svc: h3=":443"; ma=86400
```

**Comment by alno74d** [comment]
> Similar issue with Java 17 on Ubuntu 20.04 and 24.04.1

same issue here.

**Comment by nsd4npo** [comment]
same and https://packages.adoptium.net/artifactory/api/gpg/key/public is empty

**Comment by charmbv** [comment]
Same issue while building a Docker image using latest Ubuntu and JDK 21.

**Comment by alno74d** [comment]
> same and https://packages.adoptium.net/artifactory/api/gpg/key/public is empty

for me wget works:
wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public

but browser requires login

**Comment by nsd4npo** [comment]
maybe @gdams or @karianna can help

**Comment by gdams** [comment]
I have temporarily disabled some redirect logic for detecting browsers Can people please confirm the fix?

**Comment by npo-oekaraduman** [comment]
now working after @gdams fix.

**Comment by charmbv** [comment]
Docker build also working again.

**Comment by ponkio-o** [comment]
@gdams Thank you very much! It also now runs correctly in my environment.

**Comment by labkey-stuartm** [comment]
I can confirm that the fix has resolved the issues in my environment.  Hopefully the "temporary" fix becomes a permanent fix.

**Comment by asreich** [comment]
Thank you for the quick response on this @gdams.

**Comment by pkbarbiedoll** [comment]
I'm still getting this in Ubuntu 24.04

```
pkbarbiedoll@pkbarbiedoll-lappie:~$ sudo apt update
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease                                                                                                              
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease                                                                                                                 
Ign:6 https://packages.adoptium.net/artifactory/deb/ubuntu noble InRelease                                             
Hit:7 https://ppa.launchpadcontent.net/openshot.developers/ppa/ubuntu noble InRelease
Hit:8 https://esm.ubuntu.com/apps/ubuntu noble-apps-security InRelease
Err:9 https://packages.adoptium.net/artifactory/deb/ubuntu noble Release
  404  Not Found [IP: 2606:4700::6812:1542 443]
Hit:10 https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu noble InRelease
Hit:11 https://esm.ubuntu.com/apps/ubuntu noble-apps-updates InRelease
Hit:12 https://esm.ubuntu.com/infra/ubuntu noble-infra-security InRelease
Hit:13 https://esm.ubuntu.com/infra/ubuntu noble-infra-updates InRelease
Reading package lists... Done
E: The repository 'https://packages.adoptium.net/artifactory/deb/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
pkbarbiedoll@pkbarbiedoll-lappie:~$ 

```

**Comment by karianna** [comment]
> I'm still getting this in Ubuntu 24.04
> 
> ```
> pkbarbiedoll@pkbarbiedoll-lappie:~$ sudo apt update
> Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
> Hit:2 http://us.archive.ubuntu.com/ubuntu noble InRelease
> Hit:3 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease
> Hit:4 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease                                                                                                              
> Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease                                                                                                                 
> Ign:6 https://packages.adoptium.net/artifactory/deb/ubuntu noble InRelease                                             
> Hit:7 https://ppa.launchpadcontent.net/openshot.developers/ppa/ubuntu noble InRelease
> Hit:8 https://esm.ubuntu.com/apps/ubuntu noble-apps-security InRelease
> Err:9 https://packages.adoptium.net/artifactory/deb/ubuntu noble Release
>   404  Not Found [IP: 2606:4700::6812:1542 443]
> Hit:10 https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu noble InRelease
> Hit:11 https://esm.ubuntu.com/apps/ubuntu noble-apps-updates InRelease
> Hit:12 https://esm.ubuntu.com/infra/ubuntu noble-infra-security InRelease
> Hit:13 https://esm.ubuntu.com/infra/ubuntu noble-infra-updates InRelease
> Reading package lists... Done
> E: The repository 'https://packages.adoptium.net/artifactory/deb/ubuntu noble Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> pkbarbiedoll@pkbarbiedoll-lappie:~$ 
> ```
> 
> DISTRIB_RELEASE=24.04 DISTRIB_CODENAME=noble DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS" PRETTY_NAME="Ubuntu 24.04.1 LTS"

Looks like you're using IPv6, are you able to drop to a IPv4 request?
