### ISSUE TITLE
AdoptOpenJDK 11 crashes when compile source files with ToolProvider.getSystemJavaCompiler

### ISSUE THREAD

**Issue by bilalekremharmansa** [adoptium/adoptium-support#171]
**Platform:**
macOS High Sierra

**Architecture:**
x86_64

**Related Java version:**
`openjdk version "11.0.4" 2019-07-16`
`OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)`
`OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)`

My team has a project which is written with Java 8. We encounter a bug while trying to compile java source with arguments `-proc:only`.

[Here](https://github.com/bilalekremharmansa/JDKCompilerBug) is sample project that you can demonstrate the case. 

---

Processor returns an `Element` object which it's original type is `ClassSymbol`. With using JDK 11, whenever i try to access element's kind with `Element#getKind()`, java throws `Assertion Error`. **But**, if I ignore the exception and try to access elements' kind, it returns succesfully. 

After while, I dig into to the code, I found exception causes somewhere in `ImplicitCompleter` in `JavacProcessingEnvironment`. 

Whenever it tries to run 
```
JavacProcessingEnvironment.this.compiler.readSourceFile(this.topLevel, (ClassSymbol)sym);
``` 
it fails in this line (line number: 536 in mycase)
`if (!this.modules.enter(List.of(tree), c))`

In such scenario, `JavacProcessingEnvironment` calls `Modules#initModule()` while processing annotations. However, `JavacProcessingEnvironment` holds states and i think it's not able to manage correctly so it's not calling `initModule` right after `AbstractProcessor#process()` scope out. 

The following line check states and DO NOT initialize modules correctly:
```
public List<JCCompilationUnit> enterTreesIfNeeded(List<JCCompilationUnit> roots) {
    return this.shouldStop(CompileState.ATTR) ? List.nil() : this.enterTrees(this.initModules(roots));
};
````

Just because of the modules is not initialized correctly, when I try to access elements' kind java throws `AssertionException`.

To able to get a success result, i had to run with try-catch `Element#getKind()` like;
```        
int remainAttempt = 3;
while(remainAttempt-- > 0) {
    try {
        ElementKind kind = element.getKind();
        return true;
    } catch (AssertionError error) {
         System.err.println("Attempt failed, remaining attempt: " + remainAttempt);
     }
 }
```
In first attempt fails, and second while loop returns true. Probably, `JavacProcessingEnvironment` reset states when an exception occurs(passing to new round) so second attempts not fails as the first one.

**Comment by karianna** [comment]
Still open upstream

**Comment by karianna** [comment]
Still open upstream

**Comment by karianna** [comment]
As this has been reported upstream I'm closing this issue
