### ISSUE TITLE
Math.fma(float, float, float) returns different values with +/-UseFMA option

### ISSUE THREAD

**Issue by hkurokawa** [adoptium/adoptium-support#185]
## Summary
I found `Math.fma(float, float, float)` method returned different values with or without `-XX:-UseFMA` VM option for the same inputs.

## Steps to reproduce
1. Save the below code as FMAExample.java
```java
public class FMAExample {
  public static void main(String[] args) {
    float a = 0x1.fffffep23f;
    float b = 0x1.000004p28f;
    float c = 0x1.fep5f;
    // The below line prints out different values for +/-UseFMA option.
    // -XX:+UseFMA: 0x1.000002p52
    // -XX:-UseFMA: 0x1.000004p52
    System.out.printf("%a\n", Math.fma(a, b, c));
  }
}
```
2. `javac FMAExample.java`
3. `java  -XX:-UseFMA FMAExample`

## Expected results
Step 3 prints out `0x1.000002p52`

## Actual results
Step 3 printed out `0x1.000004p52`

## Triaging info

Java version:

```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```

What is your operating system and platform?

```
Ubuntu 18.04 on x86_64
```

How did you install Java?

I installed the Java with `sudo apt install adoptopenjdk-15-hotspot`

Did it work before?

No.

Did you test with other Java versions?

I tested the same code with the below Java versions and had the same result.

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Linux amd64-64-Bit Compressed References 20200715_697 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
```

## Remarks
I believe the correct answer is `0x1.000002p52` and I am wondering if this might be an implementation bug in [`Math.fma(float, float, float)`](https://github.com/AdoptOpenJDK/openjdk-jdk/blob/bca9e55b1e522cc21b6a53a87fadac4a09688799/src/java.base/share/classes/java/lang/Math.java#L1858).  If the precision is unlimited, the answer would be ` 0x1.000002fffffffcp52`.  When we convert the value to float, we get `0x1.000002p52`, which is the expected result.  On the other hand, when we convert the value to double, we get `0x1.000003000p52`, which is rounded to `0x1.000004p52` when we convert it to float.

**Comment by hkurokawa** [comment]
Just FYI.  I found Oracle OpenJDK behaved the same and reported an issue on bugs.openjdk.java.net as well.  Thanks!

**Comment by aahlenst** [comment]
@hkurokawa Thanks. Can you post a link here to the JBS issue?

**Comment by hkurokawa** [comment]
Thank you, Andreas!  Here is the link to the OpenJDK bug: https://bugs.openjdk.java.net/browse/JDK-8253409

Feel free to close the issue if you think this problem should be addressed in the upstream and we need not to track it here.  I do not know well about how to deal with this kind of core library issues.  Thank you for your support!

**Comment by aahlenst** [comment]
Thanks for sharing the link.

If it's indeed a bug in OpenJDK, it needs to be handled upstream. To ensure this is an OpenJDK bug, you should test with a JDK from https://jdk.java.net/ (for versions maintained by Oracle, currently 15 and 16) or https://adoptopenjdk.net/upstream.html (for versions maintained by Red Hat, currently 8 and 11). Reports based on other OpenJDK builds are not always accepted.

We usually leave the issues open until they have been resolved upstream.

**Comment by hkurokawa** [comment]
Thank you for the clarification.  I verified the issue occurred with other OpenJDK builds and I am pretty sure this is an OpenJDK bug.

> We usually leave the issues open until they have been resolved upstream.

Sure!  Thank you!

**Comment by karianna** [comment]
This was fixed upstream for both 11 and 17.
