### ISSUE TITLE
Clarification about versioning (for Updater)

### ISSUE THREAD

**Issue by tushev** [adoptium/adoptium-support#209]
Hello!

I need some clarification about versioning for my Updater tool.

1. ~What exactly is a patch number? What is the difference with build number?~

2. Is it critical if users do not receive `build` updates timely? As far as I understand, only security updates are critical. So if something goes wrong with version determination, nothing terrible will happen in case the user will not update for `build`? 
(Yes, I know that an update is recommended anyway if it's possible, the question is about "severity").

   2.1 ~Is the recent patch update really critical from **security** point of view, or it's about stability?~

   2.2 If a security issue/vulnerability is found, is it always ex. `security`, now `$UPDATE` field that will be increased, or `patch` field may also contain security fixes? JEP 322 Says `$PATCH is incremented only when it's necessary to produce an emergency release to fix a critical issue` - is this "critical" related to security? 

3. Some other releases, like 8, have `patch` field missing in the `/v3/assets/latest/8/hotspot` API. Why is that?
Is it optional or it will be updated with the following releases?

4. ~Is it safe to consider that by default `patch = 0` (for comparison, in case the updater was unable to determine patch number)?~ `JEP 322 says: yes`

5. ~Is it safe to consider that by default `build = 0` (for comparison, in case the updater was unable to determine build number)?
Or it is better to omit `build` from comparison at all, if the updater was unable to determine build for local version? (see 2)~ `JEP 322 says: yes`

6. ~How versions should be compared?~

`major > [minor, =0 by default] > [security, =0 by def] > [patch, =0 by def] > [build, =0 by def] > [adopt_build, =0 by def]` ~- is it ok, or not? By `>`, I mean if, say, `A.major = B.major; A.minor > B.minor`, then we can say that `A > B` without checking the "lesser" fields.~

7. ~~I've seen that you were discussing `11.0.9+11.2` - with dots **after** plus sign. Is it possible that such numbers will appear in future?
(That's why I'm asking about "if something goes wrong with version determination" :) - in case the regexes won't see build number...)~~
<hr>

**EDIT:** I will strikethrough answered questions for convenience.

**Comment by aahlenst** [comment]
Thanks for all your questions. I see we have to specify our version numbering. :weary: Generally, we follow what OpenJDK does (currently: https://openjdk.java.net/jeps/322). On top of that, we have the "AdoptBuildNumber" that we use to update a specific version if we made a mistake. 

> I've seen that you were discussing `11.0.9+11.2` - with dots after plus sign. Is it possible that such numbers will appear in future?

2 is the "AdoptBuildNumber" (not necessarily the official name). And those appear from time to time for various reasons. Our 11.0.9+11 did not build with Shenandoah GC enabled and we only realized that after releasing it. So we had to redo it and that resulted in 11.0.9+11.**1**. So the natural successor would have been 11.0.9+11.**2**.

**Comment by tushev** [comment]
> So we had to redo it and that resulted in 11.0.9+11.1. So the natural successor would have been 11.0.9+11.2.

Then one more question :) :

8. Is it safe to consider that by default `AdoptBuildNumber = 0` (for comparison, in case the updater was unable to determine AdoptBuildNumber)?

**Comment by tushev** [comment]
9. I assume you definitely have much more experience with Java than I have. Could you please confirm that in `1.8.0_275-b01` naming scheme that `0` was never used and it is safe to be ignored? (as far as I deduced from https://openjdk.java.net/jeps/223)

**Comment by tushev** [comment]
10. And one more :) - while trying to handle as much cases as possible I noticed this:

JSON request to https://api.adoptopenjdk.net/v3/assets/version/11.0.9%2B11.1?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=hotspot&lts=true&os=windows&page=0&page_size=10&project=jdk&release_type=ga&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk returns `"adopt_build_number": 1, "semver": "11.0.9+11.1"`.

In the meantime, the corresponding `release` file has `SEMANTIC_VERSION="11.0.9+11"` and MSI `revision = 11` as well. 

Thus my updater will never be able to determine that locally installed version is `"11.0.9+11.1"`, it will assume that the user has `"11.0.9+11"` and will always suggest to update until `11.0.9+12` or greater arrives.

The questions are: 
* (6,8) Does AdoptBuildNumber needs comparing at all?
* does the recent suggestion for switching to `11.0.9+101` scheme solve this potential issue?

**Comment by tushev** [comment]
12. Does `build` always have a value? I've seen **recently** `15+36`, `11.0.9.1+1`, but not `15.0.1`.

**Comment by aahlenst** [comment]
@tushev You just unlocked an achievement: "Volunteers to write spec by asking the right questions." 😁

Answering 12 by looking at JEP 322:

> $VNUM(-$PRE)?\+$BUILD(-$OPT)?
$VNUM-$PRE(-$OPT)?
$VNUM(+-$OPT)?

BUILD does not have to be present.

**Comment by tushev** [comment]
@aahlenst well, it's just my code who is begging for specs xD

Actually, I've just read JEP 322 more thoroughly, and it answers almost all of my questions, so I crossed them out. The only ones left are 2, 2.2, 3 & 8 :)

> BUILD does not have to be present.

Unfortunately, this was not clear to me.

Thanks!

**Comment by karianna** [comment]
I think this can be closed and any remaining issues opened in our api.adoptiym.net repo.
