### ISSUE TITLE
target process xxxx doesn't respond within 10500ms or HotSpot VM not loaded

### ISSUE THREAD

**Issue by SteveGase** [adoptium/adoptium-support#214]
We've seen this problem before, and thought we had it resolved, and now it is back and happening more frequently.

Situation:
we monitor the JVM used for our various application instances  (confluence, Jira, and Bitbucket).
We use Nagios monitoring to watch over heap and other JVM attributes, and use jstack to generate thread dumps, and jstat to generate heap dumps.

The various processes that connect to the JVM fail after a while, and the problem can only be "fixed" by restarting the application server where it will work for days -- sometimes weeks -- before happening again.

Here is what we see when the problem is happening:

$ sudo -u jira /usr/lib/jvm/jdk-11.0.2+7/bin/jstack 1455

1455: Unable to open socket file /proc/1455/root/tmp/.java_pid1455: target process 1455 doesn't respond within 10500ms or HotSpot VM not loaded

The JVM is running, the application is working fine and server user requests:

Here is the process info from the same running process:

[steve_gase@jira2n1prd ~]$ sudo cat /proc/1455/cmdline
/usr/bin/java-Djava.util.logging.config.file=/opt/jira/install/conf/logging.properties-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager-Xms24G-Xmx24G-XX:InitialCodeCacheSize=32m-XX:ReservedCodeCacheSize=512m-Djava.awt.headless=true-Datlassian.standalone=JIRA-Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true-Dmail.mime.decodeparameters=true-Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory-XX:-OmitStackTraceInFastThrow-Djava.locale.providers=COMPAT-Djira.home=/opt/jira/home-Datlassian.plugins.startup.options=-Djdk.tls.ephemeralDHKeySize=2048-Djava.protocol.handler.pkgs=org.apache.catalina.webresources-Dorg.apache.catalina.security.SecurityListener.UMASK=0027-Xlog:gc*:file=/opt/jira/install/logs/atlassian-jira-gc-%t.log:time,uptime:filecount=5,filesize=20M-XX:+ExplicitGCInvokesConcurrent-Xms24G-Xmx24G-DapplicationName=jira2.gtie.dell.com-Datlassian.plugins.enable.wait=60-Datlassian.plugins.startup.options=-Datlassian.standalone=JIRA-Dfile.encoding=utf-8-Dsun.jnu.encoding=UTF-8-Xlog:gc:/opt/jira/install/logs/atlassian-jira-gc-%t.log:time,uptime:filecount=5,filesize=20M-XX:+UseG1GC-XX:+ExplicitGCInvokesConcurrent-XX:+HeapDumpOnOutOfMemoryError-XX:HeapDumpPath=/opt/jira/install/logs/-Djavax.net.ssl.trustStore=/usr/lib/jvm/adoptopenjdk-11-openj9/lib/security/cacerts-Dignore.endorsed.dirs=-classpath/opt/jira/install/bin/bootstrap.jar:/opt/jira/install/bin/tomcat-juli.jar-Dcatalina.base=/opt/jira/install-Dcatalina.home=/opt/jira/install-Djava.io.tmpdir=/opt/jira/install/temporg.apache.catalina.startup.Bootstrapstart

Last year, when we had this problem, it seemed to be caused by a Linux cron process that cleaned our /tmp file system by removing old files.

The JVM stores a file with process information that is used by jstack, jstat and other JDK tools to look up connection info.

We "solved" the problem by using a daily cron job to touch the files under /tmp/hsperfdata/ to avoid having the cleanup think they were old and avoiding their undesired deletion.

With the problems we are having now, the /tmp/hsperdata files are NOT being deleted, and so that is not apparently the cause THIS TIME.

[steve_gase@jira2n1prd ~]$ sudo ls -lR /tmp/hsperfdata_jira
/tmp/hsperfdata_jira:
total 32
-rw------- 1 jira jira 32768 Nov 30 12:38 1455

HAVE YOU SEEN THIS PROBLEM BEFORE?
IS THERE A SOLUTION TO THIS?

We are experiencing this with all of our Jira, Confluence and Bitbucket instances at various times.

I can't be sure, but it might have started happening (again) after our upgrade to a newer JVM:

[steve_gase@jira2n1prd ~]$ /usr/lib/jvm/jdk-11.0.2+7/bin/java -version
openjdk version "11.0.2" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+7, mixed mode)

The "jira" user is running the JVM process:

[steve_gase@jira2n1prd ~]$ ps -fC java

UID PID PPID C STIME TTY TIME CMD
jira 1455 1 99 Nov16 ? 26-19:41:34 /usr/bin/java -Djava.util.logging.config.file=/opt/jira/install/conf/logging.properties -Djava.util.logging.ma

The .java_pid file is not present (ie. /proc/1455/root/tmp/.java_pid1455) – the tmp directory above it is still there:

[steve_gase@jira2n1prd ~]$ sudo ls -l /proc/1455/root/tmp

total 4
rw-rr- 1 root root 6 Nov 30 14:39 background.pid
drwxr-x--- 2 jira jira 80 Nov 30 14:39 hsperfdata_jira
drwxr-xr-x 2 steve_gase steve_gase 40 Nov 30 12:43 hsperfdata_steve_gase
drwxr-xr-x 2 jira jira 60 Nov 16 20:02 nagios

I ran jstack while logged in as the user "jira" and it fails with the same result:

[jira@jira2n1prd ~]$ id
uid=1003(jira) gid=1003(jira) groups=1003(jira)

[jira@jira2n1prd ~]$ /usr/lib/jvm/jdk-11.0.2+7/bin/jstack 1455
1455: Unable to open socket file /proc/1455/root/tmp/.java_pid1455: target process 1455 doesn't respond within 10500ms or HotSpot VM not loaded

**Comment by karianna** [comment]
Hi Steve, nice to hear from you over here :-)

I see that you're using an older version of Adopt, can you upgrade to 11.0.9.1?

I also see in your path that `/usr/lib/jvm/adoptopenjdk-11-openj9/lib/security/cacert` is mentioned.  That seemed a little odd to me as I think you're running a Hotspot JVM?

**Comment by SteveGase** [comment]
Hi Martin! 
When we last updated (which we tend to do every 6mo) build 11.0.2+7 was the one to use.  When we do this next, we will apply the latest Atlassian-recommended build.

Regarding the cacert path and hotspot are connected, we just happen to store our certs in a standard place to avoid changing it with each upgrade.


I've got some more details to consider...
earlier (2 years ago?) we had problems with a cron job that cleans the /tmp directory.  it was removing files under /tmp/hsperfdata_jira.  Without the reference to the running process, jstack/jstat had communication problems.

Now, we've found yet another file stored under /tmp --  /tmp/.java_pid####  That file was being removed as well... and I suspect that as the likely cause of the communication problems.

I am adding /tmp/java_pid*  to our workaround in cron, that touches files to keep the modtime current and avoid the /tmp cleaning problem.

>>> find /tmp/hsperfdata_* /tmp/.java_pid* -type f -exec touch {} \;

Does this seem like the likely cause of our problems?  ...and a reasonable workaround?
Kinda surprised that I've not seen anyone else experiencing this issue.

**Comment by aahlenst** [comment]
I never cleanup the temporary directory because that might cause havoc and exactly the kind of problems you're seeing. So to stop doing what you're doing sounds like a good idea 😀

**Comment by SteveGase** [comment]
Cleaning /tmp is an default setting for CentOs 6 and 7.

I just found confirmation of the problem in the RedHat forum...

https://bugzilla.redhat.com/show_bug.cgi?id=1704608 

It seems that Java installer might address this by auto-installing a file: 

/usr/lib/tmpfiles.d/java-version-adoptopenjdk.conf
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# Exclude java-hooks
x /tmp/hsperfdata_* 
x /tmp/.java_pid*
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by aahlenst** [comment]
> Cleaning /tmp is an default setting for CentOs 6 and 7.

😮

Are you using our RPMs? In that case, we could add that config.

**Comment by SteveGase** [comment]
Yep... we are using this package:

adoptopenjdk-11-openj9-11.0.8+10.openj9_0.21.0-2.x86_64

**Comment by aahlenst** [comment]
I've created a separate issue to track the changes for the installer: https://github.com/AdoptOpenJDK/openjdk-installer/issues/275. We also might need to document this for the binary tarballs.

**Comment by chenearl** [comment]
The user role is wrong, just change the role
