### ISSUE TITLE
jre/lib/s390x/compressedrefs/libjvm.so missing libdl reference

### ISSUE THREAD

**Issue by nealef** [adoptium/adoptium-support#25]
**Platform:**
Linux

**Architecture:**
s390x

The libjvm.so found in the java-8 compressedrefs directory doesn't reference libdl so that linking against it results in unresolved references to things like dlopen. Adding -ldl circumvents this but the other libjvm.so that are part of the tarball have been linked against the library:

```
$ ldd jre/lib/s390x/compressedrefs/libjvm.so
	libpthread.so.0 => /lib/s390x-linux-gnu/libpthread.so.0 (0x000003ff93880000)
	libm.so.6 => /lib/s390x-linux-gnu/libm.so.6 (0x000003ff93780000)
	libc.so.6 => /lib/s390x-linux-gnu/libc.so.6 (0x000003ff93580000)
	/lib/ld64.so.1 (0x000003ff93a00000)

$ nm jre/lib/s390x/compressedrefs/libjvm.so | grep dlopen
                 U dlopen

$ ldd jre/lib/s390x/j9vm/libjvm.so
	libdl.so.2 => /lib/s390x-linux-gnu/libdl.so.2 (0x000003ff9ec00000)
	libm.so.6 => /lib/s390x-linux-gnu/libm.so.6 (0x000003ff9eb00000)
	libc.so.6 => /lib/s390x-linux-gnu/libc.so.6 (0x000003ff9e900000)
	/lib/ld64.so.1 (0x000003ff9ed80000)

$ nm jre/lib/s390x/j9vm/libjvm.so | grep dlopen
                 U dlopen@@GLIBC_2.2
```
Is there a reason for this difference? Although it can be circumvented building packages like hadoop requires changes to the canonical sources which is never a great thing to have to do and doesn't happen when using the standard java-1.8.0-openjdk that comes with the distros.

**Comment by karianna** [comment]
Still open upstream

**Comment by karianna** [comment]
Still open upstream

**Comment by karianna** [comment]
As this has been reported upstream I'm closing this issue
