### ISSUE TITLE
upstream: Use Reference.reachabilityFence to keep the object alive

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/adoptium-support#274]
OpenJDK contribution suggestion: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/282#issuecomment-775495504

**Comment by andrew-m-leonard** [comment]
Needs JBS label

**Comment by karianna** [comment]
Closing this as OpenJDK proper is that right place for this enhancement proposal.
