### ISSUE TITLE
XML transformation and indentation when using xml:space

### ISSUE THREAD

**Issue by richardgroote** [adoptium/adoptium-support#276]
## Summary
When switching from Java 8 (Oracle) to Java 11 (AdoptOpenJDK) the indentation of our XML has been changed.
The indentation fails when a xml element is defined with an attribute xml:space=preserve. Everything after the xml element containing the attribute is no longer indented

## Steps to reproduce
With the below code the problem can be reproduced. The variable data must be a XML string, for instance 
`<?xml version=\"1.0\" encoding=\"UTF-8\"?><a><b>650b4d21</b><c>If true</c><d xml:space=\"preserve\">TRUE</d><e>test</e></a>`
In this case the tags 'a','b','c','d' are indented, everything after tag 'd' will not be indented.

		Transformer transformer = TransformerFactory.newInstance("com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl", Test.class.getClassLoader());

		transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");
		transformer.setOutputProperty(OutputKeys.CDATA_SECTION_ELEMENTS, "body hyperlink");
		transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
		transformer.setOutputProperty(OutputKeys.INDENT, "yes");
		transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
		
		StringWriter writer = new StringWriter();

		StreamSource in = new StreamSource(new StringReader(data));
		transformer.transform(in, new StreamResult(writer));
		
		System.out.println("-----");
		System.out.println(writer.toString());
		System.out.println("-----");

## Expected results
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <a>
        <b>650b4d21</b>
        <c>If true</c>
        <d xml:space=\"preserve\">TRUE</d>
        <e>test</e>
    </a>
```

## Actual results
Below XML:
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <a>
        <b>650b4d21</b>
        <c>If true</c>
        <d xml:space=\"preserve\">TRUE</d><e>test</e></a>
```

## Triaging info

Java version:
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

What is your operating system and platform?
Mac OSX Catalina

How did you install Java?
Installer

Did it work before?

Did you test with other Java versions?
Java 15

**Comment by aahlenst** [comment]
https://bugs.openjdk.java.net/browse/JDK-8175793 enhanced the XML serializer in JDK 9 incl. support for `xml:space`. Looks like `xml:space="preserve"` is applied to the remainder of the document. Looks wrong, but I'm not an expert in that area.

If it's indeed a problem, it would need to be handled at OpenJDK. Best way to report is to check with builds from https://jdk.java.net and then use https://bugreport.java.com/bugreport/. When filing the report, only mention the builds from jdk.java.net. Please update the issue here once you get a bug ID.

**Comment by richardgroote** [comment]
unfortunately there is no MAC version available on the jdk.java.net. but i will ask a colleague to test it on windows instead and then i will report back

**Comment by aahlenst** [comment]
On https://jdk.java.net/16/, there is: Look for "macOS / x64". Same on https://jdk.java.net/17/.

**Comment by karianna** [comment]
Fixed in Java 17 (but not backported)
