### ISSUE TITLE
A problem with ghidra

### ISSUE THREAD

**Issue by xunforce** [adoptium/adoptium-support#286]
Now,I'm using adoptopenjdk 16(openj9),but ghidra doesn't work.I tested on windows 10 and manjaro linux,both of them can't work like them should be.

**Comment by aahlenst** [comment]
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by xunforce** [comment]
Well,when I use jdk15,ghidra works well,but when  I use jdk16,it doesn't work.I can't analyze any file.
Ghidra is download from here:
https://ghidra-sre.org

**Comment by aahlenst** [comment]
> it doesn't work.I can't analyze any file.

How does that manifest itself? Does something crash, do you get an error, ...?

**Comment by xunforce** [comment]
No, I didn't see anything, but it really doesn't work.
I am analyzing an elf file.

**Comment by xunforce** [comment]
![Uploading IMG_20210330_135637.jpg…]()

**Comment by xunforce** [comment]
Just like this

**Comment by aahlenst** [comment]
Maybe the software isn't ready for Java 16?

**Comment by xunforce** [comment]
Solution:https://github.com/NationalSecurityAgency/ghidra/issues/2879
