### ISSUE TITLE
SIGSEGV when starting a GUI program that worked on JDK 15

### ISSUE THREAD

**Issue by zskamljic** [adoptium/adoptium-support#287]
## Summary

I have a piece of software (autoclicker), written ages ago (around the time java 8 was still new). It seemed to work fine up to and including JDK 15, but now it crashes with a segfault, apparently in some native code (the source is not directly using any native code). As I've lost the sources a while ago I'm only left with the class files, but I think they should be enough to reproduce the problem.

The dump log can be seen here:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f93a802914c, pid=11670, tid=11671
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (16.0+36) (build 16+36)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (16+36, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007f93a802914c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/zan/git/clicker/core.11670)
#
# An error report file with more information is saved as:
# /home/zan/git/clicker/hs_err_pid11670.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[1]    11670 abort (core dumped)  java -cp . io.github.zskamljic.clicker.Main
```

## Steps to reproduce

execute `java -cp . io.github.zskamljic.clicker.Main`

## Expected results

A window should pop up

## Actual results

Segmentation fault log is printed.

## Triaging info

Java version:

openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

What is your operating system and platform?

ArchLinux, 5.11.10-arch1-1 on x86_64

How did you install Java?

Via AUR, https://aur.archlinux.org/packages/jdk-adoptopenjdk/

Did it work before?

I have used it for a longer period of time, it worked fine with JDK 15, although I believe recently some of the gnome libraries have updated as well. 

Did you test with other Java versions?

Tested with the following:
```
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```
This version works fine.

The hs err log:
[hs_err_pid11670.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6226990/hs_err_pid11670.log)
The zip with class files (I've lost the sources, unfortunately):
[clicker.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6226992/clicker.zip)

**Comment by aahlenst** [comment]
Does it crash with 16 from https://jdk.java.net, too?

**Comment by zskamljic** [comment]
It appears to happen with that version as well, should I close the bug here and open it on https://bugreport.java.com/bugreport/crash.jsp instead?

**Comment by aahlenst** [comment]
There are pre-existing reports:

https://bugs.openjdk.java.net/browse/JDK-8253726
https://bugs.openjdk.java.net/browse/JDK-8255790 

https://bugs.openjdk.java.net/browse/JDK-8255790 seems to be the interesting one. Apparently, a fix has landed in 17. Can you check?

**Comment by zskamljic** [comment]
it appears that with 17 it works fine

**Comment by aahlenst** [comment]
> it appears that with 17 it works fine (albeit it does look a bit different)

Should something be done about it?

**Comment by zskamljic** [comment]
That depends, personally it doesn't really bother me, but somebody might see an issue in this, here's how it looks on JDK 15:
![image](https://user-images.githubusercontent.com/14160663/112983762-58574600-915e-11eb-8d54-e603983242ae.png)
And here's the look on JDK 17:
![image](https://user-images.githubusercontent.com/14160663/112983824-69a05280-915e-11eb-8da0-76fb51f7a7fb.png)

Will the fix from 17 be ported to 16?

**Comment by aahlenst** [comment]
I don't see any indication that a backport is planned to 16 or 11. Let's see if someone has the capacity to do it. Anyhow, it's too late for 11.0.11 and 16.0.1, both due in April.

**Comment by gdams** [comment]
This got backported to 11 a while back by @jerboaa https://github.com/openjdk/jdk11u-dev/commit/6a6e00e56b57006fc80e7b3560c860a0f0967111
