### ISSUE TITLE
JDK8u282-b08 Linux x64 - Xerces - old version of com/sun/org/apache/xerces/internal/impl/dv/xs/TypeValidator.java

### ISSUE THREAD

**Issue by lichtin** [adoptium/adoptium-support#289]
Xerces should have been upgraded to version 2.12.1
But with the AdoptOpenJDK, JDK8u282-b08 Linux x64,
for example class com.sun.org.apache.xerces.internal.impl.dv.xs.TypeValidator
is still an old version without the XERCESJ-1592 fix.
See also https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8242470

**Comment by karianna** [comment]
@lichtin - [Backport to 8u271](https://bugs.openjdk.java.net/browse/JDK-8244804) - so it should be in there.
