### ISSUE TITLE
Named elliptic curve groups x25519 and x448 for TLS Java 8

### ISSUE THREAD

**Issue by ed03875** [adoptium/adoptium-support#294]
## Question
I see where Oracle added support for the x25519 and x448 named elliptic curve groups in release 11.0.10 in January.  Do you know if this is available in Java 8 1.8.0_282 (wishful thinking ? ) or when it will be available ?
## Context

Java version: 

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20210120_972 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08)

Your operating system and platform:

**Comment by karianna** [comment]
https://bugs.openjdk.java.net/browse/JDK-8227348
