### ISSUE TITLE
Error in RELEASE file for 8.0.292+10: +1 instead of +10

### ISSUE THREAD

**Issue by tushev** [adoptium/adoptium-support#295]
Hello,

8.0.292's `release` file contains `SEMANTIC_VERSION="8.0.292+1"`, while https://api.adoptopenjdk.net/v3/assets/latest/8/hotspot returns 
```
    "version": {
      "build": 10,
      "major": 8,
      "minor": 0,
      "openjdk_version": "1.8.0_292-b10",
      "security": 292,
      "semver": "8.0.292+10"
    }
```
My updater tool currently prioritizes `release` file over other version information sources such as registry. This bug causes update loop: any user who updates their JDK to `8.0.292+10` would receive update suggestions again and again.

**Comment by andrew-m-leonard** [comment]
There is a "bug" in this line: https://github.com/adoptium/temurin-build/blob/eebdd4279ab45e20cb1a3b171619d72edebff886/sbin/build.sh#L1110
```
echo "jdk8u292-b10" | cut -c4- | awk -F'[-b0]+' '{print $1"+"$2}' | sed 's/u/.0./'
=> 8.0.292+1
```

**Comment by andrew-m-leonard** [comment]
It will go even more wrong for the next update jdk8u302, eg:
```
echo "jdk8u302-b10" | cut -c4- | awk -F'[-b0]+' '{print $1"+"$2}'
=> 8u3+2
```
