### ISSUE TITLE
JAVA RXTX Crash with Problematic frame: ClibNRJavaSerial.dll+0x753d

### ISSUE THREAD

**Issue by JoeBanjo5050** [adoptium/adoptium-support#300]
Java RXTX crashes on windows 64x even with Java jdk1.8.0_291 installed. Attached logs and what is supposedly the fix. 

[hs_err_pid2124.log](https://github.com/adoptium/adoptium-support/files/6411409/hs_err_pid2124.log)

[issue-131-patch.txt](https://github.com/adoptium/adoptium-support/files/6411407/issue-131-patch.txt)

**Comment by karianna** [comment]
@JoeBanjo5050 Did you create this patch yourself?  Can you provide the details on Java RXTX?

**Comment by JoeBanjo5050** [comment]
I did not create it. I think I found it on a support thread. I actually could not get it running and switched to a Python instance to complete my project.sorry this doesn't help.
