### ISSUE TITLE
macos: can not create a child java process from gui program

### ISSUE THREAD

**Issue by tangjfn** [adoptium/adoptium-support#301]
macos: 11.3

electronjs main process (start with click the program icon)
spawn("java", ....)
fail: openj9 jdk-16.0.1+9, jdk-15.0.2+7 and jdk-11.0.11+9
ok: all HotSpot

electronjs main process (start from command line)
all ok

nodejs 
all ok

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/issues/12907 to track against OpenJ9.
