### ISSUE TITLE
JarSigner.exe fails to verify .jar files that Oracle Jarsigner will verify without error.

### ISSUE THREAD

**Issue by BrianMouncer** [adoptium/adoptium-support#302]
running "jarsigner.exe --verify --strict" fails.  
I am still investigating if there is an actual problem with our certs or not.
I am raising this issue because we noticed this when the Visual Studio hosted agents started using OpenJDK, and verifying the JAR certs started failing.  I can reproduce this locally as well.

If I use the jarsigner.exe from Oracals jdk1.8.0_281, the jarsigner will verify the JAR files even from our previous releases.
However, the jarsigner from Adopt OpenJDK 8 and 11  both fail to verify the JAR certificates.

## Steps to reproduce

"C:\Program Files\Java\jdk1.8.0_281\bin\jarsigner.exe" --verify --strict \temp\foo\android\client-sdk-1.17.0-beta.0.20710767.aar

jar verified.

"C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\jarsigner.exe" --verify --strict "\temp\foo\android\client-sdk-1.17.0-beta.0.20710767.aar"

jar verified, with signer errors.

Error:
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
This jar contains entries whose TSA certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Re-run with the -verbose and -certs options for more details.

--- with --verbose --certs ---

      X.509, CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
      [certificate is valid from 12/22/17 4:00 PM to 3/22/29 4:59 PM]
      X.509, CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
      [certificate is valid from 1/11/16 4:00 PM to 1/11/31 3:59 PM]
      [Invalid TSA certificate chain: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

## Expected results

I would expect jarsigner.exe to be able to verify the file.
I would expect the tool from Adopt ad Oracle to produce the same results. 

## Actual results

.jar and .aar signation validate passes with Oracle jut filas with Adops OpenJDK.

## Triaging info

Java version:

both 

C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\jarsigner.exe
C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin\jarsigner.exe

Though we only use JDK8 on build hosts.

"C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin\java" -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

What is your operating system and platform?

Windows Server 2019 and Desktop 20H2.

How did you install Java?

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u292b10.msi

Did it work before?

Yes, but I'm not sure is the public agents changed tool verions, or something changes with the certs chains.
however I did verfy the issue happens with latest builds of both OpenJDK 8 and 11.

Did you test with other Java versions?

yes.

"C:\Program Files\Java\jdk1.8.0_281\bin\java" -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by BrianMouncer** [comment]
I reverted my OpenJDK back to an older release from earlier this year.
JAR signature validate works in the older verion, but not in the most current OpenJDK Release.

C:\git\carbon3\Carbon>"C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\bin\jarsigner.exe" -verify -strict \temp\foo\client-sdk-1.17.0-beta.0.20710767.jar

jar verified.

C:\git\carbon3\Carbon>"C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\bin\jarsigner.exe" -verify -strict \temp\foo\android\client-sdk-1.17.0-beta.0.20710767.aar

jar verified.

I see there is a pending release for the OpenJDK, I will try to verify with it when it is available...

**Comment by karianna** [comment]
I'm guessing that Oracle is supplying a Cert that OpenJDK does not for this purpose.  Since it looks like this worked under 1.8.0_275 and not 1.8.0_292 there must be a cert that fell off.

**Comment by karianna** [comment]
@johnoliver Are you able to do a diff here?

**Comment by jskov-jyskebank-dk** [comment]
I see the same verification failure when trying to verify quite a few plugins from Eclipse.

I am using:

````console
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
`````

For example:

````console
$ jarsigner --strict -verify releases_202106161001/plugins/org.eclipse.tcf.cdt.ui_1.6.3.202007121906.jar

jar verified, with signer errors.

Error: 
This jar contains entries whose TSA certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Warning: 
The SHA-1 timestamp digest algorithm is considered a security risk. This algorithm will be disabled in a future update.

Re-run with the -verbose and -certs options for more details.

$ echo $?
64
`````

I have pinpointed the certificate causing problems - its alias in Java 8 (Oracle JDK 1.8.0_192) is "verisignuniversalrootca [jdk]".


I can copy the certificate to jdk11:

```console
$ alias="verisignuniversalrootca [jdk]"
$ keytool -importkeystore -srcstorepass changeit -srckeystore $JAVA8_HOME/jre/lib/security/cacerts -deststorepass changeit -destkeystore $JAVA11_HOMElib/security/cacerts -srcalias "$alias" -destalias "$alias"
```

And the verification now works:

```console
$ jarsigner --strict -verify releases_202106161001/plugins/org.eclipse.tcf.cdt.ui_1.6.3.202007121906.jar

jar verified, with signer errors.

Warning: 
The SHA-1 timestamp digest algorithm is considered a security risk. This algorithm will be disabled in a future update.

Re-run with the -verbose and -certs options for more details.

$ echo $?
0
```

**Comment by karianna** [comment]
This was resolved in a later respin.
