### ISSUE TITLE
winrun4j fails to start with openjdk8

### ISSUE THREAD

**Issue by HolyLandir** [adoptium/adoptium-support#305]
## Summary

I am using WinRun4J (http://winrun4j.sourceforge.net/) for installing Java application as Win service. After replacing Oracle Java with Open JRE (OpenJDK8U-jre_x64_windows_hotspot_8u292b10) the library cannot load JVM.

## Steps to reproduce

1. download WinRun4J (http://winrun4j.sourceforge.net/)
2. prepare some Java app
3. configure to vm.location, main.class, classpath at INI file
4. run WinRun4J64.exe

## Expected results

Started aplication

## Actual results

Log output is:
`[info] Module INI: D:\Project\client\console-jag-open\bin\WinRun4J64.ini
[info] Module Dir: D:\Project\client\console-jag-open\bin\
[info] INI Dir: D:\Project\client\console-jag-open\bin\
[info] Working directory set to: D:\Project\client\console-jag-open
[info] Configured vm.location: D:/Project/client/console-jag-open/JRE
[info] Found VM: D:\Project\client\console-jag-open\JRE
[info] Expanding Classpath: lib/*.jar
...
 [err] ERROR: Could not load library: D:\Project\client\console-jag-open\JRE
 [err] Error starting Java VM.
`

## Triaging info

Java version:

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

What is your operating system and platform?

Windows 10 on x86-64

How did you install Java?

No, extracted from ZIP file.

Did it work before?

With Oracle JRE 8, yes.

Did you test with other Java versions?

With Oracle JRE 8 (works) and Open JDK 8 (did not work).

**Comment by karianna** [comment]
@HolyLandir - Have you tried the OpenJDK upstream build by Red Hat? https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_windows_8u292b10.zip
