### ISSUE TITLE
Java 9 .tar.gz downloads have extra "." toplevel folder

### ISSUE THREAD

**Issue by quintesse** [adoptium/adoptium-support#312]
## Summary

All AdoptOpenJDK .zip/.tar.gz downloads have a single toplevel folder named something like "jdk-XX.Y.ZZ". In case of the .tar.gz downloads for JDK 9 an extra toplevel folder was inserted named ".". This means that if you simply unpack the archive it will look correct, but if you, like us, use an option like `tar --strip-components=1` it will not correctly remove the toplevel folder anymore.

## Steps to reproduce

Simply download any .tar.gz for any non-9 version (8, 10, 11, etc) and compare the contents, eg using `tar tvf OpenJDKblah.tar.gz`.

## Expected results

For any version the result should look like:

```
drwxr-xr-x root/root         0 2021-04-20 23:09 jdk8u292-b10/
-r--r--r-- root/root      1522 2021-04-20 23:09 jdk8u292-b10/ASSEMBLY_EXCEPTION
-rw-r--r-- root/root  52758560 2021-04-20 23:09 jdk8u292-b10/src.zip
drwxr-xr-x root/root         0 2021-04-20 23:09 jdk8u292-b10/lib/
drwxr-xr-x root/root         0 2021-04-20 23:09 jdk8u292-b10/lib/amd64/
-rwxr-xr-x root/root     29008 2021-04-20 23:09 jdk8u292-b10/lib/amd64/libjawt.so
drwxr-xr-x root/root         0 2021-04-20 23:09 jdk8u292-b10/lib/amd64/jli/
-rwxr-xr-x root/root    422976 2021-04-20 23:09 jdk8u292-b10/lib/amd64/jli/libjl
.
.
.
```

## Actual results

But for 9 it actually looks like:

```
drwxrwxr-x jenkins/jenkins   0 2018-10-08 15:33 ./jdk-9.0.4+11/
drwxrwxr-x jenkins/jenkins   0 2018-10-08 15:33 ./jdk-9.0.4+11/man/
lrwxrwxrwx jenkins/jenkins   0 2018-10-08 15:33 ./jdk-9.0.4+11/man/ja -> ja_JP.UTF-8
drwxrwxr-x jenkins/jenkins   0 2018-10-08 15:33 ./jdk-9.0.4+11/man/ja_JP.UTF-8/
drwxrwxr-x jenkins/jenkins   0 2018-10-08 15:33 ./jdk-9.0.4+11/man/ja_JP.UTF-8/man1/
-rw-rw-r-- jenkins/jenkins 13698 2018-10-08 15:33 ./jdk-9.0.4+11/man/ja_JP.UTF-8
.
.
.
```

Pay special attention to the `./` in front of all the paths.

**Comment by karianna** [comment]
Unfortunately, we won't be respinning 9 builds for this.
