### ISSUE TITLE
jdk16u aarch64 64k builds show an error while testing on 4k machines (resurfaced bug)

### ISSUE THREAD

**Issue by superusercode** [adoptium/adoptium-support#314]
## Summary

Previously reported at (https://github.com/adoptium/aqa-tests/issues/1864, https://github.com/AdoptOpenJDK/openjdk14-binaries/issues/1, and https://bugs.openjdk.java.net/browse/JDK-8243392, https://bugs.openjdk.java.net/browse/JDK-8236847)
Like before, the problem is that if you build jdk16u on an aarch64 machine with 64k pages, and then use it on a machine with 4k pages (and possibly the reverse too), you get this non-fatal error right before the -version output:
```
[0.011s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
```

In my case, I installed one of the rpms available (https://adoptopenjdk.jfrog.io/artifactory/rpm/centos/7/aarch64/Packages/adoptopenjdk-16-hotspot-16.0.1+9-3.aarch64.rpm) onto the new Oracle Cloud ARM free tier rigs with maxed out cpus and ram (4core/24gb ram)

## Steps to reproduce

```
java -version
```

## Expected results
```
[opc@minecraft-server ~]$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode)
```
## Actual results
```
[opc@minecraft-server ~]$ java -version
[0.004s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode)
```
## Triaging info

Java version:
```
[0.004s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode)
```
What is your operating system and platform?

Oracle Linux 7.9 on ARM64

How did you install Java?

via the RPM i linked above

Did it work before?

This is my first time using adoptopenjdk on an arm device.

Did you test with other Java versions?

No, but the oracle 11 jdk that comes in the oracle repos did not have this issue.

**Comment by jerboaa** [comment]
> Did you test with other Java versions?
> 
> No, but the oracle 11 jdk that comes in the oracle repos did not have this issue.

Likely because https://bugs.openjdk.java.net/browse/JDK-8236847 got backported to 11.0.12-oracle. So OpenJDK is missing a backport. I'll look into it.

**Comment by superusercode** [comment]
Backport refused @ https://bugs.openjdk.java.net/browse/JDK-8268396
> After looking at this some more it seems low priority (i.e. cost/benefit) to get this backported, because:
> - Class data sharing isn't being done by default at build time in contrast to later JDKs (16+?)
> - The error is only a warning and will disable CDS. It has no other consequence.
> - It's a sort-of a corner case when this would happen in JDK 11. Generate the CDS archive on one
  system with a certain page size and then trying to run it on a different system with a different page size.
  However, I wasn't able to reproduce this with JDK 11.
> - The JDK 17 patch is quite invasive and it's too risky to attempt backporting.

It seems like the solution given is just to wait for JDK 17, which i'm fine with doing since it doesn't have any actual effect on my workload.
