### ISSUE TITLE
Kerberos Credential Retrieval from Cache not Working in Cross-Realm Setup

### ISSUE THREAD

**Issue by Raytion** [adoptium/adoptium-support#318]
## Summary

We have a problem with JDK and Kerberos in a cross-realm setup, of which we suspect the root cause to be in the JDK.

We assume cross-realm support was implemented as described here: https://bugs.openjdk.java.net/browse/JDK-8005819

The ticket's test description states the following setup:
client@REALM2 has established a kerberos context with krbservice1@REALM1 with delegcred=false, krbservice1@REALM1 delegates to krbservice2@REALM1 using S4U2PROXY 

However, in our setup krbservice2, the one we want to delegate to, is in a different realm than krbservice1. This means we have no official statement if our setup is supposed to work at all.
The delegation to krbservice2 is configured as resource-based delegation. Which means in the AD for krbservice1, krbservice2 is not in the property list of "allowedToDelegateTo". Instead, we configured the trust relationship for delegation with the PowerShell command Set-ADUser. krbservice2 cannot be added to the allowedToDelegateTo property of krbservice1 because they are in different realms.

## Steps to reproduce

1. On the first round the user "client" establishes a connection to our krbservice1. krbservice1 sends a delegated search request to krbservice2. The Java security module successfully retrieves a ticket on the user's behalf, which is attached to the search request to krbservice2 and search results are returned.
2. However, on the second search query, in the class sun/security/krb5/internal/CredentialsUtil.java it restores the credentials from the cache, but it is not able to retrieve a valid ticket for krbservice2. Instead, we get the following error messages:

>>>KRBError:
	 sTime is Tue Jun 01 14:03:37 CEST 2021 1622549017000
	 suSec is 204909
	 error code is 28
	 error Message is null
	 sname is HTTP/krbservice2@REALM2
	 msgType is 30

and

>>>KRBError:
	 sTime is Tue Jun 01 14:03:37 CEST 2021 1622549017000
	 suSec is 201727
	 error code is 13
	 error Message is KDC cannot accommodate requested option
	 sname is HTTP/krbservice2@REALM1
	 eData provided.
	 msgType is 30

When we look into the first error message with Wireshark, we found the error to be:
KRB5KRB_AP_PATH_NOT_ACCEPTED

When we decode the "Unknown eData field of KRB-ERROR" sent along with the first error message, we get:
C:\Users\me\Downloads>.\Err_6.4.5.exe c0000272
 for hex 0xc0000272 / decimal -1073741198
  STATUS_NO_MATCH                                                ntstatus.h
 There was no match for the specified key in the index.
 as an HRESULT: Severity: FAILURE (1), FACILITY_NULL (0x0), Code 0x272
 for hex 0x272 / decimal 626
  ERROR_NO_MORE_MATCHES                                          winerror.h
 There are no more matches for the current index
 enumeration.
 2 matches found for "c0000272"

From these error messages we understand the following: For some unknown reason in the second search request with the credentials retrieved from ReferralsCache it is not possible to find krbservice2 in REALM2 anymore.

## Analysis

We think that this is a bug in the JDK, because when we clear the ReferralsCache between search requests, it returns search results successfully. We did this manually with the remote debugging options of an IDE.

When remote-debugging into the code of CredentialsUtil we see that on the first request, Credentials of type Proxy are not stored, but the ones with None are. A comment in the code explicitly states that Credentials for Proxy should not be cached. However, in the second search request, the Credentials for Proxy are retrieved from the Cache. We think this contradicts the warning in the comment, as this is basically a caching of Proxy credentials. Therefore we suspect this to be the location of the bug and Credentials for type Proxy should not be retrieved from the cache.

Please fix.

## Triaging info

This is the data of the middle service, krbservice1 in the above described setup.

Java version: We tried both:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

and

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

We encounter the same problem in both versions.

What is your operating system and platform?
Windows Server 2016 Datacenter

Did it work before?
Our setup works successfully with krbservice1 and 2 in the same realm with resource-based delegation configured.

**Comment by Raytion** [comment]
Here is our suggestion for a fix. We successfully tested it on our internal environment.
[#318_add_check_before_requesting_referrals_cache_to_prevent_usage_of_an_inappropriate_tick.zip](https://github.com/adoptium/adoptium-support/files/6727176/318_add_check_before_requesting_referrals_cache_to_prevent_usage_of_an_inappropriate_tick.zip)

**Comment by Raytion** [comment]
Duplicated by https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8270137

**Comment by martinuy** [comment]
Thanks for reporting this bug.

Just for the record, the OpenJDK discussion is taking place in the context of https://github.com/openjdk/jdk/pull/5036

**Comment by karianna** [comment]
merged upstream.
