### ISSUE TITLE
JDK 8.0.292 Linux installs a dangling symlink (packaging problem)

### ISSUE THREAD

**Issue by datalogics-robb** [adoptium/adoptium-support#320]
## Summary

Unpacking jdk 8.0.292 build 10 leaves dangling symbolic links.
for x64 Linux:
```
 jdk8u292-b10/jre/lib/amd64/server/
total 9398
lrwxrwxrwx 1 robb procyon       20 Jun 18 14:22 libjsig.debuginfo -> ../libjsig.debuginfo
lrwxrwxrwx 1 robb procyon       13 Jun 18 14:22 libjsig.so -> ../libjsig.so
-rwxr-xr-x 1 robb procyon 17522288 Apr 20 16:09 libjvm.so
-rw-r--r-- 1 robb procyon     1423 Apr 20 16:09 Xusage.txt
```
And for armv8 Linux a similar problem is observed with that version in the `jre/lib/aarch64/server/` directory.

This dangling symlink causes errors when creating conan packages.

## Steps to reproduce

download package, unpack and observe the directory contents with "ls"
`ls -l jdk8u292-b10/jre/lib/amd64/server`

## Expected results

Symbolic links that point to files will show the target file.

## Actual results

Dangling symbolic links will blink  with a typical shell configuraiton.

## Triaging info

Java version: 8.0.292

source_subfolder/jdk8u292-b10/bin/java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

What is your operating system and platform?

Linux CentOS 7 x86_64 and AArch64.

How did you install Java?
tar -xvzf (with gnu tar)

gzipped tar file

Did it work before?

No dangling links are observed in older releases.

Did you test with other Java versions?
yes,
8.0.252
8.0.272
8.0.275
8.0.282
none of which demonstrate the problem.

**Comment by karianna** [comment]
This was fixed in https://github.com/adoptium/temurin-build/pull/2605 and will be released as part of the Eclipse Temurin July PSU
