### ISSUE TITLE
Adding signed jars to the module path of 11.0.11 can cause missing security providers

### ISSUE THREAD

**Issue by lerzeel2** [adoptium/adoptium-support#324]
## Summary

When certain signed jars are added to the module-path of version 11.0.11 it causes the list of security providers to shrink. This then causes connectivity issues with SSL handshakes because x25519 has become unsupported.
Removing those jars from the module path fixes the problem.
The same jar files did not cause problems in version 11.0.10 or before.
The java runtime is a standard download from the adoptopenjdk website, without any configuration changes.

## Steps to reproduce

One such signed jar is the JDBC driver "mssql-jdbc-9.2.1.jre11.jar" for MS SQLServer (search for sql server jdbc download).
Adding this file to the module path causes the length of java.security.Security.getProviders() to drop from 13 to 4.
Manually removing the digital signatures from the jar file resolves the problem.
Some signed jars do not cause problems (jogl) while others do.

## Expected results

We expected the full list of security providers, like in version 11.0.10 and before.
We were also expecting to see an error message from the class loader if it had problems with the digital signatures.

## Actual results

static public void main(String[] args)
{
    for(Provider provider: Security.getProviders()) System.out.println("Provider: "+provider);
}

the list in version 11.0.11:
SUN, SunRsaSign, SunJSSE, SunJCE

the list in version 11.0.10 and before:
SUN, SunRsaSign, SunEC, SunJSSE, SunJCE, SunJGSS, SunSASL, XMLDSig, SunPCSC, JdkLDAP, JdkSASL, SunMSCAPI, SunPKCS11

Without the problem jar file in the module path the 11.0.11 list equals the 11.0.10 one.

## Triaging info

Java version:

11.0.11+9
tested with both JRE and JDK

What is your operating system and platform?

Windows 10 21H1 on x64
but it also happens with docker image adoptopenjdk/openjdk11:alpine-jre hosted on Flatcar Container Linux

How did you install Java?

Downloaded JDK and JRE zips for Windows x64 from https://adoptopenjdk.net/releases.html

Did it work before?

We never got it working in 11.0.11.

Did you test with other Java versions?

Yes, it has worked with 11.0.10 and before, like 11.0.8, 11.0.6 and 11.0.1 for example.

**Comment by jerboaa** [comment]
This looks like:
https://bugs.openjdk.java.net/browse/JDK-8266929

The above fix is slated for 11.0.12 (July 2021 CPU, real soon now). Please test the EA version (11.0.12+6), for example from here:
https://adoptopenjdk.net/upstream.html?variant=openjdk11&ga=ea

**Comment by lerzeel2** [comment]
Indeed, it seems to describe the problems we are seeing.
I failed to find the bug reports because I got focused on the symptoms "no common named group" exception, and not on the cause.
So big thanks for helping out, and indeed, EA version 11.0.12+6 does solve the problem :)
