### ISSUE TITLE
MSCTF.dll

### ISSUE THREAD

**Issue by AmateurPotion** [adoptium/adoptium-support#326]
## Question
How can I some countermeasures about this?

[hs_err_pid14956.log](https://github.com/adoptium/adoptium-support/files/6836758/hs_err_pid14956.log)

## Context

Java version:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

Your operating system and platform: Windows 11 Home

**Comment by karianna** [comment]
@AmateurPotion - Windows 11 has not gone GA yet and is therefore untested.  Can you tell us a little bit more about what you're using Java for here?

**Comment by AmateurPotion** [comment]
@karianna Can you tell me where to contact jetbrains? I searched the jetbrains website, but could not find the contact information due to my narrow field of view.

**Comment by karianna** [comment]
https://youtrack.jetbrains.com/issues/idea/

**Comment by karianna** [comment]
Resolved in latest IntelliJ IDEA and 17.0.3
