### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by artfultom** [adoptium/adoptium-support#327]
Hello. My SpringBoot application crashed with below error.

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007fc1a218084e, pid=25825, tid=25869
JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10)
Java VM: OpenJDK 64-Bit Server VM (11.0.5+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
V  [libjvm.so+0x75084e]  frame::sender(RegisterMap*) const+0x6e

[hs_err_pid25825.log.txt](https://github.com/adoptium/temurin-build/files/6860945/hs_err_pid25825.log.txt)

**Comment by karianna** [comment]
Can you try the latest version (11.0.11) - 11.0.12 is coming out next week so you could also wait for that.

**Comment by Keval0490** [comment]
I have same issue, e2 Studio Launch & shutdown in seconds.

Yes I have latest version "e2studio_v2021-04_fsp_v3.1.0"

Using for Renesas RA Series 

Help me with the solution...

**Comment by karianna** [comment]
@Keval0490 Please try the lastest Java 11.0.12 from adoptium.net

**Comment by karianna** [comment]
Your log file is showing JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10), please send a log file with 11.0.12

**Comment by Keval0490** [comment]
@karianna  Sir I didn't get what you want.

where can I find this log file.

The problem is with e2Studio crashing. I have share you e2Studio log file.

**Comment by karianna** [comment]
@Keval0490 The hs_err_pid11044.log crash log states that you are using 11.0.8, you need to run your application with 11.0.12

**Comment by Keval0490** [comment]
@karianna  How can I change Java version for e2Studio.exe file ?

**Comment by karianna** [comment]
It looks like an Eclipse-based tool, so there is likely an eclipse.ini file somewhere you can edit.  I would contact the vendor behind that product for details though, we don't know that project.

**Comment by Keval0490** [comment]
@karianna 

Yes sir I do have e2Studion.ini file, And yes it is Eclipse based software.

[e2studio.txt](https://github.com/adoptium/adoptium-support/files/6979918/e2studio.txt)

File format not supported by github, hence extension changed to txt from ini

**Comment by karianna** [comment]
You can try Replacing:

`-vm 
plugins/com.renesas.runtime.jdk.hotspot.win32.x86_64_11.0.8.202009102051/jdk-11.0.8+10/bin`

with 

`-vm 
<path to where you've installed jdk 11.0.12>/bin`

Again, this really isn't for us to advise you on though, you need to speak to your vendor.
