### ISSUE TITLE
Font.createFont: IOException Problem reading font data.

### ISSUE THREAD

**Issue by gsegatori** [adoptium/adoptium-support#329]
This is as of AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
SO: Windows Server 2008/2012 but not tested in other Windows (so I assume all windows)

Having a ttf file to load inside/outside the jar is getting this error always if we use the commons-daemons (my version 1.0.15), so starting the application as windows service created (using the jvm.dll) we have this error if we try to do:

`Font.createFont(Font.TRUETYPE_FONT, fontstream);`
```

 java.io.IOException: Problem reading font data.
	at java.awt.Font.createFont0(Unknown Source) ~[?:?]
	at java.awt.Font.createFont(Unknown Source) ~[?:?]
```
if we try to start application with standard command line all is working, this is getting only when we have a service created from commons-daemon

**Comment by jerboaa** [comment]
Does this also happen with the latest release? `11.0.12+7`

**Comment by gsegatori** [comment]
> 
> 
> Does this also happen with the latest release? `11.0.12+7`

Yes just tried....same behaviour

**Comment by karianna** [comment]
@gsegatori can you try with 11.0.15?
