### ISSUE TITLE
Not clear where the adoptium debian package repository is hosted

### ISSUE THREAD

**Issue by losmurfs** [adoptium/adoptium-support#332]
Is there a replacement for https://adoptopenjdk.jfrog.io/ui/native/deb/dists/ ?

https://adoptopenjdk.jfrog.io/ui/native/deb/dists/ does not contain latest releases.

**Comment by karianna** [comment]
We're still working on where the Linux packages are going to go.

**Comment by losmurfs** [comment]
Thank you for the rapid response

**Comment by FSichinger** [comment]
> We're still working on where the Linux packages are going to go.

Any update so far? 

AdoptOpenJDK`s last debian package release is jdk-11.0.11, which is for now one version behind.

**Comment by TuningYourCode** [comment]
This is also an issue for us as we would have to rewrite some of our automation's (provisioning, deployment etc.) if there is no repository for the current version.
Also automatic updates are possible if there is an repository and we don't have to take a look every few days to check if there is a new (critical?) bugfix release.
I think that was one of the reasons why AdoptOpenJDK got so popular as they provided repositories for their builds.

Let us know if we can somehow help with the implementation of hosted repositories.

**Comment by karianna** [comment]
See https://www.github.com/adoptium/installer/issues/330 - we're getting closer!

**Comment by losmurfs** [comment]
https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/
