### ISSUE TITLE
Will Adoptium provide packaged "JRE" versions of Java in addition to the JDK as AdoptOpenJDK did?

### ISSUE THREAD

**Issue by titou10titou10** [adoptium/adoptium-support#333]
## Question

Is it planned for Adoptium to provide a package containing only the "JRE" part of the JDK, in addition to the JDK,  as AdoptOpenJDK did?

## Context

Java version:

- All versions of Java

Your operating system and platform:

- all OS (At least a zip for Windows x64)

**Comment by karianna** [comment]
https://github.com/adoptium/temurin-build/issues/2683

**Comment by kscheel** [comment]
@karianna According to the discussion in #2683 a JRE Release of Java 8, 11 and 16 is not available yet but you plan to do so? And with Java 17 you'll stop creating JRE releases?

Cheers and thanks for working on this project :)

**Comment by karianna** [comment]
@kscheel That is correct although it'll take a few weeks as we need to do compliance runs on the JREs

**Comment by karianna** [comment]
> @kscheel That is correct although it'll take a few weeks as we need to do compliance runs on the JREs

Correction to this - only JREs for 8 and 11 (now pretty much complete) but *not* for 16.
