### ISSUE TITLE
Open Office is 32 bit but your openjdk is only available in 64 Bit. Why?

### ISSUE THREAD

**Issue by NickDaGeekUK** [adoptium/adoptium-support#336]
## Context

Java version:jdk-11.0.12+7.

Your operating system and platform: "Windows 10 2004 on x64"

**Comment by smlambert** [comment]
We have not yet completed our release (there is a lot of testing that occurs before we release them and its not yet finished), so the Windows 32bit binaries are not yet released.  Regular updates are provided via the [release channel](https://adoptium.slack.com/archives/CLCFNV2JG) in Slack.  We've also update the website banner at adoptium.net to reflect this.

<img width="880" alt="Screen Shot 2021-08-07 at 7 45 11 AM" src="https://user-images.githubusercontent.com/2836948/128599023-920ccb5a-4580-4e00-bb4f-50bc650b66d9.png">
