### ISSUE TITLE
Adoptium Windows x86 Builds

### ISSUE THREAD

**Issue by kwheat2064** [adoptium/adoptium-support#337]
## Question

Will Adoptium provide x86 builds for JDK 8 on Windows? We have an application that we are in the midst of migrating to JDK11, that still requires JDK8 x86.

## Context

Java version:

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK Client VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**Comment by karianna** [comment]
Yes coming out over the next two weeks
