### ISSUE TITLE
Not able to find Adopt Open JDK 11.0.6 or before in https://adoptopenjdk.net/archive.html

### ISSUE THREAD

**Issue by mail2anandpatil** [adoptium/adoptium-support#340]
Hi Adopt Support team,

Could you please share the link from where can we download the Adopt Open JDK 11.0.6 or before as I am not able to find the same in in https://adoptopenjdk.net/archive.html

Thanks,
Anand Patil

**Comment by karianna** [comment]
You'll have to go to the Adoptopenjdk/openjdk11-binaries GitHub repo and look under releases

**Comment by mail2anandpatil** [comment]
Thanks, Karianna for your quick response.
Yes, I am able to find in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.6%2B10
