### ISSUE TITLE
building an ubuntu snap which contains an adoptopenjdk jre

### ISSUE THREAD

**Issue by RBornat** [adoptium/adoptium-support#345]
## Question

I'm the developer of jape, a formal logic proof editor which uses java to provide its UI and OCaml to provide a proof engine (see rbornat/jape on github if necessary). I've built a snap for Ubuntu 20.04, which includes a jre built using jlink from your Java 11 (details below). Snaps require that the developer subscribes to 'interfaces' which are external resources that the application is allowed to access. The snappy-debug program lets you see what the application is up to. It reveals (I think) that the jre is using system files extensively. For example see the next section (sorry for the length). It's accessing /proc, /etc, /sys and I'm not sure what else. Some of this is uid specific, some is pid specific. 

Question: is all this stuff, as I suspect, down to the activity of the java garbage collector?

It looks to me, as a snap novice, that this activity makes it impossible to register the snap. For example, the system-files interface seems to require a promise that it doesn't access /etc or /sys (but it does).

Does the community have experience of making snaps containing jre's? If so, what to do?

## snappy-debug output

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/proc/1/cgroup" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /proc/1/cgroup (read)
Suggestion:
* adjust program to not access '@{PROC}/@{pid}/cgroup'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/proc/2590/coredump_filter" pid=2590 comm="java" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
File: /proc/2590/coredump_filter (write)
Suggestion:
* adjust program to not access '@{PROC}/@{pid}/coredump_filter'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="truncate" profile="snap.jape.jape" name="/proc/2590/coredump_filter" pid=2590 comm="java" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
File: /proc/2590/coredump_filter (write)
Suggestion:
* adjust program to not access '@{PROC}/@{pid}/coredump_filter'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/proc/sys/kernel/core_pattern" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /proc/sys/kernel/core_pattern (read)
Suggestion:
* adjust program to not access '@{PROC}/sys/kernel/core_pattern'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/proc/sys/kernel/core_uses_pid" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /proc/sys/kernel/core_uses_pid (read)
Suggestion:
* adjust program to not access '@{PROC}/sys/kernel/core_uses_pid'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/proc/1/cgroup" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /proc/1/cgroup (read)
Suggestion:
* adjust program to not access '@{PROC}/@{pid}/cgroup'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes (read)
Suggestions:
* adjust program to not access '/sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes'
* adjust program to not access '/sys/fs/cgroup/memory/user.slice/user-[0-9]*.slice/user@[0-9]*.service/memory.limit_in_bytes'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/etc/host.conf" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /etc/host.conf (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'system-files (see https://forum.snapcraft.io/t/the-system-files-interface for acceptance criteria)' to 'plugs'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/run/systemd/resolve/stub-resolv.conf" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=101
File: /run/systemd/resolve/stub-resolv.conf (read)
Suggestions:
* adjust program to use $SNAP_DATA
* adjust program to use /run/shm/snap.$SNAP_NAME.*
* adjust program to use /run/snap.$SNAP_NAME.*
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add one of 'firewall-control, fwupd, network, network-bind, network-control, network-observe' to 'plugs'

= AppArmor =
Time: Aug 14 12:46:43
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/etc/hosts" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /etc/hosts (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
* add 'system-files (see https://forum.snapcraft.io/t/the-system-files-interface for acceptance criteria)' to 'plugs'

= AppArmor =
Time: Aug 14 12:46:44
Log: apparmor="ALLOWED" operation="open" profile="snap.jape.jape" name="/sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes" pid=2590 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes (read)
Suggestions:
* adjust program to not access '/sys/fs/cgroup/memory/user.slice/user-1000.slice/user@1000.service/memory.limit_in_bytes'
* adjust program to not access '/sys/fs/cgroup/memory/user.slice/user-[0-9]*.slice/user@[0-9]*.service/memory.limit_in_bytes'
-->

## Context

Java version:

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)

Your operating system and platform:

Ubuntu 20.04 on VirtualBox on x86-64, host MacOS 10.15.7

**Comment by RBornat** [comment]
On reflection, this may be an openJ9 issue. I shall investigate.

**Comment by karianna** [comment]
Closing this, please do reopen if it's still an issue on OpenJ9 (Semeru) that matches 11.0.15
