### ISSUE TITLE
Link to download AdoptOpenJDK JRE version jreu302 is broken, it points to jreu292

### ISSUE THREAD

**Issue by shuklapranjal** [adoptium/adoptium-support#346]
- Click on the link https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot
- You should see version as jdk8u302-b08, apply filter to choose Linux and X64.
- You will see two download options, one for JDK and another for JRE.
- Click on JRE and you'll see that update 292 is getting downloaded instead of update 302.

**Comment by karianna** [comment]
Yep known issue, its because we haven't released the JRE yet

**Comment by shuklapranjal** [comment]
Can we take the JRE folder from the JDK Distribution of release 302 and deploy on servers? Do you think that might not be the correct way and we must wait for JRE to officially release?

**Comment by karianna** [comment]
You could if you really wanted to but I'd personally wait for the official release (not long now).
