### ISSUE TITLE
Latest release 

### ISSUE THREAD

**Issue by avivbebes** [adoptium/adoptium-support#347]
Hi,
Latest release is jdk-11.0.12+7 but in the links it still on 11.0.11_9.
Need to update download links.
Thanks,
Aviv

**Comment by karianna** [comment]
Is this on adoptium.net? AdoptOpenJDK.net is the 'old' site.

**Comment by avivbebes** [comment]
In AdoptOpenJDK.net in adoptium.net there is no jre only jdk.
why is that?

**Comment by karianna** [comment]
jres are still being worked on and released - https://github.com/adoptium/adoptium/issues/68
