### ISSUE TITLE
Hanging GitHub Action builds on windows-latest, jdk 8, adopt-openj9

### ISSUE THREAD

**Issue by kriegaex** [adoptium/adoptium-support#350]
Please refer to https://github.com/actions/setup-java/issues/211 for
  * a detailed problem description,
  * version numbers,
  * links to several failing (and also one previously passing) builds.

I have no way of being sure if the problem is caused by the JVM itself or some quirk in the GitHub actions environment. I hope you can enlighten me. Thank you,

**Comment by kriegaex** [comment]
FYI, I created https://support.github.com/ticket/personal/0/1290814, which probably you cannot access. Let's see what GH support says. If I have any new insights, I am also going to keep you posted here.

**Comment by kriegaex** [comment]
I just had the idea to run this in Git Bash on my local Windows workstation (not on GitHub this time):

```bash
while true; do ./java.exe -version; ./java.exe -X; sleep 1; done
```

The JVM version I used was:

```text
openjdk version "1.8.0_302"
IBM Semeru Runtime Open Edition (build 1.8.0_302-b08)
Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20210730_192 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - de702c3174 based on jdk8u302-b08)
```

After a few seconds, this happened:

```text
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FF919692406 ContextFlags=0010004f
Handler1=00007FF8B376CBE0 Handler2=00007FF8EDB393A0
RDI=000001BD1B7BE698 RSI=00007FF9196AC3C0 RAX=000000798008DB53 RBX=0000000000000001
RCX=00000079723FBA40 RDX=000001BD02000002 R8=0000000000000000 R9=0000000000002010
R10=0000000000002000 R11=0000000000000001 R12=0000000000000003 R13=0000000000000003
R14=00007FF8F173B901 R15=0000000000000003
RIP=00007FF919692406 RSP=00000079723FBFD0 RBP=00000079723FC670 EFLAGS=0200000200000202
FS=0053 ES=002B DS=002B
XMM0 00000079723fbb60 (f: 1916779392.000000, d: 2.577085e-312)
XMM1 00007ff919609250 (f: 425759296.000000, d: 6.951891e-310)
XMM2 00000079723fba70 (f: 1916779136.000000, d: 2.577085e-312)
XMM3 0000007971f3f000 (f: 1911812096.000000, d: 2.577061e-312)
XMM4 0000000000000001 (f: 1.000000, d: 4.940656e-324)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\WINDOWS\SYSTEM32\ntdll.dll
Module_base_address=00007FF919590000 Offset_in_DLL=0000000000102406
Target=2_90_20210730_192 (Windows 10 10.0 build 19042)
CPU=amd64 (4 logical CPUs) (0x3f6a91000 RAM)
----------- Stack Backtrace -----------
```

Then, I had to manually kill java.exe in the task manager, and the endless loop continued until a minute or so later the next segfault happened. I can also reproduce it in cmd.exe with a similatr endless loop, so it is not specific to the shell used.

I think that there is a real bug in OpenJ9, and it exists in older versions too, because on GitHub I also saw hanging builds on update 292, not just 302. I suspect that this might be what kills my Maven builds in different stages. If simply running the JVM without even executing a Java program already can make it segfault, something is clkearly wrong.

**Comment by keithc-ca** [comment]
I read your comment with interest: I hoped it would mean we could understand and hopefully fix this problem - unfortunately, I was disappointed.

I created a batch file with this content:
```
@echo off

set JAVA=C:\jdk\ibm-semeru-open-jdk8u302b08-x64-openj9-0.27.0\bin\java

echo "Using JAVA=%JAVA%"

:loop
	C:\cygwin\bin\date "+%%Y-%%m-%%d@%%H:%%M:%%S"
	%JAVA% -version
	%JAVA% -X
	sleep 1
	goto loop
```
I let it run for over an hour without encountering any problems. 
I used the identical java version.
My system is running Windows 21H1 (OS Build 19043.1165).

**Comment by keithc-ca** [comment]
OpenJ9 does not distinguish between Intel and AMD cpus: both will report 'CPU=amd64'.

Do your github actions also run in the German locale? My system runs in the en-ca locale. I would get lost in German, but you seem to understand English: could you try in an English locale to see if that difference is significant?

Your jdk is installed in a location whose path contains a space, while mine did not. I'll try again using a path with spaces to see if that's relevant.

Do you have any other Java versions on your PATH? They might conflict with the one you're trying to use.

A crash like you originally reported should create a system dump (named 'core.*.dmp'). If you can find one and share it with us that would also help.

**Comment by keithc-ca** [comment]
As it shouldn't, the space in the location did not make a difference: I ran the loop (without 'sleep 1') for 20 minutes without encountering a problem.

**Comment by kriegaex** [comment]
There are no *.dmp files, maybe because the Java process is not terminating until I manually kill it in task manager. GitHub actions run on the default locale, whatever that is (C or US English), but not with German locale. The Windows locale does not make I difference, I guess. Anything else I can try? Why does the JVM print a segfault error but not a core dump file? Is there really nothing you can infer from the segfault message? The information printed there must have some use.

**Comment by kriegaex** [comment]
> Do you have any other Java versions on your PATH? They might conflict with the one you're trying to use.

As a matter of fact, I do. Folders like
```text
/c/Program Files/Java/jdk-16/bin
/c/Program Files/Common Files/Oracle/Java/javapath
/c/ProgramData/Oracle/Java/javapath
/c/Program Files (x86)/Common Files/Oracle/Java/javapath
```
are on my `PATH` on Windows (folder names taken from Unix-style Git Bash in this case).

After the hint in https://github.com/actions/setup-java/issues/211#issuecomment-920849262, my GitHub build passed, so I also tried something similar locally, removing the folders mentioned above from the path and adding the OpenJ9 path instead. Now I can no longer reproduce the segfault. Does this help you fix the problem? It only occurs on JDK 8, not 11 and 16, so maybe there is a speciic problem with path handling there.

**Comment by keithc-ca** [comment]
As implied in https://github.com/actions/setup-java/issues/211#issuecomment-922761543, I think there's a conflict between the OpenJ9 VM you're trying to use and others on the system. Can you try this command to see if some shared library is coming from an unexpected location?
```
java -Xtrace:print=omrport.476 -version
```

**Comment by kriegaex** [comment]
> Can you try this command to see if some shared library is coming from an unexpected location?
> 
> ```
> java -Xtrace:print=omrport.476 -version
> ```

Sorry for the late reply. Somehow the notification e-mail was set to read and I forgot to set it back to unread.

```text
XXX>set JAVA=c:\Program Files\Semeru\jdk-8.0.302.8-openj9\bin\java

XXX>"%JAVA%" -Xtrace:print=omrport.476 -version
04:13:50.015*0x16f00         omrport.476      - omrsl_open_shared_library using mangledName j9thr29.dll
04:13:50.015 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.016 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\jclse29.dll
04:13:50.016 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.017 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\java.dll
04:13:50.018 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.019 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\java
04:13:50.020 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.020 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\java.dll
04:13:50.024 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.024 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\zip.dll
04:13:50.025 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.026 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\zip
04:13:50.027 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.027 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\zip.dll
04:13:50.029 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.029 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\j9jit29.dll
04:13:50.057 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.058 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\java.dll
04:13:50.059 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName <NULL>
04:13:50.059 0x16f00         omrport.476      - omrsl_open_shared_library using mangledName c:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre\bin\default\java
openjdk version "1.8.0_302"
IBM Semeru Runtime Open Edition (build 1.8.0_302-b08)
Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20210730_192 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - de702c3174 based on jdk8u302-b08)
```

**Comment by kriegaex** [comment]
Instead of just letting this rot despite a ton of information I provided, maybe someone can follow up. That would be really nice. Despite the hints about what to inspect and what to change in my local settings, the error still occurred, but nobody seems to care. And now the issue is marked as stale, even though it was me who wrote the last message.

**Comment by mstoodle** [comment]
Hi @kriegaex it is weird there are no diagnostic files generated. Can you run with the additional java option `-Xdump:what` to see what it lists?

**Comment by mstoodle** [comment]
It shouldn't be any different, but just to be thorough: can you get that trace output Keith requested for a run that crashes?

**Comment by kriegaex** [comment]
@mstoodle, AFAIK I provided all trances which Keith requested. And dumps for crashing JVMs are simply not being generated, just like I said clearly before.

**Comment by kriegaex** [comment]
Some more info: I upgraded to jdk-8.0.332.9-openj9, same result (freeze, if I run several times) on my laptop with these specs (sorry, in German):

```text
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Systemhersteller	LENOVO
Systemmodell	20HR002MGE
Systemtyp	x64-basierter PC
System-SKU	LENOVO_MT_20HR_BU_Think_FM_ThinkPad X1 Carbon 5th
Prozessor	Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2904 MHz, 2 Kern(e), 4 logische(r) Prozessor(en)
BIOS-Version/-Datum	LENOVO N1MET68W (1.53 ), 11.11.2021
SMBIOS-Version	3.0
Version des eingebetteten Controllers	1.22
BIOS-Modus	UEFI
BaseBoard-Hersteller	LENOVO
BaseBoard-Produkt	20HR002MGE
BaseBoard-Version	0B98417 WIN
Installierter physischer Speicher (RAM)	16,0 GB
```

On my older desktop PC with the following specs, I cannot reproduce the problem:

```text
Betriebsystemname	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044
Systemhersteller	MSI
Systemmodell	MS-7846
Systemtyp	x64-basierter PC
System-SKU	To be filled by O.E.M.
Prozessor	Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, 3501 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends Inc. V10.0, 30.08.2013
SMBIOS-Version	2.7
Version des eingebetteten Controllers	255.255
BIOS-Modus	Vorgängerversion
BaseBoard-Hersteller	MSI
BaseBoard-Produkt	H81M-P33 V2 (MS-7846)
BaseBoard-Version	2.0
Installierter physischer Speicher (RAM)	16,0 GB
```

Not sure if that is helpful at all, but FWIW, I copied those specs from the Windows system info.

**Comment by mstoodle** [comment]
Sorry if I'm being obtuse, I just want to be sure. The output you included before (on Jan 13) for `java -Xtrace:print=omrport.476 -version` showed the -version output being correctly displayed after the trace output. Did that run also subsequently crash? If that run didn't crash, please paste the output of a command that crashes.

When I run `java -Xdump:what` on my laptop, it outputs to the terminal:
```
$ java -Xdump:what

Registered dump agents
----------------------
-Xdump:system:
    events=gpf+abort+traceassert+corruptcache,
    file=/Users/mstoodle/git/core.%Y%m%d.%H%M%S.%pid.%seq.dmp,
    range=1..0,
    priority=999,
    request=serial
----------------------
-Xdump:system:
    events=systhrow,
    filter=java/lang/OutOfMemoryError,
    file=/Users/mstoodle/git/core.%Y%m%d.%H%M%S.%pid.%seq.dmp,
    range=1..1,
    priority=999,
    request=exclusive+compact+prepwalk
----------------------
...
```

**Comment by kriegaex** [comment]
> Whatever `-Xdump:what` is meant to dump to the console or the file system, I am seeing nothing of it.

I must have mistyped something, now `-Xdump:what` indeed does display something. Again, this is my batch file which repeatedly runs the Java process:

```batch
@echo off
set JAVA=c:\Program Files\Semeru\jdk-8.0.332.9-openj9\bin\java
echo Using JAVA=%JAVA%

:loop
  c:\msys64\usr\bin\date.exe "+%%Y-%%m-%%d@%%H:%%M:%%S"
  REM "%JAVA%" -version
  REM "%JAVA%" -X
  "%JAVA%" -Xdump:what
  REM sleep 1
  goto loop
```

After just a handful of loops, it yields:

```text
2022-06-04@09:34:30

Registered dump agents
----------------------
-Xdump:system:
    events=gpf+abort+traceassert+corruptcache,
    file=C:\Users\alexa\core.%Y%m%d.%H%M%S.%pid.%seq.dmp,
    range=1..0,
    priority=999,
    request=serial
----------------------
-Xdump:system:
    events=systhrow,
    filter=java/lang/OutOfMemoryError,
    file=C:\Users\alexa\core.%Y%m%d.%H%M%S.%pid.%seq.dmp,
    range=1..1,
    priority=999,
    request=exclusive+compact+prepwalk
----------------------
-Xdump:heap:
    events=systhrow,
    filter=java/lang/OutOfMemoryError,
    file=C:\Users\alexa\heapdump.%Y%m%d.%H%M%S.%pid.%seq.phd,
    range=1..4,
    priority=500,
    request=exclusive+compact+prepwalk,
    opts=PHD
----------------------
-Xdump:java:
    events=gpf+user+abort+traceassert+corruptcache,
    file=C:\Users\alexa\javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,
    range=1..0,
    priority=400,
    request=exclusive+preempt
----------------------
-Xdump:java:
    events=systhrow,
    filter=java/lang/OutOfMemoryError,
    file=C:\Users\alexa\javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,
    range=1..4,
    priority=400,
    request=exclusive+preempt
----------------------
-Xdump:snap:
    events=gpf+abort+traceassert+corruptcache,
    file=C:\Users\alexa\Snap.%Y%m%d.%H%M%S.%pid.%seq.trc,
    range=1..0,
    priority=300,
    request=serial
----------------------
-Xdump:snap:
    events=systhrow,
    filter=java/lang/OutOfMemoryError,
    file=C:\Users\alexa\Snap.%Y%m%d.%H%M%S.%pid.%seq.trc,
    range=1..4,
    priority=300,
    request=serial
----------------------
-Xdump:jit:
    events=gpf+abort,
    file=C:\Users\alexa\jitdump.%Y%m%d.%H%M%S.%pid.%seq.dmp,
    range=1..0,
    priority=200,
    request=serial
----------------------

Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFDAADB23F6 ContextFlags=0010004f
Handler1=00007FFD6D01A650 Handler2=00007FFD923693D0
RDI=000001B4D69D3008 RSI=00007FFDAADCC3C0 RAX=00007FFDAACCCB51 RBX=0000000000000001
RCX=000001B4D3CA0C1C RDX=000000A0E713BD29 R8=0000000000000000 R9=000000A0E6DAB000
R10=00007FFDAACCD23B R11=0000000000000001 R12=0000000000000003 R13=0000000000000003
R14=00007FFD92C3B901 R15=0000000000000003
RIP=00007FFDAADB23F6 RSP=000000A0E713C430 RBP=000000A0E713CAD0 EFLAGS=AACDB86B00000206
FS=0053 ES=002B DS=002B
XMM0 000000a0e713bfc0 (f: 3876831232.000000, d: 3.414347e-312)
XMM1 00007ffdaad29240 (f: 2865926656.000000, d: 6.952861e-310)
XMM2 000000a0e713bed0 (f: 3876830976.000000, d: 3.414347e-312)
XMM3 000000a0e6dab000 (f: 3873091584.000000, d: 3.414329e-312)
XMM4 0000000000000001 (f: 1.000000, d: 4.940656e-324)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\WINDOWS\SYSTEM32\ntdll.dll
Module_base_address=00007FFDAACB0000 Offset_in_DLL=00000000001023f6
Target=2_90_20220422_375 (Windows 10 10.0 build 19044)
CPU=amd64 (4 logical CPUs) (0x3f6a91000 RAM)
----------- Stack Backtrace -----------
```

**Comment by keithc-ca** [comment]
I had another look at this today. I see some similarity with https://github.com/eclipse-openj9/openj9/issues/3747 which was fixed by https://github.com/eclipse-openj9/openj9/pull/3650, but that only applied to Java 11+. Could you try using Java 11 (or 17) to see if this problem still occurs? If not, we could explore expanding the applicability of https://github.com/eclipse-openj9/openj9/pull/3650 to Java 8.

**Comment by kriegaex** [comment]
Does https://github.com/adoptium/adoptium-support/issues/350#issuecomment-917377287 answer your question?

**Comment by keithc-ca** [comment]
Sorry, I guess I missed that when I last reviewed this. Yes, it does answer my question: I think it means we need to extend the change made for Java 11+ so it also applies to Java 8.

**Comment by karianna** [comment]
@keithc-ca Can this be closed now?

**Comment by kriegaex** [comment]
@keithc-ca, I would also be interested in whether something was back-ported in order to address this issue. If so, which JDK 8 version would you like me to test?

**Comment by keithc-ca** [comment]
I think either this issue, or one at openj9 should remain open. Unfortunately, I have not had time to work on this yet.

**Comment by karianna** [comment]
We'll close this as it's being tracked upstream.

**Comment by kriegaex** [comment]
Sorry, I strongly disagree with closing this issue. I am tracking it here, and it is not solved. Whenn it is, it can be closed in multiple locations, which should take 20 seconds per project. If I cannot track it here, where is "upstream", pray tell? At least, post a link where I can subscribe, track and comment on the issue.

**Comment by keithc-ca** [comment]
Please open an issue with [openj9](https://github.com/eclipse-openj9/openj9/issues).

**Comment by kriegaex** [comment]
Why would I? Here we have a long-standing issue with lots of technical detail. What is the value of opening yet another issue and starting over? If you would simply leave this issue open and fix it, it would be better. Or is one of you is admin in both projects, why not move this issue into the target project where you prefer to have it? Then everyone watching the issue could continue to do so, and the details would be readily available without clicking a link in a new stub issue.

**Comment by keithc-ca** [comment]
I cannot reopen this and it seems those that could don't want to do so. If issues can be "moved" between projects, I was not aware of that possibility, but, again, I can't do that.

The issue you would open at openj9 can make reference to this so the history is not lost, nor need to be repeated: you don't need to "start over".

**Comment by karianna** [comment]
I've reopened this, apologies I thought the tickets were linked

**Comment by karianna** [comment]
Closing as this is reported upstream
