### ISSUE TITLE
How to capture application monitoring information from the docker container

### ISSUE THREAD

**Issue by mahesh-tier1app** [adoptium/adoptium-support#351]
I have more than one java application running in separate docker containers. I am trying to collect monitoring data such as GC log, thread dump, heap dump from the java process running inside a container using tools like jstat, jstack, jmap. Is it possible to capture this information from the host(outside containers)?

I am new to the containerized world. I understand that the PID namespace of the host and container is different. When I execute ```jstack <PID> > thread_dump.txt``` from the host, it shows error message: **Unable to open socket file /proc/root/tmp/.java_pid: target process doesn't respond within 10500ms or HotSpot VM not loaded**

> Where PID is process id from the host PID namespace.

When I execute ```jstack``` within a container (```docker exec -it <container_id_or_name>```) then it is able to capture thread dump.

> Where PID is process id from the container PID namespace.

#### Java version
java-11-openjdk-11.0.12.0.7-0.el7_9.x86_64

#### OS & Docker version

CentOS Linux release 7.9.2009 (Core)

docker-scan-plugin-0.8.0-3.el7.x86_64
docker-ce-cli-20.10.8-3.el7.x86_64
docker-ce-rootless-extras-20.10.8-3.el7.x86_64
docker-ce-20.10.8-3.el7.x86_64

Any hints on how to solve this? Thanks in advance.

**Comment by karianna** [comment]
I'd recommend Java Flight Recorder (JFR) and use one of the streaming JFR solutions from New Relic, Microsoft or Red Hat in this case.
