### ISSUE TITLE
jdk-11.0.12+7 Windows x86 downloads

### ISSUE THREAD

**Issue by treado** [adoptium/adoptium-support#353]
## Summary
Hi team,
There seems to be a couple of issues with the Windows x86 jdk-11.0.12+7 downloads:
- downloading the jdk msi, the resulting file is 1KB, so probably missing something.
- downloading the jre msi, I get OpenJDK11U-jre_x86-32_windows_hotspot_11.0.11_9.msi, rather than 11.0.12.

Many thanks
Mike

## Steps to reproduce

Happened when i downloaded from
https://adoptopenjdk.net/releases.html

or 

https://adoptium.net/releases.html (for the JDK anyway)

## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by karianna** [comment]
Now released and resolved.
