### ISSUE TITLE
jdk version 1.8.0_292  Mac11.2.3  Failed to write core dump. Core dumps have been disabled

### ISSUE THREAD

**Issue by antyang26** [adoptium/adoptium-support#354]
how to deal ?
looking forward to replying to the email
thanks!

describe: 
enveriment :IntelliJIdea2021.1
start tomcat: error message
 Abnormal build process termination: 
Build process started. Classpath: /Applications/IntelliJ IDEA.app/Contents/plugins/java/lib/jps-launcher.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/tools.jar
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x000000011165e608, pid=1349, tid=0x0000000000006363
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# j  com.sun.tools.javac.comp.ConstFold.fold2(ILcom/sun/tools/javac/code/Type;Lcom/sun/tools/javac/code/Type;)Lcom/sun/tools/javac/code/Type;+877
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/didi/Library/Caches/JetBrains/IntelliJIdea2021.1/compile-server/hs_err_pid1349.log
Compiled method (c1)   33720 1611       1       java.lang.Integer::intValue (5 bytes)
 total in heap  [0x0000000111ba3bd0,0x0000000111ba3e60] = 656
 relocation     [0x0000000111ba3cf8,0x0000000111ba3d20] = 40
 main code      [0x0000000111ba3d20,0x0000000111ba3da0] = 128
 stub code      [0x0000000111ba3da0,0x0000000111ba3e30] = 144
 scopes data    [0x0000000111ba3e30,0x0000000111ba3e38] = 8
 scopes pcs     [0x0000000111ba3e38,0x0000000111ba3e58] = 32
 dependencies   [0x0000000111ba3e58,0x0000000111ba3e60] = 8

**Comment by antyang26** [comment]
> Try one of the 3 solutions outlined in https://izziswift.com/how-to-generate-core-dumps-in-mac-os-x/

I tried,  Solution no. 1, no.2,  no.3,  The error is still there
In my mac, only one project have the problem， others project is normal
no .4 method , I can't find pId, this method has not been tried

I also tried unstall idea, install a new idea   ,change jdk,  clear project, and git clone the error project for a new space
Sadly, it still failed

**Comment by karianna** [comment]
That's very interesting it's only happening on one project.  So other projects also crash but **are** able to write crash reports?

**Comment by karianna** [comment]
Closing this, unable to reproduce with latest temurin and IntelliJ builds
