### ISSUE TITLE
Unable to install with OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi

### ISSUE THREAD

**Issue by GusRichart** [adoptium/adoptium-support#356]
## Summary

The download for OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi is 75 bytes in size and appears to be incorrect.

## Steps to reproduce

1) Go to the https://adoptium.net/releases.html site
2) Select OpenJDK 11 (LTS) and Windows and x64
3) The JRE listed for MSI is reporting that it is 0 MB

## Expected results

Working OpenJDK 11 (LTS) Windows x64 MSI version that is greater than 75 bytes.

## Actual results

Not able to install and you receive the following error:
![image](https://user-images.githubusercontent.com/69476438/132045077-89dd95d4-0ee0-4a20-8a19-76a8dbb979d5.png)

## Triaging info

Java version: N/A as we are not able to install via OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi

What is your operating system and platform? Windows 10 2004 on x86-64

How did you install Java? N/A as we are not able install using this MSI

Did it work before? N/A

Did you test with other Java versions? N/A

**Comment by karianna** [comment]
#353 duplicate
