### ISSUE TITLE
IcedTea-Web is not bundled in 1.8.0_302 OpenJDK8 Windows 64 bit JRE installer (OpenJDK8U-jre_x64_windows_hotspot_8u302b08.msi)

### ISSUE THREAD

**Issue by SattibabuKandi** [adoptium/adoptium-support#359]
## Question

IcedTea-Web is not bundled with OpenJDK8 Windows 64 bit JRE installer (OpenJDK8U-jre_x64_windows_hotspot_8u302b08.msi), where as it has been shipped with windows 64 JRE installers until 8u292.

Also in the Adopt OpenJDK Migration Guide it is mentioned that IcedTea-Web is available as an optional component of the AdoptOpenJDK installer for 64-bit Windows on OpenJDK 8 that you can select from the Custom Setup panel. 

Could you please confirm if IcedTea-Web will be bundled with OpenJDK JRE8 and it is missed in 1.8.0_302 or it has been stopped from version 8u302-b08.

Java version: 1.8.0_302

openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

Your operating system and platform:
Windows 2008/2012 on x64

**Comment by karianna** [comment]
Correct, we no longer bundle ITW at Adoptium.  You'll need to add this yourself.  see https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/
