### ISSUE TITLE
KeyGenerator.getInstance(keyAlg) does not recognize any of the Key Algorithms listed from Providers

### ISSUE THREAD

**Issue by brunogenovese** [adoptium/adoptium-support#360]
Using version 16.

## Summary
I attempted to call KeyGenerator.getInstance(keyAlg) with several key algorithms listed from Security.getProviders().  All of them return "java.security.NoSuchAlgorithmException: NONEwithRSA KeyGenerator not available" or the equivalent.

## Steps to reproduce
(1) List the providers with:
`    TreeSet<String> algorithms = new TreeSet<String>();
    for(Provider provider : Security.getProviders()) {
      for(Service service : provider.getServices()) {
        if(service.getType().equals("Signature")) {
          algorithms.add(service.getAlgorithm());
        }
      }
    }
    List<String> algs = new ArrayList<String>();
    algs.addAll(algorithms);
    return algs;
`
(2) It returns many algorithm names, including for example "NONEwithRSA".

(3) Call KeyGenerator.getInstance(keyAlg);  

(4) Exception is thrown, regardless of keyAlg algorithm name chosen.

NOTE:  I would have much preferred using EAS encryption but I am aware that it is no longer included in Java and would have to use a 3rd party API.  So I stuck with RSA for now.

## Expected results
Run with no exception.

## Actual results
Exception "java.security.NoSuchAlgorithmException: NONEwithRSA KeyGenerator not available".

## Triaging info

Java version:  
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)

What is your operating system and platform?
Windows 10 2021 on x86-64

How did you install Java?
zip

Did it work before?
Java works fine, it is only  KeyGenerator.getInstance(keyAlg) that seems broken.

Did you test with other Java versions?
Not in years, possibly since before Oracle created the Java mess by taking it over from Sun.

**Comment by jerboaa** [comment]
> OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
> OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)

This is a corretto build, not a Temurin binary (Adoptium). Can you reproduce with a Temurin build?
https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot

If not, please bring this to the corretto folks. Probably here:
https://github.com/corretto/corretto-8/issues

**Comment by gdams** [comment]
Closing here as the issue has been reported at Corretto
