### ISSUE TITLE
Temurin jdk8u302-b08 Windows x86 JRE msi is 75 bytes

### ISSUE THREAD

**Issue by ejohnson2cnbanktexas** [adoptium/adoptium-support#361]
## Summary
The msi for Temurin x86 JRE msi installer is 75 bytes.

## Steps to reproduce

Go to the release page, https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot
Navigate to the Windows x86 section, and the JRE msi is listed as 0MB, and the checksum matches the 75 byte file.

![site](https://user-images.githubusercontent.com/90700982/133266564-839d7739-143c-4f0e-9b3b-97cbb1b55f3a.png)
![hash](https://user-images.githubusercontent.com/90700982/133266561-668f0722-efd6-4303-b356-f37261343644.png)

## Triage
Please upload the proper size msi file. Thank you!

**Comment by karianna** [comment]
Respinning here https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/15641/

**Comment by karianna** [comment]
Fixed, API should pick this up in the next few hours
