### ISSUE TITLE
11.0.12+7: SIGSEGV in com.sun.java.swing.plaf.gtk.GTKStyle.nativeGetXThickness

### ISSUE THREAD

**Issue by mduft** [adoptium/adoptium-support#362]
## Summary

When updating to 11.0.12+7 binaries there is a SIGSEGV when trying to open any swing based UI on Fedora 34/GNOME (at least, potentially other environments as well).

The problem does *not* occur with 11.0.11+9

## Steps to reproduce

1. Download e.g. https://github.com/bdeployteam/bdeploy/releases/download/v3.6.6/bdeploy-linux64-3.6.6.zip
2. Unzip, locate `launcher/launcher-linux64-3.6.6.zip` inside the release ZIP, unzip to a temp folder.
3. Run `bin/launcher` - which should open up a window but crashes as the embedded/bundled JRE is 11.0.12+7. Produces something like this: [hs_err_pid189803.log](https://github.com/adoptium/adoptium-support/files/7166996/hs_err_pid189803.log)
4. Replace `jre` folder with a 11.0.11+9 JRE download and try again - now it works.

## Expected results

The launcher should open up a window. This should be testable with about any swing application on linux.

## Actual results

Crash, see attached log.

## Triaging info

Java version: 11.0.12+7

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

What is your operating system and platform?

Linux fril0667.wamas.com 5.13.14-200.fc34.x86_64 #1 SMP Fri Sep 3 15:33:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Fedora release 34 (Thirty Four)

How did you install Java?

Java is embedded in the launcher, although I tried with the full download tar.gz as well.

Did it work before?

Yes, with 11.0.11+9, never with 11.0.12+7

Did you test with other Java versions?

Tested with 11.0.12+7 embedded (jlink'ed) in the launcher download, 11.0.12+7 fresh .tar.gz download - both don't work.
Also tested with 11.0.11+9 - works - and OpenJDK RI binaries 11+28 - works as well!

**Comment by jerboaa** [comment]
I'm surprised this works with 11.0.11+9. Either way, this seems fixed with 11.0.13+5 EA build from:
https://adoptopenjdk.net/upstream.html?variant=openjdk11&ga=ea

This yields me to believe it's a duplicate of this upstream bug (fixed in 11.0.13+4 and better):
https://bugs.openjdk.java.net/browse/JDK-8255790

**Comment by mduft** [comment]
Retested and can confirm that it works with 11.0.13+5 EA. Thanks for the hint. Will wait for a release then :)
