### ISSUE TITLE
adoptopenjdk-8-hotspot-armhf fails to run

### ISSUE THREAD

**Issue by theofficialgman** [adoptium/adoptium-support#368]
```
/usr/lib/jvm/adoptopenjdk-8-hotspot-armhf/bin/java -version

#

# A fatal error has been detected by the Java Runtime Environment:

#

#  SIGBUS (0x7) at pc=0xec50e080, pid=1759, tid=0xec32f460

#

# JRE version:  (8.0_282-b08) (build )

# Java VM: OpenJDK Client VM (25.282-b08 mixed mode linux-aarch32 )

# Problematic frame:

# V  [libjvm.so+0x16f080]  ClassFileParser::parse_constant_pool_entries(int, Thread*)+0x47c

#

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /home/garrett/hs_err_pid1759.log

#

# If you would like to submit a bug report, please visit:

#   https://github.com/AdoptOpenJDK/openjdk-support/issues

#

Aborted (core dumped)

```

## Summary

running the adoptopenjdk 8 hotspot build for armhf from the debian repo  https://adoptopenjdk.jfrog.io/adoptopenjdk/deb fails to even run the version check

## Steps to reproduce

sudo apt install adoptopenjdk-8-hotspot-jre
/usr/lib/jvm/adoptopenjdk-8-hotspot-armhf/bin/java -version

## Expected results

prints out the java version

## Actual results

fatal error occurs

### What is your operating system and platform?

debian bullseye armhf with arm64 kernel
### How did you install Java?

installed from the deb repo https://adoptopenjdk.jfrog.io/adoptopenjdk/deb (both adoptopenjdk-8-hotspot-armhf and adoptopenjdk-8-hotspot-jre-armhf do not work)

### Did you test with other Java versions?

java 11 from openjdk works as expected
```
openjdk version "11.0.11" 2021-04-20

OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

OpenJDK Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

```

### If available, test with an upstream build:

no upstream builds available at the repos for armhf

[log_adoptopenjdk-8-hotspot.txt](https://github.com/adoptium/adoptium-support/files/7220810/log_adoptopenjdk-8-hotspot.txt)

**Comment by theofficialgman** [comment]
as a point of reference.. the debian stretch security and security updates version of openjdk work fine

8u252-b09-1~deb9u1
8u302-b08-1~deb9u1

**Comment by gdams** [comment]
@tellison could you try with the temurin build for arm32? https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot

**Comment by theofficialgman** [comment]
@gdams a simple java -version test of the latest temurin build seems to work fine
```
openjdk version "1.8.0_302"

OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)

OpenJDK Client VM (Temurin)(build 25.302-b08, mixed mode)
```


also for reference this was exact deb file version that I was testing before (which is the latest available at the deb repo for armhf https://adoptopenjdk.jfrog.io/ui/native/deb/pool/main/a/adoptopenjdk-8-hotspot)
```
Package: adoptopenjdk-8-hotspot

Version: 8u282-b08-3

License: GPL-2.0+CE

Vendor: AdoptOpenJDK

Architecture: armhf

```

**Comment by gdams** [comment]
> @gdams a simple java -version test of the latest temurin build seems to work fine

I'd recommend using that binary going forwards if that works for you? We also plan to provide the temurin binary in deb/rpm form soon so you'll be able to `apt install temurin-8`. We also provide docker images for all platforms (including armhf) if that works for you?

I'm going to close this issue based on the fact that the latest version of 8 does indeed run

**Comment by theofficialgman** [comment]
@gdams 
> We also plan to provide the temurin binary in deb/rpm form soon so you'll be able to `apt install temurin-8`.

this would be nice but is it possible that the debian repo under the original adoptopenjdk-8-* could also be updated?

at minimum for armhf since the current version in the repo seems to not work for some (maybe most) system, even if its going to be abandoned for a new temurin-8 naming?

**Comment by theofficialgman** [comment]
@gdams Sorry to be a bother, any update on the creation of a debian apt repo or rpm repo?
