### ISSUE TITLE
where are the JRE variants for Java 17?

### ISSUE THREAD

**Issue by jcompagner** [adoptium/adoptium-support#372]
We ship a jre inside our product (which is eclipse based) so we only need the JRE, not a JDK where do we now get those from?

if i now go to

https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot

i only see JDK no JRE anymore

**Comment by karianna** [comment]
We are no longer building JREs for Java 16+ (the concept doesn't exist upstream either).

https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/
