### ISSUE TITLE
Java won't run on Mac 10.10

### ISSUE THREAD

**Issue by SirIntellegence** [adoptium/adoptium-support#373]
## Summary
The current built version (as of 9/28/2021) does not run on Mac 10.10 as specified. All of the executables print some sort of library error instead of their usual output. I suspect XCode changing defaults while building.

## Steps to reproduce
Install the latest copy on Mac 10.10
cd to the "Home/bin" directory
Run `find . -exec {} \;` to run each executable in the directory

## Expected results
The standard no-args output of each program

## Actual results
The following is printed out for each {executable name}

> dyld: Library not loaded: @rpath/libjli.dylib
>   Referenced from: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./{executable name}
>   Reason: no suitable image found.  Did find:
> 	/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/libjli.dylib: code signature invalid for '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/libjli.dylib'

## Triaging info

Java version:
17+35
For reference, the output of `java -version` is not useful.

> $ ./java --version 
> dyld: Library not loaded: @rpath/libjli.dylib
>   Referenced from: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/./java
>   Reason: no suitable image found.  Did find:
> 	/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/libjli.dylib: code signature invalid for '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/../lib/libjli.dylib'
> 
> [1]    92760 trace trap  ./java --version

What is your operating system and platform?
![Screen Shot 2021-09-28 at 9 31 16 AM](https://user-images.githubusercontent.com/3401182/135118517-dbe7de22-1e74-4146-931e-e3f101e61f4c.png)

How did you install Java?
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17%2B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.pkg

Did it work before?
Java 16 works, but that isn't a recent install

Did you test with other Java versions?
https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.tar.gz

> openjdk 16.0.2 2021-07-20
> OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
> OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

For reference, https://github.com/adoptium/temurin17-binaries/releases/download/jdk17-2021-09-22-02-48-beta/OpenJDK17-jdk_x64_mac_hotspot_2021-09-22-02-48.tar.gz has this issue too.

**Comment by SirIntellegence** [comment]
Edit: removed some sarcasm.

**Comment by karianna** [comment]
We no longer support 10.10 for Java 17 as it's not a supported O/S by Apple itself (Nov 2020 was the end date).
