### ISSUE TITLE
JDK 8 Windows 7 x86 support

### ISSUE THREAD

**Issue by tm250486** [adoptium/adoptium-support#380]
Hello,

I would like to know if the AdoptOpenJDK 8 hotspot x86 version supports Window 7?

On the page support platform there is no mention of x86 version in Windows section: [Support platforms - Adoptium page](https://adoptium.net/supported_platforms.html?variant=openjdk8)

While the old Adopt page it does mention the support of Window 7: [Supported platforms - AdoptOpenJDK page](https://adoptopenjdk.net/supported_platforms.html)

On the download page, it indicates only support Window 2012r2 or later.

Best regards

**Comment by karianna** [comment]
Probably 1.8.0_292 - you'll have to try it out and see though.
