### ISSUE TITLE
Createcoredumoncrash turned off

### ISSUE THREAD

**Issue by plsstahppls** [adoptium/adoptium-support#381]
im on adoptopenjdk 16 hotspot

## Summary
I was playing project zomboid b41.55 i was running its batchfile everytime i make a new character and start it after a few moments it would just crash and say "createcoredump on crash turned off"
i dunno whats exactly the problem 

## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

<!-- yes tried java 15

**Comment by karianna** [comment]
You'll likely need to reach out to them and ask what their support Java version is...

**Comment by karianna** [comment]
Closing as this a 3rd party compatibility issue
