### ISSUE TITLE
What does the word `Temurin` means?

### ISSUE THREAD

**Issue by SekiBetu** [adoptium/adoptium-support#383]
## Question

I'm not a native English speaker, so I'm curious about what the word `Temurin` means? 

## Context

Java version: not needed

Your operating system and platform: not needed

**Comment by stefan-reich** [comment]
Ahaha. I was expecting it to be a native american word with age long history. Or some such.

**Comment by smlambert** [comment]
https://twitter.com/adoptium/status/1435519863091564547

**Comment by stefan-reich** [comment]
Oh. So temurin is a caffeine analog - basically a coffee-like designer drug? That's right up my alley. Has someone ingested this? Can't find any info. Hehe.

Anyway, it's a really nice name you chose. 👍

**Comment by FyiurAmron** [comment]
https://en.wikipedia.org/wiki/Theacrine
>Other names
1,3,7,9-Tetramethyluric acid; **Temurin** (...)

Seems it fits the ☕ -themed naming scheme common to Java ecosystem nicely.

**Comment by RedactedProfile** [comment]
I mean, I was over here thinking it was a spice or something lol
