### ISSUE TITLE
AIX ppc64 JRE hotspot

### ISSUE THREAD

**Issue by mirkowein** [adoptium/adoptium-support#389]
Hi,

i'm searching for the newest **JRE** version for AIX ppc64 hotspot

JDK is 11.0.**13+8**
JRE is 11.0.**12+7**

Will be there a newer JRE version soon?

Best regards!

**Comment by karianna** [comment]
They're still being worked, hopefully this week!

**Comment by mirkowein** [comment]
That would be great. Many thanks for your work!
