### ISSUE TITLE
Maven windows 32bit

### ISSUE THREAD

**Issue by XakepSDK** [adoptium/adoptium-support#396]
## Summary
We have 100% modular multi-module project
Maven fails to build multi-module project on Windows 10 amd64 with Temurin 17 x86
We need x86 jlink builds.

I tried:
- Fail: Windows 7 x86 + Bellsoft Java 17 x86
- Fail: Windows 7 x86 + Temurin 17 x86
- Fail: Windows 10 amd64 + Bellsoft Java 17 x86
- Fail: Windows 10 amd64 + Temurin Java 17 x86
- Success: Windows 10 amd64 + Bellsoft Java 17 amd64
- Success: Windows 10 amd64 + Temurin Java 17 amd64

## Steps to reproduce
Maybe try to compile multi-module project with tests. I can share project privately.

## Expected results
Build works

## Actual results
Randomly any of those issues happens:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project auth-openid:
The parameters 'testSourceDirectory' for goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test are missing or invalid -> [Help 1]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project user-info-impl:
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed: Unable to locate surefire-booter in the list of plugin artifacts -> [Help 1]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:testResources (default-testResources) on project account-info-impl:
The parameters 'outputDirectory' for goal org.apache.maven.plugins:maven-resources-plugin:2.6:testResources are missing or invalid -> [Help 1]
```

## Triaging info

Java version:
I don't have access to the build server right now, but it was this version:
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x86-32_windows_hotspot_17.0.1_12.msi

What is your operating system and platform?
Windows 10 64bit

How did you install Java?
In power shell:
`Start-Process -Wait -FilePath "msiexec.exe" -ArgumentList "/i c:\java.msi INSTALLLEVEL=3 /quiet`
Also tried to install manually with GUI.

Did it work before?
I don't know

Did you test with other Java versions?
Bellsoft Java 17 x86, same issue

Does not happen on Windows

**Comment by jerboaa** [comment]
https://github.com/adoptium/adoptium-support/issues/385 might be related.

**Comment by karianna** [comment]
@XakepSDK can you try with our latest 17.0.3 and see if it's resolved?

**Comment by XakepSDK** [comment]
Sorry, I don't work on this project anymore, I can't test
