### ISSUE TITLE
While loading gmail in JavaFX WebView the application crashed itself.

### ISSUE THREAD

**Issue by nischalshakya95** [adoptium/adoptium-support#400]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_STACK_OVERFLOW (0xc00000fd) at pc=0x5441eaa9, pid=11560, tid=7104
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
# Java VM: OpenJDK Client VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, emulated-client, serial gc, windows-x86)
# Problematic frame:
# C  [jfxwebkit.dll+0x12deaa9]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant org.personal.javafxwebview.Launcher

Host: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 12 cores, 15G,  Windows 10 , 64 bit Build 22000 (10.0.22000.318)
Time: Tue Nov 16 11:47:59 2021 Nepal Standard Time elapsed time: 45.344023 seconds (0d 0h 0m 45s)

---------------  T H R E A D  ---------------

Current thread (0x15b9b560):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=7104, stack(0x15f80000,0x15fd0000)]

Stack: [0x15f80000,0x15fd0000],  sp=0x15f81028,  free space=4k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

**Comment by karianna** [comment]
You'll want to report this at OpenJFX, the crash is in their DLL so to speak.

**Comment by karianna** [comment]
There is an upstream issue being worked on for this.
