### ISSUE TITLE
Non-Official Docker images Git Repo

### ISSUE THREAD

**Issue by softwarebrahma** [adoptium/adoptium-support#402]
Hello Team,

I noticed that the official Docker images started providing alpine builds for Java 11 starting with 11.0.13. However i see that the same image version from the non-official repo has a different size as compared to the official version. Also the official one does not have the trimmed down alpine-slim version that the non-official does. Basically I am trying to understand what the difference is between these two repos & the plan in mind for the same.

I searched & couldn't get much insight on this. If i have missed something i apologize & kindly please point me to the same.

Thanks
Muthu

**Comment by karianna** [comment]
THe official one is scanned and blessed by Docker Inc.  The unofficial ones are the ones that we've tested and deploy locally but have not (yet) submitted to DockerHub

**Comment by softwarebrahma** [comment]
Cool, thanks @karianna ! Is there a plan to start submitting the alpine-slim versions aswell at some point or can we continue to rely on & use the unofficial ones from the unofficial repo?
Thanks
Muthu

**Comment by karianna** [comment]
Question for @gdams on Monday - IIRC it depends a little on what DockerHub allows (they prefer not to have a massive proleferation)

**Comment by gdams** [comment]
The unofficial images are from the old AdoptOpenJDK binaries and are no longer supported. It is recommended that you migrate to the official images. If you are looking for a slim version then you could consider using multi stage Dockerfiles to strip out unnecessary files

**Comment by softwarebrahma** [comment]
> Question for @gdams on Monday - IIRC it depends a little on what DockerHub allows (they prefer not to have a massive proleferation)

Thank you @karianna

**Comment by softwarebrahma** [comment]
> 

Thanks @gdams

**Comment by softwarebrahma** [comment]
> The unofficial images are from the old AdoptOpenJDK binaries and are no longer supported. It is recommended that you migrate to the official images. If you are looking for a slim version then you could consider using multi stage Dockerfiles to strip out unnecessary files

**Comment by softwarebrahma** [comment]
> The unofficial images are from the old AdoptOpenJDK binaries and are no longer supported. It is recommended that you migrate to the official images. If you are looking for a slim version then you could consider using multi stage Dockerfiles to strip out unnecessary files

Thanks @gdams
