### ISSUE TITLE
Robot class issue

### ISSUE THREAD

**Issue by heidis123** [adoptium/adoptium-support#403]
Yes

## Summary

When running Robot class program the program will show no errors but will not compete either the mouseMove or KeyPress methods

## Steps to reproduce

import java.awt.AWTException;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Random;

public class MouseMover {

    public static final int FIVE_SECONDS = 5000;
   // public static final int THREE_SECONDS = 3000;

    public static final int MAX_Y = 400;

    public static final int MAX_X = 400;
    

    public static void main(String[] args) throws IOException, AWTException,InterruptedException   
    {

//        Robot robot1 = new Robot();

        Random random1 = new Random();
        
        GraphicsDevice gd =
                GraphicsEnvironment.getLocalGraphicsEnvironment().
                    getDefaultScreenDevice();
        Robot robot1 = new Robot(gd);
        
       // robot1.keyPress(KeyEvent.VK_W);

        while (true) {
        	//Thread.sleep(THREE_SECONDS);
        	//System.out.println("Test");
        	robot1.keyPress(KeyEvent.VK_W);
        		
        	robot1.keyRelease(KeyEvent.VK_W);
        	//robot1.keyPress(KEvent.VK_KP_UP); 

            robot1.mouseMove(random1.nextInt(MAX_X), random1.nextInt(MAX_Y));

            //Thread.sleep(FIVE_SECONDS);
            robot1.delay(1000);
            
            
        }
    
    }
    
}
    
   Here is one of the codes that I tried. I'm also running on an older version of the Java JDK because the newer versions did not include/did not support the Robot class 

## Expected results

keyPressW and MouseMove a random amount every second

## Actual results

No movement or key press and no error messages

## Triaging info

Java version:

Java Version : 11.0.12 

What is your operating system and platform?

Java Version : 11.0.12
Mac OS X 11.2

How did you install Java?
From Oracle archives (tar.gz)

Did it work before?

yes, yesterday this code worked

mosemover and keypress no longer working
Did you test with other Java versions?
yes

**Comment by heidis123** [comment]
Also, in terms of system permissions both Terminal and Eclipse have been given permissions to full disk access, screen recording, accessibility, and input monitoring

**Comment by karianna** [comment]
Which Java are you using?  Adoptium?  Can you please try the latest 11.0.13?

**Comment by karianna** [comment]
There were some mouse pointer fixes in 11.0.15 - should be resolved.
