### ISSUE TITLE
Temurin-17.0.1+12 SIGBUS crash

### ISSUE THREAD

**Issue by claudionieder** [adoptium/adoptium-support#404]
## Summary

Fatal error SIGBUS

## Steps to reproduce

Sorry, this happens with a large program that contains personal data. But I am willing to produce something small that can reproduce the error, if you can help me to pinpoint to a Class/Library that causes the issue.
 
## Expected results

No crash

## Actual results

A fatal error has been detected by the Java Runtime Environment:

 SIGBUS (0xa) at pc=0x000000010ec314f0, pid=62260, tid=34831

JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
Problematic frame:
v  ~StubRoutines::SafeFetchN

No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
/Users/claudio/IdeaProjects/Claudio/hs_err_pid62260.log

If you would like to submit a bug report, please visit:
  https://github.com/adoptium/adoptium-support/issues
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

## Triaging info

Java version:

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode)

What is your operating system and platform?

Darwin M 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

How did you install Java?

tar xvf OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.1_12.tar.gz

Did it work before?

It works on my old Mac with Intel Processor. The crash started on the new Mac with Apple Silicon.

Did you test with other Java versions?

No.

N
[hs_err_pid62260.log](https://github.com/adoptium/adoptium-support/files/7574442/hs_err_pid62260.log)
[macosReport.txt](https://github.com/adoptium/adoptium-support/files/7574443/macosReport.txt)
o

**Comment by karianna** [comment]
@claudionieder - Looks like you're running this program from IntelliJ IDEA is that correct?  Can you try running the programe stand alone?

**Comment by claudionieder** [comment]
I wanted to do today, but upon rerunning it in IntelliJ first to my surprise the error had disappeared. I now assume, that it might be therefore some external library - I update my dependencies regularly - and not temurin itself causing the crash. Unfortunately I am not good at interpreting crash reports, otherwise maybe I could have known before. Anyway, thanks for your support, and I'll close this issue now.
