### ISSUE TITLE
Windows arm64 support

### ISSUE THREAD

**Issue by Alovchin91** [adoptium/adoptium-support#409]
## Question

Do you plan to release Windows arm64 builds of Temurin JDK?

We're currently planning a Windows arm64 release of our products and are considering switching to Microsoft OpenJDK because they support it natively. But we hope you have some plans to release Windows arm64 builds?

## Context

Java version:

11 or 17

Your operating system and platform:

Windows 11 21H2 on arm64

**Comment by karianna** [comment]
We do but are waiting for more Windows ARM SKUs to become publicly available.

**Comment by Alovchin91** [comment]
@karianna  What do you mean by Windows ARM SKUs?

**Comment by karianna** [comment]
Currently most Windows ARM devices are Surface Pro X client machines.  Once it proliferates a bit more beyond that it's easier to add to the build farm (can't rack mount a surface pro X) 🙂

**Comment by Alovchin91** [comment]
@karianna I see 🙂

Would "Snapdragon Developer Kit" suffice? https://www.microsoft.com/en-us/d/ecs-liva-mini-box-qc710-desktop/8z247h1h3skp

**Comment by karianna** [comment]
Maybe, we'll look into it :-)

**Comment by Alovchin91** [comment]
Do you have an idea of how long that would take? I presume we shouldn't expect it by January-February, so I guess we'll have to do the switch anyway?

**Comment by karianna** [comment]
Not sure on timelines sorry, it'll be early next year before we can look properly again though.
