### ISSUE TITLE
Problem running MultiMC 5 (on raspberry pi.) 

### ISSUE THREAD

**Issue by Skot3y** [adoptium/adoptium-support#412]
**[Begginer]**
Hello i have problem with runing minecraft and it shows this error message

[hs_err_pid21697.log](https://github.com/adoptium/adoptium-support/files/7644864/hs_err_pid21697.log)

**Comment by bLUeScrEeN1512** [comment]
I have the same error code on my raspberry pi 4, hopefully me or someone else figures out a fix soon...

**Comment by karianna** [comment]
@Skot3y or @bLUeScrEeN1512 - Can you send us exactly which version of Java you're running via `java --version`?

**Comment by XiaoBao13** [comment]
I have the same problem, I'm using Java 8, and if it effects anything I'm using TwisterOS. I enabled core dumps which gt me here. I'll put my log if that helps too
[hs_err_pid3134.log](https://github.com/adoptium/adoptium-support/files/8091638/hs_err_pid3134.log)
.
Also to the original post you have to 
1. go to /etc/security/limits.conf
2. Add this on the seventh line uncommented: * soft core unlimited 
Like this screenshot 
![image](https://user-images.githubusercontent.com/72358191/154557425-261554b0-1a64-4827-90c3-06b9cc937943.png)
Then you'll be where I am, still erroring but passed that screen.
Hope this helps ya'll!

**Comment by XiaoBao13** [comment]
> I have the same problem, I'm using Java 8, and if it effects anything I'm using TwisterOS. I enabled core dumps which gt me here. I'll put my log if that helps too [hs_err_pid3134.log](https://github.com/adoptium/adoptium-support/files/8091638/hs_err_pid3134.log) . Also to the original post you have to
> 
> 1. go to /etc/security/limits.conf
> 2. Add this on the seventh line uncommented: * soft core unlimited
>    Like this screenshot
>    ![image](https://user-images.githubusercontent.com/72358191/154557425-261554b0-1a64-4827-90c3-06b9cc937943.png)
>    Then you'll be where I am, still erroring but passed that screen.
>    Hope this helps ya'll!

And if you want to double check it works just do: ulimit -c
I have rebooted before I do ulimit -c though, I don't think it works if you don't reboot

**Comment by karianna** [comment]
Minecraft ships with OpenJDK 17.0.1 (from Microsoft) as the supported version.
