### ISSUE TITLE
 A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by meensaj** [adoptium/adoptium-support#413]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff3c72d1f0, pid=8796, tid=10812
#
# JRE version: OpenJDK Runtime Environment Temurin-17+35 (17.0+35) (build 17+35)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17+35 (17+35, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007fff3c72d1f0
[error occurred during error reporting (printing problematic frame), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff3c72db60]

# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Java\CoreJavaPro1\hs_err_pid8796.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by karianna** [comment]
Please try with the latest 17.0.1 and report back here if it's still an issues

**Comment by Jhoops03** [comment]
Still having the issue: Crashed again today - 12/20/21 at 4:37 PM

**Comment by meensaj** [comment]
yes ....issues is there. i am trying all the ways

**Comment by Jhoops03** [comment]
I downloaded JDK 11.13 I think so hopefully that fixes it

**Comment by meensaj** [comment]
can u plz share jdk 11.13 download link

**Comment by karianna** [comment]
https://www.adoptium.net contains links for the latest 17.0.1 and 11.0.13

**Comment by meensaj** [comment]
Got it, thanks!

**Comment by Jhoops03** [comment]
I have latest JDK downloaded and issue still persists.

**Comment by meensaj** [comment]
Same issue with my system

**Comment by Jhoops03** [comment]
I'm trying everything under the sun to fix it but nothing seems to be working :c
Idk what to do lol, my HC will not survive this

**Comment by karianna** [comment]
@Jhoops03 and @meensaj - What program are you trying to run?

**Comment by meensaj** [comment]
AWT and Swing programs

**Comment by karianna** [comment]
@meensaj What's the exact version of Windows you're running?

**Comment by karianna** [comment]
@meensaj  and @Jhoops03 - 17.0.3 and 11.0.15 had some fixes in this area.  Please try those versions and reopen this if the error still persists.
