### ISSUE TITLE
Migrating from Adopt JDK 8 to Adopt JDK 11

### ISSUE THREAD

**Issue by gauravmane** [adoptium/adoptium-support#415]
## Question
Hello All,

We are migrating from Adopt JDK 8 to 11, and use Ant build to prepare the build for our deployments. Our code has references to Reflect API which came OOTB along with the packages. As I understand the reflect API is no longer supported in Adopt JDK 11 which causes the build to fail with the below error : 

We get a ClassDefinitionNotFound for **jdk/internal/reflect/ConstructorAccessorImpl** class.

Any help is appreciated. 

We have already tried with adding the --add-opens flag in Ant build under the <java> tag

<arg value="--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/java.lang.reflect=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/java.security=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/sun.reflect=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/sun.reflect.annotation=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/java.lang=ALL-UNNAMED"/>
<arg value="--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED"/>
<arg value="--add-exports=java.base/sun.nio.ch=ALL-UNNAMED"/>

Java version: JDK 8 to JDK 11

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

Kindly suggest if we are missing out on anything.

**Comment by karianna** [comment]
Please do use the latest 11.0.13

https://nipafx.dev/five-command-line-options-hack-java-module-system/ is a useful guide on the various options to access internal methods.
