### ISSUE TITLE
Unrecognized option: -XshowSettings:vm when using JNI_CreateJavaVM

### ISSUE THREAD

**Issue by charlesk40** [adoptium/adoptium-support#416]
## Question

I'm able to use -XshowSettings with java command line but when trying to use with JNI_CreateJavaVM, it throws `Unrecognized option: -XshowSettings:vm
`
I'm not sure if this is expected behavior or there is an open issue about this.

# Use -XshowSettings:vm on the command line: no issue
```
java -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 1.89G
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```

# Use -XshowSettings:vm with JNI_CreateJavaVM: failed

```
Unrecognized option: -XshowSettings:vm
E 08-232213.932500 29670 08/12/2021 23:22:13: [java.c:300] Cannot create Java VM
```

## Context

Java version:

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

```
Your operating system and platform:

`Red Hat Enterprise Linux Server release 7.9 (Maipo)
`

**Comment by karianna** [comment]
We'd need to see how you've written your native code (https://docs.oracle.com/en/java/javase/11/docs/specs/jni/invocation.html)

**Comment by charlesk40** [comment]
Below is a sample code that was taken from the API doc and ran:

[charlesk@forgaveslave java_invoke]$ export LD_LIBRARY_PATH=set_to_lib_directory; ./java_invoke_test
Unrecognized option: -XshowSettings:vm
Creating JVM….Segmentation fault (core dumped)

```
#include<iostream>  
#include <jni.h>       /* where everything is defined */
 
using namespace std;
 
int main()
{
	cout<<"Creating JVM….";
 	 JavaVM *jvm;       /* denotes a Java VM */
JNIEnv *env;       /* pointer to native method interface */
JavaVMInitArgs vm_args; /* JDK/JRE 11 VM initialization arguments */
JavaVMOption* options = new JavaVMOption[2];
options[0].optionString = "-Djava.class.path=/usr/lib/java";
options[1].optionString = "-XshowSettings:vm";

vm_args.version = JNI_VERSION_10;
vm_args.nOptions = 2;
vm_args.options = options;

//false returns JNI_ERR as soon as it encounters any unrecognized option strings
vm_args.ignoreUnrecognized = false;
/* load and initialize a Java VM, return a JNI interface
 * pointer in env */
JNI_CreateJavaVM(&jvm, (void**)&env, &vm_args);
	cout<<"Invoked JNI_CreateJavaVM.";

           delete options;

/* invoke the Main.test method using the JNI */
//jclass cls = env->FindClass("Main");
//jmethodID mid = env->GetStaticMethodID(cls, "test", "(I)V");
//env->CallStaticVoidMethod(cls, mid, 100);
/* We are done. */
jvm->DestroyJavaVM();

}

```

If I were to remove the "-XshowSettings:vm" or set vm_args.ignoreUnrecognized = true, I don't get the error.

**Comment by jerboaa** [comment]
https://docs.oracle.com/en/java/javase/11/docs/specs/jni/invocation.html#jni_createjavavm mentions:

```
In addition, each VM implementation may support its own set of non-standard option strings. Non-standard option names must begin with “-X” or an underscore (“_”). For example, the JDK/JRE supports -Xms and -Xmx options to allow programmers specify the initial and maximum heap size. Options that begin with “-X” are accessible from the “java” command line.
```

You are trying to use an `-X` option only known by the `java` launcher. In fact, `-XshowSettings` options are handled by the `LauncherHelper` class which is invoked via JNI:
https://github.com/openjdk/jdk11u-dev/blob/master/src/java.base/share/native/libjli/java.c#L1894..L1909

You'd have to replicate this in your own launcher.
