### ISSUE TITLE
mid.exe

### ISSUE THREAD

**Issue by datgith** [adoptium/adoptium-support#418]
yes

## Summary

mid.exe is outdated

mid.exe in folder \jre\bin is outdated (14.01) even after deleting \bin and replacing \bin folder with newer folder.

## Steps to reproduce

mid.exe's properties details say that it's version is 14.01.

## Expected results

mid.exe should be 16,x or 17.x 

## Actual results

but it's actual version is 14.01

## Triaging info

Java version:

16.01

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?
![java bug](https://user-images.githubusercontent.com/39115349/145885737-7bb30a33-f0a1-4b55-b094-4033786ff5b5.jpg)

tested with openjdk java binary release and same thing.

**Comment by karianna** [comment]
@datgith should be fixed in 17.0.3
