### ISSUE TITLE
Error in documentation https://adoptium.net/support.html  wrong year for Next Releases

### ISSUE THREAD

**Issue by viretp** [adoptium/adoptium-support#420]
## Summary

In the release roadmap under https://adoptium.net/support.html the year for the next release is still 2021 but should be 2022.

## Steps to reproduce

got to https://adoptium.net/support.html

## Expected results

Next release date should not be in the past so 2021 is wrong and must be fixed to 2022

## Actual results

Next release date year is 2021

## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by karianna** [comment]
https://github.com/adoptium/adoptium.net/pull/252
