### ISSUE TITLE
-Takahashi Please help me understand why this won't work.

### ISSUE THREAD

**Issue by TakahashiEdenyako** [adoptium/adoptium-support#424]
I want to play BetaFixed intended for Beta 1.7.3 of Minecraft. Unfortunately, it won't load the game and it is a black screen. And there are times when I do get to play the game but there is no text and I load a new world where there is no block textures. Except heart and gui and skeleton's bows underground.

16 achievements
151 recipes
Setting user: TakahashiEden, token:<ACCESS TOKEN>:<PROFILE ID>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff976f02d77, pid=4292, tid=0x0000000000001dd0
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22d77]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:

# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process exited with code 1.

**Comment by karianna** [comment]
Minecraft now comes with its own Java 17.0.1+12 provides by Microsoft.  I'm not sure it's compatible with Java 8.
