### ISSUE TITLE
[Fedora] Desktop.open(File) hangs until the Java process is closed

### ISSUE THREAD

**Issue by JDESTM** [adoptium/adoptium-support#426]
## Summary

On Fedora 34 and Fedora 35 Desktop.open(File) does not open the default system application for the given file until the Java process is terminated.

## Steps to reproduce

Execute this snippet with a PDF file as argument (for instance):
```
public class Main {

	public static void main(String[] args) {
		try {
			System.out.println("Invoking system open");
			Desktop.getDesktop().open(new File(args[0]));
			System.out.println("Invoked system open, wait for 5s before exiting");
			try {
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			System.out.println("Exit");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}
```

On Fedora 33, the PDF viewer is launched immediately.
On Fedora 35, the PDF viewer starts after the 5s delay and the Java process ends.

## Expected results

The Desktop.open(File) shall have an immediate effect.

## Actual results

Fails with recent Fedora versions

## Triaging info

_Java version:_
```
openjdk version 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

_What is your operating system and platform?_
Fedora 35

_How did you install Java?_
Archive and Yum

_Did it work before?_
yes, until I updated from Fedora 33 to Fedora 35

_Did you test with other Java versions?_
```
openjdk version 11.0.13 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment 21.9 (build 17.0.1+12)
OpenJDK 64-Bit Server VM 21.9 (build 17.0.1+12, mixed mode, sharing)
```
Both installed with yum. Exact same behavior.

**Comment by JDESTM** [comment]
This issue is actually already reported in OpenJDK:
https://bugs.openjdk.java.net/browse/JDK-8275494

With references in GTK and Red-hat:
https://gitlab.gnome.org/GNOME/gtk/-/issues/4278
https://bugzilla.redhat.com/show_bug.cgi?id=1961119

**Comment by karianna** [comment]
Upstream bug still open

**Comment by karianna** [comment]
Upstream bug still open

**Comment by karianna** [comment]
As this is reported upstream I'm closing this issue
