### ISSUE TITLE
Java 11 define filepath separator

### ISSUE THREAD

**Issue by blaisemGH** [adoptium/adoptium-support#428]
Java AdoptOpen 11.0.13

I'm running the following java command in a Windows Server 2016 operating system:

`java -Xlog:gc*:file="C:\users\test_gc.log" -version`

This completes successfully.

However, I would like to be able to do:

`java -Xlog:gc*:file="C:/users/test_gc.log" -version`

This fails due to the forward slashes in a Windows system (I'm testing the command in PowerShell which allows forward slashes).

In java 8, forward slashes were acceptable, and furthermore the quotes weren't required due to its xloggc syntax.

Is there a way to customize java 11 to accept the forward slash as a default filepath separator as Java 8 was able to do?

The loss of a universal forward slash in my paths has been wreaking havoc with running software in Windows that has multiple embedded 3rd-party java components, as each embedded component parses the backslashes differently. Right now I have a combination of single backslashes, double backslashes, and even 4 backslashes as path separators for different java components (jboss, spark, hive).

**Comment by karianna** [comment]
@blaisemGH This isn't an Adoptium / Temurin issue per se so you'll want to report this upstream at OpenJDK (http://bugreport.java.com/)

https://stackoverflow.com/questions/783984/change-path-separator-in-windows-powershell may help as a workaround?
