### ISSUE TITLE
Segmentation fault with arm32 build for Linux

### ISSUE THREAD

**Issue by Slackadays** [adoptium/adoptium-support#432]
## Summary

After installing Adoptium 17 for Linux arm32 on a Raspberry Pi 1, I can't use the `java` command after adding it to $PATH because it yields a segmentation fault. Manually going into the install folder -> /bin and running `./java`, the segmentation fault is still there. `java -version` is no different.

## Steps to reproduce

1. `wget link-to-adoptium-linux-arm32.tar.gz`
2. `tar -xvf adoptium-linux-arm32.tar.gz`
3. `export PATH=$PWD/jdk-17.0.1+12-jre/bin:$PATH`
4. `java` or `java -version`

## Expected results

`java` would return the standard complaint about no file to execute. `java -version` would return the info normally returned.

## Actual results

`Segmentation fault`

## Triaging info

Java version:

I downloaded Adoptium 17 but can't run `java -version` because of the segmentation fault.

What is your operating system and platform?

Raspberry Pi OS on a Raspberry Pi 1B+, set to the Bookworm release from the Debian upstream.

How did you install Java?

I used the steps in the Steps To Reproduce section.

Did it work before?

Java has never worked before because it wasn't installed.

Did you test with other Java versions?

I haven't tested with other Java versions.

**Comment by karianna** [comment]
we're about to release 17.0.2 next week, if you can try with that version when it lands that would be appreciated!

**Comment by karianna** [comment]
@Slackadays try the latest 17.0.3 and reopen if still an issue.
