### ISSUE TITLE
Running java application crashes when third party app call getAccessibleContextInfo (java accessbirdge api) on object return using getAccessibleSelectionFromContext

### ISSUE THREAD

**Issue by ankitraval** [adoptium/adoptium-support#435]
## Summary
Running java application crashes when third party app call getAccessibleContextInfo - java accessbirdge api on object return using getAccessibleSelectionFromContext

## Steps to reproduce

1. Create a java application that contains ListView control and run with OpenJDK
2. Use/Create a third party app using JAVA Accessbridge. 
3. From a third party app traverse the whole tree of our running app using Java Accessbridge APIs till listview control.
4. Call getAccessibleSelectionFromContext on that listview control which gives virtualMachineId and accessibleContext values.
5. Using returned virtualMachineId and accessibleContext call getAccessibleContextInfo api and running java application crashes

## Expected results
- The Java application running using OpenJDK should not get crashed

## Actual results
- Java application crashes when any third party app execute JavaAccessBridge apis.

## Triaging info

Java version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)

What is your operating system and platform?
OS - Windows 10 - Pro
Processor - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz 
RAM - 16.0 GB RAM 

How did you install Java?
installer package

Did it work before?
No

Did you test with other Java versions?
OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10 - Issue reproduced
OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8 - Issue reproduced 
[hs_err_pid5808.log](https://github.com/adoptium/adoptium-support/files/7932228/hs_err_pid5808.log)

**Comment by karianna** [comment]
We've just released 11.0.14 - are you able to try on that?

Also what is the Java access bridge API?  Is that a JNI call to something?

**Comment by ankitraval** [comment]
Hello Karianna,

To get more information on Java access bridge Please refer  https://docs.oracle.com/en/java/javase/11/access/java-access-bridge-api.html#GUID-C10D11B0-F588-43FA-BBDE-70E9085E9AFF. 

Let me know if you want more information.

Thanks,
Ankit Raval

**Comment by karianna** [comment]
@ankitraval Can you try 11.0.15 and reopen this if its still an issue.
