### ISSUE TITLE
Install via APT

### ISSUE THREAD

**Issue by grumo35** [adoptium/adoptium-support#440]
Hi,

It was previously possible to install builds via APT using jfrog repository

https://adoptopenjdk.jfrog.io/adoptium/deb 

It looks dead now, i know there was a migration but couldnt find any news about the repositories with new names ? 

I need to serve package on an offline secured infrastructure via mirroring, thanks for the help.

**Comment by jerboaa** [comment]
https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/ might help.

**Comment by grumo35** [comment]
Hey just managed to make it work with https://packages.adoptium.net/deb 

Works event better with your tutorial also able to get gpg keys ! deb https://packages.adoptium.net/artifactory/deb bullseye main
 is the good one to add to your debian repos.

Thanks
