### ISSUE TITLE
AdoptOpenJRE and Temurin Feature Difference

### ISSUE THREAD

**Issue by Rakeshsim1** [adoptium/adoptium-support#441]
## Question
Hello, I am using  Open JRE Package (OpenJDK8U-jre_x64_windows_hotspot) and not able to find Java WebStart (IceTea Web) while installing the New package  for both 32 and 64 bits Version. JavaWeb (Ice Team Web) was available untill version 8u301 which could be easily installed install Wizard inside custom settings and now it is  missing New version 8u322.  

Can anyone Advise what changes have been made and how this Java Web Start Feature can be accessed. We need to Deploy this for large number of users.

Thanks In Advance
Regards,
Rakesh

## Context

Java version:

Your operating system and platform:

**Comment by karianna** [comment]
We no longer support this use case at Adoptium.  Please see https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/

**Comment by Rakeshsim1** [comment]
Hello karianna,

Thank you for your update. I have a few more questions now.

Even if we download Latest version of Open JRE from AdoptOpen JRE or Adoptium Website , Ice Team web component is still missing.

Adoptium Website Migration Guide shows that the IcedTea-Web component is available in Version OpenJDK 8.

I Have installed Multiple versions of JRE from Adoptium website for eg. "Eclipse Temurin JRE version 8u322 -X64" but the web component is missing in the custom section . This web component "IcedTea-Web" was available under custom section in Version 8U302- X64 as per screen shot below:

![image](https://user-images.githubusercontent.com/98759692/151836998-4c237e92-4d95-4e05-a183-8ba325210526.png).

We really need this component for lots of users in our environment are still using Iced-Tea Web component.

Could you let me  know How can we have access to the Web component or we we downloading incorrect versions or what version can be downloaded etc.

Thanks in Advance,

regards,
Rakesh

**Comment by karianna** [comment]
@hendrikebbers Is there some official guidance you can share here?

**Comment by Rakeshsim1** [comment]
Hello @karianna Thank you for your Help. @hendrikebbers Could you kindly help on the request.

**Comment by Rakeshsim1** [comment]
Hello   @karianna @hendrikebbers ,Could you help us solved the problem
