### ISSUE TITLE
Mac M1 OpenJDK11 Download Installed But Not Detected

### ISSUE THREAD

**Issue by janeofalltrades** [adoptium/adoptium-support#444]
I downloaded OpenJDK11 from https://adoptium.net/?variant=openjdk11. Opened and installed, but when searching Java version in Terminal I get back the following:

openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

I did not previously install version 17 and cannot get terminal to detect OpenJDK11. Assistance would be appreciated.

**Comment by karianna** [comment]
We recommend using https://www.jenv.be/ to manage your various Java installs on Mac OS X.  you'll be able to have both 11 and 17 and swap between them as you see fit.
