### ISSUE TITLE
can i use jdk-11.0.14+9 at your website(https://adoptium.net/?variant=openjdk11) commercially!!

### ISSUE THREAD

**Issue by DeveloperWork021** [adoptium/adoptium-support#445]
hello sir,

i want to ask that can i use jdk-11.0.14+9 at your website(https://adoptium.net/?variant=openjdk11) with android game development commercially or do i have to buy a license for that. and also if it is free
to use commercially then do i have to give credits to the jdk-11.0.14+9 maker or something like that.

thankyou

**Comment by karianna** [comment]
Yes, it's free to use (no restrictions) and free in cost!
