### ISSUE TITLE
Application crashed 

### ISSUE THREAD

**Issue by nulllinie** [adoptium/adoptium-support#449]
i've used the linux appimage 13.8.1, it was the first start after i used 13.5.1 (also appimage)
i'm not quit sure what i did last, either hitting the cross mark on the search field or the dialog cross mark for exiting. but afterwards the crash happend.
attached the crash log
i was not able to reproduce the crash, so feel free to close this report if you cannot work on it due to missing information.
best regards
[hs_err_pid52465.log](https://github.com/adoptium/adoptium-support/files/8034235/hs_err_pid52465.log)

**Comment by nulllinie** [comment]
wrong project :-(

**Comment by nulllinie** [comment]
reopened issue, because first analysis from project mediathekview on [their issue 652](https://github.com/mediathekview/MediathekView/issues/652) mentioned a check on temurin java project.

> Hmm the crash seems to be related to the Shenandoah Garbage Collector. You should report the crash to the temurin java project as they might want to check on it. The crash itself seems to be unrelated to MediathekView.
Apart from that I have seen quite a few crashes with JRE 17.0.1 in the context of concurrency. The next MediathekView will use JRE 17.0.2 which reduces (at least on my system) the number of crashes a lot.

**Comment by karianna** [comment]
17.0.3 should contain a host of Shenandoah fixes.
