### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by vikasmishra17** [adoptium/adoptium-support#455]
While installing elastic search faced the below error -

**OS - Ubuntu 20.4.3 focal fossa**

SIGSEGV (0xb) at pc=0x00007f6b31a4c4a0, pid=21056, tid=21109
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# J 59 c1 java.util.zip.ZipUtils.SH([BI)I java.base@17.0.1 (21 bytes) @ 0x00007f6b31a4c4a0 [0x00007f6b31a4c4a0+0x0000000000000000]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /usr/share/elasticsearch/core.21056)
#
# An error report file with more information is saved as:
# /usr/share/elasticsearch/hs_err_pid21056.log
Compiled method (c1)     857   59       3       java.util.zip.ZipUtils::SH (21 bytes)
 total in heap  [0x00007f6b31a4c310,0x00007f6b31a4c688] = 888
 relocation     [0x00007f6b31a4c470,0x00007f6b31a4c4a0] = 48
 main code      [0x00007f6b31a4c4a0,0x00007f6b31a4c5a0] = 256
 stub code      [0x00007f6b31a4c5a0,0x00007f6b31a4c5d0] = 48
 metadata       [0x00007f6b31a4c5d0,0x00007f6b31a4c5d8] = 8
 scopes data    [0x00007f6b31a4c5d8,0x00007f6b31a4c5f8] = 32
 scopes pcs     [0x00007f6b31a4c5f8,0x00007f6b31a4c668] = 112
 dependencies   [0x00007f6b31a4c668,0x00007f6b31a4c670] = 8
 nul chk table  [0x00007f6b31a4c670,0x00007f6b31a4c688] = 24
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues

**Comment by karianna** [comment]
Please try with our latest 17.0.2

**Comment by vikasmishra17** [comment]
17.0.2 version worked and issue is now resolved
