### ISSUE TITLE
Fatal error: Java Runtime Environment

### ISSUE THREAD

**Issue by Yoycoy** [adoptium/adoptium-support#456]
So recently I've been having my server randomly shutting down due to a Java Runtime Environment error. I can't seem to find the cause. I've included the logs. Hopefully, someone recognizes this issue and can help me solve it!

This issue happens randomly and causes my server to crash completely. I have allocated 2GB ram to this server which should be enough. Don't know what I'm doing wrong here.

[hs_err_pid369.log](https://github.com/adoptium/adoptium-support/files/8073380/hs_err_pid369.log)

**Comment by karianna** [comment]
@Yoycoy Can you try with the latest 17.0.3 and reply here?
