### ISSUE TITLE
chto mne delat

### ISSUE THREAD

**Issue by erop9123** [adoptium/adoptium-support#458]
## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by erop9123** [comment]
![Screenshot 2022-02-20 22-30-13](https://user-images.githubusercontent.com/100095214/154863430-fc1f8a24-2b33-43f6-ac57-62b686b63cce.png)

**Comment by karianna** [comment]
Please try with our latest 17.0.2

**Comment by karianna** [comment]
@erop9123 Please try with our latest 17.0.3 and reopen if the problem still persists
