### ISSUE TITLE
The crash happened outside the Java Virtual Machine in native code.

### ISSUE THREAD

**Issue by fekri1409** [adoptium/adoptium-support#459]
## Summary
I open a Dbeaver Community Edition software (install via flatpak). The software suddenly crash during import process from multiple CSV files.

But if I do same task using the Dbeaver Community Edition (install from deb package), I did not face any issue when import multiple csv files.

I use same version of Dbeaver CE which is  21.3.5

## Steps to reproduce

1. Selecting 5 tables from database
2. Right click on the selected table and choose Import Data
3. Data Transfer window appear :
    - Import Source. Click Next button
    -  Input file(s).
            The Dbeaver suddenly at this step when I try to add the 3rd CSV file

## Expected results

Able to import data from CSV into table in database

## Actual results

Crash during selecting CSV file

## Triaging info

Java version:
openjdk 18-ea 2022-03-22
OpenJDK Runtime Environment (build 18-ea+36-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 18-ea+36-Ubuntu-1, mixed mode, sharing)

What is your operating system and platform?
Ubuntu Jammy Jellyfish (development branch) - 64-bit

How did you install Java?
install via aptitude

Did it work before?

Did you test with other Java versions?

[hs_err_pid22.log](https://github.com/adoptium/adoptium-support/files/8133216/hs_err_pid22.log)

**Comment by jerboaa** [comment]
Please report this bug to the "Dbeaver Community Edition software" bug tracker.
