### ISSUE TITLE
AIX crashing because primordial thread  

### ISSUE THREAD

**Issue by ed03875** [adoptium/adoptium-support#460]
## Question

We have multi platform products. We are seeing the crash below (file included) on the AIX platform but not on Linux.   Looking at source  we see this has been fixed for Linux where we are not seeing the crash.  Is this an oversite or is it only AIX where the JVM must be started from a separate thread ? Should this be submitted as an AIX bug ?

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_aix.cpp:413), pid=15925536, tid=0x0000000000000001
#  guarantee(!os::is_primordial_thread()) failed: Must not be called for primordial thread
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode, sharing aix-ppc64 )

[hs_err_pid15925536.log](https://github.com/adoptium/adoptium-support/files/8134150/hs_err_pid15925536.log)

## Context

**Java version:**
bash-4.3$ $NOTESBIN/jvm/bin/java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

**Your operating system and platform:**

bash-4.3$ uname -a
AIX bldaix10 2 7 00FB68454C00

**Comment by BrijeshNekkare** [comment]
AIX doesn't allow primordial thread to do the java call in as the default native thread stack size is small. The default value of the native thread stacksize attribute is 192 KB. So creating a new thread for java call in, helps to control the size as needed via pthread_attr_setstacksize API.

On Linux though, default native thread stack size is of the order of few MBs.

**Comment by karianna** [comment]
FYI - We've also released 1.8.0_322, it's probably not going to be fixed in there, but worth a shot.

**Comment by ed03875** [comment]
Thank you we will try it

**Comment by karianna** [comment]
@ed03875 Can toy try the 1.8.0_332 build and reopen this if the problem still persists?
