### ISSUE TITLE
A fatal error Problematic frame: # C  [rxtxSerial.dll+0x44cb]

### ISSUE THREAD

**Issue by bust44** [adoptium/adoptium-support#464]
Hi all,
I work for a company in electronics.
Many thanks for advance for your support.
I have a problem with a communication with a serial port.
I give the detail:
Java version => java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
Windows 10 64 bit.

Jar version = RXTX-2.2pre1   (64bit)
native lib Version = RXTX-2.2pre2 (64bit)
RXTXcomm.jar

There is 7 years ago I created a short software to send some data in the serial port below the source code:
We use this application just to send some parameter on a very old equipment
It worked perfectly.
But the IT has changed  the different laptop in the company.
Me I receive an HP Elite Dragonfly G2 Notebook PC.
the other colleague a Lenovo PC (3 colleagues).
For two Lenovo we have seen nothing it continues to work. For me and the last colleague it doesn't work.
And when I check directly with the source code with eclipse I see the error during the execution of the command flush on my PC.

the system manage to send the character but just after it crashes.
Below the code where you have the report of the error.  
I checked the driver of the cable USB-SERIAL 
It is the same between the PC.
I have tried to update with the last version without changing.
Cable UGREEN driver Prolific USB-to-Serial Comm Port 3.8.36.2 / and also 3.8.41.0

For the dll rxtxSerial.dll,
I tried the version Pre 2 and the original version from my original code 1.7

Always time it crashes during the execution of flush.
If I recall me this command it is to push the data on the communication and to clear the buffer.
If you have some idea because me I arrive at the end :)

it still one possibility it is to try with java 32bit (I need to change the dll for the version 32bits).
But I would like to stay in 64bit.

//////1 part of code
public void writeDataEG4090(String serial_word)
    {
    	int inc_serial1 = 0 ;
    	byte singleData = 0;
    	int time_out = 0;
    //	SerialPortEvent evt = null ;
        try
        {
          while (inc_serial1 < serial_word.length() ){
          output.write(serial_word.codePointAt(inc_serial1));	  
          inc_serial1 ++;  
        	  
        	  
          }
        	
          output.write(10);	// caractere LF	
          output.flush();                                             _**=> here the crash**_ 
          while (answer_MC == false & time_out < 60000 ) {
        	//wait();
        	  time_out ++;
        	 
        	    System.out.println ("attend reponse serie MC ou MF");
          } 
          answer_MC = false;
          if (time_out == 60000 )
          {
        	  window.txtLog.append("time out\n"); 
        	  window.txtLog.update(window.txtLog.getGraphics());
        	 // System.exit(TIMEOUT);
          }
          time_out=0;
     
        }
        catch (Exception e)
        {
            logText = "Failed to write data. (" + e.toString() + ")";
            window.txtLog.setForeground(Color.red);
            window.txtLog.append(logText + "\n");
        }
    }

///////////////end of code

////////////////error from eclipse 
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000001800044cb, pid=9468, tid=18940
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [rxtxSerial.dll+0x44cb]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\MIS00114\workspace\serial_usb\hs_err_pid9468.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by karianna** [comment]
You state you're using Java 8 but the crash log uses 17.0.1?  Please do upgrade to 17.0.2 and try again :-)

**Comment by bust44** [comment]
Ok I try it thanks! :)

**Comment by bust44** [comment]
same error with the version 17.0.2

 A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000001800044cb, pid=5576, tid=18336
#
# JRE version: Java(TM) SE Runtime Environment (17.0.2+8) (build 17.0.2+8-LTS-86)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.2+8-LTS-86, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [rxtxSerial.dll+0x44cb]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\MIS00114\workspace\serial_usb\hs_err_pid5576.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by salfaro** [comment]
I am facing a similar error.  Is there a follow up conversation ?

**Comment by bust44** [comment]
Sorry But without solution I have decided to write a new application in Python for the communicationin serial. :(
But If you find something I'm interested ;)

**Comment by karianna** [comment]
> I am facing a similar error. Is there a follow up conversation ?

I'd recommend upgrading to 17.0.9 or 1.8.0_392 and contacting the folks who created the RXTX library (make sure you're on the latest of that as well
