### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by rj-san-juan** [adoptium/adoptium-support#468]
## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by rj-san-juan** [comment]
Java version:
jdk-11.0.11+9

What is your operating system and platform?
Ubuntu 18.04.5 LTS

How did you install Java?
apt install default-jdk

Did it work before?
no

Did you test with other Java versions?
no

**Comment by rj-san-juan** [comment]
error encountered:

ERROR (net.openhft.chronicle.core.onoes.Slf4jExceptionHandler$2.on:44) - lock of segment 164 is not clear: [read locks = 0, update locked = false, write locked = true, waits = 0]

ERROR (net.openhft.chronicle.core.onoes.Slf4jExceptionHandler$2.on:44) - Checksum doesn't match, stored: 1457209545, should be from the entry bytes: 1565100958, key: 306521, value: [PointValueTime(936.9@2022/03/09 10:04:18.549)]

ERROR (net.openhft.chronicle.core.onoes.Slf4jExceptionHandler$2.on:44) - Wrong number of entries counter for tier with index 653, stored: 652, should be: 165

Warning: Nashorn engine is planned to be removed from a future JDK release

message repeated 143 times: [ Warning: Nashorn engine is planned to be removed from a future JDK release]

**Comment by karianna** [comment]
That message is correct, Nashorn is was removed after 11.

**Comment by rj-san-juan** [comment]
do I need to upgrade the java version?

Error:
[thread 9507 also had an error]Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled

**Comment by karianna** [comment]
Yes 11.0.14.1 is the version you should use, you can grab that from adoptium.net

**Comment by rj-san-juan** [comment]
Please see below issue encountered:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:/usr/local/fosdas/web/modules/chroniclePointValueCache/lib/chronicle-core-2.21ea80.jar) to class java.lang.reflect.AccessibleObject
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Warning: Nashorn engine is planned to be removed from a future JDK release
message repeated 143 times: [ Warning: Nashorn engine is planned to be removed from a future JDK release]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f02708ac51d, pid=13456, tid=14492
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# v  ~StubRoutines::jshort_disjoint_arraycopy
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /usr/local/fosdas/core.13456)

**Comment by karianna** [comment]
you need to try with 11.0.14.1
