### ISSUE TITLE
java.library.path is ignored when given on the command line using the Linux operating system

### ISSUE THREAD

**Issue by ed03875** [adoptium/adoptium-support#470]
We are testing with the latest version 8u322

## Summary
During programmatic loading of libraries using System.loadLibrary() the JVM is suppose to use the java.library.path if it is specified on the command line  -Djava.library.path, This is stated in the Java API doc.  Unfortunately the HotSpot JVM is ignoring the directories we specified using -Djava.library.path. This works correctly on Windows but not on Linux.

## Steps to reproduce
Setup:  place findme in c:\tmp on windows or  /tmp on linux

Test program:
public class TestJVM
{
// just so it does something
public static void main(String[] args) {
String string = "The best of both worlds";
int count = 0;

//On windows platform dll is in "C:\temp\findme.dll"
//On Linux platform shared library is in /tmp/findme.so
// only important thing
System.loadLibrary("findme");

//Counts each character except space just so it does something
for(int i = 0; i < string.length(); i++) {
if(string.charAt(i) != ' ')
count++;
}

//Displays the total number of characters present in the given string to do something
System.out.println("Total number of characters in a string: " + count);
}
}

## Actual results from test runs
Here we run a test program on Windows with no java.library.path given on the command line and the shared library fails to load as expected 
1 [C:\tmp] C:\OpenJDK8H\bin\javac TestJVM.java && C:\OpenJDK8H\bin\java TestJVM
Exception in thread "main" java.lang.UnsatisfiedLinkError: no findme in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at TestJVM.main(TestJVM.java:9)

Here we run the test program on Windows giving the java.library.path on the command line and it works as expected
1 [C:\tmp] C:\OpenJDK8H\bin\javac TestJVM.java && C:\OpenJDK8H\bin\java -Djava.library.path=C:\temp TestJVM
Total number of characters in a string: 19

Here we run the test program on Linux with the java.library.path specified on the command line and the shared library fails to load 
OpenJDK]$ jdk8u322-b06-lnx/bin/javac TestJVM.java; jdk8u322-b06-lnx/jre/bin/java -Djava.library.path=/tmp TestJVM
Exception in thread "main" java.lang.UnsatisfiedLinkError: no findme in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at TestJVM.main(TestJVM.java:9)

## Expected results
One would expect that the library findme would be found after the -Djava.library.path is given on the command line

## Actual results
The library findme is not found after the java,library.path is given 

## Triaging info

Java version:
./java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)

What is your operating system and platform?
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

How did you install Java?
we copied the tar.gz file and installed into local directory

Did it work before?
Works on Windows fails on Linux 

Did you test with other Java versions?
java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

**Comment by perlun** [comment]
Late call, but @ed03875, could you show the output of the following command? I seem to be overriding the `java.library.path` fine on my machine.

```
$ /usr/lib/jvm/temurin-8-jdk-amd64/bin/java -Djava.library.path=/tmp -XshowSettings:properties -version 2>&1 | grep java.library.path -A10
    java.library.path = /tmp
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_322-b06
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Temurin
    java.vendor.url = https://adoptium.net/
    java.vendor.url.bug = https://github.com/adoptium/adoptium-support/issues
    java.version = 1.8.0_322
    java.vm.info = mixed mode
```

 (Note: I haven't yet tested any `System.loadLibrary` calls to ensure that it's picked up correctly with this setting.)

**Comment by perlun** [comment]
> (Note: I haven't yet tested any `System.loadLibrary` calls to ensure that it's picked up correctly with this setting.)

Verified, it does work correctly on this version of the package/JDK. (I use it as a local override because of a problem with `java.librarypath` in Temurin, will file a separate issue about this)

**Comment by karianna** [comment]
@ed03875 Are you able to try with 1.8.0_332 and can you also confirm that this is both a Windows and a Linux issue?

@perlun seemed to be able to get the override to work on Linux...
