### ISSUE TITLE
moving away from using Oracle Java and want to know if deployment.properties, exception.sites, deployment.config are supported?

### ISSUE THREAD

**Issue by FelixNew1** [adoptium/adoptium-support#471]
## Context

Java version:

Your operating system and platform:

**Comment by karianna** [comment]
I  think you're referring to JavaWebstart technology there which is not supported out of the box.  Please see IcedTeaWeb for an alternative with OpenJDK

**Comment by FelixNew1** [comment]
Is there a particular forum I should be asking?  I was provided with this support link by a colleague.
