### ISSUE TITLE
https://github.com/AdoptOpenJDK/openjdk-support/issues

### ISSUE THREAD

**Issue by rj-san-juan** [adoptium/adoptium-support#472]
## Summary

SIGBUS (0x7) at pc=0x00007f02708ac51d, pid=13456, tid=14492
JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
v  ~StubRoutines::jshort_disjoint_arraycopy
Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /usr/local/fosdas/core.13456)

## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by karianna** [comment]
please try with 11.0.14.1 and try again

**Comment by rj-san-juan** [comment]
Thank you @karianna, I will let you once we upgrade to 11.0.14.1 and if the issue has been fix with that upgrade.

**Comment by rj-san-juan** [comment]
Thank you @karianna, I will let you know once we upgrade to 11.0.14.1 and if the issue has been fix with that upgrade.
