### ISSUE TITLE
Some Fonts are missing with JDK 11

### ISSUE THREAD

**Issue by sephiroth-j** [adoptium/adoptium-support#473]
## Summary

If running NetBeans or Oracle SQL Developer with Temurin JDK 11, fonts such as [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) or [Cascadia Code](https://github.com/microsoft/cascadia-code) are unavailable. They do not show up in the font selection dialog.

## Steps to reproduce

- [Download Netbeans](https://netbeans.apache.org/download/index.html)
- Install one of the fonts
- Start Netbeans with the JDK to test (may need to set `netbeans_jdkhome` in `etc/netbeans.conf`)
- open Tools > Options and go to "Fonts & Colors"
- try to select one of the fonts

## Expected results
Fonts should be available

## Actual results
Fonts are unavailable

## Triaging info

Java version:

```
❯ java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
```

What is your operating system and platform?

Windows 10 21H2 x64

How did you install Java?

Downloaded JDK and unpacked Zip-File for Win x64 from https://adoptium.net/releases.html

Did it work before?

It worked with Oracle JDK. It also works with Temurin 17.0.2+8.

Did you test with other Java versions?

- Oracle JDK 17 LTS and 11 LTS
- Temurin 17 LTS
```
❯ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

**Comment by karianna** [comment]
This is likely simply due to the Font Packages deployed with OpenJDK 11 vs OpenJDK 17.  Sounds like 17 works which is great as that's the preferred version :-)
