### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Tee12345** [adoptium/adoptium-support#474]
Java version:
Java 11. Open JDK 11.0.12

What is your operating system and platform?
Windows 8.1. Spring Tool Suite IDE

Did it work before?
NO

Did you test with other Java versions?
NO

This is the error from STS IDE.

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000180008910, pid=8052, tid=10412

JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, emulated-client, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  [LavasoftTcpService64.dll+0x8910]

No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Comment by sxa** [comment]
I'm a bit confused - you say at the start you're using Java/OpenJDK11 but the version output says 17.0.1.

Can this be reproduced reliably? Can you try on the new 17.0.3? And if it's still showing can you try a runtime from another provider - Azul/Corretto/Oracle - to see if it occurs with those? That will determine any potential next action.

I would also point out that if you're really using Windows 8.1 which was out of mainstream support in 2018 it is unlikely we could support that.
