### ISSUE TITLE
 SIGSEGV  on  JRE 1.8.0_322-b06 - si_code: 1

### ISSUE THREAD

**Issue by kapil-suri-by** [adoptium/adoptium-support#475]
Have you tested with the latest version? yes  we are on 1.8.0_322-b06

## Summary 
JVM encounter  SIGSEGV

## Steps to reproduce
This  SIGSEGV occurs randomly in a spring application that is calling hazelcast .When the  SIGSEGV happened it was like 7 days after the restart. unfortunately we don't have the steps to reproduce.

## Expected results
We don't expect a crash.

## Actual results
JVM Crashed with  SIGSEGV error

## Triaging info
SIGSEGV (0xb) at pc=0x00007f1f3f40ac0c, pid=8, tid=0x00007f1df83e1700

Problematic frame:
 J 33232 C2 java.time.LocalDate.toString()Ljava/lang/String; (148 bytes) @ 0x00007f1f3f40ac0c [0x00007f1f3f40abe0+0x2c]

## Java version:
JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)

## What is your operating system and platform?
centos-7 and  25.322-b06 mixed mode linux-amd64 

## How did you install Java?
Docker image - eclipse-temurin:8u322-b06-jdk-centos7

## Did it work before?
No ,When we are on java version 1.8.0_212-b04 we got SEGSEGV error ,so we upgrade the java version to 1.8.0_322-b06 in our env but still we got this error again.

## Did you test with other Java versions?
1.8.0_212-b04
[hs_err_pid8.log](https://github.com/adoptium/adoptium-support/files/8259222/hs_err_pid8.log)

**Comment by karianna** [comment]
Reading that log it looks like you are serialising a LocalDate via the Logback logging framework. That LocalDate seems to be deserialized in memory after it gets it from a Hazelcast topic.  In the extreme short term you could disable that logging or trying to figure out what is in that DateTime object.

I'll look at getting this reported upstream but we may need to understand what is being passed in there.

**Comment by kapil-suri-by** [comment]
[capacity_scheduler.txt](https://github.com/adoptium/adoptium-support/files/8265738/capacity_scheduler.txt)
This is what we received from kafka topic and during deserialization it got crashed.

**Comment by karianna** [comment]
https://bugs.openjdk.java.net/browse/JDK-8283440

**Comment by kapil-suri-by** [comment]
The server crashed again with the same error No update from jdk team.

**Comment by karianna** [comment]
@kapil-suri-by Can you try 1.8.0_332?

**Comment by karianna** [comment]
@kapil-suri-by Can you try with the latest 1.8.0_345?
