### ISSUE TITLE
SIGSEGV (0xb) at pc=0x00007f1a5cb2b30b

### ISSUE THREAD

**Issue by tupaq** [adoptium/adoptium-support#476]
## Summary
The error occurs when opening eclipse in Ubuntu 22.04 beta

## Steps to reproduce
run eclipse
Select workspace
And the window closes

## Actual results

 A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007f1a5cb2b30b, pid=4708, tid=4709

JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
C  [libwebkit2gtk-4.0.so.37+0x69130b]

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/acuellar/core.4708)

An error report file with more information is saved as:
/home/acuellar/hs_err_pid4708.log

If you would like to submit a bug report, please visit:
  https://github.com/adoptium/adoptium-support/issues
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

## Triaging info

Java version: 
OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)

What is your operating system and platform? 
Ubuntu Jammy Jellyfish (development branch) AMD64

How did you install Java?
It is downloaded by default in eclipse

[hs_err_pid4708.log](https://github.com/adoptium/adoptium-support/files/8308716/hs_err_pid4708.log)

Did it work before?
Yes, then gnome was updated and it stopped working

Did you test with other Java versions?
No

**Comment by karianna** [comment]
I would report this to the GNOME folks as they have introduced a bug in their beta native lib
