### ISSUE TITLE
completely random crashes when playing minecraft

### ISSUE THREAD

**Issue by NPC-Master3304** [adoptium/adoptium-support#479]
this issue has been going on for such a long period of time, and finally after 2-3 years, an actual crash result appeared.

```
[11:00:28] [Render thread/INFO]: OpenGL debug message: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=7784 javaw.exe 64bit)'
[11:00:28] [Render thread/INFO]: OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to allocate memory for buffer object.'
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff88eda1991, pid=7784, tid=8920
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, shenandoah gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x861991]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Geek Squad Data Backup 3-4-14\Desktop2018\NPC\MultiMC\instances\Minecraft Beta 1.18 [Fabric] [aristois]\.minecraft\hs_err_pid7784.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 2 devices not closed
```
log here:
[hs_err_pid7784.log](https://github.com/adoptium/adoptium-support/files/8352099/hs_err_pid7784.log)

**Comment by karianna** [comment]
Hi there,

You'll need to report this to Mojang.  I'll not you're also using a Beta 1.18 server.

**Comment by NPC-Master3304** [comment]
> Hi there,
> 
> You'll need to report this to Mojang. I'll not you're also using a Beta 1.18 server.

I'm sort of confused about the 1.18 beta server since this is on a client, but for some reason I can't report this to Mojang for whatever reason. There's no way for me to create an account. Here: https://bugs.mojang.com/Signup!default.jspa

**Comment by TheKodeToad** [comment]
> > Hi there,
> > You'll need to report this to Mojang. I'll not you're also using a Beta 1.18 server.
> 
> I'm sort of confused about the 1.18 beta server since this is on a client, but for some reason I can't report this to Mojang for whatever reason. There's no way for me to create an account. Here: https://bugs.mojang.com/Signup!default.jspa

I think you want https://bugs.mojang.com/register/

**Comment by NPC-Master3304** [comment]
> > > Hi there,
> > > You'll need to report this to Mojang. I'll not you're also using a Beta 1.18 server.
> > 
> > 
> > I'm sort of confused about the 1.18 beta server since this is on a client, but for some reason I can't report this to Mojang for whatever reason. There's no way for me to create an account. Here: https://bugs.mojang.com/Signup!default.jspa
> 
> I think you want https://bugs.mojang.com/register/

sorry for the late reply, but thank u so much. ive been having this issue for so long. ill go ahead n attempt to do it in vanilla and report the issue.
