### ISSUE TITLE
java.util.Properties get and getProperty are inconsistent 

### ISSUE THREAD

**Issue by amarktl** [adoptium/adoptium-support#482]
## Summary

When initializing a new instance of java.util.Properties with an already existing instance as defaults, all keys are returned from `propertyNames()`. When iterating over the returned enumeration and  trying to retrieve the associated value with `get(k)` null is returned if the values is mapped in the **defaults** and not in the current instance. Using `getProperty(k)` instead will return the correct value.

Problem was discovered while updating the Oracle JDBC driver which  internally changed and now iterates over the Enumeration of PropertyNames and uses get instead of cloning the given properties as a whole as done before.

## Steps to reproduce

```
import java.util.Enumeration;
import java.util.Properties;

public class PropertiesInconsistentRetrievalTest {

    public static void main(String[] args) {
        Properties orig = new Properties();
        orig.put("x", "x");

        Properties next = new Properties(orig);
        next.put("y", "y");

        Enumeration<?> enumeration = next.propertyNames();
        while (enumeration.hasMoreElements()) {
            Object k = enumeration.nextElement();
            System.err.println("k: '" + k + "' v: '" + next.get(k) + "' p: " + next.getProperty((String) k));
        }
    }
}

```
## Expected results

Given the above code sample `get(k)` and `getProperty(k)` should return the same result if the key `k` is returned in `propertyNames()`.

## Actual results

Given the above code sample `get(k)` returns `null` and `getProperty(k)` return `x`

## Triaging info

Java version:

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

What is your operating system and platform?

Fedora 35
Linux 5.16.18-200.fc35.x86_64
x86_64 GNU/Linux

How did you install Java?

zipped

Did it work before?

unknown

Did you test with other Java versions?

No

**Comment by suresk** [comment]
I'm fairly certain this expected behavior with `java.util.Properties`, albeit probably not amazing API design. `get` comes from the `Hashtable` class that `java.util.Properties` extends. It doesn't recursively look up properties, whereas `getProperty` is defined by the `java.util.Properties` class and per its documentation, does recursively look them up.

In other words, the thing looking up properties should be using `getProperty` and not `get`.

**Comment by amarktl** [comment]
@suresk i agree that the API "design" is rather poor here - so if this is most likely not being addressed within java itself i think i will open an Oracle SQL Driver bug cause they are using `get` instead of `getProperty` which leads to missing driver settings.

**Comment by amarktl** [comment]
@karianna  thx for closing the issue here. I filed a bug for the Oracle JDBC Driver that their handling of the given Properties Object is faulty. 
BR Alex
