### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by beautybloodtr** [adoptium/adoptium-support#483]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff4a90265e9, pid=1012, tid=0x00007ff3af1f4700
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# j  net.minecraft.server.v1_8_R3.Chunk.b(Z)V+78
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/Skyblock/hs_err_pid1012.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues

**Comment by karianna** [comment]
Please use latest 1.8.0.322 and try again.

**Comment by karianna** [comment]
@beautybloodtr Can you try with the latest 1.8.0_332 and try again?
