### ISSUE TITLE
C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4

### ISSUE THREAD

**Issue by peutch** [adoptium/adoptium-support#484]
Hi,
I am facing the attached crash report using Eclipse 2022-03 on Ubuntu 22.04.
Thanks,
Patrice

[hs_err_pid8892.log](https://github.com/adoptium/adoptium-support/files/8440800/hs_err_pid8892.log)

**Comment by technicalguru** [comment]
Same here since upgrade to Ubuntu 22.04

**Comment by mgm3746** [comment]
I used to get this all the time, multiple crashes per day, on RHEL8 using Red Hat Codeready Studio. My CODEREADY_STUDIO_HOME/studio/ directory is filled with fatal error logs. 

But it has recently stopped. I don't have a single crash with 11.0.15. That seems to be when it stopped.

I have not tried running on JDK17.

**Comment by technicalguru** [comment]
The crash disappears when deactivating Wayland in Ubuntu 22.04.

**Comment by peutch** [comment]
On my side, this does not happen anymore since Eclipse 2022-06 which is based on:
```
java.class.path=/home/patrice/local/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
java.class.version=62.0
java.home=/home/patrice/local/eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_18.0.1.v20220515-1614/jre
java.io.tmpdir=/tmp
java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=18.0.1+10
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=18
java.vendor=Eclipse Adoptium
java.vendor.url=https://adoptium.net/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
java.vendor.version=Temurin-18.0.1+10
java.version=18.0.1
java.version.date=2022-04-19
java.vm.compressedOopsMode=32-bit
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=18
java.vm.vendor=Eclipse Adoptium
java.vm.version=18.0.1+10
```

**Comment by technicalguru** [comment]
Still have the crash with Wayland, Ubuntu 22.04 and Eclipse 22-06

**Comment by karianna** [comment]
As this bug has been reported upstream and there are several workarounds (and also the ability to use newer versions of Java), I'm going to close this issue
