### ISSUE TITLE
Eclipse Temurin JDK with Hotspot (17.0.2) cannot be configured in VS Code

### ISSUE THREAD

**Issue by AnkitKashyap0709** [adoptium/adoptium-support#487]
## How do I configure the "Eclipse Temurin JDK with Hotspot" in VS Code after installation by the "coding pack for java"?

I tried installing the JAVA JDK on my laptop, provided by the installer on VS Code website as a "Coding pack for Java". It installed the JDK and the required extensions in VS Code. But then inside the editor, it didn't configure the JDK by itself. So I tried doing it manually and then I found that there is no "JDK" folder in the "Program Files" folder in C-drive. I tried to find everywhere inside that folder about the JDK, searched online at many places, and reinstalled it several times but still, nothing worked. I can't address the error. Please reach out to me if anyone knows the fix for it.

## MISSING JDK even after installation. Help fix it.

Java version: 17.0.2

Java -version:
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

Operating system and platform: 
OS - Windows 10 pro 21H2 on x64
Platform - V.S.Code

![5](https://user-images.githubusercontent.com/63182579/162825075-5a533e3c-4522-46cf-93c7-f8739aa92c65.PNG)

**Comment by karianna** [comment]
@AnkitKashyap0709 you need to report this to the VSCode team.
