### ISSUE TITLE
Error Install jdk-11.0.14.1+1 on Mac

### ISSUE THREAD

**Issue by MichaelBonfanti** [adoptium/adoptium-support#488]
Hi I have a problem installing the jdk (jdk-11.0.14.1 + 1) l-intsaller tells me that it is installed correctly but when I go to the terminal and do javac it gives me an error. the operating system I use is MacOS Catalina 10.15.7

**Comment by karianna** [comment]
Can you try running the full path `/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/javac --version`?

Also can you tell us what:

`echo $PATH` and `echo $JAVA_HOME` are?
