### ISSUE TITLE
Trickle Crash

### ISSUE THREAD

**Issue by duCCsauCe** [adoptium/adoptium-support#492]
## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

![Capture](https://user-images.githubusercontent.com/104148964/164472134-749518f1-1651-445b-92af-58fad1d20ce2.PNG)

im getting this whenever i start Trickle

**Comment by karianna** [comment]
Assuming this is Spotify's Trickle, that lib is no longer supported and may well trigger native crashes like this..

**Comment by karianna** [comment]
@duCCsauCe you can try the 11.0.15 release but I'm afraid we can't help beyond that.
