### ISSUE TITLE
Cannot find out dumping file after fatal error from [libc.so.6+0x826bc]

### ISSUE THREAD

**Issue by jackyyeung-asw** [adoptium/adoptium-support#496]
## Summary
Cannot find out the dumping file

## Steps to reproduce
No specific step, there is a sudden HS_ERROR from Apache Tomcat

## Expected results
Should have a file specified in the log file under server

## Actual results
Cannot locate the file

## Triaging info
Java version:
Temurin-11.0.14.1+1

What is your operating system and platform?
Oracle Linux 7.7 on x86-64

How did you install Java?
Use tar.gz

Did it work before?

Did you test with other Java versions?
Yes, AdoptOpenJDK-11.0.11+9, same problem

[hs_err_pid25937.log](https://github.com/adoptium/adoptium-support/files/8587810/hs_err_pid25937.log)
[hs_err_pid19777.log](https://github.com/adoptium/adoptium-support/files/8587811/hs_err_pid19777.log)m

**Comment by karianna** [comment]
@jackyyeung-asw Can you please try the latest 11.0.15?
