### ISSUE TITLE
AdoptOpenJDK

### ISSUE THREAD

**Issue by priyalgandhi** [adoptium/adoptium-support#497]
## Context

Java version: 8.0.322.6

Your operating system and platform:

**Comment by karianna** [comment]
You'll need to provide more details.  What path are you searching under?  Did the installer complte?  Can you run java from hte command line etc etc.

**Comment by priyalgandhi** [comment]
I am searching is under C:\Program Files\AdoptOpenJDK\jdk-8.0.202.08 as per the instruction. The thing is I can not even see any folder "AdoptOpenJDK" under program files. And not able to find the folder location. So how can I find the path?

**Comment by gdams** [comment]
I assume that you're actually installing Eclipse Temurin? Rather than AdoptOpenJDK

Take a look at https://adoptium.net/installation/windows/

It's likely been installed in `C:\Program Files\Eclipse Adoptium\<version>`

**Comment by sxa** [comment]
@priyalgandhi Can you let us know where you saw that path in the instructions?
