### ISSUE TITLE
Will Debian 11 Bullseye be supported with temurin? 

### ISSUE THREAD

**Issue by contherad** [adoptium/adoptium-support#498]
## Question

Was using openjdk with bullseye now moving to temurin, but no bullseye container is available. Will there be in the future? 

## Context

Java version: 

17.0.3

Your operating system and platform:

Debian 11.3 "Bullseye"

**Comment by karianna** [comment]
Only the O/S versions supported by DockerHub official will be supported so for this one you'll have to create your own image.
