### ISSUE TITLE
no api docs on how to get the download links

### ISSUE THREAD

**Issue by jredfox** [adoptium/adoptium-support#501]
I want openjdk8u33 with default jvm yet I don't see anyway on how to get the urls?

**Comment by sxa** [comment]
We provide a download API which is documented at https://api.adoptium.net/q/swagger-ui/

For example, the following link will download the latest JDK17 (LTS) tar tvfz for Linux/aarch64:
- https://api.adoptium.net/v3/binary/latest/17/ga/linux/aarch64/jdk/hotspot/normal/eclipse
