### ISSUE TITLE
am I allowed to re-distrubute the compiled binraries

### ISSUE THREAD

**Issue by jredfox** [adoptium/adoptium-support#502]
## Question
are you allowed to re-distrubute the compiled binraries from adoptopenjdk. according to the GLP 3 license I can do this just uploading any source code to the public. you said that x versions may go down at any time well I want to download and install x version for y os for my program.

**Comment by sxa** [comment]
Yes you are free to redistribute the binaries.

**Comment by jredfox** [comment]
Ok cool at least if I can't find out how to compile it I can use yours

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
