### ISSUE TITLE
ugsplatfrom crashing after splash art

### ISSUE THREAD

**Issue by debswoodresin** [adoptium/adoptium-support#503]
recently downloaded and installed UGS Nightly and on opening UGSPLATFORM64 the programme crashes after loading and showing the splash screen.

[hs_err_pid10204.log](https://github.com/adoptium/temurin-build/files/8611443/hs_err_pid10204.log)

**Comment by sxa** [comment]
Can you check to see if the same problem also occurs with another provider e.g. Oracle/Azul/Bellsoft/Corretto?

**Comment by sxa** [comment]
Oh you're using OpenJDK13 and it's not one of ours - that version is no longer supported and so will not be fixed. Please use JDK17 or 18 instead.
