### ISSUE TITLE
Crash in Shenandoah 17.0.3 - SIGSEGV in vm maybe related to xerces

### ISSUE THREAD

**Issue by ghost** [adoptium/adoptium-support#505]
## Summary

We currently getting **irregularily vm crashes** in our junit test infrastruktur. 
We are using `eclipse-temurin:17.0.2_8-jdk-focal` base image and exceuting our test with gradle 7.3.
We are using `shenandoah` gc because we are quite memory constrainted in our containers and their hosts. 
We ran the test on the `adoptopenjdk:11-hotspot-focal` containers before with the same gc settings and they were fine.

Reading the replay.log it seems like it is related to xerces code. But understanding the replaylog is not my expertice. :wink: 
Because the crashes are not reliably reproduceable, it currently not possible to provide a simple code-example that leads to the crash.

Can you guys assist in pinpointing this in more detail? 
Please find attached hs_error log and replay log of such a crash.

[replay_pid1556530.log](https://github.com/adoptium/adoptium-support/files/8676649/replay_pid1556530.log)
[hs_err_pid1556530.log](https://github.com/adoptium/adoptium-support/files/8676650/hs_err_pid1556530.log)

Thanks in advance for your help.

**Comment by BuchienDP** [comment]
Sorry for the deplay. I tested it with `eclipse-temurin:17.0.2_8-jdk-focal`. 
Got the same random crashes. Please find error and replay logs attached.
Quick look into the replay log shows the same xerces internal methods.
[hs_err_pid45380.log](https://github.com/adoptium/adoptium-support/files/8706089/hs_err_pid45380.log)
[replay_pid45380.log](https://github.com/adoptium/adoptium-support/files/8706090/replay_pid45380.log)

**Comment by lennartfricke** [comment]
Issue is reported using bugs.java.com

**Comment by karianna** [comment]
@lennartfricke did you get a bug ID back that we can link here?  FWIW - this appears to be a Shenandoah GC bug for sure.

**Comment by rwestrel** [comment]
The author of the code that crashes here.
Even if there's no simple code example to reproduce this, could you provide instructions so I can try to reproduce this? What to build and run?

**Comment by karianna** [comment]
It's a crash in the Garbage Collector, so will be pretty hard to reproduce with a simple case.  The log provided does contain enough detail but Shenandoah isn't supported by Oracle (it's supported by Red Hat).  I'll see if @lennartfricke can give us the bug Id and I'll route accordingly.

**Comment by rwestrel** [comment]
https://bugs.openjdk.org/browse/JDK-8288302 is the bug
Even if there's no simple case, instructions to reproduce this are needed.

**Comment by karianna** [comment]
Let us keep this open bot :-)

**Comment by dmatej** [comment]
My Maven build crashed too right now ... Second attempt passed. 

```
[INFO] --- maven-compiler-plugin:3.10.1:compile (process-annotations) @ common-util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 190 source files to .../glassfish-beta/nucleus/common/common-util/target/classes
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb59b61ea0b, pid=778413, tid=778454
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, shenandoah gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xbe2a0b]  Node::unique_ctrl_out() const+0xb
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to .../glassfish-beta/core.778413)
#
# An error report file with more information is saved as:
# .../glassfish-beta/hs_err_pid778413.log
#
# Compiler replay data is saved as:
# .../glassfish-beta/replay_pid778413.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
```

**Comment by rwestrel** [comment]
@dmatej Could you provide instructions to reproduce this?

**Comment by dmatej** [comment]
> @dmatej Could you provide instructions to reproduce this?

I would love to, but I can't - it happened just once until now.

I used these JVM options (via .mavenrc file):
```
MAVEN_OPTS='
-Xms2g -Xmx4g -Xss768k
-XX:+UseShenandoahGC
-XX:+UseStringDeduplication
-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts
-Dcom.sun.security.enableAIAcaIssuers=true
-Djavax.net.debug=
--add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.io=ALL-UNNAMED
'
```

**Comment by rwestrel** [comment]
@dmatej Actually, I'm not sure I can tell from the bug report what build causes the crash. What repo is it and how should I build it? Do you still have the replay and hs_err files that were produced by the crash? Can you attach them to the bug?

**Comment by dmatej** [comment]
[replay_pid778413.log](https://github.com/adoptium/adoptium-support/files/9654741/replay_pid778413.log)
[hs_err_pid778413.log](https://github.com/adoptium/adoptium-support/files/9654743/hs_err_pid778413.log)
Repository: https://github.com/eclipse-ee4j/glassfish, command `mvn clean install -Pfastest -T4C`
Sorry, I would upload them directly, but at that time I could not find how, now I googled it :-)

**Comment by rwestrel** [comment]
@dmatej thanks

**Comment by rwestrel** [comment]
@dmatej would you still have the core file and would you be willing to share it with me?

**Comment by dmatej** [comment]
It took me a while to find it :-)
It is a quite large file, even zipped, so I uploaded it temporarily to the Google Disk: https://drive.google.com/file/d/1UzNQnIiVzScWMQkAAFOIPZuDND8hS6b8/view?usp=sharing

**Comment by rwestrel** [comment]
@dmatej thanks for taking the time to do that. I downloaded the core file.

**Comment by rwestrel** [comment]
I could reproduce it and have a fix. It will be fixed in the current development branch of the jdk first (jdk 20) and backported to some future 17 release.
