### ISSUE TITLE
Fedora Version 36  is not supported in the distribution in JFrog

### ISSUE THREAD

**Issue by boris-unckel** [adoptium/adoptium-support#506]
Tested 2022-05-12 with https://adoptium.jfrog.io/ui/native/rpm/fedora/

## Summary
The latest Fedora Version 36 ( https://fedoramagazine.org/announcing-fedora-36/ ) is not supported in the distribution in JFrog.

## Steps to reproduce
Check https://adoptium.jfrog.io/ui/native/rpm/fedora/ and lookout for 26.

## Expected results
Expected is $releasever (with 36) works dynamically

[AdoptiumJDK]
name=AdoptiumJDK
baseurl=https://adoptium.jfrog.io/artifactory/rpm/fedora/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public

## Actual results
A hardcoded out of date version is needed (35)
[AdoptiumJDK]
name=AdoptiumJDK
baseurl=https://adoptium.jfrog.io/artifactory/rpm/fedora/35/$basearch
enabled=1
gpgcheck=1
gpgkey=https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public

## Triaging info

Java version:

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

What is your operating system and platform?

cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36

How did you install Java?

sudo dnf install temurin-8-jdk
sudo dnf install temurin-11-jdk
sudo dnf install temurin-17-jdk

Did it work before?
Yes. I have updated from Fedora 35 to 36.

Did you test with other Java versions?
Yes

**Comment by gdams** [comment]
This will be fixed in the next release (July) by https://github.com/adoptium/installer/pull/479
