### ISSUE TITLE
Linux JDK LSB Shared Object vs Executable

### ISSUE THREAD

**Issue by hink084** [adoptium/adoptium-support#509]
The original question was posted in the [Eclipse Forums](https://www.eclipse.org/forums/index.php/m/1852438/) on 10/29/2021.

**Environment**
Oracle Linux Server 7.7

I noticed there was a difference in the ELF type between the newer Eclipse Adoptium JDKs and the older AdoptOpenJDK JDKs.  I'm unsure if the change from _Executable File_ to _Shared Object File_ was intentional or not.

**Adoptium JDK - 18.0.1+10**
**Adoptium JDK - 11.0.15+10**
```
> file java
java: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, not stripped


> readelf -h java
...
Type: DYN (Shared object file)
...
```

**AdoptOpenJDK - 11.0.6+10**
```
> file java
java: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=20131b09aa65e3b6cb90241e00ed35d84efa1f38, not stripped


> readelf -h java
...
Type: EXEC (Executable file)
...
```

**Comment by karianna** [comment]
@hink084 I suspect this is a side effect of the default in GCC changing.  Is there a concern that this is a shared object as opposed to an executable from your perspective?

**Comment by hink084** [comment]
I originally discovered this issue because of a proprietary shell script checking for ELF types of "EXEC (Executable file)".  

At the time, I didn't know the difference between a  _Shared Object_ and _Executable_ ELF file types.  I was concerned that the change in the file type may have been unintentional and overlooked.  However, upon further investigation, this may be a nonissue.  

This forum on AskUbuntu provides some insight on the difference between a _Shared Object_ and a _Executable_:
[https://askubuntu.com/questions/690631/executables-vs-shared-objects](https://askubuntu.com/questions/690631/executables-vs-shared-objects)

With that being said, I'm going to go ahead and close this issue.  If there is a valid concern here we can reopen it, but at least the change in file type is documented for the community to reference.
