### ISSUE TITLE
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by brucedchen1991** [adoptium/adoptium-support#511]
![image](https://user-images.githubusercontent.com/22440892/169219547-c1ba4dd0-1a0a-40c0-a675-c4419e5419aa.png)

**Comment by danillotparreira** [comment]
![image](https://user-images.githubusercontent.com/4616631/170578634-02d226de-bd55-4c40-8849-405aaf03458f.png)
[hs_err_pid5468.log](https://github.com/adoptium/adoptium-support/files/8782054/hs_err_pid5468.log)
