### ISSUE TITLE
19 version with loom?

### ISSUE THREAD

**Issue by maxandersen** [adoptium/adoptium-support#512]
## Question

Any chance of getting 19-ea upgraded from February +9 to +22 so loom is included ?

## Context

want to make it easy to use early access features with jbang - would prefer to use Adoptium if possible.

**Comment by karianna** [comment]
Our nighlty builds should catch this as soon as the merge goes into jdk tip

**Comment by quintesse** [comment]
What is "jdk tip" exactly? There is a tagged release https://github.com/openjdk/jdk/tree/jdk-19+22, isn't that it?

**Comment by karianna** [comment]
It should be yes, our nightly 19 builds should be picking this up...

**Comment by quintesse** [comment]
The problem seems to be in the foojay.io API we're using in Jbang for listing JDK distro's and versions. They've confirmed that something's off and they're looking into it. So this issue can probably be closed.
