### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by TeeQuee** [adoptium/adoptium-support#514]
![feathercrash](https://user-images.githubusercontent.com/106008902/169684441-a5b6c6db-7f7a-4094-a623-a1627040a419.png)
![feathercrash2](https://user-images.githubusercontent.com/106008902/169684466-24fe7f24-ae07-48ad-9e2f-6f41427037c4.png)

I crash every time i join a server i tried shutting mods off and on. 
I have tried to update computer, restart computer and restart feather.

**Comment by karianna** [comment]
Please try with 17.0.3 and send in that crash report (full log please).
