### ISSUE TITLE
C2 CompileTask PhaseAggressiveCoalesce::coalesce SIGSEGV

### ISSUE THREAD

**Issue by devinrsmith** [adoptium/adoptium-support#516]
## Summary

C2 CompileTask PhaseAggressiveCoalesce::coalesce is crashing with a SIGSEGV.

The issue is exhibited from multiple methods, potentially involving array / vectorization optimizations. We've so far worked around it by setting up a compiler directives file with excludes, but that's rather fragile and we are finding more places that eventually hit this error.

## Steps to reproduce

Currently, we are only able to reproduce using our junit test suite. We've also seen it in our running application, but we don't currently have a framework to easily reproduce that setup. I'm working on creating a more minimal reproduction. Some of our developers are able to reproduce the issue frequently, some are able to reproduce it infrequently, and others appear to not be able to reproduce it. I'm guessing there may be hardware or environmental issues at play. The issue is reproducible within the standard Github Actions runner environment.

Here's the branch that is meant to reproduce the issue - https://github.com/deephaven/deephaven-core/tree/nightly/phase-aggressive-sigsegv. 

```shell
./gradlew -PtestRuntimeVersion=17 -PtestRuntimeVendor=adoptopenjdk -PforceTest=true engine-table:testOutOfBand --tests io.deephaven.engine.table.impl.QueryTableAggregationTest.testMedianByIncremental
```

The above command may need to be run multiple times (10+) to get the SIGSEGV. By default, it's set to run against a Java 11 (specific version depends on OS and gradle) by default. On my local machine, I can reproduce much more consistently w/ java 17 by setting `-PtestRuntimeVersion=17`. The `nightly/phase-aggressive-sigsegv` branch is also setup to run a GH workflow to run these specific tests. 

## Triaging info

The issue is reproducible on the latest versions of OpenJDK 11 and 17 (and have also been reproduced on earlier versions of 11 and 17).

```
# JRE version: OpenJDK Runtime Environment Temurin-11.0.15+10 (11.0.15+10) (build 11.0.15+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (11.0.15+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x62619c]  PhaseAggressiveCoalesce::coalesce(Block*)+0x50c
```

```
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x597885]  PhaseAggressiveCoalesce::coalesce(Block*)+0x65
```

In GH CI, the environment seen so far:
* Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz, 2 cores, 6G, Ubuntu 20.04.4 LTS
* Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz, 2 cores, 6G, Ubuntu 20.04.4 LTS
* Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz, 2 cores, 6G, Ubuntu 20.04.4 LTS
* Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz, 2 cores, 6G, Ubuntu 20.04.4 LTS
* Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz, 2 cores, 6G, Ubuntu 20.04.3 LTS
* Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz, 2 cores, 6G, Ubuntu 20.04.3 LTS
* Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz, 2 cores, 6G, Ubuntu 20.04.3 LTS

I'm currently in the process of collecting more detailed information on our developers' machines.

Cross-posting our issue: https://github.com/deephaven/deephaven-core/issues/2038

Edits:
Updated reproducer against 17 by default.

**Comment by jerboaa** [comment]
@devinrsmith Is this reproducible without the jacoco agent? I see `-javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.7.jar_3a83c50b4a016f281c4e9f3500d16b55/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false` on the command line.

**Comment by devinrsmith** [comment]
Yep, that was my first thought too. It also reproduces without jacoco, some of the other error files show that.

**Comment by devinrsmith** [comment]
Please let me know if there is anything I can do wrt the `jbs:needs-report` label. It looks like only OpenJDK members are able to open bugs here https://bugs.openjdk.java.net/projects/JDK/?

Note: I have contributed to OpenJDK (signed OCA), https://github.com/openjdk/jdk/pull/7120, but it looks like that isn't the same level of access.

**Comment by karianna** [comment]
Correct, you need to be of author status.  I'll try to submit tomorrow.

**Comment by karianna** [comment]
https://bugs.openjdk.java.net/browse/JDK-8287432

**Comment by devinrsmith** [comment]
This has been fixed upstream. Hopefully we'll get a backport to 11 and 17. Thanks again for kicking off the process!
