### ISSUE TITLE
add-apt-repository has started failing for adoptium deb repository

### ISSUE THREAD

**Issue by Mark-Palmer-Imprivata** [adoptium/adoptium-support#520]
## Summary
We run the following command as part of our automated install/upgrade of JDK 17.
add-apt-repository --yes https://packages.adoptium.net/artifactory/deb

This was working.  Sometime in the last few weeks this has started to fail.

## Steps to reproduce
Run the add-apt-repository command as part of the following chain of commands.
1. curl -fsSL -o /tmp/adoptium-gpg-key https://packages.adoptium.net/artifactory/api/gpg/key/public
2. apt-key add /tmp/adoptium-gpg-key
3. add-apt-repository --yes https://packages.adoptium.net/artifactory/deb

## Expected results
This operation should succeed - it has been working for several weeks (since around mid-April).

## Actual results
This is what we see:
15:14:11.186 java.sh: ensuring https://packages.adoptium.net/artifactory/deb repo is installed...
Hit:1 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease
Hit:2 https://download.docker.com/linux/ubuntu bionic InRelease
Ign:3 http://ppa.launchpad.net/shutter/ppa/ubuntu bionic InRelease
**Err:4 http://ppa.launchpad.net/shutter/ppa/ubuntu bionic Release
  404  Not Found [IP: 185.125.190.52 80]**
Hit:5 https://cli.github.com/packages bionic InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:8 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bionic pgadmin4 InRelease
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic InRelease
Get:11 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:12 https://packages.adoptium.net/artifactory/deb bionic InRelease
Reading package lists... Done
**E: The repository 'http://ppa.launchpad.net/shutter/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.**
N: See apt-secure(8) manpage for repository creation and user configuration details.

To reiterate - this WAS working.

I have seen reports that a similar thing happened with the AdoptJDK repository, and I believe it was thought to be a JFrog issue.
How can we get past this problem?

## Triaging info

Java version: temurin-17

What is your operating system and platform?

This is being run on Ubuntu 18.05.6 and 20.04.1

How did you install Java?
Trying to install using the steps listed above.

Did it work before?
Yes.

Did you test with other Java versions?
Not applicable.

**Comment by karianna** [comment]
I'm unable to reproduce this using latest Ubuntu fully patched (20.04)

**Comment by gdams** [comment]
@Mark-Palmer-Imprivata can you please try with the instructions [here](https://adoptium.net/installation/linux/#_deb_installation_on_debian_or_ubuntu)

**Comment by Mark-Palmer-Imprivata** [comment]
@gdams That is how I worked around things with a single user and it worked.  Most of us have it installed the other way.  This is how AdoptJDK 15 was installed as well.  Are those instructions the only "supported" method of installation?  Would shifting from one form to the other cause problems with upgrades?
