### ISSUE TITLE
Adoptium OpenJDK 8u332b09 - Thrown EXCEPTION_INVALID_DISPOSITION when running in Windows

### ISSUE THREAD

**Issue by onionhead0708** [adoptium/adoptium-support#527]
## Summary
When using the Adoptium OpenJDK 8u332b09 to run jmxtrans program, fatal error EXCEPTION_INVALID_DISPOSITION found

The same program run with the same version of OpenJDK 8u332b09 provided by [OpenLogic](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=436&field_architecture_target_id=391&field_java_package_target_id=396) does not have this issue.

## Steps to reproduce

1. Download the https://repo1.maven.org/maven2/org/jmxtrans/jmxtrans/272/jmxtrans-272-all.jar file
2. Run the program with following command
```
SET JAVA_HOME=<path_of_adoptium_openjdk_8u332b09>
SET JRE_HOME=%JAVA_HOME%\jre
SET PATH=%JAVA_HOME%\bin
java -server -Djmxtrans.log.dir=logs -jar jmxtrans-272-all.jar -e -j . -s 10 -c false
```

## Expected results
The program can run successfully

## Actual results
Have following error and program exit
```
2022-06-14 15:03:40 [main] INFO  c.googlecode.jmxtrans.JmxTransformer - Starting Jmxtrans on : .
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_INVALID_DISPOSITION (0xc0000026) at pc=0x00007ff855735650, pid=6120, tid=0x0000000000002d60
#
# JRE version: OpenJDK Runtime Environment (8.0_332-b09) (build 1.8.0_332-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.332-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0xa5650]
#
# Core dump written. Default location: F:\test\jmxtrans\hs_err_pid6120.mdmp
#
# An error report file with more information is saved as:
# F:\test\jmxtrans\hs_err_pid6120.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Please also check the attached [hs_err_pid6120.log](https://github.com/adoptium/adoptium-support/files/8899986/hs_err_pid6120.log)

## Triaging info

Java version: 
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.332-b09, mixed mode)

What is your operating system and platform?
OS Name	Microsoft Windows Server 2016 Standard
Version	10.0.14393 Build 14393

How did you install Java?
Unzip the OpenJDK8U-jdk_x64_windows_hotspot_8u332b09.zip to a folder

Did it work before?
The program worked before and failed after switched to use the provided 8u332b09 JDK by adoptium

Did you test with other Java versions? 
Yes, tested with latest OpenJDK8U-jre_x64_windows_hotspot_2022-06-09-05-29.zip and have the same issue.

**Comment by karianna** [comment]
@onionhead0708 sorry for missing this sooner.  Can you try with the latest 8u345-b07 and let us know if it's still an issue?

**Comment by onionhead0708** [comment]
Dear @karianna , 

There is no 8u345-b07, the latest one from https://adoptium.net/temurin/releases/?version=8 is 8u345-b01
I have downloaded the 8u345-b01 and test, same error:

```
2022-09-16 15:04:20 [main] INFO  c.googlecode.jmxtrans.JmxTransformer - Starting Jmxtrans on : F:\CBX\jmxtrans\config
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_INVALID_DISPOSITION (0xc0000026) at pc=0x00007ffe362d54e0, pid=14924, tid=0x0000000000003a58
#
# JRE version: OpenJDK Runtime Environment (8.0_345-b01) (build 1.8.0_345-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.345-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0xa54e0]
#
# Core dump written. Default location: F:\CBX\jmxtrans\hs_err_pid14924.mdmp
#
# An error report file with more information is saved as:
# F:\CBX\jmxtrans\hs_err_pid14924.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by onionhead0708** [comment]
Just one more to mention, in the hs_err_pid14924.log file, there is following section: 
```
Internal exceptions (10 events):
Event: 0.312 .... <a 'java/security/PrivilegedActionException'> ...thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jvm.cpp, line 1524]
Event: 2.035 ... <a 'java/io/FileNotFoundException'> ... thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jni.cpp, line 711]
```
The windows server that i did the test does not have the J: drive and also doesn't have any jenkins folder

**Comment by karianna** [comment]
`name.pachler.nio.file.impl.Windows.CreateFile(Ljava/lang/String;IILname/pachler/nio/file/impl/Windows$SECURITY_ATTRIBUTES;IIJ)J+0` is causing the crash, are you able to post the source code snippet?

**Comment by onionhead0708** [comment]
Dear @karianna , 

I'm only the user of the jmxtrans.
But from the class and pom.xml of the jmxtrans/util/WatchDir:
https://github.com/jmxtrans/jmxtrans/blob/a826aa34885fd6bf600cfbe359f3bf4937c072f3/jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/util/WatchDir.java

Its using the library from net.sf.jpathwatch/jpathwatch:
`
		<dependency>
			<groupId>net.sf.jpathwatch</groupId>
			<artifactId>jpathwatch</artifactId>
		</dependency>
`

which i have checked the source from sourceforge:
https://sourceforge.net/p/jpathwatch/code/HEAD/tree/branches/0-95/jpathwatch/jpathwatch-java/src/name/pachler/nio/file/impl/Windows.java
`
	/**
	 * The Win32 CreateFile function. For detailed documentation, see
	 * <a href="http://msdn.microsoft.com/en-us/library/aa363858%28VS.85%29.aspx">MSDN</a>
	 * @param fileName	the file name to open
	 * @param desiredAccess
	 * @param shareMode
	 * @param securityAttributes	currently not supported, pass null in here.
	 * @param creationDisposition
	 * @param flagsAndAttributes
	 * @param templateFile	a handle to a template file
	 * @return a handle to the file
	 */
	static native long CreateFile(String fileName, int desiredAccess, int shareMode, SECURITY_ATTRIBUTES securityAttributes, int creationDisposition, int flagsAndAttributes, long templateFileHandle);

`
Its calling the native method and no problem when using JDK from [OpenLogic](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=436&field_architecture_target_id=391&field_java_package_target_id=396) but has this issue when using Adoptium JDK.

**Comment by karianna** [comment]
@onionhead0708 It may be the version of the VS DLL we built with.  If you try the latest 1.8.0_352 that goes back to a more broadly compatible DLL.

**Comment by onionhead0708** [comment]
@karianna 

Sadly, i used the latest 1.8.0_352 to try and the result is the same.

I downloaded the jmxtrans jar file from: 
https://repo1.maven.org/maven2/org/jmxtrans/jmxtrans/272/jmxtrans-272-all.jar

and run with following command line:
```
SET JAVA_HOME=D:\jdk8u352-b08
SET JRE_HOME=%JAVA_HOME%\jre
SET CLASSPATH=.;%JAVA_HOME%\lib;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
SET PATH=%JAVA_HOME%\bin

java -server -Djmxtrans.log.dir=logs -jar jmxtrans-272-all.jar -e -j . -s 10 -c false
```

Same exception:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_INVALID_DISPOSITION (0xc0000026) at pc=0x00007ffdc73354e0, pid=6824, tid=0x00000000000012bc
#
# JRE version: OpenJDK Runtime Environment (8.0_352-b08) (build 1.8.0_352-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.352-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0xa54e0]
#
# Core dump written. Default location: D:\jmxtrans\hs_err_pid6824.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Same internal exception: 
```
Internal exceptions (10 events):
Event: 0.109 Thread 0x000002c9023dd800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x00000000d5587cd8) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jni.cpp
Event: 0.110 Thread 0x000002c9023dd800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x00000000d5587fc0) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jni.cpp, line 4014]
Event: 0.200 Thread 0x000002c9023dd800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5701a58) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jvm.cpp, line 1514]
...
```

[hs_err_pid6824.log](https://github.com/adoptium/adoptium-support/files/10324184/hs_err_pid6824.log)

**Comment by karianna** [comment]
Can confirm this runs fine on Mac OS X, need to try on Windows.

**Comment by karianna** [comment]
Confirmed on Windows.

**Comment by karianna** [comment]
Fixed in latest nightly builds.  1.8.0_362 will be released next week.
