### ISSUE TITLE
EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363)

### ISSUE THREAD

**Issue by human1ty** [adoptium/adoptium-support#528]
## Summary
The EXCEPTION_UNCAUGHT_CXX_EXCEPTION returned on attempt to create JDBC connection

## Steps to reproduce
```
import jaydebeapi

token = '<your-personal-token>' # generated by the databricks
url = '<jdbc:spark://your-connection-string>'

jclassname = 'com.simba.spark.jdbc.Driver'
jdbc_name = 'spark'

# get this from https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/jdbc/2.6.22/SimbaSparkJDBC42-2.6.22.1040.zip
# place in the exec folder
jars = ['SparkJDBC42.jar']

conn = jaydebeapi.connect(jclassname=jclassname, url=url, driver_args=["token", token], jars=jars, libs=None)
```

## Expected results

JDBC connection created successfully

## Actual results

 JRE version: OpenJDK Runtime Environment Temurin-11.0.15+10 (11.0.15+10) (build 11.0.15+10)
 Java VM: OpenJDK 64-Bit Client VM Temurin-11.0.15+10 (11.0.15+10, mixed mode, serial gc, windows-amd64)
 Problematic frame:
 C  [KERNELBASE.dll+0x2d759]

[log.txt](https://github.com/adoptium/adoptium-support/files/8919393/log.txt)
## Triaging info

Java version:

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (buil
d 11.0.15+10, mixed mode)

What is your operating system and platform?

OS: Windows 10.0 , 64 bit Build 19041 (10.0.19041.662)

How did you install Java?

OpenJDK11U-jdk_x64_windows_hotspot_11.0.15_10.msi

Did it work before?
No

Did you test with other Java versions?

OpenJDK JAVA_VERSION="1.8.0_331"

**Comment by karianna** [comment]
Have you contacted support at the vendor: https://www.magnitude.com/drivers/spark-jdbc-odbc?
