### ISSUE TITLE
Windows 64 Version v2.0.11 crashes

### ISSUE THREAD

**Issue by drnathwani1** [adoptium/adoptium-support#531]
**What are you trying to do?**
Installed windows V2.0.11 and try to run 64 bit version as my laptop is 64 bit but it keeps on crashing. Tried to Run 32 bit which runs okay but once I finish one file on CNC, software doesn't respond anymore, i have tom shutdown. However 64 bit version keep on crashing all the time and generate following error file

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_STACK_OVERFLOW (0xc00000fd) at pc=0x6b99b8c9, pid=10096, tid=3376
#
# JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
# Java VM: OpenJDK Client VM (13.0.1+9, mixed mode, serial gc, windows-x86)
# Problematic frame:
# C  0x6b99b8c9
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Expected behaviour:**
it should run smoothly
**Observed behaviour:**
it keeps on crashing
**Any other comments:**

**Comment by gdams** [comment]
Java 13 is long out of support. Please can you try again with Java 17 https://adoptium.net/temurin/releases/?version=17 ?

**Comment by drnathwani1** [comment]
Installed Java 17 from a link you provided, worked first time but same thing, keep crashing. Screen stays up for 10 seconds and crashes.

**Comment by karianna** [comment]
What is this Windows 2.0.11 program?  Can you give us some more context?

**Comment by drnathwani1** [comment]
Yes it is 2.0.11 latest EGS version and using in windows 11. I run 64 bit version and it shuts down after 10-15 seconds. I couldn't locate error file anymore

**Comment by karianna** [comment]
Is that the Epic Game Store?  I don't know what EGS is :-)

**Comment by drnathwani1** [comment]
I am sorry, it was a typo.. Universal Gcode Sender  (UGS) software

**Comment by drnathwani1** [comment]
Sure thank you
