### ISSUE TITLE
Error when installing cassandra

### ISSUE THREAD

**Issue by smitpatel151** [adoptium/adoptium-support#532]
Microsoft Windows [Version 10.0.22000.739]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Smit>cd https://github.com/adoptium/adoptium-support/issues^Z
The filename, directory name, or volume label syntax is incorrect.

C:\Users\Smit>cd C:\Users\Smit\Downloads\apache-cassandra-3.11.13\bin

C:\Users\Smit\Downloads\apache-cassandra-3.11.13\bin>cassandra
Detected powershell execution permissions.  Running with enhanced startup scripts.
*---------------------------------------------------------------------*
*---------------------------------------------------------------------*

    WARNING!  Automatic page file configuration detected.
    It is recommended that you disable swap when running Cassandra
    for performance and stability reasons.

*---------------------------------------------------------------------*
*---------------------------------------------------------------------*
*---------------------------------------------------------------------*
*---------------------------------------------------------------------*

    WARNING! Detected a power profile other than High Performance.
    Performance of this node will suffer.
    Modify conf\cassandra.env.ps1 to suppress this warning.

*---------------------------------------------------------------------*
*---------------------------------------------------------------------*

C:\Users\Smit\Downloads\apache-cassandra-3.11.13\bin>CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.deserializeLargeSubset (Lorg/apache/cassandra/io/util/DataInputPlus;Lorg/apache/cassandra/db/Columns;I)Lorg/apache/cassandra/db/Columns;
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubset (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;ILorg/apache/cassandra/io/util/DataOutputPlus;)V
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubsetSize (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;I)I
CompilerOracle: dontinline org/apache/cassandra/db/commitlog/AbstractCommitLogSegmentManager.advanceAllocatingFrom (Lorg/apache/cassandra/db/commitlog/CommitLogSegment;)V
CompilerOracle: dontinline org/apache/cassandra/db/transform/BaseIterator.tryGetMoreContents ()Z
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stop ()V
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stopInPartition ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.doFlush (I)V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeExcessSlow ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeSlow (JI)V
CompilerOracle: dontinline org/apache/cassandra/io/util/RebufferingInputStream.readPrimitiveSlowly (I)J
CompilerOracle: inline org/apache/cassandra/db/rows/UnfilteredSerializer.serializeRowBody (Lorg/apache/cassandra/db/rows/Row;ILorg/apache/cassandra/db/SerializationHeader;Lorg/apache/cassandra/io/util/DataOutputPlus;)V
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.selectBoundary (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;II)I
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.strictnessOfLessThan (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;)I
CompilerOracle: inline org/apache/cassandra/utils/BloomFilter.indexes (Lorg/apache/cassandra/utils/IFilter/FilterKey;)[JCompilerOracle: inline org/apache/cassandra/utils/BloomFilter.setIndexes (JJIJ[J)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/vint/VIntCoding.encodeVInt (JI)[B
INFO  [main] 2022-06-22 10:44:50,438 YamlConfigurationLoader.java:93 - Configuration location: file:/C:/Users/Smit/Downloads/apache-cassandra-3.11.13/conf/cassandra.yaml
INFO  [main] 2022-06-22 10:44:50,876 Config.java:555 - Node configuration:[allocate_tokens_for_keyspace=null; allow_extra_insecure_udfs=false; allow_insecure_udfs=false; authenticator=AllowAllAuthenticator; authorizer=AllowAllAuthorizer; auto_bootstrap=true; auto_snapshot=true; back_pressure_enabled=false; back_pressure_strategy=org.apache.cassandra.net.RateBasedBackPressure{high_ratio=0.9, factor=5, flow=FAST}; batch_size_fail_threshold_in_kb=50; batch_size_warn_threshold_in_kb=5; batchlog_replay_throttle_in_kb=1024; broadcast_address=null; broadcast_rpc_address=null; buffer_pool_use_heap_if_exhausted=true; cache_load_timeout_seconds=30; cas_contention_timeout_in_ms=1000; cdc_enabled=false; cdc_free_space_check_interval_ms=250; cdc_raw_directory=null; cdc_total_space_in_mb=0; check_for_duplicate_rows_during_compaction=true; check_for_duplicate_rows_during_reads=true; client_encryption_options=<REDACTED>; cluster_name=Test Cluster; column_index_cache_size_in_kb=2; column_index_size_in_kb=64; commit_failure_policy=stop; commitlog_compression=null; commitlog_directory=null; commitlog_max_compression_buffers_in_pool=3; commitlog_periodic_queue_size=-1; commitlog_segment_size_in_mb=32; commitlog_sync=periodic; commitlog_sync_batch_window_in_ms=NaN; commitlog_sync_period_in_ms=10000; commitlog_total_space_in_mb=null; compaction_large_partition_warning_threshold_mb=100; compaction_throughput_mb_per_sec=16; concurrent_compactors=null; concurrent_counter_writes=32; concurrent_materialized_view_writes=32; concurrent_reads=32; concurrent_replicates=null; concurrent_writes=32; counter_cache_keys_to_save=2147483647; counter_cache_save_period=7200; counter_cache_size_in_mb=null; counter_write_request_timeout_in_ms=5000; credentials_cache_max_entries=1000; credentials_update_interval_in_ms=-1; credentials_validity_in_ms=2000; cross_node_timeout=false; data_file_directories=[Ljava.lang.String;@7d3a22a9; disk_access_mode=auto; disk_failure_policy=stop; disk_optimization_estimate_percentile=0.95; disk_optimization_page_cross_chance=0.1; disk_optimization_strategy=ssd; dynamic_snitch=true; dynamic_snitch_badness_threshold=0.1; dynamic_snitch_reset_interval_in_ms=600000; dynamic_snitch_update_interval_in_ms=100; enable_drop_compact_storage=false; enable_materialized_views=true; enable_sasi_indexes=true; enable_scripted_user_defined_functions=false; enable_user_defined_functions=false; enable_user_defined_functions_threads=true; encryption_options=<REDACTED>; endpoint_snitch=SimpleSnitch; file_cache_round_up=null; file_cache_size_in_mb=null; force_new_prepared_statement_behaviour=false; gc_log_threshold_in_ms=200; gc_warn_threshold_in_ms=1000; hinted_handoff_disabled_datacenters=[]; hinted_handoff_enabled=true; hinted_handoff_throttle_in_kb=1024; hints_compression=null; hints_directory=null; hints_flush_period_in_ms=10000; incremental_backups=false; index_interval=null; index_summary_capacity_in_mb=null; index_summary_resize_interval_in_minutes=60; initial_token=null; inter_dc_stream_throughput_outbound_megabits_per_sec=200; inter_dc_tcp_nodelay=false; internode_authenticator=null; internode_compression=dc; internode_recv_buff_size_in_bytes=0; internode_send_buff_size_in_bytes=0; key_cache_keys_to_save=2147483647; key_cache_save_period=14400; key_cache_size_in_mb=null; listen_address=localhost; listen_interface=null; listen_interface_prefer_ipv6=false; listen_on_broadcast_address=false; max_hint_window_in_ms=10800000; max_hints_delivery_threads=2; max_hints_file_size_in_mb=128; max_mutation_size_in_kb=null; max_streaming_retries=3; max_value_size_in_mb=256; memtable_allocation_type=heap_buffers; memtable_cleanup_threshold=null; memtable_flush_writers=0; memtable_heap_space_in_mb=null; memtable_offheap_space_in_mb=null; min_free_space_per_drive_in_mb=50; native_transport_flush_in_batches_legacy=true; native_transport_max_concurrent_connections=-1; native_transport_max_concurrent_connections_per_ip=-1; native_transport_max_concurrent_requests_in_bytes=-1; native_transport_max_concurrent_requests_in_bytes_per_ip=-1; native_transport_max_frame_size_in_mb=256; native_transport_max_negotiable_protocol_version=-2147483648; native_transport_max_threads=128; native_transport_port=9042; native_transport_port_ssl=null; num_tokens=256; otc_backlog_expiration_interval_ms=200; otc_coalescing_enough_coalesced_messages=8; otc_coalescing_strategy=DISABLED; otc_coalescing_window_us=200; partitioner=org.apache.cassandra.dht.Murmur3Partitioner; permissions_cache_max_entries=1000; permissions_update_interval_in_ms=-1; permissions_validity_in_ms=2000; phi_convict_threshold=8.0; prepared_statements_cache_size_mb=null; range_request_timeout_in_ms=10000; read_request_timeout_in_ms=5000; repair_session_max_tree_depth=18; request_scheduler=org.apache.cassandra.scheduler.NoScheduler; request_scheduler_id=null; request_scheduler_options=null; request_timeout_in_ms=10000; role_manager=CassandraRoleManager; roles_cache_max_entries=1000; roles_update_interval_in_ms=-1; roles_validity_in_ms=2000; row_cache_class_name=org.apache.cassandra.cache.OHCProvider; row_cache_keys_to_save=2147483647; row_cache_save_period=0; row_cache_size_in_mb=0; rpc_address=localhost; rpc_interface=null; rpc_interface_prefer_ipv6=false; rpc_keepalive=true; rpc_listen_backlog=50; rpc_max_threads=2147483647; rpc_min_threads=16; rpc_port=9160; rpc_recv_buff_size_in_bytes=null; rpc_send_buff_size_in_bytes=null; rpc_server_type=sync; saved_caches_directory=null; seed_provider=org.apache.cassandra.locator.SimpleSeedProvider{seeds=127.0.0.1}; server_encryption_options=<REDACTED>; slow_query_log_timeout_in_ms=500; snapshot_before_compaction=false; snapshot_on_duplicate_row_detection=false; ssl_storage_port=7001; sstable_preemptive_open_interval_in_mb=50; start_native_transport=true; start_rpc=false; storage_port=7000; stream_throughput_outbound_megabits_per_sec=200; streaming_keep_alive_period_in_secs=300; streaming_socket_timeout_in_ms=86400000; thrift_framed_transport_size_in_mb=15; thrift_max_message_length_in_mb=16; thrift_prepared_statements_cache_size_mb=null; tombstone_failure_threshold=100000; tombstone_warn_threshold=1000; tracetype_query_ttl=86400; tracetype_repair_ttl=604800; transparent_data_encryption_options=org.apache.cassandra.config.TransparentDataEncryptionOptions@1d082e88; trickle_fsync=false; trickle_fsync_interval_in_kb=10240; truncate_request_timeout_in_ms=60000; unlogged_batch_across_partitions_warn_threshold=10; user_defined_function_fail_timeout=1500; user_defined_function_warn_timeout=500; user_function_timeout_policy=die; windows_timer_interval=1; write_request_timeout_in_ms=2000]
INFO  [main] 2022-06-22 10:44:50,882 DatabaseDescriptor.java:381 - DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  [main] 2022-06-22 10:44:50,885 DatabaseDescriptor.java:439 - Global memtable on-heap threshold is enabled at 1004MB
INFO  [main] 2022-06-22 10:44:50,886 DatabaseDescriptor.java:443 - Global memtable off-heap threshold is enabled at 1004MB
INFO  [main] 2022-06-22 10:44:51,099 RateBasedBackPressure.java:123 - Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 2000.
INFO  [main] 2022-06-22 10:44:51,099 DatabaseDescriptor.java:781 - Back-pressure is disabled with strategy org.apache.cassandra.net.RateBasedBackPressure{high_ratio=0.9, factor=5, flow=FAST}.
INFO  [main] 2022-06-22 10:44:51,301 JMXServerUtils.java:253 - Configured JMX server at: service:jmx:rmi://127.0.0.1/jndi/rmi://127.0.0.1:7199/jmxrmi
INFO  [main] 2022-06-22 10:44:51,312 CassandraDaemon.java:490 - Hostname: DESKTOP-V1B6822
INFO  [main] 2022-06-22 10:44:51,312 CassandraDaemon.java:497 - JVM vendor/version: OpenJDK 64-Bit Server VM/1.8.0_332
INFO  [main] 2022-06-22 10:44:51,315 CassandraDaemon.java:498 - Heap size: 3.922GiB/3.922GiB
INFO  [main] 2022-06-22 10:44:51,316 CassandraDaemon.java:503 - Code Cache Non-heap memory: init = 2555904(2496K) used = 4890752(4776K) committed = 4915200(4800K) max = 251658240(245760K)
INFO  [main] 2022-06-22 10:44:51,317 CassandraDaemon.java:503 - Metaspace Non-heap memory: init = 0(0K) used = 20143224(19671K) committed = 20709376(20224K) max = -1(-1K)
INFO  [main] 2022-06-22 10:44:51,317 CassandraDaemon.java:503 - Compressed Class Space Non-heap memory: init = 0(0K) used = 2396584(2340K) committed = 2621440(2560K) max = 1073741824(1048576K)
INFO  [main] 2022-06-22 10:44:51,318 CassandraDaemon.java:503 - Par Eden Space Heap memory: init = 671088640(655360K) used = 147647672(144187K) committed = 671088640(655360K) max = 671088640(655360K)
INFO  [main] 2022-06-22 10:44:51,319 CassandraDaemon.java:503 - Par Survivor Space Heap memory: init = 83886080(81920K) used = 0(0K) committed = 83886080(81920K) max = 83886080(81920K)
INFO  [main] 2022-06-22 10:44:51,320 CassandraDaemon.java:503 - CMS Old Gen Heap memory: init = 3456106496(3375104K) used = 0(0K) committed = 3456106496(3375104K) max = 3456106496(3375104K)
INFO  [main] 2022-06-22 10:44:51,321 CassandraDaemon.java:505 - Classpath: C:\Users\Smit\Downloads\apache-cassandra-3.11.13\conf;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/airline-0.6.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/antlr-runtime-3.5.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/apache-cassandra-3.11.13.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/apache-cassandra-thrift-3.11.13.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/asm-5.0.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/caffeine-2.2.6.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/cassandra-driver-core-3.0.1-shaded.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/commons-cli-1.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/commons-codec-1.9.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/commons-lang3-3.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/commons-math3-3.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/compress-lzf-0.8.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/concurrent-trees-2.4.0.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/concurrentlinkedhashmap-lru-1.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/disruptor-3.0.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/ecj-4.4.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/guava-18.0.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/HdrHistogram-2.1.9.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/high-scale-lib-1.0.6.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/hppc-0.5.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jackson-annotations-2.13.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jackson-core-2.13.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jackson-databind-2.13.2.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jamm-0.3.0.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/javax.inject-1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jbcrypt-0.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jcl-over-slf4j-1.7.25.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jctools-core-1.2.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jflex-1.6.0.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/jna-4.2.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/joda-time-2.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/json-simple-1.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/libthrift-0.9.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/log4j-over-slf4j-1.7.25.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/logback-classic-1.2.9.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/logback-core-1.2.9.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/lz4-1.3.0.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/metrics-core-3.1.5.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/metrics-jvm-3.1.5.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/metrics-logback-3.1.5.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/netty-all-4.0.44.Final.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/ohc-core-0.4.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/ohc-core-j8-0.4.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/reporter-config-base-3.0.3.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/reporter-config3-3.0.3.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/sigar-1.6.4.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/slf4j-api-1.7.25.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/snakeyaml-1.26.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/snappy-java-1.1.1.7.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/snowball-stemmer-1.3.0.581.1.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/ST4-4.0.8.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/stream-2.5.2.jar;C:/Users/Smit/Downloads/apache-cassandra-3.11.13/lib/thrift-server-0.3.7.jar;C:\Users\Smit\Downloads\apache-cassandra-3.11.13\build\classes\main;C:\Users\Smit\Downloads\apache-cassandra-3.11.13\build\classes\thrift;C:\Users\Smit\Downloads\apache-cassandra-3.11.13\lib\jamm-0.3.0.jar
INFO  [main] 2022-06-22 10:44:51,326 CassandraDaemon.java:507 - JVM Arguments: [-Dcassandra, -Dlogback.configurationFile=logback.xml, -Dcassandra.logdir=C:\Users\Smit\Downloads\apache-cassandra-3.11.13\logs, -Dcassandra.storagedir=C:\Users\Smit\Downloads\apache-cassandra-3.11.13\data, -Xloggc:C:\Users\Smit\Downloads\apache-cassandra-3.11.13/logs/gc.log, -ea, -XX:+UseThreadPriorities, -XX:ThreadPriorityPolicy=42, -XX:+HeapDumpOnOutOfMemoryError, -Xss256k, -XX:StringTableSize=1000003, -XX:+AlwaysPreTouch, -XX:-UseBiasedLocking, -XX:+UseTLAB, -XX:+ResizeTLAB, -XX:+UseNUMA, -XX:+PerfDisableSharedMem, -Djava.net.preferIPv4Stack=true, -XX:+UseParNewGC, -XX:+UseConcMarkSweepGC, -XX:+CMSParallelRemarkEnabled, -XX:SurvivorRatio=8, -XX:MaxTenuringThreshold=1, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:CMSWaitDuration=10000, -XX:+CMSParallelInitialMarkEnabled, -XX:+CMSEdenChunksRecordAlways, -XX:+CMSClassUnloadingEnabled, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintHeapAtGC, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -XX:+PrintPromotionFailure, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=10, -XX:GCLogFileSize=10M, -Xms4096M, -Xmx4096M, -Xmn800M, -XX:+UseCondCardMark, -Djava.library.path=C:\Users\Smit\Downloads\apache-cassandra-3.11.13\lib\sigar-bin, -XX:CompileCommandFile=C:\Users\Smit\Downloads\apache-cassandra-3.11.13\conf\hotspot_compiler, -javaagent:C:\Users\Smit\Downloads\apache-cassandra-3.11.13\lib\jamm-0.3.0.jar, -XX:OnOutOfMemoryError=taskkill /F /PID %p, -Dcassandra.jmx.local.port=7199]
WARN  [main] 2022-06-22 10:44:51,341 StartupChecks.java:169 - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
INFO  [main] 2022-06-22 10:44:51,347 SigarLibrary.java:44 - Initializing SIGAR library
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000010014ed4, pid=18016, tid=0x0000000000008340
#
# JRE version: OpenJDK Runtime Environment (8.0_332-b09) (build 1.8.0_332-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.332-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [sigar-amd64-winnt.dll+0x14ed4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Smit\Downloads\apache-cassandra-3.11.13\bin\hs_err_pid18016.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by karianna** [comment]
@smitpatel151 Are you able to send that crash log?

**Comment by smitpatel151** [comment]
Hello Adoptium/Adoptium-Support,
Thanks for responding,

I have successfully installed installed the cassandra.

Thanks & Regards
Smit Patel
