### ISSUE TITLE
Gaiasky crashes on Window 8.1

### ISSUE THREAD

**Issue by Rolandwolf** [adoptium/adoptium-support#533]
yes

## Summary
Command Line: -Xms2g -Xmx6g -Dassets.location=. -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.showThreadName=false 

gaiasky.desktop.GaiaSkyDesktop

Host: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz, 8 cores, 11G,  Windows 8.1 , 64 bit Build 9600 (6.3.9600.20389)
Time: Wed Jun 22 22:01:39 2022 Mitteleuropäische Sommerzeit elapsed time: 45.319197 seconds (0d 0h 0m 45s)
Installation was without problems. Starting with Button Start Gaia Sky works fine, but at a cerrtain point the Gaiasky Window closes without any message

## Steps to reproduce
Starting over and over is always the same behavior: crash during the start procedure

## Triaging info

Java version: 6.0.210

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

[hs_err_pid12552.log](https://github.com/adoptium/adoptium-support/files/8964249/hs_err_pid12552.log)
[hs_err_pid5976.log](https://github.com/adoptium/adoptium-support/files/8964250/hs_err_pid5976.log)

**Comment by karianna** [comment]
Hi there, this program is using an old version of Java 17.  Please upgrade to 17.0.3 from adoptium.net and try again.
