### ISSUE TITLE
v-11.0.15 CFBundleIdentifier Collision on submitted to App Store

### ISSUE THREAD

**Issue by Saibion** [adoptium/adoptium-support#543]
Version: 11.0.15 as packaged by JustJ
OS: macOS 12.4
Application: Eclipse RCP Equiniox build Eclipse 4.22 Maven/Tyco 2.3.0
Relevant Build Feature: org.eclipse.justj.openjdk.hotspot.jre.full_11.0.15.v20220515-1236

Hello,

Thanks for being who you are. It is appreciated.
I first approached Eclipse JustJ forum with this issue. They suggested that I ask the question here. The issue occurs when attempting to upload a .app that contains an embedded openJRE. Apple App Store requires that each application contain a unique Bundle Identifier in any plist contained in the application. The bundle Identifier is then associated to a single application version. The embedded jre contains plist in its binary executables. In the case of the jre that I'm referencing the following executables java, jdb, jrunscript. keytool, rmid and rmiregistry all are rejected by App Store Connect with the following message: ITMS-90511: CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'net.java.openjdk.cmd' of '[name of file]' is already in use by another application. 
The issue is reported for other files, I have included a file Rejection List that also reports invalid signatures: ITMS-90238: Invalid Signature - The executable at path .../COR•REC™.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_11.0.15.v20220515-1236/jre/bin/javadoc: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s).

The COR•REC™.app in question is fully signed and notarize with entitlements that include: com.apple.security.app-sandbox. It passes Apples App Store Connect code validation.

Any advice on how I might correct these issues will be greatly appreciated. Thanks for taking the time to read and consider my question.

Ralph
[Rejection List.txt](https://github.com/adoptium/adoptium-support/files/9104365/Rejection.List.txt)
h

**Comment by karianna** [comment]
@Saibion apologies for not replying to this sooner.  Are you able to try again with the latest 11.0.16.1 and see if the error still persists?

**Comment by Saibion** [comment]
I was able to get it passed using 11.0.16.1 along with changing the Info.plist CFBundleIdentifier value of the following: rmiregistry, rmid, pack200, keytool, jrunscript, jfr, java, jaotc and jspawnhelper

**Comment by karianna** [comment]
One for @gdams to check when he gets back

**Comment by kerner1000** [comment]
> I was able to get it passed using 11.0.16.1 along with changing the Info.plist CFBundleIdentifier value of the following: rmiregistry, rmid, pack200, keytool, jrunscript, jfr, java, jaotc and jspawnhelper

Hi @Saibion great you figured this out. Currently, I build a JRE by myself to solve this issue. Did you find a better way?

**Comment by Saibion** [comment]
I certainly wouldn't label it a "better way" I directly edit the CFBundleIdentifier within the executables. Then pass the executables to the current build.

**Comment by Saibion** [comment]
The difference maybe that I also resign and set entitlements of the binaries which goes something like this:
# Sign JRE/BIN
for FILE in "$JRE/$BIN/"*;
    do
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC (APA8BXUFB2)" $FILE;
    done

echo "\n------------------> JRE/LIB Code sign and set entitlements of Directory and Orphans\n"
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC ()" "$JRE/$LIB/jspawnhelper";
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC ()" "$JRE/$LIB/jli/libjli.dylib";
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC ()" "$JRE/$LIB/server/libjsig.dylib";
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC ()" "$JRE/$LIB/server/libjvm.dylib";

ls "$JRE/$LIB"
for DYLIB in "$JRE/$LIB/"*.dylib;
    do
    codesign --force --entitlements "entitlements.plist" --options runtime --timestamp --sign "3rd Party Mac Developer Application: CORGROUP LLC ()" $DYLIB;
    done
#end java signing

**Comment by kerner1000** [comment]
Yes, you are right, the crucial part is the (re-)signing the code. Probably I am doing something wrong here. It's really a mess to get an app to the App store..

**Comment by Saibion** [comment]
It gets worse - I'm now prevented from publishing to the App Store do to a problem with SWT

**Comment by karianna** [comment]
Please raise any furthe rissues with JustJ binaries at: https://www.eclipse.org/justj/?page=support
