### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by CedanoAngel** [adoptium/adoptium-support#545]
### Please provide a brief summary of the bug

Minecraft FTB Revelations. Game crashes before loading, ran fine for 3 weeks. Re-installed mod, re-installed GPU driver. no luck.

### Please provide steps to reproduce where possible

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006a3a0f40, pid=14160, tid=0x0000000000002d10
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x90f40]
#
# Failed to write core dump. Minid
umps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues

VM Arguments:
jvm_args: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\losan\AppData\Local\.ftba\bin\versions\1.12.2-forge-14.23.5.2858\1.12.2-forge-14.23.5.2858-natives-1230985699000 -Dminecraft.launcher.brand=FTBApp -Dminecraft.launcher.version=202206081143-2e021f8e74-release -Dminecraft.client.jar=C:\Users\losan\AppData\Local\.ftba\bin\versions\1.12.2-forge-14.23.5.2858\1.12.2-forge-14.23.5.2858.jar -Dmt.disablechat=true -Dchtray.port=59950 -Dchtray.instance=8c8c00bf-fe7f-422a-b4cf-e1cc67e7da4c -javaagent:log4jfixer.jar -Xmx12288M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 
java_command: net.minecraft.launchwrapper.Launch --username KalmZAztec --version 1.12.2-forge-14.23.5.2858 --gameDir C:\Users\losan\AppData\Local\.ftba\instances\8c8c00bf-fe7f-422a-b4cf-e1cc67e7da4c --assetsDir C:\Users\losan\AppData\Local\.ftba\bin\assets --assetIndex 1.12 --uuid 65fe6e4b-321e-427c-9b04-4f60cc6c096b --accessToken eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzMzI3NDk5NjMyNDkyNCIsImFnZyI6IkFkdWx0Iiwic3ViIjoiZWZlMTViNzQtMzBmYy00NjM2LWI1M2YtNTJkNzY5ZmQyNmNjIiwibmJmIjoxNjU4MDMzMzg3LCJhdXRoIjoiWEJPWCIsInJvbGVzIjpbXSwiaXNzIjoiYXV0aGVudGljYXRpb24iLCJleHAiOjE2NTgxMTk3ODcsImlhdCI6MTY1ODAzMzM4NywicGxhdGZvcm0iOiJQQ19MQVVOQ0hFUiIsInl1aWQiOiI3NTg0YjVhZTJiMjQ0ZDExOTRjY2M3NDA1NzI5YjFiMyJ9.gPrjr99-9r4mKJsZ4pse_WNbOTTuSyMgKILrUiqir7A --userType msa --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge --width 1720 --height 840
java_class_path (initial): C:\Users\losan\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2858\forge-1.12.2-14.23.5.2858.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-debug-all\5.2\asm-debug-all-5.2.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2_mc\scala-continuations-library_2.11-1.0.2_mc.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2_mc\scala-continuations-plugin_2.11.1-1.0.2_mc.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\losan\AppData\Local\.ftba\bin\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\losan\AppData\Lo
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\losan\AppData\Local\Microsoft\WindowsApps;
USERNAME=losan
OS=Windows_NT
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 22000 (10.0.22000.708)

CPU:total 12 (initial active 12) (12 cores per cpu, 1 threads per core) family 23 model 1 stepping 1, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, mmxext, 3dnowpref, lzcnt, sse4a, tsc, tscinvbit, tscinv, bmi1

Memory: 4k page, physical 33507124k(16089848k free), swap 46614324k(23264756k free)

vm_info: OpenJDK 64-Bit Server VM (25.312-b07) for windows-amd64 JRE (1.8.0_312-b07), built on Oct 19 2021 15:47:56 by "jenkins" with MS VC++ 12.0 (VS2013)

time: Sat Jul 16 22:37:21 2022
timezone: Pacific Daylight Time
elapsed time: 204.402749 seconds (0d 0h 3m 24s)

### Expected Results

Game to Run

### Actual Results

Game Crashed

### What Java Version are you using?

java version "1.8.0_333"

### What is your operating system and platform?

Microsoft Windows 11 Pro

### How did you install Java?

https://www.java.com/download/ie_manual.jsp

### Did it work before?

```shell
Yes
```

### Did you test with other Java versions?

```shell
no
```

**Comment by karianna** [comment]
Can you try 1.8.0_332 and let us know the result?  We note that the official Minecraft Java Edition comes with 17.0.3 from Microsoft these days.

**Comment by CedanoAngel** [comment]
> Can you try 1.8.0_332 and let us know the result? We note that the official Minecraft Java Edition comes with 17.0.3 from Microsoft these days.

Thats the part I'm confused on. I have java version "1.8.0_333" but I see application is running "JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)" should I revert update to 1.8.0_332? or do I need to fix this in the directory?

**Comment by CedanoAngel** [comment]
> Oh hang on - I see you have also installed Oracle's JDK.
> 
> `PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Users\losan\AppData\Local\Microsoft\WindowsApps;`
> 
> I'd recommend temporarily removing the `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;` bit in your path and trying again.

@karianna Awesome! game is working great. thanks!
