### ISSUE TITLE
Windows binary ZIPs missing for 17.0.4+8

### ISSUE THREAD

**Issue by dhs-rec** [adoptium/adoptium-support#549]
### Please provide a brief summary of the bug

The releases page lists an MSI (`OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.msi`), but no `OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.zip`. Instead there's two times `OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.zip.json`. It's also not possible to download the ZIP (with `wget`, for example) by copying the URL of the MSI and changing the extension.

See https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.4%2B8

### Please provide steps to reproduce where possible

```
% wget 'https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.zip' 
--2022-07-22 12:00:06--  https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-22 12:00:06 ERROR 404: Not Found.
```

### Expected Results

The ZIP should have been downloaded, just like the MSI.

### Actual Results

See above

### What Java Version are you using?

Not relevant here

### What is your operating system and platform?

Not relevant here

### How did you install Java?

Not relevant here

### Did it work before?

```shell
Yes. Windows ZIPs for older releases are listed and downloadable.
```

### Did you test with other Java versions?

```shell
Not relevant here
```

### Relevant log output

```shell
Not relevant here
```

**Comment by sophia-guo** [comment]
@dhs-rec could you try again? I have re-uploaded it and it works for me.

**Comment by dhs-rec** [comment]
Yes, works now. Thanks a lot for the fast resolution!
