### ISSUE TITLE
G1ParScanThreadState:: error

### ISSUE THREAD

**Issue by mlevine-active** [adoptium/adoptium-support#550]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb1531d2d55, pid=9928, tid=0x00007fb151afc700
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x5b3d55]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x35
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[hs_err_pid9928.log](https://github.com/adoptium/adoptium-support/files/9175926/hs_err_pid9928.log)

#
# An error report file with more information is saved as:
# /tmp/hs_err_pid9928.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues

### Please provide steps to reproduce where possible

We have many runtime environments runnning the same versions of tomcat and  java - have only seen this one instance

### Expected Results

it doesn't crash

### Actual Results

it crashed

### What Java Version are you using?

build 1.8.0_292-b10

### What is your operating system and platform?

cento7 7  3.10.0-1160.66.1.el7.x86_64

### How did you install Java?

archive

### Did it work before?

```shell
yes - it was a runtime crash
```

### Did you test with other Java versions?

```shell
we know we should upgrade but have not sen any other issues.
```

### Relevant log output

```shell
log was attached above
```

**Comment by karianna** [comment]
@mlevine-active please update to the adoptium.net build 1.8.0_342 and reopen if this still exists.
