### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by amuchoudhary** [adoptium/adoptium-support#552]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd0d7534fb4, pid=2465958, tid=2493448
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.14.1+1 (11.0.14.1+1) (build 11.0.14.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (11.0.14.1+1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x4ffb4]  _IO_vfprintf+0x44
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/username/core.2465958)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

This happens to crash the service very randomly without any proper errors. I tried to find the possible reasons behind this but no clue. Can someone please suggest some possible reasons and debugging that can be done to resolve this ?

### Please provide steps to reproduce where possible

I am not very sure how this error pops up. We have hs2 service which crashes very randomly.

### Expected Results

The service should be working fine without this error

### Actual Results

The service is crashing very randomly leaving this log in users home directory.

### What Java Version are you using?

openjdk 11.0.14.1 2022-02-08 OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

### What is your operating system and platform?

Red Hat Enterprise Linux release 8.5 (Ootpa)

### How did you install Java?

tar.gz file was used to install java

### Did it work before?

```shell
Yes, it was working fine till JAVA 8 but after upgrading to java 11 this started popping up
```

### Did you test with other Java versions?

```shell
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

### Relevant log output

```shell
Stack: [0x00007fd0796f7000,0x00007fd0797f8000],  sp=0x00007fd0797f2ad0,  free space=1006k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x4ffb4]  _IO_vfprintf+0x44
C  [libc.so.6+0x58dc8]  _IO_fprintf+0x98
C  [libjpam.so+0x15c4]  Java_net_sf_jpam_Pam_authenticate+0x3c7
j  net.sf.jpam.Pam.authenticate(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I+0
j  net.sf.jpam.Pam.authenticate(Ljava/lang/String;Ljava/lang/String;)Lnet/sf/jpam/PamReturnValue;+97
j  net.sf.jpam.jaas.JpamLoginModule.login()Z+183
j  javax.security.auth.login.LoginContext.invoke(Ljava/lang/String;)V+617 java.base@11.0.14.1
j  javax.security.auth.login.LoginContext$4.run()Ljava/lang/Void;+8 java.base@11.0.14.1
j  javax.security.auth.login.LoginContext$4.run()Ljava/lang/Object;+1 java.base@11.0.14.1
v  ~StubRoutines::call_stub
V  [libjvm.so+0x8d592b]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x39b
V  [libjvm.so+0x98cbd4]  JVM_DoPrivileged+0x534
J 421  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; java.base@11.0.14.1 (0 bytes) @ 0x00007fd0c0321028 [0x00007fd0c0320f40+0x00000000000000e8]
j  javax.security.auth.login.LoginContext.invokePriv(Ljava/lang/String;)V+13 java.base@11.0.14.1
j  javax.security.auth.login.LoginContext.login()V+26 java.base@11.0.14.1
j  com.mapr.login.PasswordAuthentication.authenticate(Ljava/lang/String;Ljava/lang/String;)Z+20
j  org.apache.hive.service.auth.PamAuthenticationProviderImpl.Authenticate(Ljava/lang/String;Ljava/lang/String;)V+12
j  org.apache.hive.service.auth.PlainSaslHelper$PlainServerCallbackHandler.handle([Ljavax/security/auth/callback/Callback;)V+134
j  org.apache.hive.service.auth.PlainSaslServer.evaluateResponse([B)[B+308
```

**Comment by karianna** [comment]
@amuchoudhary can you try the most recent 11.0.16 and report back here?

**Comment by amuchoudhary** [comment]
Hi Matijn,
Same response with Java 11.0.16+8.
Crashes with exactly same issue.
