### ISSUE TITLE
JDK 8u342 for Windows lacks `vcruntime140.dll`

### ISSUE THREAD

**Issue by ppkarwasz** [adoptium/adoptium-support#553]
### Please provide a brief summary of the bug

Version 8u342 of JDK 8 for Windows contains a file named `vcrunt~1.dll` instead of `vcruntime140.dll` in both the `bin` and `jre/bin` directories.

This prevents the JVM from starting on systems that lack the _"Microsoft Visual C++ 2015-2022 Redistributable"_.

### Please provide steps to reproduce where possible

On a system **without** the _"Microsoft Visual C++ 2015-2022 Redistributable"_ run `java.exe -version`.

Since my dev system has a file named `C:\Windows\System32\vcruntime140.dll` I renamed it temporarily and set the `Path` environment variable to an empty string.

### Expected Results

```
C:\Program Files\Eclipse Adoptium\jdk-8.0.342.7-hotspot\bin>java.exe -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.342-b07, mixed mode)
```

### Actual Results

```
C:\Program Files\Eclipse Adoptium\jdk-8.0.342.7-hotspot\bin>java.exe -version
Error: loading: C:\Program Files\Eclipse Adoptium\jdk-8.0.342.7-hotspot\jre\bin\msvcp140.dll
Error: loading: C:\Program Files\Eclipse Adoptium\jdk-8.0.342.7-hotspot\jre\bin\server\jvm.dll
```

### What Java Version are you using?

openjdk version "1.8.0_342" OpenJDK Runtime Environment (Temurin)(build 1.8.0_342-b07) OpenJDK 64-Bit Server VM (Temurin)(build 25.342-b07, mixed mode)

### What is your operating system and platform?

Windows 10 21H2

### How did you install Java?

I used the MSI installer, but the ZIP file is also affected.

### Did it work before?

```shell
Previous JDK 8 versions use an older MS VS runtime (version 12.0) and work correctly.
```

### Did you test with other Java versions?

```shell
The upstream build uses an older MS VS runtime (version 10.0) and works correctly.

Other Adoptium releases using MS VS version 14.0 are not affected (latest JDK 11, 17, 18).
```

**Comment by karianna** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2208/ respin

**Comment by ppkarwasz** [comment]
The [latest build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-temurin/) looks OK, thanks.
