### ISSUE TITLE
JDK 17 fails to install on Ubuntu 20.04 on bare metal

### ISSUE THREAD

**Issue by Mark-Palmer-Imprivata** [adoptium/adoptium-support#555]
### Please provide a brief summary of the bug

Attempted to install JDK 17 on a bare metal Ubuntu 20.04 machine following the standard instructions and it fails.
Instructions:  https://adoptium.net/installation/linux/
Failure:
Err:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-17-jdk amd64 17.0.4.0.0+8
  403 Forbidden [IP: ...]
E: Failed to fetch https://(long url hosted at cloudfront.net)  403 Forbidden
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### Please provide steps to reproduce where possible

Just follow the standard instructions:  https://adoptium.net/installation/linux/

### Expected Results

Expected JDK 17 to be installed.

### Actual Results

Got the following failure message:
Err:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-17-jdk amd64 17.0.4.0.0+8
  403 Forbidden [IP: ...]
E: Failed to fetch https://(long url hosted at cloudfront.net)  403 Forbidden
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### What Java Version are you using?

17.0.4

### What is your operating system and platform?

Ubuntu 20.04

### How did you install Java?

Following these instructions:  https://adoptium.net/installation/linux/

### Did it work before?

```shell
This installs on Ubuntu VMs.  However, something interesting.  I have a VM that has 17.0.3 installed.  I attempted to upgrade it to 17.0.4, and it claims 17.0.3 is the latest release available and it is already installed.  You can see in the error above that 17.0.4 is the version that seems to be automatically selected for installation on the bare metal machine.

A difference that I noticed that may be related.  On the VM, /etc/apt/sources.list.d/adoptium.list contains the following:
deb https://packages.adoptium.net/artifactory/deb focal main

In the error above, you can see the following during the install attempt:
https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-17-jdk amd64 17.0.4.0.0+8

Why is this appearing differently on the bare metal system?

Also, why is the 17.0.4 version not being seen by the Ubuntu VM I have when trying to upgrade?
```

### Did you test with other Java versions?

```shell
This seems to be a new issue with installing 17.0.4 on bare metal.
```

**Comment by karianna** [comment]
@gdams is CDN still disabled as per https://github.com/adoptium/adoptium-support/issues/554?

**Comment by gdams** [comment]
Yes it's still disabled so it should be working right now

**Comment by Mark-Palmer-Imprivata** [comment]
Thank you - things appear to be fixed now.
