### ISSUE TITLE
Protect debian packages against overwriting - they MUST be immutable!

### ISSUE THREAD

**Issue by nudgegoonies** [adoptium/adoptium-support#556]
### Please provide a brief summary of the bug

Again an already released package has been overwritten in the debian repository.
This time temurin-8-jdk_8.0.332.0.0+9-1_amd64.deb
https://adoptium.jfrog.io/ui/repos/tree/General/deb/pool/main/t/temurin-8/temurin-8-jdk_8.0.332.0.0+9-1_amd64.deb
```
Created: 05-05-22 14:01:10 +00:00
Last Modified: 01-08-22 14:22:38 +00:00
```
Yesterday the package was 84728808 bytes big. Today it is 84693892 bytes big!

Debian packages **MUST** be immutable ****

Please remove the delete permission of the tool user that uploads packages to the artifactory debian repository or add something constantly increasing number like build number or pipeline id.

### Expected Results

Debian packages **MUST** be immutable - if something has changed or even if the same sources have been rebuilt - change debian version!

### Actual Results

Same debian package - different size and checksums!

### What Java Version are you using?

openjdk version "1.8.0_332" OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09) OpenJDK 64-Bit Server VM (Temurin)(build 25.332-b09, mixed mode)

**Comment by xorpaul** [comment]
Last time this happened I had a chat with @gdams who proposed a fix for these small changes by always bumping the patch number:
![image](https://user-images.githubusercontent.com/938061/182588319-64d5f530-3655-4ab9-88e6-ac39c7560b0b.png)

**Comment by gdams** [comment]
Hi there, yes we’re aware of the issue already. Unfortunately this was due to poor documentation on our side. We have since changed the jfrog permissions to prevent our CI from overwriting packages so hopefully this will not occur again. Apologies for the inconvenience this has caused.
