### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by LucasDamico** [adoptium/adoptium-support#558]
### Please provide a brief summary of the bug

I received an automatic error report file from Eclipse.

In the summary part it says the following:
---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=Cp1252 -XX:+ShowCodeDetailsInExceptionMessages com.mygdx.game.DesktopLauncher

Host: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 8 cores, 7G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1806)
Time: Sun Aug  7 22:21:42 2022 Hora estándar de Argentina elapsed time: 1.167099 seconds (0d 0h 0m 1s)

I don't know if the rest of the information is important or useful, I am a student with very little experience in these things.

### Please provide steps to reproduce where possible

I was using the libGDX framework for a student project. 
I was creating an OrthographicCamera for a new screen of my game and suddenly this error appeared  when I tried to run to test the new camera and I could not continue running the program, although I understand that the error seems to be outside the code

### Expected Results

I need to be able to run the program

### Actual Results

I cant even run the program

### What Java Version are you using?

java version 8, update 321

### What is your operating system and platform?

Windows 10, lenovo ideapad 520s intel core i7 8th Gen

### How did you install Java?

I installed it from the Java main page, I think from a binary archive( zip)

### Did it work before?

```shell
This was working since I installed Java on my computer at the beginning of the year. it was working all the times I run the code before
```

### Did you test with other Java versions?

```shell
No, I am almost sure I never manually updated Java
```

### Relevant log output

```shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007695d37d, pid=9728, tid=8652
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [gdx-freetype64.dll+0xd37d]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Administrador\Desktop\Trabajo_Practico_libGDX\desktop\hs_err_pid9728.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by karianna** [comment]
@LucasDamico - You have two Java's installed (8u321 and 17.0.2) - the crash log is from the 17.0.2 version.  Please upgrade to the latest 17.0.4 and see if that fixes things.

**Comment by LucasDamico** [comment]
@karianna I don't quite understand, is it fine to have two Javas? Could you tell me how I update to the latest Java version?

**Comment by karianna** [comment]
@LucasDamico it should be OK to have two Java's as long as you're consistent with using the same version when you start the Java program.  You can download the latest Java 17.0.4 fro Windows from adoptium.net to upgradre

**Comment by LucasDamico** [comment]
I have installed java 17.0.4 and I keep getting the same error:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007695d37d, pid=7244, tid=272
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4+8 (17.0.4+8) (build 17.0.4+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (17.0.4+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [gdx-freetype64.dll+0xd37d]
```

**Comment by karianna** [comment]
@LucasDamico thanks for testing again.  Have you submitted this issue to LibGDX by any chance?  Although it could be a JVM bug these crashes can be caused by libs like libGDX who make native calls (LWJGL also does this)

**Comment by LucasDamico** [comment]
@karianna You seem to be right, today I have been debugging the program until I realized that the error seems to be caused by the freeType extension of libGDX when generating parameters for fonts. I will report this to libGDX, however the strangest thing is that the error comes from a code statement that was working normally before, anyway, thanks for your time and help!

**Comment by subchannel13** [comment]
I'm using LibGDX direcly and I had EXCEPTION_ACCESS_VIOLATION in gdx-freetype64.dll crash when disposing font generator too early. Hope it helps in the bug hunt.
