### ISSUE TITLE
eclipse crash when i coding

### ISSUE THREAD

**Issue by cyclonejb** [adoptium/adoptium-support#560]
### Please provide a brief summary of the bug

eclipse crash several times,I don't know how to reproduce it.it might caused by input software?

### Expected Results

happy coding

### Actual Results

crash

### What Java Version are you using?

OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)

### Relevant log output

```shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fec90fc9f1, pid=11620, tid=10948
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0xc9f1]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by cyclonejb** [comment]
OS:
 Windows 7 , 64 bit Build 7601 (6.1.7601.24545)
OS uptime: 10 days 20:47 hours

CPU: total 6 (initial active 6) (6 cores per cpu, 1 threads per core) family 6 model 158 stepping 13 microcode 0x0, cx8, cmov, fxsr, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, lzcnt, tsc, tscinvbit, avx, avx2, aes, erms, clmul, bmi1, bmi2, rtm, adx, fma, vzeroupper, clflush, clflushopt

Memory: 4k page, system-wide physical 16318M (3921M free)
TotalPageFile size 35113M (AvailPageFile size 12811M)
current process WorkingSet (physical memory assigned to process): 1956M, peak: 2496M
current process commit charge ("private bytes"): 1957M, peak: 2502M

vm_info: OpenJDK 64-Bit Server VM (17.0.3+7) for windows-amd64 JRE (17.0.3+7), built on Apr 19 2022 16:55:35 by "" with MS VC++ 16.7 (VS2019)

END.

**Comment by cyclonejb** [comment]
Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_341
PATH=E:/software/eclipse-jee-2022-06-R-win32-x86_64/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.3.v20220515-1416/jre/bin/server;E:/software/eclipse-jee-2022-06-R-win32-x86_64/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.3.v20220515-1416/jre/bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_341\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Apache Software Foundation\apache-maven-3.5.3\bin;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\gradle-3.4\bin;C:\Program Files\Git\cmd;E:\software\eclipse-jee-2022-06-R-win32-x86_64\eclipse;
USERNAME=huangwenlong
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel

**Comment by karianna** [comment]
Hi there, can you please try with 17.0.4.  Also please note you have `JAVA_HOME=C:\Program Files\Java\jdk1.8.0_341` which means Eclipse may get confused with which Java it is actually starting/running with.

**Comment by cyclonejb** [comment]
> Hi there, can you please try with 17.0.4. Also please note you have `JAVA_HOME=C:\Program Files\Java\jdk1.8.0_341` which means Eclipse may get confused with which Java it is actually starting/running with.

Thank you,I changed this and keep watching.
eclipse.ini -vm C:\Program Files\Java\jdk-17.0.4\bin
JAVA_HOME=C:\Program Files\Java\jdk-17.0.4

**Comment by headlamp-software** [comment]
I had this problem after I installed a bunch of updates to Eclipse 4.23.0. Installing the latest release of Eclipse did not solve the problem. I installed Eclipse 4.24.0 and the problem went away. I have no idea why. Note that I got a Java error code of -1073740771 (0xc000005).
