### ISSUE TITLE
11-jdk-jammy frequently triggering full gc

### ISSUE THREAD

**Issue by tejasmjethva** [adoptium/adoptium-support#561]
We've recently updated our docker base image from openjdk:11 to eclipse-temurin:11-jdk-jammy. After the update, we're seeing very frequent full GC triggering for application and memory usage is also capped.

We have provided Xmx to 15G and GKE limit to 20G, but the memory is capped at 6G. We're using all the default jvm parameters (no overrides), also, explicitly specifying to use G1GC.

Do we need to make any jvm parameters overrides or settings when we use eclipse-temurin:11-jdk-jammy?

Note: With openjdk:11, we didn't seem to have this issue, we were seeing no or very minimum full GC.

Thanks,

**Comment by tejasmjethva** [comment]
This seems to work fine, thanks @Karianna for the help.

**Comment by RedrumSherlock** [comment]
@karianna even though setting MaxRAMPercentage would address this issue and is the preferred way, I'm curious on why using -Xmx would not work. 

Based on my limited knowledge, -Xmx is supposed to override MaxRAMPercentage setting. So when we specified -Xmx15g, isn't it supposed to override the default 25% of the container memory limit?

**Comment by karianna** [comment]
I can only speculate a docker/cgroups version challenge.  Are you on the latest Docker and/or running CGroups 2?
