### ISSUE TITLE
api-ms DLLs should not be redistributed

### ISSUE THREAD

**Issue by khourig** [adoptium/adoptium-support#564]
### Please provide a brief summary of the bug

The api-ms DLLs are to be distributed by Microsoft only and are installed by Windows Update.

The permitted distributable DLLs are listed here https://docs.microsoft.com/en-us/visualstudio/releases/2022/redistribution

### Expected Results

No api-ms DLLs installed.

### Actual Results

Some api-ms DLLs installed.

### What Java Version are you using?

JDK11.0.14.1

**Comment by gdams** [comment]
@khourig can you specify where these api-ms DLLs are located? I'll follow up once I've got confirmation

**Comment by khourig** [comment]
For instance: `jdk11.0.14.1\bin\api-ms-win-core-console-l1-1-0.dll`

**Comment by karianna** [comment]
This still needs investigating

**Comment by khourig** [comment]
Is there a time table for this to be addressed?

**Comment by karianna** [comment]
@khourig It's not on our priority list presently, so will require a volunteer to pick it up

**Comment by karianna** [comment]
@gdams I'm not sure I'm understanding this use case, is this expected behaviour for all OpenJDK distros?

**Comment by khourig** [comment]
Here is post that recommends using the VC redistributable installer.
https://stackoverflow.com/questions/74073045/is-it-ok-to-distribute-api-ms-win-core-xxx-dll-with-my-app

The redistributable installers:
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

**Comment by karianna** [comment]
@andrew-m-leonard You might have an opinion on this and reproducible builds.

**Comment by andrew-m-leonard** [comment]
I don't think this is correct, the redist DLLs listed here: https://docs.microsoft.com/en-us/visualstudio/releases/2022/redistribution
is the **"Visual Studio"** redistribution list, not the UCRT list.
UCRT is not a direct part of Visual Studio, it is a Windows OS component and provided as part of the "Windows Kit" SDK.
As documented [here](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/) the advice is to redist and copy all of C:\Program Files (x86)\Windows Kits\10\Redist\ucrt, (which is the complete set of api-ms-win*.dll's), which is what the OpenJDK make progress does.

**Comment by khourig** [comment]
Ok so a local copy of the api-ms DLLs for Windows 7 and older. An honest question: are those systems relevant? For my project, they are not. We will remove the api-ms DLLs from the jdk folder.
