### ISSUE TITLE
If we can provide Jdk 8~10 for mac aarch64?

### ISSUE THREAD

**Issue by Goooler** [adoptium/adoptium-support#566]
Cause Gradle's `jvmToolchain` depends on the `adoptium` vendor by default, many projects declare `languageVersion` < 11 and build on Apple silicon chips, which will lead the download failures:
```
Failed to calculate the value of task ':ktlint:compileJava' property 'javaCompiler'.
Unable to download toolchain matching these requirements: {languageVersion=8, vendor=any, implementation=vendor-specific}
Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
Could not read 'https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse' as it does not exist.
```
Link https://github.com/gradle/gradle/issues/19595.

**Comment by karianna** [comment]
At this stage there are no plans to provide that platform/version combination.  I'm afraid this will have to be resolved at Gradle.
