### ISSUE TITLE
(OSATE2:23122): Gdk-CRITICAL **: 09:23:55.357: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by noahsmindfuck** [adoptium/adoptium-support#567]
### Please provide a brief summary of the bug

I am running OSATE2 on linux.
After a recent update it crashes and asks me to report here:

(OSATE2:23122): Gdk-CRITICAL **: 09:23:55.357: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fe0ce6c732f, pid=23122, tid=23123

 JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
 Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 C  [libX11.so.6+0x2d32f]  XInternAtom+0x3f

 Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/herbert/nodeflow/osate_dir/core.23122)

 An error report file with more information is saved as:
 /home/herbert/nodeflow/osate_dir/hs_err_pid23122.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

./osate  113,75s user 3,94s system 99% cpu 1:58,58 total

### Please provide steps to reproduce where possible

- Open osate2
- switch to diagram view

### Expected Results

show the diagram

### Actual Results

crash and reports with error below

### What Java Version are you using?

Unrecognized option: --version

### What is your operating system and platform?

Linux, 5.19.1-arch2-1

### How did you install Java?

pacman

### Did it work before?

```shell
yes, all worked well
```

### Did you test with other Java versions?

```shell
no
```

### Relevant log output

```shell
Github complains:  There was an error creating your issue: body is too long (maximum is 65536 characters). 
there are 2000 lines of log file, I have copied it here: https://www.pastiebin.com/62fc9b98d8fa1
```

**Comment by karianna** [comment]
@noahsmindfuck Can you try with the latest 11.0.16 and let us know if its still an issue.

**Comment by noahsmindfuck** [comment]
Hi @karianna 
Thank you for your reply.
I think the JRE is shipped inside the OSATE2 installation bc on my system I have only this installed: 
extra/jre8-openjdk-headless 8.345.u01-1 [installed]

I now installed the 11.0.6 version (jre11-openjdk-headless-11.0.16.1.u1-2) and still receive the same error, although now it references to a version 17

(OSATE2:17504): Gdk-CRITICAL **: 22:30:22.977: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f6397d1ef0d, pid=17504, tid=17505

 JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [libX11.so.6+0x2cf0d]

 Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/herbert/nodeflow/osate2-2.11.0-vfinal-linux.gtk.x86_64/core.17504)

 An error report file with more information is saved as:
 /home/herbert/nodeflow/osate2-2.11.0-vfinal-linux.gtk.x86_64/hs_err_pid17504.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by noahsmindfuck** [comment]
according to [this one](https://github.com/javafxports/openjdk-jfx/pull/199) it could be a wayland/jre problem
a proposed fix is to run it with "-Djdk.gtk.version=2" to force gtk2

**Comment by noahsmindfuck** [comment]
Workaround for me now is to use a desktop environment based on Xorg (not a solution, a very dirty workaround)
Hope that everyone finds the time to migrate away from old monsters,

until then
