### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION when I open Minecraft

### ISSUE THREAD

**Issue by Gutter7** [adoptium/adoptium-support#568]
### Please provide a brief summary of the bug

When I try to launch Minecraft, it just says exception access violation and crashes. I tried repairing and reinstalling your java but it didn't work.

### Please provide steps to reproduce where possible

I really don't know how to do this, because I don't know what caused it, though it says something about Configuration conflict: there is more than one oshi.properties file on the classpath and Configuration conflict: there is more than one oshi.architecture.properties file on the classpath

### Expected Results

I expected minecraft to open.

### Actual Results

it crashed with the error EXCEPTION ACCESS VIOLATION

### What Java Version are you using?

JDK!&.04.0

### How did you install Java?

your installer package

### Did it work before?

```shell
One day my java didn't work, so I was recommended yours and it still didn't.
```

### Did you test with other Java versions?

```shell
yes
```

### Relevant log output

```shell
[21:17:25] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[21:17:25] [main/INFO]: Loading 3 mods:
	- fabricloader 0.14.9
	- java 17
	- minecraft 1.19.2
[21:17:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/gablo/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:17:25] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[21:17:26] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[21:17:27] [main/INFO]: Building optimized datafixer
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8cc3ab5f3, pid=10084, tid=15856
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4+8 (17.0.4+8) (build 17.0.4+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (17.0.4+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x53b5f3]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\gablo\AppData\Roaming\PolyMC\instances\1.19.2\.minecraft\hs_err_pid10084.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Process exited with code 1.
```

**Comment by karianna** [comment]
Minecraft comes with its own bundle 17.0.3 from Microsoft.  We generally recommend that you stick with that version.  Also please disable all the mods and start with a clean minecraft to narrow it down
