### ISSUE TITLE
Openjdk 11.0.11 java process error in k8s

### ISSUE THREAD

**Issue by shaocg** [adoptium/adoptium-support#569]
### Please provide a brief summary of the bug

We have deployed the k8s java process on multiple servers in the production environment. Two of the machines fail frequently (about once a day), and the error information is different each time. I would like to ask what is the reason, and the specific hs_err_pid.log is not mounted, can you please help me?
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/40092654/185834632-e0578e06-86d5-4bb2-9bc8-7b94741d23f9.png">
![image](https://user-images.githubusercontent.com/40092654/186311956-a605b489-fd21-4c78-b5a8-8a1af3811730.png)
![image](https://user-images.githubusercontent.com/40092654/185834723-9bb168b4-03f1-4c33-a6f5-4651cea52aa9.png)

### Expected Results

Program can run normally

### Actual Results

Frequent errors

### What Java Version are you using?

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by karianna** [comment]
@shaocg Please try 11.0.16.1 from adoptiym.net and post any new error message here.

**Comment by shaocg** [comment]
Will 11.0.16.1 fix this? Because the upgrade of our production environment needs to be very careful, can you provide instructions to solve this problem? In this way, I can clearly push the company to upgrade the jdk version, thank you very much.

**Comment by karianna** [comment]
Please see the release notes for all versions 11.0.12+ at foojay.com.  You'll see a number of C2 compiler crash fixes.  There's not a 100% guarantee that yours is fixed but an upgrade to the latest is recommended regardless
