### ISSUE TITLE
Unable to download binary using adoptium api

### ISSUE THREAD

**Issue by ivan-yankov** [adoptium/adoptium-support#573]
### Please provide a brief summary of the bug

Hello, I am trying to use curl to download specified version of jdk / jre.
However it does not work. My attempt to try on swagger also was not successful.

### Please provide steps to reproduce where possible

Execute command

curl -X 'GET' 'https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/eclipse?project=jdk' -H 'accept: */*'

### Expected Results

Download the matched file

### Actual Results

Nothing happens

### What Java Version are you using?

11

### What is your operating system and platform?

linux

**Comment by karianna** [comment]
@ivan-yankov  That link works for me here in the UK.  Which geo location are you in?

**Comment by ivan-yankov** [comment]
@karianna I am located in Bulgaria.

**Comment by jerboaa** [comment]
```
$ curl -L --output jdk8-ga.tar.gz https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/eclipse
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98.1M  100 98.1M    0     0  8907k      0  0:00:11  0:00:11 --:--:-- 9726k
$ tar -xf jdk8-ga.tar.gz 
$ ./jdk8u345-b01/bin/java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)
```

Works fine here.

**Comment by ivan-yankov** [comment]
OK. It seems the trick here is -L option of the curl. With this option it works for me also. Thank you very much @jerboaa .
I am going to close the issue as resolved.

**Comment by ivan-yankov** [comment]
Resolved.
