### ISSUE TITLE
Eclipse Temurin JRE 17 upgrade issue

### ISSUE THREAD

**Issue by 0ut1awStar** [adoptium/adoptium-support#574]
### Please provide a brief summary of the bug

Upgrading from Eclipse Temurin JRE 17.0.4+8 to 17.0.4.1+1 does not uninstall previous version.

### Please provide steps to reproduce where possible

1. install OpenJDK17U-jre_x64_windows_hotspot_17.0.4_8.msi
2. install OpenJDK17U-jre_x64_windows_hotspot_17.0.4.1_1.msi
3. check programs and features

### Expected Results

upgrading removes previous (n-1) version

### Actual Results

upgrading does not remove previous (n-1) version

### What Java Version are you using?

17.0.4.0, 17.0.4.1

### What is your operating system and platform?

Windows 10 21H2

### How did you install Java?

OpenJDK17U-jre_x64_windows_hotspot_17.0.4_8.msi
OpenJDK17U-jre_x64_windows_hotspot_17.0.4.1_1.msi

### Did it work before?

```shell
yes, this worked with prior versions
```

### Did you test with other Java versions?

```shell
issue only occurs when upgrading from 17.0.4 to 17.0.4.1
```

**Comment by gdams** [comment]
I believe this is a limitation of server as outlined in the installation docs (https://adoptium.net/installation/windows)

**Comment by 0ut1awStar** [comment]
Ahh, thank you for pointing that out.
