### ISSUE TITLE
Release Notes for JDK 8u345

### ISSUE THREAD

**Issue by tellison** [adoptium/adoptium-support#575]
Received via direct e-mail:

Hello Eclipse Support:

We have been downloading the Windows x64 version of the jdk8u from this location: https://adoptium.net/temurin/releases/?version=8

We typically check the Release Notes as you suggest here: https://foojay.io/java-8/?tab=cve

However, there are no new Release Notes for the 345 version of the JDK 8. I cannot find a way to contact anyone at Foojay otherwise I would.

Do you have any idea when the Release Notes for Java SDK 8u345 will be available?

**Comment by jerboaa** [comment]
https://mail.openjdk.org/pipermail/jdk8u-dev/2022-August/015329.html

There isn't much to say. Only includes https://bugs.openjdk.org/browse/JDK-8290832, which is a backout of https://bugs.openjdk.org/browse/JDK-8283438 included in 8u342

**Comment by tellison** [comment]
Thanks. Not sure why Foojay are not noting this release. In the meantime I will just answer the raiser with a reply to this instance, but another reason why we should be hosting our own release notes IMHO.
