### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by problemsproblemsyes** [adoptium/adoptium-support#579]
### Please provide a brief summary of the bug

Dear all,

I've been using a client called Runelite to play runescape. However at random intervals and without known trigger the client crashes. When looking into the jvm_crash_pid logs I keep noticing the EXCEPTION_ACCESS_VIOLATION (0xc0000005) error code in every crash. In the same logs it referred me to this github page. I am wondering if you know whats triggering these random crashes and may have an idea of a possible fix?

What have I tried:

- Reinstalling Java
- Reinstalling c++ visual studio
- Reinstalling Runelite
- Updating Motherboard bios
- Updating Motherboard chipset
- Updating Nvidia Drivers, multiple tested
- Disabling XMP in bios
- Removing all runescape and Runelite related files/folders/programs
- No 3rd party plugins
- Disabling PBO (Ryzen)

[jvm_crash_pid_4320.log](https://github.com/adoptium/adoptium-support/files/9443363/jvm_crash_pid_4320.log)
[client.log](https://github.com/adoptium/adoptium-support/files/9443367/client.log)

### Expected Results

I expect the client not to crash

### Actual Results

Client keeps crashing at random intervals. The program just closes.

### What Java Version are you using?

1.8.0_341

### What is your operating system and platform?

windows 11 x86_64

**Comment by karianna** [comment]
Please try 1.8.0_345 and let us know if the issue persists,
