### ISSUE TITLE
Temurin 17.0.4.1 not available via sdkman?

### ISSUE THREAD

**Issue by viktor-thell-seal** [adoptium/adoptium-support#581]
Why is Temurin 17.0.4.1 not available via sdkman? There are lots of other vendors providing 17.0.4.1 via sdkman but not Temurin. I'm on macOS x86_64.
```
$ sdk list java
================================================================================
Available Java Versions for macOS 64bit
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
...
 Temurin       |     | 18.0.2       | tem     |            | 18.0.2-tem
               |     | 18.0.1       | tem     |            | 18.0.1-tem
               | >>> | 17.0.4       | tem     | installed  | 17.0.4-tem
               |     | 17.0.3       | tem     |            | 17.0.3-tem
               |     | 11.0.16      | tem     | installed  | 11.0.16-tem
               |     | 11.0.15      | tem     |            | 11.0.15-tem
               |     | 8.0.345      | tem     | installed  | 8.0.345-tem
               |     | 8.0.332      | tem     |            | 8.0.332-tem
...
```

**Comment by karianna** [comment]
@viktor-thell-seal Have you asked the SDKMan team?  We're not actually responsible for that product :-)

**Comment by viktor-thell-seal** [comment]
Thanks for the response and sorry, but given the text on sdkman I thought you guys published to them:

> _SDKMAN! is unique in that it empowers SDK Vendors to publish their candidate releases on our platform._
From: https://sdkman.io/vendors

But given [this](https://github.com/sdkman/sdkman-disco-integration) it seems like they rely on https://github.com/foojayio/discoapi to get info about JDK releases and for some reason `17.0.4.1` is not returned by that api.

For anyone interested I opened a ticket there: https://github.com/foojayio/discoapi/issues/65
