### ISSUE TITLE
MC Modpacks crashing during launch via FTB app

### ISSUE THREAD

**Issue by Squeezened** [adoptium/adoptium-support#583]
### Please provide a brief summary of the bug

While I could launch other modpacks seemingly without issue, Infinity Evolved crashes after some time launching with the FTB app.

The following is the error log for Infinity Evolved

[hs_err_pid5964.log](https://github.com/adoptium/adoptium-support/files/9531142/hs_err_pid5964.log)

### Expected Results

I expected Infinity Evolved to launch successfully

### Actual Results

While it seemed to create an instance of Minecraft 1.7.10 successfully while launching Infinity Evolved, it would close immediately and the log for the launch process says it crashed some time afterwards. While this was happening initially a few days ago, I tried launching Ultimate Reloaded to see if it was bugged as well, however that modpack still launches without issue.

### What Java Version are you using?

Version 8 Update 341

**Comment by karianna** [comment]
Hi there, I'm afraid you'll have to report this with the mod pack team, it's hard to know what they may have introduced.  Please note std minecraft comes with MSFT Build of OpenJDK 17.
