### ISSUE TITLE
All yum commands return a "https://packages.adoptium.net/artifactory/rpm/ol/7Server/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found" Error

### ISSUE THREAD

**Issue by TZR-Redstonemaniac21** [adoptium/adoptium-support#585]
### Please provide a brief summary of the bug

No matter what I do, I get this error. I don't know how to fix it as I'm not getting anything from google. This is on an Oracle Cloud VM running an [Oracle-Linux-7.9-aarch64-2022.08.29-0] Image. 

### Expected Results

I expected the "sudo yum update" command to work

### Actual Results

It errored and gave me a "https://packages.adoptium.net/artifactory/rpm/ol/7Server/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found. Trying other mirror." error.

### What Java Version are you using?

java 18.0.2.1 2022-08-18 Java(TM) SE Runtime Environment (build 18.0.2.1+1-1) Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

### What is your operating system and platform?

[Oracle-Linux-7.9-aarch64-2022.08.29-0]

### How did you install Java?

I installed java using "sudo yum install jdk-18.aarch64"

### Did it work before?

```shell
I have not used any other Java version
```

**Comment by karianna** [comment]
@TZR-Redstonemaniac21 Apologies for not responding earlier.  You're actually installing the OpenJDK from the Oracle linux distro (not Adoptium), you'll need to report the error with them.
