### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by jm185666** [adoptium/adoptium-support#589]
### Please provide a brief summary of the bug

When start run.bat (windows) the app crashesand show the next message:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x00007ff9e8e73fb9, pid=3536, tid=2756
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [librocksdbjni9080484738302787234.dll+0x4f3fb9]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Install\RAP\hivemq-4.8.4\bin\hs_err_pid3536.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

### Expected Results

I would expect it to start without any problems.

### Actual Results

The app does not start

### What Java Version are you using?

OpenJDK11U-jdk_x64_windows_hotspot_11.0.16.1_1

### What is your operating system and platform?

Windows 10

### Did it work before?

```shell
yes, but when i restarted the machine, it stopped working
```

### Did you test with other Java versions?

```shell
NO
```

**Comment by karianna** [comment]
@jm185666 Can you send us the log at C:\Install\RAP\hivemq-4.8.4\bin\hs_err_pid3536.log

**Comment by jm185666** [comment]
Of course.

**Comment by jm185666** [comment]
[hs_err_pid3536.log](https://github.com/adoptium/adoptium-support/files/9648949/hs_err_pid3536.log)

**Comment by karianna** [comment]
@jm185666 

```
Current thread (0x00000201a786f800):  JavaThread "persistence-start-executor-4" [_thread_in_native, id=2756, stack(0x0000000868100000,0x0000000868200000)]

Stack: [0x0000000868100000,0x0000000868200000],  sp=0x00000008681fc9d0,  free space=1010k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni9080484738302787234.dll+0x4f3fb9]
```

That last line comes from the librocksdbjni dll which contains native code which has triggered the crash - have you submitted this issue to the the RocksDB folks as well?  They may need to look at what C/C++ they've written there.
