### ISSUE TITLE
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by Caeseus** [adoptium/adoptium-support#592]
### Please provide a brief summary of the bug

#

# A fatal error has been detected by the Java Runtime Environment:

#

# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc3003f4c5, pid=14424, tid=0x0000000000004028

#

# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)

# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)

# Problematic frame:

# C [atio6axx.dll+0x1f6f4c5]

#

# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

#

# If you would like to submit a bug report, please visit:

# https://github.com/adoptium/adoptium-support/issues

# The crash happened outside the Java Virtual Machine in native code.

# See problematic frame for where to report the bug.

#

I know im not the first, nor the last to have this issue. Its modded minecraft issues. The only fixes ive found ive tried.

#1: Update windows- Windows is up to date
#2: Update graphics card- AMD card, up to date
#3: If its AMD, reinstall amd software- Done twice
#4: Manually create dump file in Task manager- Done three times, same error after each time.
#5: Reinstalled FTB
#6: Had server host reset server multiple times

It had been working for 2 months until a few days ago. The mod pack still works, I only get this now when attempting to join my friends server.  I would appreciate any advice.

[hs_err_pid15012.log](https://github.com/adoptium/adoptium-support/files/9692769/hs_err_pid15012.log)

### Please provide steps to reproduce where possible

Anytime I attempt to connect to the server

### Expected Results

I expected it to work, still continues to error.

### Actual Results

Crashes every time i attempt to connect.

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)

### What is your operating system and platform?

Windows and Windows 10

### How did you install Java?

Installe rpackage

### Did it work before?

```shell
It worked on this version until a few days ago.
```

### Did you test with other Java versions?

```shell
No
```

**Comment by karianna** [comment]
@Caeseus you can try the latest 1.8.0_345 build but I'm afraid I suspect it's a problem with the LWJGL version you're using as the crash is coming from that lib.

**Comment by Caeseus** [comment]
The LWJGL? I don't recognize that abbreviation.

**Comment by karianna** [comment]
Light Weight Java Gaming Library.  It's the core lib used by Minecraft for the GUI interaction with your drivers etc.

**Comment by Caeseus** [comment]
Thank you, @karianna . Would you know what I would need to to do to "fix" that or is it possible?

**Comment by karianna** [comment]
Are you on the latest version of base minecraft?

**Comment by Caeseus** [comment]
I believe the modpack is 1.18.2

**Comment by karianna** [comment]
Did you give 1.8.09_345 a go?  Please note official Minecraft is at 1.19.x with Java 17 as its core.

**Comment by TETS-Official** [comment]
dont make this stale!!1!

**Comment by Diarawiar** [comment]
i have same problem and I don't know how I can solve it.

**Comment by karianna** [comment]
From GPT-4:

Enabling mini core dumps (also known as mini dumps) on a Windows client operating system involves a few steps. Mini dumps are smaller subsets of full memory dumps, providing essential information about the state of the system at the time of a crash, without the overhead of a complete memory dump. Here's how you can enable them:

1. **Use System Properties:**
   - Right-click on 'This PC' or 'My Computer' on your desktop or in File Explorer, and select 'Properties'.
   - Click on 'Advanced system settings' to open the System Properties dialog.
   - In the 'Advanced' tab, under 'Startup and Recovery', click on 'Settings'.
   - In the 'Startup and Recovery' dialog box, under 'System failure', you will see 'Write debugging information'.
   - In the dropdown menu for 'Write debugging information', select 'Small memory dump (256 KB)' or another mini dump option as per your requirement.

2. **Edit the Registry (Advanced):**
   - Press Win + R, type `regedit`, and press Enter to open the Registry Editor.
   - Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl`.
   - Modify or create a DWORD value named `MiniDumpEnabled` and set it to `1`.
   - You can also configure the dump file path by modifying the `MinidumpDir` value.

3. **Use Group Policy (if applicable):**
   - Open the Local Group Policy Editor by typing `gpedit.msc` in the Run dialog.
   - Navigate to Computer Configuration -> Administrative Templates -> Windows Components -> Windows Error Reporting -> Advanced Error Reporting Settings.
   - Configure the settings for mini dumps as required.

4. **Automate with a Script or Command Line:**
   - For advanced users or administrators, you can use scripts or command-line tools like Windows Management Instrumentation (WMI) or PowerShell to configure these settings.

Remember, making changes to system settings or the registry can affect your system's stability and performance. Ensure you understand the implications of these changes and consider creating a system restore point before proceeding. Additionally, the exact steps might vary slightly depending on your version of Windows.

**Comment by GabiVasile** [comment]
I get the same error with version 1.8.0_422 when trying to extract the SQL code from Oracle Forms using CAST Oracle Forms Extractor.
I tried the recommendations from above, but nothing worked.
