### ISSUE TITLE
Save file loads to clouds / unable to generate map

### ISSUE THREAD

**Issue by HammYzz** [adoptium/adoptium-support#596]
### Please provide a brief summary of the bug

Pokewilds load save to clouds screen can open menu and select items/pokemon/anything.
if you try to move it says it needs to generate a map, click yes and it's never able to load.

ram slowly ramps up to filling up all 16gb i have available then drops off.

### Expected Results

load new map

### Actual Results

unable to load

### What Java Version are you using?

"1.8.0_291"

### What is your operating system and platform?

windows 11
21H1 - 22000.978

**Comment by karianna** [comment]
@HammYzz Are you able to tell us which version of our Java that you are using?

**Comment by HammYzz** [comment]
I can check when I get home from work.

I ended up moving my save file to a vm that had 64gb of ram and was able to
load the game.
Save it.
Then move the save file back to my laptop and continue playing.

I dont know if it's from me moving to a lot of different worlds on my save
file or what, but seems to be resolved now.

I was able to generate another map just on my laptop after this though.

**Comment by karianna** [comment]
OK, sounds like the heap simply needed to grow beyond 16GB before settling back down to a smaller size.  It may be worth contacting the authors of that program to see if they can reduce the memory consumption of their maps.
