### ISSUE TITLE
Minecraft crashing when leaving the mcc island server 

### ISSUE THREAD

**Issue by Omnimanoncrack** [adoptium/adoptium-support#597]
### Please provide a brief summary of the bug

When joining the mcc island server all of the text on the leaderboard is a 0, and the game crashes when leaving. In the crash report it says that the problematic frame is "C  [jemalloc.dll+0x1ca13]" and that there was a fatal error that said "EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb4dfcca13, pid=8416, tid=4520". Also didn't render any chunks until i tampered with the chunk settings

### Please provide steps to reproduce where possible

Using the simply optimized modpack, although it worked on many different modpacks and in vanilla minecraft

### Expected Results

To have a working game 

### Actual Results

The leaderboard broke and chunks didn't render (i fixed that)

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-18.0.2.1+1

### What is your operating system and platform?

Windows 10 Pro x86-64

### How did you install Java?

Downloaded from a zip file and directed minecraft to use the javaw file

### Did it work before?

```shell
No, i tested on graalvm ee and azul and it didn't work
```

### Did you test with other Java versions?

```shell
tested with java 17 and 18
```

**Comment by karianna** [comment]
We recommend sticking with the MSFT Build of OpenJDK provided with the official Minecraft download.  Can you try with that?
