### ISSUE TITLE
jvm irregular crash[jdk version 11.0.16.1]

### ISSUE THREAD

**Issue by shallynever** [adoptium/adoptium-support#599]
## Question
jvm irregular crash

## Context
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7ee0890383 (sent by kill), pid=6, tid=5067
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 7874 c2 sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(Ljava/nio/CharBuffer;Ljava/nio/ByteBuffer;)Ljava/nio/charset/CoderResult; java.base@11.0.16.1 (489 bytes) @ 0x00007f7ee0890383 [0x00007f7ee0890140+0x0000000000000243]
#
# Core dump will be written. Default location: /workdir/core.6
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Xms6g -Xmx6g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=45 -XX:MaxTenuringThreshold=15 -XX:-OmitStackTraceInFastThrow -XX:+PrintGCDetails -Xloggc:./logs/gc.log -XX:ErrorFile=./logs/hs_err_pid_6.log -javaagent:/jmx_prometheus_agent.jar=8089:./config/jmx-config.yaml -javaagent:/jolokia-jvm-agent.jar=port=8081,host=0.0.0.0 --add-exports=java.base/jdk.internal.loader=ALL-UNNAMED -DzkHost=172.16.14.205,172.16.14.206,172.16.14.196,172.16.14.181,172.16.14.180 -Dcodis-zk-host=172.16.14.180:2181,172.16.14.196:2181,172.16.14.205:2181,172.16.14.206:2181 -Dcodis-zk-path=/codis-config -Dapollo.meta=http://apollopro.ge.cn:8081 -Dapp.id=rd-ido-odc -Denv=HZPRO -Dfile.encoding=utf-8 -Dapollo.bootstrap.enabled=true -Dapollo.bootstrap.eagerLoad.enabled=true -Dapollo.bootstrap.namespaces=rd.ido-odc,rd.ido-common,application -Dapollo.cacheDir=./apollo-config -Ddynamic.config.initialDelayMillis=0 -Dgt.config.reload_min_interval=30 -Dopen-region-name-cache=true -Dopen-region-code-cache=true com.getui.platform.ido.odc.Main

Host: Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, 64 cores, 9G, CentOS Linux release 7.6.1810 (Core) 
Time: Sun Oct  9 19:26:15 2022 CST elapsed time: 81850.532192 seconds (0d 22h 44m 10s)

---------------  T H R E A D  ---------------

Current thread (0x00007f7dd0003000):  JavaThread "qtp1619752179-4989" [_thread_in_Java, id=5067, stack(0x00007f7a67cfd000,0x00007f7a67dfe000)]

Stack: [0x00007f7a67cfd000,0x00007f7a67dfe000],  sp=0x00007f7a67dfb630,  free space=1017k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 7874 c2 sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(Ljava/nio/CharBuffer;Ljava/nio/ByteBuffer;)Ljava/nio/charset/CoderResult; java.base@11.0.16.1 (489 bytes) @ 0x00007f7ee0890383 [0x00007f7ee0890140+0x0000000000000243]
J 10496 c2 sun.nio.cs.StreamEncoder.write([CII)V java.base@11.0.16.1 (78 bytes) @ 0x00007f7ee0c1419c [0x00007f7ee0c13ea0+0x00000000000002fc]
J 16746 c2 sun.nio.cs.StreamEncoder.write(Ljava/lang/String;II)V java.base@11.0.16.1 (37 bytes) @ 0x00007f7ee0acbeb0 [0x00007f7ee0acbc40+0x0000000000000270]
J 14684 c2 com.google.gson.stream.JsonWriter.string(Ljava/lang/String;)V (169 bytes) @ 0x00007f7ee0e4aaec [0x00007f7ee0e4a800+0x00000000000002ec]
J 27304 c2 com.google.gson.internal.bind.TypeAdapters$15.write(Lcom/google/gson/stream/JsonWriter;Ljava/lang/Object;)V (10 bytes) @ 0x00007f7ee16f5d40 [0x00007f7ee16f5ae0+0x0000000000000260]
J 20765 c2 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(Lcom/google/gson/stream/JsonWriter;Ljava/lang/Object;)V (98 bytes) @ 0x00007f7ee0fd13d8 [0x00007f7ee0fd0f80+0x0000000000000458]
J 17420 c2 com.google.gson.Gson.toJson(Ljava/lang/Object;Ljava/lang/reflect/Type;Ljava/lang/Appendable;)V (34 bytes) @ 0x00007f7ee11323a0 [0x00007f7ee1131fa0+0x0000000000000400]
J 25854 c2 org.springframework.http.converter.json.AbstractJsonHttpMessageConverter.writeInternal(Ljava/lang/Object;Ljava/lang/reflect/Type;Lorg/springframework/http/HttpOutputMessage;)V (75 bytes) @ 0x00007f7ee0d4b85c [0x00007f7ee0d4afa0+0x00000000000008bc]
J 26106 c2 org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(Ljava/lang/Object;Ljava/lang/reflect/Type;Lorg/springframework/http/MediaType;Lorg/springframework/http/HttpOutputMessage;)V (71 bytes) @ 0x00007f7ee15a770c [0x00007f7ee15a7480+0x000000000000028c]
J 23661 c2 org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(Ljava/lang/Object;Lorg/springframework/core/MethodParameter;Lorg/springframework/http/server/ServletServerHttpRequest;Lorg/springframework/http/server/ServletServerHttpResponse;)V (1086 bytes) @ 0x00007f7ee129446c [0x00007f7ee1291e40+0x000000000000262c]
J 32195 c2 org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(Ljava/lang/Object;Lorg/springframework/core/MethodParameter;Lorg/springframework/web/method/support/ModelAndViewContainer;Lorg/springframework/web/context/request/NativeWebRequest;)V (59 bytes) @ 0x00007f7ee1d630c8 [0x00007f7ee1d629c0+0x0000000000000708]
J 25775 c2 org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(Lorg/springframework/web/context/request/ServletWebRequest;Lorg/springframework/web/method/support/ModelAndViewContainer;[Ljava/lang/Object;)V (143 bytes) @ 0x00007f7ee07953b4 [0x00007f7ee0794e20+0x0000000000000594]
J 31695 c2 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Lorg/springframework/web/method/HandlerMethod;)Lorg/springframework/web/servlet/ModelAndView; (296 bytes) @ 0x00007f7ee1cd44cc [0x00007f7ee1cd3780+0x0000000000000d4c]
J 27458 c2 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Lorg/springframework/web/method/HandlerMethod;)Lorg/springframework/web/servlet/ModelAndView; (128 bytes) @ 0x00007f7ee174c8fc [0x00007f7ee174c840+0x00000000000000bc]
J 31698 c2 org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljava/lang/Object;)Lorg/springframework/web/servlet/ModelAndView; (11 bytes) @ 0x00007f7ee1cd9b00 [0x00007f7ee1cd9ac0+0x0000000000000040]
J 28212 c2 org.springframework.web.servlet.DispatcherServlet.doDispatch(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (543 bytes) @ 0x00007f7ee1898460 [0x00007f7ee1897b80+0x00000000000008e0]
J 20963 c2 org.springframework.web.servlet.FrameworkServlet.processRequest(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (186 bytes) @ 0x00007f7ee134d008 [0x00007f7ee134c2a0+0x0000000000000d68]
J 27494 c2 org.springframework.web.servlet.FrameworkServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (37 bytes) @ 0x00007f7ee10026d0 [0x00007f7ee1001fc0+0x0000000000000710]
J 25665 c2 com.gexin.rp.security.web.filter.DecHttpRequestFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V (947 bytes) @ 0x00007f7ee06780b4 [0x00007f7ee06769c0+0x00000000000016f4]
J 25660 c2 org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V (344 bytes) @ 0x00007f7ee0ca7bd0 [0x00007f7ee0ca7ac0+0x0000000000000110]
J 26103 c2 org.springframework.web.filter.RequestContextFilter.doFilterInternal(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljavax/servlet/FilterChain;)V (133 bytes) @ 0x00007f7ee15a33c0 [0x00007f7ee15a2e60+0x0000000000000560]
J 25250 c2 org.springframework.web.filter.OncePerRequestFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V (175 bytes) @ 0x00007f7ee0a2948c [0x00007f7ee0a28fe0+0x00000000000004ac]
J 25578 c2 org.springframework.web.filter.FormContentFilter.doFilterInternal(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljavax/servlet/FilterChain;)V (44 bytes) @ 0x00007f7ee0c419dc [0x00007f7ee0c41940+0x000000000000009c]
J 25250 c2 org.springframework.web.filter.OncePerRequestFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V (175 bytes) @ 0x00007f7ee0a2948c [0x00007f7ee0a28fe0+0x00000000000004ac]
J 25736 c2 org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljavax/servlet/FilterChain;)V (59 bytes) @ 0x00007f7ee07148f0 [0x00007f7ee0714400+0x00000000000004f0]
J 25250 c2 org.springframework.web.filter.OncePerRequestFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V (175 bytes) @ 0x00007f7ee0a2948c [0x00007f7ee0a28fe0+0x00000000000004ac]
J 20051 c2 org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V (14 bytes) @ 0x00007f7ee0a72304 [0x00007f7ee0a722a0+0x0000000000000064]
J 25438 c2 org.eclipse.jetty.server.handler.ScopedHandler.handle(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (36 bytes) @ 0x00007f7ee0841798 [0x00007f7ee0841340+0x0000000000000458]
J 25792 c2 org.eclipse.jetty.security.SecurityHandler.handle(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (700 bytes) @ 0x00007f7ee048bdc0 [0x00007f7ee048bb20+0x00000000000002a0]
J 25403 c2 org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (50 bytes) @ 0x00007f7ee041008c [0x00007f7ee040ff20+0x000000000000016c]
J 25599 c2 org.eclipse.jetty.server.session.SessionHandler.doScope(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (533 bytes) @ 0x00007f7ee09972c4 [0x00007f7ee0996c80+0x0000000000000644]
J 27488 c2 org.eclipse.jetty.server.handler.ContextHandler.doScope(Ljava/lang/String;Lorg/eclipse/jetty/server/Request;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (524 bytes) @ 0x00007f7ee173d5a8 [0x00007f7ee173cb20+0x0000000000000a88]
J 21071 c2 org.eclipse.jetty.server.Server.handle(Lorg/eclipse/jetty/server/HttpChannel;)V (213 bytes) @ 0x00007f7ee13d692c [0x00007f7ee13d6200+0x000000000000072c]
J 28223 c2 org.eclipse.jetty.server.HttpChannel.dispatch(Ljavax/servlet/DispatcherType;Lorg/eclipse/jetty/server/HttpChannel$Dispatchable;)V (110 bytes) @ 0x00007f7ee18a1030 [0x00007f7ee18a0da0+0x0000000000000290]
J 28214 c2 org.eclipse.jetty.server.HttpChannel.handle()Z (920 bytes) @ 0x00007f7ee188f468 [0x00007f7ee188f0a0+0x00000000000003c8]
J 27609 c2 org.eclipse.jetty.server.HttpConnection.onFillable()V (433 bytes) @ 0x00007f7ee178cebc [0x00007f7ee178c9a0+0x000000000000051c]
J 26833 c2 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(Z)Z (565 bytes) @ 0x00007f7ee1666188 [0x00007f7ee1664cc0+0x00000000000014c8]
J 24055 c2 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(Z)V (158 bytes) @ 0x00007f7ee13ccc30 [0x00007f7ee13cc920+0x0000000000000310]
J 26815 c2 org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run()V (418 bytes) @ 0x00007f7ee1628fcc [0x00007f7ee1628ec0+0x000000000000010c]
J 26813 c2 org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run()V (548 bytes) @ 0x00007f7ee16251b4 [0x00007f7ee1624e60+0x0000000000000354]
J 29373 c1 java.lang.Thread.run()V java.base@11.0.16.1 (17 bytes) @ 0x00007f7edaacd984 [0x00007f7edaacd840+0x0000000000000144]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x8daf7b]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x39b
V  [libjvm.so+0x8d8f3d]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x1ed
V  [libjvm.so+0x987ffc]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xed9a3a]  JavaThread::thread_main_inner()+0x1ba
V  [libjvm.so+0xed666f]  Thread::call_run()+0x14f
V  [libjvm.so+0xc760e6]  thread_native_entry(Thread*)+0xe6

siginfo: si_signo: 11 (SIGSEGV), si_code: 0 (SI_USER), si_pid: 0 (invalid), si_uid: 0
Java version:

Your operating system and platform:

**Comment by karianna** [comment]
@shallynever Are you able to upload the core dump /workdir/core.6 to Dropbox or similar?
