### ISSUE TITLE
JRE 19 Wreaking Havoc on Brew Packages, Python3 in MacOS.

### ISSUE THREAD

**Issue by FreQRiDeR** [adoptium/adoptium-support#603]
## Question
I deleted the VM in /Library/Java but issue persists. Certain Brew packages no longer work and error out with invalid System instructions including java --version. Does latest JRE require AVX? If so, how do I remove it entirely? Brew, Python3 are broken now.

## Context

Java version:
19, latest

Your operating system and platform:
MacOS Monterey 12.4 x64 (No AVX support)

**Comment by karianna** [comment]
try `brew doctor` and see what it says

**Comment by FreQRiDeR** [comment]
"Ready to Brew"

No errors. 

JRE is conflicting with Python3.9, 3.10. Nothing that uses python runs now after installing Latest JRE. Even apps that run 100% on Java and have it imbedded. How do I remove JRE completely ?

**Comment by karianna** [comment]
@FreQRiDeR I think this is a question for the brew community.  Python3 and temurin casks are completely unrelated so something else is going on.

You can manually delete Java installations with `rm -rf /Library/Java/JavaVirtualMachines/<java installation you want to delete>`

**Comment by FreQRiDeR** [comment]
I don't believe it is a Brew issue as I deleted Homebrew and reinstalled. (I only have a few packages.) Also, apps like FutureRestore-Gui which are 100% Java and downloaded from the dev do not run anymore. FR-Gui even has Java bundled and, as I mentioned, problem only arose when I installed Adoptium Java. Any version.
