### ISSUE TITLE
Could not create the Java Virtual Machine. A fatal exception has occurred. Program will exit.

### ISSUE THREAD

**Issue by laiviettrung** [adoptium/adoptium-support#604]
### Please provide a brief summary of the bug

I used this adoptium to get into minecraft fabric 1.16.1. I use launcher but it gives me this error
![Screenshot_20221017_090223](https://user-images.githubusercontent.com/110972143/196197922-7c60a5c6-846f-499a-9274-c911abe6baf5.png)

### Expected Results

I want the development team to be able to fix bugs as quickly as possible

### Actual Results

In normal java I also get this error then I reinstall java and luckily the error is also fixed but when installing adoptium this error comes back again

### What Java Version are you using?

Unrecognized option: --version Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.

### What is your operating system and platform?

Windows 11 Enterprise Insider Preview on x64

**Comment by karianna** [comment]
Hi @laiviettrung I'm afraid we can't detect what could be the issue here with a modded version of Minecraft, you'll need to contact the Minecraft fabric owners.
