### ISSUE TITLE
Is there an alpine image of arm64v8/eclipse-temurin

### ISSUE THREAD

**Issue by Obsiye** [adoptium/adoptium-support#605]
## Question

Hi is there an alpine version of the arm64v8/eclipse-temurin ?

## Context

Java version: 17

Your operating system and platform:

arm64v8 on a macbook m1 chip

**Comment by karianna** [comment]
There is not I'm afraid.

**Comment by chadlwilson** [comment]
Hi @karianna - are you able to point me to the appropriate place to raise a request for discussion about potentially providing Alpine arm64 binaries (leaving the container images discussion for later)?

**Comment by karianna** [comment]
https://github.com/adoptium/containers/issues/158

**Comment by chadlwilson** [comment]
Ahh, thanks. Missed that as it was in the containers repo and was looking elsewhere 🙏
