### ISSUE TITLE
new URI(S,S,S,S) throws exception with incorrect error message

### ISSUE THREAD

**Issue by pekuz** [adoptium/adoptium-support#611]
### Please provide a brief summary of the bug

We rely on URI class implements reasonably well RFC-2396. Recently faced a confusing case.

### Please provide steps to reproduce where possible

```
jshell> new URI("ftps", "p.e.local|SIT@p.e.local", "/path", null)
|  Exception java.net.URISyntaxException: Illegal character in authority at index 7: ftps://p.e.local|SIT@p.e.local/path
|        at URI$Parser.fail (URI.java:2974)
|        at URI$Parser.parseAuthority (URI.java:3308)
|        at URI$Parser.parseHierarchical (URI.java:3219)
|        at URI$Parser.parse (URI.java:3175)
|        at URI.<init> (URI.java:708)
|        at URI.<init> (URI.java:809)
|        at (#2:1)
```

### Expected Results

The message should make sense, the index of the invalid character should be relative to the presented URI string.

```
jshell> "ftps://p.e.local|SIT@p.e.local/path".indexOf("|")
$4 ==> 16
```

### Actual Results

Above index ``7`` in ``ftps://p.e.local|SIT@p.e.local/path``  results in ``p``.

```
jshell> "ftps://p.e.local|SIT@p.e.local/path".charAt(7)
$3 ==> 'p'
```

### What Java Version are you using?

openjdk version "17.0.3" 2022-04-19

### What is your operating system and platform?

Win 10 on AMD x64

### Did you test with other Java versions?

```shell
Java 11
```

**Comment by karianna** [comment]
@pekuz Can you try with our latest 17.0.4.1?

**Comment by pekuz** [comment]
OK, I have used the latest available, see below:

```
PS C:\app\jdk-17.0.5+8> bin/jshell
|  Welcome to JShell -- Version 17.0.5
|  For an introduction type: /help intro

jshell> new URI("ftps", "p.e.local|SIT@p.e.local", "/path", null)
|  Exception java.net.URISyntaxException: Illegal character in authority at index 7: ftps://p.e.local|SIT@p.e.local/path
|        at URI$Parser.fail (URI.java:2974)
|        at URI$Parser.parseAuthority (URI.java:3308)
|        at URI$Parser.parseHierarchical (URI.java:3219)
|        at URI$Parser.parse (URI.java:3175)
|        at URI.<init> (URI.java:708)
|        at URI.<init> (URI.java:809)
|        at (#1:1)
```

The same wrong error message.

**Comment by karianna** [comment]
@pekuz Hmm, that's interesting :-).  Are you just concerned that the Exception is reporting the incorrect index number or do you believe that `|` should be a valida character in a URI?

**Comment by karianna** [comment]
FYI - I replicated this in 11.0.16.1 as well

**Comment by pekuz** [comment]
I'm sure about the incorrect index because ``p`` is a valid char. 

Indeed this evident smell raises subsequent questions.

For ``|``, it comes from observations that it is the pipe disrupting the URI. 


I'm not sure if ``|`` should or should not be rejected, spec-wise:

java.net.URI JavaDoc is silent on ``|``, the other category there matches non-US-ASCII chars, but ``|`` is US-ASCII char.  

RFC https://www.ietf.org/rfc/rfc2396.txt mentions ``|`` in the unwise category.

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8297687

**Comment by pekuz** [comment]
FYI, in our case the URIs with a pipe in user info component originated from IIS FTP virtual sites https://learn.microsoft.com/en-us/iis/publish/using-the-ftp-service/using-ftp-virtual-host-names-in-iis-7#logging-in-to-the-second-ftp-site-using-your-local-user-account :

_When prompted for a user name, enter the www.contoso.com virtual host name followed by the vertical line (|) character. For example: www.contoso.com|MyUser_

Users constructed corresponding URI in naïve way. Studying RFC 2396 more carefully: 

_unwise      = "{" | "}" | "|" | "\" | "^" | "[" | "]" | "`"
   Data corresponding to excluded characters must be escaped in order to
   be properly represented within a URI._

answers that `|` must be escaped as `%7C`. 

All in all, the error message mentions incorrect index for the URI that includes the unescaped excluded character.

Last but not least, thank you for reporting to JDK, the report is apt.

**Comment by karianna** [comment]
This was fixed in tip (20)

**Comment by pekuz** [comment]
Peeking into JDK issue and related commit, both new URI test coverage and explanation is sound. Thank you.
