### ISSUE TITLE
Eclipse crashes on pasting something in Editor.

### ISSUE THREAD

**Issue by vishalbandre** [adoptium/adoptium-support#612]
### Please provide a brief summary of the bug

It doesn't happen on each paste but it happens occasionally.

I experienced the same behavior on Eclipse 2022 and 2021.

Initially, I was using Eclipse 2022 but encountered this issue, so I did try to downgrade my Eclipse to 2021. But, some happens here as well.

My System:
Ubuntu 22.04 64bit
Processor: i5 11th Gen

### Please provide steps to reproduce where possible

// I am working with two IDEs because of my requirements.
// Eclipse 2021 (Java) and Android Studio (Kotlin).

For my particular project, I am manually converting Kotlin code to Java.

I have a Java class.

So to reproduce the issue. Our cycle is copying code snippets from Android studio and pasting them into any method in Java class inside eclipse.

Steps to Reproduce the issue:

i. Copy any Kotlin code snippet (body of any method inside any Kotlin class) from the Android Studio editor.
ii. To reproduce the issue: go inside any function in the Java class.
iii. Paste it in the eclipse into any method.
iv. The crash will occur.

Note: This doesn't happen on each paste, but, occasionally, and frequently.

### Expected Results

The content should have been pasted into the Eclipse editor.

### Actual Results

Instead, Eclipse is crashing. No results.

### What Java Version are you using?

java 17.0.1 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04 64bit

### How did you install Java?

With Ubuntu's apt installer.

### Did it work before?

```shell
No. I experienced the same issue on Eclipse 2021 as well as 2022.
```

### Did you test with other Java versions?

```shell
No
```

### Relevant log output

```shell
org.eclipse.m2e.logback.configuration: Activated before the state location was initialized. Retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/vish/dev/eclipse/2021/projects/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.16.3.20211002-1029.xml
org.eclipse.m2e.logback.configuration: Initializing logback
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.ui.model.AntModel (file:/home/vish/dev/eclipse/2021/plugins/org.eclipse.ant.ui_3.8.100.v20211011-0944.jar)
WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.ui.model.AntModel
WARNING: System::setSecurityManager will be removed in a future release
env: ‘/home/vish/dev/eclipse/2021/projects/processing-addon-for-artisan/src/artisan/brush/Dino.java’: Permission denied
org.eclipse.m2e.logback.configuration: Activated before the state location was initialized. Retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/vish/dev/eclipse/2021/projects/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.16.3.20211002-1029.xml
org.eclipse.m2e.logback.configuration: Initializing logback
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.ui.model.AntModel (file:/home/vish/dev/eclipse/2021/plugins/org.eclipse.ant.ui_3.8.100.v20211011-0944.jar)
WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.ui.model.AntModel
WARNING: System::setSecurityManager will be removed in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8847b3c3c4, pid=54325, tid=54327
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/vish/dev/eclipse/2021/core.54325)
#
# An error report file with more information is saved as:
# /home/vish/dev/eclipse/2021/hs_err_pid54325.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by karianna** [comment]
@vishalbandre can you try with the latest 17.0.5 and report and crash log here?

**Comment by ianbrown49** [comment]
Same issue here.  Happened twice today, so far. Some days does not happen at all. Happens with ctrl+v paste.
Version:
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2022-12 (4.26.0)
Build id: 20221201-1913
OS: Linux, v.4.18.0-448.el8.x86_64, x86_64 / gtk 3.22.30
Java vendor: Oracle Corporation
Java runtime version: 18.0.2+9-61
Java version: 18.0.2
Crash terminal output showed:
# A fatal error has been detected by the Java Runtime Environment:
# SIGSEGV (0xb) at pc=0x00007f6081baf654, pid=5080, tid=5081
# JRE version: Java(TM) SE Runtime Environment (18.0.2+9) (build 18.0.2+9-61)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.2+9-61, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libcairo.so.2+0x65654]  cairo_region_num_rectangles+0x4
 The crash happened outside the Java Virtual Machine in native code.

[hs_err_pid5080.log](https://github.com/adoptium/adoptium-support/files/10796969/hs_err_pid5080.log)

**Comment by karianna** [comment]
@ianbrown49 18.0.2 is no longer in support, please try latest 19.0.2

**Comment by pegasus0021** [comment]
Did anyone resolve the issue.

**Comment by karianna** [comment]
@pegasus0021 This was resolved in the latest release of the Eclipse IDE

**Comment by MariuszTerebecki** [comment]
w której ? zainstalowałem java19, eclipse Version: 2023-09 (4.29.0) Build id: 20230907-1323 i nadal występuje

**Comment by urbandroid** [comment]
Same error happens with 
Version: 2023-12 (4.30.0)
Build id: 20231201-2043

Copy paste crashes eclipse it is a blocker
