### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by treatmeniceplz** [adoptium/adoptium-support#622]
## Question
can someone help me understand this crash report?

## Context
i am trying to launch feather client and it crashed
Java version:1.19

java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
Your operating system and platform:
windows 11 22h2 on x86-64

[latest.log](https://github.com/adoptium/adoptium-support/files/9941629/latest.log)

**Comment by danavis** [comment]
Reporting this, with the hope it's useful for the devs. Should I post hs_err_pid4180.log somewhere?

(Eclipse:4180): Gtk-CRITICAL **: 19:42:11.735: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff3cf4f3ee6, pid=4180, tid=4238
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x6d5ee6][thread 4184 also had an error]
  void OopOopIterateDispatch<G1CMOopClosure>::Table::oop_oop_iterate<InstanceKlass, narrowOop>(G1CMOopClosure*, oopDesc*, Klass*)+0x1c6
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/mcastro/core.4180)
#
# An error report file with more information is saved as:
# /home/XXXXXXXXXXXXXXXXXX/hs_err_pid4180.log
#
# If you would like to submit a bug report, please visit:

**Comment by karianna** [comment]
Can you try with the latest 17.0.5?  And yes that hs_err log is most helpful.

**Comment by treatmeniceplz** [comment]
I'll try tommorow afternoon

**Comment by treatmeniceplz** [comment]
when it just works
