### ISSUE TITLE
Random Crash with Log

### ISSUE THREAD

**Issue by Steddo** [adoptium/adoptium-support#624]
### Please provide a brief summary of the bug

Minecraft simply crashes. This only happens when I play; it doesn't crash in my long overnight AFK sessions.

[hs_err_pid21168.log](https://github.com/adoptium/adoptium-support/files/9945155/hs_err_pid21168.log)

### Please provide steps to reproduce where possible

I could not reproduce it intentionally. It happens at random.

### Expected Results

Minecraft plays without crashing.

### Actual Results

Minecraft crashes randomly.

### What Java Version are you using?

openjdk 17.0.4.1 2022-08-12OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

**Comment by karianna** [comment]
Minecraft usually ships with its own Microsoft Build of OpenJDK 17.0.3 - have you tried using that default?  Also you can try our latest 17.0.5 release.

That said the crash report is saying that com.seibel.lod.core.builders.lodBuilding.bufferBuilding.LodQuadBuilder.mergeQuadsInternal is calling somewthing in OpenGL native which is crashingso I'd also try to make sure your graphics drivers are up to date and contact the Mod owner as well.

**Comment by Steddo** [comment]
I'm pretty sure that _com.seibel.lod.core.builders.lodBuilding.bufferBuilding.LodQuadBuilder.mergeQuadsInternal_ is from my Distant Horizons mod, so I will try to see if it still crashes once I've removed it.

If it does eliminate crashes, I'll update this thread and contact the mod dev.
