### ISSUE TITLE
Software crashed on linux(Ubuntu)

### ISSUE THREAD

**Issue by pramit57** [adoptium/adoptium-support#628]
### Please provide a brief summary of the bug

Software loads the main GUI, but then crashes when I do anything next. Log attached. 

[hs_err_pid4089040.log](https://github.com/adoptium/adoptium-support/files/9972346/hs_err_pid4089040.log)

### Please provide steps to reproduce where possible

Open Openchrom
Click on any option 

### Expected Results

Not crash

### Actual Results

It crashes 

### What Java Version are you using?

openjdk 11.0.16 2022-07-19 OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 20.04.4 LTS

**Comment by karianna** [comment]
@pramit57 Can you please try with 11.0.17 and post the results here?

**Comment by pramit57** [comment]
I installed 11.0.17:
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
[hs_err_pid2529.log](https://github.com/adoptium/adoptium-support/files/9995422/hs_err_pid2529.log)

But I still have the same issue with openchrom

I looked at the log and it(the software) is using 17.0.4 as the JRE version
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4+8 (17.0.4+8) (build 17.0.4+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (17.0.4+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libgobject-2.0.so.0+0x3dfc1]  g_type_check_instance_is_fundamentally_a+0x11

[hs_err_pid2529.log](https://github.com/adoptium/adoptium-support/files/9995424/hs_err_pid2529.log)

**Comment by karianna** [comment]
@pramit57  - I would log an issue with OpenChrom and ask them to bundle with 17.0.5 instead.

**Comment by karianna** [comment]
11.0.18 was released. REcommend trying that version
