### ISSUE TITLE
Add release for Ubuntu 22.10 (kinetic)

### ISSUE THREAD

**Issue by grigojev** [adoptium/adoptium-support#633]
After updating to 22.10 I am now getting this error, when running `sudo apt update`

Err:7 https://packages.adoptium.net/artifactory/deb kinetic Release
  404  Not Found [IP: 54.148.95.12 443]
Reading package lists... Done
E: The repository 'https://packages.adoptium.net/artifactory/deb kinetic Release' does not have a Release file.

_Originally posted by @grigojev in https://github.com/adoptium/adoptium-support/issues/632#issuecomment-1316812634_

**Comment by gdams** [comment]
closing in favour of https://github.com/adoptium/installer/issues/561
