### ISSUE TITLE
JVM can access all cpu cores on host even when container limits are set

### ISSUE THREAD

**Issue by cleitus** [adoptium/adoptium-support#638]
since `17.0.5`, I've noticed that my java application running in a container has access to all the cores on my host machine even when setting cpu contraints on container runtime (either with `--cpus`, `--cpu-shares` or even in kubernetes with resource limits).

Here is a test app with cpu limit set to "1", running in a kubernetes pod:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/7240895/203778182-03a36ab1-f711-481d-a57a-1cb586317c43.png">

As we can see, it seems that our app disregards the limits set on cpu completely.

we could also exec into the container and run `java -XshowSettings:system -version`:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/7240895/203779882-689ffc96-d69a-41b0-be65-e0f62f570055.png">

&rarr; `Effective CPU Count: 32`

or with `jshell`:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/7240895/203779617-608c8148-31f4-496d-add2-02b942a6943a.png">

the observed behaviour might be caused by this update: https://bugs.openjdk.org/browse/JDK-8289568

--- 

When running the same test on `eclipse-temurin:17.0.4.1_1-jdk` (with `{"resources":{"requests":{"cpu":"1000m"}}}` or when explicitly setting `-XX:ActiveProcessorCount=1` this behaviour is no longer observed:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/7240895/203781211-fbc43cb5-d24a-40bb-8487-3b4eae33f5cf.png">

and `Effective CPU Count: 1` and `Runtime.getRuntime().availableProcessors()` returns `1`

**Comment by jerboaa** [comment]
Please explain:

1. How exactly you are limiting CPU: `--cpus` switch of your container engine, or `--cpu-shares` (they're not the same). On kubernetes limits should result in `--cpu-quota/--cpu-period` settings. Please be precise.
2. If you expect a limit based on CPU shares only, then yes. [JDK-8289568](https://bugs.openjdk.org/browse/JDK-8289568) is the change (intentional). Use `-XX:+UseContainerCpuShares` in that case. See https://bugs.openjdk.org/browse/JDK-8282931
3. Debug output of `-Xlog:os+container=trace` would be useful too.

**Comment by jerboaa** [comment]
Note: The output of `java -XshowSettings:system -version` suggests you are running a setup which uses `cpu-shares` only.

**Comment by cleitus** [comment]
Hello, thanks for the reply

The behaviour described above was observed when running the test on `temurin_17.0.5` with each of the following configs individually (I've also tried combining them):
- `--cpus=1`
- `--cpu-shares=1024`
- in kubernetes with:
```
resources:
  limits:
    cpu: "1000m"
```

Specifically though, the plots and screenshots from above are from a basic kubernetes pod with the following configuration:
```
args:
  - --cpus
  - "1"
resources:
  requests:
    cpu: "500m"
    memory: 512Mi
  limits:
    cpu: "1000m"
    memory: "1024Mi"
```
here's the output of `-Xlog:os+container=trace` from that instance:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/7240895/203822794-eb62fabc-f7eb-4955-8d0a-fa36cbfec123.png">

**Comment by jerboaa** [comment]
Please paste the content of the following 3 files on that pod:

- `/proc/cgroups`
- `/proc/self/cgroup`
- `/proc/self/mountinfo`

**Comment by cleitus** [comment]
`/proc/cgroups`:
```
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  6       195     1
cpu     5       238     1
cpuacct 5       238     1
blkio   7       238     1
memory  10      811     1
devices 2       234     1
freezer 8       195     1
net_cls 3       195     1
perf_event      4       195     1
net_prio        3       195     1
hugetlb 11      195     1
pids    9       238     1
rdma    12      195     1
```

`/proc/self/cgroup`:
```
12:rdma:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
11:hugetlb:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
10:memory:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
9:pids:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
8:freezer:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
7:blkio:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
6:cpuset:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
5:cpu,cpuacct:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
4:perf_event:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
3:net_cls,net_prio:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
2:devices:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
1:name=systemd:/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
0::/kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba
```

`/proc/self/mountinfo`:
```
16616 4170 0:321 / / rw,relatime master:1387 - overlay overlay rw,lowerdir=/var/lib/docker/overlay2/l/BLKLC2ZOLZDEDRUV5I2VEPKOYJ:/var/lib/docker/overlay2/l/YXP3ZPHNQTSLTOIPI3Y2TY3LEU:/var/lib/docker/overlay2/l/IJZMHMBZVBPAMLKEWYSGPVNB5I:/var/lib/docker/overlay2/l/F3H5EUBM2RMDHVULYJI73WNNC5:/var/lib/docker/overlay2/l/XR33RYUECLCQX3VNDFPA25BNV3:/var/lib/docker/overlay2/l/A5X5V4ZGMHSUAXQGZXHSGGCUV2,upperdir=/var/lib/docker/overlay2/a007a336c53236078edcefe428c816f8e8e0f5327aebcdef52fb35214cc30e76/diff,workdir=/var/lib/docker/overlay2/a007a336c53236078edcefe428c816f8e8e0f5327aebcdef52fb35214cc30e76/work
16617 16616 0:335 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
16618 16616 0:336 / /dev rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
16619 16618 0:337 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
16620 16616 0:19 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
16621 16620 0:338 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
16645 16621 0:25 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime master:10 - cgroup cgroup rw,xattr,name=systemd
16646 16621 0:28 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime master:14 - cgroup cgroup rw,devices
16647 16621 0:29 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/net_cls,net_prio ro,nosuid,nodev,noexec,relatime master:15 - cgroup cgroup rw,net_cls,net_prio
16648 16621 0:30 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,perf_event
16649 16621 0:31 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:17 - cgroup cgroup rw,cpu,cpuacct
16650 16621 0:32 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime master:18 - cgroup cgroup rw,cpuset
16651 16621 0:33 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime master:19 - cgroup cgroup rw,blkio
16652 16621 0:34 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime master:20 - cgroup cgroup rw,freezer
16653 16621 0:35 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/pids ro,nosuid,nodev,noexec,relatime master:21 - cgroup cgroup rw,pids
16654 16621 0:36 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime master:22 - cgroup cgroup rw,memory
16655 16621 0:37 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime master:23 - cgroup cgroup rw,hugetlb
16656 16621 0:38 /kubepods/burstable/podd7874f44-eee0-423c-83c9-f246075bdde1/fbaa59723cd1f05d310e6f48b5d49a9d9e9552b7fde2205d0a2e2b5f60ec21ba /sys/fs/cgroup/rdma ro,nosuid,nodev,noexec,relatime master:24 - cgroup cgroup rw,rdma
16741 16618 0:274 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
16742 16618 8:1 /var/lib/kubelet/pods/d7874f44-eee0-423c-83c9-f246075bdde1/containers/springboot-redis-client/284a7374 /dev/termination-log rw,relatime - ext4 /dev/sda1 rw,commit=30
16743 16616 8:1 /var/lib/docker/containers/28a68f7fc33136956645603e4bbb191d06ccfa1d7870ee9db71d4c97addf76ae/resolv.conf /etc/resolv.conf rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
16744 16616 8:1 /var/lib/docker/containers/28a68f7fc33136956645603e4bbb191d06ccfa1d7870ee9db71d4c97addf76ae/hostname /etc/hostname rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
16745 16616 8:1 /var/lib/kubelet/pods/d7874f44-eee0-423c-83c9-f246075bdde1/etc-hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,commit=30
16746 16618 0:263 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
16747 16616 0:248 / /run/secrets/kubernetes.io/serviceaccount ro,relatime - tmpfs tmpfs rw,size=1048576k
4171 16617 0:335 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
4172 16617 0:335 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
4173 16617 0:335 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
4174 16617 0:335 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
4175 16617 0:335 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
4176 16617 0:345 / /proc/acpi ro,relatime - tmpfs tmpfs ro
4177 16617 0:336 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
4178 16617 0:336 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
4179 16617 0:336 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
4180 16617 0:371 / /proc/scsi ro,relatime - tmpfs tmpfs ro
4181 16620 0:372 / /sys/firmware ro,relatime - tmpfs tmpfs ro
```

**Comment by jerboaa** [comment]
Nothing obvious stands out. `spec.containers[].resources.limits.cpu` should result in corresponding period/quota settings in `cpu.cfs_period_us` and `cpu.cfs_quota_us` values. Not sure why it doesn't for you.

> Specifically though, the plots and screenshots from above are from a basic kubernetes pod with the following configuration:
> 
> ```
> args:
>   - --cpus
>   - "1"
> resources:
>   requests:
>     cpu: "500m"
>     memory: 512Mi
>   limits:
>     cpu: "1000m"
>     memory: "1024Mi"
> ```

You do set this for the specific container, right (not the pod)? https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-1

I've never used `args`. Does it change if you remove it?

**Comment by cleitus** [comment]
> You do set this for the specific container, right (not the pod)? https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-1

yes ofc, the deployment would fail anyways if the yaml wasn’t correct

> I've never used `args`. Does it change if you remove it?

Nothing changes. Only 'fix' is to revert to an image older than `17.0.5` (for example `temurin-17.0.4.1`) or explicitly setting `-XX:ActiveProcessorCount=1`... hence why I thought it justifiable to open this ticket

**Comment by cleitus** [comment]
**update**: I was unable to replicate the issue on my local minikube!

**Comment by jerboaa** [comment]
> The only 'fix' (tested on gke) is to revert to an image older than `17.0.5` (for example `temurin-17.0.4.1`) or explicitly setting `-XX:ActiveProcessorCount=1`... hence why I thought it justifiable to open this ticket

If reverting to `17.0.4.1` makes a difference then there also should be a difference if you specified `-XX:+UseContainerCpuShares` with `17.0.5`. That's the only change I'm aware of in the container detection space wrt CPUs.

**Comment by cleitus** [comment]
> If that was different, say 1 for requests and 2 for limit, then you should see a similar change with `17.0.4.1` if cpu quota don't end up being set in your deployment.

That seems to pe the issue, the system is applying the default limits (which happens to be 1024 shares) no matter what I tell it. Thanks for the insight and sorry to have wasted your time.
