### ISSUE TITLE
Java application under development crashes

### ISSUE THREAD

**Issue by DavidGauntt** [adoptium/adoptium-support#640]
### Please provide a brief summary of the bug

I am developing a Java application using Eclipse.  Several times a week the application crashes while running in Eclipse in debug mode.  It always crashes in the thread JavaThread "JDWP Transport Listener: dt_socket" daemon; I have attached a sample minidump. 

This bug had been previously reported and fixed (https://bugs.openjdk.org/browse/JDK-8211909); the fix had been applied in JDK11, but I am running JDK17 and Java 18  so it appears to have returned.

[hs_err_pid21124.log](https://github.com/adoptium/adoptium-support/files/10094117/hs_err_pid21124.log)

### Please provide steps to reproduce where possible

 This typically happens after I have edited code several times while running the code in debug mode; I cannot say whether it has ever happened without doing any edits.  However, it is intermittent and cannot be reliably reproduced.

### Expected Results

Application runs without crashing

### Actual Results

Crash is caused by siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005) in the thread "JDWP Transport Listener: dt_socket"

### What Java Version are you using?

java 18.0.2.1 2022-08-18

### What is your operating system and platform?

Windows 11

### How did you install Java?
As part of a JDK installation for Eclipse

### Did it work before?

It usually works

### Did you test with other Java versions?
No

### Relevant log output

See attached file

**Comment by karianna** [comment]
@DavidGauntt Can you try with the latest 17.0.5 and post the log file here?

**Comment by DavidGauntt** [comment]
I just installed 17.0.5, and will post a log file if I see another crash.
