### ISSUE TITLE
Running comsol job on cluster with slurm: A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by joergle** [adoptium/adoptium-support#643]
## Question
Hello, I am running a cluster with 6 nodes under Ubuntu 18.04 with slurm. I am using different versions of comsol. Until comsol version 5.6 the cluster runs without problems. Starting with version 6.0 and following with 6.1, I get an Java Runtime error, when I want to run a cluster computation. Comsol 6.0 and 6.1 work without a problem when I run it on a single node without slurm. 
Here, what comsol writes:
"COMSOL is shipped with OpenJDK 11.0.13. You can choose an alternative Java® 11 version 11.0.9.1 or later during installation."
I get the error with the build in OpenJDK as well as with the installed version.

Does anybody have an idea how to fix the problem ?
Here the error log:
[hs_err_pid18391.log](https://github.com/adoptium/adoptium-support/files/10133434/hs_err_pid18391.log)

## Context

Java version:

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu218.04, mixed mode, sharing)

Your operating system and platform:

Ubuntu 18.04 on x86-64

**Comment by karianna** [comment]
@joergle  The error logs states you are using 11.0.13, are you able to provide a crash log from 11.0.17?
