### ISSUE TITLE
SIGSEGV, PhaseIdealLoop::spinup

### ISSUE THREAD

**Issue by Jammy42** [adoptium/adoptium-support#646]
### Please provide a brief summary of the bug

Hello

Any got this and knows a workaround ?

# SIGSEGV (0xb) at pc=0x00007effe3232f33, pid=1, tid=256
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16+8 (11.0.16+8) (build 11.0.16+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (11.0.16+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V [libjvm.so+0xe20f33] PhaseIdealLoop::spinup(Node*, Node*, Node*, Node*, Node*, small_cache*) [clone .part.48]+0x53

### Please provide steps to reproduce where possible

It randomly happens.

### Expected Results

n/a

### Actual Results

n/a

### What Java Version are you using?

openjdk version "11.0.16" 2022-07-19  OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8)  OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

### What is your operating system and platform?

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

### How did you install Java?

n/a

### Did it work before?

```shell
yes
change : n/a
```

### Did you test with other Java versions?

```shell
ok: 11.0.10 (AdoptOpenJDK)

nok:  11.0.14.1 (Eclipse Adoptium), 11.0.16 (Eclipse Adoptium)
```

### Relevant log output

```shell
n/a
```

**Comment by karianna** [comment]
@Jammy42 Can you try the latest 11.0.17 and see if that resolves the issue?

**Comment by Jammy42** [comment]
Hi,

the problem is, that the JDK is included in a docker image and this is provided. Also it will take some effort to convince the creator of the image to change the JDK version.

I was wondering if an external java parameter might help. Even if someone could  give a hint, what "PhaseIdealLoop::spinup" is all about. Possibly one could tweak something.

Thanks & Regards
John

**Comment by karianna** [comment]
Does the crash output also point you to the hs_err log file, the crash log is usually written to /tmp - I may be able to spot something in there

**Comment by karianna** [comment]
@Jammy42 you may have luck with 11.0.18 - please do let us know if you see a future crash.
