### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment with eclipse-temurin:11.0.17_8-jre-alpine

### ISSUE THREAD

**Issue by kg185106** [adoptium/adoptium-support#652]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000003fd6, pid=1, tid=7
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  0x0000000000003fd6
#
# Core dump will be written. Default location: /core.%e.1.%t
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#

### Please provide steps to reproduce where possible

spring boot application with docker image eclipse-temurin:11.0.17_8-jre-alpine in kubernates cluster 

### Expected Results

should not crash the jvm

### Actual Results

should not crash the jvm

### What Java Version are you using?

11.0.17+8

**Comment by karianna** [comment]
@kg185106 Are you able to provide either:

Core dump will be written. Default location: /core.%e.1.%t

OR 
An error report file with more information is saved as:

/tmp/hs_err_pid1.log

**Comment by kg185106** [comment]
sorry, i do not have core dump or /tmp/hs_err_pid1.log file . we moved to diffrent os docker image. with diffrent os  docker image application working fine.
