### ISSUE TITLE
JSSE classpath changed between version 11 and 17?

### ISSUE THREAD

**Issue by c-k-ong** [adoptium/adoptium-support#653]
## Question

I have an Apache Ant mail task (see below) that works when I use Java 11, but fails with the error message "could not instantiate ssl security provider, check that you have JSSE in your classpath" when I switch to Java 17. I would like to know if there have been changes to anything relevant to JSSE in between versions.

```
<target name="email" depends="init" unless="email.skip">
	<condition property="build.version.stableStatus" value="stable" else="non-stable">
		<or>
			<matches string="${build.version.tag}" pattern="^GA$"/>
			<matches string="${build.version.tag}" pattern="^GA-E[0-9]{2}$"/>
		</or>
	</condition>
	<echo message="is stable: ${build.version.stableStatus}"/>
	<mail mailhost="${email.host}" mailport="${email.port}" ssl="${email.ssl}" user="${email.smtp.user}" password="${email.smtp.password}" 
              replyto="${email.from}" from="${email.from}" tolist="${email.to}" cclist="${email.cc}"
              subject="The ${build.version} build has completed">
		<message>Email body here</message>
	</mail>
</target>
```

## Context

Java version:

Mail task worked on this version:

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK Client VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

Mail task failed on this version:

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

Your operating system and platform:

Windows Server 2016 Standard 64-bit

**Comment by karianna** [comment]
@c-k-ong Which version of Ant and the Ant mail task are you using?

**Comment by c-k-ong** [comment]
I am using Ant 1.10.12. I am not sure of the exact version of ant-javamail, but the manifest has this:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.9
Created-By: 11.0.8+10 (AdoptOpenJDK)

Name: org/apache/tools/ant/taskdefs/optional/
Extension-Name: org.apache.tools.ant
Specification-Title: Apache Ant
Specification-Version: 1.10.12
Specification-Vendor: Apache Software Foundation
Implementation-Title: org.apache.tools.ant
Implementation-Version: 1.10.12
Implementation-Vendor: Apache Software Foundation
```

**Comment by karianna** [comment]
You'll want to contact the ant mailing lists about this.  The version of Ant you are using is the latest and is baselined off Java 8 and likely works out of the box for 11 but they may have not added 17 support yet.

Mailing list details:   https://ant.apache.org/mail.html
