### ISSUE TITLE
SIGSEGV in org.infinispan.container.DefaultDataContainer.purgeExpired

### ISSUE THREAD

**Issue by rus-99-pk** [adoptium/adoptium-support#654]
### Please provide a brief summary of the bug

The bug manifests itself some time after the application is launched in the Tomcat servlet container.

[hs_err_pid87934.log.zip](https://drive.google.com/file/d/1zib9dKNFrjW1G4XFnozD5fLoWH2KQCSs/view?usp=sharing)

### Please provide steps to reproduce where possible

Ready to reproduce if necessary.

### Expected Results

No crash

### Actual Results

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f24aaccc0a0, pid=87934, tid=88033

JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
Problematic frame:
J 21973 c1 org.hibernate.engine.spi.CollectionKey.<init>(Lorg/hibernate/persister/collection/CollectionPersister;Ljava/io/Serializable;)V (38 bytes) @ 0x00007f24aaccc0a0 [0x00007f24aaccc060+0x0000000000000040]

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)

### What is your operating system and platform?

Ubuntu 20.04.5 LTS, x64

### How did you install Java?

Binary archive, tar.gz.

### Did it work before?

```shell
This worked before updating the OS version from 18.04 to 20.04.
```

### Did you test with other Java versions?

```shell
No
```

**Comment by karianna** [comment]
@rus-99-pk Please update to 11.0.17

**Comment by rus-99-pk** [comment]
Hello!

Solved the problem by rolling back the version of the Linux kernel.
