### ISSUE TITLE
 SIGSEGV in PSPromotionManager::copy_to_survivor_space<false>(oopDesc*)

### ISSUE THREAD

**Issue by rus-99-pk** [adoptium/adoptium-support#655]
### Please provide a brief summary of the bug

The bug manifests itself some time after the application is launched in the Tomcat servlet container.

[hs_err_pid75373.log](https://drive.google.com/file/d/1E7eQ8JOo1UGfr1lAK56F7Ov6zmyLSw5I/view?usp=sharing)

### Please provide steps to reproduce where possible

Ready to reproduce if necessary and send the necessary data.

### Expected Results

No crash

### Actual Results

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007ff36385fba4, pid=75373, tid=75387

JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
Problematic frame:
V  [libjvm.so+0xcffba4]  oopDesc* PSPromotionManager::copy_to_survivor_space<false>(oopDesc*)+0x144

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)

### What is your operating system and platform?

Ubuntu 20.04.5 LTS, x64

### How did you install Java?

Binary archive, tar.gz.

### Did it work before?

```shell
This worked before updating the OS version from 18.04 to 20.04.
```

### Did you test with other Java versions?

```shell
No
```

**Comment by karianna** [comment]
Dup of #654
