### ISSUE TITLE
SIGSEGV in ru.naumen.metainfo.shared.ClassFqn.equals(Ljava/lang/Object;)

### ISSUE THREAD

**Issue by rus-99-pk** [adoptium/adoptium-support#657]
### Please provide a brief summary of the bug

The bug manifests itself some time after the application is launched in the Tomcat servlet container.

[hs_err_pid97770.log.zip](https://drive.google.com/file/d/1sFuG-Phm9CSgvB5tHHEuXXSWCfmmkAN5/view?usp=share_link)

### Please provide steps to reproduce where possible

Ready to reproduce if necessary and send the necessary data.

### Expected Results

No crash

### Actual Results

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f52866894b3, pid=97770, tid=98800

JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
Problematic frame:
J 14262 c1 ru.naumen.metainfo.shared.ClassFqn.equals(Ljava/lang/Object;)Z (39 bytes) @ 0x00007f52866894b3 [0x00007f5286689460+0x0000000000000053]

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)

### What is your operating system and platform?

Ubuntu 20.04.5 LTS, x64

### How did you install Java?

Binary archive, tar.gz.

### Did it work before?

```shell
This worked on OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7) before updating the OS version from 18.04 to 20.04.
```

### Did you test with other Java versions?

```shell
Yes.

OpenJDK Runtime Environment Temurin-11.0.12+7.
```

**Comment by karianna** [comment]
Dup of #654
