### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by tranthanh1699** [adoptium/adoptium-support#658]
### Please provide a brief summary of the bug

Hello, I am running Ecu worx base on Eclipse. When I build my project using cmd. When I run command ecu.worx -bsw rebuild it have the log error: 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001d9afd812cf, pid=12772, tid=15892
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, parallel gc, windows-amd64)
# Problematic frame:
# v  ~StubRoutines::atomic_add_long
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\RHN6HC\Desktop\BCAN\MG1CA940_XH1_L8_I100R1\hs_err_pid12772.log
Could not load hsdis-amd64.dll; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

I have used older version but it require jdk and vm like that. 
I have tried reinstalling java but it had same error

### Expected Results

I expected i can build project with ecu worx

### Actual Results

cmd log error and i can't build my project

### What Java Version are you using?

java-jdk 11.0.16.1

### What is your operating system and platform?

windows 10 x64 

### How did you install Java?

I install in my company tool base

**Comment by karianna** [comment]
@tranthanh1699 Can you try 11.0.17 and post the error log here?  (C:\Users\RHN6HC\Desktop\BCAN\MG1CA940_XH1_L8_I100R1\hs_err_pid12772.log)
