### ISSUE TITLE
JNI version above 10

### ISSUE THREAD

**Issue by romainwallon** [adoptium/adoptium-support#660]
## Question

I am currently trying to run Java code from a C++ program (and not the other way around, as it may be more often the case I guess).
To this end, I used JNI to create a JVM, create Java objects and invoke Java methods.
While everything works fine, I noticed that the highest possible Java version to set for the JVM is `JNI_VERSION_10`, which requires that the Java classes are compiled with Java 10 as target, even when Java 17 is installed.
This will be hard to maintain in the future, as new Java versions will continue to be released, and bring features that will be incompatible with Java 10.

I was thus wondering whether JNI was deprecated (which does not seems to be the case yet)?
And if it is the case, what is the alternative to invoke Java code from a C++ program?
I had a look at project Panama, but it seems to be designed to invoke native code from Java classes, without bringing anything new to invoke Java code from C++.

Best regards,
Romain Wallon

## Context

Java version:

```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```

Your operating system and platform:

(true for any OS)

**Comment by jerboaa** [comment]
Latest JDK has `JNI_VERSION_20`. So this should be a non-issue as compiling sources with `--target 10` is well supported with JDK 17. For later JDK versions, later JNI versions are available. See the `getVersion` JNI functions below on how to deal with the relevant versions.

For details see:
https://docs.oracle.com/en/java/javase/19/docs/specs/jni/functions.html#getversion
https://docs.oracle.com/en/java/javase/17/docs/specs/jni/functions.html#getversion

**Comment by romainwallon** [comment]
Thanks for your quick answer.

Indeed, I used the `--target 10` to compile the Java code and allow to run it through JNI.
However, this requires the code to be compatible with Java 10, and thus forbids the use of new methods/types introduced in later versions.

So I am happy to learn that new JDKs will have their corresponding `JNI_VERSION`.
