### ISSUE TITLE
JVM crash with SIGSEGV in ciObjectFactory::ensure_metadata_alive(ciMetadata*)

### ISSUE THREAD

**Issue by allangandelman** [adoptium/adoptium-support#661]
### Please provide a brief summary of the bug

JVM crashed when running the "C2 CompilerThread4" thread

### Expected Results

JVM works normally and the C2 compiler doesn't crash.

### Actual Results

The JVM crashed with the report:

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f62def7b3ef, pid=22481, tid=0x00007f614c77c700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.291-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x40f3ef]  ciObjectFactory::ensure_metadata_alive(ciMetadata*)+0x1f

And stack:

Stack: [0x00007f614c67c000,0x00007f614c77d000],  sp=0x00007f614c779ae0,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x40f3ef]  ciObjectFactory::ensure_metadata_alive(ciMetadata*)+0x1f
V  [libjvm.so+0x40a7af]  ciMethodData::load_extra_data()+0x13f
V  [libjvm.so+0x40aa68]  ciMethodData::load_data()+0x218
V  [libjvm.so+0x3fa378]  ciMethod::method_data() [clone .part.72]+0xf8
V  [libjvm.so+0x94cfea]  Parse::Parse(JVMState*, ciMethod*, float)+0x63a
V  [libjvm.so+0x3c57c8]  ParseGenerator::generate(JVMState*)+0x68
V  [libjvm.so+0x55b995]  Parse::do_call()+0x315
V  [libjvm.so+0x957bc6]  Parse::do_one_bytecode()+0x3ba6
V  [libjvm.so+0x9492ac]  Parse::do_one_block()+0x1ec
V  [libjvm.so+0x9494aa]  Parse::do_all_blocks()+0xca
V  [libjvm.so+0x94d1c2]  Parse::Parse(JVMState*, ciMethod*, float)+0x812
V  [libjvm.so+0x3c57c8]  ParseGenerator::generate(JVMState*)+0x68
V  [libjvm.so+0x4814bd]  Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool)+0xbcd
V  [libjvm.so+0x3c4f1a]  C2Compiler::compile_method(ciEnv*, ciMethod*, int)+0xaa
V  [libjvm.so+0x48cc9c]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0x73c
V  [libjvm.so+0x48e8d8]  CompileBroker::compiler_thread_loop()+0x6d8
V  [libjvm.so+0xa86bbb]  JavaThread::thread_main_inner()+0xdb
V  [libjvm.so+0xa86ec1]  JavaThread::run()+0x2d1
V  [libjvm.so+0x915132]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x968a]  start_thread+0xca

### What Java Version are you using?

Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)

### What is your operating system and platform?

SUSE Linux Enterprise Server 12 (x86_64)

### How did you install Java?

Extracted a binary archive

### Did it work before?

```shell
Nothing changed, as far as we could identify,
```

**Comment by karianna** [comment]
@allangandelman Can you please try 1.8.0_352 from adoptium.net
