### ISSUE TITLE
CNC control software crashing

### ISSUE THREAD

**Issue by BlackWaterMS** [adoptium/adoptium-support#662]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe5d27acd4, pid=1692, tid=10948
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffe5d27acd4
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### Please provide steps to reproduce where possible

Open Firecontrol.exe 

### Expected Results

Firecontrol.exe should open and run properly 

### Actual Results

Firecontrol.exe crashes and I receive an error message that says "child process exited with code 1"

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)

### What is your operating system and platform?

Host: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx, 8 cores, 13G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1889)

### Did it work before?

```shell
Yes this was working fine until a recent windows update
```

**Comment by karianna** [comment]
@BlackWaterMS Can you try the latest 17.0.5 - any extra app or crash logs will also help.
