### ISSUE TITLE
No RISC-V 64 binaries in the latest 20 release

### ISSUE THREAD

**Issue by gounthar** [adoptium/adoptium-support#664]
### Please provide a brief summary of the bug

I test regularly the risc-v binaries supplied in the github temurin20-binaries [repository](https://github.com/adoptium/temurin20-binaries/releases).
The [latest release](https://github.com/adoptium/temurin20-binaries/releases/tag/jdk20-2022-12-21-12-31-beta) does not provide any risc-v binaries.
The [previous release](https://github.com/adoptium/temurin20-binaries/releases/tag/jdk20-2022-12-16-15-37-beta) does supply risc-v binaries.

### Expected Results

Risc-v binaries in each upcoming release.

### Actual Results

No risc-v binaries.

### What Java Version are you using?

java --version openjdk 20-beta 2023-03-21 OpenJDK Runtime Environment Temurin-20+28-202212161229 (build 20-beta+28-202212161229) OpenJDK 64-Bit Server VM Temurin-20+28-202212161229 (build 20-beta+28-202212161229, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04.1 LTS Armbian 22.08.0-trunk Jammy
Linux MQ-Pro 6.1.0-rc3-d1 #trunk Thu Dec  1 14:53:18 MSK 2022 riscv64 riscv64 riscv64 GNU/Linux

### How did you install Java?

tar gz from Temurin

**Comment by karianna** [comment]
@gounthar Risc-V is not currently a supported platform although it is being worked on.  I see you found our Slack so closing this for now.
