### ISSUE TITLE
JRE-only yum package

### ISSUE THREAD

**Issue by askmike1** [adoptium/adoptium-support#665]
## Question

Are there any plans to release a JRE-only (ie non-JDK) version of Temurin via yum package?

## Context

Java version: 

11 or 17

Your operating system and platform:

RHEL 7/8

**Comment by smlambert** [comment]
See related https://github.com/adoptium/installer/issues/430 feature request, which has been added to the 1Q 2023 plan.

**Comment by karianna** [comment]
Closing this as we have the linked issue
