### ISSUE TITLE
Stoneblock 3 Version 1.50 Crash on loading into World

### ISSUE THREAD

**Issue by DarkDon** [adoptium/adoptium-support#668]
### Please provide a brief summary of the bug

Created a new world, short view of some graphic , instant crash back to desktop
See log below:
[hs_err_pid16084.log](https://github.com/adoptium/adoptium-support/files/10291321/hs_err_pid16084.log)

### Please provide steps to reproduce where possible

Update to Stoneblock 3 1.50 , create world
see it crashing

### Expected Results

World loads in and i can play

### Actual Results

crash back to reality - no seriously back to desktop

### What Java Version are you using?

newest Version 

### What is your operating system and platform?

Windows 11 
I9700K
16 gigs 

### How did you install Java?

From the official java page

### Did it work before?

```shell
nope
```

### Did you test with other Java versions?

```shell
yup still wont work
```

**Comment by Talidorn** [comment]
If you are running on AMD...


Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

**Comment by DarkDon** [comment]
> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

THIS IS THE SOLUTION  !!!
