### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wnsgml0814** [adoptium/adoptium-support#669]
### Please provide a brief summary of the bug

[replay_pid3552.log](https://github.com/adoptium/adoptium-support/files/10293479/replay_pid3552.log)
game crash

### Please provide steps to reproduce where possible

start world and few sec 

### Expected Results

crash

### Actual Results

crash

### What Java Version are you using?

1.8.0_351-b10

### What is your operating system and platform?

window 11 redon 3600X 5700xt

**Comment by karianna** [comment]
@wnsgml0814 Which version of Java are you using?  I assume this is a modded Minecraft?

**Comment by Talidorn** [comment]
Try my fix from #666 

If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"
