### ISSUE TITLE
StoneBlock 3 Crashing after world loading

### ISSUE THREAD

**Issue by kraeon05** [adoptium/adoptium-support#672]
### Please provide a brief summary of the bug

Hi,

Need some help with Stone Block 3 crashing a few seconds after world is loaded.
This is a new world first time playing.
Tried re-installing but got the same error.
Disabled MineTogether chat as well.
Working on Stone Block 3 version 1.5.0
Java installed: (build 1.8.0_351-b10)
FTB launcher sent out this error report file.

[hs_err_pid3528.log](https://github.com/adoptium/adoptium-support/files/10305198/hs_err_pid3528.log)

### Please provide steps to reproduce where possible

Launch game normally and create new world.

### Expected Results

World loaded

### Actual Results

World loads but apps crashes after few seconds of world loading.

### What Java Version are you using?

Version 8 build 351 (build 1.8.0_351-b10)

### What is your operating system and platform?

Windows 10 , 64 bit Build 19041 (10.0.19041.2364)

### How did you install Java?

an installer package

### Relevant log output

```shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffeaea622f0, pid=3528, tid=10924
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x1222f0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by karianna** [comment]
Please try the recommended Microsoft Build of OpenJDK 17.0.3 (that comes built into the std Minecraft install) or Adoptium 17.0.5 and please post the error log here.

**Comment by rosaqq** [comment]
I let Overwolf take care of everything (recommended java setting) and got crash with the same problem
![image](https://user-images.githubusercontent.com/16641477/209681618-dc2bc0ab-b56c-4d6c-a729-f28131366df9.png)

Log:
[hs_err_pid38780.log](https://github.com/adoptium/adoptium-support/files/10308727/hs_err_pid38780.log)

**Comment by rosaqq** [comment]
Check #666  this fixed my issue
