### ISSUE TITLE
Yogscast complete pack ATLauncher always crashing when starting

### ISSUE THREAD

**Issue by arthurnog1711** [adoptium/adoptium-support#673]
## when starting the pack it crashes before starting and I can't solve it

log: https://paste.atlauncher.com/view/5be1803d-2c72-4018-a8cb-4d1b1c9db509

Java Version 8 Update 351

Windows 10 pro x64 21H2

**Comment by karianna** [comment]
I'm afraid we can't help with modded Minecraft.  The following log entry may give you a clue.

`[26/12/2022 23:41:32 PM] [SEVERE] [Forestry] myrathi.flatsigns.FlatSigns failed validation. Halting runtime for security reasons. Please replace your mods with untampered versions from the official download sites.`
