### ISSUE TITLE
Crashed during Startup

### ISSUE THREAD

**Issue by haynie777** [adoptium/adoptium-support#674]
### Please provide a brief summary of the bug

Attached are the 2 crash reports...

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff95fb52837, pid=2264, tid=0x0000000000001b30

[hs_err_pid2264.log](https://github.com/adoptium/adoptium-support/files/10311952/hs_err_pid2264.log)
[hs_err_pid7244.log](https://github.com/adoptium/adoptium-support/files/10311953/hs_err_pid7244.log)

### Please provide steps to reproduce where possible

Started up Surviving with RotaryCraft

### Expected Results

Program would run. 

### Actual Results

Errored out

### What Java Version are you using?

(build 1.8.0_351-b10

### What is your operating system and platform?

Build 19045

I am running on INTEL and not AMD.  I tried that suggestion anyways, but no luck.

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

From my solution to #666

**Comment by karianna** [comment]
@haynie777 see advice above.
