### ISSUE TITLE
Matching JDK source code reference for each installer binary release?

### ISSUE THREAD

**Issue by daluu** [adoptium/adoptium-support#680]
## Question

For your binary JDK installer distributions that you provide, for the various Java/JDK versions (8, 11, 17-19), irrespective of the OS plaform I think, where or how can I associate back to the matching OpenJDK source code tagged release or tagged version to pull the source code commits that match the specific binary installer version?

Is this process documented anywhere?

To summarize, given I download some version from https://adoptium.net/temurin/releases/, where/how can I find the matching OpenJDK source code to that installer?

I'm unfamiliar with such a process. And this is with respect to OSS use with proprietary code, in the case of using your installers. Technically, I assume we just have to provide a copy of the installer binary if all we use is just your installer, but in case of source code, would be good to know how to get a copy of the source code the binary was built against. In case to provide to users/customers upon request.

If this process isn't documented, would be nice if we can document it somewhere. Or provide links to the source code the binaries were built against.

**Comment by daluu** [comment]
FYI, I briefly tried to look via OpenJDK source code repo, but not sure if I have the correlation correct. So say I'm downloading/using JDK 11.0.17+8 would I be looking at something like this?

https://github.com/openjdk/jdk/releases/tag/jdk-11%2B17

or where would I find the source to the matching tagged release?

**Comment by karianna** [comment]
We mirror openjdk exactly, but to be absolutely sure you'll want to look at our tagged sources, for example:

https://github.com/adoptium/jdk11u/releases/tag/jdk-11.0.17%2B8_adopt
