### ISSUE TITLE
JDK-8297063 and eclipse-temurin:11.0.17_8-jdk ...

### ISSUE THREAD

**Issue by bgfootspi** [adoptium/adoptium-support#681]
Hello all,
can you tell me if this fix [JDK-8297063](https://bugs.openjdk.org/browse/JDK-8297063) is include ​​in the eclipse-temurin:11.0.17_8-jdk 
?
if not, will this patch be in jdk-11.0.18 scheduled for january 17th.

**Comment by jerboaa** [comment]
https://bugs.openjdk.org/browse/JDK-8293562 is the master bug. You'll see that it has a linked bug in the `Backports` section with `Fix Version` of `17.0.7` which corresponds to OpenJDK version `17.0.7`. As it doesn't have a `Fix Version` of `11.0.18`, it's not going to be in the January update of OpenJDK 11 (including Eclipse Temurin).

**Comment by bgfootspi** [comment]
thank you very much

I see the tag has been added.
can we expect a change soon?

**Comment by karianna** [comment]
@bgfootspi It will be up to a volunteer to back port this upstream.  If you have a commercial support contract with Red Hat or Azul then they may be able to accelerate that for you.

**Comment by bgfootspi** [comment]
thank's

**Comment by jerboaa** [comment]
11 backport is in progress. Please watch the upstream bug for progress.

**Comment by alograg** [comment]
Hi, backporting in [PR](https://github.com/openjdk/jdk11u-dev/pull/1825)

**Comment by gdams** [comment]
Backported to 11 via https://github.com/openjdk/jdk11u-dev/commit/770c1f65c588f3156f9b70097df752d8059c1038

**Comment by jerboaa** [comment]
And the fix is going to land in `11.0.21`  release (October 2023).
