### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment - openjdk11:x86_64-alpine-jre-11.0.16_8

### ISSUE THREAD

**Issue by sebastiancapus** [adoptium/adoptium-support#682]
### Please provide a brief summary of the bug

Hello,
We have multiple microservices deployed on a Kubernetes cluster, which are having as base image the following image: adoptopenjdk/openjdk11:x86_64-alpine-jre-11.0.16_8
-> [https://hub.docker.com/layers/adoptopenjdk/openjdk11/x86_64-alpine-jre-11.0.16_8/images/sha256-818447903a60cdc4d909a5f6d4f4d34027aaac34e476298f7def40906c5d69d6?context=explore](url)
During the time we observed that some pods are restarting which are being caused by the following error:

`#`
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`#  SIGSEGV (0xb) at pc=0x000076b41336cf33, pid=1, tid=12`
`#`
`# JRE version: OpenJDK Runtime Environment Temurin-11.0.16+8 (11.0.16+8) (build 11.0.16+8)`
`# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (11.0.16+8, mixed mode, tiered, compressed oops, serial gc,` `linuxamd64)`
`# Problematic frame:`
`# V  [libjvm.so+0xe20f33]  PhaseIdealLoop::spinup(Node*, Node*, Node*, Node*, Node*, small_cache*) [clone .part.48]+0x53`
`#`
`# Core dump will be written. Default location: Core dumps may be processed with "/bin/false" (or dumping  `
` to /home/app/core.1)`
`#`
`# An error report file with more information is saved as:`
`# /tmp/hs_err_pid1.log`
`[thread 36 also had an error][thread 83 also had an error]`
`[timeout occurred during error reporting in step ""] after 30 s.`
`#`
`# If you would like to submit a bug report, please visit:`
`#   https://github.com/adoptium/adoptium-support/issues`
`#`

We are going to increase the image to see if it's going to reproduce anymore, but we wanted to report the issue in case somebody will face it or it was not discovered yet.

### Please provide steps to reproduce where possible

Use the following docker image adoptopenjdk/openjdk11:x86_64-alpine-jre-11.0.16_8 and create workload which is using multiple threads heavily.

### Expected Results

Our expectation is that the error will no longer reproduce

### Actual Results

The pods was terminated due to this error.

### What Java Version are you using?

11.0.16_8

### What is your operating system and platform?

Alpine Linux 3.14.8

### How did you install Java?

Java was already provisioned by this image - adoptopenjdk/openjdk11:x86_64-alpine-jre-11.0.16_8 - https://hub.docker.com/layers/adoptopenjdk/openjdk11/x86_64-alpine-jre-11.0.16_8/images/sha256-818447903a60cdc4d909a5f6d4f4d34027aaac34e476298f7def40906c5d69d6?context=explore

### Did it work before?

```shell
I am no aware
```

### Did you test with other Java versions?

```shell
We will increase to the next stable patch available.
```

### Relevant log output

```shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000076b41336cf33, pid=1, tid=12
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16+8 (11.0.16+8) (build 11.0.16+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (11.0.16+8, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xe20f33]  PhaseIdealLoop::spinup(Node*, Node*, Node*, Node*, Node*, small_cache*) [clone .part.48]+0x53
#
# Core dump will be written. Default location: Core dumps may be processed with "/bin/false" (or dumping to /home/intakt/core.1)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
[thread 36 also had an error][thread 83 also had an error]


[timeout occurred during error reporting in step ""] after 30 s.
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by karianna** [comment]
Please use the 11.0.17 based container eclipse-temurin provided containers from DockerHub: https://hub.docker.com/layers/library/eclipse-temurin/11.0.17_8-jdk-alpine/images/sha256-b38e8084c8d4da4bf6ed975ca3adc5d0f2b4da931538f0abe9816c1edd025d62?context=explore
