### ISSUE TITLE
Fatal error has been detected by the JRE: # #  SIGSEGV (0xb) at pc=0x00007f6942443b51

### ISSUE THREAD

**Issue by rajaveld** [adoptium/adoptium-support#683]
### Please provide a brief summary of the bug

Encounter SIGSEGV and JVM get terminated, during execution of application by processing some large XML files. 

JVM behave differently on different -xmx values 

- If -xmx value is < 5GB execution end up with Out of Memory
- If -xmx value is > 7GB execution successful 
- If -xmx value ~6GB JVM crash with Fatal error SIGSEGV

> A fatal error has been detected by the Java Runtime Environment:
  SIGSEGV (0xb) at pc=0x00007f6942443b51, pid=21688, tid=23014
 JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
 Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 V  [libjvm.so+0xb01b51]  PhaseIdealLoop::build_loop_late_post(Node*)+0x181
 Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/test/server/Tomcat/bin/core.21688)
 If you would like to submit a bug report, please visit:
  https://github.com/adoptium/adoptium-support/issues

>---------------  S U M M A R Y ------------
Command Line: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Djava.util.logging.config.file=/home/test/server/Tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Xms256M -Xmx6144M -XX:+UseG1GC -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Djava.security.auth.login.config=../../portal/conf/jaas.config -Dcom.sun.xml.ws.fault.SOAPFaultBuilder.disableCaptureStackTrace=true -Dfile.encoding=UTF-8 -Dmail.mime.cachemultipart=false -Djava.awt.headless=true -Dedtftp.log.log4j=true -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -Dsun.net.client.defaultReadTimeout=60000 -Dsun.net.client.defaultConnectTimeout=60000 -Dorg.quartz.scheduler.skipUpdateCheck=true -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 -Djavax.xml.soap.SAAJMetaFactory=com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl -Dignore.endorsed.dirs= -Dcatalina.base=/home/test/server/Tomcat -Dcatalina.home=/home/test/server/Tomcat -Djava.io.tmpdir=/home/test/server/Tomcat/temp org.apache.catalina.startup.Bootstrap start
Host: AMD EPYC 7452 32-Core Processor, 4 cores, 31G, Ubuntu 18.04.5 LTS
Time: Wed Jan  4 04:43:53 2023 UTC elapsed time: 724.310601 seconds (0d 0h 12m 4s)

> ---------------  T H R E A D  ---------------
Current thread (0x00007f68e4543800):  JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=23014, stack(0x00007f688c3b0000,0x00007f688c4b1000)]

### Please provide steps to reproduce where possible

- If -xmx value is < 5GB execution end up with Out of Memory
- If -xmx value is > 7GB execution successful 
- If -xmx value ~6GB JVM crash with Fatal error SIGSEGV

### Expected Results

Either it should through Out of Memory or execution success

### Actual Results

JVM getting crashes 

### What Java Version are you using?

openjdk version "11.0.12" 2021-07-20

### What is your operating system and platform?

Ubuntu 18.04

### How did you install Java?

Download from Adopt Open JDK

**Comment by karianna** [comment]
Please try 11.0.17 and post the error log if it reoccurs

**Comment by rajaveld** [comment]
Sure @karianna I will check with jdk 11.0.17 and update you

**Comment by rajaveld** [comment]
Verified the issue with Open JDK 11.0.17, Issue not occurs with version. 
Closing this issue. Thanks
