### ISSUE TITLE
ATM8 server wont start up...

### ISSUE THREAD

**Issue by sakura6003** [adoptium/adoptium-support#688]
### Please provide a brief summary of the bug

Trying to start up the server, but it keeps crashing before it fully opens..

### Please provide steps to reproduce where possible

1. Click ¨Start Server¨
2. Let server load
3. Crash
4. Repeat

### Expected Results

I expected the server to run correctly.

### Actual Results

Server crashed.

### What Java Version are you using?

17.0.1 update 12

### What is your operating system and platform?

Server host:
CentOS Linux release 7.8.2003 (Core)
Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
Ram: 12356MB

### How did you install Java?

It was automatically installed into the server

### Did it work before?

```shell
It has worked on this version before yes.
```

### Relevant log output

```shell
https://pastebin.com/k7eWLW9i
```

**Comment by karianna** [comment]
Please try 17.0.5 and post the error log.
