### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by manderson88** [adoptium/adoptium-support#689]
### Please provide a brief summary of the bug

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\Jack\AppData\Local\.ftba\bin\versions\1.19.2-forge-43.2.3\1.19.2-forge-43.2.3-natives-131453524700 -Dminecraft.launcher.brand=FTBApp -Dminecraft.launcher.version=202212152008-a5a6712906-release -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,1.19.2-forge-43.2.3.jar -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\Users\Jack\AppData\Local\.ftba\bin\libraries --module-path=C:\Users\Jack\AppData\Local\.ftba\bin\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm/9.3/asm-9.3.jar;C:\Users\Jack\AppData\Local\.ftba\bin\libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Dmt.disablechat=true -Dchtray.port=51152 -Dchtray.instance=73ff095c-de78-4303-80d0-d4ebf31d6f8c -javaagent:log4jfixer.jar -Xmx12288M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Duser.language=en -Duser.country=US cpw.mods.bootstraplauncher.BootstrapLauncher --username CheeseBurger2K --version 1.19.2-forge-43.2.3 --gameDir D:\Games\FTB Instances\73ff095c-de78-4303-80d0-d4ebf31d6f8c --assetsDir C:\Users\Jack\AppData\Local\.ftba\bin\assets --assetIndex 1.19 --uuid 45f5e400-3795-4242-ac8e-f59fd621b556 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQxNTg5MTAyMjU2NCIsImFnZyI6IkFkdWx0Iiwic3ViIjoiY2QyZDg2MzMtYmI5Ny00NTc3LTlkYWItNGZkMzVkMWI3MzkwIiwibmJmIjoxNjczODkyMDk2LCJhdXRoIjoiWEJPWCIsInJvbGVzIjpbXSwiaXNzIjoiYXV0aGVudGljYXRpb24iLCJleHAiOjE2NzM5Nzg0OTYsImlhdCI6MTY3Mzg5MjA5NiwicGxhdGZvcm0iOiJQQ19MQVVOQ0hFUiIsInl1aWQiOiIwNTljMzE5N2Q5NWI2OGNmYjVkY2IyZDY0NTg5NGFiNSJ9.MHswgT4s5CN-EXYmCYVFFTafTD3ZClbTOeGIFJK2_uQ --clientId ${clientid} --xuid ${auth_xuid} --userType msa --versionType release --width 1720 --height 840 --launchTarget forgeclient --fml.forgeVersion 43.2.3 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: AMD Ryzen 9 7900X 12-Core Processor            , 24 cores, 31G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2364)
Time: Mon Jan 16 13:31:10 2023 Eastern Standard Time elapsed time: 1.549812 seconds (0d 0h 0m 1s)

### Please provide steps to reproduce where possible

Just loading game

### Expected Results

game should start

### Actual Results

a few lines of loading... then nothing.

### What Java Version are you using?

java version "17.0.5" 2022-10-18 LTS Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191) Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

### What is your operating system and platform?

Windows 10 pro

### How did you install Java
from Java web site.

### Did it work before?

Has not worked since install new system.

### Did you test with other Java versions?

No

[hs_err_pid17944.log](https://github.com/adoptium/adoptium-support/files/10428992/hs_err_pid17944.log)

**Comment by karianna** [comment]
See solution for https://github.com/adoptium/adoptium-support/issues/668 - please try this and let us know
