### ISSUE TITLE
JVM crashes with EXCEPTION_ACCESS_VIOLATION (0xc0000005) in CompilerThread

### ISSUE THREAD

**Issue by n-s-engomo** [adoptium/adoptium-support#690]
### Please provide a brief summary of the bug

We have a web application running on Java 11 and Apache Tomcat 9.X. On one of our deployments, we are experiencing frequent and spurious crashes. No info is logged by neither our application logging nor the Tomcat. The Java process just seems to exit / crash.

Upon investigating we found several crash logs all stating the same error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa450541d7, pid=9776, tid=8432
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [ntdll.dll+0xa41d7]
#
# Core dump will be written. Default location: D:\tomcat\hs_err_pid9776.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

So far we cannot force a crash, but it happens roughly every couple of hours. There is no obvious pattern regarding user action, but almost all crash logs point to one of the JVM's compiler thread as well as code from `jvm.dll`, `ucrtbase.dll` and `ntdll.dll`. The code path leading up to the crash seems to be identical across almost all the crash log files.

### Please provide steps to reproduce where possible

Just leave our application server running and use the web application. The server will crash within the next two hours.

Like mentioned above, the crashes are frequent but seem spurious and unpredictable. The crash logs suggest no direct involvement of application code, but rather native core JVM parts.

### Expected Results

The application / Tomcat server does not crash. The Java process keeps running.

If there is an actual application error, throw a Java Exception or an Error that can be logged, instead of crashing completely.

### Actual Results

The Java process exits / crashes. A crash log file is written: `EXCEPTION_ACCESS_VIOLATION (0xc0000005)`

### What Java Version are you using?

openjdk 11.0.17 2022-10-18 / OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8) / OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

### What is your operating system and platform?

- Windows Server 2019 , 64 bit Build 17763 (10.0.17763.3287)
- Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, 2 cores
- 6 GB RAM (but run with -Xms1024m -Xmx1024m or -Xms1024m -Xmx2048m)

### How did you install Java?

Binary archive (`.zip`) downloaded from https://adoptium.net: 

### Did it work before?

```shell
No changes, the crashes happen since the initial deployment to that host.
```

### Did you test with other Java versions?

```shell
Other Java versions tested with same results:
- Eclipse Temurin 11.0.16.1+1
- Eclipse Temurin 11.0.17+8
- Microsoft OpenJDK 11.0.15+10
- Microsoft OpenJDK 11.0.17+8
```

### Relevant log output

```shell
There was an error creating your issue: body is too long (maximum is 65536 characters).

Will be provided separately.
```

**Comment by n-s-engomo** [comment]
Typical crash log file (complete file appended below):

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa450541d7, pid=9664, tid=10804
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [ntdll.dll+0xa41d7]
#
# Core dump will be written. Default location: D:\tomcat\hs_err_pid9664.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Dcatalina.home=D:\tomcat -Dcatalina.base=D:\tomcat -Djava.io.tmpdir=D:\tomcat\temp -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=D:\tomcat\conf\logging.properties --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED exit abort -Xms1024m -Xmx1024m 

Host: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, 2 cores, 5G,  Windows Server 2019 , 64 bit Build 17763 (10.0.17763.3287)
Time: Fri Jan 13 13:02:02 2023 W. Europe Standard Time elapsed time: 2275.852110 seconds (0d 0h 37m 55s)

---------------  T H R E A D  ---------------

Current thread (0x000000001e323000):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=10804, stack(0x000000001f520000,0x000000001f620000)]


Current CompileTask:
C2:2275852 19076   !   4       java.lang.ref.Finalizer::runFinalizer (117 bytes)

Stack: [0x000000001f520000,0x000000001f620000],  sp=0x000000001f61b900,  free space=1006k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ntdll.dll+0xa41d7]
C  [ntdll.dll+0x108a2]
C  [ntdll.dll+0xfc27]
C  [ucrtbase.dll+0xb5c6]
V  [jvm.dll+0x6122e5]
V  [jvm.dll+0xb94da]
V  [jvm.dll+0xc2528]
V  [jvm.dll+0x1e676b]
V  [jvm.dll+0xd0864]
V  [jvm.dll+0xe0a51]
V  [jvm.dll+0x2f3ea]
V  [jvm.dll+0x626364]
V  [jvm.dll+0x624b34]
V  [jvm.dll+0x209385]
V  [jvm.dll+0x20815d]
V  [jvm.dll+0x18a3b1]
V  [jvm.dll+0x217a34]
V  [jvm.dll+0x215c7b]
V  [jvm.dll+0x76ea70]
V  [jvm.dll+0x7679a4]
V  [jvm.dll+0x61e425]
C  [ucrtbase.dll+0x2268a]
C  [KERNEL32.DLL+0x17974]
C  [ntdll.dll+0x5a2f1]


siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff
```

The last seven frames are almost always the same, but the compile task varies. The thread also varies between `C2 CompilerThread0` and `C1 CompilerThread0`.

[hs_err_pid10812.log](https://github.com/adoptium/adoptium-support/files/10432980/hs_err_pid10812.log)
[hs_err_pid9664.log](https://github.com/adoptium/adoptium-support/files/10432982/hs_err_pid9664.log)
[replay_pid9664.log](https://github.com/adoptium/adoptium-support/files/10432987/replay_pid9664.log)
[replay_pid10812.log](https://github.com/adoptium/adoptium-support/files/10432988/replay_pid10812.log)
[more-logs.zip](https://github.com/adoptium/adoptium-support/files/10433005/more-logs.zip)

**Comment by n-s-engomo** [comment]
Basic troubleshooting steps we tried so far:
- Switch OpenJDK distribution
- Switch OpenJDK version
- Install available OS update
- Increase Java heap size

Thank you all very much for your help with our issue ;)

**Comment by karianna** [comment]
Does your product use any native components?  Does this fail on all machines or just that specific host?

You can also try an 11.0.18 nightly build from adoptium.net

**Comment by n-s-engomo** [comment]
Yes, there are some native components. Specifically, we are using the SAP Business One DI API JCO, which is a JNI wrapper around the native COM APIs of SAP Business One (https://www.sap.com/products/erp/business-one.html).

I would not think that the crashes would be caused by that, as the respective DLLs are not mentioned in the crash log? Do you think this could be the culprit anyway? Most machines are doing just fine with it, currently just this host is acting up…

**Comment by karianna** [comment]
> Yes, there are some native components. Specifically, we are using the SAP Business One DI API JCO, which is a JNI wrapper around the native COM APIs of SAP Business One (https://www.sap.com/products/erp/business-one.html).
> 
> I would not think that the crashes would be caused by that, as the respective DLLs are not mentioned in the crash log? Do you think this could be the culprit anyway? Most machines are doing just fine with it, currently just this host is acting up…

Hmm, if it is genuinely a single host that's playing up you may have hit a rare O/S or Hardware bug - the crashlogs are failing during the JIT compilation which means that some bad memory could be involved here.

**Comment by DBKottelenberg** [comment]
I have the same issue/bug, so it is not a one-off rarity bug. First part crash log file below and full file attached:


```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc80c2c7f0, pid=32588, tid=8352
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, tiered, compressed oops, compressed class ptrs, serial gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0xc7f0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Djpackage.app-version=0.12.1 -XX:+UseSerialGC -Dguice_bytecode_gen_option=DISABLED -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=15 -Djpackage.app-path=C:\TQRespec\TQRespec.exe -Djdk.module.main=br.com.pinter.tqrespec br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main

Host: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz, 12 cores, 15G,  Windows 11 , 64 bit Build 22000 (10.0.22000.1335)
Time: Thu Jan 19 12:42:11 2023 W. Europe Standard Time elapsed time: 0.324321 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x000001cae55d0640):  JavaThread "WindowsNativeRunloopThread" [_thread_in_vm, id=8352, stack(0x0000000587f00000,0x0000000588000000)]

Stack: [0x0000000587f00
[hs_err_pid32588.log](https://github.com/adoptium/adoptium-support/files/10456397/hs_err_pid32588.log)
000,0x0000000588000000],  sp=0x0000000587fff338,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0xc7f0]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.glass.ui.win.WinApplication._runLoop(Ljava/lang/Runnable;)V+0 javafx.graphics
j  com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(ILjava/lang/Runnable;)V+8 javafx.graphics
j  com.sun.glass.ui.win.WinApplication$$Lambda$46+0x00000008000da6c8.run()V+12 javafx.graphics
j  java.lang.Thread.run()V+11 java.base@17.0.5
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000004

```

**Comment by karianna** [comment]
@David-BK Sorry to bounce this back, but can you try 17.0.6, which was just released?
