### ISSUE TITLE
Compile errors on parallel build with java 17

### ISSUE THREAD

**Issue by huthomas** [adoptium/adoptium-support#693]
We are running a maven tycho build with the cmd _mvn -T 1C clean_ verify. So one thread for each CPU is used to compile the projects.

With _Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk_ the build fails with non deterministic compile errors. For example:

`[ERROR] The type java.io.InputStream cannot be resolved. It is indirectly referenced from required .class files`

If the build is run without parallel options it runs successful.

With _Java version: 11.0.17, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk_ the build runs successfully with the parallel options.

Does anyone know what triggers the problem, and if there is a solution for it?

Your operating system and platform:

Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-17-amd64", arch: "amd64", family: "unix"

We are using the maven docker images _3.8-eclipse-temurin-11_ and _3.8-eclipse-temurin-17_

**Comment by huthomas** [comment]
Related issue in the tycho project.
https://github.com/eclipse-tycho/tycho/issues/1099

**Comment by karianna** [comment]
@huthomas Seems like a tycho issues but you can try 11.0.18 and 17.0.6 to see if there are any changes there.

**Comment by huthomas** [comment]
The problem is resolved using tycho 3.0.4.
