### ISSUE TITLE
Mulesoft integration broken after JDK upgrade to 8_352

### ISSUE THREAD

**Issue by ssrijan** [adoptium/adoptium-support#694]
## Question

Mule Integration is broken after upgrading to Adopt 8_352.
Currently, the application uses mulesoft as an integration framework used to connect to many endpoints via different transport types.
The mmc (mule core) internally connects to mmc-console (it just manages and monitors functions for all your on-premise Mule ESB Enterprise deployments and provides a green status if that endpoint is healthy.) and gets the status of the endpoint.

The connection b/w them was all fine till AdoptJDP 8_345 and less, but the moment the upgrade happened the communication broke with below exceptions:

com.xx.yy.server.manager.MMCException: HTTP response error for MMC request List Servers; response code=401 : reason=<!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:[#525D76](javascript:void(0););} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:[#525D76](javascript:void(0););border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Bad credentials</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/7.0.109</h3></body></html>

And we also see few exceptions like :
2023-01-09 05:18:55.562 [INFO] org.apache.commons.httpclient.HttpMethodDirector:193 - Failure authenticating with BASIC 'Galaxy Realm'@localhost:8585

After going through the RN, we don't see any specific change which may have caused this, but the issue is not seen in Oracle 8_351(i understand the delta difference b/w these two branches.)

Any thoughts would be useful.

## Context

Java version: 

openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b08, mixed mode)

Your operating system and platform:

SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 5

**Comment by jerboaa** [comment]
The `8u352` update switched on TLS v3 for client roles. See: https://bugs.openjdk.org/browse/JDK-8245263
