### ISSUE TITLE
Game crashing during generating new chunks

### ISSUE THREAD

**Issue by tomak333** [adoptium/adoptium-support#695]
### Please provide a brief summary of the bug

Game is crusing during going further than ~150 blocks in any direction from spawn, probably becouse of generating structure. I am also attaching crash report.
[crash-2023-01-13_12.33.06-client.txt](https://github.com/adoptium/adoptium-support/files/10470172/crash-2023-01-13_12.33.06-client.txt)

### Expected Results

I can play game

### Actual Results

game crashes

### What Java Version are you using?

Version 8 update 231 (build 1.8.0_231-b11)

**Comment by karianna** [comment]
Please use 1.8.0_362 or the Microsoft Build of OpenJDK that comes with Minecraft JE.
