### ISSUE TITLE
Crash on world gen

### ISSUE THREAD

**Issue by SynT8735** [adoptium/adoptium-support#696]
### Please provide a brief summary of the bug

Game instantly crashes on new world generation

[hs_err_pid15352.log](https://github.com/adoptium/adoptium-support/files/10492757/hs_err_pid15352.log)

### Please provide steps to reproduce where possible

Install modpack
Run modpack
Create world

### Expected Results

Create a world that I can play

### Actual Results

Game crashes

### What Java Version are you using?

openjdk 17.0.5 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### What is your operating system and platform?

Windows 11 Pro 22H2

### How did you install Java?

MSI

### Did it work before?

```shell
Did not test with other java versions
```

### Did you test with other Java versions?

```shell
Did not test with other java versions
```

**Comment by karianna** [comment]
This needs to be reported to the mod author.  Chances are it's a driver issue.
