### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Jacktrooperc** [adoptium/adoptium-support#700]
### Please provide a brief summary of the bug

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc66780056, pid=13732, tid=17052 # # JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10) # Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64) # Problematic frame: #  V  [jvm.dll+0x7a0056] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows # # An error report file with more information is saved as: # C:\Users\Jack\AppData\Roaming\PrismLauncher\instances\FTB StoneBlock 3\.minecraft\hs_err_pid13732.log # # If you would like to submit a bug report, please visit: #   https://github.com/adoptium/adoptium-support/issues # [thread 820 also had an error] AL lib: (EE) alc_cleanup: 1 device not closed Process exited with code 1. 

### Please provide steps to reproduce where possible

ok so I have the prism launcher and java 17 and I am trying to play mc with my brother on FTB Stone Block 3 but when I got to join the sever I get in then 2 seconds late it crashes and I don't know why I tried everything bewtten rebooting the pc to uninstalling java and reinstalling it and it still does the same thing

### Expected Results

I just expected to be able to play without it crashing for no reason

### Actual Results

I get in and then it immediately crashes

### What Java Version are you using?

17.6.10

### What is your operating system and platform?

windows 11

### How did you install Java?

ninte

### Did it work before?

no

### Did you test with other Java versions?

no because it wants java 17

**Comment by dotRelith** [comment]
same happened to me, but instead in trying to run it in a development enviroment. 
im using JDK17.0.6_10 trying to open minecraft gradle

<details>
 <summary>this is the message i get</summary>

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc6c262b60, pid=15592, tid=6708
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x192b60]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Arquivos do Usuario\Documentos\GitHub\Rereskillable-Rereforked\run\hs_err_pid15592.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[error occurred during error reporting (), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc6e04da79]
```

</details>

**Comment by karianna** [comment]
Most of the time this is a video driver issue.  Please update to latest NVidia or AMD drivers.
