### ISSUE TITLE
Unable to deploy .msi via Intune

### ISSUE THREAD

**Issue by Tonrab** [adoptium/adoptium-support#701]
When deploying the .msi (latest release of 20th Jan 2023) in Intune it comes up with an error that the app appears not have either a ProductCode or Productversion

Java version: Used .msi's 
11 - OpenJDK11U-jre_x64_windows_hotspot_11.0.18_10.msi
19 - OpenJDK19U-jre_x64_windows_hotspot_19.0.2_7.msi

Windows 10 22H2 (oS Build 19045.2364)
Deploying via Intune/MEM

![adoptopen](https://user-images.githubusercontent.com/78852782/216380932-4b0bd7c7-2810-4ba0-9992-2df99be65bc4.PNG)

**Comment by karianna** [comment]
duplicate of #594
