### ISSUE TITLE
How repair this

### ISSUE THREAD

**Issue by PudlatyPL** [adoptium/adoptium-support#705]
>#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=1, tid=0x00007f5eb65c7700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump written. Default location: /home/container/core or core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
[thread 140044762113792 also had an error]
[17:25:30 INFO]: [PlaceholderAPI] Successfully registered expansion: spark [1.10.29]
>[thread 140045154936576 also had an error]
[thread 140045153883904 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[error occurred during error reporting , id 0xb]
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by karianna** [comment]
@PudlatyPL Please try with the latest 1.8.0_362 and reply back here.

**Comment by dellgreen** [comment]
@PudlatyPL did 1.8.0_362  fix your problem?

**Comment by PudlatyPL** [comment]
> @PudlatyPL did 1.8.0_362  fix your problem?

Yes
