### ISSUE TITLE
Cannot Install application on AIX 7.2

### ISSUE THREAD

**Issue by drayper** [adoptium/adoptium-support#707]
### Please provide a brief summary of the bug

Java app installs on AIX 7.2 using IBM Serium JDK 11 using the latest release or previous release 08 Installation aborts

# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool
::allocate
However there;s a lot of memory on server
I

### Expected Results

At least Java app would Install

### Actual Results

Crashes

# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool

### What Java Version are you using?

openjdk version "11.0.18" 2023-01-17 OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10) OpenJDK 64OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### What is your operating system and platform?

AIX 7.2.0.0

### How did you install Java?

download , gzip to decompress then tar -xvf 

### Did you test with other Java versions?

```shell
Works with Oracle Java 8 or IBM Serum 11.0.17.0
```

**Comment by karianna** [comment]
You mention you are using:  

openjdk version "11.0.18" 2023-01-17 OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10) OpenJDK 64OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)_

But I see two separate versions there 11.0.18 and 11.0.9

**Comment by drayper** [comment]
Yes i tried with either one and cannot get app to install , it installs with Ibm Sereum Java 11

**Comment by smlambert** [comment]
Noting a recent PMC discussion, for AIX 7.1 EOL

FYI @sxa

**Comment by karianna** [comment]
Is it possible to move to https://www.ibm.com/docs/en/aix/7.2?topic=aix-release-notes AIX 7.2.5 - I believe 7.2.0.0 is EOL

**Comment by drayper** [comment]
Hi Martin , yes this is is in process should have Server upgraded to AIX 7.2.5 Monday or Tuesday then will retry install with Adoptium 11.0.18 . Delete the 11.0.9 Java from server only tried this to see if issue was 11.0.18

**Comment by drayper** [comment]
Updated to AIX  7200-05-04-2220 and still failed with not enough memory but system has 5.8 GB free memory

**Comment by sxa** [comment]
@drayper Do you have a sample app that we can use to reproduce this with? Our tests suites didn't show any problems on 7.2.
Also if you don't already have it can you run
```
export LDR_CNTRL=MAXDATA=0x80000000
```
In the environment before starting the app to see if that makes a difference.

I have one further question - you said earlier that it `Works with Oracle Java 8 or IBM Serum 11.0.17.0` - I don't believe Oracle has a JDK for AIX - can you confirm whether it was AIX systems that it works on or another platform?

**Comment by drayper** [comment]
Thank you so much the (export LDR_CNTRL=MAXDATA=0x80000000) command did the trick. I'm running tests to ensure all is working , but now i can since it installs. Do you thinks this is a problem with the JAR from the vendor ?

**Comment by sxa** [comment]
Not really - it's related to AIX memory management and not specific to java or any particular application so not something your vendor's application is likely to be able to take any action to fix (unless they wanted to document the use of that option, or rewrite their app to use less memory!)
I'm sure I've seen an article on the IBM pages that had some details which I was going to point you to, but I can't find it right now, so https://knowledge.broadcom.com/external/article/55881/increasing-memory-usage-on-aix.html covers what it's doing. hope that clarifies things.

**Comment by drayper** [comment]
Thanks for your help . I'll close this issue with a comment that in ulimit on AIX DATA should be set to unlimited to the root process for Adoptium
