### ISSUE TITLE
At this point im actually scared, java randomly crashes in all containers.

### ISSUE THREAD

**Issue by MaximusMcfly** [adoptium/adoptium-support#712]
### Please provide a brief summary of the bug

It randomly crashes in any container, ive tried to find a specific reason to "Why?" but i sucsessfully failed.
This is the crash message, please help.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f115e99a310, pid=1, tid=0x00007f11413ab700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xa4c310]  PhaseIdealLoop::spinup(Node*, Node*, Node*, Node*, Node*, small_cache*) [clone .part.38]+0x50
#
# Core dump written. Default location: /home/container/core or core.1
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid1.log
#
# Compiler replay data is saved as:
# /home/container/replay_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
[error occurred during error reporting , id 0xb]

### Please provide steps to reproduce where possible

I have no idea how to reproduce it.

### Expected Results

Work fine

### Actual Results

Not work fine and crash at random points of time.

### What Java Version are you using?

openjdk version "1.8.0_312" OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07) OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

### What is your operating system and platform?

My os is Ubuntu 22.04 Server.
The servers are run in docker containers managed through a pterodactyl fork "Jexactyl".
All server cores are different and java versions are 8th and 16th but in all examples it crashes.

### How did you install Java?

It automatically installs it from a dcker file?

### Did it work before?

```Shell
Im not sure what chnaged, but it did work before.
```

### Did you test with the latest update version?

```Shell
The servers were made today, so it is the latest version.
```

### Did you test with other Java versions?

```Shell
Nope.
```

### Relevant log output

```Shell
Its suuuper long so i sent it to pastebin
https://pastebin.com/pxmYPXC6
```

**Comment by karianna** [comment]
@MaximusMcfly Please try 1.8.0_362 from adoptium.net and report back here if it still crashes

**Comment by MaximusMcfly** [comment]
I need a link like this: ghcr.io/pterodactyl/yolks:java_8 or ghcr.io/parkervcp/yolks:java_8

**Comment by Futuraura** [comment]
> We are marking this issue as stale because it has not been updated for a while. This is just a way to keep the support issues queue manageable. It will be closed soon unless the stale label is removed by a committer, or a new comment is made.

Can you delete this Issue for privacy reasons?

**Comment by karianna** [comment]
@Futuraura I don't have the ability to do that.  Is your edit of the original Q sufficient?
