### ISSUE TITLE
Centos 7 temurin*JRE builds are not signed

### ISSUE THREAD

**Issue by iamperson347** [adoptium/adoptium-support#713]
### Please provide a brief summary of the bug

It appears that the new JRE builds of temurin 8-19 in the centos x86_64 repo are not signed. This is causing an issue on some system that require package signing. 

The links below are for affected centos 7 packages, but RHEL 7 also appears to be affected. 

https://packages.adoptium.net/artifactory/rpm/centos/7/x86_64/Packages/temurin-8-jre-8.0.362.0.0.9-2.x86_64.rpm

https://packages.adoptium.net/artifactory/rpm/centos/7/x86_64/Packages/temurin-11-jre-11.0.18.0.0.10-2.x86_64.rpm

https://packages.adoptium.net/artifactory/rpm/centos/7/x86_64/Packages/temurin-17-jre-17.0.6.0.0.10-2.x86_64.rpm

https://packages.adoptium.net/artifactory/rpm/centos/7/x86_64/Packages/temurin-19-jre-19.0.2.0.0.7-2.x86_64.rpm

All other packages are signed with https://packages.adoptium.net/artifactory/api/gpg/key/public

### Expected Results

JRE packages are signed (similar to the JDK rpm packages).

### Actual Results

JRE packages are not signed (see links above)

### What Java Version are you using?

N/A

### What is your operating system and platform?

Centos7/RHEL7

### How did you install Java?

RPM

**Comment by jerboaa** [comment]
@gdams Where is the signing being performed? Do we need to update something given the new JRE installers?

**Comment by jerboaa** [comment]
Seems a duplicate of https://github.com/adoptium/installer/issues/611

**Comment by iamperson347** [comment]
Ah - I tried do look around a bit for existing issues but did not check that repo. I'm betting the issues also applies to fedora (in the linked issue). 

I'll go ahead and close this out and watch the linked issue. Thank you!
