### ISSUE TITLE
java 17 cannot start on AIX 7.2

### ISSUE THREAD

**Issue by elbakkouricolas** [adoptium/adoptium-support#714]
I installed java 17 from adoptium.not and it cannot start with this error:

#/usr/jdk-17.0.6+10/bin => java -version
Error: dl failure on line 542
Error: failed /usr/jdk-17.0.6+10/lib/server/libjvm.so, because  0509-022 Cannot load module /usr/jdk-17.0.6+10/lib/server/libjvm.so.
        0509-150   Dependent module libc++.a(shr_64.o) could not be loaded.
        0509-022 Cannot load module libc++.a(shr_64.o).
        0509-026 System error: A file or directory in the path name does not exist.
        0509-022 Cannot load module /usr/jdk-17.0.6+10/lib/server/libjvm.so.
        0509-150   Dependent module /usr/jdk-17.0.6+10/lib/server/libjvm.so could not be loaded.

**Comment by sxa** [comment]
Which update of AIX 7.2 are you on? It works on the systems we use:
```
$ wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jre_ppc64_aix_hotspot_17.0.6_10.tar.gz
$ gzip -cd OpenJDK17U-jre_ppc64_aix_hotspot_17.0.6_10.tar.gz | tar xpf - 
$ jdk-17.0.6+10-jre/bin/java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)
$ oslevel -r
7200-02
$ oslevel -s
7200-02-05-1938
$
```
FYA @aixtools @backwaterred
