### ISSUE TITLE
Shenandoah: Crash when running at GCTaskThread "Shenandoah GC Threads#1"

### ISSUE THREAD

**Issue by RekaDowney** [adoptium/adoptium-support#716]
### Please provide a brief summary of the bug

We run our application on K8S and find that occasionally crash occurs. The crash occurred when running at `GCTaskThread "Shenandoah GC Threads#1"`.

The ErrorFile while crashed as following:
[shenandoah-0222.err.txt](https://github.com/adoptium/adoptium-support/files/10811420/shenandoah-0222.err.txt)
[shenandoah-0223.err.txt](https://github.com/adoptium/adoptium-support/files/10811421/shenandoah-0223.err.txt)

We try to extract the heap dump from core file. but error occurred while extracting.
![image](https://user-images.githubusercontent.com/24631388/220853069-0570dbd8-d2d8-4434-8f36-fbfb1c397e97.png)

### Please provide steps to reproduce where possible

Sorry, I can't. It crashes occasionally. We run 20 pods, but crash in two different pod.

### Expected Results

not crash occurs.

### Actual Results

JVM crash 

### What Java Version are you using?

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### What is your operating system and platform?

CentOS Linux release 7.9.2009 (Core)
 linux-amd64
Linux  3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### How did you install Java?

tar.gz

### Did it work before?

```Shell
Yes, but crashes occasionally. It also crashed occasionally when running with `G1GC` at `GCTaskThread "GC Thread#1"`

[g1-1115.err.txt](https://github.com/adoptium/adoptium-support/files/10811475/g1-1115.err.txt)
```

### Did you test with other Java versions?

```Shell
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

It crashes occasionally while G1GC Thread executed.
[g1-1115.err.txt](https://github.com/adoptium/adoptium-support/files/10811475/g1-1115.err.txt)
```

**Comment by zhangever** [comment]
It seems that this issue is related to [this one](https://github.com/adoptium/adoptium-support/issues/44).
The crashing point is the same.

**Comment by karianna** [comment]
@RekaDowney - recommend moving to 17.0.6.  That said, this is sounds a little like an actual container, O/S or H/W issue (given it's randomly occurring for two different collectors).  Also, is your app using any JNI/JNA or is it hitting the limits (CPY or memory) of the container?

**Comment by RekaDowney** [comment]
> recommend moving to 17.0.6. 

We will try 17.0.6 in next few days.

> is your app using any JNI/JNA or is it hitting the limits (CPY or memory) of the container?

Our app using custom java agent and elastic-apm(with JNI), but the memory and cpu did not reach limits(`8C16G`).

![Memory_on_crash](https://user-images.githubusercontent.com/24631388/221107197-54ecdb38-a57a-4f6f-a31d-52548a8d51e8.png)
![CPU_on_crash](https://user-images.githubusercontent.com/24631388/221107416-81237d39-4691-4c42-89bd-6b0dcae3d2a4.png)

**Comment by RekaDowney** [comment]
@karianna Do you have any opinion on "Extracting heap dump failed", It took about 2 hours, but finally failed :(

![image](https://user-images.githubusercontent.com/24631388/220853069-0570dbd8-d2d8-4434-8f36-fbfb1c397e97.png)

**Comment by karianna** [comment]
Typically that's a failure when there's not enough room to write the dump (typically it needs at least the same size as the JVM process to write to disk) or another process over writing the memory 

I note in an earlier message you have some JNI at play.  I'd look at that with some prejudice 🙂

**Comment by karianna** [comment]
@RekaDowney We now have 17.0.7 available, can you try that and report back here?
