### ISSUE TITLE
eclipse-temurin:11-jdk: does not contain latest openssl version

### ISSUE THREAD

**Issue by ChristophHartwigOSP** [adoptium/adoptium-support#717]
### Please provide a brief summary of the bug

The eclipse-temurin:11-jdk image includes a version of openssl with security vulnerabilities; the openssl package needs to be updated.
https://www.openssl.org/news/secadv/20230207.txt

### Please provide steps to reproduce where possible

$ docker run -it --entrypoint /bin/bash eclipse-temurin:11-jdk
root@8f5334c25c4a:/# apt-cache show openssl | grep Version

### Expected Results

openssl should be version 3.0.2-0ubuntu1.8 or later.

### Actual Results

3.0.2-0ubuntu1.7 is vulnerable.

### What Java Version are you using?

openjdk 11.0.18

### Did you test with the latest update version?

```Shell
container image is latest version pushed on 16.02.2023 https://hub.docker.com/layers/library/eclipse-temurin/11-jdk/images/sha256-5916153a273711755ea88711902407d5603a9948edd627ee817049f2cd158179?context=explore
```

**Comment by karianna** [comment]
@ChristophHartwigOSP This is controlled by Docker (they supply the base image) - this should be updated in the coming week, if not please do file an issue with them.
