### ISSUE TITLE
[libc.so.6+0x899a6]  memcpy+0x286

### ISSUE THREAD

**Issue by karshad1** [adoptium/adoptium-support#718]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7c95f049a6, pid=349973, tid=0x00007f7b0a8ec700
#
# JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x899a6]  memcpy+0x286
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f7c90c3a000):  JavaThread "TIBCO EMS Session Dispatcher (275957133)" [_thread_in_native, id=350219, stack(0x00007f7b0a7ec000,0x00007f7b0a8ed000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007f7bc009c000

Registers:
RAX=0x0000000000000000, RBX=0x0000000000000000, RCX=0x0000000000000278, RDX=0x000000000000aac1
RSP=0x00007f7b0a8e9338, RBP=0x00007f7b0a8e93b0, RSI=0x00007f7bc009bff8, RDI=0x00007f7aa80121d3
R8 =0x000000000000aac0, R9 =0x0000000000000000, R10=0x0000000000000000, R11=0x0000000000000000
R12=0x0000000000000000, R13=0x0000000000000000, R14=0x0000000000000000, R15=0x00007f7bc0097347
RIP=0x00007f7c95f049a6, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f7b0a8e9338)
0x00007f7b0a8e9338:   00007f7c8fdf5b8a 00007f7b0a8e98ec
0x00007f7b0a8e9348:   00007f7b0a8e9908 0000000000000000
0x00007f7b0a8e9358:   00007f7b00000008 0000000000000000
0x00007f7b0a8e9368:   000000009452ff56 000000000000eac4
0x00007f7b0a8e9378:   000000000008b500 0000000000000034
0x00007f7b0a8e9388:   00007f7c90956040 0000000000000034
0x00007f7b0a8e9398:   00000000a8ef9637 00007f7c90955720
0x00007f7b0a8e93a8:   00007f7aa4000c20 00007f7b0a8e9400
0x00007f7b0a8e93b8:   00007f7c8fdf67ce 0100000000000034
0x00007f7b0a8e93c8:   00007f7b0a8e9420 00007f7b0a8e9400
0x00007f7b0a8e93d8:   0000000000000034 00007f7c90c3a250
0x00007f7b0a8e93e8:   00007f7b0a8e9878 00007f7b0a8e9420
0x00007f7b0a8e93f8:   00007f7c90955720 00007f7b0a8e9860
0x00007f7b0a8e9408:   00007f7c8fde7835 0000000000000000
0x00007f7b0a8e9418:   0000000000000001 727270752f6d6f63
0x00007f7b0a8e9428:   6273652f7379732f 736e6f697463612f
0x00007f7b0a8e9438:   746972756365732f 6974554c4d582f79
0x00007f7b0a8e9448:   632e73656974696c 000000007373616c
0x00007f7b0a8e9458:   000000000a8e9878 0000000000000000
0x00007f7b0a8e9468:   0000000000000000 00007f7c959ba8fe
0x00007f7b0a8e9478:   000000000be7d2f0 0000000000000000
0x00007f7b0a8e9488:   00000000952a33b4 000000010037b330
0x00007f7b0a8e9498:   00007f7b0a8e9650 00007f7b0be7d2f0
0x00007f7b0a8e94a8:   00007f7c90c3a000 00007f7b0a8e9520
0x00007f7b0a8e94b8:   00007f7b0be7d2f0 00007f7c90c3a000
0x00007f7b0a8e94c8:   0000000000000000 00007f7b0a8e9560
0x00007f7b0a8e94d8:   00007f7c95647afe 00007f7b0badfbd8
0x00007f7b0a8e94e8:   00007f7b9eedcdb8 000000000be88aa0
0x00007f7b0a8e94f8:   000000000bfceb48 00007f7b0be7d2f0
0x00007f7b0a8e9508:   00007f7c90c3a000 0303030303030303
0x00007f7b0a8e9518:   0000030303030303 00007f7b0be7d2f0
0x00007f7b0a8e9528:   00007f7c90c3a000 000000000bad1901 

Instructions: (pc=0x00007f7c95f049a6)
0x00007f7c95f04986:   0d 8f 80 03 00 00 48 8d 76 40 48 8d 7f 40 0f 85
0x00007f7c95f04996:   46 ff ff ff e9 b7 00 00 00 90 48 ff c9 48 8b 06
0x00007f7c95f049a6:   48 8b 5e 08 4c 8b 4e 10 4c 8b 56 18 4c 8b 5e 20
0x00007f7c95f049b6:   4c 8b 66 28 4c 8b 6e 30 4c 8b 76 38 0f 18 8e 80 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x0000000000000278 is an unknown value
RDX=0x000000000000aac1 is an unknown value
RSP=0x00007f7b0a8e9338 is pointing into the stack for thread: 0x00007f7c90c3a000
RBP=0x00007f7b0a8e93b0 is pointing into the stack for thread: 0x00007f7c90c3a000
RSI=0x00007f7bc009bff8 is an unknown value
RDI=0x00007f7aa80121d3 is an unknown value
R8 =0x000000000000aac0 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x00007f7bc0097347 is an unknown value

Stack: [0x00007f7b0a7ec000,0x00007f7b0a8ed000],  sp=0x00007f7b0a8e9338,  free space=1012k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x899a6]  memcpy+0x286
C  [libzip.so+0x127ce]  ZIP_GetEntry2+0xde
C  [libzip.so+0x3835]  Java_java_util_zip_ZipFile_getEntry+0x85
J 250  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007f7c81195b0e [0x00007f7c81195a40+0xce]
J 1586 C2 sun.misc.URLClassPath$JarLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (85 bytes) @ 0x00007f7c816cee78 [0x00007f7c816ce9c0+0x4b8]
J 1505 C2 sun.misc.URLClassPath.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (83 bytes) @ 0x00007f7c815fbcb0 [0x00007f7c815fbbc0+0xf0]
J 879 C1 java.net.URLClassLoader$1.run()Ljava/lang/Class; (63 bytes) @ 0x00007f7c813675ac [0x00007f7c813673a0+0x20c]
J 878 C1 java.net.URLClassLoader$1.run()Ljava/lang/Object; (5 bytes) @ 0x00007f7c8136880c [0x00007f7c81368780+0x8c]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f9a]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe1a
V  [libjvm.so+0x7431b3]  JVM_DoPrivileged+0x553
J 831  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x00007f7c81354375 [0x00007f7c813542a0+0xd5]
J 876 C1 java.net.URLClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class; (47 bytes) @ 0x00007f7c81367ef4 [0x00007f7c81367d40+0x1b4]
J 4143 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (122 bytes) @ 0x00007f7c81cd400c [0x00007f7c81cd3640+0x9cc]
J 829 C1 sun.misc.Launcher$AppClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (85 bytes) @ 0x00007f7c8135688c [0x00007f7c81355f00+0x98c]
J 776 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007f7c813384c4 [0x00007f7c813383c0+0x104]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f9a]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe1a
V  [libjvm.so+0x692653]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x692ca4]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Handle, Thread*)+0x64
V  [libjvm.so+0xa9f864]  SystemDictionary::load_instance_class(Symbol*, Handle, Thread*)+0x2c4
V  [libjvm.so+0xaa0361]  SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*)+0xa11
V  [libjvm.so+0xaa25f9]  SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, Thread*)+0x49
V  [libjvm.so+0x4d2908]  ConstantPool::klass_at_impl(constantPoolHandle, int, Thread*)+0x328
V  [libjvm.so+0x4d375b]  ConstantPool::klass_ref_at(int, Thread*)+0xbb
V  [libjvm.so+0x81cb46]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle, int, Thread*)+0xa6
V  [libjvm.so+0x81fa60]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle, int, Bytecodes::Code, Thread*)+0x160
V  [libjvm.so+0x687e23]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x5d3
j  com.uprr.sys.esb.actions.security.DefaultSAMLVerifier.getSecurityElement(Lcom/uprr/sys/esb/ESBMessage;)Ljava/lang/String;+8
j  com.uprr.sys.esb.actions.security.DefaultSAMLVerifier.isAuthCyberArkOrSiteminder(Lcom/uprr/sys/esb/ESBMessage;)Z+4
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.verifySecurityToken(Lcom/uprr/sys/esb/ESBMessage;)V+45
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.verify(Lcom/uprr/sys/esb/ESBMessage;)V+20
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.process(Lcom/uprr/sys/esb/ESBMessage;)V+22
J 5079 C2 com.uprr.sys.esb.pipeline.SimplePipeline.process(Lcom/uprr/sys/esb/ESBMessage;)V (80 bytes) @ 0x00007f7c81371d28 [0x00007f7c81371ac0+0x268]
J 5651 C2 com.tibco.tibjms.TibjmsxSessionImp._dispatchAsyncMessage(Lcom/tibco/tibjms/TibjmsxSessionImp$Dispatcher;Z)Z (646 bytes) @ 0x00007f7c81f1ee7c [0x00007f7c81f1d020+0x1e5c]
j  com.tibco.tibjms.TibjmsxSessionImp$Dispatcher.run()V+29
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f9a]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe1a
V  [libjvm.so+0x692653]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x692c27]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x57
V  [libjvm.so+0x734a1c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xaceb77]  JavaThread::thread_main_inner()+0x1c7
V  [libjvm.so+0xacfeca]  JavaThread::run()+0x2fa
V  [libjvm.so+0x95d732]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x7aa1]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 250  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007f7c81195a98 [0x00007f7c81195a40+0x58]
J 1586 C2 sun.misc.URLClassPath$JarLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (85 bytes) @ 0x00007f7c816cee78 [0x00007f7c816ce9c0+0x4b8]
J 1505 C2 sun.misc.URLClassPath.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (83 bytes) @ 0x00007f7c815fbcb0 [0x00007f7c815fbbc0+0xf0]
J 879 C1 java.net.URLClassLoader$1.run()Ljava/lang/Class; (63 bytes) @ 0x00007f7c813675ac [0x00007f7c813673a0+0x20c]
J 878 C1 java.net.URLClassLoader$1.run()Ljava/lang/Object; (5 bytes) @ 0x00007f7c8136880c [0x00007f7c81368780+0x8c]
v  ~StubRoutines::call_stub
J 831  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x00007f7c81354303 [0x00007f7c813542a0+0x63]
J 876 C1 java.net.URLClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class; (47 bytes) @ 0x00007f7c81367ef4 [0x00007f7c81367d40+0x1b4]
J 4143 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (122 bytes) @ 0x00007f7c81cd400c [0x00007f7c81cd3640+0x9cc]
J 829 C1 sun.misc.Launcher$AppClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (85 bytes) @ 0x00007f7c8135688c [0x00007f7c81355f00+0x98c]
J 776 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007f7c813384c4 [0x00007f7c813383c0+0x104]
v  ~StubRoutines::call_stub
j  com.uprr.sys.esb.actions.security.DefaultSAMLVerifier.getSecurityElement(Lcom/uprr/sys/esb/ESBMessage;)Ljava/lang/String;+8
j  com.uprr.sys.esb.actions.security.DefaultSAMLVerifier.isAuthCyberArkOrSiteminder(Lcom/uprr/sys/esb/ESBMessage;)Z+4
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.verifySecurityToken(Lcom/uprr/sys/esb/ESBMessage;)V+45
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.verify(Lcom/uprr/sys/esb/ESBMessage;)V+20
j  com.uprr.sys.esb.actions.security.DefaultSecurityPolicyAction.process(Lcom/uprr/sys/esb/ESBMessage;)V+22
J 5079 C2 com.uprr.sys.esb.pipeline.SimplePipeline.process(Lcom/uprr/sys/esb/ESBMessage;)V (80 bytes) @ 0x00007f7c81371d28 [0x00007f7c81371ac0+0x268]
J 5651 C2 com.tibco.tibjms.TibjmsxSessionImp._dispatchAsyncMessage(Lcom/tibco/tibjms/TibjmsxSessionImp$Dispatcher;Z)Z (646 bytes) @ 0x00007f7c81f1ee7c [0x00007f7c81f1d020+0x1e5c]
j  com.tibco.tibjms.TibjmsxSessionImp$Dispatcher.run()V+29
v  ~StubRoutines::call_stub

### Expected Results

.

### Actual Results

jvm crush

### What Java Version are you using?

OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08

**Comment by karianna** [comment]
@karshad1 Please try 1.8.0_362 and report back here.
