### ISSUE TITLE
SIGSEGV on compile

### ISSUE THREAD

**Issue by masmc05** [adoptium/adoptium-support#720]
### Please provide a brief summary of the bug

The server was running fine for half a day, then it crashed

### Please provide steps to reproduce where possible

It's random, happens once in a month

### Expected Results

No crash to happen

### Actual Results

It crashed

### What Java Version are you using?

OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (19.0.2+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)

### Relevant log output

```Shell
https://drive.google.com/file/d/1DCTBiDuNoRY57_jyBXYFzCD9RKkTntV5/view?usp=sharing
```

**Comment by karianna** [comment]
[Uploading hs_err_pid3769014.log…]()

**Comment by karianna** [comment]
Hi @masmc05 I'm curious as to what me.PM2.AdvancedCrates.animations.cosmic.CosmicAnimationHologramRemove::run does.  Would it eventually call JNI code or the new vector API?

**Comment by masmc05** [comment]
the author of the code ignores this question, and I'm not sure if i could share the bytecode for you to check

**Comment by masmc05** [comment]
yes, and no response from 28 February

**Comment by karianna** [comment]
> if we remove his product, do we have a chance for this issue to not happen again?

I beleive so as the crash is coming directly from their use of a native call (as best as I can tell)

**Comment by masmc05** [comment]
ok, thanks!
