### ISSUE TITLE
[Bug]: A fatal error has been detected by the Java Runtime Environment SIGSEGV (0xb)

### ISSUE THREAD

**Issue by jebbench** [adoptium/adoptium-support#721]
### Please add the exact image (with tag) that you are using

eclipse-temurin:jdk-17

### Please add the version of Docker you are running

Google Kubernetes Engine

### What happened?

JVM crashed (crash log below) when under light load.

Unfortunately it was running on a container which was restarted after the crash so I can't access the error report files.

We've seen the crash occur twice, both times when the application was under light load.

~~The image was built using JIB (https://github.com/GoogleContainerTools/jib).~~ We've now seen this occur in a container that was not built using JIB.

Heap usage was around 1gb of 2gb allocated.

### Relevant log output

```shell
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f3ea639d898]
#
# https://github.com/adoptium/adoptium-support/issues
# If you would like to submit a bug report, please visit:
#
# //replay_pid1.log
# Compiler replay data is saved as:
#
# //hs_err_pid1.log
# An error report file with more information is saved as:
#
# JFR recording file will be written. Location: //hs_err_pid1.jfr
#
# Core dump will be written. Default location: /core.%e.1.%t
#
# C 0x0000000000000000
# Problematic frame:
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
#
# SIGSEGV (0xb) at pc=0x0000000000000000, pid=1, tid=19
#
# A fatal error has been detected by the Java Runtime Environment:
#
```

**Comment by jebbench** [comment]
This is still an issue in OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (but has apparently been resolved in OpenJDK 19 - I've not been able to verify though).

**Comment by karianna** [comment]
@jebbench Would be good to understand the fix in 19 - is there a bug report or mail thread to reference?

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8303279

**Comment by simonis** [comment]
Fixed by https://github.com/openjdk/jdk/pull/14600 in JDK 22.

Still needs to be downported to 17 & 21.

**Comment by gdams** [comment]
> Fixed by [openjdk/jdk#14600](https://github.com/openjdk/jdk/pull/14600) in JDK 22.
> 
> Still needs to be downported to 17 & 21.

the 17 backport PR is here: https://github.com/openjdk/jdk17u-dev/pull/1580

**Comment by simonis** [comment]
Notice that this doesn't doesn't affect 11 because it was introduced by https://bugs.openjdk.org/browse/JDK-8238691 which only went int 15.

**Comment by gdams** [comment]
> Notice that this doesn't doesn't affect 11 because it was introduced by https://bugs.openjdk.org/browse/JDK-8238691 which only went int 15.

I was just thinking the same thing, I'll remove the label

**Comment by karianna** [comment]
Do we close or does it need a 21 backport?

**Comment by gdams** [comment]
It went into 21 here: https://github.com/openjdk/jdk21/pull/119
