### ISSUE TITLE
Eclipse Temurin JRE Install to Custom (Non-Default) Location Does Not Work

### ISSUE THREAD

**Issue by annasilchenko** [adoptium/adoptium-support#722]
I'm installing Eclipse Temurin Adoptium JRE 11 to non-default location (to "C:\Non-Default-Path\Eclipse Adoptium" instead of "C:\Program Files\Eclipse Adoptium").

But it always gets installed to the default location (to "C:\Program Files\Eclipse Adoptium").

Does Adoptium JRE 11 msi distribution file "OpenJDK11U-jre_x64_windows_hotspot_11.0.18_10.msi" supports command line installation to non-default location?

I'm using following command format:
"msiexec /i <jre>.msi /l*v <file>.log /qn INSTALLDIR=C:\Non-Default-Path\Eclipse Adoptium"

I see "Ignoring disallowed property INSTALLDIR" in the log file.

What property name MSI file supports for Non-Default location, should I use INSTALLDIR or different property?

Thanks so much!

File name: "OpenJDK11U-jre_x64_windows_hotspot_11.0.18_10.msi"
openjdk version "11.018" 2023-01-17
Windows 10 Enterprise x64

**Comment by karianna** [comment]
@douph1 Is this something we can add as a feature?

**Comment by douph1** [comment]
I have not tested since long time but changing the INSTALLDIR is allowed as documented here :
https://adoptium.net/installation/windows/

>msiexec /i <package>.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="c:\Program Files\Temurin\" /quiet
>Note: You must use INSTALLDIR with FeatureMain.

@annasilchenko , maybe you must add ADDLOCAL=FeatureMain

**Comment by annasilchenko** [comment]
@douph1 
It works, thanks! Explicitly running the CMD shell as administrator fixed the issue. Thank you for pointing me to the right direction with ADDLOCAL feature.
