### ISSUE TITLE
All the Mods 8 Crash 

### ISSUE THREAD

**Issue by TuliMul** [adoptium/adoptium-support#726]
### Please provide a brief summary of the bug

# # A fatal error has been detected by the Java Runtime Environment: # #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe5b4f2e20, pid=29196, tid=30936 # # JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10) # Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64) # Problematic frame: # C   [nvoglv64.dll+0x1852e20] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows # # An error report file with more information is saved as: # C:\Users\Tulipher\AppData\Roaming\PrismLauncher\instances\All the Mods 8 - ATM8\minecraft\hs_err_pid29196.log Compiled method (c1)  466479 64936       3       com.mojang.blaze3d.vertex.VertexBuffer::m_231223_ (63 bytes)  total in heap  [0x00000206da363490,0x00000206da364c50] = 6080  relocation     [0x00000206da3635e8,0x00000206da363780] = 408  main code      [0x00000206da363780,0x00000206da3646e0] = 3936  stub code      [0x00000206da3646e0,0x00000206da3647a8] = 200  oops           [0x00000206da3647a8,0x00000206da3647b8] = 16  metadata       [0x00000206da3647b8,0x00000206da364810] = 88  scopes data    [0x00000206da364810,0x00000206da3649d8] = 456  scopes pcs     [0x00000206da3649d8,0x00000206da364c28] = 592  dependencies   [0x00000206da364c28,0x00000206da364c30] = 8  nul chk table  [0x00000206da364c30,0x00000206da364c50] = 32 #

### Please provide steps to reproduce where possible

Get All the mods 8 play for a few hours then wait for crash. 

### Expected Results

To be able to play the modpack without crashing every time I load into a world 

### Actual Results

I crash.

### What Java Version are you using?

 Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)

### What is your operating system and platform?

Windows 11 Home 22H2 on x64

### How did you install Java?

MSI 

### Did it work before?

```Shell
No.
```

### Did you test with the latest update version?

```Shell
No.
```

### Did you test with other Java versions?

```Shell
No.
```

**Comment by karianna** [comment]
@TuliMul Does it work without hte mods installed?  I'd recommend filing an issue againsthte mod authors and/or updating yor graphics drivers to the latest levels.

**Comment by TuliMul** [comment]
The issue was with the mods thanks for the help!
