### ISSUE TITLE
can I use Adoptium JDK/JRE 8u362 to replace Oracle Java SE to run an applet in Edge (using IE Mode)?

### ISSUE THREAD

**Issue by Jtreml60** [adoptium/adoptium-support#727]
## Question

we have an old Java applet that needs to run in Microsoft's Edge browser running in IE Mode for compatibility, on Windows 2019 server. This works fine using Oracle Java SE 8u351, but if I try to use Adoptium JDK/JRE 8u362 x64, the applet wont run in the browser. I've trawled the internet trying to find out if this should work, or if Adoptium cant be used like this, but I cant find the answer, so I'm grateful for any help or advice

Java version: 8u362

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

Your operating system and platform:
Windows 2019 Server on VMware ESX 7.1 on HPE DL360

**Comment by karianna** [comment]
See historical blog post at: https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/

further background reading https://adoptopenjdk.net/icedtea-web.html, https://github.com/AdoptOpenJDK/IcedTea-Web and
