### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by xsedlife** [adoptium/adoptium-support#728]
## Question
Hi, I got the problem with that whatever I do I can't run minecraft and always during launching EXCEPTION_ACCESS_VIOLATION appears.

Java version:
I tried 11.0.18.10 and 8.0.362.9 but both doesn't seems to work.
<!--
[hs_err_pid3376.log](https://github.com/adoptium/adoptium-support/files/10926640/hs_err_pid3376.log)

**Comment by karianna** [comment]
@xsedlife This is usually caused by mods or needing to upgrade your graphics drivers.   Please try disable the mods and upgrading the drivers and report back here.

**Comment by xsedlife** [comment]
I've already updated by drivers and I also tried to play vanilla minecraft but with the same result. There is still exception_access_violation.

**Comment by karianna** [comment]
There should be an hs_err_<pid>.log file dumped to teh folder of your minecraft install or $TEMP or $TMP - if you can post that up here we might be able to see what is going on

**Comment by xsedlife** [comment]
[hs_err_pid13944.log](https://github.com/adoptium/adoptium-support/files/10926740/hs_err_pid13944.log)

**Comment by karianna** [comment]
That log file reports you are using 1.8.0_51 as opposed to the latest 1.8.0_362.  Recommend you change the underlying JVM and upload a new log.

**Comment by xsedlife** [comment]
Alright, vanilla minecraft seems fixed but when I try to run a modpack with ATLauncher the error appears.
[hs_err_pid14800.log](https://github.com/adoptium/adoptium-support/files/10926855/hs_err_pid14800.log)

**Comment by karianna** [comment]
OK you'll need to file this issue with the mod pack owner in that case, it's a crash caused by them overloading some memory when they shouldn't.
