### ISSUE TITLE
How to automatically delete .jnlp file after it's launch?

### ISSUE THREAD

**Issue by panther078** [adoptium/adoptium-support#729]
##
We used to launch our Kinaxis RR application from our Okta web (SAML2) in the past using Oracle Java JRE v8update 333. 
We are using Chrome, Firefox or Edge. Since our browser setting is managed by our IT management team, the option we have is each time we click on our web applet, it will:
1. downloads a JNLP file and we will hit open it.
2. The JNLP file starts our Java application.
3. The Java application then deletes the JNLP file.

Last week, my team is trying to launch a Kinaxis RapidResponse (RR) application by using Eclipse OpenJDK and IcedTeaWeb. I have followed these links to install and setup:

https://adoptium.net/temurin/releases?version=8,
https://adoptopenjdk.net/icedtea-web.html
We also have associated IcedTeaWeb with the OpenJDK as well as modified Windows environment variables.

![EnvironmentSettings](https://user-images.githubusercontent.com/127479585/224262062-7ebdbcfb-8762-49c8-badf-18f1430b58e1.jpg)

![IcedTea-WebConsole](https://user-images.githubusercontent.com/127479585/224261996-5d26f026-3970-420b-99f0-a07d1580af7d.jpg)

However, this time, when we click on our application:
1. It will download the JNLP file and we hit open it.
2. JNLP will starts launch Java application
3.  The JNLP file remains in the download folder.

This actually created a lot of JNLP files in the download folder and users would need to delete them manually.
Is there a workaround setting in the Java console to automatically delete the JNLP file upon successfully Java application launch? 

![MultpleJNLP](https://user-images.githubusercontent.com/127479585/224266086-dd12066b-fda3-4307-8aaa-55e6bebe16ea.jpg)

Java version:
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

Your operating system and platform: Windows 10 Enterprise Version 20H2 / OS Build: 19042.2604

**Comment by karianna** [comment]
@hendrikebbers over to you :-)
