### ISSUE TITLE
Java Swing application crash due to EXCEPTION_ACCESS_VIOLATION in JavaThread "C2 CompilerThread0"

### ISSUE THREAD

**Issue by adriantoganel** [adoptium/adoptium-support#732]
### Please provide a brief summary of the bug

The application is crashing suddenly while running.

Attached there are the hs_err and replay files generated for two different crashes

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff5927f413, pid=184384, tid=80332
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x52f413]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Djava.io.tmpdir=C:\Users\Brian Jepsen\.tora\com.tora.g2.launchpad\bootstrapper\installations\TORA OEMS PROD\tmp -Dsun.awt.nopixfmt=true -Dsun.java2d.d3d=false -Dsun.java2d.noddraw=true -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintCommandLineFlags -XX:+PrintFlagsFinal -XX:+ResizeTLAB -XX:+ScavengeBeforeFullGC -XX:+UseCompressedOops -XX:+UseNUMA -XX:+UseStringDeduplication -XX:+UseTLAB -XX:MaxGCPauseMillis=100 -XX:MaxMetaspaceSize=384M -XX:MaxNewSize=2G -XX:NewSize=2G -XX:StringDeduplicationAgeThreshold=6 -Xlog:gc*::time,uptime,level,tags: -Xlog:gc*::time,uptime,level,tags: -Xms8G -Xmx16G -Xss2m -verbose:gc C:\Users\Brian Jepsen\.tora\com.tora.g2.launchpad\bootstrapper\installations\TORA OEMS PROD\versions\11.25.0\launchers\e395cbe11d6dca29d43bc0b689f8ccddeadd2cfc77f4f585a161a47eaf3c3617.jar -cdist prod/config_gui/cdist_config_all.xml -forceCompression true -forceSSL true -language ENGLISH -launcher launchpad:bootstrapper -listenport 17700 -logmsg true -ping 3000 -title TTS -usageinfotoserver true -screenLocation 980,615

Host: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 8 cores, 63G,  Windows 11 , 64 bit Build 22621 (10.0.22621.1105)
Time: Mon Mar 13 10:20:29 2023 Eastern Daylight Time elapsed time: 1889.917883 seconds (0d 0h 31m 29s)

---------------  T H R E A D  ---------------

Current thread (0x000002236bf2b800):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=80332, stack(0x000000d476400000,0x000000d476500000)]


Current CompileTask:
C2:1889918 43789   !   4       javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer (510 bytes)

Stack: [0x000000d476400000,0x000000d476500000],  sp=0x000000d4764fa8f0,  free space=1002k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x52f413]
V  [jvm.dll+0x52f188]
V  [jvm.dll+0x52e4b0]
V  [jvm.dll+0x21118b]
V  [jvm.dll+0x20add4]
V  [jvm.dll+0x207f6b]
V  [jvm.dll+0x18a3a1]
V  [jvm.dll+0x2178e4]
V  [jvm.dll+0x215b2b]
V  [jvm.dll+0x76e610]
V  [jvm.dll+0x767544]
V  [jvm.dll+0x61dff5]
C  [ucrtbase.dll+0x29363]
C  [KERNEL32.dll+0x126bd]
C  [ntdll.dll+0x5dfb8]


siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000008
```

[hs_err_pid11208.log](https://github.com/adoptium/adoptium-support/files/10979339/hs_err_pid11208.log)
[replay_pid11208.log](https://github.com/adoptium/adoptium-support/files/10979340/replay_pid11208.log)
[hs_err_pid184384.log](https://github.com/adoptium/adoptium-support/files/10979341/hs_err_pid184384.log)
[replay_pid184384.log](https://github.com/adoptium/adoptium-support/files/10979342/replay_pid184384.log)

### Please provide steps to reproduce where possible

Unfortunately I am not able to reproduce the problem or to isolate the cause of it

### Expected Results

application should run 

### Actual Results

application crashes

### What Java Version are you using?

Temurin-11.0.16.1+1 

### What is your operating system and platform?

Windows 11

### Did it work before?

```Shell
we did not see this error on oracle java 8
```

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8304428

**Comment by karianna** [comment]
@adriantoganel Can you give the below a try?

This has all the hallmarks of a C2 bug. There's no test case, and 11.0.16 is old so I can't say if this was fixed already.
The submitter can try excluding that specific method from compilation along the lines of these docs

https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE
the example syntax there is :-
-XX:CompileCommand=exclude,java.lang.String::indexOf

you'd need to apply that to the method cited in your case.

-XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer

I admit I am not sure if the "$" can be used literally .. or if it must escaped ..

If that fixes it, then it is even more likely to be a C2 bug.

**Comment by adriantoganel** [comment]
Hi,

Thanks for input.
Will give it a try and try to provide you details if it is still happening

**Comment by adriantoganel** [comment]
Short update.
So far it seems that setting jvm parameter 
`-XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer
`
is fixing the crash

**Comment by karianna** [comment]
@adriantoganel Can you try our 11.0.19 build? It may have been fixed as part of https://bugs.openjdk.org/browse/JDK-8285835

**Comment by adriantoganel** [comment]
it was reproducible with Temurin-11.0.19+7 
attached file
[replay_pid9595.log](https://github.com/adoptium/adoptium-support/files/11543466/replay_pid9595.log)
[hs_err_pid9595.log](https://github.com/adoptium/adoptium-support/files/11543467/hs_err_pid9595.log)

**Comment by karianna** [comment]
Updated the upstream ticket

**Comment by dorumititean** [comment]
Hi @karianna ,

Unfortunately setting jvm parameter:
`-XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer `
is not actually fixing our application, it's just making it crash from somewhere else. Our application crashed again in a similar manner and now the problem seems to be a different method from the same class:

```
---------------  T H R E A D  ---------------

Current thread (0x0000015ab9877000):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=22420, stack(0x000000286bf00000,0x000000286c000000)]


Current CompileTask:
C2:9699782 41389       4       javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::resetToPreferredSizes (93 bytes)
```

We were using Temurin-11.0.18+10 on a Windows 11 machine. I'm attaching the _hs_err_ and _replay_ files generated.

Can you please explain us in more details what you mean by "(1) to reproduce with a debug build to check if we hit any (known) asserts". What is a debug build and what assertions should we look for?

Thank you,
Doru Mititean

[replay_pid26524.log](https://github.com/adoptium/adoptium-support/files/11834703/replay_pid26524.log)
[hs_err_pid26524.log](https://github.com/adoptium/adoptium-support/files/11834704/hs_err_pid26524.log)

**Comment by karianna** [comment]
Are you able to reproduce that crash with 11.0.19 and -XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer set? 

If you send those logs in I can submit that to the Oracle folks upstream

**Comment by dorumititean** [comment]
Hi @karianna ,

We encountered crashes on version 11.0.19 even with the proposed setting.
This happens less often and is significantly harder for us to reproduce it.
And it is crashing in a different place:

`# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_PRIV_INSTRUCTION (0xc0000096) at pc=0x000001e3caa04b9f, pid=17204, tid=30896
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.19+7 (11.0.19+7) (build 11.0.19+7)
`

I've attached 2 _hs_err_ files.

Thank you,
Doru Mititean
[hs_err_pid12984.log](https://github.com/adoptium/adoptium-support/files/11916267/hs_err_pid12984.log)
[hs_err_pid17204.log](https://github.com/adoptium/adoptium-support/files/11916270/hs_err_pid17204.log)

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8309309 - 11.0.20 will have the fix.
