### ISSUE TITLE
what is the purpose of the debugimage-archives?

### ISSUE THREAD

**Issue by AlBundy33** [adoptium/adoptium-support#734]
## Question
Today I wanted to debug the HttpClient from the sun package to find the cause of an "Unexpected end of file from server"

So I've created a debug-project with the latest Adoptium 1.8, added the src.zip and set a breakpoint in HttpClient.parseHttpHeader
This worked as expected but eclipse couldn't display the local and class variables.
argument where shown as arg0, arg1 and arg2 in variables view instead byntheir name from the source-file.

So I wonder if the debugimage would provide this informations.
if so: how do I use this archives?
if not: what's then the purposes of this achives?

## Context

Java version: latest 1.8

Your operating system and platform: windows 10

**Comment by AlBundy33** [comment]
question is still open but with this blogpost https://www.javaadvent.com/2014/12/recompiling-the-java-runtime-library-with-debug-symbols.html and this gist https://gist.github.com/cdman/84e195d9f5d36e401c8b I was able to create a patched rt.jar with debug-informations. :-)

This is my build.xml
```
<project name="add debug-informations to rt.jar" default="patch" basedir=".">
    <target name="init">
        <property name="project.build" location="build"/>
        <property name="project.src" location="${project.build}/src"/>
        <property name="project.classes" location="${project.build}/classes"/>
        <path id="project.classpath">
            <fileset dir="./jre/lib">
                <include name="*.jar"/>
            </fileset>
        </path>
		<mkdir dir="${project.build}"/>
    </target>
 
    <target name="clean" depends="init">
        <delete dir="${project.build}" quiet="true"/>
    </target>
 
    <target name="unpack" depends="clean,init">
        <unzip src="./src.zip" dest="${project.src}"/>   
    </target>
 
    <target name="build" depends="unpack">
        <mkdir dir="${project.classes}"/>
        <javac srcdir="${project.src}" classpathref="project.classpath"
            destdir="${project.classes}" debug="on" includeAntRuntime="false"
            fork="true" memoryMaximumSize="4096m" failonerror="false">
			<include name="sun/**/*.java"/>
        </javac>
    </target>
 
    <target name="patch" depends="build">
        <jar jarfile="./jre/lib//rt.jar" update="true" compress="true">
            <fileset dir="${project.classes}"/>
        </jar>
    </target>
</project>
```

this can be copied into the jdk and started with ant
after hat it can be used for debugging in eclipse

**Comment by jerboaa** [comment]
`debugimage` artefacts contain debug symbols of the JVM (for native `gdb` debugging). What you are looking for is `-g` option to javac for JDK classfiles which apparently isn't available. I've filed https://github.com/adoptium/temurin-build/issues/3287 to track this.
