### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by otachasak** [adoptium/adoptium-support#737]
### Please provide a brief summary of the bug

Application is crashing unexpectedly, Java updated to latest 17.
[hs_err_pid4324.log](https://github.com/adoptium/adoptium-support/files/10992153/hs_err_pid4324.log)

### Please provide steps to reproduce where possible

We have no steps, just start appliaction and after few hours or days it crashes.

### Expected Results

Apliaction should not crash.

### Actual Results

Application crashes.

### What Java Version are you using?

OpenJDK 64-Bit Server VM Temurin-17.0.6+10

### What is your operating system and platform?

Windows Server 2016 Standard

### How did you install Java?

zip

### Did you test with the latest update version?

```Shell
yes
```

**Comment by karianna** [comment]
@otachasak judging by `-Djava.library.path=D:\PROD\dll\x64` it looks like you are loading or linking to some native libs?  com.aspose.? Is that correct?

**Comment by otachasak** [comment]
@karianna we have sqljdbc_auth.dll, because of integratedSecurity in jdbc connection. Aspose is jar, which contains WindowsNativeCall_x64.dll. This dll is probably copied from jar to filesystem as you can see in hs_err_pid. Yesterday we have removed aspose and waiting, if it helps.

**Comment by karianna** [comment]
I suspect it is that native lib causing the crash, let's wait and see!

**Comment by cmanhandley** [comment]
I'm having the same error code, do i need to open a new bug thing? Just in case here's the log file.
[hs_err_pid20460.log](https://github.com/adoptium/adoptium-support/files/11035375/hs_err_pid20460.log)

**Comment by karianna** [comment]
@cmanhandley Are you also using Aspose?

**Comment by cmanhandley** [comment]
@karianna if that's a server then no, i'm just playing on my single player worlds but they keep crashing with the same report. However, I got a new problematic frame and I'm about to post an issue report about it. I think i had read the wrong part of the bug report sorry.

**Comment by otachasak** [comment]
@karianna backend app is still running. On Wednesday Tomcat frontend crashed. Could you look at [hs_err_pid5828.log](https://github.com/adoptium/adoptium-support/files/11120219/hs_err_pid5828.log)?

**Comment by karianna** [comment]
@otachasak Hmmmm, tomcat version?

**Comment by otachasak** [comment]
@karianna Apache Tomcat/9.0.71

**Comment by karianna** [comment]
Slight long shot but there was one fix in 9.0.73 for corrupted Http requests which might be leaking through here.  Give that a go first and if you see one more crash log after that I'll take both and report upstream :).

**Comment by karianna** [comment]
@otachasak - Ohhhh this is only happening on _one_ install base out of many?  And you say it's in a lower traffic node?

I'm going to swap my suspicion to the very rare  'but we do see it happen' Windows O/S patch or memory hardware bug.  I'm going to assume your windows is fully patched in which case try running the _Windows Memory Diagnostic tool_ and see if it comes up with anything.

It won't hurt to upgrade Tomcat as well.

**Comment by karianna** [comment]
avx3 is supported out of the box so that sounds like a bug.  Tomcat itself doesn't execute those instructions but the Java 17 JVM does depending on your code path.  Your workaround is good for now I suspect.  Will keep this issue open to see if others report similar things.

**Comment by Frenchhtoasty** [comment]
hello i have the same issue and I don't understand the fix for this problem I'm not very good with backend stuff I need help

**Comment by cmanhandley** [comment]
I know I had a similar issue, I had just gotten 2 new sticks of ram. But the motherboard was messing up with 4 sticks so when I removed 2 it worked just fine.

**Comment by Frenchhtoasty** [comment]
i have a simmilar porbelm but i dont understand how to fix it

**Comment by Frenchhtoasty** [comment]
> I know I had a similar issue, I had just gotten 2 new sticks of ram. But the motherboard was messing up with 4 sticks so when I removed 2 it worked just fine.

um im on my gaming laptop and havent triend running on my pc and i cant remove any ram and only have 8gb or ram of this lapotop and will upgrade when i have the funds but the program worked before

**Comment by Frenchhtoasty** [comment]
and ive done a fresh download and of the program and java and haven't completely setup tomcat

**Comment by karianna** [comment]
@Frenchhtoasty you can try adding `-XX:UseAVX=2` to the java command, so something like:

`java -XX:UseAVX=2 <all of the other arguments>`

**Comment by Frenchhtoasty** [comment]
how would i do that

**Comment by karianna** [comment]
@Frenchhtoasty - Hmmm I suspect you are talking about Minecraft and not the Tomcat Server?

**Comment by Frenchhtoasty** [comment]
yh i am im redownloading  some drivers as I got told on the discord server to see if that works but if you have any other idea pls inform me

**Comment by karianna** [comment]
Ah OK, yeah, this is a totally separate issue.  Updating drivers for Minecraft is usually the fix.

**Comment by Frenchhtoasty** [comment]
yh it is didnt know but thank you anyways itsq working now hope you have a good day
