### ISSUE TITLE
Sparrow Terminal Bug on Raspiblitz

### ISSUE THREAD

**Issue by JohnnyBTCBLOCK** [adoptium/adoptium-support#743]
### Please provide a brief summary of the bug

Hello,

on my RasberryPI/Raspiblitz I run the Sparrow terminal via tmux. This has been producing a bug and crashing for a while. Please take a look to the error message:

BH sparrow: T:bash - "raspberrypi’ - Oo X

2 > Bll(thread 3789464 also had an error]

A fatal error has been detected by the Java Runtime Environment:

SIGILL (8x4) at pc-6x0600067f0d2a6060, pid-3782462, tid-3834868

A I TU ERE

+ JRE version: OpenJDK Runtime Environment Temurin-18.0.1+16 (18.6.1+1) (build 18..1+16;
+ Java VM: OpenJDK 64-Bit Server VM Temurin-18.6.1+10 (18.0.1+16, mixed mode, tiered, compressed oops, compressed class
tes, gl gc, linux-aarched)

+ Problematic fram

+ J 12238 c1 com. github. benmanes. caffeine. cache.VarHandletpscAccess. casProducerIndex(Lcon/github/benmanes/caffeine/cachel

/BaseMpscLinkedArrayQueue;33)Z com. sparrowallet.merged.module@l.7.0 (11 bytes) @ 0xP000007£0d226000 [0x00000070d2a5Cco
+6X0060060060000346 |

:
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try “ulimit —c unlimited” before
caring 2ava. a=.»
:

# An error report file with more information is saved as:
# /home/adnin/hs_err_pid3782462.1og

:

# Tf you would like to submit a bug report, please visit:

# https: //github.com/adoptiun/adoptium-support/issues

:

Aborted |

### Expected Results

The terminal should not crash

### Actual Results

The terminal crashes

### What Java Version are you using?

OpenJDK 64-Bit Server VM Tremurin-18.0.1+10

### Did it work before?

```Shell
Yes, it worked perfectly
```

**Comment by karianna** [comment]
@JohnnyBTCBLOCK 18.0.1 is no longer supported.  Can you try the latest 19.02 or LTS 17.0.6
