### ISSUE TITLE
Unexplained memory footprint on JDK 11.0.18

### ISSUE THREAD

**Issue by iominfra123** [adoptium/adoptium-support#748]
### Please provide a brief summary of the bug

For my application with a 2GB XMX I have an RSS footprint of >7GB! 

`app01@myhost:~$ ps -edf | grep java`
`app01  2083 27401  0 15:52 pts/0    00:00:00 grep --color=auto java`
`app01 27477     1 21 15:09 pts/0    00:09:26 /java/openj9-jdk-11.0.18.10//bin/java -Djava.util.logging.config.file=/App/App01/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dgenesis.conf=/App/App01/myapp/production/conf/myapp.properties -DBase=/App/App01/tomcat -javaagent:/App/App01/myapp/production/libs/core-agent-final.jar -Xms2g -Xmx2g -XX:MaxMetaspaceSize=256m -Djava.awt.headless=true -Duser.timezone=Europe/Paris -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal  -Dignore.endorsed.dirs= -classpath /srvapps/tomcat/apache-tomcat-9.0.27/bin/bootstrap.jar:/srvapps/tomcat/apache-tomcat-9.0.27/bin/tomcat-juli.jar -Dcatalina.base=/App/App01/tomcat -Dcatalina.home=/srvapps/tomcat/apache-tomcat-9.0.27 -Djava.io.tmpdir=/App/App01/tomcat/temp org.apache.catalina.startup.Bootstrap start`
`app01@myhost:~$ ps -orss,cmd 27477`
`  RSS CMD 
7835488 /java/openj9-jdk-11.0.18.10//bin/java -Djava.util.logging.config.file=/App/App01/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.p`
`app01@myhost:~$`

Heap
 garbage-first heap   total 2097152K, used 342143K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 193 young (197632K), 152 survivors (155648K)
 Metaspace       used 51196K, capacity 53225K, committed 53452K, reserved 303104K
  class space    used 5081K, capacity 5822K, committed 5888K, reserved 253952K

Memory leak ? 
how to find out what uses the memory ?

### Expected Results

ideally, the footprint should be less than 4g for Xmx to 2GB

### Actual Results

currently, the footprint uses almost all the available memory on the server

### What Java Version are you using?

openjdk 11.0.18 2023-01-17 OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10) OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

### What is your operating system and platform?

CentOS Linux release 7.5.1804 (Core)

### How did you install Java?

tar.gz

### Did you test with the latest update version?

```Shell
already in latest
```

### Did you test with other Java versions?

```Shell
11.0.5
```

**Comment by iominfra123** [comment]
You are right, it is a hotspot (error in the path)
it comes from https://adoptium.net/temurin/releases/?version=11

**Comment by karianna** [comment]
From Ghat-GPT - GPT4

------

Native Memory Tracking (NMT) is a feature in the HotSpot JVM that helps track native memory usage by the JVM and Java applications. This can be useful for diagnosing memory leaks, understanding memory consumption, and tuning the JVM for better performance. Here's how to enable and use NMT in Java 11:

Enable NMT:
To enable NMT, you need to set the JVM flag -XX:NativeMemoryTracking. There are three options for this flag: off, summary, and detail.

Off: NMT is disabled (default setting).
Summary: Enables NMT and provides summary-level tracking.
Detail: Enables NMT with detailed tracking, which can add some overhead to the JVM performance.
To enable NMT, add the flag to the command line when starting your Java application:

ruby
Copy code
java -XX:NativeMemoryTracking=summary -jar your_application.jar
Or for detailed tracking:

ruby
Copy code
java -XX:NativeMemoryTracking=detail -jar your_application.jar
Access NMT data:
You can access NMT data using the jcmd tool, which is included in the JDK. First, find the process ID (PID) of your running Java application. You can use the jps command to list all running Java processes:

Copy code
jps
Once you have the PID, you can use jcmd to access NMT data. For a summary report, run:

css
Copy code
jcmd <PID> VM.native_memory summary
For a detailed report, run:

php
Copy code
jcmd <PID> VM.native_memory detail
The output will show native memory usage broken down into categories, such as Java heap, class metadata, and thread stacks.

Analyze NMT data:
Analyze the NMT output to understand the memory usage of your application. Look for any unexpected growth in memory consumption, which could indicate a memory leak. Keep in mind that detailed tracking may have some overhead, so only use it when necessary.

Remember that NMT tracks native memory usage, which is separate from Java heap memory. If you want to analyze heap memory usage, you should use tools like VisualVM, JConsole, or other Java profiling tools.

Disable NMT:
To disable NMT, simply remove the -XX:NativeMemoryTracking flag from the command line or set it to off:

ruby
Copy code
java -XX:NativeMemoryTracking=off -jar your_application.jar
NMT is a powerful feature for diagnosing and understanding native memory usage in Java applications. Be sure to use it in conjunction with other profiling and monitoring tools to gain a comprehensive understanding of your application's performance and memory consumption.

**Comment by iominfra123** [comment]
After a new test today and the implementation of NMT

NMT summary does not explain the footprint
The different elements of the summary have coherent reserved/committed results, but the sum does not correspond to the real memory consumption


```
app01@myhost:~/tomcat$ jcmd 31006 VM.native_memory summary
31006:

Native Memory Tracking:

Total: reserved=3178299KB, committed=2381379KB
-                 Java Heap (reserved=2097152KB, committed=2097152KB)
                            (mmap: reserved=2097152KB, committed=2097152KB)

-                     Class (reserved=305031KB, committed=55123KB)
                            (classes #7730)
                            (  instance classes #7195, array classes #535)
                            (malloc=1927KB #27568)
                            (mmap: reserved=303104KB, committed=53196KB)
                            (  Metadata:   )
                            (    reserved=49152KB, committed=47308KB)
                            (    used=45878KB)
                            (    free=1430KB)
                            (    waste=0KB =0,00%)
                            (  Class space:)
                            (    reserved=253952KB, committed=5888KB)
                            (    used=5077KB)
                            (    free=811KB)
                            (    waste=0KB =0,00%)

-                    Thread (reserved=371344KB, committed=36604KB)
                            (thread #318)
                            (stack: reserved=369816KB, committed=35076KB)
                            (malloc=1156KB #1910)
                            (arena=372KB #635)

-                      Code (reserved=250401KB, committed=38129KB)
                            (malloc=2713KB #8453)
                            (mmap: reserved=247688KB, committed=35416KB)

-                        GC (reserved=126795KB, committed=126795KB)
                            (malloc=15927KB #24584)
                            (mmap: reserved=110868KB, committed=110868KB)

-                  Compiler (reserved=655KB, committed=655KB)
                            (malloc=523KB #660)
                            (arena=133KB #5)

-                  Internal (reserved=10395KB, committed=10395KB)
                            (malloc=10363KB #12216)
                            (mmap: reserved=32KB, committed=32KB)

 -                     Other (reserved=1280KB, committed=1280KB)
                            (malloc=1280KB #165)

 -                    Symbol (reserved=11014KB, committed=11014KB)
                            (malloc=8034KB #109565)
                            (arena=2981KB #1)

-    Native Memory Tracking (reserved=3510KB, committed=3510KB)
                            (malloc=432KB #6107)
                            (tracking overhead=3078KB)

-               Arena Chunk (reserved=196KB, committed=196KB)
                            (malloc=196KB)

-                   Logging (reserved=4KB, committed=4KB)
                            (malloc=4KB #192)

-                 Arguments (reserved=21KB, committed=21KB)
                            (malloc=21KB #549)

-                    Module (reserved=185KB, committed=185KB)
                            (malloc=185KB #1791)

-              Synchronizer (reserved=305KB, committed=305KB)
                            (malloc=305KB #2479)

-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB)

app01@myhost:~/tomcat$ ps -orss,cmd 31006
  RSS CMD
6140908 /java/openj9-jdk-11.0.18.10//bin/java -Djava.util.logging.config.file=/App/App01/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.p
app01@myhost:~/tomcat$
```

**Comment by karianna** [comment]
Hmm, with your printflags final, what GC is it saying its using?  G1 or Parallell?

**Comment by iominfra123** [comment]
G1GC

````
catalina.out:     bool UseG1GC                                  = true                                      {product} {ergonomic}
catalina.out:     bool UseParallelGC                            = false                                     {product} {default}
````

**Comment by iominfra123** [comment]
we are not in docker...., we run tomcat directly on the host

**Comment by karianna** [comment]
@iominfra123 Are you familiar with JDK Flight Recorder?

**Comment by lgonzalezluna** [comment]
I just started my own investigation, but based on https://mail.openjdk.org/pipermail/jdk-dev/2023-December/008491.html it seems that the information collected by NMT is not exactly complete
