### ISSUE TITLE
Challenging memory issue with Temurin-11.0.17 

### ISSUE THREAD

**Issue by VictorL-At16** [adoptium/adoptium-support#749]
Hello there,

I have an application newly migrated to ADOPT OPENJDK 11. I ran into strange memory issue: the same application ran ok with (Temurin)(build 1.8.0_322-b06), but occupied more memory in Temurin-11.0.17. 

During my investigation with Native Memory Tracking turned on, I found that even though visualVM showed steady heap usage along with time ( visualVM showed Size: 2,705,326,080 B   Used: 1,795,162,112 B), but jcmd gave a totally different picture(with JVM setting: -Xmx3G):

>>>>>>>>>>>>>>>>>>>>jcmd output>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
125993:

Native Memory Tracking:

Total: reserved=**17180282265KB** +9436KB, committed=**2762197KB** +27560KB

-                 Java Heap (reserved=17179869184KB, committed=2598912KB +10240KB)
                            (mmap: reserved=17179869184KB, committed=2598912KB +10240KB)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Does anyone have any idea why this **17180282265KB** is listed as "reserved" ? 

The Linux top command gave something else:
 
>>>>>>>>>>>>>>>>>>>top command output >>>>>>>>>>>>>>>>>>>>>>>>>
top - 20:23:52 up 20 days, 22:04,  2 users,  load average: 0.15, 0.23, 0.31
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  1.5 sy,  0.0 ni, 97.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32761424 total, 13108252 free, 12252936 used,  7400236 buff/cache
KiB Swap:  2097148 total,  1752920 free,   344228 used. 16361544 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
125993 myapp    20   0   17.0t   4.6g   4.3g S   0.3 14.7   1:37.31 java
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Where the RES has 4.6g in Temurin-11.0.17, but only about 2.2g in (Temurin)(build 1.8.0_322-b06).

The only difference for JVM parameter is that I used below options for Temurin-11.0.17 as experiment in my performance tuning:
-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+UseTLAB
-XX:CMSInitiatingOccupancyFraction=90 -XX:MinHeapFreeRatio=30 -XX:MaxHeapFreeRatio=70
-XX:+DisableExplicitGC

Here is the detail of my environment:

Linux 3.10.0-1160.83.1.el7.x86_64 #1 SMP Mon Dec 19 10:44:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

Please let me know if you have any idea about this situation.

Thanks in advance!

**Comment by karianna** [comment]
The ZGC Garbage Collector takes more reserved memory in order to operate.
