### ISSUE TITLE
Major release notifications

### ISSUE THREAD

**Issue by cap10morgan** [adoptium/adoptium-support#751]
## Question

Would it be possible to setup major release notifications so that people integrating w/ your releases downstream know when to add them?

## Context

I am one of the maintainers of the [official Clojure Docker image](https://hub.docker.com/_/clojure) and would love to be able to get a notification when there is a new major release available of Eclipse Temurin so I can add it to our build matrix. In this case a notification of the new official `eclipse-temurin` Docker image would be ideal. A GitHub release would be ideal as the notification source as I can easily subscribe to those and that's how I monitor for new releases of some of the build tools we package as well.

I discussed this in Slack w/ @sxa.

**Comment by karianna** [comment]
@cap10morgan How would you expect to get that notification?

**Comment by cap10morgan** [comment]
> @cap10morgan How would you expect to get that notification?

A GitHub release notification is sent to any subscribers when you create a “Release” from a tag. So you’d need a GitHub repo in which you could create tags and releases corresponding to the JDK release versions. But it’s fine if a different approach works better for you all.

**Comment by karianna** [comment]
We could tag our containers repo I suppose, challenge is that our images are actually built and maintained by Docker Inc at DockerHub.  Have you looked at seeing if you can get notified via them?

**Comment by sxa** [comment]
That may be tricky since we don't have our own repository for temurin in dockerhub - it's a generic one (Our files are at e.g. https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin)

**Comment by cap10morgan** [comment]
> That may be tricky since we don't have our own repository for temurin in dockerhub - it's a generic one (Our files are at e.g. https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin)

Yeah, same for us in the official Clojure image. It's not critical that the notification be immediately after the image becomes available on Docker Hub. If it's more of a "heads up, this is imminent" that's OK too.

**Comment by tellison** [comment]
@cap10morgan our release schedule is quite predictable - did you notice the "[Release Roadmap](https://adoptium.net/support)" on our website? HTH
