### ISSUE TITLE
Error on setup/repair

### ISSUE THREAD

**Issue by JasonP-01** [adoptium/adoptium-support#753]
### Please provide a brief summary of the bug

Every time i repair/setup adoptium it says there is an error on line 2502 and 2503 and ends the setup wizard so now i am unable to play my game due to the fact the installation download is broken, i have tried the one i had before and it gave the error so i redownloaded it and it gave the same error, it might be cause by me updating my windows (update was 2023-03 Cumulative Update Preview for Windows 10 Version 22H2 for x64-based Systems (KB5023773) )

### Please provide steps to reproduce where possible

Launch OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi and do the setup or repair the current one

### Expected Results

It to install/repair properly without giving an error and canceling the wizard

### Actual Results

![image](https://user-images.githubusercontent.com/118902738/228831903-4d3a5189-674e-4b3a-8887-0f23cfb4e892.png)
This happens (image) stating an error on lines 2502 and 2503

### What Java Version are you using?

I dont have java installed

### What is your operating system and platform?

windows 10.0.19045 N/A Build 19045 x64-based PC 

### How did you install Java?

as stated i do not have java 
![image](https://user-images.githubusercontent.com/118902738/228833471-35a10e3f-37ae-40a6-a293-3e196b46ada3.png)

### Did it work before?

```Shell
worked before i installed the update
```

### Did you test with the latest update version?

```Shell
yes
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by JasonP-01** [comment]
![image](https://user-images.githubusercontent.com/118902738/228838254-fd2a813e-d3df-47f3-96a7-337c22306e98.png)
Upon installing java and retrying i still encounter the same issue

**Comment by karianna** [comment]
@JasonP-01 You have two Java's on your system, one Java 8 and one Java 17.  If you are using Java only for Minecraft I recommend using the default Microsoft Build of OpenJDK 17.0.3 that comes with Minecraft.

If the MSI installers are not working correctly you may need to run them as administrator or try other Windows based clean up tools.

**Comment by JasonP-01** [comment]
the issue is not with minecraft its now with i cant run my .jars cause nothing is registering as a viable option, i can select java se runtime environment as an extra option but it just opens cmd prompt for 0.5 seconds and clsoes and then does nothing

**Comment by karianna** [comment]
If you open a command prompt and type `java -version` what do you get?

**Comment by JasonP-01** [comment]
I get nothing, command prompt accepts it as a cmd (once i manually
installled java) and provides zero output and goes to the next cmd i enter.
Before i downloaded java it said unknown command its not an
internal/external command

**Comment by karianna** [comment]
Hmm, I can only recommend using some sort of a registry/program files cleaning tool to remove all traces of the old Java installs and reinstall from scratch - something is likely corrupted
