### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by cmanhandley** [adoptium/adoptium-support#755]
### Please provide a brief summary of the bug

I'm using the refined storage mod and in a diamond crafter (4 speed upgrades applied), and I found how to duplicate speed upgrades.

### Please provide steps to reproduce where possible

Middle mouse click the Crafter interface (to quick sort the inventory) it will duplicate the 4 speed upgrades. Yes, the speed upgrades are legit and can be placed into other refined storage blocks.

### Expected Results

to sort the processor cards.

### Actual Results

sorted cards, and yielded 4 speed upgrades.

### What Java Version are you using?

1.17.0.6

### What is your operating system and platform?

windows 11

### How did you install Java?

Oracle website

### Did it work before?

```Shell
Don't know
```

### Did you test with the latest update version?

```Shell
no, i'm on 2.2.0
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact us to address the issue.
