### ISSUE TITLE
No arm32v7 platform present in eclipse-temurin:latest

### ISSUE THREAD

**Issue by tdedobbeleer** [adoptium/adoptium-support#758]
I got an image which is build with docker builds on circleci and it suddenly failed today. The platform armv7 seemed to be missing. I did not find anything in the docker docs about the sudden absence of the platform. Could this be an error somewhere?

**Comment by karianna** [comment]
@tdedobbeleer  What version of our OpenJDK and where are you pulling the image from?

**Comment by tdedobbeleer** [comment]
@karianna Good questions, should have been clearer.

I'm pulling from the docker hub and using the latest tag, which is according to the docs OpenJDK19 (don't know if this matters at all). Since I'm using only one dockerfile, I do not specify the platform in the image (I'm not using arm32v7/eclipse-temurin), just eclipse-temurin:latest. This did always succeed, because latest included the arm32v7 platform as well. But now latest does not contain it anymore:

https://hub.docker.com/layers/library/eclipse-temurin/latest/images/sha256-41acc982e932eeb61a51af3262f3070ccfc23a32fd6f89bc16e7fec7647979fa?context=explore

Hence my docker build fails:

```
------
 > [linux/arm/v7 internal] load metadata for docker.io/library/eclipse-temurin:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM eclipse-temurin:latest
   2 |     
   3 |     ARG JAR
--------------------
ERROR: failed to solve: eclipse-temurin:latest: no match for platform in manifest sha256:f2f82ba81dae08f785bd1e37bd0597b7e514408d1f08d6676a0cba170568b776: not found
```

**Comment by gdams** [comment]
this is due to the fact that latest switched to JDK20 and (for now) we cannot ship JDK20 on arm32. I'd suggest you switch your tag to `eclipse-temurin:19` and your problem should be solved.

**Comment by tdedobbeleer** [comment]
@gdams Thanks, that explains!
The downside of using latest. Should have expected platform issues :) Keep up the good work!
