### ISSUE TITLE
Jar file does not run: Missing main class exception

### ISSUE THREAD

**Issue by Honey-Programming** [adoptium/adoptium-support#760]
**Version**: Eclipse Temurin JDK Build 20 with Hotspot

**Description of Bug:**

When I try to run my calculator jar file on the desktop with temurin by double clicking or running as administrator the cmd window opens and says: Cannot execute this program: Missing main class.
I think this is a linkage error.

**Comment by karianna** [comment]
@honey-java We need a lot more information.  What version of Temurin are you running, what program are you rtying to run and how do you try to execute that program?

**Comment by honey-java** [comment]
> @honey-java We need a lot more information. What version of Temurin are you running, what program are you rtying to run and how do you try to execute that program?

Alright

**Comment by Honey-Programming** [comment]
This issue is fixed with JarFix app
