### ISSUE TITLE
JAVA 11 crashes on frame # V  [libjvm.so+0x7fb3bc]  void OopOopIterateBackwardsDispatch<G1ScanEvacuatedObjClosure>::Table::oop_oop_iterate_backwards<InstanceKlass, oopDesc*>(G1ScanEvacuatedObjClosure*, oopDesc*, Klass*)+0xfc

### ISSUE THREAD

**Issue by aghawanmeh** [adoptium/adoptium-support#764]
I'm running a web application with huge heap (around 220GB), and facing crashes from one time to another with no steps to reproduce, what could be the problem?

A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f1b4662c3bc, pid=12806, tid=12822

 JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
 Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, g1 gc, linux-amd64)
 Problematic frame:
 V  [libjvm.so+0x7fb3bc]  void OopOopIterateBackwardsDispatch<G1ScanEvacuatedObjClosure>::Table::oop_oop_iterate_backwards<InstanceKlass, oopDesc*>(G1ScanEvacuatedObjClosure*, oopDesc*, Klass*)+0xfc

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /mnt/ssd/na101/home/literatum/servers/P/web115/resin/hs_err_pid12806.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues

**Comment by karianna** [comment]
@aghawanmeh Please update to 11.0.18 and report back here if the problem persists
