### ISSUE TITLE
JVM crash due to EXCEPTION_ACCESS_VIOLATION in ConcurrentGCThread

### ISSUE THREAD

**Issue by adriantoganel** [adoptium/adoptium-support#765]
### Please provide a brief summary of the bug

The Swing application crashes sometimes after running a few minutes and other times after a few hours.
We have multiple users running the application but the crash occurs more often for a subset of users that have heavy profiles (more memory used, more data processing, more GC)
here are some of the hs_err file generated when crash happens
[hs_err_pid23884.log](https://github.com/adoptium/adoptium-support/files/11170736/hs_err_pid23884.log)
```

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffac3463e01, pid=23884, tid=17032
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x193e01]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -Djava.io.tmpdir=C:\Users\markz\.tora\com.tora.g2.launchpad\bootstrapper\installations\TORA OEMS PROD\tmp -Dsun.awt.nopixfmt=true -Dsun.java2d.d3d=false -Dsun.java2d.noddraw=true -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintCommandLineFlags -XX:+PrintFlagsFinal -XX:+ResizeTLAB -XX:+ScavengeBeforeFullGC -XX:+UseCompressedOops -XX:+UseNUMA -XX:+UseStringDeduplication -XX:+UseTLAB -XX:MaxGCPauseMillis=100 -XX:MaxMetaspaceSize=384M -XX:MaxNewSize=2G -XX:NewSize=2G -XX:StringDeduplicationAgeThreshold=6 -Xlog:gc*::time,uptime,level,tags: -Xlog:gc*::time,uptime,level,tags: -Xms8G -Xmx16G -Xss2m -verbose:gc -XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer C:\Users\markz\.tora\com.tora.g2.launchpad\bootstrapper\installations\TORA OEMS PROD\versions\11.25.0\launchers\0430749e5ccb53eb0e10328c5de88346b3d5f82105ca9df66a03ed3cb5d34a9c.jar -cdist prod/config_gui/cdist_config_all.xml -forceCompression true -forceSSL true -language ENGLISH -launcher launchpad:bootstrapper -listenport 17700 -logmsg true -ping 3000 -title TTS -usageinfotoserver true -screenLocation 468,246

Host: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, 12 cores, 31G,  Windows 11 , 64 bit Build 22621 (10.0.22621.1344)
Time: Tue Apr  4 10:38:34 2023 Eastern Daylight Time elapsed time: 23414.169947 seconds (0d 6h 30m 14s)

---------------  T H R E A D  ---------------

Current thread (0x000001dd7d2fb000):  ConcurrentGCThread "G1 Conc#0" [stack: 0x0000001083c00000,0x0000001083d00000] [id=17032]

Stack: [0x0000001083c00000,0x0000001083d00000],  sp=0x0000001083cffaa8,  free space=1022k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x193e01]


siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000110


Register to memory mapping:

RIP=0x00007ffac3463e01 jvm.dll
RAX=0x0 is NULL
RBX=0x0421110040404129 is an unknown value
RCX=0x0000000800000009 is pointing into metadata
RDX=0x000000069d981420 is an oop: 
[error occurred during error reporting (printing register info), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffac38dbc2d]


```

### Please provide steps to reproduce where possible

I am not able to reproduce it but it seems to be related to user machine and higm memory usage\gc activity

### Expected Results

no crash

### Actual Results

the application crashes randomly 

### What Java Version are you using?

Temurin-11.0.16.1+1 

### What is your operating system and platform?

Windows 11

### Did it work before?

```Shell
the crash did not occured when we used oracle jdk 8u121
```

**Comment by karianna** [comment]
@adriantoganel please upgrade 11.0.18 and send in crash logs if they occur.

**Comment by heidenthal-gtisoft** [comment]
Our customers, who are using JVM 11.0.21_9, have continued to report JVM crashes which exhibit this signature

**Comment by adriantoganel** [comment]
Hi,

> does not work for us as can be seen in the log files
There is a typo, the package start with javax not java (javax.swing.plaf.basic.BasicSplitPaneUI)

**Comment by heidenthal-gtisoft** [comment]
@adriantoganel Thank you for spotting that!! Can't see the forest for the trees sometimes!

**Comment by lSherozl** [comment]
> [hs_err_pid15064.log](https://github.com/adoptium/adoptium-support/files/14196455/hs_err_pid15064.log) [replay_pid15064.log](https://github.com/adoptium/adoptium-support/files/14196456/replay_pid15064.log)
> 
> Our customers, who are using JVM 11.0.21_9, have continued to report JVM crashes which exhibit this signature.
> 
> Further, the fix in https://bugs.openjdk.org/browse/JDK-8304428 to use -XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer does not work for us as can be seen in the log files

Hi i have the same crash happening again and again, with the same problematic frame, can u please tell me how u fix it, I cant understand ur comment

**Comment by karianna** [comment]
Add `-XX:CompileCommand=exclude,javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer` to your command line

**Comment by heidenthal-gtisoft** [comment]
> > [hs_err_pid15064.log](https://github.com/adoptium/adoptium-support/files/14196455/hs_err_pid15064.log) [replay_pid15064.log](https://github.com/adoptium/adoptium-support/files/14196456/replay_pid15064.log)
> > Our customers, who are using JVM 11.0.21_9, have continued to report JVM crashes which exhibit this signature.
> > Further, the fix in https://bugs.openjdk.org/browse/JDK-8304428 to use -XX:CompileCommand=exclude,java.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager::layoutContainer does not work for us as can be seen in the log files
> 
> Hi i have the same crash happening again and again, with the same problematic frame, can u please tell me how u fix it, I cant understand ur comment

Yes, my previous CompileCommand has java.swing... not the required javax.swing... .  Please use the JVM argument that @karianna suggests above
