### ISSUE TITLE
Fedora 37 Issue

### ISSUE THREAD

**Issue by chu-1-chu** [adoptium/adoptium-support#767]
Hi! I'm using the official guide to enable the Adoptium repositories, but it doesn't work.
`sudo dnf update` output:

Warning: failed loading '/etc/yum.repos.d/adoptium.repo', skipping.

Last metadata expiration check: 3:40:35 ago on Fri 07 Apr 2023 05:36:04 AM CEST.

Dependencies resolved.

Nothing to do.

Complete!

what I put inside `/etc/yum.repos.d/adoptium.repo`:

cat <<'EOF > /etc/yum.repos.d/adoptium.repo

[Adoptium]

name=Adoptium

baseurl=https://packages.adoptium.net/artifactory/rpm/${DISTRIBUTION_NAME:-$(. /etc/os-release; echo $ID)}/\$releasever/\$basearch

enabled=1

gpgcheck=1

gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public

EOF

**Comment by karianna** [comment]
@chu-1-chu From which part of the world are you trying this and do you have a VPN that you are using?
