### ISSUE TITLE
Crashplan dies on startup with SIGSEGV

### ISSUE THREAD

**Issue by Subtalime** [adoptium/adoptium-support#768]
### Please provide a brief summary of the bug

Java virtual machine created.
Starting service.
[04.10.23 15:11:04.194 INFO  main             com.code42.utils.ClassFinder] Loaded classpaths in 514 ms
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007eff22be671a, pid=5757, tid=5864
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.18+10 (11.0.18+10) (build 11.0.18+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (11.0.18+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xe671a]  readdir64+0x2a
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/local/crashplan/core.5757)
#
# An error report file with more information is saved as:
# /usr/local/crashplan/hs_err_pid5757.log
[thread 5757 also had an error][thread 5869 also had an error]

### Please provide steps to reproduce where possible

Every time I start up Crashplan. Eventually... after maybe the 4th reboot, it works... only to die again half day later.

### Expected Results

Crashplan to run

### Actual Results

Crashplan crashes

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment Temurin-11.0.18+10 (11.0.18+10) (build 11.0.18+10)

### What is your operating system and platform?

Ubuntu 22.04.2 LTS

### How did you install Java?

Using "apt install default-jre"

### Did it work before?

```Shell
yes, it works and then doesn't... and then works again... no changes, not even OS updates...
```

### Did you test with the latest update version?

```Shell
Same outcome
```

### Relevant log output

```Shell
Initializing the JVM arguments.
Creating the Java virtual machine.
Number of arguments: 20
Java virtual machine created.
Starting service.
[04.10.23 15:23:26.783 INFO  main             com.code42.utils.ClassFinder] Loaded classpaths in 882 ms
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f364e9b771a, pid=1190, tid=2932
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.18+10 (11.0.18+10) (build 11.0.18+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (11.0.18+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xe671a]  readdir64+0x2a
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/local/crashplan/core.1190)
#
# An error report file with more information is saved as:
# /usr/local/crashplan/hs_err_pid1190.log
[thread 2936 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by Subtalime** [comment]
[hs_err_pid1190.log](https://github.com/adoptium/adoptium-support/files/11198045/hs_err_pid1190.log)

**Comment by Subtalime** [comment]
@karianna attached, sorry, was meant to with original submission. I have 6 more if you require.

**Comment by Subtalime** [comment]
@karianna attached, sorry, was meant to with original submission. I have 6 more if you require.

> ShrinkHeapInSteps

sorry for late response. Where would I change this? service.sh does not have this value stored... it calls /usr/local/crashplan/bin/CrashPlanService which is a binary?

**Comment by karianna** [comment]
@Subtalime I'm not familiar wit the CrashPlan app but I imagine it must have a config file containing those values, recommend grepping :-)

**Comment by Subtalime** [comment]
I have 'grepped', and only place is in the binary...
Will try and find out if it can be overwritten with some commandline arguments

**Comment by aberridg** [comment]
I have the same issue. It does not appear to be possible to adjust the command line arguments.

**Comment by karianna** [comment]
You'll both need to ask Crashplan support how they set those values.

**Comment by Dwper** [comment]
To the CrashPlan users.  I had this same problem and   got this info from CrashPlan that worked for me (I had a headless machine so #2 worked)

Maybe this info will be helpful to JRE maintainers to understand why the crash happened with no input devices.
———-
From CrashPlan
Our version 11 agent made some changes to our user activity detection. These changes had the side effect of causing an error if a mouse and keyboard are not in use on a system.

To that end we have two paths you can take to resolve the issues with CrashPlan:
Plug a mouse and keyboard into the physical hardware that is running the CrashPlan agent.
Create the path /dev/input/by-path on disk by running following command:
sudo mkdir -p /dev/input/by-path
 
 Once either of these actions have been taken we expect you will be able to start up CrashPlan and log in as normal.

**Comment by aberridg** [comment]
Yep that fixed it for me too. I suspect it's an issue with Crashplan and
nothing to do with the JRE but what do I know? This is just the only
reference I've found on the 'net to the issue.

**Comment by karianna** [comment]
Closing this as it was a Crashplan issue.
