### ISSUE TITLE
Disable automatic updates

### ISSUE THREAD

**Issue by grannymaster** [adoptium/adoptium-support#770]
## Question

We are currently runnin jdk-11.0.17.101-hotspot and we would like to disable updates. We would like to be able to update only when we allow it. Change of java version breaks our setup.

## Context

Java version:

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

Your operating system and platform:

Windows Server 2022 21H2

**Comment by karianna** [comment]
@grannymaster that's entirely up to you, our installers don't have auto-update in them, so as long as you don't download a new installer you should be fine.

**Comment by grannymaster** [comment]
Hmm.. our client is reporting that the version keeps changing without any intervention. I'll ask around more.
