### ISSUE TITLE
Im trying to uninstall Eclipse Temurin JRE with Hotspot 17.0.6 +10 (x64) 

### ISSUE THREAD

**Issue by whatyoudoinhere** [adoptium/adoptium-support#771]
Im trying to uninstall Eclipse Temurin JRE with Hotspot 17.0.6 +10 (x64)
is it fine to uninstall it through the Programs and Features application in my system? 
and will it break some of my computer's system?
![azjazdijpzfi](https://user-images.githubusercontent.com/130663053/231748787-4308bc6d-54df-4f00-ab35-9e36a443252d.png)

**Comment by karianna** [comment]
@whatyoudoinhere Yes it's fine to remove.
