### ISSUE TITLE
Im having trouble unistalling this and updating to a newer version of java

### ISSUE THREAD

**Issue by MC-Clutch** [adoptium/adoptium-support#772]
## Question

So this is kinda confusing for me so pls help. Im trying to update my java version and I tried unistalling this and I don't know how and I Installed java 17 from the main website but when I launch games that only work with 17 its not working

## Context

Java version: Java 16.0 ASM 9.4

Your operating system and platform: Windows 10 64 bit arceteture

**Comment by karianna** [comment]
@MC-Clutch - I assume you're playing Minecraft?

**Comment by MC-Clutch** [comment]
Yes, I installed the main version of java but it didn't uninstall the adoptium thing.

**Comment by karianna** [comment]
Minecraft should come with the Microsoft Build of OpenJDK 17.0.3 as a default.

See https://minecraft.fandom.com/wiki/Tutorials/Update_Java on how to change your Java for Minecraft.
