### ISSUE TITLE
MouseEvent class behaves differently in JDK11 and JDK8

### ISSUE THREAD

**Issue by munnanoori** [adoptium/adoptium-support#773]
### Please provide a brief summary of the bug

We are translating Received Swing MouseEvent for some customization. In our custom method we are creating a new MouseEvent instance by providing the details received as part of MouseClickEvent.
But the button field which is member of MouseEvent class filled with 0 value in the new instance of MouseEvent whereas the received event has button value as 1.
Copying the code below for reference:

            newEvent = new MouseEvent ( c, mevent.getID(),
                                    mevent.getWhen(), mevent.getModifiersEx(),
                                    point.x, point.y, mevent.getClickCount (),
                                    mevent.isPopupTrigger() ) ;

In the above code mevent also the instance of MouseEvent and has the value of button as 1 but when try to create a new MouseEvent from mevent the button value filled as 0 in newEvent. I am using JDK11 but in JDK 8 in both instances having the button value as 1.

### Please provide steps to reproduce where possible

Create a MouseEvent instance from existing MouseEvent and observed the button value

### Expected Results

The button value of MouseEvent should be consistent

### Actual Results

The button value of MouseEvent is changing based on JDK version

### What Java Version are you using?

openjdk version "11.0.18" 2023-01-17 OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10) OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

### What is your operating system and platform?

Windows Server 2012 R2

**Comment by karianna** [comment]
@munnanoori Can you post a Java source code file that has a single button component which highlights this problem?

**Comment by munnanoori** [comment]
We identified that one argument we changed for retrieving the modifiers is from java8 code to java11 as getModifiers method is deprecated from java9 onwards. But the return values from getModifiers () and getModifiersEx() different.  The method getModifiersEx() returns zero as value. I am not sure how we can achieve the same behavior with getModifiersEx(). Please suggest any recommendations on this. I am copying the MouseEvent instance creation code when using Java8 and Java11.

Java8: 

        newEvent = new MouseEvent ( c, mevent.getID(),
                                mevent.getWhen(), mevent.getModifiers(),
                                point.x, point.y, mevent.getClickCount (),
                                mevent.isPopupTrigger() ) ;


Java11:

        newEvent = new MouseEvent ( c, mevent.getID(),
                                mevent.getWhen(), mevent.getModifiersEx(),
                                point.x, point.y, mevent.getClickCount (),
                                mevent.isPopupTrigger() ) ;

**Comment by munnanoori** [comment]
Any recommendations on this?

**Comment by karianna** [comment]
Not sure I'm afraid, I may submit this as a bug upstream

**Comment by karianna** [comment]
It looks like getModifiersEx was backported to later versions of Java 8 - https://bugs.openjdk.org/browse/JDK-8041928 can you give that a go and see if you have parity?

**Comment by karianna** [comment]
Also see https://bugs.openjdk.org/browse/JDK-8043771 for more context
