### ISSUE TITLE
SIGSEGV on ZBarrier::mark_barrier_on_oop_slow_path

### ISSUE THREAD

**Issue by kimattree** [adoptium/adoptium-support#775]
### Please provide a brief summary of the bug

I have experienced this crash across 2 x microservices in the same cluster, randomly there is a crash with the reported error:

# V  [libjvm.so+0xf32adb]  ZBarrier::mark_barrier_on_oop_slow_path(unsigned long)+0x8b

### Please provide steps to reproduce where possible

Unable to reproduce manually, has occurred randomly over the past week 4 times across 2 services.

### Expected Results

no crash and normal operation

### Actual Results

java crashes, kubernetes liveness probe fails and pod restarts.

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)

### What is your operating system and platform?

Microservice pod running from base image "amd64/eclipse-temurin:17.0.3_7-jdk-alpine"
Running in a GKE Kubernetes 1.23 cluster

### How did you install Java?

Used the amd64/eclipse-temurin:17.0.3_7-jdk-alpine image from docker hub

### Did it work before?

```Shell
we have used this version for 6+ months - first recorded instance we've noticed but cannot discount previous events occurring - we have only 30 days of logs
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
Apr 14, 2023 @ 12:18:21.003	# Problematic frame:
Apr 14, 2023 @ 12:18:21.003	#  SIGSEGV (0xb) at pc=0x00007f6ef61b2adb, pid=7, tid=13
Apr 14, 2023 @ 12:18:21.003	# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
Apr 14, 2023 @ 12:18:21.003	#
Apr 14, 2023 @ 12:18:21.003	# A fatal error has been detected by the Java Runtime Environment:
Apr 14, 2023 @ 12:18:21.003	# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed class ptrs, z gc, linux-amd64)
Apr 14, 2023 @ 12:18:21.007	# Core dump will be written. Default location: /core.%e.7.%t
Apr 14, 2023 @ 12:18:21.007	# //hs_err_pid7.log
Apr 14, 2023 @ 12:18:21.007	#
Apr 14, 2023 @ 12:18:21.007	# V  [libjvm.so+0xf32adb]  ZBarrier::mark_barrier_on_oop_slow_path(unsigned long)+0x8b
Apr 14, 2023 @ 12:18:21.007	# An error report file with more information is saved as:
Apr 14, 2023 @ 12:18:21.009	 metadata       [0x00007f6ee8d65b68,0x00007f6ee8d66138] = 1488
Apr 14, 2023 @ 12:18:21.009	 stub code      [0x00007f6ee8d65a00,0x00007f6ee8d65b08] = 264
Apr 14, 2023 @ 12:18:21.009	 scopes pcs     [0x00007f6ee8d69728,0x00007f6ee8d6da38] = 17168
Apr 14, 2023 @ 12:18:21.009	 dependencies   [0x00007f6ee8d6da38,0x00007f6ee8d6dc00] = 456
Apr 14, 2023 @ 12:18:21.009	 relocation     [0x00007f6ee8d5ef70,0x00007f6ee8d5f4a0] = 1328
Apr 14, 2023 @ 12:18:21.009	 total in heap  [0x00007f6ee8d5ee10,0x00007f6ee8d6e2c0] = 62640
Apr 14, 2023 @ 12:18:21.009	 scopes data    [0x00007f6ee8d66138,0x00007f6ee8d69728] = 13808
Apr 14, 2023 @ 12:18:21.009	 handler table  [0x00007f6ee8d6dc00,0x00007f6ee8d6e0f8] = 1272
Apr 14, 2023 @ 12:18:21.009	 nul chk table  [0x00007f6ee8d6e0f8,0x00007f6ee8d6e2c0] = 456
Apr 14, 2023 @ 12:18:21.009	Compiled method (c2) 6896098 33692   !   4       org.springframework.web.servlet.DispatcherServlet::doDispatch (543 bytes)
Apr 14, 2023 @ 12:18:21.009	 main code      [0x00007f6ee8d5f4a0,0x00007f6ee8d65a00] = 25952
Apr 14, 2023 @ 12:18:21.009	 oops           [0x00007f6ee8d65b08,0x00007f6ee8d65b68] = 96
Apr 14, 2023 @ 12:18:21.012	 oops           [0x00007f6ee8d65b08,0x00007f6ee8d65b68] = 96
Apr 14, 2023 @ 12:18:21.012	 nul chk table  [0x00007f6ee8d6e0f8,0x00007f6ee8d6e2c0] = 456
Apr 14, 2023 @ 12:18:21.012	 relocation     [0x00007f6ee8d5ef70,0x00007f6ee8d5f4a0] = 1328
Apr 14, 2023 @ 12:18:21.012	 dependencies   [0x00007f6ee8d6da38,0x00007f6ee8d6dc00] = 456
Apr 14, 2023 @ 12:18:21.012	Compiled method (c2) 6896101 33692   !   4      org.springframework.web.servlet.DispatcherServlet::doDispatch (543 bytes)
Apr 14, 2023 @ 12:18:21.012	 total in heap  [0x00007f6ee8d5ee10,0x00007f6ee8d6e2c0] = 62640
Apr 14, 2023 @ 12:18:21.012	 handler table  [0x00007f6ee8d6dc00,0x00007f6ee8d6e0f8] = 1272
Apr 14, 2023 @ 12:18:21.012	 stub code      [0x00007f6ee8d65a00,0x00007f6ee8d65b08] = 264
Apr 14, 2023 @ 12:18:21.012	 metadata       [0x00007f6ee8d65b68,0x00007f6ee8d66138] = 1488
Apr 14, 2023 @ 12:18:21.012	 scopes data    [0x00007f6ee8d66138,0x00007f6ee8d69728] = 13808
Apr 14, 2023 @ 12:18:21.012	 main code      [0x00007f6ee8d5f4a0,0x00007f6ee8d65a00] = 25952
Apr 14, 2023 @ 12:18:21.012	 scopes pcs     [0x00007f6ee8d69728,0x00007f6ee8d6da38] = 17168
Apr 14, 2023 @ 12:18:21.042	# If you would like to submit a bug report, please visit:
Apr 14, 2023 @ 12:18:21.042	#   https://github.com/adoptium/adoptium-support/issues
Apr 14, 2023 @ 12:18:21.042	#
```

**Comment by kimattree** [comment]
Looking at APM tracing it looks like it is locking up on ZGC garbage collection:
![image](https://user-images.githubusercontent.com/11436848/233150115-f7a1e266-3ebd-4e3e-8e2a-bf71d8bf8cc6.png)

**Comment by karianna** [comment]
@kimattree please update to 17.0.7 and report back here if you still see the crash

**Comment by kimattree** [comment]
@karianna I have updated to 17.0.6_10 as there is no 17.0.7 in eclips-temurin in docker hub:

https://hub.docker.com/r/amd64/eclipse-temurin/tags?page=1&name=17.0.7

**Comment by karianna** [comment]
17.0.7 should be out in the next couple of working days.

**Comment by kimattree** [comment]
Just had the same SIGSEGV on an upgraded pod/image running 17.0.6_10

**Comment by karianna** [comment]
Thanks, are you able to send in the log from the 17.0.6 run?  I'll open a bug upstream.

**Comment by kimattree** [comment]
@karianna I was able to capture a full log as well as a Z-Worker core dump from 2 pods running in the cluster - they are pretty big 3Gb and 10Gb whats the preferred way to get these to you ?

![image](https://github.com/adoptium/adoptium-support/assets/11436848/91e03c35-5392-4dcf-b372-526a2de42a98)
![image](https://github.com/adoptium/adoptium-support/assets/11436848/caa4f4a4-7d38-4a79-a944-ae57714cb95f)

**Comment by karianna** [comment]
@kimattree Are those full application logs or the hs_err_pid7.log ?

**Comment by kimattree** [comment]
the .log files are ErrorFile, and the core files are from CoredumpOnCrash:

`-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/ -XX:+CrashOnOutOfMemoryError -XX:+CreateCoredumpOnCrash -XX:ErrorFile=/java_error.log`

**Comment by kimattree** [comment]
@karianna the new error logs have a lot more information in them, seems we've tracked it down to APM Java Agent:

`RAX=0x0000000000000768 is an unknown value
RBX=0x000003227503c420 is an unknown value
RCX=0x00007f2282eb8068: <offset 0x0000000001370068> in /opt/java/openjdk/lib/server/libjvm.so at 0x00007f2281b48000
RDX=0x00007f2282e60140: <offset 0x0000000001318140> in /opt/java/openjdk/lib/server/libjvm.so at 0x00007f2281b48000
RSP=0x00007f226a92f6e0 points into unknown readable memory: 0x000010009e040198 | 98 01 04 9e 00 10 00 00
RBP=0x00007f226a92f710 points into unknown readable memory: 0x00007f226a92f760 | 60 f7 92 6a 22 7f 00 00
RSI=0x0000080048ed9da0 is a good oop: java.lang.String 
{0x0000080048ed9da0} - klass: 'java/lang/String'
 - string: "co.elastic.apm.exception"`

There is an open task with elastic to investigate:

https://discuss.elastic.co/t/sigsegv-jvm-crash-with-zgc-garbage-collection/337269

**Comment by kimattree** [comment]
Still an open bug, but some changes:

* Changed base image from alpine to ubuntu, to test musl/glibc compatibility issues

But crashes still occurring.

**Comment by kimattree** [comment]
Removing APM agent resolves the crashes - closing ticket. Ongoing investigation with Elastic Here: https://discuss.elastic.co/t/sigsegv-jvm-crash-with-zgc-garbage-collection/337269/3
