### ISSUE TITLE
RHEL 8 installer - Failed to download metadata for repo

### ISSUE THREAD

**Issue by ilohjaacg** [adoptium/adoptium-support#776]
I am trying to install Java 17 on a RHEL 8 server using the Adoptium repo following the installation instructions (https://packages.adoptium.net/ui/native/rpm/rhel/8/x86_64/).
I have created an Ansible role which adds the repo and then installs Java.
But, every time I encounter this error:

`
fatal: [xx.xxx.xxx.xx]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'Adoptium': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
`

The Adoptium repo is successfully added (as I can see on the server's `/etc/yum.repos.d/`).

What I have tried so far:
After the repo has been added by my Ansible task, I tried installing Java manually: with no success.
Even doing `sudo yum update` results in the same error.
I am behind a proxy, so I have tried adding the proxy as an environment variable in Ansible, and as an extra variable on the command line.
The error persists.

Is there something that I am missing ?

**Comment by karianna** [comment]
Are you able to get more debug info from the task?  I suspect it's proxy config related

**Comment by ilohjaacg** [comment]
I have checked the content of Adoptium.repo on the server, and it's the correct one.

```
[Adoptium]
baseurl = https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64
enabled = 1
gpgcheck = 1
gpgkey = https://packages.adoptium.net/artifactory/api/gpg/key/public
name = Repo for Adoptium
```

**Comment by ilohjaacg** [comment]
It was in fact related to proxy (I had specified an http_proxy and not https_proxy (duh!)).
It is now fixed.
