### ISSUE TITLE
Getting segmentation error 

### ISSUE THREAD

**Issue by uday708** [adoptium/adoptium-support#777]
### Please provide a brief summary of the bug

Java version: openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

using eclipse temurin image with jruby version 
ENV JRUBY_VERSION=9.3.9.0 \

JRUBY_SHA256=251e6dd8d1d2f82922c8c778d7857e1bef82fe5ca2cf77bc09356421d0b05ab8

facing issue:

`
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00000000000036ee, pid=26, tid=30

 JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  0x00000000000036ee

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /blacklist/hs_err_pid26.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Aborted`

### Please provide steps to reproduce where possible

While running `bundle exec rspec` in container facing 

### Expected Results

Test cases should run

### Actual Results

`A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00000000000036ee, pid=26, tid=30

 JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  0x00000000000036ee

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /blacklist/hs_err_pid26.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Aborted`

### What Java Version are you using?

openjdk 17.0.4.1 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

**Comment by karianna** [comment]
@uday708 Please try with our latest 17.0.7 and post back here

**Comment by uday708** [comment]
@karianna 
Hi I have found out I am facing this issue because of `Bounce Studio API`. I am doing Extract the Bounce Studio API library from the RPM, symlink it, then remove rpm tools cause they adds a lot of bloat to the container.
Do you have Idea about it. Using bouncestudio-3.7.0.850-1.x86_64.rpm

**Comment by karianna** [comment]
I'm not sure of that product/tool sorry, it does sound like you have a lot of moving parts there though that could introduce a bug.  Did you try 17.0.7 JIC?

**Comment by uday708** [comment]
not able to find ecilipse-temurin alpine image 17.0.7

**Comment by karianna** [comment]
Will be out early next week.

**Comment by loehnertz** [comment]
For me, this was happening specifically only in the Alpine image as it's missing a library that other Linuxes have shipped by default (see here: https://github.com/micrometer-metrics/micrometer/issues/2776#issuecomment-924430670). Note that this was specific to me using Netty inside of the JVM, so your problem could be completely unrelated.
Switching to a Ubuntu-based image of Adoptium fixed it for me though and since you mentioned the Alpine image, @uday708, I figured I'll post this here.
