### ISSUE TITLE
Java Runtime Error

### ISSUE THREAD

**Issue by Loganplayz124** [adoptium/adoptium-support#778]
### Please provide a brief summary of the bug

So I was trying to make a MC mod with MCreator But when I tried to test out/launch the game with the mod it just wouldn't work!. I tried everything I deleted mod elements, Heck! I even made a mod that didn't have anything in it and tried to run and GUESS WHAT!!? IT DIDN'T WORK!. I'm being as nice as I can so please fix this :( .

### Expected Results

That the game would launch and it would be perfectly fine.

### Actual Results

I didn't launch.

### What Java Version are you using?

1.19.4

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by Loganplayz124** [comment]
Hello sorry for the late reply I have fixed the issue I just needed to
update my drivers with the AMD software.
