### ISSUE TITLE
How to stop Temurin Java Automatic Updates

### ISSUE THREAD

**Issue by h2obringer** [adoptium/adoptium-support#781]
## Question

I have a need to stay on a specific version of Java and we only want to upgrade Java when we are ready and have tested that an updated version still works for our code base. How do I stop Temurin Java from Automatically Updating to a newer version? I originally had installed Temurin Java JDK x64 v17.0.6_10 via the .msi installer, selecting to set the JAVA_HOME variable during installation. I performed the install on 4/6/2023. When I looked at the Windows Control Panel to look at Programs and Features that are installed I see 3 entries for Temurin Java:
1. Eclipse Temurin JDK with Hotspot 17.0.6+10 (x64) installed on 4/6/2023 (Version: 17.0.6.10)
2. Eclipse Temurin JDK with Hotspot 19.0.2+7 (x64) installed on 4/9/2023 (Version: 19.0.2.7)
3. Eclipse Temurin JDK with Hotspot 20+36 (x64) installed on 4/16/2023 (Version: 20.0.0.36)

How can I stop Temurin from automatically updating the installation?

## Context

Java version:_______________________________________________________________________________________________

openjdk 20 2023-03-21
OpenJDK Runtime Environment Temurin-20+36 (build 20+36)
OpenJDK 64-Bit Server VM Temurin-20+36 (build 20+36, mixed mode, sharing)

Your operating system and platform:______________________________________________________________________

Microsoft Windows Server 2019 Standard on x64

**Comment by karianna** [comment]
@h2obringer We do not auto update, so you'll need to check your admin log as to when someone installed 19 and 20 beside 17)

**Comment by h2obringer** [comment]
Thank you for the response I will go and do some investigating there.
