### ISSUE TITLE
Eclipse in STM32CubeIDE no longer creates a new workspace - crashes

### ISSUE THREAD

**Issue by mrjimenez** [adoptium/adoptium-support#785]
### Please provide a brief summary of the bug

I can no longer create a new workspace. The IDE crashes. STM32CubeIDE.

### Please provide steps to reproduce where possible

- Start the IDE
- When prompted to choose the workspace, choose to create a new workspace. The program crashes.

### Expected Results

I would expect that a new workspace would have been created.

### Actual Results

Program crashes.

### What Java Version are you using?

openjdk 11.0.19 2023-04-18 OpenJDK Runtime Environment (build 11.0.19+0-suse-1.1-x8664) OpenJDK 64-Bit Server VM (build 11.0.19+0-suse-1.1-x8664, mixed mode)

### What is your operating system and platform?

---------------  S Y S T E M  ---------------

OS:NAME="openSUSE Tumbleweed"
# VERSION="20230429"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230429"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230429"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
uname:Linux 6.2.12-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr 20 11:01:10 UTC 2023 (eb3255d) x86_64
OS uptime: 0 days 4:18 hours
libc:glibc 2.37 NPTL 2.37 
rlimit (soft/hard): STACK 8192k/infinity , CORE infinity/infinity , NPROC 128017/128017 , NOFILE 4096/4096 , AS infinity/infinity , CPU infinity/infinity , DATA infinity/infinity , FSIZE infinity/infinity , MEMLOCK 8192k/8192k

### How did you install Java?

RPM

### Did it work before?

```Shell
Yes.
```

### Did you test with the latest update version?

```Shell
Of STM32CubeIDE, Yes.
```

### Did you test with other Java versions?

```Shell
No.
```

### Relevant log output

```Shell
$ /home/mroberto/st/stm32cubeide_1.12.1/stm32cubeide
SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory
SWT WebKit: error initializing DBus server, dBusServer == 0

(STM32CubeIDE:22039): GLib-GIO-CRITICAL **: 00:48:18.989: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4973c3ed16, pid=22039, tid=22040
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/mroberto/mrj/xyz/tmp/core.22039)
#
# An error report file with more information is saved as:
# /home/mroberto/mrj/xyz/tmp/hs_err_pid22039.log
Compiled method (nm)   10246 4010     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f4a5fcb1590,0x00007f4a5fcb1930] = 928
 relocation     [0x00007f4a5fcb1708,0x00007f4a5fcb1738] = 48
 main code      [0x00007f4a5fcb1740,0x00007f4a5fcb1928] = 488
 oops           [0x00007f4a5fcb1928,0x00007f4a5fcb1930] = 8
Compiled method (nm)   10248 4010     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f4a5fcb1590,0x00007f4a5fcb1930] = 928
 relocation     [0x00007f4a5fcb1708,0x00007f4a5fcb1738] = 48
 main code      [0x00007f4a5fcb1740,0x00007f4a5fcb1928] = 488
 oops           [0x00007f4a5fcb1928,0x00007f4a5fcb1930] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by mrjimenez** [comment]
Log attached.
[hs_err_pid22039.log](https://github.com/adoptium/adoptium-support/files/11363411/hs_err_pid22039.log)

**Comment by karianna** [comment]
The crash is occurring at:

```
C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
j  org.eclipse.swt.internal.Converter.cCharPtrToJavaString(JZ)Ljava/lang/String;+1
j  org.eclipse.swt.browser.WebKit$WebKitExtension.initializeWebExtensions_callback(JJ)V+178
```

Do you have the latest GTK drivers installed?

Also, the crash log claims 11.0.17 but you have 11.0.19 installed so there is a mismatch there

**Comment by mrjimenez** [comment]
Hi, @karianna , thank you for your quick response.

> The crash is occurring at:
> 
> ```
> C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
> j  org.eclipse.swt.internal.Converter.cCharPtrToJavaString(JZ)Ljava/lang/String;+1
> j  org.eclipse.swt.browser.WebKit$WebKitExtension.initializeWebExtensions_callback(JJ)V+178
> ```
> 
> Do you have the latest GTK drivers installed?

I had my system updated with `zypper dup`, which is supposedly the proper way to update OpenSUSE Tumbleweed. But I can check, what are the latest GTK drivers?

> Also, the crash log claims 11.0.17 but you have 11.0.19 installed so there is a mismatch there

I might have messed up because I tried to update the system software and I had lots of logs, so I am doing it again.

```bash
$ java --version 
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+0-suse-1.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.19+0-suse-1.1-x8664, mixed mode)
```

```bash
$ /home/mroberto/st/stm32cubeide_1.12.1/stm32cubeide
SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory
SWT WebKit: error initializing DBus server, dBusServer == 0

(STM32CubeIDE:15675): GLib-GIO-CRITICAL **: 10:30:54.787: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd1da43ed16, pid=15675, tid=15676
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/mroberto/mrj/stm32cubeide-bug/core.15675)
#
# An error report file with more information is saved as:
# /home/mroberto/mrj/stm32cubeide-bug/hs_err_pid15675.log
Compiled method (nm)   50267 3933     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fd287cae310,0x00007fd287cae6b0] = 928
 relocation     [0x00007fd287cae488,0x00007fd287cae4b8] = 48
 main code      [0x00007fd287cae4c0,0x00007fd287cae6a8] = 488
 oops           [0x00007fd287cae6a8,0x00007fd287cae6b0] = 8
Compiled method (nm)   50267 3933     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fd287cae310,0x00007fd287cae6b0] = 928
 relocation     [0x00007fd287cae488,0x00007fd287cae4b8] = 48
 main code      [0x00007fd287cae4c0,0x00007fd287cae6a8] = 488
 oops           [0x00007fd287cae6a8,0x00007fd287cae6b0] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Looks like STM32CubeIDE is using a different JDK from the one installed in the system.

[hs_err_pid15675.log](https://github.com/adoptium/adoptium-support/files/11365597/hs_err_pid15675.log)

**Comment by mrjimenez** [comment]
All JDK Installed:

```bash
$ rpm -qa | grep -i jdk
java-1_8_0-openjdk-headless-1.8.0.362-1.3.x86_64
java-1_8_0-openjdk-1.8.0.362-1.3.x86_64
java-11-openjdk-11.0.19.0-1.1.x86_64
java-1_8_0-openjdk-devel-1.8.0.362-1.3.x86_64
java-11-openjdk-headless-11.0.19.0-1.1.x86_64
```

**Comment by mrjimenez** [comment]
It seems like it does indeed comes with its own version of OpenJDK

```bash
$ /home/mroberto/st/stm32cubeide_1.12.1/plugins/com.st.stm32cube.ide.jre.linux64_2.4.101.202303251752/jre/bin/java --version 
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

**Comment by dmelentyev** [comment]
Just in case: you can start ide with different java. Just set different VM in your "/opt/st/stm32cubeide_1.12.1/stm32cubeide.ini" (I'm on Ubuntu 23.04, same issue):

-vm
+ /usr/lib/jvm/java-17-openjdk-amd64/bin
- plugins/com.st.stm32cube.ide.jre.linux64_2.4.101.202303251752/jre/bin

Does not change the result though. Crashes at the same "strlen" stuff somewhere in webkit (I guess)

**Comment by karianna** [comment]
I recommend sending in a bug report to STM32CubeIDE as they first need to investigate that teh are calling the native lib correctly

**Comment by mrjimenez** [comment]
I did so, but they don't seem to have a bug tracker.

[Can no longer create a new workspace - STM32CubeIDE 1.12.1](https://community.st.com/s/question/0D53W00002FDNNJSA5/can-no-longer-create-a-new-workspace-stm32cubeide-1121)

**Comment by karianna** [comment]
You may have luck finding the right repo: https://github.com/STMicroelectronics

**Comment by karianna** [comment]
As the other user stated on the community forum they need to change their native string length call to be safe.

**Comment by TheWeirdDev** [comment]
I had the same issue and this line of the error message caught my eye:
`SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory`

I looked into the source code of SWT to find out where this error happens. I saw it wants to open a directory named `/tmp/SWT-GDBusServer` and throws the error if it doesn't exist. so I manually created this directory and to my surprise it fixed the issue.


```bash
mkdir /tmp/SWT-GDBusServer
```

**Comment by bibble235** [comment]
Thanks @TheWeirdDev , spent the weekend, and no one in our game gets much free time, looking at this. Left a comment on ST32 for others but the prize is all yours. https://community.st.com/s/question/0D53W00002IMDFZSA5/import-project-in-vs-code-ubuntu-2304?t=1686444054254

**Comment by mrjimenez** [comment]
Fixed for me too. Amazing hack, congratulations @TheWeirdDev !

**Comment by SimeonPr** [comment]
Fixed it for me as well. Thanks @TheWeirdDev!

**Comment by Aletz-Arce** [comment]
Thanks!! @TheWeirdDev

**Comment by ozanerturk** [comment]
> I had the same issue and this line of the error message caught my eye: `SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory`
> 
> I looked into the source code of SWT to find out where this error happens. I saw it wants to open a directory named `/tmp/SWT-GDBusServer` and throws the error if it doesn't exist. so I manually created this directory and to my surprise it fixed the issue.
> 
> ```shell
> mkdir /tmp/SWT-GDBusServer
> ```

You're the best!

**Comment by oleosterhagen** [comment]
This is a bug in [Eclipse SWT](https://github.com/eclipse-platform/eclipse.platform.swt) that was introduced with https://github.com/eclipse-platform/eclipse.platform.swt/commit/19153b908d6d4cedcbd59824686717502cfde4f7.

Before this change, the path for the _D-Bus server_ address was created by calling `g_dir_make_tmp`, which creates a subdirectory in the folder for temporary files. After this change, this method is no longer called. But the address still uses a subdirectory of the `/tmp` folder: `unix:tmpdir=/tmp/SWT-WebExtensionGDBusServer`.

From the commit message you can see, that the intention was to use an **abstract socket** instead of a **path-based socket**:

> Removed unnecessary temporary directory creation, as Linux supports abstract addresses (compared to path-based addresses).

But the used address `unix:tmpdir` may not always create an abstract socket (see [D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html)). To get always an abstract socket (on supported platforms) the address `unix:abstract` has to be used.

The code has now been completely revised and does not use D-Bus anymore: https://github.com/eclipse-platform/eclipse.platform.swt/commit/a56c5b55c9ec05607ae31a2f3865406d2288980f. This change has been released with Eclipse 2022-06 (4.24).

**Comment by robinjere** [comment]
@TheWeirdDev Dude I owe you my life

**Comment by TheWeirdDev** [comment]
> @TheWeirdDev Dude I owe you my life

Lol, I'm glad I could help.

**Comment by minecraft2048** [comment]
> I had the same issue and this line of the error message caught my eye: `SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory`
> 
> I looked into the source code of SWT to find out where this error happens. I saw it wants to open a directory named `/tmp/SWT-GDBusServer` and throws the error if it doesn't exist. so I manually created this directory and to my surprise it fixed the issue.
> 
> ```shell
> mkdir /tmp/SWT-GDBusServer
> ```

This workaround fixed Microchip SoftConsole IDE: https://www.microchip.com/en-us/products/fpgas-and-plds/fpga-and-soc-design-tools/soc-fpga/softconsole
