### ISSUE TITLE
Crashing when opening world on 1.15.1 oceanblock

### ISSUE THREAD

**Issue by Ivannivi** [adoptium/adoptium-support#786]
### Please provide a brief summary of the bug

when i join the world its loading and then just crashes

### Please provide steps to reproduce where possible

1. i launch oceanblock 1.15.1 from ftb app
2. i opening my world
3. game crashes without error showing up

### Expected Results

no crash

### Actual Results

game crashing

### What Java Version are you using?

OpenJdk64

### What is your operating system and platform?

Windows 10 Pro

### How did you install Java?

ftb app installed itsself

### Did it work before?

```Shell
no
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
https://drive.google.com/drive/folders/1amngJgXNgAg3R6Gwfu_mioFbgPU4_Naf?usp=sharing
```

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
