### ISSUE TITLE
JVM is crashing [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf

### ISSUE THREAD

**Issue by alexsuter** [adoptium/adoptium-support#789]
### Please provide a brief summary of the bug

As soon as I start a web view in Eclipse, the JVM is crashing

```
(Axon Ivy:13108): GLib-GIO-CRITICAL **: 15:50:28.374: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcd2223ed16, pid=13108, tid=13109
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/alex/Downloads/AxonIvyDesigner11.2.0.2305101531_Linux_x64/core.13108)
#
# An error report file with more information is saved as:
# /home/alex/Downloads/AxonIvyDesigner11.2.0.2305101531_Linux_x64/hs_err_pid13108.log
Compiled method (n/a)   26046 6299     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fce45406d10,0x00007fce45407088] = 888
 relocation     [0x00007fce45406e70,0x00007fce45406ea0] = 48
 main code      [0x00007fce45406ea0,0x00007fce45407080] = 480
 oops           [0x00007fce45407080,0x00007fce45407088] = 8
Compiled method (n/a)   26047 6299     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007fce45406d10,0x00007fce45407088] = 888
 relocation     [0x00007fce45406e70,0x00007fce45406ea0] = 48
 main code      [0x00007fce45406ea0,0x00007fce45407080] = 480
 oops           [0x00007fce45407080,0x00007fce45407088] = 8
```

### Expected Results

Not crashing

### Actual Results

Crashing

### What Java Version are you using?

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 23.04 Intel

### How did you install Java?

debian package

### Did it work before?

```Shell
no
```

### Did you test with the latest update version?

```Shell
yes
```

**Comment by karianna** [comment]
Recommend reporting this to the folks who are supplying the AxonIvyDesigner11.2.0.2305101531_Linux_x64 product, they're making a native call via SWT that's causing GTK to send back a crash signal that propagates through the JVM, they likely need to make a fix on their end

**Comment by alexsuter** [comment]
Thanks for feedback. I'm the guy who is making AxonIvyDesigner :)

Axon Ivy Designer is built on Eclipse, and currently we use 2022-03, which may cause the problem. I'll try to reproduce the problem with plain eclipse 2022-03. 

It seems that it is no problem with eclipse 2023-03.

**Comment by karianna** [comment]
> Thanks for feedback. I'm the guy who is making AxonIvyDesigner :)
> 
> Axon Ivy Designer is built on Eclipse, and currently we use 2022-03, which may cause the problem. I'll try to reproduce the problem with plain eclipse 2022-03.
> 
> It seems that it is no problem with eclipse 2023-03.

:-D - Sorry about that!  Yes in that case it is an Eclipse SWT bug and you'll need to upgrade to that latest base.

**Comment by alexsuter** [comment]
@karianna 

I can confirm that the error occurs in plain Eclipse 2022-03, but not in plain Eclipse 2023-03.

Thanks for beeing highly responsive!
