### ISSUE TITLE
Crash after pasting text from another program

### ISSUE THREAD

**Issue by IZWO** [adoptium/adoptium-support#792]
### Please provide a brief summary of the bug

Crash after pasting text from another program or doing some simultaneous tasks in other programs

### Expected Results

no crash

### Actual Results

crash

### What Java Version are you using?

openjdk 17.0.6 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04) OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### How did you install Java?

dnf install

**Comment by IZWO** [comment]
[hs_err_pid618629.log](https://github.com/adoptium/adoptium-support/files/11449242/hs_err_pid618629.log)

**Comment by karianna** [comment]
@IZWO The log file says you're using our 19.0.1+10 build which is no longer supported.  Please use 17.0.7 and also upgrade your Eclipse IDE to the latest 2023 version.

**Comment by IZWO** [comment]
[](url)
[hs_err_pid359892.log](https://github.com/adoptium/adoptium-support/files/11459232/hs_err_pid359892.log)
same behaviour

**Comment by karianna** [comment]
@IZWO I assume your Eclipse IDE and O/S are at the latest patched levels?  I suspect it's an SWT native lib crash

**Comment by IZWO** [comment]
> @IZWO I assume your Eclipse IDE and O/S are at the latest patched levels? I suspect it's an SWT native lib crash

yes, the crash is very often (after mutliple OS/IDE updates remaining), not clear when it will happen, somtimes also "Refresh Gradle Project" crashes.

**Comment by karianna** [comment]
@IZWO Eclipse IDE has recently updated to their June 2023 release (containing a number of bug fixes for Linux desktop).  Can you upgrade and see if that resolves your issue?
