### ISSUE TITLE
SIGSEGV on frame  MetadataOnStackMark::~MetadataOnStackMark()

### ISSUE THREAD

**Issue by will-zdu** [adoptium/adoptium-support#794]
### Please provide a brief summary of the bug

 A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007fc93cce3444, pid=112650, tid=0x00007fb55dbb9700

RE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 )
Problematic frame:
 V  [libjvm.so+0x8c4444]  MetadataOnStackMark::~MetadataOnStackMark()+0xb4

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-support/issues

---------------  T H R E A D  ---------------

Current thread (0x00007fc938c7a800):  VMThread [stack: 0x00007fb55daba000,0x00007fb55dbba000] [id=112821]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000007a80827

Registers:
RAX=0x0000000007a807df, RBX=0x00007fc8842fa970, RCX=0x0000000080080001, RDX=0x0000000080000001
RSP=0x00007fb55dbb8760, RBP=0x00007fb55dbb8780, RSI=0x0000000000000000, RDI=0x00007fa7de71a330
R8 =0x00007fc93d44390c, R9 =0x0000000000000001, R10=0x0000000000000001, R11=0x000dad9a3730d4f2
R12=0x00007fc8842fa920, R13=0x00007fc8842fab20, R14=0x00007fb55dbb87e0, R15=0x00007fb55dbb88a0
RIP=0x00007fc93cce3444, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fb55dbb8760)
0x00007fb55dbb8760:   00001dbb761dfb08 00007fc938c7af50
0x00007fb55dbb8770:   00007fb55dbb8870 0000000000000001
0x00007fb55dbb8780:   00007fb55dbb8940 00007fc93c8be65a
0x00007fb55dbb8790:   0000000000000020 00007fb55dbb88a0
0x00007fb55dbb87a0:   00007fb55dbb87e0 00000000000003d8
0x00007fb55dbb87b0:   00007fc9380acc80 00007fb55dbb88d0
0x00007fb55dbb87c0:   00007fc938c27828 00007fc938c27450
0x00007fb55dbb87d0:   00007fb55dbb8840 00007fc938c27440
0x00007fb55dbb87e0:   00007fc93d379da8 00007fb55dbb8700
0x00007fb55dbb87f0:   00007fc938023400 00007fc8f77e2700
0x00007fb55dbb8800:   00007fc93d379df0 00007fc93815baa0
0x00007fb55dbb8810:   00007fc938188980 0000000000000001
0x00007fb55dbb8820:   0000000000000000 0000000000005ce2
0x00007fb55dbb8830:   000000000000149b 000000000000045a
0x00007fb55dbb8840:   00007fc93cfa912d 00007fc93cd80001
0x00007fb55dbb8850:   00007fc9380acc80 00001dbb6b586e1b
0x00007fb55dbb8860:   00003b52db9cd876 00007fc93cb590e6
0x00007fb55dbb8870:   00007fc93cfa915e 00007fc938020001
0x00007fb55dbb8880:   00007fc9380acc80 00001dbb6cc98a43
0x00007fb55dbb8890:   00003b52de7d54a0 0000004000000018
0x00007fb55dbb88a0:   00007fc93cfa9168 00007fc93d7e0000
0x00007fb55dbb88b0:   00007fc9380acc80 00001dbb749923db
0x00007fb55dbb88c0:   00003b52ee13214c 00007fc938005601
0x00007fb55dbb88d0:   00007fc938c7a800 00007fc938c7af90
0x00007fb55dbb88e0:   00007fc938c7afd0 00007fc938c7afe0
0x00007fb55dbb88f0:   00007fc938c7b0b8 00000000000000d8
0x00007fb55dbb8900:   00007fb55dbb8bd0 00007fb55dbb897e
0x00007fb55dbb8910:   00007fb55dbb8940 00007fc938023400
0x00007fb55dbb8920:   0000000000000000 00007fb55dbb897e
0x00007fb55dbb8930:   00007fb55dbb8980 00007fc93815baa0
0x00007fb55dbb8940:   00007fb55dbb89f0 00007fc93c8c2914
0x00007fb55dbb8950:   00007fc93801b7c0 00007fc9380056a0 

Instructions: (pc=0x00007fc93cce3444)
0x00007fc93cce3424:   c1 e8 03 48 85 c0 74 20 4d 8d 2c c4 4c 89 e3 0f
0x00007fc93cce3434:   1f 44 00 00 48 8b 3b 48 83 c3 08 31 f6 48 8b 07
0x00007fc93cce3444:   ff 50 48 4c 39 eb 75 ec 49 8b 84 24 08 02 00 00
0x00007fc93cce3454:   48 8b 15 ed f9 75 00 4d 89 a4 24 00 02 00 00 49 

Register to memory mapping:

RAX=0x0000000007a807df is an unknown value
RBX=0x00007fc8842fa970 is an unknown value
RCX=0x0000000080080001 is an unknown value
RDX=0x0000000080000001 is an unknown value
RSP=0x00007fb55dbb8760 is an unknown value
RBP=0x00007fb55dbb8780 is an unknown value
RSI=0x0000000000000000 is an unknown value
RDI=0x00007fa7de71a330 is pointing into metadata
R8 =0x00007fc93d44390c: <offset 0x102490c> in /Raid/atlassian/jira/jre/lib/amd64/server/libjvm.so at 0x00007fc93c41f000
R9 =0x0000000000000001 is an unknown value
R10=0x0000000000000001 is an unknown value
R11=0x000dad9a3730d4f2 is an unknown value
R12=0x00007fc8842fa920 is an unknown value
R13=0x00007fc8842fab20 is an unknown value
R14=0x00007fb55dbb87e0 is an unknown value
R15=0x00007fb55dbb88a0 is an unknown value

Stack: [0x00007fb55daba000,0x00007fb55dbba000],  sp=0x00007fb55dbb8760,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x8c4444]  MetadataOnStackMark::~MetadataOnStackMark()+0xb4
V  [libjvm.so+0x49f65a]  ConcurrentMark::weakRefsWork(bool)+0x6ca
V  [libjvm.so+0x4a3914]  ConcurrentMark::checkpointRootsFinal(bool)+0xb4
V  [libjvm.so+0xb37a46]  VM_CGC_Operation::doit()+0xa6
V  [libjvm.so+0xb36f46]  VM_Operation::evaluate()+0x46
V  [libjvm.so+0xb34d3a]  VMThread::evaluate_operation(VM_Operation*) [clone .constprop.54]+0xfa
V  [libjvm.so+0xb3523b]  VMThread::loop()+0x3ab
V  [libjvm.so+0xb35669]  VMThread::run()+0xa9
V  [libjvm.so+0x95c802]  java_start(Thread*)+0x102

VM_Operation (0x00007fc7c06c6e50): CGC_Operation, mode: safepoint, requested by thread 0x00007fc93815c800

### Expected Results

No SIGSEGV

### Actual Results

found  SIGSEGV

### What Java Version are you using?

1.8.0_275

**Comment by karianna** [comment]
@will-zdu please upgrade to 1.8.0_372 and post back here if the issue persists

**Comment by will-zdu** [comment]
@karianna  I will try check it,Can you tell us what might be the cause of this problem? What could it have to do with？
Stack: [0x00007fb55daba000,0x00007fb55dbba000],  sp=0x00007fb55dbb8760,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x8c4444]  MetadataOnStackMark::~MetadataOnStackMark()+0xb4
V  [libjvm.so+0x49f65a]  ConcurrentMark::weakRefsWork(bool)+0x6ca
V  [libjvm.so+0x4a3914]  ConcurrentMark::checkpointRootsFinal(bool)+0xb4
V  [libjvm.so+0xb37a46]  VM_CGC_Operation::doit()+0xa6
V  [libjvm.so+0xb36f46]  VM_Operation::evaluate()+0x46
V  [libjvm.so+0xb34d3a]  VMThread::evaluate_operation(VM_Operation*) [clone .constprop.54]+0xfa
V  [libjvm.so+0xb3523b]  VMThread::loop()+0x3ab
V  [libjvm.so+0xb35669]  VMThread::run()+0xa9
V  [libjvm.so+0x95c802]  java_start(Thread*)+0x102

VM_Operation (0x00007fc7c06c6e50): CGC_Operation, mode: safepoint, requested by thread 0x00007fc93815c800

**Comment by karianna** [comment]
It's a crash when the JVM is executing a GC and checking weak references.  I suspect 1.8.0_372 will have the bug fix

**Comment by will-zdu** [comment]
@karianna  I was trying to reproduce it，but as my option，I have never seen the difference  metadataOnStackMark.cpp  between 1.8.0_275 and 1.8.0_372,I am afarid 1.8.0_372 will not fix it , and this will be happen in product env,could you please give me more evidence 
to proof it ,I will trying to check it on production env

**Comment by karianna** [comment]
1.8.0_382 is the latest release you should try.

**Comment by Geker** [comment]
> 1.8.0_382 is the latest release you should try.
8.0_422 still have the issue

# JRE version: OpenJDK Runtime Environment (8.0_422-b05) (build 1.8.0_422-b05)
# Java VM: OpenJDK 64-Bit Server VM (25.422-b05 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x8c19ca]  MetadataOnStackMark::~MetadataOnStackMark()+0xca

**Comment by karianna** [comment]
@Geker Can you send in the full log?
