### ISSUE TITLE
Stoneblock 3 crashing

### ISSUE THREAD

**Issue by Chillthuggin1** [adoptium/adoptium-support#802]
### Please provide a brief summary of the bug

I launch SB3 and it runs normally but sometimes a REI box shows up saying it's loading which lags the game then can crash it entirely, crashes whenever or when alt tabbing. error is listed as: `java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length O at java.base/jdk.internal.util.Preconditions.outOfBo unds(Unknown Source) at java.base/jdk.internal.util.Preconditio ns.outOfBoundsCheckIndex(Unknown Source) at java.base/jdk. internal.util.Preconditions.checkIndex(Unknown Source)

### Expected Results

The game to not crash

### Actual Results

Crashed

### What Java Version are you using?

java 19.0.2 2023-01-17 Java(TM) SE Runtime Environment (build 19.0.2+7-44) Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

### What is your operating system and platform?

Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
NVIDIA GeForce GTX 1650 SUPER
16Gb RAM
AMD Ryzen 5 3500 6-Core Processor

### How did you install Java?

Through oracle.

### Did it work before?

```Shell
No
```

### Did you test with the latest update version?

```Shell
no
```

### Relevant log output

```Shell
https://pastebin.com/x1Bv65B6
```

**Comment by karianna** [comment]
Java 19.0.2 is not supported.  For Minecraft related gaming we recommend 17.0.7 and make sure to update your drivers.
