### ISSUE TITLE
SIGSEGV (0xb)

### ISSUE THREAD

**Issue by cailtin** [adoptium/adoptium-support#803]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f87be83ed16, pid=9524, tid=9525
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.14+9 (11.0.14+9) (build 11.0.14+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (11.0.14+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4948r9.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/clopez/BonitaStudioCommunity-2022.1-u0/core.9524)
#
# An error report file with more information is saved as:
# /home/clopez/BonitaStudioCommunity-2022.1-u0/hs_err_pid9524.log
Compiled method (nm)    6515 8192     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f891caa1f90,0x00007f891caa2330] = 928
 relocation     [0x00007f891caa2108,0x00007f891caa2138] = 48
 main code      [0x00007f891caa2140,0x00007f891caa2328] = 488
 oops           [0x00007f891caa2328,0x00007f891caa2330] = 8
Compiled method (nm)    6517 8192     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f891caa1f90,0x00007f891caa2330] = 928
 relocation     [0x00007f891caa2108,0x00007f891caa2138] = 48
 main code      [0x00007f891caa2140,0x00007f891caa2328] = 488
 oops           [0x00007f891caa2328,0x00007f891caa2330] = 8
[thread 9626 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

### Please provide steps to reproduce where possible

[hs_err_pid4642.log](https://github.com/adoptium/adoptium-support/files/11533951/hs_err_pid4642.log)

### Expected Results

tried to open the app

### Actual Results

crash

### What Java Version are you using?

9.0.1

### What is your operating system and platform?

open suse 
Linux torin 6.3.2-1-default #1 SMP PREEMPT_DYNAMIC Mon May 15 15:59:38 UTC 2023 (70ea6f6) x86_64 x86_64 x86_64 GNU/Linux

### How did you install Java?

tried with jdk 9 from Oracle

### Did it work before?

```Shell
do not recall
```

### Did you test with the latest update version?

```Shell
Yes 11 and 19
```

**Comment by jiekang** [comment]
Probably an Eclipse SWT bug, others reported this for their Eclipse based IDEs here:

https://github.com/adoptium/adoptium-support/issues/798

**Comment by karianna** [comment]
@cailtin Please also try 11.0.19 JIc it is a JVM issue (it is most likely an SWT problem though).

**Comment by Breezeman69** [comment]
Still seeing this issue.  Any thoughts on how to p[roceed diagnosis.  I am using Talend Open Studio v8 pn Fedora 38

**Comment by karianna** [comment]
@Breezeman69 https://github.com/adoptium/adoptium-support/issues/785#issuecomment-1585740194 might help, but you'll need to report this to the Talend Studio folks.

**Comment by Breezeman69** [comment]
Thank You!  Thank You!That worked.  Much Appreciated!Sent from my iPhoneOn Jun 11, 2023, at 8:01 PM, Martijn Verburg ***@***.***> wrote:﻿
@Breezeman69 #785 (comment) might help, but you'll need to report this to the Talend Studio folks.

**Comment by smlambert** [comment]
Did someone raise an issue to the Eclipse IDE team, so a workaround they can address it, so a workaround will not be required?  (I do not see a link to an issue from either of the adoptium-support issues that got raised relating to this apparent regression bug in the IDE).

**Comment by Breezeman69** [comment]
I don’t have a paid subscription for the Talend support folks and I am not aware  of the process for submitting this to them in this case.  Can someone provide details and I will do the needful.Thanks!Sent from my iPhoneOn Jun 12, 2023, at 7:58 AM, Shelley Lambert ***@***.***> wrote:﻿
Did someone raise an issue to the Eclipse IDE team, so a workaround they can address it, so a workaround will not be required?  (I do not see a link to an issue from either of the adoptium-support issues that got raised relating to this apparent regression bug in the IDE).
