### ISSUE TITLE
Strange Memory Leak-like Behavior Using Shenandoah GC & AlwaysPreTouch

### ISSUE THREAD

**Issue by Landon-9999** [adoptium/adoptium-support#804]
## Question

**_Question_**
**Are there any know bugs when using Shenandoah GC and the `AlwaysPreTouch` flag on eclipse-temurin:17?**

Earlier this week I was working on improving the performance on my server and noticed what seemed to be a very slow memory leak. So I gathered and analyzed 2 different heap dumps across a timeframe. Both were identical and within 25MB of difference in heap size. Off-heap usage was also within that same negligible range of difference. The strange part that I noticed was the server slowly using/adding upwards of 1.2GB+ of RAM over a 10 hour period. Same behavior occurs over longer periods as well at a semi-linear rate. And I'm assuming given enough time it would run into an OOM situation.

After discovering that, I was experimenting with my GC flags and I eventually came to the conclusion that `-XX:+AlwaysPreTouch` was the reason for this slow climb in RAM usage when combined with Shenandoah GC specifically. Once I removed that flag the RAM completely stabilized and had no slow increases in RAM over time. And this is rather strange considering that nobody is on the server and it is basically idle during both heap dumps.

Additionally there are no other things contributing to RAM usage. It is only Minecraft in this environment.

Hopefully that's a decent overview of the context to the question here. If you have questions I will do my best to answer them. And I will post links to the heap dumps in question below.

## Context

Context of all this is on a dedicated Java Minecraft server using Shenandoah GC.

**Java version:**
Java Version: `17.0.7, Eclipse Adoptium`
Java VM Version: `OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium`

**Your operating system and platform:** 
I'm on a dedicated host with the following configuration. 
Docker container on `Linux (Ubuntu 22)` using image `eclipse-temurin:17-jdk`
Operating System: `Linux (amd64) version 5.15.0-69-generic`

You can see in this screenshot that the RAM usage is slowly increasing (6AM to 10AM+) despite the heap dumps showing the heap size staying the same.
https://cdn.discordapp.com/attachments/1097554927460552835/1110241709243236442/image.png

Right picture is baseline heap dump. And left is 4 hours after baseline dump.
https://cdn.discordapp.com/attachments/1110251836037939221/1110394013854482503/image.png

**Comment by karianna** [comment]
PreTouch will load in memory aggressively in case it is required.  I would leave it off for client apps such as Minecraft
