### ISSUE TITLE
Strange Memory Leak-like Behavior Using Shenandoah GC & AlwaysPreTouch

### ISSUE THREAD

**Issue by Landon-9999** [adoptium/adoptium-support#805]
## Question

**_Question_**
**Are there any know bugs when using Shenandoah GC and the `AlwaysPreTouch` flag on eclipse-temurin:17?**

Earlier this week I was working on improving the performance on my server and noticed what seemed to be a very slow memory leak. So I gathered and analyzed 2 different heap dumps across a timeframe. Both were identical and within 25MB of difference in heap size. Off-heap usage was also within that same negligible range of difference. The strange part that I noticed was the server slowly using/adding upwards of 1.2GB+ of RAM over a 10 hour period. Same behavior occurs over longer periods as well at a semi-linear rate. And I'm assuming given enough time it would run into an OOM situation.

After discovering that, I was experimenting with my GC flags and I eventually came to the conclusion that `-XX:+AlwaysPreTouch` was the reason for this slow climb in RAM usage when combined with Shenandoah GC specifically. Once I removed that flag the RAM completely stabilized and had no slow increases in RAM over time. And this is rather strange considering that nobody is on the server and it is basically idle during both heap dumps.

Additionally there are no other things contributing to RAM usage. It is only M-C in this environment.

Hopefully that's a decent overview of the context to the question here. If you have questions I will do my best to answer them. And I will post links to the heap dumps in question below.

## Context

Context of all this is on a dedicated Java M-C server using Shenandoah GC.

**Java version:**
Java Version: `17.0.7, Eclipse Adoptium`
Java VM Version: `OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium`

**Your operating system and platform:** 
I'm on a dedicated host with the following configuration. 
Docker container on `Linux (Ubuntu 22)` using image `eclipse-temurin:17-jdk`
Operating System: `Linux (amd64) version 5.15.0-69-generic`

You can see in this screenshot that the RAM usage is slowly increasing (6AM to 10AM+) despite the heap dumps showing the heap size staying the same.
https://cdn.discordapp.com/attachments/1097554927460552835/1110241709243236442/image.png

Right picture is baseline heap dump. And left is 4 hours after baseline dump.
https://cdn.discordapp.com/attachments/1110251836037939221/1110394013854482503/image.png

**Comment by karianna** [comment]
Might be a genuine issue with Shenandoah and Pretouch (aggressively loading in memory so it can meet the pause guarantees.

**Comment by karianna** [comment]
I've passed this on to one of the original Shenandoah authors

**Comment by Landon-9999** [comment]
I did test AlwaysPreTouch with G1GC and didn't notice the same behavior as explained above. I understand G1GC and Shenandoah are very different but I don't personally know enough about either of them to know why there would be a major difference with AlwaysPreTouch.

And earlier I did see a bug that the Shenandoah dev team closed around 3 years ago that sounds similar to what is happening. But again do not know enough myself to know whether or not it's related to this behavior.
https://bugs.openjdk.org/browse/JDK-8245757 

Also I will mention this is a dupe of #804 that got closed. I just didn't want this to get buried because of MC seeing as it doesn't seem to be related to MC as far as I can tell.

But with all that said I should be able to answer any questions about the environment or test different setups if needed.

**Comment by kdnilsen** [comment]
We (AWS Corretto team) will investigate, but today is a holiday in US

**Comment by karianna** [comment]
@kdnilsen Hey Kelvin, nice to hear from you!  LMK if you want this transferred to JBS.

**Comment by shipilev** [comment]
Hi there! On first read, I am puzzled how `AlwaysPreTouch` could contribute to the apparent leak, given that it "only" writes to memory at page granularity and lets the underlying OS memory manager to map the pages early. When you say "RAM", what does that mean exactly? Is this process RSS, Java heap "used", or something else? 

To investigate further, it would be good to have the following:
  1. JVM command line. You can drop MC-related application options, as it would mostly be interesting what JVM options the run is done with.
  2. GC logs during the "leaky" couple of hours, to see whether GC makes weird choices there. Enable with `-Xlog:gc`.
  3. NMT logging to see if there is a memory leak in native structures somewhere. Enable with `-XX:NativeMemoryTracking=summary`, and then do the regular dumps with `jcmd <pid> VM.native_memory`.

**Comment by shipilev** [comment]
> Additionally I was using the `-XX:ShenandoahGuaranteedGCInterval=20000` flag during all of this behavior. And with AlwaysPreTouch disabled the web panel would report the same RAM usage over time. And with it enabled you get the slow increase in RAM usage according to the web panel. Which is very strange considering I did all this testing while the server was "idle" aka nobody joining during the periods of testing.

Hypothesis: so every 20 seconds a GC would happen, regardless what happened in the system, idle or not. `AlwaysPreTouch` would commit the entire region on first allocation, whether application (normal) or GC (evacuation) allocs. If `-Xmx` != `-Xms`, it might so happen than on every GC we take another region and commit it. Which will look like RSS growing until it hits `Xmx`. 

Question: Is `Xmx` == `Xms` in that config? If not, would the "leak" still happen with `-Xms${C}g -Xmx${C}g -XX:+AlwaysPreTouch`, for a reasonable `$C`?

**Comment by Landon-9999** [comment]
I believe it was `Xmx=6192M` & `Xms=512`. Although with the same flags on the JVM for G1GC, I didn't see the 'leaky' behavior using AlwaysPreTouch. Only with Shenandoah for some reason.

> From my understanding the line graph that shows RAM usage over time would be how much RAM the docker container is using. And the 2 pie graphs would be JVM heap dumps I believe. I will try and get another person to clarify that first statement.

This is the dev's response to that.

> It’s process rss, as reported specifically with `docker stats`

1. > GC logs during the "leaky" couple of hours, to see whether GC makes weird choices there. Enable with -Xlog:gc.
2. > NMT logging to see if there is a memory leak in native structures somewhere. Enable with -XX:NativeMemoryTracking=summary, and then do the regular dumps with jcmd <pid> VM.native_memory.

Is there a particular log from above that you would like to see in particular? I could work on getting those generated today if so.

**Comment by Landon-9999** [comment]
So I was able to get the basic GC Logs with the `-Xlog:gc` flag. And unfortunately I can't run jcmd in my environment. Also cannot drop Minecraft given the setup of the server via the host I'm using.

Also I did test out having `Xmx=Xms` with Pretouch and as expected it went ahead and allocated all available memory. And after an hour there was no increase in RAM usage in the docker container. Now I don't know if the leaky behavior is still occurring though since I don't know enough about GC to interpret the logs I generated. But anyways the log for this is below.
[ShenAlwaysPreTouchGCLog-Xmx=Xms.txt](https://github.com/adoptium/adoptium-support/files/11604514/ShenAlwaysPreTouchGCLog-Xmx.Xms.txt)

With Pretouch enabled and the `Xms=512` set to that, the container used 300 more MB of RAM after an hour.
[ShenAlwaysPreTouchGCLog-Xms=512.txt](https://github.com/adoptium/adoptium-support/files/11604519/ShenAlwaysPreTouchGCLog-Xms.512.txt)

And below is No Pretouch with `Xmx=Xms` at 6192M
[ShenNoPreTouchGCLog-Xmx=Xms.txt](https://github.com/adoptium/adoptium-support/files/11604529/ShenNoPreTouchGCLog-Xmx.Xms.txt)

And then No Pretouch with `Xms=512` below
[ShenNoPreTouchGCLog-Xms=512.txt](https://github.com/adoptium/adoptium-support/files/11604539/ShenNoPreTouchGCLog-Xms.512.txt)

Anything else that I might be able to test for you @shipilev? I think your hypothesis could be correct here but again I didn't look at the logs generated and I don't know enough about GC either, so I don't know for certain if that's the case.

**Comment by Landon-9999** [comment]
> I wonder why you run with 20s GC interval? Is it to keep the heap sizes low?

Umm well I was previously dealing with 155MB allocation per second with just one person online with 6GB allocated. Which is absurd for Minecraft in that context lol. Basically I kept running into OOM crashes due to this until I figured out that memory pressure was the problem.  You should be able to see below 3 minute allocation profilers before and after I found a fix for the issue of high memory pressure. So I should in theory be able to raise that guaranteed GC interval by quite a bit since I decreased memory pressure by 10x lol

You should be able to change the label to Bytes Per Second on these. Also looking back at these, the number for Memory (Process) is the total amount currently allocated instead of the actual max allocation.
**Before Fix (1 Player):** https://spark.lucko.me/6d1hJ8GpAp

**After Fix (1 Player):** https://spark.lucko.me/OE3dFezvPI

> It looks that a better option here would be dropping `-XX:+AlwaysPreTouch` and then try with `-XX:ShenandoahGCHeuristics=compact` to battle fragmentation-induced heap growth better.

Yeah I'll just drop PreTouch for now. And currently I'm using experimental mode (=iu) with the flags below. I'll have to try out compact mode and see how that works out in different setups. Along with changing the guaranteed GC interval to something higher.
`-XX:MaxGCPauseMillis=100 -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:ShenandoahUncommitDelay=17000 -XX:ShenandoahGuaranteedGCInterval=20000 -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:-UseBiasedLocking -XX:ShenandoahGCMode=iu`

Also I noticed compact mode isn't mentioned on the docs for openjdk Shenandoah here: 
https://access.redhat.com/documentation/en-us/openjdk/17/html/using_shenandoah_garbage_collector_with_openjdk_17/different-modes-to-run-shenandoah-gc

But anyways thanks for all the analysis on this scenario @shipilev! Glad it's not necessarily a memory leak and more so that PreTouch wasn't being used in the right context.

I'll close this issue/question after the comments stop from either of us or by the end of the day otherwise.
