### ISSUE TITLE
our app is download the temurin jre 11.0.18 tar.gz and getting error while accessing java cannot be opened because develop cannot be verified

### ISSUE THREAD

**Issue by nareshk355** [adoptium/adoptium-support#808]
## Context

Java version: 11.0.18

Your operating system and platform: mac

**Comment by nareshk355** [comment]
<img width="263" alt="Screenshot 2023-05-31 at 10 25 38 AM" src="https://github.com/adoptium/adoptium-support/assets/12135070/b35ff52e-db50-48e3-82ee-bc5f736d3dd8">
attching error screenshot for the reference, we are kind of struck with this issues  and greatly appreciate any help on this.

**Comment by karianna** [comment]
@nareshk355 You need to use the signed PKG / DMG files

**Comment by karianna** [comment]
Also please try 11.0.19

**Comment by gdams** [comment]
What's the app that your downloading?

**Comment by nareshk355** [comment]
@karianna  tried with 11.0.19 version aswell same issue no change.

We have downloaded 11.0.18 version jre binary tar.gz from the temurin site.
https://adoptium.net/temurin/releases/

once after successful download we extracting tar.gz and remaining the root folder “jdk-11.0.18+10-jre” to “jre” and we created jre_mac-11.zip from source jre.

Example: mv jdk-11.0.18+10-jre jre
                 zip -9 -r -y jre_mac-11.zip jre

we are distributing jre_mac-11.zip to internal users by uploading to local maven server.
Errors:
We are seeing the errors “java cannot be opened because developer cannot be verified”

So, after extracting tar.gz and renaming directory to "jre" then we did codesinging the jre and its contents and created zip and then submitted for notarization. Notarization is successful but when we share it we are seeing the same error 
“java cannot be opened because developer cannot be verified”

Any help on this coule be greatly appreciated.

successful Notarized id’s
Request Identifier: a27d80c4-b73a-4a7c-848c-7b6baf5c593c
Request Identifier: 66bc2336-452e-4aea-b0e2-defe669ea02f

Thanks,
Naresh

**Comment by gdams** [comment]
did you staple the notarization ticket to your final package? E.g:

```bash
xcrun stapler staple "Application.app"
```

**Comment by nareshk355** [comment]
@gdams  it is binary file not a .app file to staple.

![image](https://github.com/adoptium/adoptium-support/assets/12135070/fe2b1e6d-878d-4fd0-8c58-f5013ddfd241)

**Comment by nareshk355** [comment]
we are downloading  tar.gz file shown in the screenshot, could you please let us know how did you managed to notarize it.

![image](https://github.com/adoptium/adoptium-support/assets/12135070/09fc51fb-d4e6-425d-b059-34b29b1cb1fd)

**Comment by karianna** [comment]
@nareshk355 Is this still true for 11.0.21?
