### ISSUE TITLE
Do You plan to release a deb Temurin OpenJDK 17 for Ubuntu 23.04?

### ISSUE THREAD

**Issue by aprilzeland** [adoptium/adoptium-support#812]
## Question

Hi, Temurin Team.

There are DEBs for many Ubuntu versions but 23.04 is missing ATM. 
https://packages.adoptium.net/ui/native/deb/dists/
Do You plan to build a DEB of openjdk 17 for 23.04?

Thanks in advance.

**Comment by karianna** [comment]
We do not as we only support the LTS O/S versions.
