### ISSUE TITLE
Do You plan to release a deb Temurin OpenJDK 17 for Ubuntu 23.04?

### ISSUE THREAD

**Issue by aprilzeland** [adoptium/adoptium-support#813]
https://github.com/adoptium/adoptium-support/issues/812
Mr. Martijn Verburg replied that they only support LTS releases.

**But this is not true** as there are packets for many non-LTS releases here https://packages.adoptium.net/ui/native/deb/dists/

May be this is because he works for Microsoft.

So does anybody know if Adoptium team will release a packet for Ubuntu 23.04?

Thanks in advance.

**Comment by karianna** [comment]
Hmm, I may have misspoke, I'll check with the PMC!

**Comment by karianna** [comment]
Our officially supported images are as per: https://adoptium.net/en-GB/supported-platforms/.  Although I understand there might be images that we've released that are not in that matrix, those extra images should not be considered as officially supported.

We're still discussing whether or not to expand that matrix of supported O/S's

**Comment by karianna** [comment]
@aprilzeland see [The Minutes](https://github.com/adoptium/adoptium/blob/main/Meetings/PMC%20Meeting%20Minutes/2023/2023-06-14%20Adoptium%20PMC%20Meeting%20Minutes.pdf) for the discussion on this.  The addition has been approved but I'm not sure when the work will be done.
