### ISSUE TITLE
Can't run Universal Gcode Sender on Raspberry Pi

### ISSUE THREAD

**Issue by mlwash** [adoptium/adoptium-support#817]
## Context

Java version: Java VM: OpenJDK Client VM (25.275-b01 mixed mode linux-aarch32 )

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0xf6196f20, pid=1246, tid=0xf5fb8440
#
# JRE version:  (8.0_275-b01) (build )
# Java VM: OpenJDK Client VM (25.275-b01 mixed mode linux-aarch32 )
# Problematic frame:
# V  [libjvm.so+0x16ef20]  ClassFileParser::parse_constant_pool_entries(int, Thread*)+0x47c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#

---------------  T H R E A D  ---------------

Current thread (0xf5e08000):  JavaThread "Unknown thread" [_thread_in_vm, id=1247, stack(0xf5f69000,0xf5fb9000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 1 (BUS_ADRALN), si_addr: 0xf5e2703f

Registers:
R0=0xf3c04a68
R1=0x00000001
R2=0x000046d1
R3=0xf5e2703f
R4=0x000000a0
R5=0xf5e08000
R6=0xf5fb7808
R7=0x00000224
R8=0x000000a1
R9=0xf6737000
R10=0x0000000d
R11=0xf5fb7444
R12=0x00000005
R13=0xf5fb7348
R14=0xf65fa16c
R15=0xf6196f20

Top of Stack: (sp=0xf5fb7348)
0xf5fb7348:   00000001 00000077 00000000 00000000
0xf5fb7358:   f66c6e30 f5e2b710 00000002 f66c6e5c
0xf5fb7368:   0000000d f5fb738c 00000007 00000000
0xf5fb7378:   8ab1940d f5e0d3b8 f5fb73d4 f7be3f90
0xf5fb7388:   00000000 f5e26d18 f5e2b710 f5e2703f
0xf5fb7398:   f5e42550 00000000 f5e26fe6 f5e2701a
0xf5fb73a8:   00000000 f5e2ff50 f5e0ee78 f6737000
0xf5fb73b8:   00000060 f5fb73f4 00000019 00000010 

Instructions: (pc=0xf6196f20)
0xf6196f00:   00 00 53 e3 6c ff ff 1a b0 30 1b e5 b4 20 1b e5
0xf6196f10:   03 20 42 e0 08 00 52 e3 21 01 00 9a 06 c0 a0 e3
0xf6196f20:   04 40 93 e8 62 08 22 e0 34 10 96 e5 08 30 83 e2
0xf6196f30:   20 04 a0 e1 b0 30 0b e5 ff 0c c0 e3 6e 38 2e e0 

Stack: [0xf5f69000,0xf5fb9000],  sp=0xf5fb7348,  free space=312k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x16ef20]  ClassFileParser::parse_constant_pool_entries(int, Thread*)+0x47c
V  [libjvm.so+0x1738c4]  ClassFileParser::parse_constant_pool(Thread*)+0x12c
V  [libjvm.so+0x174c8c]  ClassFileParser::parseClassFile(Symbol*, ClassLoaderData*, Handle, KlassHandle, GrowableArray<Handle>*, TempNewSymbol&, bool, Thread*)+0x4bc
V  [libjvm.so+0x17c780]  ClassLoader::load_classfile(Symbol*, Thread*)+0x394
V  [libjvm.so+0x5e0f24]  SystemDictionary::load_instance_class(Symbol*, Handle, Thread*)+0x23c
V  [libjvm.so+0x5e1884]  SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*)+0x7d0
V  [libjvm.so+0x5e2d7c]  SystemDictionary::initialize_wk_klasses_until(SystemDictionary::WKID, SystemDictionary::WKID&, Thread*)+0x114
V  [libjvm.so+0x5e36a4]  SystemDictionary::initialize_preloaded_classes(Thread*)+0x48
V  [libjvm.so+0x5e3a94]  SystemDictionary::initialize(Thread*)+0x140
V  [libjvm.so+0x62a01c]  Universe::genesis(Thread*)+0x3c0
V  [libjvm.so+0x62af18]  universe2_init()+0x2c
V  [libjvm.so+0x2d55a0]  init_globals()+0x90
V  [libjvm.so+0x61dc70]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x51c
V  [libjvm.so+0x3ac8e0]  JNI_CreateJavaVM+0x78
C  [libjli.so+0x6818]  JavaMain+0x80
C  [libpthread.so.0+0x6310]  start_thread+0xd0
C  [libc.so.6+0xdbda8]

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )

Other Threads:

=>0xf5e08000 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=1247, stack(0xf5f69000,0xf5fb9000)]

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Classes redefined (0 events):
No events

Internal exceptions (0 events):
No events

Events (3 events):
Event: 0.102 loading class java/lang/Object
Event: 0.154 loading class java/lang/Object done
Event: 0.154 loading class java/lang/String

Dynamic libraries:
00010000-00011000 r-xp 00000000 b3:02 656741                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/bin/java
00020000-00021000 r--p 00000000 b3:02 656741                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/bin/java
00021000-00022000 rw-p 00001000 b3:02 656741                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/bin/java
00b1c000-00b3d000 rw-p 00000000 00:00 0                                  [heap]
e33b0000-e35e3000 rw-p 00000000 00:00 0 
e35e3000-e37b4000 r--s 03c95000 b3:02 656777                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/rt.jar
e37b4000-e39da000 rw-p 00000000 00:00 0 
e39da000-e3c00000 ---p 00000000 00:00 0 
e3c00000-e5150000 rw-p 00000000 00:00 0 
e5150000-e9150000 ---p 00000000 00:00 0 
e9150000-ebc00000 rw-p 00000000 00:00 0 
ebc00000-f3c00000 ---p 00000000 00:00 0 
f3c04000-f3c75000 rw-p 00000000 00:00 0 
f3c75000-f3cb5000 ---p 00000000 00:00 0 
f3cb5000-f3cc0000 rw-p 00000000 00:00 0 
f3cc0000-f3cdf000 ---p 00000000 00:00 0 
f3cdf000-f3cf5000 rw-p 00000000 00:00 0 
f3cf5000-f3d35000 ---p 00000000 00:00 0 
f3d35000-f3d39000 rw-p 00000000 00:00 0 
f3d39000-f3db6000 ---p 00000000 00:00 0 
f3db6000-f3e6e000 rwxp 00000000 00:00 0 
f3e6e000-f5db6000 ---p 00000000 00:00 0 
f5db6000-f5dce000 r-xp 00000000 b3:02 656879                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libzip.so
f5dce000-f5ddd000 ---p 00018000 b3:02 656879                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libzip.so
f5ddd000-f5dde000 r--p 00017000 b3:02 656879                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libzip.so
f5dde000-f5ddf000 rw-p 00018000 b3:02 656879                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libzip.so
f5ddf000-f5de9000 r-xp 00000000 b3:02 406533                             /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so
f5de9000-f5df8000 ---p 0000a000 b3:02 406533                             /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so
f5df8000-f5df9000 r--p 00009000 b3:02 406533                             /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so
f5df9000-f5dfa000 rw-p 0000a000 b3:02 406533                             /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so
f5dfa000-f5e00000 rw-p 00000000 00:00 0 
f5e00000-f5e6c000 rw-p 00000000 00:00 0 
f5e6c000-f5f00000 ---p 00000000 00:00 0 
f5f02000-f5f21000 r-xp 00000000 b3:02 656855                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libjava.so
f5f21000-f5f30000 ---p 0001f000 b3:02 656855                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libjava.so
f5f30000-f5f31000 r--p 0001e000 b3:02 656855                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libjava.so
f5f31000-f5f32000 rw-p 0001f000 b3:02 656855                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libjava.so
f5f32000-f5f3f000 r-xp 00000000 b3:02 656869                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libverify.so
f5f3f000-f5f4e000 ---p 0000d000 b3:02 656869                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libverify.so
f5f4e000-f5f4f000 r--p 0000c000 b3:02 656869                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libverify.so
f5f4f000-f5f50000 rw-p 0000d000 b3:02 656869                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/libverify.so
f5f50000-f5f56000 r-xp 00000000 b3:02 406658                             /usr/lib/arm-linux-gnueabihf/librt-2.31.so
f5f56000-f5f66000 ---p 00006000 b3:02 406658                             /usr/lib/arm-linux-gnueabihf/librt-2.31.so
f5f66000-f5f67000 r--p 00006000 b3:02 406658                             /usr/lib/arm-linux-gnueabihf/librt-2.31.so
f5f67000-f5f68000 rw-p 00007000 b3:02 406658                             /usr/lib/arm-linux-gnueabihf/librt-2.31.so
f5f68000-f5f69000 ---p 00000000 00:00 0 
f5f69000-f5f6c000 ---p 00000000 00:00 0 
f5f6c000-f5fb9000 rw-p 00000000 00:00 0 
f5fb9000-f6017000 r-xp 00000000 b3:02 406444                             /usr/lib/arm-linux-gnueabihf/libm-2.31.so
f6017000-f6026000 ---p 0005e000 b3:02 406444                             /usr/lib/arm-linux-gnueabihf/libm-2.31.so
f6026000-f6027000 r--p 0005d000 b3:02 406444                             /usr/lib/arm-linux-gnueabihf/libm-2.31.so
f6027000-f6028000 rw-p 0005e000 b3:02 406444                             /usr/lib/arm-linux-gnueabihf/libm-2.31.so
f6028000-f6716000 r-xp 00000000 b3:02 656847                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/client/libjvm.so
f6716000-f6726000 ---p 006ee000 b3:02 656847                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/client/libjvm.so
f6726000-f6737000 r--p 006ee000 b3:02 656847                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/client/libjvm.so
f6737000-f674f000 rw-p 006ff000 b3:02 656847                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/client/libjvm.so
f674f000-f7b6e000 rw-p 00000000 00:00 0 
f7b6e000-f7cac000 r-xp 00000000 b3:02 406109                             /usr/lib/arm-linux-gnueabihf/libc-2.31.so
f7cac000-f7cbc000 ---p 0013e000 b3:02 406109                             /usr/lib/arm-linux-gnueabihf/libc-2.31.so
f7cbc000-f7cbe000 r--p 0013e000 b3:02 406109                             /usr/lib/arm-linux-gnueabihf/libc-2.31.so
f7cbe000-f7cbf000 rw-p 00140000 b3:02 406109                             /usr/lib/arm-linux-gnueabihf/libc-2.31.so
f7cbf000-f7cc2000 rw-p 00000000 00:00 0 
f7cc2000-f7cc5000 r-xp 00000000 b3:02 406179                             /usr/lib/arm-linux-gnueabihf/libdl-2.31.so
f7cc5000-f7cd4000 ---p 00003000 b3:02 406179                             /usr/lib/arm-linux-gnueabihf/libdl-2.31.so
f7cd4000-f7cd5000 r--p 00002000 b3:02 406179                             /usr/lib/arm-linux-gnueabihf/libdl-2.31.so
f7cd5000-f7cd6000 rw-p 00003000 b3:02 406179                             /usr/lib/arm-linux-gnueabihf/libdl-2.31.so
f7cd6000-f7cec000 r-xp 00000000 b3:02 656873                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/jli/libjli.so
f7cec000-f7cfb000 ---p 00016000 b3:02 656873                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/jli/libjli.so
f7cfb000-f7cfc000 r--p 00015000 b3:02 656873                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/jli/libjli.so
f7cfc000-f7cfd000 rw-p 00016000 b3:02 656873                             /home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre/lib/aarch32/jli/libjli.so
f7cfd000-f7d15000 r-xp 00000000 b3:02 406626                             /usr/lib/arm-linux-gnueabihf/libpthread-2.31.so
f7d15000-f7d25000 ---p 00018000 b3:02 406626                             /usr/lib/arm-linux-gnueabihf/libpthread-2.31.so
f7d25000-f7d26000 r--p 00018000 b3:02 406626                             /usr/lib/arm-linux-gnueabihf/libpthread-2.31.so
f7d26000-f7d27000 rw-p 00019000 b3:02 406626                             /usr/lib/arm-linux-gnueabihf/libpthread-2.31.so
f7d27000-f7d29000 rw-p 00000000 00:00 0 
f7d29000-f7d30000 r-xp 00000000 b3:02 406051                             /usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0
f7d30000-f7d3f000 ---p 00007000 b3:02 406051                             /usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0
f7d3f000-f7d40000 r--p 00006000 b3:02 406051                             /usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0
f7d40000-f7d41000 rw-p 00007000 b3:02 406051                             /usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0
f7d41000-f7d42000 rw-p 00000000 00:00 0 
f7d57000-f7d5b000 r-xp 00000000 b3:02 406041                             /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
f7d5b000-f7d6a000 ---p 00004000 b3:02 406041                             /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
f7d6a000-f7d6b000 r--p 00003000 b3:02 406041                             /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
f7d6b000-f7d6c000 rw-p 00004000 b3:02 406041                             /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
f7d6c000-f7d8e000 r-xp 00000000 b3:02 405879                             /usr/lib/arm-linux-gnueabihf/ld-2.31.so
f7d90000-f7d98000 rw-s 00000000 b3:02 654155                             /tmp/hsperfdata_pi/1246
f7d98000-f7d99000 r--p 00000000 00:00 0 
f7d99000-f7d9d000 rw-p 00000000 00:00 0 
f7d9d000-f7d9e000 r-xp 00000000 00:00 0                                  [sigpage]
f7d9e000-f7d9f000 r--p 00022000 b3:02 405879                             /usr/lib/arm-linux-gnueabihf/ld-2.31.so
f7d9f000-f7da0000 rw-p 00023000 b3:02 405879                             /usr/lib/arm-linux-gnueabihf/ld-2.31.so
ff934000-ff955000 rw-p 00000000 00:00 0                                  [stack]
ffff0000-ffff1000 r-xp 00000000 00:00 0                                  [vectors]

VM Arguments:
jvm_args: -Djdk.home=/home/pi/Downloads/ugsplatform-pi/jdk/jdk8u275-b01-jre -Dnetbeans.dirs=/home/pi/Downloads/ugsplatform-pi/ide:/home/pi/Downloads/ugsplatform-pi/bin:/home/pi/Downloads/ugsplatform-pi/platform:/home/pi/Downloads/ugsplatform-pi/ugsplatform:/home/pi/Downloads/ugsplatform-pi/java:/home/pi/Downloads/ugsplatform-pi/extra:/home/pi/Downloads/ugsplatform-pi/etc: -Dnetbeans.home=/home/pi/Downloads/ugsplatform-pi/platform -Xms64m -Xverify:none -Dsun.java2d.noddraw=true -Dsun.awt.noerasebackground=true -Dnetbeans.indexing.noFileRefresh=true -Dorg.openide.text.big.file.size=20 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/pi/.ugsplatform/var/log/heapdump.hprof -Djava.security.manager=allow 
java_command: org.netbeans.Main --cachedir /home/pi/.cache/ugsplatform/var/cache --userdir /home/pi/.ugsplatform --branding ugsplatform
java_class_path (initial): /home/pi/Downloads/ugsplatform-pi/platform/lib/boot.jar:/home/pi/Downloads/ugsplatform-pi/platform/lib/org-openide-modules.jar:/home/pi/Downloads/ugsplatform-pi/platform/lib/org-openide-util.jar:/home/pi/Downloads/ugsplatform-pi/platform/lib/org-openide-util-lookup.jar:/home/pi/Downloads/ugsplatform-pi/platform/lib/org-openide-util-ui.jar
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
SHELL=/bin/bash
DISPLAY=:0

Signal Handlers:
SIGSEGV: [libjvm.so+0x66162c], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGBUS: [libjvm.so+0x66162c], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGFPE: [libjvm.so+0x5119f4], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGPIPE: [libjvm.so+0x5119f4], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGXFSZ: [libjvm.so+0x5119f4], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGILL: [libjvm.so+0x5119f4], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGUSR1: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGUSR2: [libjvm.so+0x511854], sa_mask[0]=00000000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
SIGHUP: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGINT: SIG_IGN, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGTERM: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGQUIT: SIG_IGN, sa_mask[0]=00000000000000000000000000000000, sa_flags=none

---------------  S Y S T E M  ---------------

OS:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

uname:Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64
libc:glibc 2.31 NPTL 2.31 
rlimit: STACK 8192k, CORE 0k, NPROC 13113, NOFILE 1048576, AS infinity
load average:0.80 0.27 0.10

/proc/meminfo:
MemTotal:        3885396 kB
MemFree:         3347640 kB
MemAvailable:    3563376 kB
Buffers:           28584 kB
Cached:           285048 kB
SwapCached:            0 kB
Active:           314876 kB
Inactive:          67128 kB
Active(anon):     122236 kB
Inactive(anon):     1464 kB
Active(file):     192640 kB
Inactive(file):    65664 kB
Unevictable:       51000 kB
Mlocked:              16 kB
SwapTotal:        102396 kB
SwapFree:         102396 kB
Zswap:                 0 kB
Zswapped:              0 kB
Dirty:                60 kB
Writeback:             0 kB
AnonPages:        119576 kB
Mapped:           129404 kB
Shmem:             55328 kB
KReclaimable:      28360 kB
Slab:              55516 kB
SReclaimable:      28360 kB
SUnreclaim:        27156 kB
KernelStack:        4256 kB
PageTables:         4908 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2045092 kB
Committed_AS:    1180524 kB
VmallocTotal:   259653632 kB
VmallocUsed:       11380 kB
VmallocChunk:          0 kB
Percpu:              704 kB
CmaTotal:         524288 kB
CmaFree:          505160 kB

CPU:total 4 (initial active 4) 0x41:0x0:0xd08:3

/proc/cpuinfo:
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: c03114
Serial		: 10000000a5ac3c50
Model		: Raspberry Pi 4 Model B Rev 1.4

Memory: 4k page, physical 3885396k(3347640k free), swap 102396k(102396k free)

vm_info: OpenJDK Client VM (25.275-b01) for linux-aarch32 JRE (1.8.0_275-b01), built on Nov 12 2020 01:02:53 by "jenkins" with gcc 7.5.0

time: Wed Jun  7 13:37:43 2023
timezone: EDT
elapsed time: 0.222760 seconds (0d 0h 0m 0s)

Raspberry Pi OS, 32 bit full version

**Comment by maxcel2** [comment]
I'm having the same problem

**Comment by karianna** [comment]
please try 1.8.0_362 and report back :-)

**Comment by mlwash** [comment]
Thank you your suggestion.  

I located 1.8.0_362 on the OpenJDK and downloaded the .tar file (https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/8u362-b09/openlogic-openjdk-jre-8u362-b09-linux-x32.tar.gz).  But, I can't figure out how to install this version on my Raspberry Pi 4.  After unzipping the file, there is no .tar file that I can locate.  

Can you recommend where I can find the process to install this on my Pi?

**Comment by maxcel2** [comment]
I cannot find the file that karianna is referring to. The file 8u362-b09-linux-x32.tar.gz  appears to be for x86 architectures, Raspberry-Pi's are ARM architecture. I cannot find an OpenJDK for Pi.

**Comment by mlwash** [comment]
maxcel2 -- I reverted back to the legacy version of PiOS using RaspberryPi Imager, and GCS open, which is a relief.  I now need to test to see if it is working with my CNC.

**Comment by maxcel2** [comment]
karianna-- downloaded the file that mlwash suggested and inserted into the ugsplatform-pi/jdk/ directory, but UGS reported that it could not find Java.

mlwash-- I've found a very good how-to for UGS here:
[https://cebess.wordpress.com/2019/10/14/installing-universal-g-code-sender-on-the-raspberry-pi/](url)
I followed it through with the exception that I didn't need VNC, so left it out of the startup file.
I haven't coupled it up to GRBL yet, but the panel is up and running.

**Comment by karianna** [comment]
Apologies - the build we support is at: https://adoptium.net/en-GB/temurin/releases/?version=8 should be a 1.8.0_372 if you filter by Linux arm

**Comment by maxcel2** [comment]
I have downloaded 1.8.0_372 (jdk8u372-b07-aarch32-20230426) from your link above, and used it to replace the existing folder in the ugsplatform-pi/jdk. When I run ./ugsplatform from the bin folder, I get the error 'Cannot find java'.

**Comment by karianna** [comment]
check `which java`, `JAVA_HOME` and `PATH`

**Comment by maxcel2** [comment]
dave@raspberrypi:~ $ $PATH
-bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games: No such file or directory
dave@raspberrypi:~ $ $JAVA_HOME
dave@raspberrypi:~ $ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-1+rpi1-b07)
OpenJDK Client VM (build 25.312-b07, mixed mode)
dave@raspberrypi:~ $

**Comment by maxcel2** [comment]
karianna-- Perhaps you could tell me how I should install the 1.8.0.372 file so that UGS can see it.

**Comment by karianna** [comment]
export JAVA_HOME=<path to newly installed java> typically does the trick

I'd look at `which java` as well since you seem to be picking up a 1.8.0_312 from somewhere

**Comment by karianna** [comment]
You'll have to read the UGS documentation or contact their support and find the script where they reference the Java that they are using and change it from internal to external.

**Comment by gregq18** [comment]
I solved the problem by downloading pi-ugs-platform-app-2.0.20.tar.gz, unzipping.  
Installing sudo apt install openjdk-8-jdk, latest version of which in the repository is 1.8.0_312 required for UGS
Editing /home/yourdir/ugsplatform-pi/etc/ugsplatform.conf and changing line jdkhome="jdk/jdk8u275-b01-jre" to jdkhome="/usr/lib/jvm/java-8-openjdk-armhf/jre"
Using Preferences/Main Menu Editor I added a new Menu Item and Name: UGS and Command: Browsed to /home/yourdir/ugsplatform-pi/bin/ugsplatform and pressed OK OK. If you right click the new UGS Menu Item you can add it to your desk top.

**Comment by Seb-Leb** [comment]
Thank you, that worked for me!
