### ISSUE TITLE
I don't know if it's a bug or a configuration error

### ISSUE THREAD

**Issue by agitechcr** [adoptium/adoptium-support#818]
## Question

I don't know if it's a bug in the JRE or if it's some Tomcat configuration.

Should I add some extra configuration at the level of the default tomcat?

Note this is the first time I see this error. And that causes a complete fall of the demon.

----
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007efdb10523b0, pid=21085, tid=0x00007efd71def700
#
# JRE version: OpenJDK Runtime Environment (8.0_372-b07) (build 1.8.0_372-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# v  ~StubRoutines::jlong_disjoint_arraycopy
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  T H R E A D  ---------------

Current thread (0x00007efd8d692800):  JavaThread "ajp-nio-8009-exec-81" daemon [_thread_in_Java, id=11082, stack(0x00007efd71bef000,0x00007efd71df0000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 2 (BUS_ADRERR), si_addr: 0x00007efda8018000

Registers:
RAX=0x00007efda801a000, RBX=0x0000000000000000, RCX=0x00000000a4f860d0, RDX=0xfffffffffffffc04
RSP=0x00007efd71deddd0, RBP=0x00007efd71deddd0, RSI=0x00000000a4f840d8, RDI=0x00007efda8019ff8
R8 =0x00000000a495bd80, R9 =0x00007efda8018000, R10=0x00007efdb1052940, R11=0x0000000000000010
R12=0x0000000000000000, R13=0x00000000a4f840c8, R14=0x0000000000002000, R15=0x00007efd8d692800
RIP=0x00007efdb10523b0, EFLAGS=0x0000000000010282, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e
----

## Context

Java version:

openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)

Your operating system and platform:

Ubuntu 18.04.6 LTS x86_64
Tocmat 8.5.39-1ubuntu1~18.04.3

**Comment by karianna** [comment]
please upgrade to Tomcat 8.5.89 and reopen this if you get another crash
