### ISSUE TITLE
Got a different Checksum value.

### ISSUE THREAD

**Issue by easoftwareGit** [adoptium/adoptium-support#821]
## Context

Java version: 8 Update 371 (build 1.8.0_371-b11)

Windows 10 Home 
Version 22H2 
OS build 19045.3031 
Experience Windows Feature Experience Pack 1000.19041.1000.0

**Comment by jerboaa** [comment]
What's the question? AFAIK, there is no 8u371-b11 for OpenJDK (Temurin). There is only 8u372-b07. See https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u372-b07
