### ISSUE TITLE
Deb repository not signed with key at https://packages.adoptium.net/artifactory/api/gpg/key/public

### ISSUE THREAD

**Issue by hheg** [adoptium/adoptium-support#823]
### Please provide a brief summary of the bug

Following the guide on https://adoptium.net/installation/linux/ results in that the repository can't be verified

### Please provide steps to reproduce where possible

Follow the guide on https://adoptium.net/installation/linux/ 

### Expected Results

sudo apt update should succeed.

### Actual Results

> sudo apt update
Hit:1 http://se.archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://se.archive.ubuntu.com/ubuntu lunar-updates InRelease                                
Hit:3 http://se.archive.ubuntu.com/ubuntu lunar-backports InRelease                                                    
Hit:4 http://se.archive.ubuntu.com/ubuntu lunar-security InRelease                                                                    
Hit:5 https://download.sublimetext.com apt/stable/ InRelease                                                                          
Get:6 https://packages.adoptium.net/artifactory/deb jammy InRelease [6,632 B]
Err:6 https://packages.adoptium.net/artifactory/deb jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 843C48A565F8F04B
Reading package lists... Done
W: GPG error: https://packages.adoptium.net/artifactory/deb jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 843C48A565F8F04B
E: The repository 'https://packages.adoptium.net/artifactory/deb jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Output of keys:
> sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2021-11-16 [SC]
      3B04 D753 C905 0D9A 5D34  3F39 843C 48A5 65F8 F04B
uid           [ unknown] Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>
sub   rsa2048 2021-11-16 [E]

### What Java Version are you using?

No version

### What is your operating system and platform?

Ubuntu 23.04

### How did you install Java?

I'm trying to

**Comment by hheg** [comment]
gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3B04D753C9050D9A5D343F39843C48A565F8F04B
gpg: key 843C48A565F8F04B: public key "Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Solved it.

**Comment by kytay** [comment]
Hi @hheg 

Mind to share what is causing this error?
I am trying to build a docker image with temurin 17 installed.

Uncomfortable to run the command 
`gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3B04D753C9050D9A5D343F39843C48A565F8F04B`
so need some help to understand this better.

The following is my dockerfile
```bash
ARG PARAM_UBUNTU_VERSION=latest
ARG PARAM_TZ=UTC

FROM ubuntu:${PARAM_UBUNTU_VERSION}

# Environment for timezone setup
ENV TZ=${PARAM_TZ}

RUN echo -e '#!/bin/bash \nexit 0' > /usr/sbin/policy-rc.d \
&& apt-get update \
&& apt-get install -y --no-install-recommends \
curl  ca-certificates apt-transport-https gnupg lsb-release tzdata zip \
&& apt-get upgrade -y \
&& apt-get autoremove -y \
&& apt-get purge -y --auto-remove \
&& rm -rf /var/lib/apt/lists/*

# TimeZone Configuration
# 4       - setup noninteractive timezone
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
echo $TZ /etc/timezone && \
dpkg-reconfigure --frontend noninteractive tzdata

# Setup and Download temurin-17-jdk:
RUN mkdir -p /etc/apt/keyrings \
&& curl https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --import \
&& echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list \
&& apt-get update \
&& apt-get install temurin-17-jdk

CMD ["/bin/bash"]
```
