### ISSUE TITLE
Runescape keeps crashing and the log said to report it here

### ISSUE THREAD

**Issue by rascopog** [adoptium/adoptium-support#825]
### Please provide a brief summary of the bug

Runescape and a lot of my other games keep crashing while im playing for months now. Today I reinstalled windows and it is still happening. I attached some of the crash logs. Any help would be appreciated 
[jvm_crash_pid_3908.log](https://github.com/adoptium/adoptium-support/files/11778140/jvm_crash_pid_3908.log)
[jvm_crash_pid_14932.log](https://github.com/adoptium/adoptium-support/files/11778142/jvm_crash_pid_14932.log)

### Expected Results

Not to crash

### Actual Results

Crash

### What Java Version are you using?

java 8 update 371

### What is your operating system and platform?

Runelite, Windows 10

### How did you install Java?

From the website

### Did it work before?

```Shell
No
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000025ce6e4c28e, pid=3908, tid=5616
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.19+7 (11.0.19+7) (build 11.0.19+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (11.0.19+7, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# J 14686 c2 jd.ao(ZLjd;[B)Ljd; (473 bytes) @ 0x0000025ce6e4c28e [0x0000025ce6e4bc60+0x000000000000062e]
#
```

**Comment by karianna** [comment]
@rascopog - Are your graphics drivers and Runescape fully up to date?  I recommend posting this crash to them as it's likely a native library causing it that's under their control.
