### ISSUE TITLE
SIGSEGV 0xb

### ISSUE THREAD

**Issue by optionalc** [adoptium/adoptium-support#832]
### Please provide a brief summary of the bug

I'm using Eclipse on daily basis. So when I do something like autocomplete or copy pasting it randomly crashes.

### Please provide steps to reproduce where possible

1. Use Eclipse
2. Import some random Maven project
3. Do anything until crash happens

### Expected Results

No crashes

### Actual Results

This crash

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.7+7

### What is your operating system and platform?

Ubuntu 22.04.2 LTS (x64) - Wayland

### How did you install Java?

Throughout Eclipse installation wizzard.

### Did it work before?

```Shell
Didn't test.
```

### Did you test with the latest update version?

```Shell
Yes.
```

### Did you test with other Java versions?

```Shell
Nope.
```

### Relevant log output

```Shell
Log is here:
https://pastebin.com/fsKSLWP6
```

**Comment by karianna** [comment]
Please update your GTK version, graphics drivers and update to the latest Eclipse IDE version (mostly likely fix).

**Comment by optionalc** [comment]
There is a catch. Switching to XORG x11 display system apparently works. Also updated everything in previous comment.
