### ISSUE TITLE
after ruuning spring tool suite 4  automatically closes & one error page generated 

### ISSUE THREAD

**Issue by SushilUniverse** [adoptium/adoptium-support#837]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f37488e93c4, pid=633451, tid=633452
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE/core.633451)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Xms256m -Xmx2048m --illegal-access=permit --add-modules=ALL-SYSTEM /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE/SpringToolSuite4 -name SpringToolSuite4 --launcher.library /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024/eclipse_11801.so -startup /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --launcher.overrideVmargs -exitdata 28014 -product org.springframework.boot.ide.branding.sts4 -vm /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.7.v20230425-1502/jre/bin/java -vmargs --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Dosgi.requiredJavaVersion=17 -Dosgi.dataAreaRequiresExplicitInit=true -Dsun.java.command=SpringToolSuite4 -Xms256m -Xmx2048m --illegal-access=permit --add-modules=ALL-SYSTEM -jar /home/sushil/Downloads/spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64/sts-4.19.0.RELEASE//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar

Host: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz, 4 cores, 3G, Ubuntu 22.04.2 LTS
Time: Fri Jul  7 17:30:43 2023 IST elapsed time: 251.697353 seconds (0d 0h 4m 11s)

---------------  T H R E A D  ---------------

Current thread (0x00007f3770026f90):  JavaThread "main" [_thread_in_native, id=633452, stack(0x00007f3775019000,0x00007f3775119000)]

Stack: [0x00007f3775019000,0x00007f3775119000],  sp=0x00007f3775115eb8,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 8951  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(J)V (0 bytes) @ 0x00007f3765776861 [0x00007f3765776820+0x0000000000000041]
j  org.eclipse.swt.widgets.Display.eventProc(JJ)J+196
v  ~StubRoutines::call_stub
J 9018  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Z)Z (0 bytes) @ 0x00007f376577ab61 [0x00007f376577ab20+0x0000000000000041]
J 16716 c2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (88 bytes) @ 0x00007f3765b6cb84 [0x00007f3765b6caa0+0x00000000000000e4]
j  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run()V+564
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(Lorg/eclipse/e4/ui/model/application/MApplicationElement;Lorg/eclipse/e4/core/contexts/IEclipseContext;)Ljava/lang/Object;+57
j  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(Lorg/eclipse/e4/ui/model/application/MApplicationElement;)V+20
j  org.eclipse.ui.internal.Workbench.lambda$3(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;[I)V+393
j  org.eclipse.ui.internal.Workbench$$Lambda$183+0x000000010028b858.run()V+12
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+16
j  org.eclipse.ui.PlatformUI.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+2
j  org.eclipse.ui.internal.ide.application.IDEApplication.start(Lorg/eclipse/equinox/app/IApplicationContext;)Ljava/lang/Object;+113
j  org.eclipse.equinox.internal.app.EclipseAppHandle.run(Ljava/lang/Object;)Ljava/lang/Object;+138
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ljava/lang/Object;)Ljava/lang/Object;+85
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Ljava/lang/Object;)Ljava/lang/Object;+79
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run(Ljava/lang/Object;)Ljava/lang/Object;+99
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run([Ljava/lang/String;Ljava/lang/Runnable;)Ljava/lang/Object;+132
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.7
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.7
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.7
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.7
j  org.eclipse.equinox.launcher.Main.invokeFramework([Ljava/lang/String;[Ljava/net/URL;)V+201
j  org.eclipse.equinox.launcher.Main.basicRun([Ljava/lang/String;)V+159
j  org.eclipse.equinox.launcher.Main.run([Ljava/lang/String;)I+4
j  org.eclipse.equinox.launcher.Main.main([Ljava/lang/String;)V+10
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

### Expected Results

provide solution to solve this error

### Actual Results

after running spring boot suite 4 automatically closes & generate one error page in spring boot suite 4 folder

### What Java Version are you using?

openjdk version "11.0.19" 2023-04-18 OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1) OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

### What is your operating system and platform?

ubantu 22.04 on arm64

### How did you install Java?

using terminal commands

### Did it work before?

```Shell
it worked ,but right know not working
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by karianna** [comment]
We've seen a number of these issues recently in older builds of the Eclipse IDE.  See if upgrading to the very latest version resolves this.
