### ISSUE TITLE
Java Swing crashed 

### ISSUE THREAD

**Issue by CodesOfScappy** [adoptium/adoptium-support#839]
### Please provide a brief summary of the bug

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffae6f6b796, pid=17780, tid=7856

### Expected Results

normal terminated on close

### Actual Results

When closing the application, a serious error occurs in Runtime

### What Java Version are you using?

OpenJDK 64-Bit Server VM Temurin-17.0.6+10

### What is your operating system and platform?

Windows 11 Java 17.0.6

### Relevant log output

```Shell
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffae6f6b796, pid=17780, tid=7856

 Problematic frame:
 C  [glass.dll+0x1b796]

Command Line: --module-path=F:\javafx-sdk-20.0.1\lib --add-modules=javafx.controls,javafx.fxml -Dfile.encoding=UTF-8 -XX:+ShowCodeDetailsInExceptionMessages game.HangmanFX
```

**Comment by karianna** [comment]
@CodesOfScappy you need to use Java 20.0.1 to work with JavaFX 20.0.1
