### ISSUE TITLE
Witelisting ? like deployment Rule set  possible with Temurin

### ISSUE THREAD

**Issue by 5l4p** [adoptium/adoptium-support#841]
## is it possible to control with Temurin wich java apps are allowed to start/run (whitelisting)?
wanting to comletely get rid of any ORACLE JRE or JDKs on my system but need to keep the possibilities offerd from  https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/deployment_rules.html

## Context
i could not  find any Documentation on that matter thus created this account to investigate closer to the authors

Java version:
the Idea is to use the current Temurin adoptium LTS Versions as stated here https://adoptium.net/de/support/
at the Moment Java 17 (LTS)

Your Operating System and Platform: 
Win10 x64 19044 21h2
and soon  Win11 x64

**Comment by karianna** [comment]
@5l4p This is not supported.  Please see OpenWebstart as an alternative.

**Comment by 5l4p** [comment]
thank u 4 the quick rply
and the referal to the [OWS](https://openwebstart.com/) project
sadly on their [Feature list](https://openwebstart.com/feature-table/) that Rule Set possibility is still stated as:
 **Unscheduled Feature** 
 
 and a [forum rply from 2021](https://board.karakun.com/viewtopic.php?p=9119&hilit=rule+set#p9119) implies that it will not Change
