### ISSUE TITLE
JVM Crash on [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4  OpenJDK 17.0.6

### ISSUE THREAD

**Issue by gmshiot** [adoptium/adoptium-support#842]
### Please provide a brief summary of the bug

---------------  S U M M A R Y ------------

Command Line: -Dosgi.requiredJavaVersion=17 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true -Xms256m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -javaagent:/opt/eclipse23/lombok.jar /opt/eclipse23//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -os linux -ws gtk -arch x86_64 -showsplash /opt/eclipse23//plugins/org.eclipse.epp.package.common_4.27.0.20230309-1200/splash.bmp -launcher /opt/eclipse23/eclipse -name Eclipse --launcher.library /opt/eclipse23//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024/eclipse_11801.so -startup /opt/eclipse23//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --launcher.appendVmargs -exitdata a -product org.eclipse.epp.package.jee.product -vm /opt/eclipse23//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.6.v20230204-1729/jre/bin/java -vmargs -Dosgi.requiredJavaVersion=17 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true -Dsun.java.command=Eclipse -Xms256m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -javaagent:/opt/eclipse23/lombok.jar -jar /opt/eclipse23//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar

Host: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2 cores, 4G, Ubuntu 22.04.2 LTS
Time: Thu Jul 13 15:13:47 2023 CST elapsed time: 1755.588762 seconds (0d 0h 29m 15s)

---------------  T H R E A D  ---------------

Current thread (0x00007fbe440282c0):  JavaThread "main" [_thread_in_native, id=3177, stack(0x00007fbe4ae19000,0x00007fbe4af19000)]

Stack: [0x00007fbe4ae19000,0x00007fbe4af19000],  sp=0x00007fbe4af15f78,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcairo.so.2+0x643c4]  cairo_region_num_rectangles+0x4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 11302  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(J)V (0 bytes) @ 0x00007fbe3966ffe1 [0x00007fbe3966ffa0+0x0000000000000041]
J 37860 c2 org.eclipse.swt.widgets.Display.eventProc(JJ)J (212 bytes) @ 0x00007fbe3a8e7728 [0x00007fbe3a8e7680+0x00000000000000a8]
v  ~StubRoutines::call_stub
J 12114  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Z)Z (0 bytes) @ 0x00007fbe396a9ae1 [0x00007fbe396a9aa0+0x0000000000000041]
J 42035 c2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (88 bytes) @ 0x00007fbe3aa7de24 [0x00007fbe3aa7dd40+0x00000000000000e4]
J 39218% c2 org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run()V (690 bytes) @ 0x00007fbe3a9fc354 [0x00007fbe3a9fc1a0+0x00000000000001b4]
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(Lorg/eclipse/e4/ui/model/application/MApplicationElement;Lorg/eclipse/e4/core/contexts/IEclipseContext;)Ljava/lang/Object;+57
j  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(Lorg/eclipse/e4/ui/model/application/MApplicationElement;)V+20
j  org.eclipse.ui.internal.Workbench.lambda$3(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;[I)V+393
j  org.eclipse.ui.internal.Workbench$$Lambda$188+0x00000001002a3be8.run()V+12
j  org.eclipse.core.databinding.observable.Realm.runWithDefault(Lorg/eclipse/core/databinding/observable/Realm;Ljava/lang/Runnable;)V+12
j  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+16
j  org.eclipse.ui.PlatformUI.createAndRunWorkbench(Lorg/eclipse/swt/widgets/Display;Lorg/eclipse/ui/application/WorkbenchAdvisor;)I+2
j  org.eclipse.ui.internal.ide.application.IDEApplication.start(Lorg/eclipse/equinox/app/IApplicationContext;)Ljava/lang/Object;+113
j  org.eclipse.equinox.internal.app.EclipseAppHandle.run(Ljava/lang/Object;)Ljava/lang/Object;+138
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ljava/lang/Object;)Ljava/lang/Object;+85
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Ljava/lang/Object;)Ljava/lang/Object;+79
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run(Ljava/lang/Object;)Ljava/lang/Object;+99
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run([Ljava/lang/String;Ljava/lang/Runnable;)Ljava/lang/Object;+132
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.6
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.6
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.6
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.6
j  org.eclipse.equinox.launcher.Main.invokeFramework([Ljava/lang/String;[Ljava/net/URL;)V+201
j  org.eclipse.equinox.launcher.Main.basicRun([Ljava/lang/String;)V+159
j  org.eclipse.equinox.launcher.Main.run([Ljava/lang/String;)I+4
j  org.eclipse.equinox.launcher.Main.main([Ljava/lang/String;)V+10
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

Register to memory mapping:

RAX=0x00007fbd540a0ef0 points into unknown readable memory: 0x00007fbe46e94330 | 30 43 e9 46 be 7f 00 00
RBX=0x0 is NULL
RCX=0x0000000000000001 is an unknown value
RDX=0x0000000000000002 is an unknown value
RSP=0x00007fbe4af15f78 is pointing into the stack for thread: 0x00007fbe440282c0
RBP=0x00007fbe444800e0 points into unknown readable memory: 0x00007fbe4447f320 | 20 f3 47 44 be 7f 00 00
RSI=0x00007fbe4447ecc0 points into unknown readable memory: 0x0000000000000372 | 72 03 00 00 00 00 00 00
RDI=0x0 is NULL
R8 =0x0 is NULL
R9 =0x0 is NULL
R10=0x0 is NULL
R11=0xd40e1b1398e489b4 is an unknown value

### Please provide steps to reproduce where possible

 copy text from other app to eclipse, for example: from firfox browser  to eclipse,

### Expected Results

copy text from other app to eclipse .

### Actual Results

The crash often occurs when copy text from other app to eclipse,  it happens frequently, but not every time.

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)

### What is your operating system and platform?

Ubuntu 22.04.2 LTS 64bit

### How did you install Java?

download  openjdk17.0.6 zip from oracle

**Comment by karianna** [comment]
Please update to Java 17.0.7 (or 17.0.8 when that comes out in the next few weeks) and also upgrade the underlying Eclipse IDE libs (they've fixed the most common Cairo rendering issues there)
