### ISSUE TITLE
Jar unzip issues on MacOS Arm

### ISSUE THREAD

**Issue by alexet** [adoptium/adoptium-support#845]
### Please provide a brief summary of the bug

We are getting occasional mangled classes on macos aarch64 .

An example: `java.lang.ClassFormatError: Unknown constant tag 101 in class file com/semmle/cli2/generate/LogSummaryCommand` but we get various different symptoms (mangled dependency names, verification issues, etc). The classes on disk are fine and work fine for future runs.

We think this is [JDK-8282954](https://bugs.openjdk.org/browse/JDK-8282954).

The fix was supposedly backported here: [JDK-8297637](https://bugs.openjdk.org/browse/JDK-8297637) but the adoptium builds are not bundling zlib on macos arm and I don't see the backport in the jdk repository.

 It seems like the fix just changes default build arguments so it should be possible to fix this in the build scripts instead.

### Please provide steps to reproduce where possible

I suspect the reproduction in [JDK-8282954](https://bugs.openjdk.org/browse/JDK-8282954) would work?

### Expected Results

Not crash.

### Actual Results

It crashes on class loading.

### What Java Version are you using?

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### What is your operating system and platform?

Mac OS arm.

### How did you install Java?

Downloaded via the api from the website. Repacked with 

```
jlink \
                      --output "new-jdk" \
                      --module-path jmods/ \
                      --compress=2 \
                      --strip-debug \
                      --add-modules java.management,java.instrument,java.naming,jdk.management.agent,jdk.zipfs,jdk.compiler,java.xml,java.sql,java.rmi,java.desktop,jdk.unsupported,jdk.crypto.ec
```

### Did it work before?

```Shell
It has never worked on macos aarch64.
```

### Did you test with the latest update version?

```Shell
We tested with the latest version of 17 (17.0.7)
```

### Did you test with other Java versions?

```Shell
We have had the same issue with all previous versions of 17
```

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8297637 is an Oracle JDK only backport, we'll need to backport to OpenjDK

**Comment by gdams** [comment]
Backport to JDK17u-dev here: https://github.com/openjdk/jdk17u-dev/pull/1609
