### ISSUE TITLE
Where/how to Manage the exception list?

### ISSUE THREAD

**Issue by MarcAStHilaire** [adoptium/adoptium-support#846]
## How to manage the exception list?

I recently changed from Oracle to Temurin.
Where/how do I manage the exception list of java?

Java version:
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)

My operating system and platform:
Windows 10 Entreprise  V.21H2 x64

**Comment by karianna** [comment]
We do not support this Webstart feature.  Please see OpenWebstart if you need to use IcedTeaWeb/Webstart.  CC @hendrikebbers
