### ISSUE TITLE
Java 17 cannot start on AIX 7.2

### ISSUE THREAD

**Issue by gvernier** [adoptium/adoptium-support#847]
### Please provide a brief summary of the bug

Hello,
I'm trying to run java 17 on an AIX7.2TL05SP05 and I get the following error:
rs95:/tmp/jdk-17.0.7+7-jre/bin# oslevel -s
7200-05-05-2246

rs95:/tmp/jdk-17.0.7+7-jre/bin# ./java -version
Error: dl failure on line 542
Error: failed /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so, because 0509-022 Cannot load module /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so.
        0509-150 Dependent module libc++.a(shr_64.o) could not be loaded.
        0509-022 Unable to load module libc++.a(shr_64.o).
        0509-026 System error: A file or directory in the path name does not exist.
        0509-022 Unable to load module /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so.
        0509-150 Dependent module /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so could not be loaded.

I have retrieved the following archive : https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jre_ppc64_aix_hotspot_17.0.7_7.tar.gz

A similar ticket has already been opened, but there was no resolution.
On my system, the xlc++ installed is version XLC 16.1.
Thank you in advance for your help.

Gaël

### Expected Results

show java version

### Actual Results

rs95:/tmp/jdk-17.0.7+7-jre/bin# ./java -version
Error: dl failure on line 542
Error: failed /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so, because       0509-022 Cannot load module 
        0509-150   Dependent module libc++.a(shr_64.o) could not be loaded.
        0509-022 Cannot load module libc++.a(shr_64.o).
        0509-026 System error: A file or directory in the path name does not exist.
        0509-022 Cannot load module /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so.
        0509-150   Dependent module /tmp/jdk-17.0.7+7-jre/lib/server/libjvm.so could not be loaded.

### What Java Version are you using?

17.0.7+7

### What is your operating system and platform?

AIX 7.2TL05SP05

### How did you install Java?

I download from github

**Comment by karianna** [comment]
@gvernier Can you try the 17.0.8 release?   Should be out in a few days.

**Comment by gvernier** [comment]
@karianna I don't think the latest version is available for OS AIX. There is a ppc64 version for Linux. Do you have this version for AIX?

**Comment by karianna** [comment]
See adoptium.net - the banner there has a link to our status page for getting the builds out this week including AIX.
