### ISSUE TITLE
JRE 17 LTS: can't open jar files

### ISSUE THREAD

**Issue by TomasGnG** [adoptium/adoptium-support#848]
### Please provide a brief summary of the bug

I just installed the latest version of Eclipse Temurin JRE 17LTS and I wanted to install Optifine but I couldnt open the file as it opens a console windows for a millisecond. Nothing happens after that.
I tried to use `java -jar file.jar` in a console window and it worked. I didnt changed anything from the installer or something.

### Expected Results

The file should open as usual and do the things that it should do.

### Actual Results

A console window for a millisecond. Nothing happens afterwards.

### What Java Version are you using?

openjdk 17.0.8 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### What is your operating system and platform?

Microsoft Windows 10 Pro
Version: 10.0.19044

### How did you install Java?

Downloaded the installer package from the official adoptium.net site.

### Did it work before?

```Shell
I just reseted my pc. I've had Oracle Java installed before and everything worked.
```

### Did you test with the latest update version?

```Shell
It is the latest update.
```

### Did you test with other Java versions?

```Shell
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)

Also with Redhat:
jdk-17.0.8+7_1
JDK
July 20, 2023
```

**Comment by TomasGnG** [comment]
Used jarfix and the problem was solved.

**Comment by Baraz-Siriel** [comment]
Awesome.  It also made it much simpler (as it should be imo).
