### ISSUE TITLE
Client keeps crashing

### ISSUE THREAD

**Issue by manman8258** [adoptium/adoptium-support#850]
### Please provide a brief summary of the bug

[jvm_crash_pid_9304_r.log](https://github.com/adoptium/adoptium-support/files/12210344/jvm_crash_pid_9304_r.log)

### Please provide steps to reproduce where possible

just playing the game and it will randomly crash at any point. Annoying when I'm in the middle of a boss or in a bad area.

### Expected Results

I expect the game not to crash randomly.

### Actual Results

Game crashes randomly and give me logs I have no idea what they mean.

### What Java Version are you using?

java 11

### What is your operating system and platform?

Windows 10 AMD Ryzen 9 5900x

### How did you install Java?

installed it with runescape and runelite

### Did it work before?

```Shell
Had no issues before a hard drive failure and resetting it.
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffff5b5c42d, pid=9304, tid=19752
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.19+7 (11.0.19+7) (build 11.0.19+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (11.0.19+7, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x32c42d]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```

**Comment by karianna** [comment]
@manman8258 Can you try the recently release 11.0.20 and report back here.
