### ISSUE TITLE
elasticsearch use jdk 1.8-8u322 arm kylin sp3 find from-size = -1 but jdk handler with 268435455 

### ISSUE THREAD

**Issue by xxy201799** [adoptium/adoptium-support#851]
### Please provide a brief summary of the bug

i try to use elasticsearch on jdk-8u322 and the cpu archive is arm(os version kylin sp3)，but find a data detail bug, from-size is -1,but traced the data find its changed by jdk ( 268435455)

### Expected Results

i try to use elasticsearch on jdk-8u322 and the cpu archive is arm(os version kylin sp3)，but find a data detail bug, from-size is -1,but traced the data find its changed by jdk ( 268435455)

### Actual Results

i try to use elasticsearch on jdk-8u322 and the cpu archive is arm(os version kylin sp3)，but find a data detail bug, from-size is -1,but traced the data find its changed by jdk ( 268435455)

### What Java Version are you using?

ibm-semeru-open-jdk_aarch64_linux_8u322b06

### What is your operating system and platform?

kylin sp3 v10 arm64

### How did you install Java?

tar.gz

### Did it work before?

```Shell
no
```

### Did you test with the latest update version?

```Shell
yes,  jdk8u372-b07 not has this bug
```

### Did you test with other Java versions?

```Shell
yes,  jdk8u372-b07 not has this bug
```

**Comment by karianna** [comment]
Please update to jdk8u372 or u382 to resolve this.
