### ISSUE TITLE
no core dump is being created in the specified location

### ISSUE THREAD

**Issue by yugandharreddy1** [adoptium/adoptium-support#853]
### Please provide a brief summary of the bug

we are doing a stress test on our application with AWS 8 node cluster test and one pod is restarting frequently with the below error log saying that core dump will be written at below location  but no such file found.

we also set the ulimit -c unlimited and also increased our PVC size but still same issue of file not written.

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0790f26461, pid=1, tid=2197
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8+7 (17.0.8+7) (build 17.0.8+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (17.0.8+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libccutil.so+0xe461]  ghdGetStringReference+0x131
#
# Core dump will be written. Default location: /opt/appworks/cluster/shared/core.1
#
[hs_err_pid%t.log](https://github.com/adoptium/adoptium-support/files/12246889/hs_err_pid.t.log)
 

### Expected Results

core dump should be present at given location 

### Actual Results

no core dump found

### What Java Version are you using?

openjdk 17.0.8 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)

### What is your operating system and platform?

kubernetes node with centos rhel fedora

**Comment by karianna** [comment]
com.eibus.xml.nom.Node.getAttributeInt seems to be the calling culprit here.  Is this using Unsafe, native calls, off heap memory anything like that?

**Comment by yugandharreddy1** [comment]
Hi @karianna  its calling the C code of ours which is mentioned 
C [libccutil.so+0xe461] ghdGetStringReference+0x131

but to did deep we wanted to collect the core dump which we are failing to get in the location mentioned

**Comment by karianna** [comment]
You'll need to use a debugger like GDb to dig into the c lib that is the root cause (it's sending an error back to Java basically)

**Comment by yugandharreddy1** [comment]
Hi We know that we can Use the GDb to check further but we are checking why the core dump is not written even when the cluster memory is sufficient  and we have also set the ulimit -c unlimited

**Comment by karianna** [comment]
@yugandharreddy1 so the core dump was not written to `/opt/appworks/cluster/shared/core.1`?
