### ISSUE TITLE
mcreator.sh does not finish installation

### ISSUE THREAD

**Issue by june8tr** [adoptium/adoptium-support#855]
### Please provide a brief summary of the bug

I was trying to install mcreator software for Linux (https://github.com/MCreator/MCreator/releases/download/2023.2.24119/MCreator.2023.2.Linux.64bit.tar.gz). I am at Ubuntu 22.04 installed on Raspberry Pi4 8GB.

I go into terminal by right click when inside the extracted archive folder and type ./mcreator.sh as instructed by the related MCreator web page (https://mcreator.net/install/linux) however installation quits with Fatal Error with the attached report.
[hs_err_pid2758.log](https://github.com/adoptium/adoptium-support/files/12251064/hs_err_pid2758.log)

### Please provide steps to reproduce where possible

Download (https://github.com/MCreator/MCreator/releases/download/2023.2.24119/MCreator.2023.2.Linux.64bit.tar.gz).

Extract the files in to a directory and open that directory window, right click on blank area and choose "Open in Terminal"

type ./mcreator.sh

installation quits with Fatal Error with the attached report.

### Expected Results

Installation of MCreator without any error

### Actual Results

Installation ends with error and not installs MCreator software

### What Java Version are you using?

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04) OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-122.04, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04 on Raspberry Pi with 8GB Ram using Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz

### How did you install Java?

Entering - sudo apt install default-jre - on Ubuntu 22.04 Terminal

### Did it work before?

```Shell
yes
```

### Did you test with the latest update version?

```Shell
yes
```

### Did you test with other Java versions?

```Shell
Yes, java-11-openjdk-arm64
```

### Relevant log output

```Shell
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00000001026f60ec, pid=2758, tid=2773
JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Problematic frame:
V [libjvm.so+0x6c60ec] frame::sender_for_interpreter_frame(RegisterMap*) const+0x8c
Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/kasif/MCreator20232/core.2758)
If you would like to submit a bug report, please visit:
https://github.com/adoptium/adoptium-support/issues

--------------- S U M M A R Y ------------

Command Line: --add-opens=java.base/java.lang=ALL-UNNAMED net.mcreator.Launcher

Host: Intel Pentium IV @ 1,8GHz, 4 cores, 7G, Ubuntu 22.04.2 LTS
Time: Thu Aug 3 14:31:54 2023 +03 elapsed time: 35.711371 seconds (0d 0h 0m 35s)
```

**Comment by karianna** [comment]
Please upgrade to 17.0.8 and post any errors back here.  I do suspect this will be the same advice as for Minecraft itself though (in terms of updating grpahics drivers etc).

**Comment by june8tr** [comment]
[hs_err_pid3673.log](https://github.com/adoptium/adoptium-support/files/12413113/hs_err_pid3673.log)

**Comment by june8tr** [comment]
Hello and thanks for your support. I have installed 17.0.8 as per your advice. When I run "java -version" it shows java 17.0.8+7, however when I run "./mcreator.sh" it detects java 17.0.5+8 and can not complete the installation with the attached log.
[hs_err_pid3673.log](https://github.com/adoptium/adoptium-support/files/12413139/hs_err_pid3673.log)

**Comment by karianna** [comment]
You'll need to look at mcreator.sh and find where it is referencing the older version of Java, it may bundle it with the application.
