### ISSUE TITLE
Core dump on installing OpenJDK jdk8u372-b07 

### ISSUE THREAD

**Issue by kasayers** [adoptium/adoptium-support#862]
### Please provide a brief summary of the bug

After installing this version - if you run java -version you get:
>./java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:51), pid=66322624, tid=0x0000000000000102
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode, sharing aix-ppc64 )
# Core dump written. Default location: /usr/openjdk/jdk8u372-b07-jre/bin/core or core.66322624
#
# An error report file with more information is saved as:
# /usr/openjdk/jdk8u372-b07-jre/bin/hs_err_pid66322624.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
IOT/Abort trap(coredump)

### Please provide steps to reproduce where possible

You can re-produce by running  : java -version   - I also tried on jdk8u382 and get the same result. Customers are respoting the same problem

### Expected Results

RBAIX2->java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b08, mixed mode)

### Actual Results

/java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:51), pid=66322624, tid=0x0000000000000102
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode, sharing aix-ppc64 )
# Core dump written. Default location: /usr/openjdk/jdk8u372-b07-jre/bin/core or core.66322624
#
# An error report file with more information is saved as:
# /usr/openjdk/jdk8u372-b07-jre/bin/hs_err_pid66322624.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues:

### What Java Version are you using?

See above

### What is your operating system and platform?

RBAIX2->uname -a
AIX br-aix-02 1 7 00FA782C4C00

### Did it work before?

```Shell
gunzip -c /tpp/oracle/CDs/openjdk/OpenJDK8U-jre_ppc64_aix_hotspot_8u372b07.tar.gz|tar -xvf -

This worked on previous versions
```

### Did you test with the latest update version?

```Shell
Tested 8u382B07.tar.gz  and got the same result also tried the JRE with the same result.
```

### Did you test with other Java versions?

```Shell
Yes See above 8u352  works
```

### Relevant log output

```Shell
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:51), pid=19923188, tid=0x0000000000000102
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode, sharing aix-ppc64 )
# Core dump written. Default location: /usr/openjdk/jdk8u372-b07-jre/bin/core or core.19923188
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x000000011001e000,0x000000011021d000],  sp=0x000000011021b580,  free space=2037k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

[error occurred during error reporting (printing native stack), id 0xe0000000]


---------------  P R O C E S S  ---------------

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None


Dynamic libraries:

VM Arguments:
java_command: <unknown>
java_class_path (initial): <not set>
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=/tpp/oracle/java/openjdk_tomcat
PATH=/tpp/oracle/java/openjdk_tomcat/bin:/opt/bin:/usr/sbin:/usr/bin:/usr/vac/bin:/usr/ccs/bin:/usr/lib:.:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:
/usr/java6/jre/bin:/usr/java6/bin:/tpp/oracle/19.0.0.0SE/bin:/tpp/oracle/19.0.0.0SE/OPatch:/tpp/oracle/19.0.0.0SE/lib:.
SHELL=/usr/bin/ksh

Signal Handlers:
SIGSEGV:
[error occurred during error reporting (printing signal handlers), id 0xe0000000]


---------------  S Y S T E M  ---------------

OS:uname:AIX br-aix-02 1 7 00FA782C4C00
rlimit: STACK infinity, CORE infinity, NPROC 262144, NOFILE infinity, AS infinity, DATA infinity
load average:0.31 0.27 0.30
```

**Comment by kasayers** [comment]
Is there a problem with this release as all are customers are experiencing the same problem

**Comment by karianna** [comment]
Can you send in the exact crash log for _382 please and we'll take a look

**Comment by kasayers** [comment]
extracted with:
gunzip -c OpenJDK8U-jre_ppc64_aix_hotspot_8u382b05.tar.gz|tar -xvf -

 A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:51), pid=7471272, tid=0x0000000000000102
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.382-b05 mixed mode, sharing aix-ppc64 )
# Core dump written. Default location: /usr/openjdk/jdk8u382-b05/bin/core or core.7471272
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x000000011001e000,0x000000011021d000],  sp=0x000000011021b580,  free space=2037k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

[error occurred during error reporting (printing native stack), id 0xe0000000]


---------------  P R O C E S S  ---------------

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None


Dynamic libraries:

VM Arguments:
java_command: <unknown>
java_class_path (initial): <not set>
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=/tpp/oracle/java/openjdk_tomcat
PATH=/tpp/oracle/java/openjdk_tomcat/bin:/opt/bin:/usr/sbin:/usr/bin:/usr/vac/bin:/usr/ccs/bin:/usr/lib:.:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/
usr/java6/jre/bin:/usr/java6/bin:/tpp/oracle/19.0.0.0SE/bin:/tpp/oracle/19.0.0.0SE/OPatch:/tpp/oracle/19.0.0.0SE/lib:.
SHELL=/usr/bin/ksh

Signal Handlers:
SIGSEGV:
[error occurred during error reporting (printing signal handlers), id 0xe0000000]


---------------  S Y S T E M  ---------------

OS:uname:AIX br-aix-02 1 7 00FA782C4C00
rlimit: STACK infinity, CORE infinity, NPROC 262144, NOFILE infinity, AS infinity, DATA infinity
load average:0.55 0.39 0.38

CPU:total 16 (initial active 0)
CPU:total 16

Memory:
  default page size: 4K
  default stack page size: 4K
  default shm page size: 4K
  can use 64K pages dynamically: yes
  can use 16M pages dynamically: no
  LDR_CNTRL=<unset>.
  EXTSHM=<unset>.
  physical total : 66303557632
  physical free  : 326983680
  swap total     : 34896609280
  swap free      : 34651414528

vm_info: OpenJDK 64-Bit Server VM (25.382-b05) for aix-ppc64 JRE (1.8.0_382-b05), built on Jul 19 2023 15:51:09 by "jenkins" with xlC 1313

time: Tue Aug  8 06:48:56 2023
timezone: BST
elapsed time: 0.009685 seconds (0d 0h 0m 0s)

**Comment by kasayers** [comment]
extracted with:
gunzip -c OpenJDK8U-jre_ppc64_aix_hotspot_8u382b05.tar.gz|tar -xvf -

 A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:51), pid=7471272, tid=0x0000000000000102
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  ((uninitialized)) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.382-b05 mixed mode, sharing aix-ppc64 )
# Core dump written. Default location: /usr/openjdk/jdk8u382-b05/bin/core or core.7471272
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x000000011001e000,0x000000011021d000],  sp=0x000000011021b580,  free space=2037k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

[error occurred during error reporting (printing native stack), id 0xe0000000]


---------------  P R O C E S S  ---------------

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None


Dynamic libraries:

VM Arguments:
java_command: <unknown>
java_class_path (initial): <not set>
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=/tpp/oracle/java/openjdk_tomcat
PATH=/tpp/oracle/java/openjdk_tomcat/bin:/opt/bin:/usr/sbin:/usr/bin:/usr/vac/bin:/usr/ccs/bin:/usr/lib:.:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/
usr/java6/jre/bin:/usr/java6/bin:/tpp/oracle/19.0.0.0SE/bin:/tpp/oracle/19.0.0.0SE/OPatch:/tpp/oracle/19.0.0.0SE/lib:.
SHELL=/usr/bin/ksh

Signal Handlers:
SIGSEGV:
[error occurred during error reporting (printing signal handlers), id 0xe0000000]


---------------  S Y S T E M  ---------------

OS:uname:AIX br-aix-02 1 7 00FA782C4C00
rlimit: STACK infinity, CORE infinity, NPROC 262144, NOFILE infinity, AS infinity, DATA infinity
load average:0.55 0.39 0.38

CPU:total 16 (initial active 0)
CPU:total 16

Memory:
  default page size: 4K
  default stack page size: 4K
  default shm page size: 4K
  can use 64K pages dynamically: yes
  can use 16M pages dynamically: no
  LDR_CNTRL=<unset>.
  EXTSHM=<unset>.
  physical total : 66303557632
  physical free  : 326983680
  swap total     : 34896609280
  swap free      : 34651414528

vm_info: OpenJDK 64-Bit Server VM (25.382-b05) for aix-ppc64 JRE (1.8.0_382-b05), built on Jul 19 2023 15:51:09 by "jenkins" with xlC 1313

time: Tue Aug  8 06:48:56 2023
timezone: BST
elapsed time: 0.009685 seconds (0d 0h 0m 0s)

**Comment by sxa** [comment]
> RBAIX2->uname -a
> AIX br-aix-02 1 7 00FA782C4C00

It looks like you are running on AIX 7.1 which is now out of support. We are now building Temurin on AIX 7.2 which means you cannot expect the latest versions to run properly on AIX 7.1 unfortunately.
