### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment: SIGSEGV

### ISSUE THREAD

**Issue by bakogee** [adoptium/adoptium-support#863]
### Please provide a brief summary of the bug

We've experienced the following issue:

A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x00007f0cde41a5d0, pid=1964, tid=2180

JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
V  [libjvm.so+0x7f05d0]

Core dump will be written. Default location: Core dumps may be processed with "/bin/sh /usr/sbin/coredump.sh %p %P %t %e %h" (or dumping to /opt/core.1964)

If you would like to submit a bug report, please visit:
https://github.com/adoptium/adoptium-support/issues

### Expected Results

No crash during the JVM runtime

### Actual Results

JVM stopped working caused by a SIGSEGV error. See the following file for more details:
[hs_err_pid1964.log](https://github.com/adoptium/adoptium-support/files/12288760/hs_err_pid1964.log)

### What Java Version are you using?

 OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

### What is your operating system and platform?

Rocky Linux release 8.7 (Green Obsidian)

### How did you install Java?

RPM installation from custom built rpm from `https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz`

**Comment by karianna** [comment]
Please upgrade to 11.0.20 and report back here with any crashlogs.
