### ISSUE TITLE
Cannot install Adoptium

### ISSUE THREAD

**Issue by Robin91862** [adoptium/adoptium-support#866]
### Please provide a brief summary of the bug

When I try to install Adoptium, I get error codes: 2503 i 2502
![Error code 2503](https://i.imgur.com/sL4QxOf.png)
![Error code 2502](https://i.imgur.com/OTzukOu.png)

### Please provide steps to reproduce where possible

Run OpenJDK17U-jre_x64_windows_hotspot_17.0.8_7.msi and try to install Adoptium

### Expected Results

I expected Adoptium to install without any errors

### Actual Results

Adoptium failed to install and threw two error codes: 2503 and 2502

### What Java Version are you using?

I don't have Java installed

### What is your operating system and platform?

Windows 10 (AtlasOS) 22H2 x64

### How did you install Java?

I tried installing Java with a .msi file

### Did it work before?

```Shell
Adoptium was working before Windows reinstallation
```

### Did you test with the latest update version?

```Shell
I used the latest version of Adoptium
```

### Did you test with other Java versions?

```Shell
Yes, I tested with RedHat JRE 17, Microsoft JDK 17.
There were the same error codes
```

**Comment by gdams** [comment]
According to [this guide](https://winaero.com/fix-msi-installer-errors-2502-and-2503-in-windows-10-windows-8-1-and-windows-7/) MSI error 2502 and 2503 indicate that the folder `C:\Windows\Temp` has [incorrect NTFS permissions](https://winaero.com/blog/easier-way-to-set-copy-and-manage-ntfs-permissions-acls-on-files-and-folders-in-windows/).

Can you look at the steps in this guide and see if that fixes the issue? https://winaero.com/fix-msi-installer-errors-2502-and-2503-in-windows-10-windows-8-1-and-windows-7/

**Comment by Robin91862** [comment]
Hello @gdams, the tutorial worked. I saw another issue on GitHub just about these errors, but that one didn't work. So thank you very much for your help and I hope this issue will help others.
