### ISSUE TITLE
AdoptOpenJDK 11.0.8+10 awt.dll (The process cannot access the file because it is being used by another process)

### ISSUE THREAD

**Issue by brijesh-dobariya** [adoptium/adoptium-support#871]
### Please provide a brief summary of the bug

We have encountered an issue wherein the awt.dll file appears to be utilized by a separate process within the context of Windows Server 2012. It's noteworthy that this issue has not manifested on Windows Server 2019. The environment employs AdoptOpenJDK version 11.0.8+10.

Despite our efforts, which included ensuring the termination of all related processes, we are perplexed by the persistence of the awt.dll file's association with another process on Windows Server 2012.

We express gratitude for any insights or assistance in comprehending and resolving this situation.

Thank you.

### Please provide steps to reproduce where possible

1. Stop apache tomcat server (Apache tomcat server v9.0.40)
2. Backup full Java folder (AdoptOpenJDK11.0.8+10)
3. Remove full java folder (AdoptOpenJDK11.0.8+10)
4. While doing step-3, Java\bin\awt.dll (The process cannot access the file because it is being used by another process)

Same process will works in windows server 2019 but not in windows server 2012. All steps we are doing by Java application.

### Expected Results

If all dependent processes have been terminated, the awt.dll file should be released.

### Actual Results

awt.dll (The process cannot access the file because it is being used by another process) even all dependent process are stoped.

### What Java Version are you using?

AdoptOpenJDK-11.0.8+10

### What is your operating system and platform?

Windows server 2012 and 64bit

### How did you install Java?

we have used binary archive .zip direct

### Did it work before?

While the functionality was successful on Windows Server 2019, it encountered difficulties on Windows Server 2012.

### Did you test with the latest update version?

Yes, we have tested with OpenJDK17 but it is not working.

### Did you test with other Java versions?

I have tested with OpenJDK17

### Relevant log output

Java\bin\awt.dll (The process cannot access the file because it is being used by another process)

**Comment by gdams** [comment]
@brijesh-dobariya you are using a very old version of OpenJDK. The latest Temurin version is 11.0.20+8. Please can you download the latest from here: https://adoptium.net/temurin/releases/?version=11 and report back

**Comment by brijesh-dobariya** [comment]
@gdams I have already tested with OpenJDK17, so still need to test with OpenJDK11.0.20+8?

**Comment by gdams** [comment]
> @gdams I have already tested with OpenJDK17, so still need to test with OpenJDK11.0.20+8?

yes please

**Comment by brijesh-dobariya** [comment]
Sure @gdams will test and let you know. Thanks for prompt response.

**Comment by brijesh-dobariya** [comment]
@gdams 
I have tested the cases mentioned below; however, I continue to encounter the same issue on Windows Server 2012.

**Actions Taken:**
	Stopped and Deleted Apache Tomcat **v9.0.40** service associated with **OpenJDK 11.0.8+10.**
	Stopped and Deleted Apache Tomcat **v9.0.40** service associated with **OpenJDK 11.0.11+9.**
	Stopped and Deleted Apache Tomcat **v9.0.68** service associated with **OpenJDK 11.0.11+9.**
	Stopped and Deleted Apache Tomcat **v9.0.40** service associated with **OpenJDK 17.0.8+7.**
	Stopped and Deleted Apache Tomcat **v9.0.68** service associated with **OpenJDK 11.0.20+8.**

**Outcome:**
Unfortunately, the attempt to remove the Java folders for **OpenJDK 11.0.8+10, 11.0.11+9, 11.0.20+8, and 17.0.8+7** was unsuccessful due to the presence of the awt.dll file, which is currently in use by another process. The encountered error message was: "The process cannot access the file because it is being used by another process."

**Comment by karianna** [comment]
Chat GPT-4 gives the following guidance:

If you want to find out which processes are currently using a particular DLL (Dynamic Link Library) on a Windows Server 2012 system, you can use various methods. Here are some of the most common techniques:

1. **Tasklist Command**:
    - Open a command prompt as an administrator.
    - Use the following command to list all processes using a particular DLL:
      ```
      tasklist /m "your_dll_name.dll"
      ```
    Replace `your_dll_name.dll` with the name of the DLL you're interested in.

2. **Resource Monitor**:
    - Press `Win + R` to open the Run dialog.
    - Type `resmon` and hit Enter. This will open the Resource Monitor.
    - Go to the CPU tab.
    - Under the "Associated Handles" section, you can search for the DLL name in the search box. This will display a list of processes using that DLL.

3. **Process Explorer**:
    - Download and run [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) from Microsoft's Sysinternals suite.
    - Launch Process Explorer and then go to `Find` > `Find Handle or DLL` in the menu (or press `Ctrl + F`).
    - Type the name of the DLL into the search box and hit Enter. Process Explorer will show you a list of processes using the specified DLL.

4. **Dependency Walker**:
    - Another useful tool is [Dependency Walker](http://www.dependencywalker.com/). It can show you which DLLs a specific application uses. However, this doesn't show you the currently running processes that use the DLL; instead, it's more about checking an application's dependencies.

5. **Windows Performance Toolkit**:
    - You can also use tools like the Windows Performance Toolkit to trace DLL usage. This toolkit, however, is more advanced and has a steeper learning curve.

Remember that while these methods will tell you which processes are using a specific DLL, they won't necessarily inform you why a particular DLL is in use or whether it's essential for the process. If you're troubleshooting a specific issue, further investigation may be required.

**Comment by brijesh-dobariya** [comment]
@karianna Thanks for details response, but same cases work on windows server 2019. The question is why it is not working on windows server 2012, but no worries we will kill the DLL process forcefully now.
