### ISSUE TITLE
"Comparison method violates its general contract" error on SAP PO 

### ISSUE THREAD

**Issue by faisal-jamal** [adoptium/adoptium-support#874]
### Please provide a brief summary of the bug

Hello,
I am new to github and this is my first post. Not sure if this is the right place to port this. Anyways, hoping to find a solution to the issue I am facing with SAP PO Integration Builder tool.
I get the "Comparison method violates its general contract" error as soon as I click on Value Mapping group option and try to expand it. This is a known error and the solution provided by SAP indicated to update the parameter "-Djava.util.Arrays.useLegacyMergeSort=true" in the Java Control panel. This worked fine when we were usig Oracle Java but it is not working with Adopt OpenJDK.

<img width="303" alt="ID Error" src="https://github.com/adoptium/adoptium-support/assets/142318786/2782fdf3-d947-42ca-b480-0f690e19c9c5">
[Log.txt](https://github.com/adoptium/adoptium-support/files/12344401/Log.txt)

Also, this parameter is updated on SAP PO server as suggested by SAP in https://me.sap.com/notes/2185344

Any hints on how to get this working would be appreciated. Also, please let me know if I missed any details. Thanks!

### Expected Results

The Integration Builder window should show the list of Value mapping Groups available.

### Actual Results

results in error pop up saying: Comparison method violates its general contract in PI Integration Builder

### What Java Version are you using?

11.0.12

### What is your operating system and platform?

Windows 10

### Did it work before?

```Shell
Only with Oracle Java.
```

**Comment by karianna** [comment]
@faisal-jamal What version of Oracle Java were you using?

**Comment by faisal-jamal** [comment]
> @faisal-jamal What version of Oracle Java were you using?

It was 1.8.0_281-b09. (Version 8 update 281)

**Comment by karianna** [comment]
@faisal-jamal - This is an issue that SAP will need to resolve in their product.  They should ideally rewrite their sorting logic to not use the legacy sorting algo (which is brittle).  If you are using JNLP - the setting of the property file may not be working due to https://bugs.openjdk.org/browse/JDK-7132484 - see if you can follow the instructions there.

I'd also recommend downgrading to Java 1.8.0_382 to most closely match what you had with Oracle.

**Comment by karianna** [comment]
@faisal-jamal You'll need to ask the SAP folks to resolve this for their product.  You might have some luck talking to the folks behind OpenWebstart as well.
