### ISSUE TITLE
Cant install bc ca-certificates and fonts dejavu is missing

### ISSUE THREAD

**Issue by MoinAmMorgen** [adoptium/adoptium-support#886]
## Question

I am trying to install Java 8 with the guide on the adoptium website. Everything works until I do this command: apt install temurin-8-jdk. I get this error: Hängt ab von: adoptium-ca-certificates soll aber nicht installiert werden
                 Hängt ab von: fonts-dejavu ist aber nicht installierbar
In English: Termium-8-jdk needs adoptium-ca-certificates but shouldn’t be installed.
Termium-8-jdk needs fonts-dejavu but cant be installed.
## Context

Java version:
Trying to Install Java 8

openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Debian-1deb11u1, mixed mode, sharing)

Your operating system and platform:
Debian 10

**Comment by karianna** [comment]
@MoinAmMorgen Can you post exactly which instructions you followed? I believe the Adoptium Certificates and the Dejavu fonts should come with the installer as such.
