### ISSUE TITLE
Error Start

### ISSUE THREAD

**Issue by DarkErrorZX** [adoptium/adoptium-support#890]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f197d78d6f4, pid=1, tid=34
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (17.0.8.1+1) (build 17.0.8.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (17.0.8.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7396f4]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x14d4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/container/core.1)
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid1.log
[thread 51 also had an error]
[thread 53 also had an error]
[thread 52 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f197e3ca898]

### Please provide steps to reproduce where possible

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f197d78d6f4, pid=1, tid=34
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (17.0.8.1+1) (build 17.0.8.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (17.0.8.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7396f4]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x14d4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/container/core.1)
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid1.log
[thread 51 also had an error]
[thread 53 also had an error]
[thread 52 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f197e3ca898]

### Expected Results

press start snow error and stop automat

### Actual Results

no starting

### What Java Version are you using?

java --19

### What is your operating system and platform?

ununtu 20

### How did you install Java?

no

### Did it work before?

```Shell
no
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
java --19
```

**Comment by karianna** [comment]
Could be https://bugs.openjdk.org/browse/JDK-8274053 which is not backported to 17.

**Comment by thaarbach** [comment]
Today, we ran into the same Problem

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff936b30214, pid=7, tid=51
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x73b214]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x14d4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /usr/local/tomcat/core.7)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=
ALL-UNNAMED -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.web
resources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 --add-opens=java.base/sun.util.locale=ALL-UNNAMED --add-opens=java.base/java.math=ALL-UNNAMED -Dorg.apache.catalina.STRICT_SERVLET_COMPLIANCE=false -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false -Djava.security.egd=file:///dev/urandom -XX:ErrorFile=/var/log/java/hs_err_wtf.log -Xms7500M -Xmx10000M -Xss384k -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:MaxGCPauseMillis=400 -XX:Initiat
ingHeapOccupancyPercent=1 -XX:ConcGCThreads=12 -XX:ParallelGCThreads=24 -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/java/heapdump-java/ -XX:+UseStringDeduplication -Xlog
:gc*,gc+stringdedup*=trace,gc+ref*=trace,gc+heap*=trace,gc+phases*=trace,gc+region*=debug,gc+marking*=debug,gc+remset*=debug,gc+task+stats*=trace,gc+task*=debug,gc+ergo*=trace,gc+age*=trace:file=/var/log/java/java-gc.log:tags,u
ptime,time,level:filecount=5,filesize=250m -Xlog:safepoint*:file=/var/log/java/java-safepoints.log:tags,uptime,time,level:filecount=5,filesize=50m -Denv-name=**** -Dspring.profiles.active=springMobile,elasticsearch,es-imag
e-service,production -Dlog4j2.isThreadContextMapInheritable=true -Dignore.endorsed.dirs= -Dcatalina.ba
se=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp org.apache.catalina.startup.Bootstrap start

Host: AMD EPYC 7502P 32-Core Processor, 64 cores, 503G, Ubuntu 22.04.3 LTS
Time: Thu Feb  1 19:55:25 2024 CET elapsed time: 130026.317481 seconds (1d 12h 7m 6s)

---------------  T H R E A D  ---------------

Current thread (0x00007ff89800e650):  GCTaskThread "GC Thread#8" [stack: 0x00007ff8f03dd000,0x00007ff8f04dd000] [id=51]

Stack: [0x00007ff8f03dd000,0x00007ff8f04dd000],  sp=0x00007ff8f04db9b0,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x73b214]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x14d4
V  [libjvm.so+0x756e20]  G1ScanHRForRegionClosure::scan_heap_roots(HeapRegion*)+0x530
V  [libjvm.so+0x74e6d7]  G1RemSet::scan_heap_roots(G1ParScanThreadState*, unsigned int, G1GCPhaseTimes::GCParPhases, G1GCPhaseTimes::GCParPhases, bool)+0x1a7
V  [libjvm.so+0x6f6d4b]  G1EvacuateRegionsTask::scan_roots(G1ParScanThreadState*, unsigned int)+0x4b
V  [libjvm.so+0x6f75a3]  G1EvacuateRegionsBaseTask::work(unsigned int)+0x83
V  [libjvm.so+0xf1431f]  GangWorker::loop()+0x5f
V  [libjvm.so+0xf1437f]
V  [libjvm.so+0xe633b8]  Thread::call_run()+0xa8
V  [libjvm.so+0xc24791]  thread_native_entry(Thread*)+0xe1


siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000125cf0790

Registers:
RAX=0x00007ff930056e44, RBX=0x00007ff82405faa0, RCX=0x00007ff9300572da, RDX=0x0000000000000000
RSP=0x00007ff8f04db9b0, RBP=0x00007ff8f04dba40, RSI=0x0000000000000003, RDI=0x000000000000024b
R8 =0x0000000000000001, R9 =0x00007ff8a3112500, R10=0x0000000000000000, R11=0x0000000000000017
R12=0x000000076726aafd, R13=0x0000000125cf0790, R14=0x00007ff9376f832d, R15=0x00007ff9376b1330
RIP=0x00007ff936b30214, EFLAGS=0x0000000000010246, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e


Register to memory mapping:

RAX=0x00007ff930056e44 points into unknown readable memory: 00 00 00 00
RBX=0x00007ff82405faa0 points into unknown readable memory: 0x00007ff937600ef0 | f0 0e 60 37 f9 7f 00 00
RCX=0x00007ff9300572da points into unknown readable memory: 00 00 00 00 00 00
RDX=0x0 is NULL
RSP=0x00007ff8f04db9b0 points into unknown readable memory: 0x00000000004485ab | ab 85 44 00 00 00 00 00
RBP=0x00007ff8f04dba40 points into unknown readable memory: 0x00007ff8f04dbb90 | 90 bb 4d f0 f8 7f 00 00
RSI=0x0000000000000003 is an unknown value
RDI=0x000000000000024b is an unknown value
R8 =0x0000000000000001 is an unknown value
R9 =0x00007ff8a3112500 is pointing into metadata
R10=0x0 is NULL
R11=0x0000000000000017 is an unknown value
R12=0x000000076726aafd is pointing into object: java.util.concurrent.ConcurrentHashMap$Node 
{0x000000076726aae8} - klass: 'java/util/concurrent/ConcurrentHashMap$Node'
 - ---- fields (total size 4 words):
 - final 'hash' 'I' @12  2140888767 (7f9b5ebf)
 - final 'key' 'Ljava/lang/Object;' @16  "co.elastic.apm.exception"{0x00000005db13f200} (bb627e40)
 - volatile 'val' 'Ljava/lang/Object;' @20  
[error occurred during error reporting (printing register info), id 0xb, SIGSEGV (0xb) at pc=0x00007ff936c20e9a]

```

Application runs in an dockerized tomcat.  Since few weeks we struggling also with other issues like

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2d95bf3498, pid=7, tid=51
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x760498]  G1SATBMarkQueueSet::filter(SATBMarkQueue&)+0x78
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /usr/local/tomcat/core.7)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

```

We don't know if it's just a coincidence that different problems occur during GC. 

Maybe someone sees an unfavorable GC option that should be changed for JDK17.

We have been using JDK17 (tomcat:9-jdk17-openjdk) since July 2023 and so far there have been no problems. Due to a recommendation regarding another problem, we switched to the latest Temurin (tomcat:9-jdk17) on January 30, 2024. Since then there have been various problems related to GC.

**Comment by karianna** [comment]
@thaarbach Any luck with the very latest 17.0.11 based images?

**Comment by thaarbach** [comment]
@karianna sorry, didn't see your comment. The error disapear with newer image. The latest which we use is 17.0.12.

**Comment by violetgo** [comment]
I have same issues at `17.0.13+11`

`
#  SIGSEGV (0xb) at pc=0x00007fcba788ee38, pid=1, tid=79
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.13+11 (17.0.13+11) (build 17.0.13+11)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (17.0.13+11, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x75fe38]  G1SATBMarkQueueSet::filter(SATBMarkQueue&)+0x78


Current thread (0x00007fcba28c4190):  JavaThread "xxxxx daemon [_thread_in_Java, id=79, stack(0x00007fcb71400000,0x00007fcb71500000)]

Stack: [0x00007fcb71400000,0x00007fcb71500000],  sp=0x00007fcb714fe068,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x75fe38]  G1SATBMarkQueueSet::filter(SATBMarkQueue&)+0x78
V  [libjvm.so+0xcdcd24]  SATBMarkQueueSet::handle_zero_index(SATBMarkQueue&)+0x24
V  [libjvm.so+0xcdce5b]  SATBMarkQueueSet::enqueue_known_active(SATBMarkQueue&, oopDesc*)+0x3b


[Global flags]
     bool AlwaysPreTouch                           = true                                      {product} {command line}
     intx AutoBoxCacheMax                          = 20000                                  {C2 product} {command line}
     intx CICompilerCount                          = 3                                         {product} {ergonomic}
     uint ConcGCThreads                            = 1                                         {product} {ergonomic}
     bool DisableExplicitGC                        = true                                      {product} {command line}
    ccstr ErrorFile                                = /var/log/kiwi/hs_err_pid_%p.log            {product} {command line}
     uint G1ConcRefinementThreads                  = 4                                         {product} {ergonomic}
     uint G1EagerReclaimRemSetThreshold            = 16                                   {experimental} {ergonomic}
   size_t G1HeapRegionSize                         = 2097152                                   {product} {ergonomic}
    uintx G1ReservePercent                         = 25                                        {product} {command line}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
   size_t InitialHeapSize                          = 4294967296                                {product} {command line}
    uintx InitiatingHeapOccupancyPercent           = 40                                        {product} {command line}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
   size_t MaxHeapSize                              = 4294967296                                {product} {command line}
   size_t MaxNewSize                               = 2575302656                                {product} {ergonomic}
   size_t MinHeapDeltaBytes                        = 2097152                                   {product} {ergonomic}
   size_t MinHeapSize                              = 4294967296                                {product} {command line}
    ccstr NativeMemoryTracking                     = detail                                    {product} {command line}
    uintx NonNMethodCodeHeapSize                   = 5832780                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122912730                              {pd product} {ergonomic}
     bool PrintFlagsFinal                          = true                                      {product} {command line}
    uintx ProfiledCodeHeapSize                     = 122912730                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 251658240                              {pd product} {ergonomic}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
     bool ShowCodeDetailsInExceptionMessages       = true                                   {manageable} {command line}
   size_t SoftMaxHeapSize                          = 4294967296                             {manageable} {ergonomic}
     bool UnlockExperimentalVMOptions              = true                                 {experimental} {command line}
     bool UseCompressedClassPointers               = true                           {product lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                           {product lp64_product} {ergonomic}
     bool UseFastUnorderedTimeStamps               = true                                 {experimental} {ergonomic}
     bool UseG1GC                                  = true                                      {product} {command line}


OS:
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.20.5
PRETTY_NAME="Alpine Linux v3.20"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
uname: Linux 5.10.218-208.862.amzn2.x86_64 #1 SMP Tue Jun 4 16:52:10 UTC 2024 x86_64
OS uptime: 88 days 1:20 hours
libc: glibc 2.40 NPTL 2.40 
rlimit (soft/hard): STACK 10240k/10240k , CORE infinity/infinity , NPROC infinity/infinity , NOFILE 1048576/1048576 , AS infinity/infinity , CPU infinity/infinity , DATA infinity/infinity , FSIZE infinity/infinity , MEMLOCK infinity/infinity
load average: 1.71 1.39 1.31


Environment Variables:
JAVA_HOME=/opt/jdk
PATH=/usr/glibc-compat/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk//bin
LD_LIBRARY_PATH=/usr/glibc-compat/lib/


`
any Idea about this ? I found some issues in https://bugs.openjdk.org/browse/JDK-8233415 , is this belong C2 ? but I have a lot of nodes , only very few nodes have this issues .

**Comment by karianna** [comment]
@violetgo yours is a separate issue, please log a separate bug :-)
