### ISSUE TITLE
Java Runtime Environment

### ISSUE THREAD

**Issue by Leila-GitHub** [adoptium/adoptium-support#892]
## Question 
Greetings, I am trying to run KNIME on a remote server. The KNIME workflow has Python nodes. All nodes execute without any issues except Python nodes. KNIME crashes at Python nodes. Here is the head of log file: 

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007f0422ef1817, pid=38950, tid=39998
JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libGraphMolWrap.so+0xd3a817]  void RDKit::MolPickler::_addRingInfoFromPickle<unsigned char>(std::istream&, RDKit::ROMol*, int, bool)+0x3e7

## Context

Java version: openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

Your operating system and platform: NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"

Any comments and suggestions will be appreciated

**Comment by karianna** [comment]
Please use 17.0.8 and report back.   ALso npte that you supplied two versions of Java (1.8.0_282 - which is also out of date for the 1.8.0 line), so you'll need to check which one you are really using.
