### ISSUE TITLE
Temurin JDK/JRE 11 - jdk-11.0.20.1+1 - Upgrade issue

### ISSUE THREAD

**Issue by metaad** [adoptium/adoptium-support#893]
### Please provide a brief summary of the bug

Hello,

Downloaded and installed - https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi

We are facing issue during upgrade.

Installed the latest version "11.0.20.101" on top of "11.0.20.8" - Both versions co-exist as shown below: 
![Co-exists](https://github.com/adoptium/adoptium-support/assets/106653425/7887c52a-ffc6-4f5d-9ad4-a94d9771e2c1)

 
Tested the following scenarios:
Installed 11.0.20.101 on top of 11.0.20.8 - **CO-EXIST**
Installed 11.0.20.101 on top of 11.0.19.7 - **Upgrades**
Installed 11.0.20.8 on top of 11.0.19.7 - **Upgrades**

Tried the same with x86 as well - https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.20.1_1.msi
Same behavior as x64.
![image](https://github.com/adoptium/adoptium-support/assets/106653425/22da4332-16e9-446d-a3a0-3db374af8e0b)

Could you please help us with this?

Thank you.

### Please provide steps to reproduce where possible

Installed https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20_8.msi with default selection.

On the same account, installed https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi with same default selection.

Both versions co-exist without upgrading to higher version.
![Co-exists](https://github.com/adoptium/adoptium-support/assets/106653425/d4581faa-b3db-4493-844e-ab09e46a65b3)

### Expected Results

It should be upgraded with earlier version like the following:

11.0.20.101 on top of 11.0.19.7 - Upgrades.
11.0.20.8 on top of 11.0.19.7 - Upgrades.

### Actual Results

While installing11.0.20.101 on top of 11.0.20.8 it should upgrade, not CO-EXIST.

### What Java Version are you using?

-

### What is your operating system and platform?

Windows 10

### How did you install Java?

Java is not installed.

### Did it work before?

```Shell
Installed 11.0.20.101 on top of 11.0.19.7 - Upgrades.
Installed 11.0.20.8 on top of 11.0.19.7 - Upgrades.
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
No
```

**Comment by karianna** [comment]
@gdams & @douph1 - Are you able to take a look?  I suspect the exrta point release logic failed somewhere

**Comment by douph1** [comment]
Windows installer don't provide update capabilities for same version and Windows Installer is limited to 3 numbers in versioning so for Windows Installer 
11.0.20.101  = 10.0.20
11.0.20.8 = 10.0.20
No upgrade support

This is a know limitation of Windows Installer and our 4 digit versionning : 
https://adoptium.net/installation/windows/#_upgrade_limitation
