### ISSUE TITLE
Files.copy(InputStream, Path, CopyOption...) can fail with OOM if direct memory is limited

### ISSUE THREAD

**Issue by pwagland** [adoptium/adoptium-support#894]
### Please provide a brief summary of the bug

If DirectMemory has been limited by `-XX:MaxDirectMemorySize`, then copying from (at least) a `ByteArrayInputStream` will fail if the buffer is bigger then `MaxDirectMemorySize`.

### Please provide steps to reproduce where possible

On either Mac or Linux, do the following:

```
echo 'java.nio.file.Files.copy(new java.io.ByteArrayInputStream(new byte[256*1024*1024]), java.nio.file.Path.of("/tmp/aaa"), java.nio.file.StandardCopyOption.REPLACE_EXISTING);' | jshell -R-XX:MaxDirectMemorySize=25M
```

Result:
```
|  Welcome to JShell -- Version 17.0.8
|  For an introduction type: /help intro

jshell> java.nio.file.Files.copy(new java.io.ByteArrayInputStream(new byte[256*1024*1024]), java.nio.file.Path.of("/tmp/aaa"), java.nio.file.StandardCopyOption.REPLACE_EXISTING)|  Exception java.lang.OutOfMemoryError: Cannot reserve 268435456 bytes of direct buffer memory (allocated: 127, limit: 26214400)
|        at Bits.reserveMemory (Bits.java:178)
|        at DirectByteBuffer.<init> (DirectByteBuffer.java:121)
|        at ByteBuffer.allocateDirect (ByteBuffer.java:332)
|        at Util.getTemporaryDirectBuffer (Util.java:243)
|        at IOUtil.write (IOUtil.java:89)
|        at IOUtil.write (IOUtil.java:67)
|        at FileChannelImpl.write (FileChannelImpl.java:288)
|        at Channels.writeFullyImpl (Channels.java:74)
|        at Channels.writeFully (Channels.java:96)
|        at Channels$1.write (Channels.java:171)
|        at ByteArrayInputStream.transferTo (ByteArrayInputStream.java:208)
|        at Files.copy (Files.java:3171)
|        at (#1:1)
```

Doing the following works as expected:
```
echo 'new java.io.ByteArrayInputStream(new byte[256*1024*1024]).transferTo(new java.io.FileOutputStream("/tmp/aaa"));' | jshell -R-XX:MaxDirectMemorySize=25M
```

### Expected Results

I expect `Files.copy` to work, regardless of the restrictions placed on `MaxDirectMemorySize`. Particularly in a docker environment, it can be required to limit `MaxDirectMemorySize` to ensure that the VM is not killed by the OOMK.

### Actual Results

`Files.copy` fails with an OOME.

Note that this isn't strictly a problem of `Files.copy`, but rather of the output stream returned by`Files.newOutputStream`, as evidenced by `echo 'new java.io.ByteArrayInputStream(new byte[256*1024*1024]).transferTo(java.nio.file.Files.newOutputStream(java.nio.file.Path.of("/tmp/aaa")));' | jshell -R-XX:MaxDirectMemorySize=25M`

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)

### What is your operating system and platform?

Note that this fails on all of Java 11 (11.0.18), Java 17 (17.0.8), and Java 20 (openjdk 20.0.2 2023-07-18).

This has been tested on both Mac and Linux.

### How did you install Java?

Java was installed from the appropriate .zip file for Mac and Linux.

### Did it work before?

```Shell
It works with smaller files, but not larger files.
```

### Did you test with the latest update version?

```Shell
Yes. Java 11, 17, and 20.
```

### Did you test with other Java versions?

```Shell
Tested with Java 11, 17 and 20 from adoptium.
Tested with Java 21 RC from jdk.net (OpenJDK Runtime Environment (build 21+35-2513))
```

**Comment by pwagland** [comment]
In this particular code path, the easiest fix is to replace https://github.com/adoptium/jdk/blob/d0be73a78038faf9509623bc4ba71eb4385cd645/src/java.base/share/classes/sun/nio/ch/IOUtil.java#L94 with something like:
```java
            bb = Util.getTemporaryDirectBuffer(Math.min(rem, VM.maxDirectMemory()/2));
```

Since the code outside of this method already loops until the ByteBuffer is full, at least on this code path. Other code paths _should_ also retry, since Channel.write() doesn't guarantee to write all bytes _anyway_.

**Comment by karianna** [comment]
This is by design as the limit has been set.  You can repos this issue to an OpenJDK mailing list (core-libs) if you have a suggested change.

**Comment by pwagland** [comment]
Is it _really_ by design to say that you cannot copy memory buffers of an arbitrary size if you limit `DirectMemorySize`? Why is this limit _only_ applied to internal files, and not to files copied on disk? And why does it depend on the InputStream as to whether or not this will succeed?

**Comment by jerboaa** [comment]
> Is it _really_ by design to say that you cannot copy memory buffers of an arbitrary size if you limit `DirectMemorySize`? Why is this limit _only_ applied to internal files, and not to files copied on disk? And why does it depend on the InputStream as to whether or not this will succeed?

As @karianna mentioned, please raise this issue on [core-libs-dev](https://mail.openjdk.org/mailman/listinfo/core-libs-dev) or better yet [nio-dev](https://mail.openjdk.org/mailman/listinfo/nio-dev). This really is an upstream OpenJDK discussion and best addressed there.

**Comment by pwagland** [comment]
Thanks @jerboaa and @karianna. Mail has been sent: https://mail.openjdk.org/pipermail/nio-dev/2023-September/014766.html

**Comment by pwagland** [comment]
This has been converted into an issue: https://bugs.openjdk.org/browse/JDK-8316156
