### ISSUE TITLE
Runelite client crashing randomly

### ISSUE THREAD

**Issue by numb189** [adoptium/adoptium-support#895]
### Please provide a brief summary of the bug

will be playing the game and the client will crash at random times, i cannot force it to happen so im at a loss. the log is a jvm_crash_pid_2740_r

[jvm_crash_pid_2740_r.log](https://github.com/adoptium/adoptium-support/files/12614382/jvm_crash_pid_2740_r.log)

### Please provide steps to reproduce where possible

i dont know how to reproduce

### Expected Results

client will randomly crash

### Actual Results

i dont know lol

### What Java Version are you using?

version 8 update 381

### What is your operating system and platform?

windows 11,  13th Gen Intel(R) Core(TM) i7-13700K   3.40 GHz, 32.0 GB (31.8 GB usable), 64-bit operating system, x64-based processor

### How did you install Java?

went to the java website and downloaded via java.com

### Did it work before?

```Shell
no idea when this started happening, happens on and off
```

### Did you test with the latest update version?

```Shell
yes
```

**Comment by karianna** [comment]
@numb189 looks like you are using an old version of the Runelite client, can you upgrade to the [1.10.13.1](https://runelite.net/#news) latest and see?
