### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by RameshRajuSagi** [adoptium/adoptium-support#898]
### Please provide a brief summary of the bug

I am getting below error when running Jenkins

======================================================================
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff444fe2b40, pid=14, tid=651
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.20+8 (11.0.20+8) (build 11.0.20+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (11.0.20+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007ff444fe2b40
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/s.jenkins/Apptainer/IMAGES/sept
17/core.14)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
---------------  S U M M A R Y ------------

Command Line: -Duser.home=/var/jenkins_home -Djenkins.install.runSetupWizard=false -Djenkins.model.Jenkins.slaveAgentPort=59522 --illegal-access=deny -Dhudson.lifecycle=hudson.lifecycle.ExitLifecycle /usr/share/jenkins/jenkins.war --httpPort=8642

Host: Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 8 cores, 62G, Debian GNU/Linux 12 (bookworm)
Time: Tue Sep 19 18:19:26 2023 CEST elapsed time: 350.589326 seconds (0d 0h 5m 50s)

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x00007f7ae8300000,0x00007f7ae8400000],  sp=0x00007f7ae83fee98,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007f7b2e436b40

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007f7b2e436b40

Register to memory mapping:

RAX=
[error occurred during error reporting (printing register info), id 0xb, SIGSEGV (0xb) at pc=0x00007f7b2fce72c7]

Registers:
RAX=0x0000000000000001, RBX=0x00007f7ae83ff9f8, RCX=0x0000000000000011, RDX=0x00007f7b2e436b40
RSP=0x00007f7ae83fee98, RBP=0x00007f7b307fdaa8, RSI=0x0000000000000002, RDI=0x00007f7a9805d850
R8 =0x0000000000000007, R9 =0x00007f7a9805a060, R10=0x1a5a69f1fa2b4d99, R11=0x0000000000000246
R12=0x0000000000000000, R13=0x00007f7b307fda88, R14=0x0000000000000004, R15=0x00007f7ae83ffbd8
RIP=0x00007f7b2e436b40, EFLAGS=0x0000000000010202, CSGSFS=0x002b000000000033, ERR=0x0000000000000014
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f7ae83fee98)
0x00007f7ae83fee98:   00007f7b306af361 00007f7ae83feed0
0x00007f7ae83feea8:   00007f7ae83ff6c0 0000000000000000
0x00007f7ae83feeb8:   ffffffffffffff80 0000000000000058
0x00007f7ae83feec8:   00007f7b2ed1e700 00007f7ae8300000 

### Expected Results

It should not crash .

### Actual Results

When I start the Jenkins , it runs for some time, and suddenly crashes. It happens when I edit something in Jenkins.
In some cases even if It is Idle , no edits being done it crashes itself.

### What Java Version are you using?

openjdk version "11.0.19" 2023-04-18 LTS OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS) OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS, mixed mode, sharing)

### What is your operating system and platform?

>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**more /etc/os-release** 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**hostnamectl** 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>

 Static hostname: myjenkinshost
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: abb7dc0517d54654a510fe30999f522e
         Boot ID: 9bbe1724e5ba49ccad55e320fdbd3251
  Virtualization: vmware
Operating System: Red Hat Enterprise Linux 9.2 (Plow)     
     CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
          Kernel: Linux 5.14.0-284.11.1.el9_2.x86_64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware7,1
Firmware Version: VMW71.00V.21100432.B64.2301110304

>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**uname -r**
>>>>>>>>>>>>>>>>>>>>>>>>>>>>

5.14.0-284.11.1.el9_2.x86_64

**Comment by karianna** [comment]
This bug report seems to indicate you're using 11.0.20 and 11.0.19 are they being mixed up?

**Comment by RameshRajuSagi** [comment]
No , they are not mixed, even with RHEL8 I see the same issue

**Comment by karianna** [comment]
Please try the 11.0.21 that is coming out this week and see if that resolves the issue

**Comment by RameshRajuSagi** [comment]
Sure , Thanks

**Comment by karianna** [comment]
@RameshRajuSagi Any luck?
