### ISSUE TITLE
Trying to find a timeline for jdk21 @ eclipse-temurin

### ISSUE THREAD

**Issue by DRoppelt** [adoptium/adoptium-support#899]
## Question

As a temurin user (via containers), I am trying to find a timeline when I can expect to be running 21 with temurin?
I dont expect to find a ready-to-use version the day of GA, but for a way to track progress so that I can introduce 21 in my org once its finished with an idea when that is going to be.

So far tried looking into open/solved issues and/or PRs of these repos

- https://github.com/adoptium/temurin-build
- https://github.com/adoptium/containers
- https://github.com/adoptium/jdk21u (not found, while https://github.com/adoptium/jdk20u exists)

also not here https://adoptium.net/temurin/releases/ 

so far I have only found this tag 
- https://github.com/adoptium/jdk/releases/tag/jdk-21-ga

## Context

Java version: 21 is GA since 19.09.23

Your operating system and platform: Alpine container

**Comment by DRoppelt** [comment]
oh well, just now found what I was looking for.

Took a bit till I landed in https://github.com/adoptium/adoptium and then found tickets relating to 21
- https://github.com/adoptium/adoptium/issues/248
- https://github.com/adoptium/adoptium/issues/249

**Comment by sverhagen** [comment]
I could still see there to be merit to this issue. A FAQ entry explaining a general timeline or philosophy, not even specific to any version or any date, might be useful. To me adoptium#248 is way too much into the weeds (and the target release date there is also not filled out; not to suggest that only a specific date would be satisfactory.

**Comment by DRoppelt** [comment]
Since yesterday there is now also a banner stating that they wait for formal specification tests before releasing

> 25th of September 2023:We are awaiting access to the new Java 21's specification tests before formally releasing Temurin 21

Also, I found following here (although it was hard to spot as the numbers did not stick out from the text all that much)

 https://adoptium.net/support/
 
 > there will be a short delay relative to these dates while we complete our extensive build and test cycles which can take up to three weeks. ... We always prioritise the most popular platforms which will typically appear within a few days of these dates.
