### ISSUE TITLE
adoptopenjdk-8-hotspot not available anymore in Debian APT Repo

### ISSUE THREAD

**Issue by cadirol** [adoptium/adoptium-support#902]
## Question
Today i was not able to find the Package _adoptopenjdk-8-hotspot_ with the following apt Repo.
```
$ cat /etc/apt/sources.list.d/adoptopenjdk.list 
deb [signed-by=/etc/apt/trusted.gpg.d/adoptium.asc] https://packages.adoptium.net/artifactory/deb bullseye main

```

two Weeks ago i was able to install _adoptopenjdk-8-hotspot_ with this APT source.

Did i missed something?

## Context

Java version: 8

Your operating system and platform:

Debian 11 - bullseye - x64

**Comment by karianna** [comment]
adoptopenjdk is no longer supported, you should move to the eclipse temurin binaries as per https://adoptium.net/en-GB/installation/
