### ISSUE TITLE
Installer Packages vs. Compatibility List missmatch

### ISSUE THREAD

**Issue by cadirol** [adoptium/adoptium-support#903]
## Context
From my Point of view, in https://adoptium.net/supported-platforms/ is only Ubuntu Listed as Compatible OS - for DEB Based Operation Systems.  
In https://adoptium.net/installation/linux/ is Debian listed as possible "DEB Based" OS.  
What is correct? Seems to be a mismatch in your website.  
Thank you very much for clarify!

**Comment by jerboaa** [comment]
See: https://adoptium.net/installation/linux/

In particular this section in that doc:
```
See [Supported Platforms](https://adoptium.net/supported-platforms) for a list of our officially supported installers by Linux distribution / version. Other Linux distributions / versions are supported on a best-effort basis.
```
