### ISSUE TITLE
Crash loading up client direwolf20 access violation

### ISSUE THREAD

**Issue by airhawk9** [adoptium/adoptium-support#913]
### Please provide a brief summary of the bug

the game crashes while loading up assets and mods, sometimes without any intervention gets to the main minecraft menu, but only like every 1/10 launches. just updated java, reinstalled graphics driver with ddu for fresh install, and chdsk and scannow all came back no issues. 

### Please provide steps to reproduce where possible

6gb allocated ram launching windowed 1600x900. launch direwolf20 (had the same issue on the 1.0.1 version as well as 1.1.0) . signed in with microsoft account. not logged into overwolf or any ftb accounts. browse and get the direwolf mod, try to run it, and client will close after 5-10 seconds on average, but has survived 30s and crashed at the minecraft menu.

### Expected Results

game opens

### Actual Results

game crashes. error given:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc365d653a, pid=5996, tid=23828

### What Java Version are you using?

build 1.8.0_381-b09

### What is your operating system and platform?

win 10 64bit rx6900 xt and i913900k. ssd boot and ssd storage drives

### Did it work before?

```Shell
no but it has launched to menu, no gameplay was attempted at the time
```

### Relevant log output

```Shell
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# V [jvm.dll+0x30656d]
# Problematic frame:
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
#
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc3506656d, pid=17724, tid=20096
#
# A fatal error has been detected by the Java Runtime Environment:
#
2023-10-10 20:06:12,708 main WARN Advanced terminal features are not available in this environment
```

**Comment by airhawk9** [comment]
does not help im trying to launch modded minecraft... vanilla launcher wouldnt fix anything

**Comment by VT-14** [comment]
The bot may be improved by noting which version of Java each Minecraft version is looking for.

* I think older versions of Minecraft used Java 6, but likely work fine on Java 8.
* Minecraft 1.12-1.16 used Java 8 (1.8).
* Minecraft 1.17 used Java 16.
* Minecraft 1.18 to present use Java 17.

From a Reddit post I know airhawk is using a Minecraft 1.20 modpack, and their issue report says they are using a 1.8 (Java 8) build of Adoptium.  It's a setup error with their 3rd party launcher (FeedTheBeast), not an issue with Adoptium.
