### ISSUE TITLE
SSL ceritifcate expired when download packages from Adoptium.net

### ISSUE THREAD

**Issue by xiwang370** [adoptium/adoptium-support#916]
### Please provide a brief summary of the bug

Hi All, I am trying to install Java on ec2 instances using flintrock, however, I am getting the below error while trying to download temurin jdk (temurin java 11) from https://packages.adoptium.net/artifactory/rpm/centos/8/.  The page shows 404 error when clicked on the link, not sure if there has been any change in path in the last week. Any help is appreciated! Thanks

![274014890-7163f29e-08e5-47b9-9bdb-134066467d68](https://github.com/adoptium/adoptium-support/assets/64625138/bd37fe62-13b6-48f8-9d44-9302ac4b7963)

### Please provide steps to reproduce where possible

I'm just using flintrock to connect ec2.

pip install flintrock 
flintrock launch <ec2 name>
then the it threw a problem like this. It looks like there is something changed from adoptium packages.

### Expected Results

it should successfully download java from adoptium through the steps.

### Actual Results

it threw me an error listed above. Indicating ssl certificate expired  from https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64/repodata/repomd.xml

### What Java Version are you using?

java --11

### What is your operating system and platform?

mac os 14.0

### How did you install Java?

through flintrock, connecting to adotpium.net packages (rpm)

### Did it work before?

```Shell
yes, it worked fine a week ago but then it suddenly stop working since last week.
```

**Comment by gdams** [comment]
@xiwang370 are you able to share the output of the following command:

```
 wget --server-response https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64/repodata/repomd.xml
```

**Comment by xiwang370** [comment]
<img width="1002" alt="image" src="https://github.com/adoptium/adoptium-support/assets/64625138/afcc5011-1ab3-4af4-9f49-808ae0e80a62">

**Comment by gdams** [comment]
@xiwang370 is that on the same machine? The SSL cert looks perfectly valid in that wget request

**Comment by xiwang370** [comment]
yes, it's the same machine, I just tried again and it still threw the same errors to me.

<img width="898" alt="image" src="https://github.com/adoptium/adoptium-support/assets/64625138/bb6d594c-2da3-4746-8900-9dead8bdad39">

**Comment by gdams** [comment]
@xiwang370 let's try ruling out curl (as that's shown in your error code):

```
curl -vvvv https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64/repodata/repomd.xml
```

**Comment by gdams** [comment]
Also can I see the output of:

```
echo | openssl s_client -showcerts -servername adoptium -connect packages.adoptium.net:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

**Comment by xiwang370** [comment]
hi i have run both of the coding line you asked.




(base) xi.wang@DAT-00405-XI-W ~ % echo | openssl s_client -showcerts -servername adoptium -connect packages.adoptium.net:443 2>/dev/null | openssl x509 -inform pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            da:b0:ab:9b:c4:6c:3e:61:c6:00:70:7d:bc:49:e7:1e:d9:3c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Certainly, CN = Certainly Intermediate R1
        Validity
            Not Before: Sep 29 14:45:15 2023 GMT
            Not After : Oct 29 14:45:14 2023 GMT
        Subject: CN = s.sni-810-default.ssl.fastly.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ad:e9:b8:9a:62:cf:3a:d6:7c:20:83:ae:ee:64:
                    07:53:02:3e:b3:01:62:0e:73:77:04:3e:be:42:be:
                    8f:83:09:40:86:7c:d6:33:71:3c:70:2f:8b:9e:2a:
                    8d:a5:86:b6:bc:fd:80:fe:e7:b6:a2:e5:7f:66:a9:
                    4f:b7:a1:32:5d:ce:c2:62:fc:19:6c:51:cd:1f:ba:
                    da:9c:4c:94:ab:6c:94:d0:e8:86:8c:5c:b1:f6:f4:
                    92:cb:82:7a:73:74:f9:a2:88:2b:9b:89:0f:ff:0a:
                    f6:32:bb:ad:f6:85:5e:97:5c:80:95:e1:b7:14:61:
                    2b:e1:e4:c8:f9:be:fe:d4:0e:c3:71:6e:f0:56:ac:
                    a3:75:77:46:c3:94:e1:4c:37:ce:0a:a8:f6:48:ca:
                    c9:a1:91:10:6e:fb:b6:20:4d:a5:2e:71:9b:6a:50:
                    38:56:b3:8f:71:ec:f3:7f:e9:5c:f9:ef:8b:e5:48:
                    4e:e1:14:b9:b4:13:3e:aa:28:9a:5d:82:a7:36:4b:
                    e1:d2:c7:7c:a1:59:29:79:e7:84:01:76:79:a2:86:
                    52:18:a2:51:32:da:b6:93:d6:7f:9b:09:e6:11:12:
                    a5:f3:0f:f8:48:22:ba:1d:23:74:63:1d:62:0c:aa:
                    13:93:9f:db:a4:59:aa:67:67:a0:19:a6:da:10:ec:
                    7d:89
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                C3:D0:B4:F0:69:4C:28:E5:A3:58:07:1F:F6:4E:E4:5D:FB:09:F2:2C
            X509v3 Authority Key Identifier: 
                keyid:BD:97:9D:DF:A1:D8:1B:25:99:E3:0C:04:06:89:64:12:D7:65:24:C7

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-r1.certainly.com
                CA Issuers - URI:http://int-r1.certainly.com

            X509v3 Subject Alternative Name: 
                DNS:s.sni-810-default.ssl.fastly.net
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1

            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : AD:F7:BE:FA:7C:FF:10:C8:8B:9D:3D:9C:1E:3E:18:6A:
                                B4:67:29:5D:CF:B1:0C:24:CA:85:86:34:EB:DC:82:8A
                    Timestamp : Sep 29 15:45:15.487 2023 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:43:DA:24:37:52:37:1E:FF:EE:BD:20:A2:
                                8B:BA:D0:0F:A6:AB:9B:D6:87:86:49:00:13:A0:BB:88:
                                A5:65:71:8C:02:21:00:AC:8C:50:8C:DA:2D:2A:20:CC:
                                12:36:4A:60:A9:6A:80:32:63:DF:63:C7:8D:F8:A5:9A:
                                81:3E:8A:71:06:19:3B
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 55:81:D4:C2:16:90:36:01:4A:EA:0B:9B:57:3C:53:F0:
                                C0:E4:38:78:70:25:08:17:2F:A3:AA:1D:07:13:D3:0C
                    Timestamp : Sep 29 15:45:15.680 2023 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:46:02:21:00:82:1C:CE:32:13:03:DA:33:57:61:09:
                                B6:74:94:75:47:65:BA:55:21:66:95:25:8D:26:4D:5C:
                                7C:4B:2E:9C:4C:02:21:00:8E:3D:D5:80:54:BE:D7:2F:
                                C7:F5:14:F6:72:EC:65:D3:AF:04:BA:DD:77:F2:F7:69:
                                77:E9:DC:5B:0B:E7:A6:F7
    Signature Algorithm: sha256WithRSAEncryption
         08:f2:e5:a6:60:0f:80:51:9d:91:dd:f4:69:cc:85:8f:52:25:
         8b:f7:f0:2e:00:ed:d1:b2:8f:23:22:4c:ff:59:3f:94:f7:a4:
         51:3e:1c:c8:d1:b1:13:56:0e:86:ea:7f:45:91:a8:5a:69:f6:
         1e:b8:34:23:51:a5:86:f9:ef:65:09:ee:2d:eb:cf:bc:c9:18:
         b7:87:ac:2c:f6:cd:fa:c8:d8:e2:c0:93:55:4e:1c:db:43:34:
         95:3f:a9:c3:8b:ba:39:a8:d4:3c:9c:22:58:69:f4:2a:91:d5:
         da:53:00:83:71:85:56:5a:93:53:c0:8e:92:07:48:3f:48:9c:
         6f:da:2b:01:03:20:04:83:d5:7d:0e:fb:19:04:48:e0:08:11:
         5c:28:44:56:a5:88:c1:0e:03:e3:7f:a8:12:f7:97:2b:20:7b:
         60:99:e4:e7:0f:e3:45:a0:c4:ea:2c:40:ef:97:e7:56:6d:46:
         19:d4:72:dd:aa:7a:84:cf:a2:f8:e5:09:b2:74:fd:56:3f:92:
         a2:c1:f9:9e:60:83:eb:fc:3f:b2:51:1a:85:08:9a:ca:94:2f:
         56:0e:82:c6:51:e5:7a:ec:0b:ef:ae:8b:f4:fb:b4:46:a8:55:
         b3:c4:f3:a0:06:83:6d:8e:ed:14:f0:10:e7:3e:94:b1:1f:da:
         41:92:b2:eb

**Comment by gdams** [comment]
okay, no issues there. @xiwang370 can you also run this one last command:

```
openssl s_client -connect packages.adoptium.net:443 -showcerts
```

**Comment by xiwang370** [comment]
do i need to type anything or press anything now?

(base) xi.wang@DAT-00405-XI-W ~ % openssl s_client -connect packages.adoptium.net:443 -showcerts
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = packages.adoptium.net
verify return:1
---
Certificate chain
 0 s:CN = packages.adoptium.net
   i:C = US, O = Let's Encrypt, CN = R3
-----BEGIN CERTIFICATE-----
MIIE+DCCA+CgAwIBAgISBOzM1gw+LQR8tgrF5jkgzyDgMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzEwMDIxMTIyMThaFw0yMzEyMzExMTIyMTdaMCAxHjAcBgNVBAMT
FXBhY2thZ2VzLmFkb3B0aXVtLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAL5FrHScAm1o0Mk0lBMQqVHhab9mTRcKx/8Ccv9lNvKeGp2C+TlA+Dwi
O0q14FsOuldrv6sB6PTZurrS2ebQ2dyu6RDYd7v5rxFyhtPf8Phv+XjdHSHv5BES
UWVL1+JFxOSG4pCCMBHiw9ZQYANgWzQeBCzykn6ORsCZ/EJ1pFIWTmUbqeW9Q6tT
1BRuh0u/IpdIKYNY+Hosk/jdQihErQpRebjKaE4X4DAraSGewulUyULz95ZRFEQr
ZfG/jgz1ks7m08NYlF7GPR+Phoz9PW4oeTTwCsnpXXlBYF/Ao2pzPdxou4OIVGlJ
Oa+ujyh3bz/Y7hytYAUIhAimbZhqh3ECAwEAAaOCAhgwggIUMA4GA1UdDwEB/wQE
AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
ADAdBgNVHQ4EFgQUgxj3sCGXJGKCf7gBOgklsM7VXhUwHwYDVR0jBBgwFoAUFC6z
F7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVo
dHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxl
bmNyLm9yZy8wIAYDVR0RBBkwF4IVcGFja2FnZXMuYWRvcHRpdW0ubmV0MBMGA1Ud
IAQMMAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYAtz77JN+c
Tbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkAAAGK8FbcKgAABAMARzBFAiEAvTJV
Z/rNhNCZdpzSfnGEXPJU67bCrDPZCtJ1db6iCdkCIGbD0PZRGvQCQj9lw1dQHkt2
T2OPpQkpXctfG4EMPiiVAHcAejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS
61IAAAGK8FbcOwAABAMASDBGAiEAkV50AMwsyKnVtdc+1L1HAlAw2CedElH+Om9F
B5CuCnwCIQDf8yGKbOolsTKsar3naD8OOsojd+lQXh4j0aWEhZViXTANBgkqhkiG
9w0BAQsFAAOCAQEAXKUgImwKFg0oZBfGOvbUmjBOJaqxZnVGGE19OH8V4FrsMpaL
bFKS2uVMFO6/U1NSzC8av3abbLjSXh9JpQO9ioHrd9KkKLDtcx8yMJm6NDkmiKq2
WraD4yuZ3rNIfZMK0oISqa0cu7/XS1sZTUTjMKSbgO+wbeV+/g76x+hy06WarUCd
FTTuDCF21NydTL4cLEtbN/tFmyL76SRt1FCSG5bUutqR8U0JT9DW5n4ZKrg1RFyn
oSrW+Ybp5uxDIL03/PbPWVlNV5MAFdBvHQvs7JQglkZqVMRPTbmO03V+Y7/8VoUR
hxWYxDFhL8jdAuk98F7fqQY0KUaVN51yQQha7Q==
-----END CERTIFICATE-----
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----
---
Server certificate
subject=CN = packages.adoptium.net

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4532 bytes and written 403 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BC51D8891951F2B97F39F3370EE33E4D9069A80A76DE910F5E1AF818F001071B
    Session-ID-ctx: 
    Resumption PSK: B83CC062E4F4656FD991B65857B4924E74C07F1479FFBC2BE19825C5A7B16FDA8AD48D9A8954B412C7F585FC538AD701
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 3600 (seconds)
    TLS session ticket:
    0000 - 98 94 ef 0b ad 62 65 89-f0 5b 1b 37 90 42 36 af   .....be..[.7.B6.
    0010 - ae 35 23 10 ba c4 fc 3e-f1 6f df 0a 69 e0 71 66   .5#....>.o..i.qf
    0020 - 58 bf 99 ab 7c 5f 99 52-4c bb 18 67 ae 6c c6 ff   X...|_.RL..g.l..
    0030 - 69 cf 9a e6 c5 74 f4 15-2a 50 de e2 c7 aa e2 8f   i....t..*P......
    0040 - 77 61 3c 33 45 7b d5 34-ec 33 f1 10 bb e4 ed 5e   wa<3E{.4.3.....^
    0050 - ac c0 82 d3 22 8d 2c a7-75 82 bf 4f d9 53 b4 fe   ....".,.u..O.S..
    0060 - 3d fe 44 7d de 3f 7c db-a7 fb ce d5 b7 52 3b 73   =.D}.?|......R;s
    0070 - b3 ea 57 71 51 35 22 3f-0b 8e 0e 29 bd f7 65 29   ..WqQ5"?...)..e)
    0080 - ff ce 21 c4 80 cf f5 c1-b7 f0 50 c4 ef 80 bb 85   ..!.......P.....
    0090 - bb 84 33 76 3a f3 e1 e0-88 66 06 96 f8 20 36 53   ..3v:....f... 6S
    00a0 - 7e 5d 65 73 36 47 7a cd-85 95 ab 3f 34 54 27 d2   ~]es6Gz....?4T'.

    Start Time: 1697142747
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

**Comment by gdams** [comment]
@xiwang370 you've run the correct command but I was expecting to see the expiry date of the certificate in that output which I don't see in yours. Here's mine for example: (note the `v:NotBefore: Oct  2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT` block)

```
➜  ~ openssl s_client -connect packages.adoptium.net:443 -showcerts
CONNECTED(00000007)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = packages.adoptium.net
verify return:1
---
Certificate chain
 0 s:CN = packages.adoptium.net
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Oct  2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT
-----BEGIN CERTIFICATE-----
```

**Comment by xiwang370** [comment]
that's weird. I used the same code but there is no line showing of this  v:NotBefore: Oct  2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT..

I only see two lines here : Certificate chain
 0 s:CN = packages.adoptium.net
   i:C = US, O = Let's Encrypt, CN = R3

**Comment by gdams** [comment]
> that's weird. I used the same code but there is no line showing of this v:NotBefore: Oct 2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT..
> 
> I only see two lines here : Certificate chain 0 s:CN = packages.adoptium.net i:C = US, O = Let's Encrypt, CN = R3

Can you check that your ca-certificates are up to date (just to rule things out)

```
sudo yum update ca-certificates
```

**Comment by wesleycheungSikka** [comment]
Hi George, I actually encountered the same issue and got the follow result from the code you provided.
`CONNECTED(00000006)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = packages.adoptium.net
verify return:1
---
Certificate chain
 0 s:CN = packages.adoptium.net
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Oct  2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT`

**Comment by gdams** [comment]
> Hi George, I actually encountered the same issue and got the follow result from the code you provided.
> 
> ## `CONNECTED(00000006)
> depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
> verify return:1
> depth=1 C = US, O = Let's Encrypt, CN = R3
> verify return:1
> depth=0 CN = packages.adoptium.net
> verify return:1
> Certificate chain 0 s:CN = packages.adoptium.net i:C = US, O = Let's Encrypt, CN = R3 a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256 v:NotBefore: Oct 2 11:22:18 2023 GMT; NotAfter: Dec 31 11:22:17 2023 GMT`

@wesleycheungSikka that's interesting, your output does show that the SSL certificate is valid so I'm a little puzzled

**Comment by wesleycheungSikka** [comment]
yeah i had the same issue as xi.
```
Existing lock /var/run/yum.pid: another copy is running as pid 3419.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 181 M RSS (397 MB VSZ)
    Started: Thu Oct 12 20:47:54 2023 - 00:03 ago
    State  : Running, pid: 3419
https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"
Trying other mirror.


 One of the configured repositories failed (Adoptium),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=Adoptium ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable Adoptium
        or
            subscription-manager repos --disable=Adoptium

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=Adoptium.skip_if_unavailable=true

failure: repodata/repomd.xml from Adoptium: [Errno 256] No more mirrors to try.
https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"
```
`sudo yum update ca-certificates` seems to not work on my end with the error command not found.

**Comment by xiwang370** [comment]
yum command not found so i used brew upgrade ca-certifications. it gave me this output : 
% brew upgrade ca-certificates
Warning: ca-certificates 2023-08-22 already installed

**Comment by gdams** [comment]
> yum command not found so i used brew upgrade ca-certifications. it gave me this output : % brew upgrade ca-certificates Warning: ca-certificates 2023-08-22 already installed

I don't understand? Have you been running these commands on the Centos 8 machine running in AWS or your MacBook? You should be able to run `yum update ca-certificates` on the Centos VM. Can you try again?

**Comment by wesleycheungSikka** [comment]
I am running on my MacBook and using the open source flintrock package.

**Comment by gdams** [comment]
> I am running on my MacBook and using the open source flintrock package.

Hmm this is going to be harder to diagnose then, I was under the impression that the commands were being run on the Centos VM that flintrock generates. There could be a whole factor of reasons that this is no longer working. I can see that https://github.com/nchammas/flintrock/issues/363 has been raised to discuss this on the flintrock side.

**Comment by wesleycheungSikka** [comment]
I rmb I can do yum update when ec2 instances are successfully spinned up, like after the launching process.

**Comment by gdams** [comment]
> I rmb I can do yum update when ec2 instances are successfully spinned up, like after the launching process.

Yes please, can you try updating the ca certificates and then run `yum install temurin-11-jdk`

**Comment by wesleycheungSikka** [comment]
Thanks George!!!!! Updated the ca certificates version in the source code and it worked!

**Comment by wesleycheungSikka** [comment]
For some reason, when i spin up two clusters, it worked perfectly fine. But when there's more, the same issue arises.

**Comment by Xisikka** [comment]
hi, 

i've read the post from flintrock. i used the author's ami and the connection issue get resolved. I will recheck my private ami set up and get back to you.

**Comment by gdams** [comment]
Great thanks, I'm going to close this for now given that the authors standard AL ami is working
