### ISSUE TITLE
Reinstate support for ppc64le?

### ISSUE THREAD

**Issue by h-vetinari** [adoptium/adoptium-support#917]
Until java 19, temurin [provided](https://github.com/adoptium/temurin19-binaries/releases) builds for ppc64le, e.g. `OpenJDK19U-jdk_ppc64le_linux_hotspot_19.0.2_7.tar.gz`.

These builds are not present anymore for java 20 & 21, and I couldn't find something about this on the issue tracker here.

I just wanted to ask if support for this architecture has been dropped, or whether that's planned to be re-added at some point?

**Comment by karianna** [comment]
https://adoptium.net/en-GB/supported-platforms/ lists our supported platforms and yes unfortunately PPC-LE was dropped from Java 20 onwards.

**Comment by smlambert** [comment]
ppc64le was paused due to not passing some compliance tests.  With the latest JDK21 release, we are re-testing and looking to see if we can reinstate it as a platform we will be able to release.

**Comment by h-vetinari** [comment]
Thanks for the super-quick response!

**Comment by sxa** [comment]
JDK21 builds of Temurin for Linux/ppc64le are now available.
