### ISSUE TITLE
Termurin OpenJDK 20 and 21 require GLIBC_2.14

### ISSUE THREAD

**Issue by rainerjung** [adoptium/adoptium-support#918]
### Please provide a brief summary of the bug

Termurin OpenJDK 20 and 21 require GLIBC_2.14. This requirement did not exist until OpenJDK 19. It also does not exists for OpenJDK 20 and 21 builds from other vendors (Oracle, RedHat, Zulu, Amazon, OpenJDK Upstream).

Due to this requirement, Termurin 21 can not be used on the old Linux distributions SLES 11 and RHEL 6.

If this is intended, it should be documented in the release notes.

### Please provide steps to reproduce where possible

/path/to/termurin21/bin/java -version

### Expected Results

openjdk version "21" 2023-09-19 LTS
OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)

### Actual Results

/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /path/to/termurin21/bin/../lib/libjli.so)

### What Java Version are you using?

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS) OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)

### What is your operating system and platform?

SuSE Linux Enterprise SLES 11
and
RedHat Enterprise Linux RHEL 6

### How did you install Java?

Download and unpack tarball.

### Did it work before?

```Shell
Never for JDK 20 and 21 on these platforms.
```

### Did you test with the latest update version?

```Shell
yes.
```

### Did you test with other Java versions?

```Shell
Yes, works until JDK 19 and also with JDK 20+21 from (all) other vendors.
```

### Relevant log output

```Shell
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /path/to/termurin21/bin/../lib/libjli.so)
```

**Comment by rainerjung** [comment]
The symbol that needs the higher library version is "memcpy@GLIBC_2.14". This seems to be a widely known problem. For reference see e.g. https://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html

**Comment by karianna** [comment]
Please see https://adoptium.net/en-GB/supported-platforms/ with the minimum support glibc details at the footer of the table.
