### ISSUE TITLE
temurin21-binaries tag name changes

### ISSUE THREAD

**Issue by cvirtucio** [adoptium/adoptium-support#922]
## Question
What is the versioning scheme for `temurin-binaries` repositories, moving forward?

## Context
We have automation that uses the `temurin-binaries` repositories' tags to look up the latest versions for each major. In the past, we've relied on the standard semver convention followed by repositories such as [temurin20-binaries](https://github.com/adoptium/temurin20-binaries). This appears to have changed with [temurin21-binaries](https://github.com/adoptium/temurin21-binaries): it now follows the convention of `<major>+<build no>`, despite Oracle builds maintaining semver.

Is this the new version scheme for all major versions of temurin moving forward?

**Comment by karianna** [comment]
Please use our official API at https://api.adoptium.net

**Comment by cvirtucio** [comment]
Looks like the release tags were fixed today: https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12

<img width="1528" alt="Screenshot 2023-10-25 at 1 09 06 PM" src="https://github.com/adoptium/adoptium-support/assets/108751461/34d60a1b-5d85-4d63-ac2d-1b4a71cac08a">
