### ISSUE TITLE
When i execute on Ubuntu 20.04.6 :  sudo wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - i get connection refuse.

### ISSUE THREAD

**Issue by RaminHeidari** [adoptium/adoptium-support#924]
### Please provide a brief summary of the bug

When i execute on Ubuntu 20.04.6 :
 sudo wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add -
i get connection refuse.

--2023-10-23 14:01:53-- https://packages.adoptium.net/artifactory/api/gpg/key/public
Looking up packages.adoptium.net (packages.adoptium.net)... 151.101.3.42, 151.101.67.42, 151.101.131.42, ...
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.3.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.67.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.131.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.195.42|:443 … failed: Connection refused.

Then i execute : sudo apt-get install temurin-21-jdk

I get below message:
Reading package lists… Done
Builds dependency trees
Reading state information… Done
E: Could not find package temurin-21-jdk

### Expected Results

Download and install java 21

### Actual Results

2023-10-23 14:01:53-- https://packages.adoptium.net/artifactory/api/gpg/key/public
Looking up packages.adoptium.net (packages.adoptium.net)... 151.101.3.42, 151.101.67.42, 151.101.131.42, ...
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.3.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.67.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.131.42|:443 … failed: Connection refused.
Connecting to packages.adoptium.net (packages.adoptium.net)|151.101.195.42|:443 … failed: Connection refused.

Then i execute : sudo apt-get install temurin-21-jdk

I get below message:
Reading package lists… Done
Builds dependency trees
Reading state information… Done
E: Could not find package temurin-21-jdk

### What Java Version are you using?

Java 17 wants to install java 21

### What is your operating system and platform?

Ubuntu 20.04.6

**Comment by karianna** [comment]
@RaminHeidari  Can you update your ca-certificates package and try again?

**Comment by RaminHeidari** [comment]
@karianna : I did . Still get same error

**Comment by karianna** [comment]
Hi folks, we're aware of the issue and are investigating with our CDN and package repo providers.

**Comment by karianna** [comment]
We've fixed two underlying causes and this appears to be resolved.  Please do let us know if you still have issues.

**Comment by RaminHeidari** [comment]
@karianna I tested it and receiving same errors

**Comment by karianna** [comment]
@RaminHeidari We'e had reports that folks on VPNs have struggled, are you able to test again (with VPN off if you do have one)
