### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment at the time of eclipse installation

### ISSUE THREAD

**Issue by OmkarPatwardhan** [adoptium/adoptium-support#927]
### Please provide a brief summary of the bug

at the time of instalation of eclipse a notepad is created showing A fatal error has been detected by the Java Runtime Environment
[hs_err_pid7924.log](https://github.com/adoptium/adoptium-support/files/13114042/hs_err_pid7924.log)

### Expected Results

It should be installed clearly

### Actual Results

eclipse forcefully comes out of the application by providing error notepad file
[hs_err_pid7924.log](https://github.com/adoptium/adoptium-support/files/13114062/hs_err_pid7924.log)

### What Java Version are you using?

jdk-18.0.2.1

### What is your operating system and platform?

Windows 11 version 22H2 on X86_64

### How did you install Java?

binary archive zip

### Did it work before?

```Shell
No
```

### Did you test with the latest update version?

```Shell
No
```

### Did you test with other Java versions?

```Shell
No
```

**Comment by karianna** [comment]
@OmkarPatwardhan  18.0.2 is no longer supported.  Are you able to update to Java 21?

**Comment by OmkarPatwardhan** [comment]
@karianna As per your suggestion i have updated java 21 but it is not working same notepad file of fatal error of java Runtime Environment has produced

**Comment by karianna** [comment]
Can you upload that latest error log?

**Comment by OmkarPatwardhan** [comment]
@karianna this is my latest error log 
[hs_err_pid12732.log](https://github.com/adoptium/adoptium-support/files/13208666/hs_err_pid12732.log)
kindly go through it

**Comment by karianna** [comment]
@OmkarPatwardhan  Your log file is showing Java 17.0.8.1, can you try 17.0.9 and send the log in for that?

**Comment by OmkarPatwardhan** [comment]
[hs_err_pid12164.log](https://github.com/adoptium/adoptium-support/files/13589604/hs_err_pid12164.log)
This id the log fille with java 17.0.09 . PLease help !

**Comment by karianna** [comment]
Are you on the very latest version of the Eclipse IDE?  The error below is an internal native lib that the IDE is calling.  I can only recommend you upgrade to the latest IDE and Windows and Windows graphics drivers.  If it still persists then contact the Eclipse IDE folks

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.eclipse.swt.internal.ole.win32.COM.VtblCall(IJJI[J)I+0
j  org.eclipse.swt.internal.ole.win32.IDispatch.GetTypeInfo(II[J)I+9
j  org.eclipse.swt.ole.win32.OleAutomation.<init>(Lorg/eclipse/swt/internal/ole/win32/IDispatch;)V+40
j  org.eclipse.swt.ole.win32.Variant.getAutomation()Lorg/eclipse/swt/ole/win32/OleAutomation;+31
j  org.eclipse.swt.browser.IE.execute(Ljava/lang/String;)Z+171
j  org.eclipse.swt.browser.IE.lambda$5(Lorg/eclipse/swt/widgets/Event;)V+128
j  org.eclipse.swt.browser.IE$$Lambda$234+0x000000010056b388.handleEvent(Lorg/eclipse/swt/widgets/Event;)V+5
j  org.eclipse.swt.widgets.EventTable.sendEvent(Lorg/eclipse/swt/widgets/Event;)V+243
j  org.eclipse.swt.widgets.Display.sendEvent(Lorg/eclipse/swt/widgets/EventTable;Lorg/eclipse/swt/widgets/Event;)V+12
j  org.eclipse.swt.widgets.Widget.sendEvent(Lorg/eclipse/swt/widgets/Event;)V+26
j  org.eclipse.swt.widgets.Widget.sendEvent(ILorg/eclipse/swt/widgets/Event;Z)V+73
j  org.eclipse.swt.widgets.Widget.sendEvent(I)V+4
j  org.eclipse.swt.widgets.Widget.release(Z)V+39
j  org.eclipse.swt.widgets.Composite.releaseChildren(Z)V+55
j  org.eclipse.swt.widgets.Canvas.releaseChildren(Z)V+42
j  org.eclipse.swt.widgets.Decorations.releaseChildren(Z)V+22
j  org.eclipse.swt.widgets.Shell.releaseChildren(Z)V+104
j  org.eclipse.swt.widgets.Widget.release(Z)V+65
j  org.eclipse.swt.widgets.Widget.dispose()V+23
j  org.eclipse.swt.widgets.Decorations.dispose()V+52
j  org.eclipse.oomph.ui.UIUtil$2.run()V+61
j  org.eclipse.oomph.ui.UIUtil.syncExec(Ljava/lang/Runnable;)V+16
j  org.eclipse.oomph.ui.UIUtil.isBrowserAvailable()Z+13
j  org.eclipse.oomph.setup.internal.installer.SimpleProductPage.createContent(Lorg/eclipse/swt/widgets/Composite;)V+256
j  org.eclipse.oomph.setup.internal.installer.SimpleInstallerPage.<init>(Lorg/eclipse/swt/widgets/Composite;Lorg/eclipse/oomph/setup/internal/installer/SimpleInstallerDialog;Z)V+111
j  org.eclipse.oomph.setup.internal.installer.SimpleProductPage.<init>(Lorg/eclipse/swt/widgets/Composite;Lorg/eclipse/oomph/setup/internal/installer/SimpleInstallerDialog;Lorg/eclipse/oomph/setup/ui/wizards/SetupWizard$SelectionMemento;)V+4
j  org.eclipse.oomph.setup.internal.installer.SimpleInstallerDialog.createUI(Lorg/eclipse/swt/widgets/Composite;)V+341
j  org.eclipse.oomph.setup.internal.installer.AbstractSimpleDialog.show()I+5
j  org.eclipse.oomph.setup.internal.installer.InstallerApplication.run(Lorg/eclipse/equinox/app/IApplicationContext;)Ljava/lang/Integer;+749
j  org.eclipse.oomph.setup.internal.installer.InstallerApplication.start(Lorg/eclipse/equinox/app/IApplicationContext;)Ljava/lang/Object;+2
j  org.eclipse.equinox.internal.app.EclipseAppHandle.run(Ljava/lang/Object;)Ljava/lang/Object;+138
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ljava/lang/Object;)Ljava/lang/Object;+85
j  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Ljava/lang/Object;)Ljava/lang/Object;+79
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run(Ljava/lang/Object;)Ljava/lang/Object;+99
j  org.eclipse.core.runtime.adaptor.EclipseStarter.run([Ljava/lang/String;Ljava/lang/Runnable;)Ljava/lang/Object;+132
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.9
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.9
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.9
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.9
j  org.eclipse.equinox.launcher.Main.invokeFramework([Ljava/lang/String;[Ljava/net/URL;)V+201
j  org.eclipse.equinox.launcher.Main.basicRun([Ljava/lang/String;)V+159
j  org.eclipse.equinox.launcher.Main.run([Ljava/lang/String;)I+4
v  ~StubRoutines::call_stub
