### ISSUE TITLE
I am not able run java applet with Adoptium Open JDK8 , Applet was working fine with Oracle JRE by adding my site address in exception.sites list. How can I able to run java applets with OpenJDK 8,  Please clarify

### ISSUE THREAD

**Issue by rajeshp808** [adoptium/adoptium-support#928]
## Context

Java version: Eclipse Temurin JDK 8u392-b08-x86 

I am not able run java applet with Adoptium Open JDK8 , Applet was working fine with Oracle JRE by adding my site address in exception.sites list. How can I able to run java applets with OpenJDK 8,  Please clarify.

Paste the entire output of java -version.
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_392-b08)
OpenJDK Client VM (Temurin)(build 25.392-b08, mixed mode)

Your operating system and platform: Window 10 64 bit

**Comment by karianna** [comment]
See https://adoptium.net/docs/migration/ for guidance
