### ISSUE TITLE
Secured Memory Accessed by JVM

### ISSUE THREAD

**Issue by Anu790j** [adoptium/adoptium-support#929]
### Please provide a brief summary of the bug

Access of secured memory address by the JVM

### Please provide steps to reproduce where possible

`import java.io.*;
import java.util.*;

public class A {
    public static void main(String srgs[]){
        try{
            System.out.println("I am running   ");
            File f = new File("C:\\Users\\coer\\Desktop\\ReaderWriter/Reader.txt");
            File f1 =  new File("C:\\Users\\coer\\Desktop\\ReaderWriter/B.txt");

            FileWriter fw  = new FileWriter(f);   //writer object for reader.txt
            FileReader fr = new FileReader(f);    //Reader object for reader.txt
            FileWriter fw1 = new FileWriter(f1);  //Writer object for B.txt

            String data;                          //Taking input from user
            Scanner sc = new Scanner(System.in);
            System.out.println("Enter the data you want to enter  ");
            data = sc.nextLine();

            fw.write(data);                      //Writing user input data to Reader.txt
            fw.close();                          //Closing write stream because if write and read stream cannot work on same file at same time

            //fetching data from reader.txt

            int ch;
            while((ch=fr.read()) != -1){
                char c = (char)ch;
                fw1.write(c);
            }
            
            fr.close();
            fw1.close();
            sc.close();
        }

        catch(Exception e){
            System.out.println("Exception  "+ e);
        }
    }
}`

### Expected Results

Hi there !! How are you I am fine

### Actual Results

Program executed successfully ,but generated a fatal error after execution.

### What Java Version are you using?

java 19 2022-09-20 Java(TM) SE Runtime Environment (build 19+36-2238) Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)

### What is your operating system and platform?

"Windows 10 Pro x64"

Detailed Specification:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎2/‎2022
OS build	19045.3570
Experience	Windows Feature Experience Pack 1000.19052.1000.0

Device name	DESKTOP-VTFP7TF
Processor	Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz   3.50 GHz
Installed RAM	4.00 GB (3.88 GB usable)
Device ID	8FA44CA1-0346-46CB-AAA6-A69D16D52706
Product ID	00331-10000-00001-AA584
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### How did you install Java?

Vs Code 

### Did it work before?

```Shell
Don't know
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffca4d5b926, pid=5304, tid=4704
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (17.0.8.1+1) (build 17.0.8.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (17.0.8.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x6ab926]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: --add-modules=ALL-SYSTEM --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable -javaagent:c:\Users\coer\.vscode\extensions\redhat.java-1.23.0-win32-x64\lombok\lombok-1.18.30.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\coer\AppData\Roaming\Code\User\workspaceStorage\2fbc6c1e9dd55bdd2202c0cf41356f97\redhat.java -Daether.dependencyCollector.impl=bf c:\Users\coer\.vscode\extensions\redhat.java-1.23.0-win32-x64\server\plugins\org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar -configuration c:\Users\coer\AppData\Roaming\Code\User\globalStorage\redhat.java\1.23.0\config_win -data c:\Users\coer\AppData\Roaming\Code\User\workspaceStorage\2fbc6c1e9dd55bdd2202c0cf41356f97\redhat.java\jdt_ws

Host: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz, 4 cores, 3G,  Windows 10 , 64 bit Build 19041 (10.0.19041.3570)
Time: Wed Oct 25 15:10:45 2023 India Standard Time elapsed time: 3644.905209 seconds (0d 1h 0m 44s)
```

**Comment by karianna** [comment]
Java 19 is no longer supported, please use 21.0.1 - I'm not sure what you're saying is a bug here either?
