### ISSUE TITLE
Bad Request while installing temurin-11-jdk on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by whatdoidonow** [adoptium/adoptium-support#933]
## Question
I was following the instructions on page https://adoptium.net/en-GB/installation/linux/.
I got to the last point where you do (in my case)
```
sudo apt install temurin-11-jdk
```
I'll paste the output of that, shall I?
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  adoptium-ca-certificates fonts-dejavu-extra java-common
Suggested packages:
  default-jre
The following NEW packages will be installed
  adoptium-ca-certificates fonts-dejavu-extra java-common temurin-11-jdk
0 to upgrade, 4 to newly install, 0 to remove and 0 not to upgrade.
Need to get 168 MB/170 MB of archives.
After this operation, 332 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-11-jdk amd64 11.0.21.0.0+9
  400  Bad Request [IP: 146.75.75.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0+9_amd64.deb  400  Bad Request [IP: 146.75.75.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Annoyingly, I can wget perfectly the file it is complaining about: 'https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0+9_amd64.deb'. But that doesn't help because I don't know what apt would have done with it, had it been able to get it.

## Context

Java version: java isn't installed

Your operating system and platform: Ubuntu 20.04.6 LTS on a VM running on Windows 11 Pro through Hyper-V.

Regards, Michael

**Comment by jzaers** [comment]
Same problem with Ubuntu 22.04.3 LTS

**Comment by RusovDmitriy** [comment]
https://packages.adoptium.net/ui/native/deb/pool/main/t/temurin-11

You can use the following workaround by specifying a particular version, for example

apt install temurin-11-jdk=11.0.20.1.0+1

**Comment by Ribesg** [comment]
Same here for Ubuntu 20.04.6 and temurin-17-jdk

```
Err:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-17-jdk amd64 17.0.9.0+9
  400  Bad Request [IP: x 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0+9_amd64.deb  400  Bad Request [IP: x 443]

```

**Comment by MiguelEXE** [comment]
Same here on Debian bookworm

**Comment by karianna** [comment]
Hi folks, we're aware of the issue and are investigating with our CDN and package repo providers.

**Comment by proofrock** [comment]
Of the 3 I tried, JDK 11 and 21 work for me (connecting from Italy), JDK 17 doesn't. Take your time, just thought you may want to know.

**Comment by jzaers** [comment]
Cool. It is working fo rme again (Ubuntu 22.04 temurin-jdk-11). Thx.

**Comment by Ribesg** [comment]
Can confirm, fixed for me too. Ubuntu 20.04.6, temurin-17-jdk.

**Comment by whatdoidonow** [comment]
Fortunately, it is fixed for me too. 😊 Thank you very much.
