### ISSUE TITLE
DocFetcher Pro Crashes without reason report

### ISSUE THREAD

**Issue by Melmac-ALF** [adoptium/adoptium-support#934]
### Please provide a brief summary of the bug

DocFetcher Pro will start to index a file tree that has worked on the previous computer. Without any warning or entry into event viewer, the program shuts down. When reopening, only get the broken index issue. I have attached the log file below as it is above my IT knowledge to decipher.

[hs_err_pid22824.log](https://github.com/adoptium/adoptium-support/files/13192861/hs_err_pid22824.log)

### Please provide steps to reproduce where possible

This is reproducible on the machine whenever trying to get it to run a new index.

### Expected Results

Expected results is for the indexing to run without any java failure or crash.

### Actual Results

Software crashes without report. Only have the attached log file to view.

### What Java Version are you using?

1.8.0_391

### What is your operating system and platform?

Windows 10 Build 19045

### How did you install Java?

Binary Archive

### Did it work before?

```Shell
It was working for a little while but the failure was before the most recent update.
```

### Did you test with the latest update version?

```Shell
Done
```

**Comment by karianna** [comment]
Please update to the last 11.0.21 and post back here if it still occurs.

**Comment by Melmac-ALF** [comment]
I have updated to 11.0.21 and am still experiencing the same issue.

**Comment by karianna** [comment]
can you fire through the latest error log please

**Comment by Melmac-ALF** [comment]
[hs_err_pid21812.log](https://github.com/adoptium/adoptium-support/files/13194067/hs_err_pid21812.log)

**Comment by karianna** [comment]
@Melmac-ALF - That logs says you're using an Old AdoptOpenJDK 11.0.12 binary.  Try Eclipse Temurin 11.0.21
