### ISSUE TITLE
SIGSEGV errors using jfr

### ISSUE THREAD

**Issue by socar-brad** [adoptium/adoptium-support#941]
### Please provide a brief summary of the bug

I uses JFR profiling in production by DataDog Continuous Profiler.
But there are several SIGSEGV errors in two weeks.

### Please provide steps to reproduce where possible

It runs in a kubernetes environment on x86-64 and is using version 17.0.9.

### Expected Results

There are no SIGSEGV errors using JFR.

### Actual Results

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
exec java -ea -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ExitOnOutOfMemoryError -Dlogging.config=/app/conf/logback.xml -Dspring.profiles.active=prod -javaagent:/app/dd-java-agent.jar -Ddd.profiling.jfr-template-override-file=minimal -Xmx2048m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:CICompilerCount=2 -cp .:/app/* kr.socar.server.ServerApplicationKt
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007fd90884d898]
#
#   https://github.com/adoptium/adoptium-support/issues
# If you would like to submit a bug report, please visit:
#
# /app/hs_err_pid1.log
# An error report file with more information is saved as:
#
# JFR recording file will be written. Location: /app/hs_err_pid1.jfr
#
# Core dump will be written. Default location: /app/core.1
#
# V  [libjvm.so+0xbaaf53]  Method::bcp_from(unsigned char*) const+0x3
# Problematic frame:
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
#
#  SIGSEGV (0xb) at pc=0x00007fd908088f53, pid=1, tid=215
#
# A fatal error has been detected by the Java Runtime Environment:
```

### What Java Version are you using?

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9) OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 22.04 on x86-64

### How did you install Java?

I uses [17-jre-jammy docker image](https://hub.docker.com/layers/library/eclipse-temurin/17-jre-jammy/images/sha256-ff7a89fe868ba504b09f93e3080ad30a75bd3d4e4e7b3e037e91705f8c6994b3).

**Comment by karianna** [comment]
@socar-brad This will need to be reported to the Datadog folks in the first instance.  can you also post /app/hs_err_pid1.jfr?

**Comment by socar-brad** [comment]
I ran the app on k8s. But I haven't configured copying hs_err_pid1.jfr, core dump and logs. So these files were lost.

**Comment by karianna** [comment]
@socar-brad OK, you'll need to recreate it and send the details to Datadog in the first instance.

**Comment by socar-brad** [comment]
Thank you~ After gathering detailed logs and jfr, I'll recreate it. And send the details to DataDog.
