### ISSUE TITLE
I can't connect my Mapple Mini to the Arduino

### ISSUE THREAD

**Issue by pumassaurorex** [adoptium/adoptium-support#942]
I have a maple mini stm32f103CBT6 and I'm trying to connect it to the Arduino but an error always appears, I followed the entire Rogerclark tutorial,I'm a layman and this is my first time trying to use these boards
If I made a mistake in any other part of the tutorial please tell me, the maple appears as a USB serial device (com13)

the error in question is

```
maple_loader v0.1
Resetting to bootloader via DTR pulse
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=664, tid=8048
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.1+12 (21.0.1+12) (build 21.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (21.0.1+12-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\xfly\Documents\Arduino\hardware\Arduino_STM32\tools\win\hs_err_pid664.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by karianna** [comment]
@pumassaurorex can you upload the C:\Users\xfly\Documents\Arduino\hardware\Arduino_STM32\tools\win\hs_err_pid664.log file?

Also the JSSC library is at version [2.9.5](https://github.com/java-native/jssc/releases/tag/v2.9.5) you might want to try upgrading from the 2.8 version you have.

**Comment by pumassaurorex** [comment]
I ended up managing to pass the code, I used maple for some time and soon after it started to present this problem, it turns on but it doesn't seem to recognize it, and then you move your hand under it, it stays with the light fixed, on top in any of the poles it doesn't do this, only underneath or on the PCB at the bottom

https://github.com/adoptium/adoptium-support/assets/97665703/4bf2c0bd-7a99-43ba-b31d-f8a381c05879
