### ISSUE TITLE
Problematic frame: # V  [libjvm.so+0x6d259b]  Dependencies::check_valid_dependency_type(Dependencies::DepType)

### ISSUE THREAD

**Issue by agilob** [adoptium/adoptium-support#945]
### Please provide a brief summary of the bug

JVM occasionally crashes when run with a chaotic agent changing class modifiers.

### Please provide steps to reproduce where possible

Sometimes crashes when running with an agent https://gitlab.com/agilob/java-agent-to-remove-class-modifiers

### Expected Results

No crash?

### Actual Results

Crash with hs_err file

### What Java Version are you using?

VM Temurin-21.0.1+12

### What is your operating system and platform?

amd64 ArchLinux 6.1.60-1-lts

### How did you install Java?

sdkman

### Did it work before?

```Shell
sometimes
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
Yes, never crashed with 11 or 17
```

### Relevant log output

```Shell
https://gitlab.com/agilob/java-agent-to-remove-class-modifiers/-/blob/main/hs_err_pid3804.log
```

**Comment by karianna** [comment]
@agilob chances are this is because you are performing some sort of illegal operation in the JVM by changing modifiers on the fly.  You can report this to bugs.java.com but this is not an Adoptium build issue.
