### ISSUE TITLE
SIGFPE libopenal.so

### ISSUE THREAD

**Issue by zoga-com** [adoptium/adoptium-support#947]
### Please provide a brief summary of the bug

From what I understand, sometimes the application crashes because of SIGFPE when the game accesses the openal library.

### Please provide steps to reproduce where possible

Since the problem was noticed only in Minecraft Java Edition 1.20.1, and only after updating the java version to 17.0.8+7 (it is possible that the problem is valid only for fedora 38/39, as the problem was reproduced only on it):
1. Install JDK 17.0.8+7
2. Install Minecraft 1.20.1
3. Change game worlds
4. With some chance the game will freeze and call SIGFPE

### Expected Results

The application should not crash.

### Actual Results

The app crashes.

### What Java Version are you using?

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### What is your operating system and platform?

Fedora 38 (and 39) on x86_64. kernel 6.5.10-300

### How did you install Java?

dnf 

### Did it work before?

```Shell
Before to upgrading openjdk (and temurin) to 17.0.8, the problem was not detected.
```

### Did you test with the latest update version?

```Shell
I'm using the latest version available for my system.
```

### Did you test with other Java versions?

```Shell
Yes, there is also a problem on Red Hat openjdk.
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x00007fa2dee458b4, pid=23744, tid=23745
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8+7 (17.0.8+7) (build 17.0.8+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (17.0.8+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libopenal.so+0x458b4]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/dima/Загрузки/PrismLauncher-Linux-Portable-6.0/instances/Fabulously Optimized(1)/minecraft/core.23744)
#
# An error report file with more information is saved as:
# /home/dima/Загрузки/PrismLauncher-Linux-Portable-6.0/instances/Fabulously Optimized(1)/minecraft/hs_err_pid23744.log
[thread 23857 also had an error]
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by grepwood** [comment]
>Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers"; often Minecraft crashes are caused by outdated graphics drivers
>In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
>If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

This isn't valid advice. I'm getting the same issue on Fedora 41 with OpenJDK 17 from RHEL, with the exact same Minecraft version. No such problems on Gentoo however.

**Comment by prufaraSS** [comment]
> You'll need to report this to the Prism launcher team. It's their binary that's crashing.

I'm trying building prism launcher against arch's official repository openal and aur's openal nothing helps

**Comment by prufaraSS** [comment]
here's the fix that worked
https://github.com/henkelmax/sound-physics-remastered/issues/143#issuecomment-1832844261

**Comment by grepwood** [comment]
@karianna thanks for the hint, I'll try to rebuild Prism from srpm.
@prufaraSS applying `ALSOFT_DRIVERS=pulse` to literally every process might not be wise. I'll try this with the stock binaries, but in a way that doesn't trespass on other processes.
