### ISSUE TITLE
C  [liblicensing.so+0x2a4d1]  boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>()+0x11

### ISSUE THREAD

**Issue by jincentos** [adoptium/adoptium-support#950]
### Please provide a brief summary of the bug

Hi
I'm running Centos7 in the virtual box. When I try to fire up a software application it crashes with this error message. I have attached the log file for your review.

Thanks
[error1.log](https://github.com/adoptium/adoptium-support/files/13363721/error1.log)

### Expected Results

The software application should fire up

### Actual Results

Crashed with error message

### What Java Version are you using?

JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08) Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode linux-amd64 compressed oops)

### What is your operating system and platform?

CentOS 7in Virtual box 7.0.12r159484 (Qt5.15.2)

### Did it work before?

```Shell
No, this is the first attempt
```

**Comment by karianna** [comment]
Please upgrade to Java 1.8.0_392 and report back here if you still get crashes.

**Comment by jincentos** [comment]
Thanks, Karianna. When I listed the available packages for Java, there is only 1.8.0.382.b05 and no 18.0.392! Is there any other way I can locate this version.

On a different note, I was also suggested to set the image configuration to a different virtualisation mode as the windows HyperV usage excludes anything better than SSE support. By doing this, I can have AVX/AVX2 become available in Centos 7 which can resolve this error. Please can you shed some light on this as well. Thanks

**Comment by karianna** [comment]
@jincentos Ah, you may not actually be using our Eclipse Temurin build in that case.  How do you get your OpenJDK today?
