### ISSUE TITLE
While executing openjdk build via makejdk-any-platform.sh script,we are getting following error on windows. Autoconf is not found on the PATH, and AUTOCONF is not set.

### ISSUE THREAD

**Issue by nehajm** [adoptium/adoptium-support#952]
Autoconf is not found on the PATH, and AUTOCONF is not set.
You need autoconf to be able to generate a runnable configure script.
Error: Cannot find autoconf
Error: No configurations found for C:/openjdk8/temurin-build/workspace/build/src.
Please run 'bash configure' to create a configuration

Please let me know any other info on this error

**Comment by karianna** [comment]
Are you running in cygwin or WSL?

**Comment by nehajm** [comment]
Using wsl

**Comment by karianna** [comment]
https://learn.microsoft.com/en-us/windows/wsl/setup/environment follow this guide for general advice on how to use WSL.  You'll need to install autoconf via the package manager.
