### ISSUE TITLE
DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US) broken in JDK 21.0.1

### ISSUE THREAD

**Issue by kwin** [adoptium/adoptium-support#953]
### Please provide a brief summary of the bug

The following code fails with JDK 21.0.1

```
DateTimeFormatter dateFormat = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US);
dateFormat.parse("11:00 AM");
```

with exception

```
java.time.format.DateTimeParseException: Text '11:00 AM' could not be parsed at index 5
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2108)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1936)
```

This works fine in 17.0.9

### Please provide steps to reproduce where possible

Just execute the following code and experience the exception

```
DateTimeFormatter dateFormat = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US);
dateFormat.parse("11:00 AM");
```

### Expected Results

This should parse just fine as in JDK17

### Actual Results

```java.time.format.DateTimeParseException: Text '11:00 AM' could not be parsed at index 5```

### What Java Version are you using?

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### What is your operating system and platform?

OS name: "mac os x", version: "14.1.1", arch: "aarch64", family: "mac"

### How did you install Java?

Manually from Installer provided by adoptium.com

### Did it work before?

```Shell
Yes
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
See above
```

**Comment by kwin** [comment]
Seems to be related to https://bugs.openjdk.org/browse/JDK-8304925 although I cannot believe this really was intentional. Strings with a non-breaking space in front of `am/pm` will probably never appear in reality.

**Comment by kwin** [comment]
Would be nice to get a fix for this in 21.0.2 but currently the fixed CLDR 44 is only contained in JDK 22 (https://bugs.openjdk.org/browse/JDK-8306116). I have not seen a backport or an update to 43.1 in JDK 21 yet.

**Comment by kwin** [comment]
Still not fixed in 21.0.2 (https://www.oracle.com/java/technologies/javase/21-0-2-relnotes.html). Can I ask you to request a backport to 21 as I don't have an account with bugs.openjdk.org?

**Comment by kwin** [comment]
I haven't tested to be honest, but I was assuming so given https://unicode-org.atlassian.net/browse/CLDR-16606 is fixed with 43.1 (and hopefully 44 as well).

**Comment by jerboaa** [comment]
I don't think there is anything to fix here in OpenJDK, but CLDR. The CLDR releases which OpenJDK consumes is at fault if anything. The upstream issue for this is:
https://unicode-org.atlassian.net/browse/CLDR-17324

The current work-around for JDK 21 users is to replace spaces with narrow non breaking space before parsing date strings:

```
jshell> import java.time.format.DateTimeFormatter; import java.time.format.FormatStyle;

jshell> DateTimeFormatter dateFormat = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US);
dateFormat ==> Localized(,SHORT)

jshell> dateFormat.parse("11:00 AM".replace(" ", "\u202F"));
$17 ==> {},ISO resolved to 11:00
```

**Comment by kwin** [comment]
Java 23 introduces lenient parsing: https://inside.java/2024/03/29/quality-heads-up/. For earlier versions there won’t be a fix

**Comment by jerboaa** [comment]
Thanks.

The JDK 23 CSR for lenient parsing has some details:
https://bugs.openjdk.org/browse/JDK-8324990

For JDK releases `N` where `19 < N < 23` one can use `-Djava.locale.providers=COMPAT` or replace spaces with `\u202F` (narrow non breaking space) prior to parsing:

```
$ cat Scratch2.java 
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Locale;
public class Scratch2 {
   public static void main(String[] args) throws Exception {
	 var dateString = "11:00 AM";
         var df = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US);
         var date = df.parse(dateString);
   }
} 
$ javac Scratch2.java
$ java -showversion Scratch2 
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
Exception in thread "main" java.time.format.DateTimeParseException: Text '11:00 AM' could not be parsed at index 5
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2108)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1936)
	at Scratch2.main(Scratch2.java:8)
$ java -Djava.locale.providers=COMPAT -showversion Scratch2 
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
Apr 16, 2024 11:38:42 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release
```

**Comment by karianna** [comment]
I'm closing this based on the conversation above, thanks folks!
