### ISSUE TITLE
how

### ISSUE THREAD

**Issue by ItWasHim808** [adoptium/adoptium-support#954]
### Please provide a brief summary of the bug

failed to launch client: Process exited with non-zero code: 7900

### Please provide steps to reproduce where possible

boot up on mac

### Expected Results

failed to launch client: Process exited with non-zero code: 7900

### Actual Results

failed to launch client: Process exited with non-zero code: 7900

### What Java Version are you using?

8 i think

### What is your operating system and platform?

mac os Ventura 13.6.1

**Comment by karianna** [comment]
@ItWasHim808 What version of our OpenJDK are you using and can you proviude the error log?
