### ISSUE TITLE
gh "Authorization required" when downloading via XDM download manager

### ISSUE THREAD

**Issue by goyalyashpal** [adoptium/adoptium-support#955]
## Question

https://adoptium.net/temurin/releases/?arch=x64&package=jdk&version=21

i was downloading the win (msi) build from above via XDM 2020 download manager, then at around 50% it started asking for github authorization - i tried refreshing link, regenerating link, but nothing worked

https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12

i have downloaded lots of just release packages from github before, and it worked flawlessly - it's first time facing such issue.

## Context

![image](https://github.com/adoptium/adoptium-support/assets/19423063/5c759ba1-0e48-42ac-9ca2-9a529819432d)

Java version: n/a

Your operating system and platform: Windows 10 22h2

**Comment by karianna** [comment]
The XDM installer is likely altering the request to the API.  Are you able
to manually download from the browser?

Cheers,
Martijn

**Comment by goyalyashpal** [comment]
> Are you able to manually download from the browser?

being on limited bandwidth, i didn't try. however, i have managed to finish the download somehow by repeated trials with clicking on cancel and opening the download page etc

**Comment by karianna** [comment]
You'll want to report this to the XDM installer folks either way :-).

**Comment by med-boubekri** [comment]
For anyone stumbling across this in the future, try to pause the download and refresh the download link (Go to main menu, right click the file, click "Refresh Link", this will send you to the source page, click the same download link as you did initially, a window will pop up stating the new link was accepted, then resume.)
