### ISSUE TITLE
Running the jar to receive dds data directly reports this error. Is it a memory issue with the jvm?

### ISSUE THREAD

**Issue by daishenglan** [adoptium/adoptium-support#957]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbc69b1c727, pid=196941, tid=197203
#
# JRE version: OpenJDK Runtime Environment (11.0.20.1+1) (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x188727]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /root/agent/core.196941)
#
# An error report file with more information is saved as:
# /root/agent/hs_err_pid196941.log
ModuleNotFoundError: No module named 'numpy'
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

### Expected Results

Start the project without reporting errors

### Actual Results

error

### What Java Version are you using?

openjdk version "11.0.20.1" 2023-08-24 OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

### What is your operating system and platform?

Ubuntu 20.04.6 LTS

**Comment by karianna** [comment]
Can you post /root/agent/hs_err_pid196941.log and also try 11.0.21?
