### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by kevinluo6191** [adoptium/adoptium-support#960]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x1967778d, pid=4072, tid=12292

JRE version: OpenJDK Runtime Environment Temurin-11.0.18+10 (11.0.18+10) (build 11.0.18+10)
# Java VM: OpenJDK Client VM Temurin-11.0.18+10 (11.0.18+10, mixed mode, serial gc, windows-x86)
# Problematic frame:
# C  [unicorn_java.dll+0xb778d]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

### Please provide steps to reproduce where possible

Well launch the software and that's it a lot of times

### Expected Results

normal operation

### Actual Results

[hs_err_pid4072.log](https://github.com/adoptium/adoptium-support/files/13463297/hs_err_pid4072.log)

### What Java Version are you using?

 OpenJDK Runtime Environment Temurin-11.0.18+10 (11.0.18+10) (build 11.0.18+10)

### What is your operating system and platform?

Win10 22H2 x64

### Relevant log output

[hs_err_pid4072.log](https://github.com/adoptium/adoptium-support/files/13463297/hs_err_pid4072.log)

**Comment by karianna** [comment]
@kevinluo6191 please try with 11.0.21 and send in a new crash log if it reoccurs
