### ISSUE TITLE
Is it possible to get more than 8GB heap memory size in a Windows PC with 32GB? 

### ISSUE THREAD

**Issue by vgpowered** [adoptium/adoptium-support#961]
### Please provide a brief summary of the bug

I am using Rapidminer 10.1 on a Windows 7 X64 PC but unfortunately one of my Rapidminer process is always out of memory. The maximun memory used by the Windows process (java.exe) related to that Rapidminer process is about 8GB and there is another 16GB windows memory available. Why Java is not able to increase the memory heap. Even I have tryed to increase memory heap using the command -Xmx16G to configure the JVM. What's going on?

### Expected Results

I assume that the Java system should be able to use all the available memory in the computer.

### Actual Results

Rapidminer says there is not enough memory to continue. But there is between 13GB and 16GB of available memory in Windows depending on the situation.

### What Java Version are you using?

11.0.16+8

### What is your operating system and platform?

Windows 7 Ultimate.

java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.16+8
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=Eclipse Adoptium
java.vendor.url=https://adoptium.net/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
java.vendor.version=Temurin-11.0.16+8
java.version=11.0.16
java.version.date=2022-07-19
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=Eclipse Adoptium
java.vm.version=11.0.16+8

### How did you install Java?

It was embedded with Rapidminer.

### Did it work before?

```Shell
Never with that process.
```

### Did you test with the latest update version?

```Shell
No
```

### Did you test with other Java versions?

```Shell
No
```

**Comment by karianna** [comment]
Please try with 11.0.21 and report back, alos please send in your full java command line.

**Comment by vgpowered** [comment]
Thank you Kariana, you helped us open our eyes. RapidMiner has two ways to start, one is through the program 'PapidMiner Studio.exe' and the other through a command file '.bat'. We can't know what the program is doing, but the command file contains all the information and we read it contents  the -Xmx4000m argument. This is the problem. Anyway, even changing that argument to -Xmx16000 the program fails. We use the VisualVM tool and it shows us that there should be a memory leak in the application.
It's time to complain to RapidMiner.
Maybe you see somethigs strange in the arguments line, this is 
-XX:+UseG1GC -XX:G1HeapRegionSize=32m -XX:ParallelGCThreads=3 -XX:InitiatingHeapOccupancyPercent=55 -Xms384m -Xmx4000m -Djava.net.preferIPv4Stack=true -Dsun.java2d.dpiaware=false -Djava.locale.providers=COMPAT -Djava.net.useSystemProxies=true --add-exports java.desktop/sun.awt.shell=ALL-UNNAMED --add-exports java.desktop/sun.swing=ALL-UNNAMED --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED --add-exports java.desktop/sun.lwawt.macosx=ALL-UNNAMED

Regards

**Comment by karianna** [comment]
@vgpowered - Make sure that flag is `-Xmx16000**m**` :-).  The rest of those settings look OK although I suspect they have tweaked the GC flags to try to combat that memory leak.
