### ISSUE TITLE
Status of arm32 support in Temurin

### ISSUE THREAD

**Issue by MDoswaldSchiller** [adoptium/adoptium-support#962]
What is the current status of Temurin releases for the arm32 Linux  platform?

According to the March 2023 Release Status (https://github.com/adoptium/adoptium/issues/218) issue, the binaries for the arm32 Linux platform could not be built for Temurin 20 due to a problem with the TCK test. It was noted, that it will be released at a later date, if this changes.

For the Temurin 20.0.x releases, the arm32 Linux platform binaries were then marked as 'not planned' in the Release Status issues (https://github.com/adoptium/adoptium/issues/224, https://github.com/adoptium/adoptium/issues/239).

For Temurin 21, the arm32 Linux binaries were then again marked as planned in the Release Status issue (https://github.com/adoptium/temurin/issues/8) but only the "jdk21 AQA" task was finished. The subsequent tasks are still marked as 'actively working on' and 'not yet started' respectively. My question about the state of the arm32 Linux platform in this issues remained unanswered.
For the Temurin 21.0.1 build, the arm32 Linux binaries were then again marked as 'not planned' (https://github.com/adoptium/temurin/issues/6)

The official "Supported Platforms" (https://adoptium.net/en-GB/supported-platforms/) page does not list arm32 Linux as a supported platform for Temurin 21. Does that mean that the support for arm32 Linux is now cancelled for future versions of Temurin and I need to switch to a different OpenJDK build that still supports that platform? Or do you expect to reintroduce support for arm32 Linux in the future?

**Comment by sxa** [comment]
This is still in discussion. As far as I know no other provider of java compliant openjdk runtimes have shipped a JDK21 (If you know of one, please let us know). It is also unclear at present how much support is being provided for this platform at the upstream openjdk project, which we depend on, for JDK21+.

For now we are still producing nightly builds, and there should be early access builds available for arm32 at https://adoptium.net/blog/2023/08/early-access-builds/

Out of interest is this for use on a 32-bit Raspbian distribution or something else?

**Comment by sxa** [comment]
> Bellsoft offers their Liberica JDK 21 (https://bell-sw.com/pages/downloads/#jdk-21-lts), which supports arm32. According to their website, their JDKs are verified by TCK, so I guess it is a compliant build.

Thank you - that's useful information - I hadn't spotted that Bellsoft had published one.

> We use Java on custom i.MX6 based devices in the medical space.
> So losing the possibility to update the JRE on these devices would be a shame.

Bear in mind that we do not plan to stop updating earlier versions of Temurin so you will still be able to get patches to the previous versions from us regardless of whether we ship a JDK21.

**Comment by andrew-m-leonard** [comment]
Following on from PMC discussion, arm32Linux will not be provided for Temurin jdk21+ releases.

**Comment by gounthar** [comment]
That's very sad, as `arm32` machines make good Jenkins agents. 🤷

**Comment by sxa** [comment]
@MDoswaldSchiller Just having a think around this - does your use case require a GUI? (Same question to @bbernhard ref https://github.com/adoptium/containers/issues/502#issuecomment-1953924555)

**Comment by MDoswaldSchiller** [comment]
@sxa Yes, my use case requires a GUI. We are using JavaFX for that, which we compile ourselves and generate a JRE using jlink which includes the JavaFX modules.

**Comment by bbernhard** [comment]
Many thanks for picking this issue up again! 

My use case doesn't require a GUI :)

**Comment by gounthar** [comment]
Neither does mine. 🤷

**Comment by theofficialgman** [comment]
hoping this decision gets reversed

**Comment by karianna** [comment]
See https://github.com/adoptium/adoptium.net/pull/3104

**Comment by tinspin** [comment]
For anyone looking for a solution:

https://download.bell-sw.com/java/23.0.2+9/bellsoft-jdk23.0.2+9-linux-arm32-vfp-hflt.tar.gz
https://download.bell-sw.com/java/21.0.6+10/bellsoft-jdk21.0.6+10-linux-arm32-vfp-hflt.tar.gz

**Comment by tlf30** [comment]
Can this be revisited? 
Bellsoft has not released 32bit arm builds for JDK 24 or 25. 
Many modern embedded arm systems still use 32bit arm, and I am in need of upgrading my currently LTS build to JDK 25, but am working on embedded systems that still use arm32.

**Comment by tinspin** [comment]
Apparently they are looking for commercial incentives to do this.

Patience is our virtue OR we just have to roll up our sleeves and compile it ourselves.

I might do this later if the priority becomes high enough.
