### ISSUE TITLE
JRE crashes

### ISSUE THREAD

**Issue by cppandasm** [adoptium/adoptium-support#966]
### Please provide a brief summary of the bug

---------------  S U M M A R Y ------------

Command Line: -Xms512m -Xmx8192m -Dplugin.jar.repository=/opt/hp93000/soc/pws/plugins/jar_repository -D93k.temp_dir=/var/opt/hp93000/soc/tmp/93k.RHZ7wo -D93k.debug=no -DHP83000_DISPLAY=:1 -DHP83000_ROOT=/opt/hp93000/soc -Dsun.java2d.pmoffscreen=true -Djstart.port=51519 -Dsun.java2d.xrender=false com.guify.framework.app.Dispatcher -port 51519

Host:
[timeout occurred during error reporting in step "printing summary machine and OS info"] after 30 s.

------ Timeout during error reporting after 120 s. ------

### Expected Results

No crash

### Actual Results

If there are some limitation, should inform users, not just silently crashed

### What Java Version are you using?

Temurin-17.0.6+10

### What is your operating system and platform?

redhat 3.10.0-1160.el7.x86_64

**Comment by karianna** [comment]
@cppandasm please try with 17.0.9 and report back here if there is still a crash
