### ISSUE TITLE
jdk-8166197 backport to jdk8, jvm hang on g1 full gc work threads in offer_termination with high cpu usage

### ISSUE THREAD

**Issue by wanshiliuyun** [adoptium/adoptium-support#971]
## Question
will jdk-8166197 back port to jdk8 and have a plan?
https://github.com/openjdk/jdk9/commit/7e084fd81fc5ef3e8245dc2381d4f13c016746c5
we meet the same bug, jvm hang on g1 full gc work threads in offer_termination with high cpu usage
platform: AArch64

## Context

Java version:
jdk8u382-b05 AArch64

Your operating system and platform:
ky10 on aarch64

**Comment by karianna** [comment]
You'll need to ask that question on the OpenJDK jdk8u-dev mailing list (go to openjdk.org and follow your nose).  That issue is no longer listed in the bug tracker.

**Comment by wanshiliuyun** [comment]
> You'll need to ask that question on the OpenJDK jdk8u-dev mailing list (go to openjdk.org and follow your nose). That issue is no longer listed in the bug tracker.

ok，i will try.
Thanks for your reply.
