### ISSUE TITLE
Fatal error detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by RubyDuby99** [adoptium/adoptium-support#974]
### Please provide a brief summary of the bug

I use a software called Open LCA which utilizes Java to run. Recently, every time I try to do a calculation using Open LCA, it crashes and I get a text file in the Open LCA folder providing information on the error. In the text file, it shows the following text

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe67ab2af1, pid=6664, tid=3144
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [mkl_avx2.2.dll+0x2382af1]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

What can I do in this case

### Expected Results

I expected for the software to run and to provide calculations 

### Actual Results

The software crashed instead and gave a text file 

### What Java Version are you using?

(17.0.5+8)

### What is your operating system and platform?

Windows 10 , 64 bit Build 19041 (10.0.19041.3636)

### How did you install Java?

It was automatically installed with the Open LCA software.

**Comment by karianna** [comment]
Please upgrade to 17.0.9 and report back here with a new crash log.

**Comment by swavyast** [comment]
[hs_err_pid6012.log](https://github.com/adoptium/adoptium-support/files/13906516/hs_err_pid6012.log)
[replay_pid6012.log](https://github.com/adoptium/adoptium-support/files/13906517/replay_pid6012.log)

**Comment by karianna** [comment]
@swavyast You'll want to report this to the Eclipse IDE project.  Its their internal JDT compiler crashing.
