### ISSUE TITLE
missing TLSv1.2 ciphers

### ISSUE THREAD

**Issue by bdh8** [adoptium/adoptium-support#975]
## Question

When making https connections to some services, connections are refused due to handshake failures as a result of the required TLSv1.2 ECDHE ciphers not being available from the JDK.  Specifically TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), but all other ECDHE ciphers are missing as well.

I am using the docker container from ortussolutions/commandbox:adobe2023-3.8.4 and making http calls from the Adobe ColdFusion server it has installed.

when starting the JVM with -Djavax.net.debug=ssl:handshake  the clientHello message contains "cipher suites": "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCAA), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]"

How might I configure the JVM to allow the ECDHE cipher suites for https TLS communication?
Example: "cipher suites":"[TLS_AES_128_GCM_SHA256(0x1301), TLS_AES_256_GCM_SHA384(0x1302), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(0xC02B), TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C), TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xC030), TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA9), TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA8), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(0xC013), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(0xC014), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035)]"

## Context

Java version:

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

Your operating system and platform:

UNIX 5.10.102.1-microsoft-standard-WSL2  (Docker desktop on Windows 10 64 bit)

**Comment by karianna** [comment]
As a workaround you can try the following:

To add support for the `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` cipher suite to your Java application, you need to ensure that both the Java runtime environment (JRE) or Java Development Kit (JDK) you're using supports this cipher suite, and that it is explicitly enabled in your application's configuration. Here's a general guide on how to do this:

### 1. Check Java Version

Ensure that you are using a version of the JRE or JDK that supports `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. This cipher suite is typically available in Java 7 and later versions. You can check your Java version by running:

```bash
java -version
```

### 2. Enable the Cipher Suite in Java

There are several ways to enable and prioritize this cipher suite in Java:

#### a. Java System Properties

You can set the `https.cipherSuites` and `jdk.tls.client.protocols` system properties. This can be done as command-line arguments when starting your Java application:

```bash
java -Dhttps.cipherSuites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.client.protocols=TLSv1.2 -jar your-app.jar
```

This sets the cipher suite for HTTPS connections and forces the use of TLS 1.2, where this cipher suite is supported.

#### b. Programmatically in Code

If you need finer control, or if you are writing a server application, you can set the cipher suite when creating SSL/TLS contexts:

```java
SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory.getTrustManagers(), new SecureRandom());
SSLSocketFactory ssf = sslContext.getSocketFactory();

HttpsURLConnection.setDefaultSSLSocketFactory(ssf);
```

And then set the cipher suite on the `SSLSocket` or `SSLEngine` instances:

```java
SSLSocket socket = (SSLSocket) ssf.createSocket(host, port);
socket.setEnabledCipherSuites(new String[] {"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"});
```

### 3. Test the Configuration

After enabling the cipher suite, it's a good practice to test your application to ensure that it's correctly negotiating the desired cipher suite. You can use tools like OpenSSL or online SSL testing services to verify the SSL/TLS configuration of your server.

### 4. Consider Server Configuration

If you are configuring a server application, ensure that the server's SSL/TLS configuration also supports and prioritizes `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. This depends on the server software you are using (like Apache Tomcat, Jetty, etc.).

### Note

- The exact method to enable and prioritize cipher suites can vary depending on the specific Java version and the application server or framework you are using.
- Always test in a development or staging environment before making changes to production systems.
- Stay informed about the latest security best practices and compliance requirements relevant to your application.

**Comment by bdh8** [comment]
Thankyou for your response.  I have tried adding the JVM args (as we are not able to modify the java code) you suggested: 

-Dhttps.cipherSuites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.client.protocols=TLSv1.2

But this results in an immediate error (no handshake is attempted):

javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
          at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)

So this would imply that the desired ciphers are not available on the system... How might I install them?

**Comment by bdh8** [comment]
This was indeed a problem with other software running on the server.  The tomcat server was being started with a flag that disabled ecc (-Dcom.sun.net.ssl.enableECC=false) that once we reverted allowed things to function as expected for us again.
