### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by VesterTop** [adoptium/adoptium-support#977]
### Please provide a brief summary of the bug

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1f3230fa31, pid=18955, tid=19035
#
# JRE version: OpenJDK Runtime Environment Temurin-16.0.2+7 (16.0.2+7) (build 16.0.2+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (16.0.2+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xca5a31]  PhaseIterGVN::add_users_to_worklist(Node*)+0x11
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

### Did you test with the latest update version?

```Shell
No
```

### Please provide steps to reproduce where possible

---------------  S U M M A R Y ------------

Command Line: -Xms8192M -Xmx8192M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 server.jar --nogui

Host: AMD Ryzen 9 3900X 12-Core Processor, 12 cores, 31G, Debian GNU/Linux 10 (buster)
Time: Thu Dec 14 21:59:40 2023 MSK elapsed time: 8735.202023 seconds (0d 2h 25m 35s)

---------------  T H R E A D  ---------------

Current thread (0x00007f1f2c97d980):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=19035, stack(0x00007f1ef0d16000,0x00007f1ef0e17000)]

### Expected Results

Fix

### Actual Results

No

### What Java Version are you using?

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7) OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

### What is your operating system and platform?

Debian 10

### How did you install Java?

wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && tar xf OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && rm OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && rm /opt/jdk-16.0.2+7 -rf && mv jdk-16.0.2+7 /opt

### Did it work before?

```Shell
wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && tar xf OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && rm OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz && rm /opt/jdk-16.0.2+7 -rf && mv jdk-16.0.2+7 /opt
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
?
```

**Comment by karianna** [comment]
16 is no longer supported, please move to 17.0.9
