### ISSUE TITLE
Certificate error from repository

### ISSUE THREAD

**Issue by secondvibe** [adoptium/adoptium-support#979]
### Please provide a brief summary of the bug

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from Adoptium: [Errno 256] No more mirrors to try.\nhttps://packages.adoptium.net/artifactory/rpm/amazonlinux/2/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - \"SSL certificate problem: certificate has expired\""}

### Expected Results

Successful install from repository.

### Actual Results

Certificate expired.

### What Java Version are you using?

NA

**Comment by secondvibe** [comment]
It was through yum install on a AL2 EC2 instance.

**Comment by karianna** [comment]
@secondvibe I just tried via my browser and my curl from my Mac OS X command line and the file is retrieved OK.  Are you missing some ca certs on your Linux system perhaps?  Might be worth updating the ca-certificates package.
