### ISSUE TITLE
"java.lang.VerifyError: Bad local variable type" when compiling release=9 and above

### ISSUE THREAD

**Issue by niloc132** [adoptium/adoptium-support#991]
### Please provide a brief summary of the bug

Using `javac` to compile a snippet of code apparently succeeds, but a VerifyError occurs when trying to run it. Using `java` to compile and run at once will result in the same error.

### Did you test with the latest update version?
Tested with jdk-21.0.1+12 (obtained from the release link above):
```Shell
/home/colin/tmp/jdk-21.0.1+12/bin/java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
```

### Please provide steps to reproduce where possible

Create a `.java` file with the following contents:
```
        boolean b;
        String test = ((((b = true) ? null : null) + "") + b);
```

For example, here is `Foo.java`:
```java
public class Foo {
    public static void main(String[] args) {
    }
    private void unused() {
        boolean b;
        String test = ((((b = true) ? null : null) + "") + b);
    }
}
```

Compile with javac, no errors/warnings
```shell
$ javac Foo.java
```

Run with java:
```shell
$ java Foo
```

### Expected Results

The program should complete with no output and no errors, since main is empty.

### Actual Results

```
Error: Unable to initialize main class Foo
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Foo.unused()V @0: iload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Foo' }
    stack: { }
  Bytecode:
    0000000: 1bba 0007 0000 4db1                    
```

### What Java Version are you using?

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### What is your operating system and platform?

Arch Linux on x86_64

### How did you install Java?

Directly downloaded and unpacked the linked tarball above, previously confirmed with java builds installed from the package manager.

### Did it work before?

```Shell
This code compiles (and can be invoked as well) with Java 8. Additionally, when `--release=8` is passed to `java`, warnings are emitted, but the compiled code has no errors when run:

$ /home/colin/tmp/jdk-21.0.1+12/bin/javac --release=8 Foo.java
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
$ /home/colin/tmp/jdk-21.0.1+12/bin/java Foo
$
```

Note also that disabling verification (while deprecated) allows the code to be used (thought the behavior is wrong), even if the "unused" method is actually used. Using the bytecode generated as above:
```
/home/colin/tmp/jdk-21.0.1+12/bin/java -noverify Foo
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

Changing Foo to actually use the output:

```java
public class Foo {
    public static void main(String[] args) {
        System.out.println(new Foo().unused());
    }
    private String unused() {
        boolean b;
        String test = ((((b = true) ? null : null) + "") + b);
        return test;
    }
}
```
```
$ /home/colin/tmp/jdk-21.0.1+12/bin/javac Foo.java
$ /home/colin/tmp/jdk-21.0.1+12/bin/java -noverify Foo
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
nullfalse
```
**Note that this output is incorrect, the expression `b = true` should evaluate before `b`, so the output should be `"nulltrue"`.**

Changed code still fails without `-noverify`:
```
$ /home/colin/tmp/jdk-21.0.1+12/bin/java Foo          
Error: Unable to initialize main class Foo
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Foo.unused()Ljava/lang/String; @0: iload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Foo' }
    stack: { }
  Bytecode:
    0000000: 1bba 001a 0000 4d2c b0                 
```

### Did you test with other Java versions?
Also tested with 11 and 17 builds:
```Shell
java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9)
OpenJDK 64-Bit Server VM (build 11.0.21+9, mixed mode)
```
```
java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+8)
OpenJDK 64-Bit Server VM (build 17.0.9+8, mixed mode)
```

### Relevant log output

```Shell
Error: Unable to initialize main class Foo
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Foo.unused()V @0: iload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Foo' }
    stack: { }
  Bytecode:
    0000000: 1bba 0007 0000 4db1
```

**Comment by karianna** [comment]
@niloc132 - Have you posted this to the OpenJDK mailing lists?  If not I can point you to the likely one (if this is a bug its an OpenJDK one in general and not just Eclispe Temurin)

**Comment by karianna** [comment]
> Sorry, I had understood that starting at one of the distribution issue trackers made the most sense to validate that this is indeed a general OpenJDK issue and get it created there. Can you confirm that [discuss@openjdk.java.net](mailto:discuss@openjdk.java.net) is the correct list to start on, or is there a more appropriate place to submit this as a bug?

All good!  Actually if you can try your code sample on another vendor's OpenJDK (like Azul Zulu) to confirm its a broader issue then I think the right place to go is:

https://mail.openjdk.org/mailman/listinfo/compiler-dev

**Comment by jerboaa** [comment]
verifier issues - not sure if it's javac or the verifier - need to go to hotspot-dev or hotspot-runtime-dev (or at least cross-post):

https://mail.openjdk.org/pipermail/hotspot-runtime-dev/
https://mail.openjdk.org/pipermail/hotspot-dev/

**Comment by jerboaa** [comment]
FWIW, I've tried with a Fedora build:

```
$ /usr/lib/jvm/java-21-openjdk/bin/java -showversion Foo
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (Red_Hat-21.0.1.0.12-4) (build 21.0.1+12)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.1.0.12-4) (build 21.0.1+12, mixed mode, sharing)
Error: Unable to initialize main class Foo
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Foo.unused()Ljava/lang/String; @0: iload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Foo' }
    stack: { }
  Bytecode:
    0000000: 1bba 001a 0000 4d2c b0                 

```

And a recent JDK 23 build from upstream:

```
bin/java -showversion Foo
openjdk version "23-internal" 2024-09-17
OpenJDK Runtime Environment (fastdebug build 23-internal-adhoc.sgehwolf.jdk-jdk)
OpenJDK 64-Bit Server VM (fastdebug build 23-internal-adhoc.sgehwolf.jdk-jdk, mixed mode, sharing)
Error: Unable to initialize main class Foo
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Foo.unused()Ljava/lang/String; @0: iload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Foo' }
    stack: { }
  Bytecode:
    0000000: 1bba 001a 0000 4d2c b0                 
```

I'll file an upstream bug for this.

**Comment by jerboaa** [comment]
Upstream bug: https://bugs.openjdk.org/browse/JDK-8323657

**Comment by niloc132** [comment]
The upstream bug was fixed (though not backported I believe), so perhaps this can be closed? I'm not sure what the policy is.

**Comment by karianna** [comment]
Yes although there are no backports to 8/11/17/21
