### ISSUE TITLE
Some binaries missing in release jdk-17.0.9+9 that got added in jdk-17.0.9+9.1

### ISSUE THREAD

**Issue by sebkur** [adoptium/adoptium-support#994]
## Question

I'm maintaining a tool for packaging JVM applications and it uses Adoptium releases to package the applications. Users of the tool can configure an Adoptium release to package their applications with. I have built the tool such that it accepts a single version such `17.0.6+10` and expects to find binaries for each platform such as Windows, macos, Linux with the respective architecture suffixes at `https://github.com/adoptium/temurin17-binaries/releases/download/[version]/[filename]`. This has been working OK for a while in the past, but now with `jdk-17.0.9+9` it seems no Windows artifacts have been released and then `jdk-17.0.9+9.1` looks like it adds the missing binaries. However our algorithm for determining the exact path to retrieve the binaries from the web is not working as it doesn't include any logic for this kind of situtation. My questiones are:
* is there any place such as a release notes statement somewhere where I can learn about a specific release, which OS's are supported by it etc?
* Is it generally a naive assumption that a release usually includes binaries for all OS's and architectures and should I foresee such situations in the future (by making it possible to specify a specific JVM version per OS) or is generally a good assumption?
* If the 9.1 release was just made to add the missing Windows files, is there maybe any URL that redirects the missing `jdk-17.0.9+9` files to the `jdk-17.0.9+9.1` ones? maybe my approach of retrieving the binaries from that location mentioned above is not the recommneded one?

**Comment by smlambert** [comment]
https://adoptium.net/blog/2023/11/eclipse-temurin-8u392-11021-1709-and-2101-available/ mentions the Windows binary respin, but this likely doesn't help your automation story.  

In the future, there will likely be cases, though we hope will not happen often, where a respin is needed, and we produce a dot release for particular platforms.  

https://github.com/adoptium/api.adoptium.net/issues/829 discusses the challenge from the API perspective somewhat.

**Comment by sebkur** [comment]
Thanks for the explanation. I think I'll just add some kind of mapping to the tool that lets it know how to map exceptional versions such as this one to the appropriate URLs.
